### PR TITLE
BassBooster Redesign

### PR DESCRIPTION
**Pull request by Umcaruje**
Per #2978 and #2831

Screenshot:
screenshot from 2016-08-20 15 10 26

@RebeccaDeField

### CODE REVIEW

**Comment by tresf** [comment]
This is already merged but may also be a good time to standardize the way these are displayed, e.g `Stereo<space>Matrix` vs. `Bass<no space>Booster`

**Comment by grejppi** [comment]
👍 for `Bass Booster`

**Comment by Umcaruje** [comment]
Sorry if I merged too quickly, it was a pretty straightforward design change, and Rebecca +1'd it.

I agree on standardizing the plugin names, and Give my vote to `Bass Booster`.

We also ought to consider standardising the plugin folder names. e.g. `CamelCase` vs `snake_case`: `LadspaEffect` vs `ladspa_browser`

I'd vote for `CamelCase`, to be consistent with the rest of the software.

**Comment by simonvanderveldt** [comment]
@Umcaruje is the plugin name standardisation still something you/LMMS wants to do?

Because that should be a relatively straightforward change that I could create a PR for to get my feet wet with the code :)

**Comment by Umcaruje** [comment]
>@Umcaruje is the plugin name standardisation still something you/LMMS wants to do?

>Because that should be a relatively straightforward change that I could create a PR for to get my feet wet with the code :)

@simonvanderveldt Yeah, its something desirable, so if you're up to it, that would be helpful. Note that if you also want to standardize the folder names, you'll need to write some project upgrade procedures, which should probably be straightforward. 

That, said, welcome aboard, all help is really appreciated, also if you have some problems, don't be afraid to ask :smile:

**Comment by simonvanderveldt** [comment]
> @simonvanderveldt Yeah, its something desirable, so if you're up to it, that would be helpful. Note that if you also want to standardize the folder names too, you'll need to write a project upgrade procedure, which should probably be straightforward.

Perfect, I've created #3055 to track this.
I'll have to see about the folder names and migration, not sure if I'm up for that already ;)


> That, said, welcome aboard, all help is really appreciated, also if you have some problems, don't be afraid to ask 😄

Thanks! Happy to help! :)
I'll probably drop by on IRC with some questions.

**Comment by Umcaruje** [comment]
>Thanks! Happy to help! :)
>I'll probably drop by on IRC with some questions.

Well, I mostly hang out on our discord server, which I find more usable than IRC because you can share images and have code snippets: https://discord.gg/5kSc32Z

**Pull request merged**
