### PR TITLE
Adds Project Version check when loading

### PR DESCRIPTION
**Pull request by Spekular**
Implements #432. Currently displays a warning when the project is from a newer *or* older version, rather than just when it is newer. @diizy what do you think?

### CODE REVIEW

**Comment by Spekular** [comment]
Alright, tested, detects older and newer versions properly and displays a dialog. @tresf @diizy any comments?

**Comment by tresf** [comment]
Only major+minor versions should be checked, not bugfix.

Furthermore, you can really simplify that into a single "version mismatch" dialog and simply change the word older/newer, it will be cleaner code.

-Tres

**Comment by tresf** [comment]
Also, we should be verbose about which versions here..   i.e. If someone reads 1.1.0 > 1.0.0, that illustrates a different severity than 1.1.0 > 0.4.13.

-Tres

**Comment by Spekular** [comment]
@tresf I've changed it so when LMMS_VERSION != root.attribute( "creatorversion" ) it should show:
```
QMessageBox::information( NULL,
				SongEditor::tr( "Project Version Mismatch" ),
				SongEditor::tr( "This project was created with "
						"LMMS version " + 
						root.attribute( "creatorversion" ) +
						", but version" + 
						LMMS_VERSION +
						"is installed."			).
```
But I'm still getting the "this project was created with a newer version" message. I must be compiling wrong. I guess I'll work on it later.

**Comment by grejppi** [comment]
"Mismatch" sounds pretty harsh. Also, I wonder if this is necessary for minor versions at all...

**Comment by tresf** [comment]
> I wonder if this is necessary for minor versions at all...

FYI - Minor is 1.0 vs 1.1.  Patch is 1.0.0 vs. 1.0.3.

> I've changed it so when LMMS_VERSION != root.attribute( "creatorversion" )

This is how I did it for the themes directory.... 

https://github.com/LMMS/lmms/pull/1442/files#diff-0

> "Mismatch" sounds pretty harsh.

Perhaps... we can use Newer/Older, I just don't see the purpose of having the MessageBox code twice when one word was changing, that was really the point. :+1:

**Comment by tresf** [comment]
@Spekular I had forgotten you won't have MAJOR/MINOR versions in the MMPZ.  Since this is for MAJOR + MINOR, I'd recommend you do some parsing to determine those... 

We do read this in the LSP now per https://github.com/LMMS/lmms.io/commit/d9b53d48c82869d1febbf852de4538fe7ea95a67 but we didn't parse out the MAJOR + MINOR from it.

**Comment by grejppi** [comment]
@tresf
> FYI - Minor is 1.0 vs 1.1. Patch is 1.0.0 vs. 1.0.3.

I mean exactly that.

**Comment by diizy** [comment]
On 01/02/2015 02:24 PM, grejppi wrote:
>
> @tresf <https://github.com/tresf>
>
>     FYI - Minor is 1.0 vs 1.1. Patch is 1.0.0 vs. 1.0.3.
>
> I mean exactly that.
>

Well, minor versions matter too if the user tries to open a too new file
(1.1 file in 1.0, for example). They probably don't matter in the other
direction that much though.

**Comment by Spekular** [comment]
@tresf this part?
```
+		if (($project_data = read_project($rs['id'])) != null) {
+			echo "<b>LMMS Version:</b>&nbsp;" . $project_data->attributes()['creatorversion'];
+		}
```
I'm a bit confused as to what needs changing. Should I be reading the project file version differently? currently I just use `root.attribute( "creatorversion" )`.

**Comment by tresf** [comment]
Creator version will look like this:
```
1.0.3
```

Major/minor will look something like this:
```
1.0
```

You will want to compare against `MAJOR_VERSION + "." + MINOR_VERSION`, which will require you to split `"1.0.3"` on `"."` and take the 0th and 1st elements prior to comparing.

-Tres

**Comment by Spekular** [comment]
@tresf @diizy still having issues with the problem from my previous post. Any clue what I should do?

**Comment by tresf** [comment]
Is there something wrong with your code?  I don't see string concatenation, was it stripped out when you copied and pasted?

**Comment by tresf** [comment]
Also our constants are defined in header files which need to be included to be recognized within the code.  I haven't checked, but that is a good place to double-check as well.

**Comment by Spekular** [comment]
There's no concatenation. In the other qMessagebox in DataFile there's just
quotation marks around the string on each line and it works fine. When I
added "+" between the lines it broke. I guess I should only have plusses
around 'root.get...'? I'll try that later. As for being recognized, the
same function is used in the if check so I have no idea why it wouldn't
work inside the if statement.

**Comment by Spekular** [comment]
@tresf Forgot to tagou in myprevious message. Anyways, adding "+" before and after "root.get..." gives ```
error: no matching function for call to ‘SongEditor::tr(const QString)’
       " is installed."   ).
```

**Comment by tresf** [comment]
I just realized you are using a numeric operator to compare strings.  Don't do that lol.

-Tres

**Comment by softrabbit** [comment]
There's a ProjectVersion class in the sources for comparing project versions, maybe extend that with a looser comparison function?

**Comment by diizy** [comment]
The problem is, if you concat char* with QString, the result is a QString, and IIRC tr() takes char* as argument.

**Comment by tresf** [comment]
> There's a ProjectVersion class in the sources for comparing project versions, maybe extend that with a looser comparison function?

Thanks @softrabbit!

Yeah, perhaps we split `compare()` out into `compareMajor()`, `compareMinor()`, `comparePatch()`, etc. as the logic is all right there.

```cpp
ProjectVersion projVer = new ProjectVersion(root.attribute( "creatorversion" ));
ProjectVersion softVer = new ProjectVersion(LMMS_VERSION_MAJOR + "." + LMMS_VERSION_MINOR);

// compareMinor() is hypothetical... it doesn't exist yet :)
if ( softVer.compareMinor(projVer) != 0) 
{
	// Do something
}
```

**Comment by tresf** [comment]
So compare() is only really intended for the `<` operator, which is really where this `ProjectVersion` class seems to have left off.

This is a bit out of my comfort zone, but I've expanded the class a bit to make the `MAJOR`, `MINOR`, `RELEASE` and `BUILD` values within our project files parseable (I'm actually using the same parse logic, just retaining the values).

Please see #1582.  A second set of eyes on this is greatly appreciated.

**Comment by tresf** [comment]
So I've put some more though into this and I think @softrabbit's subclass idea is a great approach.

What I'm confused about is how I could achieve it without making a brand new header and CPP file.  Is that something you could help me with?

**Comment by Spekular** [comment]
@tresf why subclass? Wouldn't it be simpler to create new functions
instead. Like compareMajor(), compareMinor() so on? Am I missing something?
(probably)

**Comment by Spekular** [comment]
@tresf Ugh. I converted creatorversion to a char* and stored it in avariable called cVersion, but when I use cVersion in the message text I get an error. The code:
```
char* cVersion = root.attribute( "creatorversion" ).toLocal8Bit().data();
		QMessageBox::information( NULL,
				SongEditor::tr( "Project Version Mismatch" ),
				SongEditor::tr( "This project was created with "
						"LMMS version "
						cVersion
						", but version " 
						LMMS_VERSION
						" is installed."			).
```
The error:
```
/home/spekular/Spekular-LMMS/src/core/DataFile.cpp:785:7: error: expected ‘)’ before ‘char’
       char* cVersion
       ^
/home/spekular/Spekular-LMMS/src/core/DataFile.cpp:780:9: error: unused variable ‘cVersion’ [-Werror=unused-variable]
   char* cVersion = root.attribute( "creatorversion" ).toLocal8Bit().data();
```
Yes, I do use that variable, right there in that message text where you refuse to cooperate...

**Comment by softrabbit** [comment]
You can't concatenate strings like that. `cVersion` is a variable, not a literal like all the other strings in there. And besides, even if that worked it wouldn't be wise to feed the resulting string to `tr()`. You'd then need a separate translation for every possible version. And what's with the period at the end? `).`

**Comment by Spekular** [comment]
@softrabbit Alright, so how should I concatenate them? And should I end the tr before the creator version and start a new one afterwards? As for the period,it was there in the other message box in DataFile.

**Comment by tresf** [comment]
> @tresf why subclass? Wouldn't it be simpler to create new functions instead. Like compareMajor(), compareMinor() so on? Am I missing something? (probably)

No, you are somewhat correct.  (This answer also addresses @softrabbit's response).

The problem is that a standard `compare()` function in all object oriented languages is a built-in Object function which can be used for comparison such as sorting or greater than/less than operations.

In the case of `ProjectVersion`, the original author (Javier Serrano Polo) overrode the `<` operator so that the operation `"1.0.10" > "1.0.3"` could happen.

We can write helper functions but they convolute the original intention of `compare()` and they also take away the convenience and readability of the `<` operator.  Does that make sense?

So, to do this properly, we have two choices.... 

 1. Subclass `ProjectMinorVersion`
 2. Pass in an enumerated flag to tell `ProjectVersion` to stop comparing when it reaches `m_minor`.

Since I've never done nested subclassing in C++, I'll work on option No. 2. :smile_cat:

**Comment by tresf** [comment]
> how should I concatenate them

@Spekular, See here, which uses `%` and `.arg(...)` to achieve variable replacement in the translation: [`LadspaSubPluginFeatures.cpp#L57`](https://github.com/LMMS/lmms/blob/master/plugins/LadspaEffect/LadspaSubPluginFeatures.cpp#L57)

**Comment by softrabbit** [comment]
@spekular, something like this should get you closer to the goal:
```SongEditor::tr( "This project was created with "
                        "LMMS version %1, "
                        "but version %2 "
                        "is installed.").arg( cVersion ).arg(LMMS_VERSION);```

Will have to get back to this later, have to run...

and

**Comment by tresf** [comment]
> Will have to get back to this later, have to run...

:rabbit2: --> :laughing:

**Comment by Spekular** [comment]
Well this is embarrassing. The extra ```.``` was part of ```arg( _sourceFile )```, which I'd left in. The dialog I copied used the exact method you guys just described and I didn't realize :(

**Comment by Spekular** [comment]
The message box works perfectly now (thanks guys!) but the version checking only works for mmp files (not mmpz) and still takes into account patch versions.

**Comment by tresf** [comment]
> but the version checking only works for mmp files 

Then you are doing something wrong.  The file format shouldn't matter. You might just have your code in the wrong place.

**Comment by tresf** [comment]
> Now I know why I needed to check out LMMS/lmms.io@d9b53d4

Ignore that please.  That was only for reference as something I had done recently involving versions. It doesn't really apply to MINOR version checking.

**Comment by Spekular** [comment]
@tresf in the commit you referenced the filetype is checked and if it's an
mmpz it gets decompressed. I assumed I needed to do this as well. In fact
qUncompress is used elsewhere in DataFile.cpp so I'm pretty sure I do.

**Comment by tresf** [comment]
> @tresf in the commit you referenced the filetype is checked and if it's an
mmpz it gets decompressed. I assumed I needed to do this as well. In fact
qUncompress is used elsewhere in DataFile.cpp so I'm pretty sure I do.

I know what you are thinking.... But dont.  Don't worry about compression, the software is already decompressing (how else would we be able to open an mmpz?) :)

-Tres

**Comment by tresf** [comment]
@Spekular please take a look at the updated #1582 (not yet merged) which supports `Major`, `Minor`, and `Release` comparisons now with the `>` and `<` sign.

**Comment by Spekular** [comment]
@tresf sure!

**Comment by Spekular** [comment]
@tresf Comparing "Minor" compares Major + Minor version, right? So I would do something like:
```
ProjectVersion LMMSV = new ProjectVersion( LMMS_VERSION, Minor );
ProjectVersion CV = new ProjectVersion( root.attribute( "creatorversion" ), Minor );
if (LMMSV != CV){
//message
}
```

**Comment by tresf** [comment]
> Comparing "Minor" compares Major + Minor version, right?

Exactly.  P.S. Don't use caps for a variable, you'll get slapped. :laughing:

**Comment by tresf** [comment]
Also, you don't need to cast both to `ProjectVersion` types.  It will take the comparator from either side if specified.

I've written all comparators on all sides that we should need per per [`ProjectVersion.h#L85`](https://github.com/tresf/lmms/blob/master/include/ProjectVersion.h#L85)  (This means you can put `char *`, `QString &` or `ProjectVersion &` on either side of the `==`, `!=`, `<`, `>`, etc).

**Comment by tresf** [comment]
> This means you can put char *, QString & or ProjectVersion & on either side of the ==, !=, <, >



Sorry, forgot to specify... so as long as you have at least one `ProjectVersion` in the comparison. :)

**Comment by Spekular** [comment]
Yeah I know, camelCase, but I needed to write quick names and was just
following the style of  LMMS_VERSION. That's a constant though which is
probably why its caps.
On Jan 12, 2015 3:30 PM, "Tres Finocchiaro" <notifications@github.com>
wrote:
>>
>> This means you can put char *, QString & or ProjectVersion & on either
side of the ==, !=, <, >
>
> Sorry, forgot to specify... so as long as you have at least one
ProjectVersion in the comparison. :)

**Comment by tresf** [comment]
> following the style of  LMMS_VERSION. That's a constant though which is probably why its caps.

:smile:

**Comment by Spekular** [comment]
@tresf did I say something funny? :P
On Jan 12, 2015 7:59 PM, "Tres Finocchiaro" <notifications@github.com>
wrote:
>>
>> following the style of LMMS_VERSION. That's a constant though which is
probably why its caps.

**Comment by tresf** [comment]
> @tresf did I say something funny? :P

:rooster: 

I'm almost ready to merge the ProjectVersion stuff... just want another day or so for comments/concerns.

**Comment by Spekular** [comment]
Closing. I've gotten so behind on my already messy fork that dealing with syncing it up would probably end in me losing my progress. Rather than rushing to make a new one I'll take my time and set it up properly this time, so don't expect a new pr until at least tomorrow.

**Comment by tresf** [comment]
Fair enough.  FYI, the ProjectVersion stuff is live in master, so you can use that for your `<`, `>` comparisons. :+1:

**Pull request closed without merging**
