### PR TITLE
If using Qt5, use Qt5LinguistTools to locate lupdate/lrelease

### PR DESCRIPTION
**Pull request by thothonegan**
When compiling master with Qt5, it wouldn't locate lupdate or lrelease, failing the build. Added Qt5LinugistTools so the qt5 versions are located properly.

Using: OpenSUSE 42.1

### CODE REVIEW

**Comment by tresf** [comment]
@thothonegan Thanks.

Unfortunately, this patch breaks builds on our Ubuntu-based systems.

https://travis-ci.org/LMMS/lmms/jobs/107331393#L1658

Once this is resolved, we'll happily merge.

**Comment by tresf** [comment]
**Edit:** @thothonegan if this package is available for Ubuntu, this may be as simple as adding `qttools5-dev` to the [travis install script](https://github.com/LMMS/lmms/blob/master/.travis/linux..install.sh#L8)... 

```diff
-	PACKAGES="$PACKAGES qtbase5-dev"
+ 	PACKAGES="$PACKAGES qtbase5-dev qttools5-dev"
```

**Comment by thothonegan** [comment]
Not sure where to add it in the wiki - the Qt5 section doesnt really cover the dependencies (though i could add a section with the ones currently in Travis). Added to the build though, needed both qttools5-dev-tools and qttools5-dev (one provides lupdate and friends, the other provides the cmake script to locate it).

**Comment by tresf** [comment]
> Added to the build

:+1: 

> i could add a section with the ones currently in Travis

Done via [`45b9b1f`](https://github.com/LMMS/lmms/wiki/Compiling-lmms/45b9b1f8f8e3492d879a047e61aaab79f0220f56)

**Pull request merged**
