### PR TITLE
Envelope time modifier

### PR DESCRIPTION
**Pull request by zonkmachine**
envelope

Just some things I've wanted to test since https://github.com/LMMS/lmms/pull/411
Also in response to issue https://github.com/LMMS/lmms/issues/3223
I think It's a good idea to make dangerously long envelopes a conscious decision. 

I never liked the  0 - 2.0 value for the envelope times. This fixes it right up and instead adds a check box to turn on longer envelope times.

#### TODO
 * The upgrade path isn't 'tuned in' just yet.
 * The check box context menu lacks a 'help' button which this knob would benefit from.
 * One could also scrap the check box and just tweak the knob value range to 0 - 1.0 .

@jasp00 You suggest here to make the envelope knobs response linear. If this is still a plan now would probably be a good time.
https://github.com/LMMS/lmms/blob/master/src/core/EnvelopeAndLfoParameters.cpp#L407

### CODE REVIEW

**Comment by zonkmachine** [comment]
I bump the buffer amount to 1024. It's the fastest way to reduce the risk of running out of buffers like in https://github.com/LMMS/lmms/issues/3223 . You could go higher but there is a time penalty to it. I haven't looked at precisely how much the cost in CPU cycles is to do this. From my testing, pretty much negligible.

**Comment by jasp00** [comment]
> You suggest here to make the envelope knobs response linear. If this is still a plan now would probably be a good time.

It is still a plan because it is an optimization to avoid the calculations from `expKnobVal()`; for a (-1.0, 2.0) range, it means to switch to (-1.0, 4.0) and upgrade old data. This can be done in a different PR.

>I never liked the 0 - 2.0 value for the envelope times. This fixes it right up and instead adds a check box to turn on longer envelope times.

Then the knob is probably not the proper widget.

**Comment by Jousboxx** [comment]
I think I have found a bug: When I open a project file that was made using normal master LMMS, the envelopes on my instruments are way too long. I tried a few different project files and I've seen this behavior on all of them. When I made a project using my build of this pull request, it saved and reopened properly. Here's links to a video of this behavior and the MMPZ. 

https://drive.google.com/open?id=0B8dZ3IVOKKA6VXN2aTdzT0JkSGc

lmms.io/lsp/?action=show&file=10488

Interesting feature, could be very useful :)

**Comment by grejppi** [comment]
The choice between 1x and 5x feels arbitrary to me. What if it was an LCD spin box with a range of 1-5 instead?

**Comment by zonkmachine** [comment]
I'm closing for the time being.

**Comment by zonkmachine** [comment]
PS. Thanks for the reviews.

**Pull request closed without merging**
