### PR TITLE
Proposed fix 710

### PR DESCRIPTION
**Pull request by curlymorphic**
proposed fix for #710 save as new version format.

Simple followed instructions in #710

### CODE REVIEW

**Comment by tresf** [comment]
Thanks for taking charge of this Dave.  I assume you tested it which is what we really needed.  Merging.

**Comment by badosu** [comment]
@tresf I tested it:

2015-01-27-162552_307x74_scrot

Thanks @curlymorphic!

**Comment by tresf** [comment]
:+1:

**Comment by Sti2nd** [comment]
If the picture is correct you tested it wrong @badosu . You must test with spaces, minus signs is already implemented.

**Comment by badosu** [comment]
@Sti2nd Thanks for the observations, just tested again and it works as well:

2015-01-27-164828_222x38_scrot

**Comment by Sti2nd** [comment]
:+1:

**Comment by tresf** [comment]
@Sti2nd I noticed that too however he represented regression testing which is just as important, so I didn't say anything... :sweat_smile:

**Pull request merged**
