### PR TITLE
No "tb303" only "TB-303" 

### PR DESCRIPTION
**Pull request by JGHFunRun**
Specifically in the plugin description

### CODE REVIEW

**Comment by JohannesLorenz** [comment]
I think the other TB303 should be changed to TB-303, too :smiley:

**Comment by JGHFunRun** [comment]
Agreed, I will get on that now

**Comment by JGHFunRun** [comment]
That should do it

**Comment by JohannesLorenz** [comment]
There are still a lot of issues, can you `git grep -i tb.*303` in the top of your LMMS source folder? If not, I'll dump you the list.

**Comment by JGHFunRun** [comment]
Good idea

**Comment by JGHFunRun** [comment]
Should I be worried about how long it's taking to `grep`?

**Comment by JGHFunRun** [comment]
@JohannesLorenz you mind sending that list?

**Comment by JGHFunRun** [comment]
Alright that should do it

**Comment by JohannesLorenz** [comment]
I see 2 more in lb302.h, but those should be the last ones...

**Comment by Spekular** [comment]
LGTM once the two instances of "TB303" Johannes mentioned are adjusted as well, should be safe to squash and merge after that since this only touches comments and user facing strings.

https://github.com/LMMS/lmms/blob/54bee2272e10af303eaa659f5a76f9119d0ea671/plugins/lb302/lb302.h#L3-L11

**Comment by JGHFunRun** [comment]
Done! Not sure how I missed it. I think I took a break and forgot lol

**Comment by JohannesLorenz** [comment]
Then it should be ready to merge now. However, since I have this open PR #6350 which renames 100s of files :smiling_face_with_tear: , including these lb302 files, I'd really like to ask to get mine merged before this, since it's probably easier to fix a merge conflict in a smaller PR.

**Comment by JGHFunRun** [comment]
I see your PR is a draft, it's minor enough that I'm willing to wait the time but if yours is just renaming the files I touched wouldn't it be just a matter of making it still rename the file? Then again I have no idea how to fix merge conflicts

**Comment by JGHFunRun** [comment]
I see your PR is a draft, it's minor enough that I'm willing to wait the time but if yours is just renaming the files I touched wouldn't it be just a matter of making it still rename the file? Then again I have no idea how to fix merge conflicts

**Comment by JohannesLorenz** [comment]
@JGHFunRun Which operating system do you use? If it's Linux, I guess it should be easy to do fix the merge conflict on your side. If it's Windows, I probably can't help you with the merge conflict, so I could merge yours first.

**Comment by JohannesLorenz** [comment]
Never mind. I merge your PR before mine and try to deal with the conflicts.

**Pull request merged**
