### PR TITLE
Update fr.ts

### PR DESCRIPTION
**Pull request by trebmuh**
+ a few new translations + a few typos + French consistency (capital letters + space before punctuation).

### CODE REVIEW

**Comment by Umcaruje** [comment]
Hi, I'm sorry, but we moved to transifex to manage our localisations. https://www.transifex.com/lmms/lmms/ 

@liushuyu can we accept this PR and will transifex get updated or will the OP need to go there and make an account to update the localisation?

**Comment by liushuyu** [comment]
>@liushuyu can we accept this PR and will transifex get updated or will the OP need to go there and make an account to update the localisation?

No, this will confuses translation synchronise bot and de-synchronise translations. Maybe we can manually upload the file to Transifex.

**Comment by Umcaruje** [comment]
Ok, I'll close this then. 

P.S. can you please update https://github.com/LMMS/lmms/wiki/Creating-a-localization to reflect that we're using transifex now to handle our localisations.

**Comment by liushuyu** [comment]
>P.S. can you please update https://github.com/LMMS/lmms/wiki/Creating-a-localization to reflect that we're using transifex now to handle our localisations.

Okay, and hope someone can review my work after finishing the job :smile:

**Comment by Umcaruje** [comment]
@trebmuh you'll need to manually upload this file to transifex for this localisation to get accepted. Please coordinate with @liushuyu about that. Even though the PR is closed, you can still communicate here.

**Comment by trebmuh** [comment]
@Umcaruje : thanks.
@liushuyu : would you mind merging this PR to transifex? I've got no account on it and am not planning to get one.

**Comment by liushuyu** [comment]
@trebmuh Okay

**Comment by trebmuh** [comment]
@liushuyu : sweet. Thanks. Please let me know when it's done, then I can delete my branch.

**Comment by liushuyu** [comment]
>@liushuyu : sweet. Thanks. Please let me know when it's done, then I can delete my branch.

Done.
Current progress of French (fr): 91% complete, 531 words (192 strings) remaining

**Comment by trebmuh** [comment]
Thank you very much @liushuyu

**Comment by liushuyu** [comment]
>Thank you very much @liushuyu

You're welcome. We're looking forward to your further brilliant contributions! :+1:

**Comment by trebmuh** [comment]
I'm happy to keep on progressing towards a better FR translation. So what is the best workflow for someone not going/willing to use transifex ? I think it certainly depend on how often the transifex file is merged back to the github repo. Could you please tell me how often is that done please?

One thing is that it does look that your move to transifex is pretty recent. Being new to LMMS contributions, I didn't see when it happened and I'd like to read at the discussion(s) which has(ve) been leading LMMS to this decision. Would you please have a link(s) for that?

**Comment by liushuyu** [comment]
>Could you please tell me how often is that done please?

Not too often, the merge backs are managed by a bot. The bot will synchronize the translation when Transifex signals it. Transifex only signals it when one language reaches 100% complete. So this is not too often. But despite this, manual jobs are mainly committed by me, which is more often than the bot sometimes.

>Would you please have a link(s) for that?

Maybe you wonder why this platform is used. The talk was at #2676 .

**Comment by trebmuh** [comment]
Thanks, #2676 was exactly what I was looking for.

@liushuyu : if I understand correctly (tell me if I'm wrong here) : the bot will synchronize to the transifex's translation when transifex signals the translation as 100% complete or you will synchronise this file to github manually yourself. Is that correct?

**Comment by liushuyu** [comment]
> the bot will synchronize to the transifex's translation when transifex signals the translation as 100% complete or you will synchronise this file to github manually yourself. 

Nearly. But when ransifex signals the translation as 100% complete, the bot will download files from Transifex and commit the translations to GitHub. My manual work is needed when new strings appear or there are some mistakes that need to correct asap.

**Comment by trebmuh** [comment]
OK, that means that in this workflow, the most updated translation files are the one from transifex, not the one on github. So if I would want to continue working on LMMS french translation (I've got already a few typos, some new translations that I spotted on, and one really-very-incorrect-translations-leading-to-misunderstanding), how can I fetch the transifex version without being subscribed/logged-in transifex? I can't see nothing to do so here : https://www.transifex.com/lmms/lmms/ ...

**Comment by liushuyu** [comment]
>how can I fetch the transifex version without being subscribed/logged-in transifex?

Unfortunately, Transifex doesn't allow anyone who doesn't login to download translations. But maybe I can help you in some ways. (In fact, you can login with your GitHub account)

**Comment by trebmuh** [comment]
My concerns are mainly:
1) privacy (login in with github gives my email address)
2) relevancy of making the way of translating too much easy, then anyone can commit a translation without testing it and that can lead to bad translation (I know this is arguable because it allows for more contributors to jump in ... but still, I'm really not convinced)
Anyway, to find a way of improving LMMS French translation, I've got a few questions:
- is there another current FR translator ? Maybe I could link with him then.
- is it possible/doable for you @liushuyu to "freeze" the FR translation for the time I'm working on, then there is no overlap of work ?
Let me know what are your tought.
Cheers

**Comment by liushuyu** [comment]
>My concerns are mainly:

I respect your choices ;-) 

>is there another current FR translator ? Maybe I could link with him then.

The answer is yes. There are two other translators: @midi-pascal and @ycollet . Maybe they can help you.

>is it possible/doable for you @liushuyu to "freeze" the FR translation for the time I'm working on, then there is no overlap of work ?

It's possible to freeze the translation, but I don't think it would be a good way. Modern translation platforms can handle translation conflict very well. In addition, other translators may also double check your translations to increase the accuracy .

**Comment by trebmuh** [comment]
Sweet, I know @ycollet and eager to know @midi-pascal , salut !
Are you guys currently working on translating or is it free for me to squash a bunch of translations now?

**Comment by ycollet** [comment]
Hello,

You can change the translation, if it's for the good of lmms ... :)

YC

**Comment by midi-pascal** [comment]
@trebmuh  Hello Olivier,
You are welcome to enhance the French translation of LMMS.
I did some work on this a year ago because the translation was not even half done and there were problems in the code so some literals were not extracted for translation.
I fixed  what I could but has not been able to finish it 100%.
So, go for it! :+1:

**Comment by trebmuh** [comment]
Sweet thanks to both of you @ycollet and @midi-pascal for the quick answers!
@liushuyu : what's the best way for me to grab the state-of-the-art fr.ts file? Please advise.

**Comment by trebmuh** [comment]
@liushuyu : I've got now a locale 100% completed tr.ts file based on the tr.ts file released while on 1.1.3 release. I guess I need to merge it to the current fr.ts file. Could you please send it to me or post it somewhere on the web then I can grab it? Thanks.

**Comment by liushuyu** [comment]
Since you don't want to leak your email address, I will upload the current
file to somewhere. Wait a moment, thx.

**Comment by trebmuh** [comment]
Thanks @liushuyu , file grabbed. I'll let you know when I'm done with updating it.
All the best

**Comment by trebmuh** [comment]
Thanks @liushuyu , file grabbed. I'll let you know when I'm done with updating it.
All the best

**Comment by trebmuh** [comment]
@liushuyu please find the fr.ts file 100% completed here : http://download.tuxfamily.org/librazik/volatile/LMMS%20translation%20complete%2020160608%20fr.ts 
Can I ask you to test if it build correctly since I've not dive into building lmms from git yet and I'm going out of my keyboard for the next 5 or 6 days? I hope the file to be correct and I already checked usual typo, but we never know.
All the best

**Comment by liushuyu** [comment]
>Can I please ask you to test if it build correctly before merging it since I've not dive into building lmms from git yet and I'm going out of my keyboard, travelling for the next 5 or 6 days? 

I guess you edited the translations with plain text editor, for the XML structures were broken and couldn't compile. But I have fixed the broken structures that for you as many as possible. The fixed version is here: https://mega.nz/#!iRtEQRJa!lq4wv-zj1iAuhNYG4J9zfNGSgnsivW7Fuspv1YmH-uE
And there are some strings that remain untranslated and some of the translated strings emitted warnings during the check.

Below goes the problems: [The line numbers are based on the fixed version]
```
Line 4633:     No punctuation mark at the end of the translation
Line 4637:     No punctuation mark at the end of the translation
Line 4641:     No punctuation mark at the end of the translation
Line 4645:     No punctuation mark at the end of the translation
Line 5618:     No punctuation mark at the end of the translation

4064:        Unfinished translation
4072:        Unfinished translation
4076:        Unfinished translation
4080:        Unfinished translation
4084:        Unfinished translation
4088:        Unfinished translation
4092:        Unfinished translation
4096:        Unfinished translation
4100:        Unfinished translation
5604:        Unfinished translation
6675:        Unfinished translation
6679:        Unfinished translation
6683:        Unfinished translation
6687:        Unfinished translation
9215:        Unfinished translation
```

**Comment by trebmuh** [comment]
Hi @liushuyu: yes I did edit it with a plain text editor (pluma). Thanks for your help with fixing stuffs and for the feedback above, here is the new version which is (hopefully) 100% completed: http://download.tuxfamily.org/librazik/volatile/LMMS%20translation%20complete%2020160614%20fr.ts

Can I ask you if there is an up-to-date on-line tutorial about how to build LMMS on GNU/linux (debian here) ?

**Comment by Umcaruje** [comment]
>Can I ask you if there is an up-to-date on-line tutorial about how to build LMMS on GNU/linux (debian here) ?

@trebmuh here you go: https://github.com/LMMS/lmms/wiki/Compiling-lmms

**Comment by liushuyu** [comment]
>Hi @liushuyu: yes I did edit it with a plain text editor (pluma). Thanks for your help with fixing stuffs and for the feedback above, here is the new version which is (hopefully) 100% completed: http://download.tuxfamily.org/librazik/volatile/LMMS%20translation%20complete%2020160614%20fr.ts

Okay, I verified and found your translation passed all the tests. :+1: 
Note: I don't speak French, so I cannot figure out the linguistic mistakes.

>Can I ask you if there is an up-to-date on-line tutorial about how to build LMMS on GNU/linux (debian here) ?

For Debian, maybe you can contact @jasp00 for help, since he also uses Debian and compiles LMMS.

**Comment by tresf** [comment]
> Can I ask you if there is an up-to-date on-line tutorial about how to build LMMS on GNU/linux (debian here) ?

Our tutorial is written for Ubuntu, but it's comprehensive enough for any platform, you'll just need to replace some of the package names with the Debian equivalent... 

https://github.com/LMMS/lmms/wiki/Compiling-lmms

**Comment by jasp00** [comment]
I have added some instructions for Debian in the tutorial.

**Comment by trebmuh** [comment]
Sweat. Thanks for that.

With this help, and with the debian packaging from the debian multimedia team, I've been successfully building a .deb for Debian Jessie from a git clone from this morning (ref: ecf9db6). Thanks to one of the last @liushuyu commit, I've got a LMMS running fully in french (almost fully actually).

@liushuyu: before continuing helping with the French translation, I've got (once again!) a question for you. I saw that you've been adding and removing some lines in the en.ts file with https://github.com/LMMS/lmms/commit/f7377b6ee75df7e255fae9802b7b1f0bdd510c30 and https://github.com/LMMS/lmms/commit/03eccc4ffb4fe5bf667e6d4dc29494355169e19c .
They doesn't look to be automatically added in the fr.tr (and other *.tr files). How do you envisage this process ? I'd suggest that the easiest way from a translator POV would be that all the *.tr files to be updated in the same time that the en.tr is. Doing that, LMMS is sure to keep up with consistency. Would that be possible and if so, would you envisage to do so ?

**Comment by trebmuh** [comment]
@liushuyu : ping ?

**Comment by liushuyu** [comment]
I'm very sorry for making you to wait for so long. I caught a bad cold
these days and I couldn't do anything but having rest.

>Thanks to one of the last@liushuyu <https://github.com/liushuyu> commit,
I've got a LMMS running fully in french (almost fully actually).

Congratulations on your contribution been accepted by both humans and bots
:smiley: And welcome to continue contribute to us.

>They doesn't look to be automatically added in the fr.tr(and other *.tr
files)

Because they shouldn't be merged automatically due to some concerns.

Now, I will explain this. At first, I felt like to work just like what you
suggested: when translation changes I will update all the translation
files. Then I found it very redundant, since (1) Transifex will update all
other language files when the source language file changes; (2) If one do
clone LMMS repository, he/she will be able to update on his/her own; (3)
Even one do not want to clone the whole repository, he/she can merge the
source language  file with the current translation file using Qt linguist
software; (4) The translation changes sometimes could be massive and would
enlarge the repository if all the translations are updated all together.

Sorry for the inconvenience, but I once thought you already used Qt
linguist software to edit the translations until I found the broken XML
structures.

I will update the translation wiki later when my health situation gets
better, so please wait a little bit patient. Thanks!

**Comment by liushuyu** [comment]
@trebmuh I am totally back now. And I came with an idea: I can set up a standalone repository for lmms translations only. I (or my bot) will update the repository regularly to ensure the translations are up-to-date.

Thank again! :+1:

**Comment by liushuyu** [comment]
@trebmuh Repository is up: https://github.com/liushuyu/lmms-translations

**Comment by liushuyu** [comment]
@trebmuh : Ping?

**Comment by trebmuh** [comment]
@liushuyu : oh sweet ! I didn't see you're previous message so thanks for having pinging me. I'll have a look to the lmms-translation repo. Sounds to be a great idea so far. I'll update you a little bit later.

**Comment by trebmuh** [comment]
@liushuyu : I did a pull request to make the French translation up to 100%

**Pull request closed without merging**
