### PR TITLE
Update Monstro.h

### PR DESCRIPTION
**Pull request by dnl-music**

### CODE REVIEW

**Comment by softrabbit** [comment]
You do know that you can just push more commits to the same branch and have them show up in the original pull request?

**Comment by dnl-music** [comment]
14.01.2015 18:12, Raine M. Ekman пишет:
>
> You do know that you can just push more commits to the same branch and 
> have them show up in the original pull request?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/LMMS/lmms/pull/1624#issuecomment-69907765>.
>
I did not realize how to do it.

**Comment by softrabbit** [comment]
Just checkout the same branch again, work on it and push. The exact push command depends on your setup, but it should be easy if you've followed this: https://github.com/LMMS/lmms/wiki/Submitting-a-patch

**Comment by diizy** [comment]
wait, you based these against master?

sigh...

**Comment by dnl-music** [comment]
15.01.2015 21:09, Vesa V пишет:
>
> wait, you based these against master?
>
> sigh...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/LMMS/lmms/pull/1624#issuecomment-70099047>.
>
Well, let it be stable or something.

**Comment by badosu** [comment]
I don't understand these comments, do we have a guideline on where to base our feature branches/PRs?

I am asking this because I always base them against master, what is the other possibility?

**Comment by tresf** [comment]
@badosu you are fine.  This happens to be a specific bug that stable-1.1 could benefit from in the form of a patch release.  The items you have been working on have mostly been for stable-1.2 milestone.  Sometimes we cherrypick from master and bring it into to the patches.  This happens to be a good candidate for that.

When we released stable-1.0, we had many more bug reports surrounding its release, so this split was more apparent than it is today.  stable-1.1 has only had a handful of bugs and the author wasn't notified to switch branches until after the PR was made.

**Comment by badosu** [comment]
@tresf Gotcha, thanks for clarifying. :+1:

**Pull request merged**
