### PR TITLE
Organic tooltip fix

### PR DESCRIPTION
**Pull request by jackokring**
Hopefully this should fix an issue

### CODE REVIEW

**Comment by softrabbit** [comment]
This would look a lot better with the peak controller change in a separate PR.

**Comment by grejppi** [comment]
@jackokring Why are you messing with the peak controller anyway?

You're also basing this against `stable-1.1` which is no longer in development.

**Comment by jackokring** [comment]
I did a 

```git fetch upstream
git checkout master
git merge upstream/master
cp <changed file> <new loc>
git add ../
git commit
git push```

And err, the file has changed. eg. Engine => engine ... so I assume some file naming changes are happening. Will try when master more close to stable.

**Comment by jackokring** [comment]
The PR thing should really be possibly merged closer to fixing the TODO: ...

A common subroutine for a gating function?

**Comment by tresf** [comment]
> Will try when master more close to stable.

Please backup your changes and reset the master branch back to upstream status (try `git reset --hard HEAD~2; git push --force`)

Hand-commit the changes onto master's copy of `organic.cpp`.  We refactored too much to copy/paste between branches.  The branches aren't close enough to cherry-pick this particular commit.

But before you do that, clone your master branch and work from the clone.  An easy way to do this is to use the **Switch branch** dropdown on github, selected master.  Select it again, but instead of clicking one, type in a name such as `organifix`.

In regards to the commit, don't auto-commit your files, just `git add plugins/organic/organic.cpp; git commit; # etc...`.  If you insist on using auto-commit, move your build directory to `lmms/build` like the compilation instructions say so that it doesn't get picked up by version control.

**Pull request closed without merging**
