### PR TITLE
Protect reads to SampleBuffer with read locks

### LINKED ISSUE #2833: Triple_Oscillator  user-defined waveform selection during playback causes segfault.
### Running the current master branch on Ubuntu 16.04 ( 64bit )

* **Steps to reproduce** 

1. Open a new song.
2. Add a few notes into the default Triple_Osc Piano roll.
3. Start by pressing play in the piano roll ( playback will loop now as desired ).
4. Select the +icon in Triple_Osc ( "use a user-defined waveform for current oscillator" ).
5. Select any one of the default .flac files. << crash occurs

* note that this only seems to happen during playback.
* The bug is not specific to .flac files, crashes with .wav and .ogg also.
 * terminal output ( without GDB ) = Floating point exception (core dumped)

 * Full backtrace here http://paste.ubuntu.com/17147786/

### PR DESCRIPTION
**Pull request by jasp00**
This fixes #2833.

### CODE REVIEW

**Comment by Umcaruje** [comment]
I don't think something like this can be accepted to the code base, since we want RT-safety in the core, and avoid adding any more locks. Please read up #1744 #1747 for a PR that was rejected and then redone in an RT-safe way.

**Comment by tresf** [comment]
If my vote counts, `Stability > RT` but I'm interested in seeing this conversation mature as I'm not an expert on the topic.

**Comment by jasp00** [comment]
SampleBuffer already relies on read and write locks, see [`SampleBuffer::play`](https://github.com/LMMS/lmms/blob/master/src/core/SampleBuffer.cpp#L594). The proposed fix is in line with the current implementation.
If lockless operation is desired, SampleBuffer should work like the mixer deleting tracks in #2822. Adding notes, handling MIDI events, loading settings, etc. should work like that: signal the mixer and wait until changes in the model are allowed.

**Comment by Spekular** [comment]
@jasp00

>already relies on read and write locks

This might be true, but

>[we want to] avoid adding any more locks

**Comment by jasp00** [comment]
So, should I change the current operation of SampleBuffer and remove present locks?

**Comment by jasp00** [comment]
I have removed some locks, some more could be removed. Besides fixing #2833, some freezing introduced with #2822 is fixed. I will merge this soon (less than 24 hours), since projects cannot be loaded in the master branch.

**Comment by grejppi** [comment]
(Sorry for the noise; that was my phone thinking I pressed something instead of scrolling)

**Pull request merged**
