### PR TITLE
Revise README

### PR DESCRIPTION
**Pull request by regulus79**
The current state of README.md is a bit sub-par, and I think it could really use some revising.

## Critique
(some of these critiques are subjective; I don't mean anything against the person who originally wrote the readme, and I myself don't know if I could do much better)
- It mentions a competing DAW in the first sentence and describes LMMS as a free alternative to it. 
- The first paragraph is very informal (uses "you" quite a bit, along with the phrase "You can have fun...")
- Claims that LMMS is user-friendly and modern (The ui is great, but I wouldn't call it particularly user friendly atm)
- Flow could be improved ("to create music with your computer. **This includes...**" could be revised to be more direct)

I'm not saying that I am a good enough writer to fix the readme, but what I have in this PR is at least a start.

Please please please critique me and suggest edits.

### CODE REVIEW

**Comment by thismoon** [comment]
my following suggestions are mainly stylistic but i hope it is still relevant since we're discussing the readme file
- although the user interface is probably going to change (there are many issues opened about it) it would be nice to have screenshots in the readme to show what the program looks like
- no need for the "Share your songs!" line since "LMMS Sharing Platform" is clear enough and it's the only link with additional text
- remove "on our wiki for information on how to build LMMS." from the building section. pointing to a hyperlink is enough
- the logo and name aren't aligned. maybe make it centered using
```md
<div align="center">
    <h1><img src="https://raw.githubusercontent.com/LMMS/artwork/master/Icon%20%26%20Mimetypes/lmms-64x64.svg" alt="LMMS Logo"><br> LMMS</h1>
</div>
```

<details>
<summary>demonstration</summary>

image

</details>

or here's an idea of what the whole header could look like (more compact layout and simpler hyperlink labels)

<details>
<summary>codeblock</summary>

```markdown
<div align="center">
  <h1>
    <img
      src="https://raw.githubusercontent.com/LMMS/artwork/master/Icon%20%26%20Mimetypes/lmms-64x64.svg"
      alt="LMMS Logo"
    /><br />LMMS
  </h1>
  <p>Cross-platform music production software</p>
  <p>
    <a href="https://lmms.io/">Website</a>
	⦁︎
	<a href="https://github.com/LMMS/lmms/releases">Releases</a>
	⦁︎
	<a href="https://github.com/LMMS/lmms/wiki">Developer wiki</a>
	⦁︎
	<a href="https://lmms.io/documentation">User manual</a>
	⦁︎
	<a href="https://lmms.io/showcase/">Showcase</a>
	⦁︎
	<a href="https://lmms.io/lsp/">Sharing platform</a>
  </p>
</div>
```

</details>

<div align="center">
  <h1>
    LMMS Logo<br />LMMS
  </h1>
  <p>Cross-platform music production software</p>
  <p>
    <a href="https://lmms.io/">Website</a>
	⦁︎
	<a href="https://github.com/LMMS/lmms/releases">Releases</a>
	⦁︎
	<a href="https://github.com/LMMS/lmms/wiki">Developer wiki</a>
	⦁︎
	<a href="https://lmms.io/documentation">User manual</a>
	⦁︎
	<a href="https://lmms.io/showcase/">Showcase</a>
	⦁︎
	<a href="https://lmms.io/lsp/">Sharing platform</a>
  </p>
</div>

**Comment by regulus79** [comment]
I like it, very professional! I hope you don't mind me copying that and adding it to the PR

**Comment by Rossmaxx** [comment]
The new readme looks professional, better than what we had. I am not approving for now as there seems to be something missing.

**Comment by Rossmaxx** [comment]
I would like to get opinion on the new readme in this branch from someone with an eye for detail, @RoxasKH mind chiming in?

**Comment by FyiurAmron** [comment]
+1, definitely a move in the right direction. Even if not perfect, I see no risk by merging this as-is, worst case scenario the next editor will have an easier task.

**Comment by Rossmaxx** [comment]
@regulus79 you fine with merging this as is? If so, cam you either comment here, or mark it as ready, that way, i can hit merge.

**Review by Rossmaxx — APPROVED** [review]
Looks good, the readme.

**Comment by regulus79** [comment]
> you fine with merging this as is?

The readme could probably still use some work, but I agree with FyiurAmron, it's probably best to merge this now, otherwise it will never be finished (perhaps any further modifications can be done later).

**Comment by regulus79** [comment]
It appears the `man` page needs to be updated.

**Comment by Rossmaxx** [comment]
Updating the man page would be a part of the release cycle. If it's a part of the source tree, do it now.

**Pull request merged**
