### PR TITLE
Setup dialog improvements.

### PR DESCRIPTION
**Pull request by Sawuare**
**Chnages:**
• Improved code style.
• Improved translatable strings.
• Reordered everything.
• Divided the MISC tab into 2 tabs: GUI and Projects, and moved some of its items.
• Moved some items to more appropriate places.

**TODO:**
• Fix the position of the extras widget.
• Fix that some odd stuff are required to display the "Paths settings" label widget.
• Find the height for path selectors layout that fits 5 tabs perfectly.

There are 2 irrelevant commits in this PR: https://github.com/Sawuare/lmms/commit/9db830b1c32f78c3d0b4a6460180ba48a47d027d and https://github.com/Sawuare/lmms/commit/fbbcbffcd0f4bf5a12f2c2faa2af102010bcb7c0.

### CODE REVIEW

**Comment by Sawuare** [comment]
I messed some stuff up...
I will delete my fork and start a fresh one.
I have all of the changed source files backed up.

**Comment by PhysSong** [comment]
https://github.com/LMMS/lmms/compare/master...PhysSong:SDI_Sawuare?expand=1

**Comment by Sawuare** [comment]
@PhysSong 
Thank you for reverting the irrelevant commits!
I deleted my repo so this PR can't be reopened...
Could you open a new PR please?

**Comment by Sawuare** [comment]
Nvm, I will open a new PR. 👍

**Pull request closed without merging**
