### PR TITLE
New Organic Presets

### PR DESCRIPTION
**Pull request by YesImAsh**
Some New organic presets that i've been dying to add

easy to implement (hopefully)

### CODE REVIEW

**Comment by Rossmaxx** [comment]
It looks fine from diff and I usually welcome new contributions, but I can't judge if this is the way to add presets. As much as I would like to help you, my lack of clarity means I can't just hit the button. Once another dev says it's ok, I'll hit merge.

**Comment by Rossmaxx** [comment]
Another point which you might have heard from somewhere, Try to reduce effects used in the presets.

**Comment by YesImAsh** [comment]
but there's only 2 effects on average, and they're really important to sound. I wouldn't say they're drowning, they're just in shallow water

**Comment by Rossmaxx** [comment]
Ok then.

**Comment by YesImAsh** [comment]
besides, as long as i've shared my presets somehow, it should be fine

**Comment by michaelgregorius** [comment]
> but there's only 2 effects on average, and they're really important to sound. I wouldn't say they're drowning, they're just in shallow water

@YesImAsh, some of these effects cannot be found when opening the presets with a recent LMMS build. It seems that they are effects that are not shipped with LMMS?

**Comment by YesImAsh** [comment]
> Contributor

i did not think this through 💀

**Pull request closed without merging**
