### PR TITLE
Fixed #3443. Added and fixed mixer automation labels.

### LINKED ISSUE #3443: Mixer solo and mute automations have empty label
If you connect mixer mute or solo button to automation track it's label is empty.
Right click and disconnect option shows also "".
All other automation connections show something like "BitInvader>Volume" or "Amplifier>>Panning".

### PR DESCRIPTION
**Pull request by karmux**

### CODE REVIEW

**Comment by Umcaruje** [comment]
Changed the PR to address `stable-1.2`

**Comment by jasp00** [comment]
>Changed the PR to address `stable-1.2`

How does work flow? Another PR to `master`?

**Comment by Umcaruje** [comment]
The way this happened for 1.1 is that we had people just periodically merge the new changes in the `stable` branch back to master.

**Comment by tresf** [comment]
> How does work flow? Another PR to `master`?

No, the admins generally handle this by doing occasional (e.g. weekly) syncs between `stable-1.2` and `master`.

**Pull request merged**
