### PR TITLE
Search Wine in the i386 multiarch directory

### PR DESCRIPTION
**Pull request by jasp00**
This allows CMake to detect i386 Wine on amd64 systems that do not have the unnecessary amd64 Wine. This scenario is possible in Debian.

### CODE REVIEW

**Comment by qnebra** [comment]
Maybe this will repair lmms compilation error with VST on my PC. Without checked wine/vst flags in CMake compilation works very fine, if they are checked configuration and generation works fine, but when lmms is install by "make install" installation stopped on approx. 85%, when vestige/vst was be installed.

**Comment by jasp00** [comment]
@qnebra, I doubt this patch will fix your problem. Make sure you have the `g++-multilib` package.

**Comment by qnebra** [comment]
@jasp00 of course I have g++-multilib package installed in my system.

**Comment by jasp00** [comment]
@qnebra, please open a new issue. Are you using Debian or Ubuntu? Run `make VERBOSE=1` and post the command.

**Comment by qnebra** [comment]
@jasp00 I compile lmms with your changed file, and I haven't any errors when vestige/vst is installed. DAW crashed on "add effect", but it's propably my failure.

**Pull request merged**
