### PR TITLE
Find vstbase library at runtime

### PR DESCRIPTION
**Pull request by jasp00**
The `NEEDED` entry was `../vst_base/libvstbase.so`. The library was searched in `../vst_base`, which is relative to the invocation directory. The patch sets the `RUNPATH` entry.

### CODE REVIEW

**Comment by tresf** [comment]
Seems to be bombing out with the changed linker command.

screen shot 2016-04-14 at 6 56 32 pm

**Comment by jasp00** [comment]
I will fix the win builds later (maybe tomorrow).

**Comment by liushuyu** [comment]
@jasp00 I think you can surround your new instructions with IF statements

**Comment by liushuyu** [comment]
>Might even help #1875.

Well, not work for me currently

**Comment by liushuyu** [comment]
>Might even help #1875.


**EDIT**: Even tried several machines/ different wine versions, still didn't work...
I may do more thorough tests soon.

**Comment by jasp00** [comment]
This will not fix #1875. This patch is necessary to make vestige appear in the list of instrument plugins in the first place. (3 patches more to go.)

**Comment by tresf** [comment]
If this patch is to fix a particular problem (e.g. #2724), you should append that to the PR description although it appears this is more about using the new `RPATH` search order syntax.

For readability we also require you to squash your commit history down into one, please.

As an FYI, dev's aren't notified when new patches are submitted to a particular PR, so you should get in the habit of bumping a PR when you've made new changes that require review. 👍

**Pull request closed without merging**
