### PR TITLE
Envelope Generator - Don't divide by zero

### PR DESCRIPTION
**Pull request by zonkmachine**
Some think it's rude so I cleaned up `EnvelopeAndLfoParameters.cpp`  a bit. I caught this because the new reverb went NaN and things shut down when I turned up the decay.
I made `const f_cnt_t minimumFrames` and didn't touch the knob values even though you could give them saner minimum values but you would still need to set some of the f_cnt_t variables in `EnvelopeAndLfoParameters::updateSampleVars()` so I went this way instead.

In the LFO `m_lfoAttackFrames` also use `minimumFrames`.

### CODE REVIEW

**Comment by zonkmachine** [comment]
> removed from In Progress in Release 1.2.0 RC3

Removing from RC3 project as this is nothing new and needs more time.

**Comment by Umcaruje** [comment]
@zonkmachine is this targeted for 1.2?

**Comment by zonkmachine** [comment]
> @zonkmachine is this targeted for 1.2?

No. I don't think we should do any changes for 1.2 concerning NaN's and 0 divisions etc. It's not one bug and it's not introduced in 1.2 . It sucks a bit but I won't have time to work on this now.

**Comment by zonkmachine** [comment]
> It's not one bug...

I had a second go at this as #3687 mad this so much easier. The ones in the envelope seems clearly defined and straight forward to just give a minimum frame of 0.

This one is ready to be merged into master. It should clear up a couple of the NaN oriented bugs for sure.
It also makes debugging with the new `WANT_DEBUG_FPE` flag more practical as you currently can't start lmms with any instruments because it will give a floating point error as soon as 
`EnvelopeAndLfoParameters::updateSampleVars()` is run.

**Comment by zonkmachine** [comment]
Some final adjustments. To test this commit I suggest compiling with and without `WANT_DEBUG_FPE` to see the difference.

I intend to merge this in a day.

**Pull request merged**
