### PR TITLE
Update ExprTk

### PR DESCRIPTION
**Pull request by ArashPartow**
- Moved submodule to release branch
- Release notes: https://www.partow.net/programming/exprtk/exprtk_release_notes_v0.0.3.txt

### CODE REVIEW

**Comment by Rossmaxx** [comment]
@gnudles if you don't mind, can you brief us about the effects of updating the submodule. I'm asking you because the rest of us are clueless about the xpressive plugin infrastructure.

**Comment by gnudles** [comment]
It is the under the hood engine that evaluates the expressions

**Comment by messmerd** [comment]
Are there any plans to try to cut down on the Xpressive/exprtk binary size?

In this PR it is 66.2 MB uncompressed on Linux, while on master it is currently 70.9 MB. That's a little better, but it's still by far the largest single file in the installation after the lmms executable itself. Plus it takes longer than the other plugins to compile.

**Review by messmerd — APPROVED** [review]

**Comment by ArashPartow** [comment]
@messmerd  a large proportion of that would be symbols et al that could be removed at least on linux builds using `strip. -s` 

```
-rwxr-xr-x 1 66209040 Nov 20 10:05 libxpressive.so
-rwxr-xr-x 1 10554912 Nov 20 10:06 libxpressive_stripped.so
```

**Comment by messmerd** [comment]
That's great to see! I'll look into stripping the binaries and using lld or mold.

**Comment by gnudles** [comment]
It's worth checking why the debugging symbols are there in first place.

**Pull request merged**
