### PR TITLE
Workaround Qt5 bug that fails to remove separator at end of File/Help menus

### PR DESCRIPTION
**Pull request by follower**
See #3345 for details.

### CODE REVIEW

**Comment by follower** [comment]
Note: I've only tested this fix on Qt5 + Mac OS X 10.8.x.

**Comment by tresf** [comment]
@follower thanks, your test results are sufficient.

I think your comment could be shorted some.

`Conditional compilation to workaround Qt5 bug` is redundant since you're using precompiler flags and the flag has Qt in the name.  I'd shrink it to simply:

```cpp
// Per https://bugreports.qt.io/browse/QTBUG-40071
```

Or if you prefer to leave an explanation:

```cpp
// remove dangling separator at end of menu per https://bugreports.qt.io/browse/QTBUG-40071
```

Also note that removing the specificity of `Quit` also allows others to copy and past this patch in other areas moving forward without fear of contextual comment typos.

**Comment by follower** [comment]
Thanks for the review.

I suspected I might get that feedback--I've never been accused of being excessively terse. :)

I can make the change as suggested but wanted to mention part of the motivation for the wording was to make it clear that it was the preprocessor conditional that was the workaround not the addition of the separator. I'd normally put the comment on the `#if` line but figured it'd make the line too long in this case.

Will go with:

    // Prevent dangling separator at end of menu per https://bugreports.qt.io/browse/QTBUG-40071

**Comment by follower** [comment]
Should now exclude Qt 5.6+. Tested with Qt 5.5.1.

**Comment by tresf** [comment]
@follower thanks!!!

**Pull request merged**
