### PR TITLE
Fix #5840

### LINKED ISSUE #5840: Song Editor - Pasting tco on first position
If you try and paste something to the first bar in the Song Editor it ends up on the second bar. This is a glitch that has been introduced after lmms-1.2 .

paste

#### Affected LMMS versions

master

### PR DESCRIPTION
**Pull request by Spekular**

### CODE REVIEW

**Review by IanCaio — APPROVED** [review]
LGTM!

You have to buy me a beer after such a long review :laughing:

**Comment by zonkmachine** [comment]
There's still odd things going on. I'll investigate this some more.

**Review by zonkmachine — APPROVED** [review]

**Comment by zonkmachine** [comment]
This PR fixes the problem reported in https://github.com/LMMS/lmms/issues/5840.

There are other issues described in the comment section of https://github.com/LMMS/lmms/issues/5840 which may or may not be related to the original issue.

**Comment by Spekular** [comment]
Doubly approved oneliner, Mac CI failure is unrelated, merging.

**Pull request merged**
