### PR TITLE
Proposed fix for 1649 for stable-1.1

### PR DESCRIPTION
**Pull request by curlymorphic**
Proposed fix for #1649  aimed at 1.1

replaces pull request #1655

### CODE REVIEW

**Comment by tresf** [comment]
Waited for Linux to pass in Travis, and then merged.  Thanks!

**Comment by tresf** [comment]
@curlymorphic Are you sure this message box is causing the crash?  I removed my stk rawwaves directory and it doesn't seem to affect this specific bug.

**Comment by curlymorphic** [comment]
hmmmm...  ok  what i had was a fix for a segfault that occurs in master without the stk.

**Comment by tresf** [comment]
> hmmmm... ok what i had was a fix for a segfault that occurs in master without the stk.

Well, we fixed it downstream at least and Vesa will sync it back up to master.

**Pull request merged**
