### PR TITLE
Arpeggiator Cycle function.

### PR DESCRIPTION
**Pull request by zonkmachine**
cycle

See #2080 

From the Cycle Knob's help text:
```
Jumps over n steps in the arpeggio and cycles around if we're over the note range.
If the total note range is evenly divisible by the number of steps jumped over you will
get stuck in a shorter arpeggio or even on one note.
```
...and if you do get stuck in a shorter sequence you can just turn up the `Miss` Knob to reach the other notes.

### CODE REVIEW

**Comment by zonkmachine** [comment]
This is the last of the three functions (the others being skip and miss) originally targeted for 1.2 .
Fixed up and tested.

**Comment by zonkmachine** [comment]
Merge?

**Comment by jasp00** [comment]
```c++
	// Cycle notes
	if( m_arpCycleModel.value() && dir != ArpDirRandom )
	{
		cur_arp_idx += m_arpCycleModel.value() + 1;
		cur_arp_idx %= range;
	}
```

**Comment by zonkmachine** [comment]
Awesome!

Though `cur_arp_idx += m_arpCycleModel.value() + 1;`
has to be: ` cur_arp_idx *= m_arpCycleModel.value() + 1;`

**Comment by zonkmachine** [comment]
OK, I'll merge this in a day if there are not other comments.

**Comment by Umcaruje** [comment]
:+1:

**Pull request merged**
