### PR TITLE
Add Qt5 Linux VST subwindow implementation

### LINKED ISSUE #2855: VSTi plugins don't show in Subwindow on Qt5 build (probably only X11)
screenshot_20160616_145731

Qt 5 bug:

the vst window will not be caught by the subwindow. With Qt4 we use QX11EmbedContainer for catching the vst window in our subwindow. QX11EmbedContainer is gone in Qt5. 

https://github.com/LMMS/lmms/blob/master/plugins/vst_base/VstPlugin.cpp#L228

```

#ifdef LMMS_BUILD_LINUX
    if( m_pluginWindowID == 0 )
    {
        return;
    }

    m_pluginWidget = new QWidget( _parent );
    m_pluginWidget->setFixedSize( m_pluginGeometry );
    m_pluginWidget->setWindowTitle( name() );
    if( _parent == NULL )
    {
        vstSubWin * sw = new vstSubWin(
                    gui->mainWindow()->workspace() );
        if( isEffect )
        {
            sw->setAttribute( Qt::WA_TranslucentBackground );
            sw->setWindowFlags( Qt::FramelessWindowHint );
            sw->setWidget( m_pluginWidget );
#if QT_VERSION < 0x050000
            QX11EmbedContainer * xe = new QX11EmbedContainer( sw );
            xe->embedClient( m_pluginWindowID );
            xe->setFixedSize( m_pluginGeometry );
            xe->show();
#endif
        } 
        else
        {
            sw->setWindowFlags( Qt::WindowCloseButtonHint );
            sw->setWidget( m_pluginWidget );

#if QT_VERSION < 0x050000
            QX11EmbedContainer * xe = new QX11EmbedContainer( sw );
            xe->embedClient( m_pluginWindowID );
            xe->setFixedSize( m_pluginGeometry );
            xe->move( 4, 24 );
            xe->show();
#endif
```

### PR DESCRIPTION
**Pull request by Lukas-W**
Uses `QWindow::fromWinId` and `QWidget::createWindowContainer` instead of
`QX11EmbedContainer` which was removed in Qt5.
Adds a workaround for mouse events that aren't accepted by the window
container, and thus were being propagated to the parent.

Fixes #2855. (Does this work on other platforms than Linux with Qt5?)
screenshot_2017-01-25_18-47-17

### CODE REVIEW

**Comment by jasp00** [comment]
@Lukas-W, have a look at #2856.

**Comment by Lukas-W** [comment]
@jasp00 Oh, I missed that. Just tried it out. I don't experience any visual or moving glitches, I guess that's fixed in Qt 5.7.1? However, I still have the following issues:

* The VST instrument opens in a separate window outside of LMMS instead of as a subwindow
* It's possible to resize the window to a size smaller than its contents
* I can close the window, but I can't bring it back using the "Show/hide GUI" button, only re-loading the project works.
* "Show/hide GUI" feature is very slow, takes a few seconds to open the window

Would you mind testing this PR? If there are no major bugs, I'd suggest merging this one in favor of #2856, as it touches a lot less code and doesn't have the issues mentioned above, nor any glitches in Qt versions prior to 5.7.1 (at least that I know of).

**Comment by jasp00** [comment]
>I'd suggest merging this one in favor of #2856

As you can see in https://github.com/LMMS/lmms/pull/2856/commits/23c3b218283bf1f7a80f8e5928f896ece6bb73a5, I just tried what you do now. Subwindows cause glitches in Qt 5.6.1 and 5.7.1. The issues that you have detected should be fixed:

>* The VST instrument opens in a separate window outside of LMMS instead of as a subwindow

This is unavoidable because subwindows cause glitches. This way it works like ZynAddSubFX.

>* It's possible to resize the window to a size smaller than its contents

`QMainWindow::setFixedSize()` does not work on your system. I will try setting the layout instead.

>* I can close the window, but I can't bring it back using the "Show/hide GUI" button, only re-loading the project works.

Do you use X11? Does `ps -A` report a defunct `embed-window` process?

>* "Show/hide GUI" feature is slow, takes a few seconds to open the window

It is `DestroyWindow()` from Wine actually. If you wait after closing, then you may open faster, right? This could be improved by using a (Windows) thread.

**Comment by Lukas-W** [comment]
> Do you use X11? Does ps -A report a defunct embed-window process?

Yes & Yes. Just tested it again and the window does reappear when clicking "Show/hide GUI". Sorry for the false negative.

> QMainWindow::setFixedSize() does not work on your system. I will try setting the layout instead.

Yep, that could actually be my WM's (i3) fault.

> Subwindows cause glitches in Qt 5.6.1 and 5.7.1

> This is unavoidable because subwindows cause glitches. 

My point is that I don't have any glitches in 5.7.1 with this PR, so it's possible the glitches you experience are not caused by Qt.

**Comment by Lukas-W** [comment]
Just tested on Ubuntu 16.04 LTS with Qt 5.5.1. No glitches with this PR or with yours. However, when using 23c3b21, the VST subwindow is empty.

**Comment by jasp00** [comment]
>it's possible the glitches you experience are not caused by Qt.

We see environments [without glitches](https://github.com/LMMS/lmms/pull/2856#issuecomment-265288582) and others [with them](https://github.com/LMMS/lmms/pull/2856#issuecomment-230675365). The glitches are triggered by the switch from Qt 4 to Qt 5 and they persist after removing the embedding subwindow. Even with separated windows, Qt 5 applications behave erratically, not just LMMS. Is it really a Qt bug? I will not know for sure until I debug Qt 5, but Qt 4 does not trigger this.

**Comment by BaraMGB** [comment]
In my opinion we should really consider to have the VST plugins into a QDialog instead of a QSubWindow. The user can move the window to a second desktop and we prepare a future [single window solution](https://github.com/LMMS/lmms/issues/1911) for lmms which wouldn't work with subwindows.

**Comment by jasp00** [comment]
>we should really consider to have the VST plugins into a QDialog

This is an ill concept. Why would a dialog work when a widget does not?

>we prepare a future single window solution for lmms which wouldn't work with subwindows.

Yes, it does not work with subwindows, it works with widgets, which is essentially the same.

@BaraMGB, you mentioned QDialog at https://github.com/LMMS/lmms/pull/2856#issuecomment-244391667. Could you provide the implementation so I could confirm whether the glitches are present?

**Comment by Lukas-W** [comment]
@jasp00 Did you actually test this PR with Qt 5.7 or were you just referring to experiences made with your implementation? (23c3b21)

**Comment by BaraMGB** [comment]
>Could you provide the implementation so I could confirm whether the glitches are present?

This could be difficult. Unfortunately I never pushed it to github. Perhaps I have the branch on my laptop. I will look tonight when I get home.

**Comment by BaraMGB** [comment]
Okay, found the branch. Rebased it: https://github.com/BaraMGB/lmms/tree/vstembedqt5
I guess I made a lot of stupid stuff there. The problem was the window doesn't show the plugin at first. You have to click hide/show Gui for it.

**Comment by jasp00** [comment]
>Did you actually test this PR [...] ?

It is essentially the same code. Anyway, I have tested and it has the glitches.

>we should really consider to have the VST plugins into a QDialog

I have tested your branch. `QDialog` is not needed, `QWidget` is enough. A dialog, by default, is modal and cannot be sent to the background. However, it uses a different window and the glitches are not there. The glitches appear when using `QMdiSubWindow`. Using `QWidget` with `Qt::Window` flag works; this flag may not be necessary in a single window interface.

So an external embedder is not needed. Protocol enhancements from #2856 should be merged into a `Qt::Window` solution. There are some XCB errors that do not seem to do harm.

I will pause development for some days.

**Comment by tresf** [comment]
> A dialog, by default, is modal and cannot be sent to the background. 

Only if `setModal(true);` but that can be toggled off with `setModal(false);`, so I'm not sure the purpose of this point.

**Comment by jasp00** [comment]
>A dialog, by default, is modal and cannot be sent to the background.

My bad, it is modeless by default. Anyway, it cannot be sent to the background because of the default `Qt::Dialog` flag.

**Comment by Lukas-W** [comment]
> It is essentially the same code. Anyway, I have tested and it has the glitches.

Thanks @jasp00. Would you mind sharing some details about your environment (such as distro, Qt version, GPU/graphics driver)? I'd really like to be able to reproduce this.

So far, I tested (without glitches):
* Arch Linux, Intel GPU, i3 window manager, Qt 5.7.1
* Arch Linux, Nvidia GPU, Nouveau driver, i3 window manager, Qt 5.7.1
* Ubuntu 16.04 inside VirtualBox, Qt 5.5.1

**Comment by jasp00** [comment]
Sorry for the delay, I have like 800 pending messages to catch up.

> I'd really like to be able to reproduce this.

`QMdiSubWindow` is not required and I am the one able to fix that case. Anyway...

> Would you mind sharing some details about your environment (such as distro, Qt version, GPU/graphics driver)?

I develop with Debian Sid, updated from time to time; as of today, glitches are still there. Qt version is 5.7.1+dfsg-3+b1. Graphics go through X11 without DRI drivers.

**Comment by karmux** [comment]
I tested this PR with Wine 2.4.0 and Qt 5.6.1 on Kubuntu 16.10.

VST effects from effects chain work without issues but VST loaded into Vestige opens separately from Qt subwindow. There is empty Qt subwindow and borderless VST instrument, just like in @jasp00's PR when I tested it couple of months ago.

Difference is that in jasp00's PR VST instrument went inside Qt subwindow after clicking "Show/hide GUI" button twice in Vestige but here it always opens without window borders.

screenshot_20170329_235402

**Comment by Lukas-W** [comment]
I can reproduce this with Qt 5.6.1 and Plasma and i3. Xfce doesn't have this issue.

I started a new approach on branch `qt5-vst-2`, porting `QX11EmbedContainer` to Qt5. @karmux Could you test the new implementation and check if it fixes the floating-window issue on your system?

**Comment by karmux** [comment]
@Lukas-W, I tried this new approach and didn't get any window issues. :+1: 
I noticed only that instrument window border style is a bit different from effect window border style.

screenshot_20170401_193342

On the screenshot Kontakt 5 is instrument and Guitar Rig 5 is effect.

Had to install following new packages to be able to compile `qt5-vst-2`:
```
libqt5x11extras5-dev
qtbase5-private-dev
libxcb-util-dev
libxcb-keysyms1-dev
```

**Comment by jasp00** [comment]
>I started a new approach on branch `qt5-vst-2`, porting `QX11EmbedContainer` to Qt5.

Same glitches there.

**Comment by Lukas-W** [comment]
@jasp00 I guess you have the same glitches using Qt4 then, as it's the same code, right? What WM/desktop environment are you using?

**Comment by Lukas-W** [comment]
@karmux Great, thanks for testing! 👍 I'll open a new PR to track `qt5-vst-2`'s issues there.

**Comment by jasp00** [comment]
>I guess you have the same glitches using Qt4 then

No, I only have glitches on Qt 5 when embedding in a subwindow.

>What WM/desktop environment are you using?

Metacity and GNOME.

**Comment by Lukas-W** [comment]
> Metacity and GNOME.

So you're still using Gnome 2?

**Comment by jasp00** [comment]
>So you're still using Gnome 2?

I do in this environment, GNOME 2 speaks X11.

**Comment by Lukas-W** [comment]
@jasp00 I pushed some fixes to #3475. You're invited to re-test if you're interested. 

However, even if your glitches persist, supporting a platform as old as GNOME 2 is out of scope for this feature and for LMMS in general. Support for it has been long dropped by most projects, and I don't know about any distro that still provides it, let alone provide GNOME 2 and Qt5 at the same time.

Note that prior to my most recent commits, almost all of the code in `QX11EmbedContainer` was unused because of a bug in Qt's `XEMBED` protocol implementation ([QTBUG-36446](https://bugreports.qt.io/browse/QTBUG-36446)). So the code you tested basically only consisted of a single `XReparentWindow` call. If this simple call causes issues on you're environment, I'm afraid there's little we can (or should) do.

Closing this as it'll most likely be superseded by #3475.

**Pull request closed without merging**
