### PR TITLE
Update generated C files from SWH upstream

### PR DESCRIPTION
**Pull request by jasp00**
These files include the vocoder adopted by SWH upstream. See #2366 for more information.

### CODE REVIEW

**Comment by jasp00** [comment]
There are two new plugins: `analogue_osc_1416` and `fm_osc_1415`.
The new warnings need to be fixed.

**Comment by jasp00** [comment]
Fixed and forwarded upstream (swh/ladspa#29).

**Comment by tresf** [comment]
Most of these changes are formatting or initialization changes and seem quite benign.

For example, the `setlocale` changes seem to be something that has [changed naturally over time](https://www.gnu.org/software/gettext/manual/html_node/Libraries.html).

The `malloc` and the `calloc` changes seem to be [quite sane](http://stackoverflow.com/a/1585987/3196753) as well.

This is a rather large commit as it touches 97 source files so a full review can take some time.  Propert testing too.... these swh plugins are used heavily by musicians so I'd like some feedback from the likes of @grejppi, etc as to whether or not we should hold this off until after the `1.2` release.

Some code changes I simply don't understand the benefit of.... such as:

`int foo = 0;`

versus the new:

`int foo;`
`foo = 0;`

An example of this can be found here: https://github.com/LMMS/lmms/pull/2753/files#diff-4f6dec5e589f41fd2f4a0206a5e51a38L451

Perhaps this is just how the upstream code generator behaves.

Anyway, feedback is needed prior to merging this one.  👍

**Comment by jasp00** [comment]
I think an upgrade step will be needed for the name change from `Vocoder for LMMS` to `Vocoder`.

**Comment by tresf** [comment]
> 

Good catch.

Here's the relevant XML structure... 

```xml
<effect name="ladspaeffect" [...]>
    <ladspacontrols [...]>
        <port [...] />
    </ladspacontrols>
    <key>
        <attribute value="vocoder_1337" name="file" />
        <attribute value="vocoder-lmms" name="plugin" />
    </key>
</effect>
```

So something like... 
 * Element by tag-name `effect`
  * Has property-name `ladspaeffect`
    * Child tag-name `key`
      * Child tag-name `attribute`
         * Has property-name `value` equal to `vocoder-lmms`
           * Change property-name `value="vocoder-lmms"` to `vocoder`


@T-boneG might be a good person to help with this as he just fixed the misspelling of `bassloopes` via 8e7d819, but he'd have to clone `-b new-swh https://github.com/jasp00/lmms` to test it out.

**Comment by tresf** [comment]
> upgrade step will be needed for the name change from Vocoder for LMMS to Vocoder

Confirmed. The name change breaks old projects that used the `vocoder-lmms` named plugin and now requires `vocoder`.  Done via f2b611b.

Vocoder as well as several other `swh` plugins tested on this branch without issues.  Merging.

**Pull request merged**
