### PR TITLE
set new initial width of piano roll editor

### PR DESCRIPTION
**Pull request by BaraMGB**
fixes https://github.com/LMMS/lmms/issues/3299

set the size equal to automation editor window.

### CODE REVIEW

**Comment by tresf** [comment]
The toolbar method seemed a bit more dynamic.  Is there a reason why this began failing (collapsible toolbar perhaps?)

**Comment by mikobuntu** [comment]
@tres I'm presuming the collapsible toolbar method will still work after this PR gets implemented as it seems to only initialize a set width on opening ? , If so I think at least the user will still get these option if they decide to shrink the Piano_Roll window. 
I just find that I have to stretch out the window every single time I use LMMS which can be annoying ( less clicks/dragging window size means more music being created ) .

**Comment by BaraMGB** [comment]
>The toolbar method seemed a bit more dynamic. Is there a reason why this began failing (collapsible toolbar perhaps?)

@tresf yes, I guess thats the reason. The toolbar is broken into parts. I don't quite get it. Seems it uses the standard Qt Toolbar. But I don't see how to get a sizehint() from it.

**Comment by tresf** [comment]
@mikobuntu I think you misread my concern.  My concern is why this calculated value became hard-coded, not so much about the toolbar behavior.

@BaraMGB my concern here is that as we start to write more code around high DPI displays, we need to move away from magic width and height parameters.

Since this fix is a hard requirement of 1.2, I'll merge as-is, but we need to move away from magic numbers as a project goal.

**Pull request merged**
