### PR TITLE
Update ExprTk package

### PR DESCRIPTION
**Pull request by ArashPartow**

### CODE REVIEW

**Comment by ArashPartow** [comment]
@JohannesLorenz @tresf  when you have a moment can you please review and merge this PR

**Comment by JohannesLorenz** [comment]
I wanted to pull the branch, but it is not possible. It looks like you removed ArashPartow/lmms.

Sorry, but I can't review the branch if it does not exist anymore. At least, I don't know how to pull it.

**Comment by JohannesLorenz** [comment]
Never mind, I found it out: `git fetch upstream refs/pull/6646/head:refs/heads/pr-6646`.

**Review by JohannesLorenz — APPROVED** [review]
From a code perspective OK. Needs testing though (from someone who knows how to use `Xpressive`).

@ArashPartow As usual, please keep in mind to not overwrite this commit (just mentioning because we had issues with this in the past).

**Comment by ArashPartow** [comment]
@JohannesLorenz I think @gnudles might be able to help out here with the testing. But given the default tests passed, it's probably good to go.

**Comment by JohannesLorenz** [comment]
> But given the default tests passed, it's probably good to go.

That makes sense. I will wait a few days for gnudles if they want to test. If not, I'll simply merge.

**Comment by gnudles** [comment]
ExprTk comes with extensive tests. I think it should be ok.

**Comment by tresf** [comment]
@JohannesLorenz thanks for merging.

> From a code perspective OK. Needs testing though (from someone who knows how to use Xpressive).

I would recommend testing a few presets before and after as a sanity check.

**Pull request merged**
