### PR TITLE
Adds better versioning for non-stable builds

### LINKED ISSUE #2365: Misleading version information
Currently, if someone grabs the master branch, they build LMMS and it will be labeled in respect to the version information in `/CMakeLists.txt`, which currently is `1.1.3`.

This is misleading because most developers will build from `master` when developing a new feature and any binaries released will bear the stable version number in the dialogs.

Should we try to leverage git in the build process to detect a non-stable build?  If so, how should we do the numbering for a non-stable build?

My thought is to take a "nightly" approach:

**Edit:** The agreed approach is:

```cmake
   SET(VERSION_MAJOR       "1")
   SET(VERSION_MINOR       "1")
   SET(VERSION_PATCH       "3")
   # and perhaps
   SET(VERSION_SUFFIX      "a1b2c3") # commit id
```

This would be done by checking the origin of the `git remote` and if it is not `/lmms/lmms` and does not contain the word `stable` in the branch name, use the above versioning.

**Edit2:** Overridable via `cmake -DFORCE_VERSION=x.x.x-x`

(old, left for historical purposes... disregard this part)
```cmake
   SET(VERSION_MAJOR       "2015")
   SET(VERSION_MINOR       "09")
   SET(VERSION_PATCH       "21")
   # and perhaps
   SET(VERSION_SUFFIX      "0932") # 9:32 AM
```

The biggest downside is that this may have some unintended side-effects when comparing stuff like `ProjectVersion` which uses version_major, etc inside the code for compat code and project and config file upgrades.  Thoughts?

### PR DESCRIPTION
**Pull request by tresf**
Closes #2365

This prevents nightly builds from having official version numbers, instead appending the commit hash as a suffix.

For example a fresh build from master may look like this `1.1.3-a1b2c3d`.

Furthermore, this allows specifying the version information on the command line via: 

```bash
$ cmake -DFORCE_VERSION=1.2.0

# or

$ cmake -DFORCE_VERSION=1.1.90-bug1234

# or 

$ cmake -DFORCE_VERSION=internal #don't append a hash
```

... and `VersionInfo.cmake` will parse the `VERSION_MAJOR`, `VERSION_MINOR`,`VERSION_PATCH` and optionally `VERSION_SUFFIX` from the command line.  If a full version is not supplied (e.g. `1.2`) cmake will fail with an out of bounds error.

image

image

### CODE REVIEW

**Comment by Lukas-W** [comment]
This is great! Thanks for your efforts.

I'd take a less centralized approach though. Instead of checking for the remote URL and the branch, how about checking if the current git commit has a tag attached and use that information for determining if the build is stable or not. This way we're not depending on the remote URL or name, or on a branch name, those can all differ per user.

A very easy way to get useful version information for our purpose is `git describe`, which outputs information about the current commit. For instance, running `git describe --tags` on the current master branch prints:
```
v1.1.3-1356-g596a41d
```
That contains the latest tag, the number of commits since that tag, and the unique current commit hash.

When we're on a tag, we just get the tag's name:
```sh
[lmms]$ git checkout v1.1.3
Note: checking out 'v1.1.3'.
HEAD is now at d14f451... Remove compiler optimizations for mingw, bump version
[lmms]$ git describe --tags
v1.1.3
```
So we could actually use that output directly to get our version and to determine if our build is a release/stable build or a nightly.

**Comment by tresf** [comment]
@Lukas-W done via a1df2d1.

The only (slight) downside to this approach is it honors fork-specific tag information, so builds from my branch don't use the `CMakeLists.txt` version information, but [rather a version I chose when uploading a build for a tester](https://github.com/tresf/lmms/tags).  I think I favor this approach, but it could get confusing quickly if people like @curlymorphic make an arbitrary version number a long time ago.  It also will mandate some actual versioning (or the use of `FORCE_VERSION`) on these interim builds or else tags like `20150101-zynwin` won't parse correctly.

Opinions welcome.

**Comment by Lukas-W** [comment]
I think we can avoid that by using `git describe`'s --matches option. From the docs:

> **--match < pattern >**
>
>    Only consider tags matching the given glob(7) pattern, excluding the "refs/tags/" prefix. This can be used to avoid leaking private tags from the repository.

So our command could be somethink like `git describe --tags --matches v[0-9].[0-9].*`

**Comment by tresf** [comment]
> I think we can avoid that by using `git describe`'s --matches option. From the docs:

Interesting... Results are not as I'd expect... check this out... 

```bash
# clone tresf/master
# checkout "zyn25.00"
git describe --tags --match v[0-9].[0-9].[0-9]*
# outputs:
#     zyn25.00

git describe --tags --match v[0-9].[0-9].[0-9]*

# outputs:
#     v1.0.100-1004-gbdd3f3
```

And these are my "private" tags... 

image

So why the heck does it grab such an old tag?  This concerns me.

**Comment by Lukas-W** [comment]
The problem might be that they both point to the same commit.

**Comment by tresf** [comment]
> The problem might be that they both point to the same commit.

Yeah, there's some strange stuff going on there, I'll consider it safe for now... 

Implemented pattern matching via a7b1697.

I was going to check the return code for non-zero, but I find that to be a redundant exercise since we'll always have a valid `vX.X.X` somewhere in our tag history.

**Comment by tresf** [comment]
Squashed and merged.  Ping me if there are any unforeseen issues with this, notably when creating a build, the About Dialog as well as the setup package filename (Mac/Windows) will be affected.

**Pull request merged**
