### PR TITLE
Enable HiDPI Scaling (Qt 5.6+ only)

### PR DESCRIPTION
**Pull request by flynn16**
(Qt 5.6+ only) This pull request will make LMMS scale automatically on HiDPI displays and solve the [GUI scaling issue](https://github.com/LMMS/lmms/issues/2510#issuecomment-330239441) _[at least for me]_.

### CODE REVIEW

**Comment by tresf** [comment]
@flynn16 thanks!

>  solve the GUI scaling issue.

As far as we know, this solution will only work properly on Linux, correct?  Just want to be as specific as possible as this scaling issue occurs on Mac and Windows as well.

This should be targeted against `stable-1.2` so we can make it part of the RC4 release.  We can try to switch it for you from this PR.

**Comment by flynn16** [comment]
> This should be targeted against `stable-1.2` so we can make it part of the RC4 release. We can try to switch it for you from this PR.

Sure. Please help me switch over to `stable-1.2`.

**Comment by tresf** [comment]
@flynn16 it doesn't look possible due to the divergence of the branches.  If you are OK making a new PR against `stable-1.2`, that would be ideal.  Sorry for the inconvenience.

**Comment by flynn16** [comment]
I opened a new PR #3814

**Pull request closed without merging**
