### PR TITLE
New PlayHandles directory

### PR DESCRIPTION
**Pull request by M374LX**
Small improvement of source structure to keep it more organized.

### CODE REVIEW

**Comment by tresf** [comment]
@M374LX, I think you pushed some code to the wrong project.

**Comment by tresf** [comment]
Ok, you've fixed it.  This should be rather obvious, but you'll have to squash the commit history.  As far as the refactoring, I'll defer to @Lukas-W.

**Comment by M374LX** [comment]
@tresf 
Done.

**Comment by badosu** [comment]
Nice refactoring, thanks @M374LX!

**Comment by tresf** [comment]
Another observation.... this is our first `CamelCase` folder in src.  @badosu opinions welcome.  I assume the idea here is for better organization, but I'm not sure I see the big picture yet, so any explaining is welcome here. :+1:

**Comment by badosu** [comment]
I guess this is the first instance of folders with composite names on our source tree, so there's a bit of ambiguity towards this.

So the way things are, folders can even be `cathis is a bit undefinedmelCase` or `snake_case`. But not `PascalCase` as @M374LX is using.

I would prefer @tobydox or @diizy to chime in with this, since they worked with most of LMMS and probably their opinion will make more sense.

**Comment by diizy** [comment]
Hm well I don't really know if we should single out playhandles to a separate directory... It's kind of questionable whether adding more layers to the directory structure is beneficial to us.

If we do decide to add it, I believe it should be in all lower case, because some of our supported OS's do not have case sensitivity in filenames...

**Comment by tresf** [comment]
> If we do decide to add it, I believe it should be in all lower case, because some of our supported OS's do not have case sensitivity in filenames...

I don't disagree, but would this actually build any distributable binaries in a separate folder?  Last I knew the only supported OS we have that is case insensitive is Windows, which we don't build on... And even if we do, I'm not sure the case insensitiveness would be a contributing factor to its build success or failure... :/

**Comment by diizy** [comment]
AFAIK OS X is also case insensitive... anyway, all our source directories are in lower case, so this should be too for consistency. I don't think the case-insensitivity would bring any problems, either, but it's better to be safe than sorry.

Also I'm still not sure if playhandles should be in their own directory... there's lots of changes to how playhandles work coming in lmms2, also there's possibly going to be other handles (in lmms2 I've  played with something I named processHandles) so maybe we could simply have a "handles" directory...

**Comment by tobydox** [comment]
I strongly vote for keeping file names and containing types and class names consistent. Means class FooBar should be declared in FooBar.h and defined in FooBar.cpp. The actual platform itself shouldn't matter for building at all.

**Comment by tresf** [comment]
> AFAIK OS X is also case insensitive...

I did some searching and it seems that there is a strange history on OSX in terms of case sensitivity... Since it is based off of BSD, many components are sensitive, but I remember the original OSX builds of LMMS having the binary name wrong in the launcher (`LMMS` instead of `lmms`) and it still worked, so I suppose it is a matter of context... 

I found an argument on arstechnica and I saw this phrase used:

> OS X became **case preserving** in its consumer release, but case sensitivity remained (and I assume still remains) for legacy reasons.

So I guess the jury is out for now.  As far as its impact on the software, I think Toby's right in the sense that it is more of a nomanclature and standards topic than a compatibility conversation. :)

**Comment by tresf** [comment]
Closing as this yields virtually no benefit until a larger refactoring effort warrants it

**Pull request closed without merging**
