### PR TITLE
Add missing ¹⁄₉₆ quantization.

### PR DESCRIPTION
**Pull request by Cyp**

### CODE REVIEW

**Comment by PhysSong** [comment]
I think `AutomationEditor::setQuantization()` will be broken with this changes while `PianoRoll::quantization()` doesn't.

**Comment by Cyp** [comment]
Eeek, sorry about that.

**Comment by PhysSong** [comment]
Looks good, but I don't think the stable branch needs these changes.
@Cyp Sorry for the delay.

**Comment by PhysSong** [comment]
BTW, is it okay to keep `Quantizations` in `MidiTime.h`?

**Comment by Veratil** [comment]
> 
> 
> BTW, is it okay to keep `Quantizations` in `MidiTime.h`?

I feel if we need to use quantizations in other areas keeping it in that file will be beneficial for reducing code duplication. Allow a model to use whatever it wants, but have all the options available. Since the Automation Editor also uses the values, we shouldn't have them in both places.

**Comment by PhysSong** [comment]
I also agree with reducing code duplication. What I mean is that `Quantizations` is for the GUI whereas `MidiTime.h` is independent of the UI.

**Comment by Veratil** [comment]
> 
> 
> I also agree with reducing code duplication. What I mean is that `Quantizations` is for the GUI whereas `MidiTime.h` is independent of the UI.

🤦 gotcha! What would be the better choice in your opinion?

**Comment by PhysSong** [comment]
The problem is, I don't know either. `Editor.h` is a candidate, but I'm not sure if it's the best place.

**Comment by Cyp** [comment]
Rebased and fixed merge conflicts. Moved `Quantizations` from `MidiTime.h` to `Editor.h`, and hope it's ok there.

**Pull request merged**
