### PR TITLE
Fix for the font of truncated sidebar items (#5714).

### PR DESCRIPTION
**Pull request by DigArtRoks**
For windows platforms, retrieve the system font and set it for the FileBrowserTreeWidget. This makes sure that truncated items will use the font as non-truncated items.

### CODE REVIEW

**Comment by DigArtRoks** [comment]
It looks like there is a shortcoming/bug in QT. When it truncates the text of an item because the sidebar is made smaller, it uses another font (in particular MS Shell Dlg 2 vs. Segoe UI for non-truncated items on my Win10 box).

The issue is flagged here: [https://bugreports.qt.io/browse/QTBUG-29232](url).
Also the QTableWiget seems to have a similar issue: [https://bugreports.qt.io/browse/QTBUG-22572](url).

Both bugreports do a suggestion to fix it or workaround it.
* Set font-family in the stylesheet. This works also fine for LMMS, but in the stylesheet there is no font at all defined. Also a font may not be available or not the same as the system font that is used for other QT Widgets. So I rejected this.
* Retrieve the font that is used by Windows for Non-Client area elements and set it as font for the QApplication. This also works fine for LMMS, but for some reason it changes quite a lot of other text labels in the UI as well.

Taking it further I implemented the second proposal and apply the retrieved font only on the FileBrowserTreeWidget. Resizing the sidebar now looks clean when text items get truncated.
I was not sure where to put the function (getWin32SystemFont) to retrieve the system font. Please advice if there is a better location. The fix is only applicable for Windows builds, but I understood from the issue that it is anyway only Windows related.

@Spekular, unfortunately it's adding logic instead of removing logic.

**Comment by Spekular** [comment]
Tested and working for me. I don't see any issues with the code itself but I'd love to hear from someone else, especially regarding this: 

> I was not sure where to put the function (getWin32SystemFont) to retrieve the system font. Please advice if there is a better location.

As for this:

> @Spekular, unfortunately it's adding logic instead of removing logic.

That is a bit unfortunate, but worth it IMO. That being said, I would add a link to the qt bug report and a searchable keyword to the comments. That should make it easier to remove this code when it becomes obsolete. Something like

```
// Workaround this qt bug, fixed in 5.12.2: https://bugreports.qt.io/browse/QTBUG-29232
// TODO: remove this when all builds use a recent enough version of qt
```

**Comment by superpaik** [comment]
It works perfect. Tested on both 32 and 64bits, on Windows10

**Comment by DigArtRoks** [comment]
Thanks!
I added the suggested comments in an additional commit.

**Review by Spekular — APPROVED** [review]

**Comment by Spekular** [comment]
Merging ~24h from now if there are no objections. Shouldn't be hard to move the font function if it does belong elsewhere :P

**Comment by DomClark** [comment]
How about adding the condition `QT_VERSION < QT_VERSION_CHECK(5, 12, 2)` in addition to `LMMS_BUILD_WIN32`? Quoting myself from #5598:

> Knowing which parts can be removed later is easy - just search the codebase for `QT_VERSION`. This is something we've already done before, to remove Qt 4 compatibility code.

As for where to put `getWin32SystemFont`, I think `GuiApplication` is fine if it could be useful elsewhere, otherwise I would put it in an anonymous namespace in `src/gui/FileBrowser.cpp`. Since the Qt bug report mentions other cases where the bug can occur, let's keep the function where it is for now in case the bug crops up somewhere else before we update Qt.

**Comment by DigArtRoks** [comment]
Thanks. Good suggestion! I added the check and commited again.

**Comment by Spekular** [comment]
Good suggestion indeed, I'll have to remember that for the future. My approving review stands, @DomClark if the newly added check is to your satisfaction I'm still in favor of a merge.

**Review by DomClark — APPROVED** [review]

**Comment by Spekular** [comment]
🎉

**Pull request merged**
