### PR TITLE
Proposed fix 760  Improve search field

### PR DESCRIPTION
**Pull request by curlymorphic**
Proposed fix for #760 
Added Recursive searching in the following tabs

projects
presets
samples
home

I did allow this in root, as it would try to search all drives, networked drives, dvds, phones

### CODE REVIEW

**Comment by tresf** [comment]
Fixed. :)

> I did **not**  allow this in root, as it would try to search all drives, networked drives, dvds, phones

**Comment by tresf** [comment]
Works well, thanks!

image


The one comment I have is that the way the folders stay collapsed could probably be improved.  I'm not sure if we should just expand all search selections or perhaps hide the parent folders... What do you think?

**Comment by curlymorphic** [comment]
Will have a look this evening. All I done was to fill the tree on startup,
or when refresh is clicked. Then I closed all the directorys to stop the
display looking a mess when there is no search filter.

**Comment by tresf** [comment]
This is tested, working and ready to be merged.  The only outstanding enhancement to possibly expand the tree nodes witch matching elements.  If you'd rather we file this enhancement separately, we can merge now, just let us know (and thanks!)

**Comment by curlymorphic** [comment]
Im going to leave this pull request as is for now. I do see the advantage in your suggestion. Atm if there is no text in the search field, it acts like a wildcard and matches everything. It may also need some more thought because if i type kick or hh i get Loads of open folders with hundreds of samples listed, it may be better in that case to show the folder names. Maybe best to open a new issue to discuss/define what is needed.

**Comment by tresf** [comment]
> Im going to leave this pull request as is for now. 

Fair enough.  Merging.  Thanks for investigating.  Perhaps we auto-expand after 3 characters are typed... But we can open a new enhancement for that.

**Pull request merged**
