### PR TITLE
Disable minimization on all subwindows

### LINKED ISSUE #2976: Enable/Disable window minimization Setting
Right now, you can minimize some of the windows inside LMMS.
You can do it for the windows that are already accessible from the function keys or from the top bar of the program, and for instrument track windows.
If a window is minimized and then closed, it will stay in minimized state even if you call it again.
This, in my experience, leads to confusion.

That particular problem would be fixed by just resetting the window state to normal, not minimized, when a window is closed. So when it gets called again, it will show up on screen right away.
But there is an inconsistency with effect windows, which can't be minimized: I propose to remove the minimazation alltogether.

### PR DESCRIPTION
**Pull request by Umcaruje**
Fixes #2976 
All subwindows now have a flag set to disable the minimize button. I have also removed its drawing code and pixmaps. EffectView was also modified to properly set the window flags. Screenshot: 
screenshot from 2016-08-19 23 40 39

### CODE REVIEW

**Comment by RebeccaDeField** [comment]
My 2 cents: If we do decide to git rid of the minimize button, it seems to me that the maximize icon could be changed. That specific kind of maximize icon is used with a minimize icon very frequently, whereas a "full screen" style icon is not always paired with a minimize icon. 

I actually think that you have already created an icon like what I am thinking for the title bars in the past. [I hunted down the link to it.](https://github.com/LMMS/lmms/files/106637/icons.zip)

**Comment by Umcaruje** [comment]
Here's how it looks with the new icon: 
screenshot from 2016-09-27 19 03 22

This is rebased, conflicts removed and ready to be merged.

**Comment by liushuyu** [comment]
I think this is much better, not only get rid of further bugs relating to
the minimize button, but also beautified the icons

**Comment by BaraMGB** [comment]
I'll test this out, tonight.

**Comment by Umcaruje** [comment]
After some discussion over on Discord @RebeccaDeField modified the maximize icon so it fits better with the close icon: 
screenshot from 2016-09-27 22 52 59

**Comment by BaraMGB** [comment]
Okay, let's see what the people say.

**Pull request merged**
