### PR TITLE
Change spacing on hovered items in the context menus

### PR DESCRIPTION
**Pull request by Umcaruje**
Per: https://github.com/HDDigitizerMusic/lmms-alt-theme/issues/13

I also extended the separators to the edges.

Before and after: 
screenshot from 2016-02-14 11 41 59 screenshot from 2016-02-14 11 32 20

I think this adds a touch of modern to the current look, and its prettier imo.

### CODE REVIEW

**Comment by zonkmachine** [comment]
Looks better.

**Comment by IvanMaldonado** [comment]
Not sure if relevant, but I was able to do that much before this merge:

muchbeforethismerge

**Comment by tresf** [comment]
Correct this is just a stylesheet modification so anyone could have done
this previously this change just makes the spacing default which is easier
for themers to modify.

**Comment by Umcaruje** [comment]
^ what @tresf said.

**Comment by Umcaruje** [comment]
Merging this one, its a simple change and people seem to like it.

**Comment by zonkmachine** [comment]
:+1:

**Pull request merged**
