### PR TITLE
Split BBEditor and BBContainerView out into two pieces

### PR DESCRIPTION
**Pull request by nwertzberger**
So in order to get familiar with the codebase, I'm trying to do something:
- I'm trying to fix a bug where when you add a track, it doesn't put the track in with the same number of beats as the other tracks.
- I'm trying to capture the issue in a test, so that the quality of the code goes up.

In the process of trying to make things testable, I saw two classes in the same header file and source file. I split them out, because I only wanted to test one of them. Let me know if anything I did looks bad to you.

You can deny this pull request if you don't like something, there's no functionality yet. I just wanted to make sure this looked like the sort of stuff that you'd want committed in the future.

### CODE REVIEW

**Comment by zapashcanon** [comment]
What is the `.idea` file you added in `.gitignore` ? Looks like a tmp local file to test/debug, thus, I think it shouldn't be added. ;)

**Comment by tresf** [comment]
`.idea` files are perfect candidates for `.gitignore`.  They are generally IDE configuration files and we generally want to encourage that they stay ignored to encourage use of whatever editor people choose without the burden of constantly removing them from commits.

**Comment by zapashcanon** [comment]
Hum ok. I though using a global custom .gitignore was better:

`git config --global core.excludesfile '/path/to/my/.gitignore'`

**Comment by tresf** [comment]
> Hum ok. I though using a global custom .gitignore was better:

For those that have a single dev machine with a single git config, that makes a lot of sense for all of your projects... however
 1. Contributors here often don't have that luxury (e.g. they may be contributing to LMMS once a year from a machine not used often for C++ coding)
 2. Contributors here often find themselves on several platforms to reproduce various bugs meaning they won't realize the global ignore wasn't set until they're ready to submit a patch.

Adding common, sane IDE defaults is always a good idea to help remove files that IDEs leave behind thus adding a single:

```diff
+.idea
```

... is completely warranted, valid and convenient for others that may use the same IDE.
https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore

Why support commercial IDEs you may ask?  Well, Qt's commercial too and [can cost more than JetBrains](https://www.qt.io/buy-product/?pid=7051).

@nwertzberger apologies for using your PR as a place to discuss `.gitignore` files.

**Comment by nwertzberger** [comment]
General thoughts on code style / direction here? As i touch classes, i want to try to get a dependency-injectable constructor in there to open up more unit testable code. I think it might lead to me trying to compose in the QT stuff / or compose in the stuff that messes with QT.

**Comment by nwertzberger** [comment]
I'm obviously with @tresf, quick edits by new people can quickly accidentally add ide files.

**Comment by jasp00** [comment]
I think a file split is desirable, but I would like to see a serious proposal. You should make a new branch and remove the debug `printf()`s.

**Comment by nwertzberger** [comment]
Would anyone be interested in me integrating in a logging framework?

**Comment by jasp00** [comment]
That question should be in a different issue.

**Comment by PhysSong** [comment]
I think it's almost impossible to utilize changes in this PR because there are many merge conflicts, and the OP deleted the forked repository.
> get familiar with the codebase

@nwertzberger Thank you, and sorry for closing. Please don't hesitate to come back to LMMS whenever you want. :+1:

**Pull request closed without merging**
