### PR TITLE
Fix Sample Clip Reversing Position

### LINKED ISSUE #7352: Sample Track: Clips trimmed from Sample Track are not reverted.
### System Information

Debian Sid Cinnamon

### LMMS Version(s)

Nightly Version

### Most Recent Working Version

Versión 1.3.0-alpha.1.642+g6634cec12 (Linux/x86_64, Qt 5.12.8, GCC 9.4.0).

### Bug Summary

When I want to reverse a clip cut with the knife or trimmed on the sides, instead of reverting the visible part of the clip or the trimmed fragment, it reverses the entire clip, and that is very annoying because I have to trim the clip again and even more so when I'm using a lot of Sample Track tracks and clips. Here I leave you a sample:

https://github.com/LMMS/lmms/assets/26127693/4d20c55a-a10a-492c-bc9c-8bef008144c4

### Expected Behaviour

Only revert the clipped fragment, the visible part of the clip, and not the entire clip.

### Steps To Reproduce

1- Open LMMS.
2- Import an audio file into a Sample Track track.
3- Cut out a fragment of the audio or cut it with the knife.
4- Revert the clipped fragment.
5- Not the fragment is reversed but the entire clip.

### Logs

<details>
<summary>Click to expand</summary>
<pre>
  
</pre>
</details>

### Screenshots / Minimum Reproducible Project

_No response_

### Please search the issue tracker for existing bug reports before submitting your own.

- [X] I have searched all existing issues and confirmed that this is not a duplicate.

### PR DESCRIPTION
**Pull request by regulus79**
This pr makes it so that when you reverse a trimmed/cropped sample, the cropped section is actually reversed. This is in contrast to the previous behavior, where the original sample would be reversed, causing the clip bounds to be on a different part of the sample.

Fixes #7352

### CODE REVIEW

**Comment by sakertooth** [comment]
Just tested the PR. It seems it didn't fix it for me.

**Comment by Gabrielxd195** [comment]
I tried this and it didn't work, but it's good that they took this into account.

**Comment by Gabrielxd195** [comment]
@regulus79  I did the test and now this improvement works, if there is no other problem I think it can be merged.

**Review by messmerd — APPROVED** [review]
Tested it and it seems to work fine

**Comment by messmerd** [comment]
If @sakertooth approves, I think it's good to merge

**Review by sakertooth — APPROVED** [review]
Just retested, it seems to work for me now.

**Comment by bratpeki** [comment]
screencap-2024-09-14-14-28-00
screencap-2024-09-14-14-28-04

Notice how the reversed one has this "tail" after the transient.

**Comment by bratpeki** [comment]
Sounds perfectly fine, so the feature is a success!

However, the sample zoom thing is most odd.

Here's proof that the reverse doesn't match the sound.

https://github.com/user-attachments/assets/c5e1fd63-7c06-4941-8794-62ceaeb64083

This is what `ffprobe` has to say about the audio file:

```
Input #0, mp3, from 'MidiMelo2updatedMidi3.mp3':
  Metadata:
    Software        : LMMS (libsndfile-1.0.28)
  Duration: 00:01:03.79, start: 0.025057, bitrate: 294 kb/s
  Stream #0:0: Audio: mp3 (mp3float), 44100 Hz, stereo, fltp, 294 kb/s
      Metadata:
        encoder         : LAME3.100
```

Should I open a new issue regarding this?

**Comment by regulus79** [comment]
@bratpeki I cannot reproduce the issue; would you mind providing a sample file/project where the bug happens?

**Comment by bratpeki** [comment]
Just to note, we discussed this further [on Discord](https://discord.com/channels/203559236729438208/784594576223633478/1284567535286620221).

**Pull request merged**
