### PR TITLE
Minimum framesPerPeriod() effect decay

### PR DESCRIPTION
**Pull request by zonkmachine**
In response to https://github.com/LMMS/lmms/issues/4284
Increase the 1 minimum frame to `Engine::mixer()->framesPerPeriod();`

### CODE REVIEW

**Comment by DomClark** [comment]
The time returned by `timeout()` is in units of buffers, so `framesPerPeriod()` probably isn't the thing to go for here. It seems there is already a one-buffer minimum, although with a buffer size of 256 at 44100Hz this is a mere 6ms, so a longer timeout would still be good. Rather than adding a constant to the value of the "Delay" knob, would it instead be worth increasing the minimum and/or default value of the knob instead?

**Comment by PhysSong** [comment]
> The time returned by `timeout()` is in units of buffers, so `framesPerPeriod()` probably isn't the thing to go for here.

Correct. Simple calculation gives 1.486s for the buffer size of 256. I guess it's too long.
> although with a buffer size of 256 at 44100Hz this is a mere 6ms, so a longer timeout would still be good.

Agreed.
> would it instead be worth increasing the minimum and/or default value of the knob instead?

That's more straightforward. I think it should be at least 50ms \~ 100ms(delay and/or dynamic processors may need longer time though).
Maybe it would be better to allow users to disable the automatic stop feature for effects. That will give a simple and straightforward solution for side effects like #4284.

**Comment by zonkmachine** [comment]
> Maybe it would be better to allow users to disable the automatic stop feature for effects.

Already implemented. That's the setting named **Keep effects running even without input**.

**Comment by PhysSong** [comment]
> Already implemented. That's the setting named Keep effects running even without input.

Thanks! I forgot about that. I don't know if it'd be better to allow changing that per effect.

**Comment by zonkmachine** [comment]
>> would it instead be worth increasing the minimum and/or default value of the knob instead?
> 
> That's more straightforward. I think it should be at least 50ms ~ 100ms(delay and/or dynamic processors may need longer time though).

I tried a minimum of 100ms but could still replicate the issue with some bpm settings. Maybe make '**Keep effects running even without input**' default on?

**Comment by PhysSong** [comment]
> Maybe make **'Keep effects running even without input'** default on?

:+1:

**Comment by zonkmachine** [comment]
So, something like:
1. Close this PR
2. Disable the fx auto quit function for lmms-1.2 (as below)
https://github.com/LMMS/lmms/blob/daa3f535158f321e7a01ea531fc3085f2d26ab37/src/gui/SetupDialog.cpp#L137:L138

```
	m_disableAutoQuit(ConfigManager::inst()->value( "ui",
						   "disableautoquit").toInt() ),
```
to

```
	m_disableAutoQuit(ConfigManager::inst()->value( "ui",
						   "disableautoquit", "1" ).toInt() ),
```

3. Keep #4284 open and add a better framesPerPeriod() fix at a later time?

**Comment by zonkmachine** [comment]
> 2. Disable the fx auto quit function for lmms-1.2

https://github.com/LMMS/lmms/pull/4378

**Pull request closed without merging**
