### PR TITLE
Fix error collection on Song instead of MainWindow

### PR DESCRIPTION
**Pull request by badosu**
@tresf Here's the fix for the failure caused by #1579

### CODE REVIEW

**Comment by tresf** [comment]
Thanks, and sorry for the early merge here.  We'll get the message stuff in soon.  Please add your AFP code to that original commit.

Vesa said he was going to look at it prior to merging.  If he doesn't soon, I will.  He's quite better with C++ so we rely a lot on him for these, sorry for the delay.

**Comment by diizy** [comment]
On 01/08/2015 09:57 PM, Tres Finocchiaro wrote:
>
> Thanks, and sorry for the early merge here. We'll get the message
> stuff in soon. Please add your AFP code to that original commit.
>
> Vesa said he was going to look at it prior to merging. If he doesn't
> soon, I will. He's quite better with C++ so we rely a lot on him for
> these, sorry for the delay.
>

Yeah, I'll get to it soon, when I can. I've been having some pretty
heavy RL stuff here (in addition to the usual school etc.) that's been
cutting my LMMS time recently, but I'll get around to it...

**Comment by tresf** [comment]
Hmm.. @badosu for some reason Travis says this is failing.   I just tried reproducing on Ubuntu 12.04 using `build_mingw32.sh` and it's not erroring for me on my local machine... 

I can't see anything obvious with this code... Perhaps we comment it out until it is fully implemented?

**Comment by badosu** [comment]
Again, it's that issue with the windows builds.

You pointed out that using `EXPORT` could fix it, for example [here](https://github.com/LMMS/lmms/blob/8529f6a0a412416e11ab99c58de8eebc46e372c6/include/Song.h#L49) on [here](https://github.com/LMMS/lmms/blob/8529f6a0a412416e11ab99c58de8eebc46e372c6/include/MainWindow.h#L43).

But when I do that my build fails with:

    /home/badosu/Code/lmms/include/MainWindow.h:43:25: error: expected initializer before ‘:’ token
 class EXPORT MainWindow : public QMainWindow

Any idea?

**Comment by badosu** [comment]
Don't worry, already sorted it out, was missing an include :-). My next PR should fix this.

Sorry about that, I should have taken Travis into account, will be more careful about this.

**Comment by badosu** [comment]
@tresf Please check https://github.com/LMMS/lmms/pull/1583

**Comment by tresf** [comment]
> Sorry about that, I should have taken Travis into account, will be more careful about this.

Yeah, I'm a bit confused why it is pickier than my Ubuntu 12.04 machine in these cases... Thanks for the quick fix!!

**Pull request merged**
