### PR TITLE
Fixes #3183: Fix file factory delimeter position

### LINKED ISSUE #3183: Factory files separator incorrectly placed if factory directory has subdirectories.
My Samples/drums, My Samples/drumsynth and My Presets/ZynAddSubFX.
I have my own folders under samples/misc and there is no separator at all.
I'm using up to date master.

### PR DESCRIPTION
**Pull request by JohannesLorenz**
## Testers

@karmux @zonkmachine Can you please both test this branch (just open LMMS and check some of the delimeters in the file browsers)? With the help of two testers, more file hierarchies are tested.

## Code review

Volunteers? :skull_and_crossbones: :smile:

### CODE REVIEW

**Comment by zonkmachine** [comment]
Thank you so much for commenting the code! :cake: 
I'm testing away and it passes everything I've been throwing at it so far.

**Comment by karmux** [comment]
Separators always appear at expected places in this branch :+1:

**Comment by JohannesLorenz** [comment]
Many thanks you two for testing. Only code-review is left now.

**Comment by zonkmachine** [comment]
I'm starting to grasp the code a bit more now. This looks about right. Style looks fine too.

**Comment by JohannesLorenz** [comment]
Thanks for testing. I'm merging this now.

**Pull request merged**
