### PR TITLE
Updated wave icons for contrast, updated graphics for greater legibility

### PR DESCRIPTION
**Pull request by RebeccaDeField**
I made some updates to the graphs to improve the hinting and to match the updated LFO and Envelope backgrounds. I also updated the waveform icons to have more contrast with all of the plugins.

Fixes this problem [here](https://github.com/LMMS/lmms/pull/2806#issuecomment-222650129).
Referenced [here](https://github.com/LMMS/lmms/pull/2816#issuecomment-223566437).

@BaraMGB @Umcaruje @tresf

### CODE REVIEW

**Comment by BaraMGB** [comment]
The lfo controller artwork I have added yet here https://github.com/LMMS/lmms/pull/2816. Sorry, I forgot to change the title of the PR. There two commits in there. One for the peak controller and one for the lfo controller.

**Comment by RebeccaDeField** [comment]
@BaraMGB Not sure how I missed that, sorry! Do you know how to remove a commit from a pull request? I will also look into it.

**Comment by Umcaruje** [comment]
@RebeccaDeField this looks better:
screenshot from 2016-06-05 22 03 41

But could you please increase the backround size so there's a 1 pixel padding between the icons and the BG? I think that'd make it better.

**Comment by RebeccaDeField** [comment]
usr_wave_active
round_square_wave_active
square_wave_active
white_noise_wave_active
exp_wave_active
sin_wave_active
saw_wave_active

@Umcaruje Updated. Does this look better to you? :)

**Comment by RebeccaDeField** [comment]
usr_wave_active
white_noise_wave_inactive
exp_wave_inactive
sin_wave_inactive
saw_wave_inactive






@Umcaruje  Updated. Does this look better to you?

**Comment by Umcaruje** [comment]
>@Umcaruje Updated. Does this look better to you?

Yes that looks very good :+1:

**Comment by RebeccaDeField** [comment]
@Umcaruje Before I make another commit with the updated waveforms, I need to address the problem that the LFO artwork is a duplicate from @BaraMGB's pull request that was already merged. It seems there are very many ways to handle this on git, but I'm not sure what the best way is to go about it.

**Comment by teeberg** [comment]
If the files are identical, the merge shouldn't be a problem. Otherwise, look at the two conflicting images and `git add` the right ones to resolve the conflict for each file individually. Happy to assist in gitter if you need any more pointers!

**Comment by RebeccaDeField** [comment]
@teeberg The files are identical, so it should be fine?

**Comment by teeberg** [comment]
Have you already pushed all the files here? According to github, there are no merge conflicts :)
image

**Comment by RebeccaDeField** [comment]
@teeberg I need to make one last commit and then it should be all set to go.

**Comment by RebeccaDeField** [comment]
@teeberg updated and all checks passed. I think this is ready to be merged.

**Comment by Umcaruje** [comment]
>I think this is ready to be merged.
:+1:

**Pull request merged**
