### PR TITLE
Knob: Shortcut automation

### LINKED ISSUE #4485: Knob automation shortcuts
While the song is playing, a knob should provide an interface to set/clear the record of connected automation tracks. To enhance a looped automation recording live. I think context menu options would be the easiest. Drag and drop connection the most intuitive.

Knob should also have an "automate me" feature, which would add an automation track to the song, initialized with a connection, with the length of the whole song, and with the combined title of channel and effect names. Possible difficulty: I don't know if the knob is aware of the effect, and if the effect is aware of the channel. OK UX: context menu option. Awesome UX: ctrl+drag to the song editor.

Effect control window title should begin with the channel name. Then if multiple effect windows are opened, what they affect would be clear. Same difficulty as previously described.

I want to try implementing these for personal usage. Order matches priority, meaning that the set/clear interface is a timesaver I'd really appreciate, and the two other are thoughts aloud. Readme says I should file an issue first, so here it is.

### PR DESCRIPTION
**Pull request by nykula**
Resolves #4485, implements all the enhancements I suggested.

Hold Alt, and drag a knob or a fader, to instantly add a meaningfully named automation-track (if no matching or empty automation-track exists) and start recording changes. Release mouse, and existing automation starts playing again without getting overwritten by a constant value.

You can still manually set/clear record. For example, this is handy when you want to indeed overwrite with a constant value, or to disable changes. Knob context menu then lets you re-enable auto toggle.

Also fixed icon for "Remove all linked controls" which is in the same menu.

Effect control window titles, as well as automation patterns in the song enditor, now include the channel name, to help you adjust same effect on different channels side by side.

Please review.

### CODE REVIEW

**Comment by SecondFlight** [comment]
Any chance you could post screenshots/gifs of your PR in action? That will make it significantly easier to review.

**Comment by qnebra** [comment]
https://gfycat.com/ExcitableAdvancedGonolek

I haven't connected midi controller, so it's only basic connection stuff. Also if this PR can doing something like:

1. "add automation track"
2. lmms create corresponding automation track
3. first move of knob or fader in controller connect latest automation track to this knob or fader
4. start recording

This would be something beyond amazing for me, also I know this would be something hard to doing.

**Comment by qnebra** [comment]
It uses left Alt? For this functionality what I'm thinking lmms should have ability to save default midi controller, for example you have for example Arturia Keylab 49 (I have this) and in settings this controller is saved as default. 

Wait, this is for another PR.

**Comment by makepost** [comment]
Qt::AltModifier, so left Alt, and maybe right Alt in some layouts too. Now I get your suggestion better, and it's definitely worth implementing as well. Buying an external controller to complement the laptop, so can try add that after a few days.

**Comment by qnebra** [comment]
Well, it something in other DAWs what lmms should have. But I don't know how hard would it be to implement.

**Comment by makepost** [comment]
Enable this auto-connect LED in controller rack, create an automation track with Alt+drag, and use your MIDI controller. Until you disable, it keeps looking for uncontrolled tracks, so you can connect other models to same or different knob or fader.

image

**Comment by qnebra** [comment]
For now I didn't get full idea of latest post in this topic. Maybe you can post some gif?

**Comment by makepost** [comment]
In other words, when you move something on your external controller, it connects to an automation-track that has no connected controller yet, as long as the checkbox on the screenshot above is on. Exactly what you asked, if I understood correctly.

Turn the checkbox off after connecting all you needed from the controller, because it adds CPU load.

**Comment by qnebra** [comment]
I must test this, thank you for clarify.

**Comment by JohannesLorenz** [comment]
@nykula @qnebra  Can you please help identify what's the status of this PR? Ready for review, or still work in progress?

**Comment by nykula** [comment]
Was ready the moment I sent it but now likely has lots of conflicts with updated master. I'm burnt out at writing music, sorry. Anyone interested, please fork and take over.

**Comment by qnebra** [comment]
@JohannesLorenz When I tested this last time (previous year) it was really useful in terms of UX. But doesn't fix my biggest issues with lmms automation. It was buggy with external controllers. Really.

**Pull request closed without merging**
