### PR TITLE
Add "Rename this controller" option in context menu.

### PR DESCRIPTION
**Pull request by DeRobyJ**
I thought that having this option in the context menu would have been more obvious.
Also, "Remove this plugin" didn't make sense to me, so I decided to change it to "Remove this controller".

About the commits:
I don't get why it shows a commit about me updating my fork... There is no file change on that commit to compare.
How do I fix that?
(maybe I'm updating my fork the wrong way)

### CODE REVIEW

**Comment by tresf** [comment]
>  There is no file change on that commit to compare. How do I fix that?

Squashing usually does the trick, although AFAIK GitHub added a squash button to the web interface.  @Umcaruje said we can do it on our end now apparently but I can't find the option (perhaps it's on your end?)

**Comment by Umcaruje** [comment]
@tresf once you press 'merge pull request' you can change whether you want to squash or have a merge commit.
screenshot from 2016-04-29 17 48 30

**Comment by tresf** [comment]
^ :+1:

**Comment by DeRobyJ** [comment]
Perfect :)

**Comment by Umcaruje** [comment]
@DeRobyJ this is a good read on keeping your fork up to date, and avoiding the merge commits: https://github.com/LMMS/lmms/wiki/%5BGit%5D-Fast-forward-personal-branch-to-upstream

Some day, when I have time, I'll write up a git cheat-sheet for you guys.

**Comment by DeRobyJ** [comment]
Problem is that I followed "Accessing the repository" first, so I had cloned the LMMS/lmms first.
I tried to follow that too, and I think I've got something wrong

**Comment by Umcaruje** [comment]
@DeRobyJ please rebase this PR so it gets properly built by Travis. Here's a tut: https://github.com/LMMS/lmms/wiki/%5BGit%5D-Fast-forward-personal-branch-to-upstream

**Comment by liushuyu** [comment]
@DeRobyJ In short of https://github.com/LMMS/lmms/wiki/%5BGit%5D-Fast-forward-personal-branch-to-upstream, you can just `git pull --rebase git://github.com/LMMS/lmms.git master`

**Comment by DeRobyJ** [comment]
I'll deal with the problem later: I didn't use different branches, because I didn't know I should have done it.

I'll re-create the pull request when I'll have the time to fix this.
Also I'm probably going to pull different minor changes (like #2785 ) in one pull request after discussing them in an issue.
For now this is closed. It's no problem if I don't make it in time for 1.2!

**Comment by Umcaruje** [comment]
>I'm probably going to pull different minor changes (like #2785 ) in one pull request

No, please don't. It will quickly become a mess and probably never get merged. Open a seperate pull request for each different fix you make. That'll make it easier for us to test, review and merge them.

**Comment by DeRobyJ** [comment]
As you wish

**Pull request closed without merging**
