### PR TITLE
Avoid creating TCOs while rendering

### PR DESCRIPTION
**Pull request by Reflexe**

### CODE REVIEW

**Comment by PhysSong** [comment]
I think this is overkill. Creating a TCO shouldn't cause any race conditions with `Mixer` as you addressed in this PR, but I think you can somehow minimize actions within the `requestChangeInModel()`~`doneChangeInModel()` block. We should take care of realtime safety while considering thread safety as well.
The first commit looks good, though.

**Comment by PhysSong** [comment]
@Reflexe Is it okay to cherry-pick the first commit to `master` and close this PR for now?

**Comment by Reflexe** [comment]
No problem. Thanks.

**Comment by PhysSong** [comment]
Done via 371f7f506dd6b6552d36863dbe627e3dbd021327, with minor changes.

**Pull request closed without merging**
