### PR TITLE
LADSPA - Fix various floating point errors

### PR DESCRIPTION
**Pull request by zonkmachine**
Fixes NaN in project from closed issue https://github.com/LMMS/lmms/issues/3685
Also, some fixes salvaged from https://github.com/LMMS/lmms/pull/3313

### CODE REVIEW

**Comment by tresf** [comment]
@zonkmachine thanks!  Just a reminder that once merged, we should PR against https://github.com/swh/ladspa with the same fixes.

**Comment by zonkmachine** [comment]
Last fixes. Adapted coding style to the rest of the file and swapped `fmaxf()` with `std::max()`.
I'll merge this later. It's basically just one-liners and well tested.

> Just a reminder that once merged, we should PR against https://github.com/swh/ladspa with the same fixes.

I'll try and build those pluggins first. Last time I looked at it I failed miserably.

**Comment by tresf** [comment]
> I'll try and build those pluggins first. Last time I looked at it I failed miserably.

This should ease your struggles: https://github.com/swh/ladspa/pull/55

Besides the Travis-CI capabilities, it fixes a few compilation problems I ran into while working on #3931.  They haven't been merged yet so they're sitting as duplicates in the Travis-CI PR.

**Comment by tresf** [comment]
PR submitted https://github.com/swh/ladspa/pull/57.  Second set of eyes appreciated.

**Pull request merged**
