### PR TITLE
Fix issue #1848

### PR DESCRIPTION
**Pull request by M374LX**
New attempt after ruining #1850.

### CODE REVIEW

**Comment by tresf** [comment]
@badosu you've been following this right along... relying on you for input. Please...  and thank you. :)

**Comment by badosu** [comment]
@M374LX Everything looks fine to me!

Would you be able to change your commit message to reflect what it does? e.g.: *Fix config settings not using correct device*

This is really easy and straightforward to do: `git commit --amend -m "<your new message>"`

Then `git push -f`.

**Comment by tresf** [comment]
@badosu, that's ok.  We'll merge it as is. :+1:

**Comment by badosu** [comment]
:-/

**Comment by tresf** [comment]
@M374LX can you please test these recent SetupDialog commits against an empty `~/.lmmsrc.xml` file?  I'm getting a segfault after deleting mine working on #1849 and I think the recent changes may be the cause.

**Comment by tresf** [comment]
P.S. @badosu Sorry about the impatience on merging this... I'll allow more time for `--ammend` type fixes in the future. :)

**Comment by M374LX** [comment]
@tresf 
All right. The segfault is caused by `ConfigManager::inst()->value( "mixer", "audiodev" );` (in `SetupDialog.cpp`) returning an empty value, as the attribute **audiodev** is not set when *~/.lmmsrc* is absent. The same for the attribute **mididev**.

**Comment by tresf** [comment]
Thanks for the quick fix. :+1:

**Pull request merged**
