### PR TITLE
Moved RingBuffer to plugins/MultitapEcho

### LINKED ISSUE #7137: RingBuffer Refactor
Putting this here to act as a reminder to us that it needs to be done.

### Enhancement Summary
Ringbuffers are an important data structure for realtime audio processing, and LMMS makes extensive use of them in various places throughout the codebase.
Currently, they are implemented through the `ringbuffer` submodule, LMMS' own `RingBuffer` class, which has heavy and unnecessary coupling to the engine, and a `LocklessRingBuffer` type as well.

It would be good to consolidate all of those into one ring buffer implementation that is fast, flexible, and limited in scope to just being a data structure.

#### Justification
It will help simplify the codebase and make behaviour more consistent.

### PR DESCRIPTION
**Pull request by Rossmaxx**
fixes #7137 

per https://github.com/LMMS/lmms/issues/7137#issuecomment-1992490345 by @michaelgregorius , this `RingBuffer` class is only being used by the MultitapEcho plugin and is needlessly referenced in the core. So I moved it to the MultitapEcho plugin folder.

~~Todo : The effect should be changed to use `LocklessRingBuffer` instead but that can be done in a follow up PR (I'm scared of messing up something and breaking the plugin)~~
Both implementations have seperate purposes so I'll just scope down for now.

### CODE REVIEW

**Comment by Rossmaxx** [comment]
Looks like it won't work without a full swap to `LocklessRingBuffer`. I'll attempt that later.

**Comment by Rossmaxx** [comment]
@JohannesLorenz need help on porting to `LocklessRingBuffer`

**Comment by DomClark** [comment]
See my comment on #7137 - I don't think there's any need to get rid of this class. I wouldn't even move it for now - it likely has utility in the core for something like latency compensation.

**Comment by Rossmaxx** [comment]
Silly me doing work which no one asked for.

**Comment by Rossmaxx** [comment]
I think i now understand about what's going on with the build fail. Looks like `MixHelpers.h`needs to be exported if it needs to be called from within plugin code.

**Comment by Rossmaxx** [comment]
I'm biting more than i can chew. again. closing.

**Pull request closed without merging**
