### PR TITLE
fix export project for sampletracks with vst effects on it

### PR DESCRIPTION
**Pull request by BaraMGB**
fixes https://github.com/LMMS/lmms/issues/3511

### CODE REVIEW

**Comment by BaraMGB** [comment]
Okay, but now we don't need this anymore: 

`connect( gui->songEditor(), SIGNAL( playTriggered() ), this, SLOT( playbackPositionChanged() ) );`

I'll remove that.

**Comment by BaraMGB** [comment]
I guess I merge this tomorrow.

**Comment by Spekular** [comment]
@BaraMGB did something come up or should this be merged?

> I guess I merge this tomorrow.

**Comment by BaraMGB** [comment]
@Spekular  :+1:

**Pull request merged**
