### PR TITLE
Enable HiDPI Scaling (Qt 5.6+ only) [stable-1.2]

### PR DESCRIPTION
**Pull request by flynn16**
This pull request is based on the `stable-1.2` branch. Hopefully it will solve the long-standing UI scaling issue of LMMS. Tested on Ubuntu 16.04 via an AppImage.

### CODE REVIEW

**Comment by tresf** [comment]
@flynn16 thanks for rebasing this against `stable-1.2`.  Before this is merged, I think we owe it to the project to also [test this on MacOS](http://doc.qt.io/qt-5/highdpi.html#macos-and-ios).

The code is:

```xml
<key>NSPrincipalClass</key>
<string>NSApplication</string>
<key>NSHighResolutionCapable</key>
<string>True</string>
```

The file it will eventually reside in is here:
https://github.com/LMMS/lmms/blob/stable-1.2/cmake/apple/lmms.plist.in

Does anyone subscribed to the project have a Mac with a retina display that can test out the plist option?

**Comment by lukas-w** [comment]
@tresf I dont't see any difference between `stable-1.2` and this branch with Qt 5.9.1. The UI is scaled properly in both cases.

**Comment by tresf** [comment]
@lukas-w Thanks.  Do you have a retina display?  If Qt is already scaling on retina, we'll keep the XML changes to be consistent with the official Qt documentation and just not make it a requirement before merging.

**Comment by flynn16** [comment]
One more problem, the PPA used for cross compiling contains an old Qt 5. Perhaps someone should contact the PPA maintainer or build Qt 5.9 manually.

**Comment by tresf** [comment]
> Perhaps someone should contact the PPA maintainer or build Qt 5.9 manually.

Thanks for the recommendation.  His name is @tobydox and yes he's aware and working on updating the repos.  They'll be under a 16.04 repo moving forward but can be safely force-installed onto 14.04 in Travis-CI.

If a new Qt build for Windows fixes the scaling issues there too, we can remove [our hack which forces the exact opposite](https://github.com/LMMS/lmms/pull/3531).

**Comment by lukas-w** [comment]
> Do you have a retina display?

Yes. Most icons also appear pixelated due to upscaling, just like in the sreenshot in https://github.com/LMMS/lmms/issues/2510#issuecomment-330239441.

**Comment by Redsandro** [comment]
I've just downloaded the AppImage version for Linux, so I have `1.2.0-rc5 (Linux/x86_64, Qt 5.9.2, GCC 4.8.4)`. However, everything is still microsized. Am I missing some setting to enable the scaling?

**Comment by flynn16** [comment]
If it fails to scale automatically, try setting the QT_* environment
variables before launching the AppImage.

$ export | grep 'QT'
$ export QT_SCREEN_SCALE_FACTORS=''
$ export QT_AUTO_SCREEN_SCALE_FACTOR='1'
$ ./lmms.AppImage


On Sat, Apr 28, 2018 at 11:32 AM, Sander Steenhuis <notifications@github.com

**Comment by Redsandro** [comment]
@flynn16 thank you. The interface indeed scales nicely this way.

However, some fonts (menu, instrument panel) stay small while others (track titles) scale properly. Is there a setting for this I have missed?

image

**Pull request merged**
