### PR TITLE
CMake use explicit source file specifying

### PR DESCRIPTION
**Pull request by Lukas-W**
Let's just see what Travis thinks of this, then I'll merge.

### CODE REVIEW

**Comment by tresf** [comment]
This list seems much harder to maintain, no?  What is the reasoning behind this?

**Comment by Lukas-W** [comment]
It's a bit cleaner this way. There are basically two issues often experienced with automatically fetching the source list (="globbing"). 
* CMake has no way of finding new files without re-invoking `cmake` manually. While this is not that bad when developing, this can be a hard to find linker error when `git pull`ing new code suddenly breaks the build because your CMake script doesn't doesn't know about the new files. The same issue applies when removing files.
* The opposite case: CMake may compile files you don't actually want it to. This happens with some temporary test files you create or, which often bugged me, when using a merge tool that creates backup files such as `main.orig.cpp`. CMake picks those up and breaks the build.

The CMake documentation also advises not to use file globbing for sources:
> We do not recommend using GLOB to collect a list of source files from your source tree. If no CMakeLists.txt file changes when a source is added or removed then the generated build system cannot know when to ask CMake to regenerate.

**Comment by tresf** [comment]
I do not agree with this change.  Hypothetically making things cleaner isn't making things cleaner.  This adds a laundry list of hard-coded files which is harder to maintain down the road and the benefit sounds to be a upstream fix to a downstream anomaly.  If cmake has problems with GLOBS, can't we patch that script and not add a hundred lines to one that's working?

When CMake wrote those recommendations surely they didn't base it on a project with code organization like ours.

**Comment by Lukas-W** [comment]
> Hypothetically making things cleaner isn't making things cleaner.

The issues I described above are not hypothetical, they are real problems I and everyone who tries to update and build LMMS may discover. I'd rather add a single line to the according CMake script when adding a new file to the project (that happens very rarely) than regularly debug hard to trace linker errors when pulling new changes (that happens quite often).

So with this change, the two issues I described don't occur anymore. The only difference besides that is that you now have to add new files to the build script (like in about any project). Before, you had to manually invoke `cmake` for the build system to detect the changes, which is no longer necessary. 

> If cmake has problems with GLOBS, can't we patch that script and not add a hundred lines to one that's working?

I don't know of any way to fix them with still using glob. Please share if you do.

> surely they didn't base it on a project with code organization like ours.

How is our code well organized?

**Comment by Lukas-W** [comment]
On a side note, this is part of my efforts to "modularize" things in the code (separating core and gui). Auto-detecting a hundred files, throwing them into a huge pot called "lmms_sources" and feeding those to gcc doesn't really encourage building a modular architecture. Gaining control over ( and awareness of) what and where sources are built is crucial for having a well-organized, clean codebase.

If core, gui and plugins had been built separately from the beginning of this project, the kind of (gui/core-)mixed, interwoven code we have could not have evolved.

**Comment by tresf** [comment]
Thanks for the explanation.

I like the glob idea and perhaps I don't know enough to make an argument for or against it, but taking 20 minutes of CPU time off of each Travis build is enough for me to shut up, at lease for now.  :)

**Comment by Lukas-W** [comment]
> taking 20 minutes of CPU time off of each Travis build is enough for me to shut up, at lease for now. :)

Then I better not tell you that this would have also been possible with globbing. :bike:

**Comment by tresf** [comment]
:)

**Pull request merged**
