### PR TITLE
Remove Wine as a VeSTige requirement

### PR DESCRIPTION
**Pull request by Snowiiii**
Closes https://github.com/LMMS/lmms/issues/7148

### CODE REVIEW

**Comment by Rossmaxx** [comment]
Just a doubt. If vestige gets compiled without wine (for native linux vsts), doesn't lmms need to know it at compile time, so that lmms should prevent users from loading windows vsts without wine, else there's a high chance of a crash.
Also, you need to remove vst support for mac, as mac doesn't support vst and using your workaround might lead to "fake" mac vst support which might lead to crashes.

**Comment by Snowiiii** [comment]
> Just a doubt. If vestige gets compiled without wine (for native linux vsts), doesn't lmms need to know it at compile time, so that lmms should prevent users from loading windows vsts without wine, else there's a high chance of a crash. Also, you need to remove vst support for mac, as mac doesn't support vst and using your workaround might lead to "fake" mac vst support which might lead to crashes.

Should be fine, We can add an check when user tries to load an Windows vst. Also i added macOS support, It looks like the CI is failing for another reason

**Comment by Rossmaxx** [comment]
> Also i added macOS support

Are you sure? Have you tested it on your system. Perhaps @tresf can help in that area. 

> We can add a check when user tries to load an Windows vst

Should be done in a seperate pr but this pr depends on that change so would be better of opening and merging that pr first.

**Comment by Snowiiii** [comment]
> > Also i added macOS support

With support i just meant we dont't compiling it for mac, Because otherwise it breaks

**Review by DomClark — CHANGES_REQUESTED** [review]
This doesn't just remove Wine as a requirement for VST support on Linux; it removes the ability to use it at all. We should still build the Wine bridges if Wine is available, the change being that we can now build the native bridge even without Wine.

**Comment by tresf** [comment]
> Closes #7148

Not really.  As @DomClark alludes to, there's some ambiguity of what "VST" support means in LMMS, but no clear distinction in the build system:
* Windows VST2 support (either natively on Windows, or through a Wine bridge on Linux)
   * This is historically how VST/Vestige was referred to.  Mac-native and Windows-native VSTs were far less common when support was initially added.
* Native VST support
  * What's being requested here as well as in #7148
   
To properly close #7148, the concept of "Wine VST" need to be separated from "Native VST" in the code.  Simply removing the former is a major regression and one which will not be merged.

> Are you sure? Have you tested it on your system. Perhaps @tresf can help in that area.

I'd be happy to test once the PR is fixed.  I would expect native Mac VSTs to work fairly sanely.  They work just fine through Carla.

**Comment by Snowiiii** [comment]
maybe we should add an CMake Option and let the User decide if they want to able to load Windows VSTs trough Wine, Or if they only want to have native support

**Comment by Rossmaxx** [comment]
> maybe we should add an CMake Option and let the User decide if they want to able to load Windows VSTs trough Wine

With the way the vst code is written, a mere cmake option won't be enough. IMO, anything vst related should be started only after dom finishes his refactor, which can't be predicted.

**Comment by DomClark** [comment]
> maybe we should add an CMake Option and let the User decide if they want to able to load Windows VSTs trough Wine, Or if they only want to have native support

This already exists - see the `WANT_VST_32` and `WANT_VST_64` options.

> With the way the vst code is written, a mere cmake option won't be enough. IMO, anything vst related should be started only after dom finishes his refactor, which can't be predicted.

A CMake option is sufficient and indeed already present. A future refactoring is unrelated to this; we want the same set of outputs regardless of what the C++ code looks like.

**Comment by Snowiiii** [comment]
> This already exists - see the `WANT_VST_32` and `WANT_VST_64` options.

This is not quit what i meant, I mean we could add another option that allows to waive Wine and only allows Native VSts for People who want, So far i understand this should close #7152

**Comment by DomClark** [comment]
> I mean we could add another option that allows to waive Wine and only allows Native VSts for People who want

Those options already allow for that, don't they? Pass `-DWANT_VST_32=NO -DWANT_VST_64=NO` and only native Linux VST support will be built. See their use in `VstBase`:
https://github.com/LMMS/lmms/blob/3e19d1335f478504c22ed68af9c96fccd6a6774b/plugins/VstBase/CMakeLists.txt#L49-L60

**Comment by Snowiiii** [comment]
Ups, I think i overlooked it, Sorry

**Pull request closed without merging**
