### PR TITLE
Fix possible noise when normalizing bitinvader

### PR DESCRIPTION
**Pull request by zonkmachine**
Fixes https://github.com/LMMS/lmms/issues/5867

### CODE REVIEW

**Comment by zonkmachine** [comment]
Now the default wave isn't a full sine. Quickest fix for this is to increase the default wave to 200 samples.

**Comment by thmueller64** [comment]
I tested this PR and it fixes the issue as intended. In the PR above I added an additional check for correct normalization if a similar bug occurs in the future.

**Comment by PhysSong** [comment]
@zonkmachine Is this ready?

**Comment by zonkmachine** [comment]
> @zonkmachine Is this ready?

Almost there... :)

**Comment by zonkmachine** [comment]
Tests fine. Problem gone and old projects seem to behave well.

> In the PR above I added an additional check for correct normalization if a similar bug occurs in the future.

I've stepped through this code and it looks good to me. Should 7c3213b be squashed with the rest or kept separately at merge?

**Comment by zonkmachine** [comment]
I think this is ready to merge.

**Review by Spekular — APPROVED** [review]

**Comment by zonkmachine** [comment]
Rebased and pushed manually to master in 04d696a1e98e1b756d057c8adbbcc2a94315b572 and 4107bc02b98d9e21ad9036acb221339782ab5eb6

**Pull request closed without merging**
