### PR TITLE
Fixes #2262

### LINKED ISSUE #2262: Rendering from command-line does not check if file exists
When trying to render a nonexistent file from the command-line (using the `--render` option), it does not display an error message and stop. Instead, it tries to render the "otherworldly" file, although it never goes past 0%.

### PR DESCRIPTION
**Pull request by michaelgregorius**
Added a check for the existence of the file that should be rendered from
the command line. LMMS now exits with an error message in case the file
does not exist.

### CODE REVIEW

**Comment by zonkmachine** [comment]
I think the consensus is to use qDebug for messaging.
Thus you would substitute the iostream stuff for:
```#include <QDebug>```
and 
```qDebug() << "The file" << file_to_load << "does not exist!";```

**Comment by tresf** [comment]
@zonkmachine agreed although then he'd be inclined to switch all of them over.  I think leaving it a printf for now is suitable.

**Comment by michaelgregorius** [comment]
Had to make a small correction as the error message was missing a space.

I have to admit that I don't even think that `qDebug()` is the right thing to use in this context because as its name implies it is intended for debugging purposes. However, printing an error message for a file that does not exist is a regular interaction with the user and no debug output.

**Comment by Wallacoloo** [comment]
Right. qError would make more sense.

**Comment by zonkmachine** [comment]
Aight. I thought qDebug was "the thing".

**Comment by M374LX** [comment]
For now, I think the best idea is to use `printf()`, as this keeps consistency and avoids the unnecessary inclusion of `iostream`.

**Comment by michaelgregorius** [comment]
Switched to `printf`, removed the include of `iostream` and squashed the commits.

**Comment by Wallacoloo** [comment]
Looks good to me. Maybe in the future we can make it so all the error messages actually print to stderr, but that can be reserved for a future PR.

**Comment by tresf** [comment]
@michaelgregorius Please retitle, rebase and we'll merge. :+1:

**Comment by michaelgregorius** [comment]
@tresf Done!

**Comment by tresf** [comment]
@michaelgregorius Thanks for rebasing.. the tile is still a bit vague, can you make it describe the fix?  We should also follow this quality standard for the PR title as well, it will only make it easier for us down the road when we're looking back for troubleshooting, etc.

**Comment by michaelgregorius** [comment]
@tresf Title is now changed as well. :)

**Comment by tresf** [comment]
:+1:

**Pull request merged**
