### PR TITLE
Merge `stable-1.2` into `master`

### PR DESCRIPTION
**Pull request by liushuyu**
Yet another so-called `up-port` merge before it's too late

---
This change is [Reviewable](https://reviewable.io/reviews/lmms/lmms/4133)

### CODE REVIEW

**Comment by liushuyu** [comment]
Basic tests have manually done on a device running Arch Linux (amd64) 
With the following related packages installed:

Package | Version
------------ | -------------
gcc |7.2.1 20180116
glibc|2.26
wine| 2.21-staging
Qt|5.10.0
fltk|1.3.4

**Comment by liushuyu** [comment]
Packaged version:
https://transfer.sh/xwgtn/lmms-1.2.0-rc5.6474-mac10.12.dmg
https://transfer.sh/BRDx8/lmms-1.2.0-rc5.6474-win32.exe
https://transfer.sh/i7uT7/lmms-1.2.0-rc5.6474-win64.exe

Linux AppImage is missing b/c the packaging script errored

**Comment by liushuyu** [comment]
@PhysSong Sorry, I haven't been in the development for a while now, I didn't get catch up with your progress and your discussions.

**Comment by liushuyu** [comment]
The Travis CI complaint about cannot find `mksquashfs` which should be used to work (otherwise you wouldn't add this segment, right?)

**Comment by PhysSong** [comment]
@liushuyu There was a discussion about AppImage script error on Discord `#devtalk`. Fixing the issue looks tricky for now.

**Comment by PhysSong** [comment]
Anyway, the only conflicting file is `en.ts`, and it seems to be covered in this merge(by @liushuyu you). Good job. :+1:

**Comment by liushuyu** [comment]
>If I add ARCH=x86_64, then another error occurs: `appimagetool` uses system `mksquashfs` instead of bundled one.

@PhysSong Oh, I see, AppImage builder just plainly refuse to use the system `mksquashfs` am I correct about this?

**Comment by PhysSong** [comment]
Yes. For some reason the builder doesn't work with system `mksquashfs` after some upstream changes.

**Comment by tresf** [comment]
A viable AppImage for now should be to use this:

```diff
diff --git a/cmake/linux/package_linux.sh.in b/cmake/linux/package_linux.sh.in
index 7f500e6..ea35383 100644
--- a/cmake/linux/package_linux.sh.in
+++ b/cmake/linux/package_linux.sh.in
@@ -73,8 +73,9 @@ elif ! find "$LINUXDEPLOYQT" -mtime -$DAYSOLD 2>/dev/null|grep -q ".
        "$LINUXDEPLOYQT" --appimage-extract > /dev/null 2>&1
        mv "squashfs-root/usr/bin/appimagetool" "$APPIMAGETOOL"
        success "Extracted $APPIMAGETOOL"
-       mv "squashfs-root/usr/bin/mksquashfs" "$USERBIN/mksquashfs"
-       success "Extracted $USERBIN/mksquashfs"
+       mkdir -p "$USERBIN/../lib"
+       mv "squashfs-root/usr/lib/appimagekit/" "$USERBIN/../lib/"
+       success "Extracted $USERBIN/../lib/mksquashfs"
        rm -rf "squashfs-root/"
 
 else
```

The fix should be applied to `stable-1.2`, but a better fix is to just take the custom `~/bin` logic out.  As @PhysSong indicates, `mksquashfs` will only work with the AppImage version.  More details about this here: https://github.com/AppImage/AppImageKit/issues/592

**Comment by liushuyu** [comment]
@tresf @PhysSong  Still broken, is there a way to see the log file in the VM?

**Comment by PhysSong** [comment]
Adding this two lines seems to fix the issue:
```sh
mv "squashfs-root/usr/bin/desktop-file-validate" "$USERBIN/desktop-file-validate"
success "Extracted $USERBIN/desktop-file-validate"
```
See https://travis-ci.org/PhysSong/lmms/jobs/327108566#L5220 and https://github.com/AppImage/AppImageKit/commit/8a471fc5cd16ce22ea0795b24cfbd66a22cd8988

**Comment by PhysSong** [comment]
@liushuyu The new `en.ts` contains some strings from `src/3rdparty/qt5-x11embed/3rdparty/ECM`, which should be excluded according to your script. Any ideas?

**Comment by liushuyu** [comment]
>Adding this two lines seems to fix the issue:

@PhysSong Included in 87f4bfb

>@liushuyu The new en.ts contains some strings from src/3rdparty/qt5-x11embed/3rdparty/ECM, which should be excluded according to your script. Any ideas?

I forgot to run the checker script when I was merging this, sorry. It's fixed in 2dab6dc

**Comment by liushuyu** [comment]
Packaged Version for this PR:

OS | URL
------ | ------
GNU/Linux (amd64, kernel 3.4+) w/ GLibc  | https://transfer.sh/16Pbu/lmms-1.2.0-rc5.6477-linux-x86_64.AppImage
Windows (R) 32-bit | https://transfer.sh/NzhuJ/lmms-1.2.0-rc5.6477-win32.exe
Windows (R) 64-bit | https://transfer.sh/zyRlI/lmms-1.2.0-rc5.6477-win64.exe
macOS (amd64)  10.12+ (Sierra)| https://transfer.sh/oJRoG/lmms-1.2.0-rc5.6477-mac10.12.dmg

**Comment by liushuyu** [comment]
So is this good to merge though?

**Comment by PhysSong** [comment]
Before merging, I suggest:
1. Squash commit 2dab6dc(i8n fixup) into the merge commit
2. Squash two `package_linux.sh.in` commit into a single commit

Any other things look good for me. :+1:

**Comment by liushuyu** [comment]
>1. Squash commit 2dab6dc(i18n fixup) into the merge commit

Sorry this will screw up `git` rebase mechanism, so I merged two i18n related commits together and two package_linux.sh commits together instead

**Comment by tresf** [comment]
@liushuyu, spaces vs. tabs on `package_linux.sh.in`.

```diff
-        mv "squashfs-root/usr/bin/desktop-file-validate" "$USERBIN/desktop-file-validate"
-        success "Extracted $USERBIN/desktop-file-validate"
+	mv "squashfs-root/usr/bin/desktop-file-validate" "$USERBIN/desktop-file-validate"
+	success "Extracted $USERBIN/desktop-file-validate"
```

**Comment by PhysSong** [comment]
@liushuyu Please squash two `package_linux.sh.in` commit into a single commit again. Then I'd like to say go ahead. :tractor:

**Comment by PhysSong** [comment]
@liushuyu I think doing a new merge may be better since some commits have been added into `stable-1.2` and AppImage issue will be fixed when/if #4186 is merged.

**Comment by PhysSong** [comment]
Just pushed 0a5d056bdbe3731074d3cac1ba8a67fcffae1dc3 instead. Anyway, thanks to @liushuyu for reminding us.
@liushuyu Could you please sync i18n strings with Transifex(which have not been done from current `master`) again?

**Pull request closed without merging**
