### PR TITLE
Scan for native LMMS plugins in home lmms directory (#3392)

### PR DESCRIPTION
**Pull request by PaulBatchelor**
This PR should make it possible to look for LMMS plugins in two new places: the environment variable LMMS_PLUGIN_DIR, and the folder ~/lmms/plugins/lmms (not sure if my current solution will work on Windows).

It doesn't seem like the search paths are working properly, so I am creating ``QStringList`` paths and loading them up that way. Also did some minor refactoring and added a new private method called ``PluginFactory::loadPluginDirectory``.

Most of the new code here is borrowed from [LadspaManager](https://github.com/LMMS/lmms/blob/master/src/core/LadspaManager.cpp#L41), which does a similar thing.

### CODE REVIEW

**Comment by PaulBatchelor** [comment]
Fixes #3392

**Comment by BaraMGB** [comment]
I guess we need a native plug in for testing this. 😀

**Comment by Lukas-W** [comment]
Ah, I expected `QDir("plugins:").entryInfoList()` to list entries of all search paths, but apparently it only uses one. May I suggest a different fix for this though? This patch only adds a few lines and uses all search paths set up in the `PluginFactory` constructor or elsewhere.

```diff
--- src/core/PluginFactory.cpp
+++ src/core/PluginFactory.cpp
@@ -30,6 +30,7 @@
 #include <QtCore/QFileInfo>
 #include <QtCore/QLibrary>
 
+#include "ConfigManager.h"
 #include "Plugin.h"
 
 #ifdef LMMS_BUILD_WIN32
@@ -42,7 +43,7 @@ PluginFactory* PluginFactory::s_instance = nullptr;
 
 PluginFactory::PluginFactory()
 {
-	// Adds a search path relative to the main executable to if the path exists.
+	// Adds a search path relative to the main executable if the path exists.
 	auto addRelativeIfExists = [this] (const QString& path) {
 		QDir dir(qApp->applicationDirPath());
 		if (!path.isEmpty() && dir.cd(path)) {
@@ -71,6 +72,8 @@ PluginFactory::PluginFactory()
 	if (!(env_path = qgetenv("LMMS_PLUGIN_DIR")).isEmpty())
 		QDir::addSearchPath("plugins", env_path);
 
+	QDir::addSearchPath("plugins", ConfigManager::inst()->workingDir() + "/plugins/lmms");
+
 	discoverPlugins();
 }
 
@@ -130,7 +133,11 @@ void PluginFactory::discoverPlugins()
 	PluginInfoList pluginInfos;
 	m_pluginByExt.clear();
 
-	const QFileInfoList& files = QDir("plugins:").entryInfoList(nameFilters);
+	QFileInfoList files;
+	for (const QString& searchPath : QDir::searchPaths("plugins"))
+	{
+		files << QDir(searchPath).entryInfoList(nameFilters);
+	}
 
 	// Cheap dependency handling: zynaddsubfx needs ZynAddSubFxCore. By loading
 	// all libraries twice we ensure that libZynAddSubFxCore is found.
```

**Comment by PaulBatchelor** [comment]
@Lukas-W Sure. I can try it out at some point.

**Comment by PaulBatchelor** [comment]
@BaraMGB The plugin I am testing: https://github.com/paulbatchelor/lmms-sporth

**Comment by jasp00** [comment]
>I guess we need a native plug in for testing this.

How about kicker?

>and the folder ~/lmms/plugins/lmms

Please, just use `~/lmms/plugins`.

**Comment by Lukas-W** [comment]
@PaulBatchelor I applied my patch to `master` (tested with LMMS-Sporth, which fails to load even though it's discovered, but that's unrelated), closing #3392. Thanks for your work on this! 👍

**Pull request closed without merging**
