### PR TITLE
Automation Pattern - Rename 'controlKey'

### PR DESCRIPTION
**Pull request by zonkmachine**
Separate core and UI. Fix from PR #3352
See comment here: https://github.com/LMMS/lmms/pull/3352#pullrequestreview-27534195

### CODE REVIEW

**Comment by jasp00** [comment]
Simple name change. Merging...

**Comment by zonkmachine** [comment]
This should probably have been against stable-1.1

**Comment by Umcaruje** [comment]
@zonkmachine want me to cherry pick this back to stable-1.2?

**Comment by zonkmachine** [comment]
> @zonkmachine want me to cherry pick this back to stable-1.2?

Yes please!

**Comment by Umcaruje** [comment]
Done https://github.com/LMMS/lmms/commit/1bfd0931be9136c6cd90f58bb8cb24288e2558f7

**Comment by zonkmachine** [comment]
:+1:

**Pull request merged**
