### PR TITLE
Language update

### PR DESCRIPTION
**Pull request by softrabbit**
Following up on #1858:
```
for i in *.ts ; do mv $i $i.bak ; sed 's/12 semitones (1 octave)/24 semitones (2 octaves)/' <$i.bak >$i ; done
```

Drop this PR if that's not what was asked for, I'm pretty unfamiliar with this translation business.

### CODE REVIEW

**Comment by M374LX** [comment]
It seems that you are updating the sources but not the translations.

**Comment by tresf** [comment]
> It seems that you are updating the sources but not the translations.

Correct, those are done at build time per [`src/CMakeLists.txt#L129`](https://github.com/LMMS/lmms/blob/master/src/CMakeLists.txt#L129). Thanks for the attention to detail.  Much appreciated.  :+1:

**Comment by softrabbit** [comment]
> It seems that you are updating the sources but not the translations.

Isn't updating the translations more of a job for the translators? OK, I can change the numbers but I really don't want to start guessing how to say "2 octaves" in a bunch of languages :)

**Comment by tresf** [comment]
Sorry.... @M374LX you are right.  We need to touch the translated version of the XML too.

> I really don't want to start guessing how to say "2 octaves" in a bunch of languages :)

Luckily, they all use numbers.  Still manual, but needs to be addressed.

-Tres

**Comment by tresf** [comment]
Actually, it looks like quite a few use translated versions of the word "one".  We shouldn't really allow  spelled numbers in any of our translations for this very reason.  (`1` vs. `one`).

**Pull request merged**
