### PR TITLE
Remove excess parentheses from ternary operations

### PR DESCRIPTION
**Pull request by husamalhomsi**
Thanks to the very low precedence of the ternary operator and its right-to-left associativity.

### CODE REVIEW

**Comment by Veratil** [comment]
I feel like this is something that can/will be handled with #4690?

**Comment by Spekular** [comment]
What is the benefit to this? Doesn't the huge number of lines with the same format* imply that people prefer the parenthases to be there?

*(condition) ? true val: false val

**Comment by IanCaio** [comment]
You definitely put some work on this PR by hunting all ternary operators in the code base, but the code style guideline is kind of open when it comes to the use of parenthesis on the ternary operator. So it's something to be discussed and decided, whichever is thought to be the best way.

Personally, I think the parenthesis looks better when the conditional is an expression a little bit bigger than usual. When it's a small expression, no parenthesis look fine to me, maybe even better. So if I was to create a rule for that I'd probably use the amount of operators and size of the evaluation expression as a factor to decide for/against using the parenthesis. Though there's already a rule that says if the expression is big, multiple lines should be used. Maybe if that rule was more strictly followed there would be no need for the parenthesis (that would require quite some more changes on the PR though, for dividing the ternary operators that have bigger expressions in multiple lines).

Anyways, think more voices should be heard on the matter. As for me, I would vote for the PR if the ternary operators with larger evaluation expressions were also divided in multiple lines for the sake of readability. I would vote against if they are kept as one-liners, because in that case I'd prefer the parenthesis to be there.

**Comment by Sawuare** [comment]
@veratil No clang-format or clang-tidy checks affect parentheses in ternary expressions.

**Comment by Sawuare** [comment]
@Spekular Actually, ()-less expressions outnumber those with ().

**Comment by DomClark** [comment]
I don't see why ternary operators either all must have parentheses, or all must not. There's no such requirement in our coding conventions currently, and I would be against adding one - we shouldn't restrict style so much that there's only a single way to format a piece of code, as that removes the flexibility to choose what is most readable in any particular situation. We could equally well go around and remove parentheses from around `&&` whenever it's next to `||`, since it has precedence there, but I imagine this would seriously reduce readability.

As for whether this gets merged or not, I'm indifferent. It doesn't make anything worse, but it doesn't really make anything better either.

**Comment by Sawuare** [comment]
I think excess parentheses obfuscate code, but I realize this is me trying to enforce my personal preference...
If this PR is deemed unneeded/unwanted, I will close it.

**Comment by Veratil** [comment]
> I think excess parentheses obfuscate code

It *can*, but doesn't always. Sometimes it helps readability. There certainly are some areas where we can remove some of those parenthesis, but a global removal is probably not the best idea. I think after we reorg with #5592 and merge the clang-tidy/format #4690 this can be readdressed for sure. 👍

Until then, we can close this one out.

**Pull request closed without merging**
