### PR TITLE
Fix SongEditorWindow resize when a project loads

### PR DESCRIPTION
**Pull request by DanWin**
This addresses the SongEditor part of issue #1621

### CODE REVIEW

**Comment by tresf** [comment]
`const` fixes it?  Interesting...

**Comment by DanWin** [comment]
Eyup! Because it is defined as const in SerializingObject we have to use it here too. Else it wouldn't override the function definition and simply do nothing, as the function without const is never invoked. I wonder why this worked before, because it wasn't touched at all in 3e9cc61042d753ba73d0e0786ae7ecb618e68b18 which is the commit that introduced this bug.

**Comment by tresf** [comment]
Hmm... I believe it was https://github.com/LMMS/lmms/commit/a52e4724cf4ce6f780e5693e50b39549e587b570 which introduced it, no?  Previously it had utilized [`TrackContainerView.h#L53`](https://github.com/LMMS/lmms/blob/master/include/TrackContainerView.h#L53)'s loadSettings.

Either way, thanks for the fix!!

**Comment by Lukas-W** [comment]
Good find @DanWin  :+1:

**Comment by DanWin** [comment]
@tresf I think that was the attempt to fix this issue, but it was missing the const to really fix it.

**Comment by tresf** [comment]
> @tresf I think that was the attempt to fix this issue, but it was missing the const to really fix it.

:+1:

**Comment by badosu** [comment]
@DanWin Thank you for this fix, really good catch! :-)

**Pull request merged**
