### PR TITLE
High resolution scrolling

### PR DESCRIPTION
**Pull request by allejok96**
Handle really sensitive scroll wheels (or touch pads) gracefully.

### Problem

Most widgets only check if a scroll event is positive or negative, and scroll exactly one step. For mice like the MX master this may result in 7 steps per mouse wheel tick, because it has a wheel resolution of 2° (compared to standard 15°).

### Solution

This PR implements a concise way to calculate scrolled steps, while keeping the remainder value, [as suggested by the Qt docs](https://doc.qt.io/qt-5/qwheelevent.html#angleDelta). The remainder is discarded when the widget loses focus.

Widgets are updated to use this new counter logic. This means that editors, knobs and faders may be scrolled with a much finer precision using a hi-res mouse.

This also sets a new minimum scroll speed for knobs and faders (at most 200 steps form start to end). Scrolling really really fast on a standard mouse is also ~faster~ more accurate now.

### Excuses
I've tried to build the counter in a way that using it would require as little code as possible, and no need to remember increasing, decreasing or resetting it. In other words, make it so you can't get it wrong.

- Using `ScrollCounter` is cleaner than having an `int` member in each widget and doing the same calculation in 20 places.
- `ScrollCounter` is a [singleton](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ri-singleton) because there is only one scroll wheel, so why would each widget have its own instance of it?
- If a widget doesn't check the counter during event handling, the counter won't be increased. This prevents it from silently growing when scroll events are being ignored or propagated to the parent.
- Also, thanks to the event filter, widgets never have to pass `QWheelEvent` to the counter.

As a side note, I've tried a way to intercept `QWheelEvent` and solve this problem higher up in the event chain. But this does not work due to how Qt does (undocumented) event propagation.

### Bugs fixed in this PR
- #3370 (not tested)
- #5511 (a matter of taste)
- Horizontal scroll on most automatable controls decrease their value
- Alt+scroll in piano roll note edit area only decreases the velocity
- Scrolling on empty pattern in song editor while zoomed in creates step notes even if they are invisible

### Other questionable changes
- Song editor's horizontal scroll step size is now based on zoom level
- Allow horizontal scroll in Piano roll's note edit area
- Scrolling inside Song editor never scrolls the MDI window
  - #3154

### CODE REVIEW

**Comment by qnebra** [comment]
For some reason MinGW build failed, but I guess you already notice it.

#3154 is annoying as hell when someone workflow had Song Editor at full screen. I am glad it gets fixed.

**Comment by allejok96** [comment]
I tried building it locally with the `lmmsci/linux.mingw32:18.04` container, and it worked just fine :confused:

**Comment by qnebra** [comment]
Trying to build it locally, on Ubuntu 20.04 using MinGW it throws those errors:

```
[ 64%] Linking CXX shared module ../compressor.dll
/usr/bin/x86_64-w64-mingw32-ld: CMakeFiles/compressor.dir/objects.a(CompressorControlDialog.cpp.obj):CompressorControlDialog.cpp:(.text+0x247e): undefined reference to `ScrollCounter::getStepsY(float)'
/usr/bin/x86_64-w64-mingw32-ld: CMakeFiles/compressor.dir/objects.a(CompressorControlDialog.cpp.obj):CompressorControlDialog.cpp:(.text+0x7843): undefined reference to `ScrollCounter::registerWidget(QWidget*)'
collect2: error: ld returned 1 exit status
make[2]: *** [plugins/Compressor/CMakeFiles/compressor.dir/build.make:241: plugins/compressor.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:2712: plugins/Compressor/CMakeFiles/compressor.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 65%] Building CXX object plugins/Delay/CMakeFiles/delay.dir/__/Eq/moc_EqFader.cpp.obj
[ 65%] Linking CXX shared module ../crossovereq.dll
[ 65%] Built target crossovereq
[ 65%] Building CXX object plugins/Delay/CMakeFiles/delay.dir/qrc_delay.cpp.obj
[ 65%] Linking CXX shared module ../delay.dll
[ 65%] Built target delay
make: *** [Makefile:152: all] Error 2

```

Clean master was compiled correctly, without issues.

**Comment by allejok96** [comment]
It's a long shot, but what if you change line 32 in `include/ScrollCounter.h` to

    #include "lmms_export.h"
    class LMMS_EXPORT ScrollCounter: public QObject

**Comment by qnebra** [comment]
> It's a long shot, but what if you change line 32 in `include/ScrollCounter.h` to
> 
> ```
> #include "lmms_export.h"
> class LMMS_EXPORT ScrollCounter: public QObject
> ```

It fixes compilation

**Pull request closed without merging**
