### PR TITLE
Fix regression caused by fcec8dd

### LINKED ISSUE #2660: Regression: Pattern size is not updated when it is altered by changing note length
Commit fcec8dd causes a regression in the drawing of Patterns on the song editor. To reproduce, enlarge any last note in a piano roll so that the Pattern becomes at least one measure longer. Now look at the song editor and notice that the Pattern still has its old length.

@Umcaruje As this is your commit, could you look into this regression? Let me know if you have trouble reproducing it.

### PR DESCRIPTION
**Pull request by Umcaruje**
Fixes #2660

### CODE REVIEW

**Comment by Umcaruje** [comment]
@Fastigium could you test it out please?

**Comment by zonkmachine** [comment]
Fix confirmed! :+1:

**Comment by Fastigium** [comment]
Confirmed here, too, so I'll go ahead and merge it :+1:

**Comment by Umcaruje** [comment]
Cool :+1: 

If you find anything else weird with the TCO drawing, let me know.

**Pull request merged**
