### PR TITLE
Multiband EQ Adjusted windowing to remove distortion.

### LINKED ISSUE #1885: Multiband EQ - Distorted Sound

### PR DESCRIPTION
**Pull request by curlymorphic**
Removed the incorrectly applied windowing to the input of the FFT.

fixes #1885

### CODE REVIEW

**Comment by tresf** [comment]
Wow that was quick.  I trust your judgement on this one.  If you think it should be merged, I'll merge it. :+1:

**Comment by curlymorphic** [comment]
Yeah, The windowing was distorting the signal, before the fft.

**Comment by tresf** [comment]
Is that a "Yes, merge" ? :)

**Comment by curlymorphic** [comment]
Yes. would like a green light from travis first though :)

**Comment by tresf** [comment]
Living life on the edge here.... 

image

**Comment by mikobuntu** [comment]
Hmmm @tres that is always a good start when something compiles 1st on OSX ;)

thanks Mikobuntu ;)


Date: Thu, 19 Mar 2015 13:29:43 -0700

**Comment by geedubess** [comment]
/delurk*

$.02 - if you're no longer applying the window there, perhaps an
update to the comment above ("// Window input FIFO") is needed as well?

I'm trying to remember my DSP. I see the windowing being applied in the
output buffer post-FFT, but isn't the idea to apply a windowing function
*before* FFT to reduce the spectral leakage of a discontinuous input?

cheers,
Greg

* Trying to learn and figure out where I may be able to contribute to LMMS.

**Comment by tresf** [comment]
> * Trying to learn and figure out where I may be able to contribute to LMMS.

:tada:

**Comment by curlymorphic** [comment]
@geedubess 

> $.02 - if you're no longer applying the window there, perhaps an
> update to the comment above ("// Window input FIFO") is needed as well?

good call.



> * Trying to learn and figure out where I may be able to contribute to LMMS.

Would you like to look at the windowing used here?

**Comment by geedubess** [comment]
Sure - I am, but I'm not fully understanding why it is designed like this.

If you would like me to look into it, give me a few hours and I'll ping back
here.

-g

**Comment by curlymorphic** [comment]
@tres Leave this for now please. Lets wait for @geedubess input

**Comment by mikobuntu** [comment]
@curlymorphic ping Tres with @tresf ... I did this earlier myself from a mail client ., I'm sure Tres Wong-Godfrey could probably help tho :P

**Comment by curlymorphic** [comment]
sorry for this miss ping

**Comment by mikobuntu** [comment]
miss type ping :+1:

**Comment by geedubess** [comment]
The only distortion (unintentional modification of the signal) that I could see
was gain (clipping) - non-unity gain at the output despite the default initial
parameters to the eq (which should = unity gain).

First thing I found was what appears to be a mistake in the windowing function:

// Create raised cosine window table
for (i=0; i < FFT_LENGTH; i++) {
         window[i] = -0.5f*cos(2.0f*M_PI*(double)i/(double)FFT_LENGTH)+0.5f;
         window[i] *= 2.0f;
}

A raised cosine function (Hann/Hanning window) is described as:
      .5 - .5*cos(2*pi*n/N)

However, his window function expands to:
      1 - 1*cos(...)

(And why the heck would you (*2.0f) in a separate calculation?! It's not like
he was going to overflow a float!)

So, that was odd. I also went on to change it to be a Hamming window, but I'm
still playing with it (it depends on what kind of input is being used;
different functions will produce different effects). I probably shouldn't
tweak it too much for improvements, since this is more about bug fixing...
(I looked upstream at his git repo and saw the same problem there.)

After the windowing process, the next steps are to convert it to the frequency
domain via FFT, modify the coefficients, and then convert it back via IFFT.
Those steps should result in unity gain, though (and first thing I did was to
disable them ;).

Finally, the data is summed back into the output: because the output window
slides around to match the partial windowed output, I'd expect gain to be unity
here as well (window / "de-window" should approximately cancel each other out).

Strangely, though, that's not working quite like it should. I'm not understanding
his constant (unidentified constants in signal processing are sometimes just
hacks to make the data come out nicely), though my first guess is that it has
to do with the gain/width of the initial windowing function. The gain is now
too low. So, I am guessing that the algorithm is incorrect there, and that it
is sliding the output accumulator window around too quickly.

As a hack, I flipped the terms a bit in the summation, and it is now ~unity gain,
but that's not a real fix, and I want to understand why.

As a more general question, though, are we attempting to put in enhancements
or fixes into these plugins, or should I push these questions upstream to swh?

Thanks for encouraging me to play with the code!

-g

**Comment by tresf** [comment]
@geedubess,

I can't comment much on the DSP conversation, but in terms of the swh/Steve Harris plugins, he's very receptive to improvements.  He no longer actively maintains the codebase but [will accept pull requests](https://github.com/swh/ladspa/pulls?q=is%3Apr+is%3Aclosed) (as you'll observe, most are from the LMMS team, since we still rely so heavily on his great work).

In terms of **where** to commit the code, we don't sync his work directly from upstream like we do Zyn (you'll notice his codebase is mostly stored in XML files) so what I've done personally is issue PRs in both locations.  BTW, thanks for asking, @curlymorphic may not have known to send these upstream and I had completely missed it. :+1:

**Comment by curlymorphic** [comment]
Closing this PR due to a better fix in #1897

**Pull request closed without merging**
