### PR TITLE
Travis osx

### LINKED ISSUE #1391: (Apple) Travis-CI Mac build support
[Travis-CI](https://travis-ci.org/LMMS/lmms) generously enabled OSX build support for our software today!

**Some minor obstacles:**
 * They use [homebrew](http://brew.sh/) for building (we currently use [MacPorts](https://www.macports.org/))
 * The use [XCode 6.1](https://itunes.apple.com/us/app/xcode/id497799835) (we currently use XCode/Clang 5.1)

**Some goals:**
 * Test our [Apple build instructions](https://github.com/LMMS/lmms/wiki/Compiling-lmms-(Apple)) against homebrew
 * Add/update our wiki to support [homebrew](http://brew.sh/)
 * Enable/configure our [Travis-CI build environment](https://travis-ci.org/LMMS/lmms) to report on Apple build errors

**Some longer-term goals:**
 * Leverage the same auto-upload process we're currently use for win32/win64 for GitHub Apple dmg releases
     * Possible Issue:  We use a custom shell script for creating the Apple bundles which is fired as part of the cmake `install` process, but we should create a cmake `package` process which incorporates install and DMG steps (or switch to the built-in cmake tools for this) 
     * Possible Issue:  We a DMG script which relies on AppleScript and Finder macros which may break on a console.  Alternate DMG build process may be necessary.

### PR DESCRIPTION
**Pull request by Lukas-W**
This is me ridiculously trying to enable OSX builds on Travis.

Closes #1391

### CODE REVIEW

**Comment by Lukas-W** [comment]
Hm… I'll close this and reopen when (if) it's working. Else Travis runs all build twice, once for the `travis-osx` branch and once for the pull request.

**Comment by tresf** [comment]
@Lukas-W, I had to add MacPorts to `CMakeLists.txt` originally for the build to work.

I've never tried with Brew, but I wanted to give you the FYI of the critical line to add [`CMakeLists.txt#L57`](https://github.com/LMMS/lmms/blob/master/CMakeLists.txt#L57)

If brew puts itself into to the standard build locations, then this is likely unnecessary to change.

**Comment by Lukas-W** [comment]
Thanks for the info. AFAIK Homebrew installs into `/usr/local`, so I that should be fine, right? :)

**Comment by tresf** [comment]
> Thanks for the info. AFAIK Homebrew installs into /usr/local, so I that should be fine, right? :)

Hmm... If it links to the non-Apple stuff then it worked.  I don't really know how the library linking works, so I would have to speak from experience (which I have none) rather than knowledge (which I have little). :wine_glass:

**Comment by Lukas-W** [comment]
I think we got our first successful Travis OSX build. :cocktail: 
https://travis-ci.org/LMMS/lmms/builds/47177839 :)

**Comment by badosu** [comment]
Great! :-)

**Comment by tresf** [comment]
Some slick work here @Lukas-W!

**Comment by tresf** [comment]
PS, please note you went from "ridiculous" to "fixed" in less than 4 hours. ;)

**Comment by tresf** [comment]
@Lukas-W just an idea here, but these shell scripts you've written could eventually become shortcuts or replacements for our build instructions on certain platforms...

**Comment by Lukas-W** [comment]
That's not a bad idea actually, I don't know how the scripts will evolve though. Also… I think build instructions should rather not simplify the build process too much by hiding what's really going on and how to control the build (e.g. you can't pass any additional options to CMake with these scripts).

**Comment by tresf** [comment]
Yeah.   Good point.  Perhaps we do the deps that way for the major platforms at least?  Reason I say that that is we have the majority of package names in quite a few places now.

You are right tho... We should be careful not to hide what is happening... Hmm...

**Comment by tresf** [comment]
Here's a reference chart of what we have so far... 

This information is currently in each build tutorial as well as the travis build scripts.  I'm not sure if there's an easy way to centralize them... but sometimes putting them side-by-side helps visualize if it would make sense or not.

Note, some of these may be implicitly added via other packages...  I tried to make them as comparable as possible.


|Name           |Ubuntu32          |Ubuntu64           |Win32                   |Win64                   |Homebrew      |Macports       |
|---------------|------------------|-------------------|------------------------|------------------------|--------------|---------------|
|**qt**         |libqt4-dev        |libqt4-dev         |mingw32-x-qt            |mingw64-x-qt            |qt            |qt4-mac        |
|**sndfile**    |libsndfile-dev    |libsndfile-dev     |mingw32-x-libsndfile    |mingw64-x-libsndfile    |libsndfile    |libsndfile     |
|**fftw**       |fftw3-dev         |fftw3-dev          |mingw32-x-fftw          |mingw64-x-fftw          |fftw          |fftw-3-single  |
|**vorbis**     |libvorbis-dev     |libvorbis-dev      |mingw32-x-libvorbis     |mingw64-x-libvorbis     |libvorbis     |libvorbis      |
|**ogg**        |libogg-dev        |libogg-dev         |mingw32-x-libogg        |mingw64-x-libogg        |libogg        |libogg         |
|**asound**     |libasound2-dev    |libasound2-dev     |--                      |--                      |--            |--             |
|**jack**       |libjack-dev       |libjack-dev        |--                      |--                      |jack          |jack           |
|**sdl**        |libsdl-dev        |libsdl-dev         |mingw32-x-sdl           |mingw64-x-sdl           |sdl           |libsdl         |
|**samplerate** |libsamplerate0-dev|libsamplerate0-dev |mingw32-x-libsamplerate |mingw64-x-libsamplerate |libsamplerate |libsamplerate  |
|**stk**        |libstk0-dev       |libstk0-dev        |mingw32-x-stk           |mingw64-x-stk           |stk           |!!FIXME        |
|**fluidsynth** |libfluidsynth-dev |libfluidsynth-dev  |mingw32-x-fluidsynth    |mingw64-x-fluidsynth    |fluid-synth   |fluidsynth     |
|**portaudio**  |portaudio19-dev   |portaudio19-dev    |mingw32-x-portaudio     |mingw64-x-portaudio     |portaudio     |portaudio      |
|**gig**        |libgig-dev        |libgig-dev         |mingw32-x-libgig        |mingw64-x-libgig        |--            |--             |
|**gcc**        |gcc               |gcc                |mingw32-x-gcc           |mingw64-x-gcc           |--            |--             |
|**binutils**   |binutils          |binutils           |mingw32-x-binutils      |mingw64-x-binutils      |--            |--             |
|**cmake**      |cmake             |cmake              |cmake                   |cmake                   |cmake         |cmake          |
|**pkgconfig**  |pkg-config        |pkg-config         |mingw32-x-pkgconfig     |mingw64-x-pkgconfig     |pkg-config    |pkgconfig      |
|**glib**       |libglib2.0-dev    |libglib2.0-dev     |mingw32-x-glib2         |mingw64-x-glib2         |--            |--             |
|**fltk**       |libfltk1.3-dev    |libfltk1.3-dev     |mingw32-x-fltk          |mingw64-x-fltk          |fltk          |fltk           |
|**cpp multi**  |--                |g++-multilib       |--                      |--                      |--            |--             |
|**c multi**    |--                |gcc-multilib       |--                      |--                      |--            |--             |
|**libc6-x86**  |--                |libc6-dev-i386     |--                      |--                      |--            |--             |
|**wine**       |wine-dev          |wine-dev           |--                      |--                      |--            |--             |

**Comment by Lukas-W** [comment]
Thanks for taking the time to compile this! Centralizing that information sounds like a good idea, yet I can't think of a good way to do it…

**Comment by tresf** [comment]
> Centralizing that information sounds like a good idea, yet I can't think of a good way to do it…

Me neither.  We'll shelf this until a day that we might need this.  I'd like it in a place we can find it, but I can't even think of a good place to put this chart in our wiki.  :confused:

**Pull request merged**
