### PR TITLE
New song: Free World, by M-374 LX

### PR DESCRIPTION
**Pull request by M374LX**
As a tribute to the LMMS team and all the free software community, I am donating my new seven-minute song, "Free World".

### CODE REVIEW

**Comment by Sti2nd** [comment]
Licence?

**Comment by M374LX** [comment]
> Licence?

Creative Commons BY-SA.
Here is the song in LSP: https://lmms.io/lsp/?action=show&file=6573

**Comment by tresf** [comment]
@M374LX,

Just an FYI, regardless of whether or not we accept this for the 1.2 release, our goal for future versions  (i.e. 1.3, 2.0, etc) is to bundle only with CC0 content. :+1:

**Comment by unfa** [comment]
Can't wait to give it a try :)

**Comment by M374LX** [comment]
For those wanting to hear the song before downloading the project file: https://www.youtube.com/watch?v=0yiNYMTHXUM

**Comment by Sti2nd** [comment]
IMO an ok song for LMMS, had it only been CC0 :)

**Comment by tresf** [comment]
@M374LX I've downloaded and listened to the song.

There are two problems I have with it:
 * Not CC0 (not a requirement until 1.3)
 * Makes inefficient use of tracks for beat/bassline (see attached image)

We don't have any strict requirements on what we allow, but if we're going to add this, I'd prefer it to showcase something that our users can benefit from.

image

**Comment by M374LX** [comment]
> Not CC0 (not a requirement until 1.3)
Unfortunately, the idea of allowing the usage of the project without acknowledging my authorship is not attractive to me.

> Makes inefficient use of tracks for beat/bassline (see attached image)
This shows the disadvantage of the current beat/bassline system for more complex, less repetitive beats.

**Comment by Sti2nd** [comment]
> This shows the disadvantage of the current beat/bassline system for more complex, less repetitive beats.

Yup, it is for repetitive stuff. The technique I have found to work best (less B&B tracks I think) is to put each drum instrument pattern in its own B&B track, not a drum pattern variation in its own variation. So the kickdrum have it's own B&B track. Why? Because the basic pattern will most likely be the same (at least in refrain and verse, although it may differ from each other). Then I can build up by adding hihats (in another B&B track) and then cymbals, toms, whatever I want. And if I suddenly want to add a random step for the kickdrum I add a B&B track with one kick step. If I want that step to be on another time later, I don't have to create a new B&B track just for that, I use the already existing one step bar and use fine adjust (click and hold and then Ctrl + drag) to put the step where I want it. Another benefit with that is that no matter variation of drum pattern is playing right nowI can use the same B&B track together with it. 
This song might be an example of what I am talking about, the last part. https://lmms.io/lsp/?action=show&file=6334 Although I admit that is very repetitive... it only has 5 B&B tracks and you can hear the variation.

In your case, I would have put that snare drum playing the whole time in it's own B&B track. Also, if you are just going to use a sound once, or in one part of the song, it is not meant to be in the B&B tracks, what I just said doesn't apply if you have no intentions of using it several times. Then it should be a normal instrument track :)

**Comment by tresf** [comment]
> This shows the disadvantage of the current beat/bassline system for more complex, less repetitive beats.

Well, we won't fix the BB editor just to merge a track, so I'm going to close this out for now.

**Pull request closed without merging**
