### PR TITLE
Fix 32-bit winegcc call on Linux when using LLD

### PR DESCRIPTION
**Pull request by rdrpenguin04**

### CODE REVIEW

**Comment by PhysSong** [comment]
Possibly related: #5024
See also: https://github.com/llvm/llvm-project/commit/0a7412f00ba4a2ccca069c55a1e21cdafb3bade1

**Comment by rdrpenguin04** [comment]
That other issue could be related; since `lld` blocks text relocations by default, it was a hard error for me.

The commit you referenced seems to be implementing the `-z notext` flag, not setting it as the default. I run `main` branch LLVM, so if it was made the default, I would have it by now.

This commit simply adds the flag so that RemotePluginVST32 will build and work properly, and, as I have stated, I have tested it on a 32-bit VST that I have.

**Comment by PhysSong** [comment]
LGTM. Please revert the last commit, BTW. The `CONTRIBUTORS` file is a fallback for automatically generated file, so it should probably be regenerated properly if it needs updating.

**Comment by rdrpenguin04** [comment]
K, will do.

**Pull request merged**
