### PR TITLE
fix locking of the useless_lock in LocklessRingBuffer.h

### PR DESCRIPTION
**Pull request by he29-net**
Cherry-picked bugfix from #5328.

### CODE REVIEW

**Comment by JohannesLorenz** [comment]
Looks good, and is confirming to docs.

Code and style review finished. No testing done yet.

**Comment by JohannesLorenz** [comment]
IIRC you say in the #5328 that it had only been crashing on Windows? If yes, then we need a Windows tester. As it's such a simple change though, for me it's just OK without testing, what do you think?

**Comment by he29-net** [comment]
Yes, it crashed only on Windows (that's why we missed it in the spectrum analyzer update review). I tested the Vectorscope build on Windows and this commit fixed the issue. PhysSong also mentioned it fixed "a similar crash" for him, so that should be hopefully a good enough indication that the fix works as intended.

**Comment by JohannesLorenz** [comment]
Thanks for the fix!

**Pull request merged**
