### PR TITLE
Rename "FX-Mixer" to "Mixer".

### LINKED ISSUE #3300: Rename "FX-Mixer" to "Mixer"
Rename "FX-Mixer" to "Mixer"

With LMMS, windows titles come with heavy debate, not my decision to make, but I noticed that this was mentioned in a few other posts, so I figured I would give it its own platform for debate, as other possible window name changes have....

Rename "Beat+Bassline Editor" to "Pattern Editor"
Rename "Song Editor" to "Sequencer"

### PR DESCRIPTION
**Pull request by claell**
Closes #3300 (hopefully, if not sorry for wasting your time!).

I currently only renamed String texts imho, but can also rename classes, variable names etc.

Not tested.

### CODE REVIEW

**Comment by SecondFlight** [comment]
Ordinarily we'd target changes like this to `master`, but I see no reason not to target `1.2`.

Also while you're at it, I'd personally be for changing variable names, though this is significantly more error-prone. Also I'm not as regular of a contributor as some others, so I'll let someone else weigh in on that.

**Comment by claell** [comment]
Ah, alright, makes sense. Can I change this now to target to master?

Will also change variable names etc.

**Comment by SecondFlight** [comment]
Before you target master, let's make sure nobody has objections to targeting `1.2`. Changes to `1.2` are regularly merged into master.

You can't just change the target to master without breaking a *lot*. You would have to:

1. Clone master
2. Re-apply your changes
3. Create a new PR

**Comment by claell** [comment]
Ok. Have created some more commits now to hopefully rename all instances of FX Mixer. I split it up into many commits to make it easier to follow the search and replace changes.

**Comment by tresf** [comment]
`stable-1.2`  is bug-fix only.  Please re-target.

> Not tested.

All changes should be tested.  If not, you're asking the developers to test for you, which is asking them to work on a task you invented.

> I currently only renamed String texts imho, but can also rename classes, variable names etc.

Why cause inconsistencies in the codebase?

**Comment by tresf** [comment]
> If this is not wanted, just say

~~Why cause inconsistencies~~ Please do not cause inconsistencies in the codebase.

**Comment by claell** [comment]
Closing to create another PR for `master`.

**Comment by tresf** [comment]
FYI, PRs can also be retargeted.  It can get messy with largely-diverged branches like ours, so this is just for information purposes. :)

image

**Pull request closed without merging**
