### PR TITLE
Redesign Stereophonic Matrix

### PR DESCRIPTION
**Pull request by Umcaruje**
Per #2978 and #2831

Screenshot:
screenshot from 2016-08-21 01 04 24

@RebeccaDeField 

P.S. The top left corner looks kinda empty to me, I guess some kind of texture could be added to make it more interetsting, since we don't want any titles. Anyhow, I couldn't come up with anything, so I might as well leave it as-is.

### CODE REVIEW

**Comment by Umcaruje** [comment]
After feedback I have recieved on the discord group, the plugin looks like this: 
screenshot from 2016-08-21 18 33 55

I renamed it to `Stereo Matrix` rather than `Stereophonic Matrix`, so the title fits to the window. The previous plugin artwork called the plugin Stereo Matrix, and its folder is also called stereo_matrix, so I think this rename is consistent.

**Comment by Umcaruje** [comment]
Made all the lines parallel, the plugin is wider so the padding is consistent on top and sides:
screenshot from 2016-08-21 21 16 48

**Comment by BaraMGB** [comment]
That's really great!

**Comment by Spekular** [comment]
Maybe you could shift the middle two lines out a little so they align with the knob when it's centered? This looks really good though. 

(Apologies if this comment shows up twice, I'm posting it a second time as it doesn't seem to have showed up the first time)

**Comment by Umcaruje** [comment]
Per @Spekular the middle lines are now centered to the knobs:
screenshot from 2016-08-22 23 24 38

**Comment by zonkmachine** [comment]
A thought just popped up. Shouldn't the indicator line ( green glow lining ) trail from zero (middle) and out when the amp is -1.0 to 1.0  like the `Amount` knobs under the `ENV/LFO` tab?

PS. Awesome job everyone with the plugins! :+1:

**Comment by Umcaruje** [comment]
Good catch @zonkmachine. Fixed it:
screenshot from 2016-08-23 21 54 02

**Pull request merged**
