### PR TITLE
Proposed fix for 1345 Exclude tracks from master pitch

### PR DESCRIPTION
**Pull request by curlymorphic**
Proposed fix for #1345 Exclude tracks from master pitch

image

### CODE REVIEW

**Comment by tresf** [comment]
Creative... I like the departmentalization of this button (and more to come, right?)

Can we use styling that is more consistent with the other tabs?

screen shot 2015-01-10 at 3 10 15 pm

**Comment by curlymorphic** [comment]
sure,

> Can we use styling that is more consistent with the other tabs?

sure.

so a groupbox, with the checkbox in the header, and the description as the content text>

**Comment by tresf** [comment]
:+1:

**Comment by curlymorphic** [comment]
How is the wording and layout on this?

image

**Comment by tresf** [comment]
I like the word "inherit" and "break inheritance" personally.  More opinions welcome.

**Comment by curlymorphic** [comment]
My use of words is sometimes not the best :(, so really im after 2 lines

1) Group box heading (currently "MASTER PITCH")
2) description text (currently "Enables the use of master pitch")

**Comment by tresf** [comment]
I would vote:

 >  [ . ] INHERIT MASTER PITCH
 >  When unchecked, this instrument ignores the master pitch slider.

Which puts a bit of help text in there (something we don't normally do) so opinions welcome @Umcaruje @StakeoutPunch

**Comment by tresf** [comment]
Also @curlymorphic the font size looks a bit large in you preview.  Is that normal for your computer, or is there something off in the code/CSS?

**Comment by curlymorphic** [comment]
@tresf 

> Also @curlymorphic the font size looks a bit large in you preview. Is that normal for your computer, or is there something off in the code/CSS?

it was me. Have now copied the relevant line of code from the midi tab to keep consistency.

Another Screenshot showing proposed text, with a midi tab open for comparision.

image

**Comment by tresf** [comment]
Well done.  If people have issues with the text, we can make those tweaks later.  Thanks!!!

**Comment by curlymorphic** [comment]
Sorry that was only a screen shot, i had not updated the pull request. 

will do so now

**Comment by Sti2nd** [comment]
The first text wasn't understandable, the last is. :)

**Pull request merged**
