### PR TITLE
Simpler SF2 Player file dialog.

### PR DESCRIPTION
**Pull request by karmux**
Copied from GIG Player. Opens correct SF2 plugin directory when running LMMS from build directory without install. Used to open LMMS build directory before.

### CODE REVIEW

**Comment by Umcaruje** [comment]
I think this fix should be targeted at `stable-1.2`.

**Comment by tresf** [comment]
> just to explain, the problem occured when you had an already loaded soundfont, and the file dialog wouldn't open at its location, rather opened at the last browsed folder.

I think we have a few areas where this bug occurs (e.g. saving a project, opening a project).  I find myself desiring this same behavior in other dialogs.

>  I can confirm the fix

Great we can merge.

> I think this fix should be targeted at stable-1.2.

Agreed.

**Comment by tresf** [comment]
Well, changing the branch didn't do well.  Perhaps we can cherry-picked back onto stable.

image

**Comment by Umcaruje** [comment]
@tresf I think we should change the default branch to `stable-1.2` on github. Also I think all future small fixes like this can be targeted to stable-1.2 with no problems @karmux

**Comment by tresf** [comment]
> @tresf I think we should change the default branch to stable-1.2 on github. Also I think all future small fixes like this can be targeted to stable-1.2 with no problems @karmux

We did that for `stable-1.0` as well since so many bugfixes were hitting it in a short period of time.  I'll do that now however we should switch it back shortly after release.

**Comment by tresf** [comment]
> I'll do that now

Done.

**Comment by tresf** [comment]
Cherry-picked to `stable-1.2` via 09c9ccb

**Pull request merged**
