### PR TITLE
Fix loop condition in project rendering (#3105, #2030)

### LINKED ISSUE #2030: Numerator Automation
LMMS only exports song until automation track changes the value for the numerator. Then the export stops and I'm left with half a song :(

I'm on LMMS 1.1.3 Windows 10

### PR DESCRIPTION
**Pull request by PhysSong**
Fix loop condition in ProjectRenderer::run().
It fixes #2030 clearly.
@DeRobyJ Could you test this for #3105?

Based on https://github.com/LMMS/lmms/issues/3105#issuecomment-2626364333
(The idea from @softrabbit)

### CODE REVIEW

**Comment by qnebra** [comment]
Numerator automation fixed, but I don't know nothing about second issue.

**Comment by zonkmachine** [comment]
> Tested this with all 3 export modes and it works perfectly :+1:

Then I suggest merging this.  :tractor:

**Comment by Umcaruje** [comment]
:+1:

**Comment by Umcaruje** [comment]
Thank you for your contribution @PhysSong

**Pull request merged**
