### PR TITLE
Remove the missing `spoken.flac` file in unfa - Spoken

### LINKED ISSUE #3167: Unfa - Spoken missing a sample
unfa
'Nuff said

### PR DESCRIPTION
**Pull request by Rossmaxx**
fixes #3167 

I would appreciate if anyone could check the file for upgrade routines for me as i can't check it by myself.

### CODE REVIEW

**Comment by zonkmachine** [comment]
As I recall it the sample was left out for a reason. Taken from memory, I believe you were supposed to drop in a spoken message of your own device. Artistic stuff. If you want to remove it you should perhaps ask the original creator @unfa.
Isn't there a sample with silence we can drop in as a replacement of the missing file?

**Comment by tresf** [comment]
> As I recall it the sample was left out for a reason. Taken from memory, I believe you were supposed to drop in a spoken message of your own device. Artistic stuff. If you want to remove it you should perhaps ask the original creator @unfa. Isn't there a sample with silence we can drop in as a replacement of the missing file?

No, it's just missing because we can't bundle samples yet.  Instructions for obtaining the sample are explained here: https://lmms.io/lsp/?action=show&file=4929

This really needs to be fixed.

**Comment by tresf** [comment]
> I would appreciate if anyone could check the file for upgrade routines for me as i can't check it by myself

The LSP says 0.4.14-rc, created for 1.0.0.  Editing it with an old version could satisfy any paranoia; or attempt to decompress, edit, and recompress without using LMMS. 😈

**Comment by Rossmaxx** [comment]
Just a doubt, would it make sense to add the missing `spoken.flac` file into the factory samples and change the project file to point to that file instead?

**Comment by tresf** [comment]
> Just a doubt, would it make sense to add the missing `spoken.flac` file into the factory samples and change the project file to point to that file instead?

This was discussed 10 years ago and we didn't want one-off samples added.   Somehow it snuck past us.

**Comment by tresf** [comment]
> fixes #3167
> 
> I would appreciate if anyone could check the file for upgrade routines for me as i can't check it by myself.


What version did you use to strip it out?  Visiting upgrade routines might be too much work for a single project.

**Comment by Rossmaxx** [comment]
> We didn't want one-off samples added.

IMO, it's better to have complete projects, even if it means one-off samples. Also, the old sample library is deprecated anyway so shouldn't be much of a concern. I'll think of adding the sample once @unfa approves.

**Comment by Rossmaxx** [comment]
> What version did you use to strip it out?

The latest nightly. I asked someone to check out just to make sure i messed nothing up.

**Comment by tresf** [comment]
> > We didn't want one-off samples added.
> 
> IMO, it's better to have complete projects, even if it means one-off samples. Also, the old sample library is deprecated anyway so shouldn't be much of a concern. I'll think of adding the sample once @unfa approves.

We're not adding it.

**Comment by Rossmaxx** [comment]
> We're not adding it.

Alrite then.

**Comment by tresf** [comment]
> > What version did you use to strip it out?
> 
> The latest nightly. I asked someone to check out just to make sure i messed nothing up.

That's where your risk lies.  😂 You can export to mmp and do a diff but they have a tendency to not maintain parameter ordering so it's harder to find differences.

I would advise to use 0.4.15 or 1.0.0 and remove it.  Worst case, a stable version.

**Comment by tresf** [comment]
> > > What version did you use to strip it out?
> > 
> > 
> > The latest nightly. I asked someone to check out just to make sure i messed nothing up.
> 
> That's where your risk lies. 😂 You can export to mmp and do a diff but they have a tendency to not maintain parameter ordering so it's harder to find differences on larger projects.
> 
> I would advise to use 0.4.15 or 1.0.x and remove it. Worst case, a newer stable version.

So 0.4.15 has an error opening this file, says a plugin is missing.  Trying 1.0.3, which is the last stable 1.0.x release.

**Comment by zonkmachine** [comment]
> > As I recall it the sample was left out for a reason...
> 
> No, it's just missing because we can't bundle samples into projects yet. Instructions for obtaining the sample are explained here: https://lmms.io/lsp/?action=show&file=4929

OK. As false memories goes, that one was elaborate.

**Comment by tresf** [comment]
I've removed the sample and I'm currently exporting the WAV with 1.0.3;  I'll then compare the resulting wave to master to see how it bodes.   If all goes well, I'll push the 1.0.3 patched mmpz to this branch and close this issue.

@zonkmachine I had forgotten all these years later how long exports took back then... do you remember?  The song played at normal speed. 💀 💀 💀

**Comment by zonkmachine** [comment]
> @zonkmachine I had forgotten all these years later how long exports took back then... do you remember? The song played at normal speed. 💀 💀 💀

I do remember this vagely but my machine back then was on the weaker side so I have nothing to compare it with. And then I downgraded to a 2011 netbook...

**Comment by tresf** [comment]
> I've removed the sample and I'm currently exporting the WAV with 1.0.3; I'll then compare the resulting wave to master to see how it bodes. If all goes well, I'll push the 1.0.3 patched mmpz to this branch and close this issue.

The export suffered underruns in both exports.  This is disheartening.  Unfa Spoken strikes again 2024, I guess.

Well, I'm going to push this patched file.  If there are regressions, we can always try to patch the xml manually.

**Pull request merged**
