### PR TITLE
Change the minimum width of the B&B editor

### PR DESCRIPTION
**Pull request by Umcaruje**
Adresses https://github.com/LMMS/lmms/issues/2636#issuecomment-222775333

Before:
screenshot from 2016-06-01 00 43 06

After:
screenshot from 2016-06-01 00 41 38

### CODE REVIEW

**Comment by RebeccaDeField** [comment]
Perfect, thank you!

**Comment by IvanMaldonado** [comment]
What happens when you add more steps?

**Comment by tresf** [comment]
Changing the default width for better sane defaults/cosmetic reasons versus changing the minimum width are two separate things.  As long as we allow shorter step counts, shouldn't we allow smaller window sizes?

**Comment by RebeccaDeField** [comment]
@tresf I see what you are saying. I thought that making a minimum size would help with having just one less variable that made the BBeditor pixelated, but if it causes usability issues, then just making it default to the right size could be a great solution too.

**Comment by tresf** [comment]
It's a benign change.  We'll get more feedback when RC2 is release and it's easy enough to revert if people complain.

BTW, we're still dealing with magic numbers here... The value of `384` I assume is the width of the other components to the left such as the track label, etc.  This WILL be problematic if anything changes size due to a theme, a higher resolution display, etc.  The proper fix would be to eliminate the magic number completely.

**Comment by Umcaruje** [comment]
> The value of 384 I assume is the width of the other components to the left such as the track label

No, actually those are some hard-coded variables that are taken to account. The `384` is actually the width of a default B&B pattern (16 step pixmaps + the various spacing between them).

**Pull request merged**
