### PR TITLE
Fix dialog button mismatch

### LINKED ISSUE #2518: Recover file dialog buttons mismatch
LMMS master branch, built yesterday (https://github.com/LMMS/lmms/commit/d30a7df965c99a91706ba89f8d5e215efa7420b8).

OS: Elementary OS Freya x64, Ubuntu based distro.

When I crash LMMS and an recovery is attempted, the dialog looks like this: 
screenshot from 2016-01-25 21 27 39

Instead of this (Picture from #2176)
image

So the 'discard' button became 'Close without saving' and also the actual order of the buttons changed. 

On the other hand, I think the order of the buttons should be the same as the order of the columns (recover, ignore, discard, exit rather than recover, discard, ignore, exit).

I also think that 'Quit' should be renamed to 'Exit' in the text.

I'm sorry for pointing out these issues now, but I never got around testing #2176

Tagging @zonkmachine since he's the author of the mentioned PR.

### PR DESCRIPTION
**Pull request by Umcaruje**
Fixes #2518

Added/designed missing icons for the other 3 buttons. All buttons are now manually added. The ordering is done relative to the OS, and I don't think that should get fixed since qt probably has a good reason for it.

Sreenshots:
Qt4:
screenshot from 2016-07-11 00 05 11
Qt5: 
screenshot from 2016-07-11 00 04 34

Testing on as many platforms would be appreciated, I'll see to make some windows builds (@tresf, when you get back from Vacation, could you test on a Mac?)

### CODE REVIEW

**Comment by zonkmachine** [comment]
Cool!

Maybe the order of Recover and Discard should be switched, either in the menu or the buttons?

> Testing on as many platforms would be appreciated

Release Linux Mint 17.3 Rosa 64-bit
MATE 1.12.0
Qt4, classic and default.

recoverscreenclassic

recoverscreendefault

**Comment by Umcaruje** [comment]
>Maybe the order of Recover and Discard should be switched,

You mean Discard and Ignore?

**Comment by zonkmachine** [comment]
> You mean Discard and Ignore?

Yes.

**Comment by Umcaruje** [comment]
screenshot from 2016-07-11 01 31 00
Done.

**Comment by zonkmachine** [comment]
Yup, It's a keeper!

**Comment by teeberg** [comment]
I was trying to reproduce on a Mac to post back a screenshot, but can't seem to get it to open. Could you post instructions on how to get to that dialog? I tried both running lmms twice and to `kill -9` it, but the dialog never shows up.

**Comment by zonkmachine** [comment]
> Could you post instructions on how to get to that dialog?

Start lmms from the command line and force quit from the same. Then start again.

**Comment by zonkmachine** [comment]
> I tried both running lmms twice and to kill -9 it, but the dialog never shows up.

This should work. If you run from the build directory you may have to reselect auto save as we now have a separate .lmmsrc file ( per folder or per build directory... don't quite remember )

**Comment by teeberg** [comment]
Oooh, sorry about that, I thought this was around the "Create backup file when saving a project". I didn't see the auto-save one before. So, here we go:
#### Mac OS X 10.11.5, Qt 5.6.1
image

**Comment by Umcaruje** [comment]
@teeberg does the button order make sense to you, as a Mac user? Qt changes the button order depending on the OS, to provide a consistent look and feel over applications, but I'm not sure how applicable this is in this case.

**Comment by teeberg** [comment]
To me, it would feel more intuitive to have the buttons be in the same order as the text. Although that still requires me to map the button texts to their meanings.

How do you feel about making the descriptions the buttons? Instead of having a table with button names and descriptions and those four buttons at the bottom. I.e. have 4 big buttons, one on top of each other, with the descriptions instead of the short names, and completely lose the "Recover"/"Discard"/'Ignore"/"Exit" names.

**Comment by Umcaruje** [comment]
>How do you feel about making the descriptions the buttons? Instead of having a table with button names and descriptions and those four buttons at the bottom. I.e. have 4 big buttons, one on top of each other, with the descriptions instead of the short names, and completely lose the "Recover"/"Discard"/'Ignore"/"Exit" names.

I feel like this would be inconsistent with the rest of the software.

I think I'll just make all the buttons the same role, so we can have custom ordering on all platforms

**Comment by Umcaruje** [comment]
Ok, setting all the buttons to `AcceptRole` doesn't work, produces opossite order on qt4 and qt5

**Comment by liushuyu** [comment]
>I think I'll just make all the buttons the same role, so we can have custom ordering on all platforms

I am totally agree with this. And It seems that the biggest difference is on the Mac. :+1:

**Comment by Umcaruje** [comment]
When I set all the buttons to the same role, I get this: 
screenshot from 2016-07-24 16 04 37
screenshot from 2016-07-24 16 00 43

Top is Qt5, bottom qt4

**Comment by Spekular** [comment]
@Umcaruje at least its more consistent than before. Isn't the goal to be
entirely on qt5 at some point anyway?

**Comment by Umcaruje** [comment]
Ok here are the changes I've done:
* I've hidden the Exit button by making it captionless and flat, and reinstated a close button to the dialog, so now when you press `esc` or the close button, the dialog exits.

* I've changed the order of the buttons and text, so there is a more consistent flow for users when looking at the dialog. Here's an article on the topic: http://uxmovement.com/buttons/why-ok-buttons-in-dialog-boxes-work-best-on-the-right/

* The buttons now all have the same role, and I added an if statement to check for the Qt version, and add them in the reverse order for qt4.

Screenshots:

Qt4: 
screenshot from 2016-07-25 02 28 17

qt5:
screenshot from 2016-07-25 02 30 16

**Comment by Umcaruje** [comment]
>qt4

Weird, that's opposite then what I have when I compile with qt4 ...

What's your Distro?

**Comment by zonkmachine** [comment]
Version 1.1.90-g18439ed (Linux/x86_64, Qt 4.8.6, GCC 4.8.4)
Release Linux Mint 17.3 Rosa 64-bit
MATE 1.12.0

**Comment by Umcaruje** [comment]
Ok, so I did some testing. On unity, the order on qt4 is correct:
screenshot from 2016-07-25 23 56 54
The order is also correct on Gnome.

But when I tested on Xubuntu, the order appeared reversed, just like in @zonkmachine's screenshot.

Anyways, I think this can't go any better. Some testing on Mac and Windows would be nice.

**Comment by Umcaruje** [comment]
screenshot from 2016-07-26 00 43 02

This is the final look, made the exit button not visible, so it centers properly.

**Comment by zonkmachine** [comment]
Tested! Cool, like the last shot but buttons centred.

**Comment by Umcaruje** [comment]
Self merging in 12 hours if there are no objections.

**Pull request merged**
