### PR TITLE
Add option to set the list of plug-ins to build

### LINKED ISSUE #2580: -DWANT_MINIMAL
Git bisect is a wonderful tool but it takes time. I suggest, just a thought, that we make a
new compile option MINIMAL which lets you build lmms without most of the pluggins.
We have little use of it today but I suspect that we'll have good use of it a year from now.
Many times when I bisect I test against the previous stable release so for this to work it
should be included now for 1.2

```
ADD_SUBDIRECTORY(kicker)
ADD_SUBDIRECTORY(triple_oscillator)

IF(NOT WANT_MINIMAL)
ADD_SUBDIRECTORY(Amplifier)
ADD_SUBDIRECTORY(Bitcrush)

...


ENDIF()
```

Test builds after make clean. This doesn't mean that an actual bisect will take half the time but it will cut it significantly. Two lines of code well spent I say.

```
cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=DEBUG

real	5m50.047s
user	9m55.876s
sys	0m51.896s


cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=DEBUG -DWANT_MINIMAL=ON

real	2m44.669s
user	4m43.520s
sys	0m24.904s
```

### PR DESCRIPTION
**Pull request by jasp00**
This fixes #2580. Configure with `-DPLUGIN_LIST="audio_file_processor kicker triple_oscillator"`.

### CODE REVIEW

**Comment by zonkmachine** [comment]
Tested, cool! I still would want the actual wording "minimal" in there. I liked it. :wink: 
Something like this right before `SET(PLUGIN_LIST ...`

```cmake
IF(MINIMAL)
	SET(DEFAULT_PLUGINS
		audio_file_processor
		kicker
		triple_oscillator
	)
ENDIF()
```

**Comment by tresf** [comment]
I think the more important part is @zonkmachine's recommendation to make a clear distinction that the AFP, Kicker and 3xOsc are what the devs consider a minimalist installation.  Without these three plugins, the default template has dummy tracks; the software can't be used for all that much.

Someone that builds other projects would vote for `LMMS_MINIMAL` to prevent any clobbering of the word `MINIMAL` in other projects, etc.

So probably... 
```cmake
IF(LMMS_MINIMAL)
    SET(LMMS_PLUGINS
        audio_file_processor
        kicker
        triple_oscillator
    )
    MESSAGE( "Using minimal plugins: ${LMMS_MINIMAL}")
ELSE()
   SET(LMMS_PLUGINS
      Amplifier
      audio_file_processor
      BassBooster
      # [... and so on ]
   )
ENDIF()

STRING(REPLACE " " ";" LMMS_MINIMAL "${LMMS_MINIMAL}")

FOREACH(PLUGIN ${PLUGIN_LIST})
   ADD_SUBDIRECTORY(${PLUGIN})
ENDFOREACH()
```

**Comment by tresf** [comment]
Or take it a step further and check for `LMMS_PLUGINS` on command line first, then check `LMMS_MINIMAL`, then default to all so that a user can specify specific plugins.  I would also recommend putting that into the minimal message:

> Note: You can specify specific plugins using `-DLMMS_PLUGINS="foo bar"` 

... etc

**Comment by tresf** [comment]
@jasp00 looks great although I think it could be simplified even further.

```cmake
IF(LMMS_MINIMAL)
   # Minimal build, only use the following plugins
   SET(PLUGIN_LIST 
      audio_file_processor
      kicker
      triple_oscillator
   )
   MESSAGE("-- Using minimal plug-ins: ${PLUGIN_LIST}\n"
      "   Note: You can specify specific plug-ins using -DPLUGIN_LIST=\"foo bar\"")
ENDIF()

IF("${PLUGIN_LIST}" STREQUAL "")
   # No plugin list provided, use default
   SET(PLUGIN_LIST
         audio_file_processor
         Amplifier
         BassBooster
         bit_invader
         Bitcrush
         carlabase
         # [...]
    )
ENDIF()

# Done, do ";", FOREACH, etc.
# [...] 
```

**Comment by zonkmachine** [comment]
Tested. :+1:  I think this works really well.

```cmake
         IF(NOT LMMS_BUILD_APPLE)
            SET(LMMS_PLUGINS ${LMMS_PLUGINS} sf2_player)
         ENDIF()
```
Looks like you can't put it in the set list though, but it needs to go in that if or sf2 player will build.

**Comment by zonkmachine** [comment]
I can totally work with this. What I would find more logical is if the LMMS_MINIMAL selection would be kept even if you add other plugins with PLUGIN_LIST.
So `-DLMMS_MINIMAL=ON -DPLUGIN_LIST="stk"` would generate `audio_file_processor kicker   triple_oscillator stk` and not just `stk`

**Comment by jasp00** [comment]
>So `-DLMMS_MINIMAL=ON -DPLUGIN_LIST="stk"` would generate `audio_file_processor kicker triple_oscillator stk` and not just `stk`

Done.

**Comment by zonkmachine** [comment]
Spot on! :+1:

**Comment by tresf** [comment]
👍

**Pull request merged**
