### PR TITLE
shortcut refactor for songeditor

### PR DESCRIPTION
**Pull request by BaraMGB**
This cleans up the keyboard short cuts for the song editor to being consist with the Piano Roll editor. I want to have the same behavior as in the Piano Roll editor.

What is implemented so far:

**hold Ctrl - toggle to selection mode**
you can select your Tcos and by release the Ctrl key it turns back into draw mode.

**deselect all selections by:**
click on empty space (new Tco)
click on unselected Tco
[Ctrl] + [shift] + A
[Esc]

**select all Tcos**
[ctrl] + A
*EDIT*:
**[Ctrl] + drag**
copies a selection or an unselected Tco
no matter the mode (draw or selection)

**click + drag**
moves a selection or an unselected Tco
no matter the mode (draw or selection)

**[DEL]**
deletes all selected Tcos

### CODE REVIEW

**Comment by tresf** [comment]
Ctrl-dragging is proper copying in my opinion, not shift.  Isn't this how we copy full tracks?

**Comment by BaraMGB** [comment]
Then we should change this in the piano roll. But I fear the short cuts of the piano roll are more burned to the brain of the users than the cuts of the song editor. Piano roll should be our basis. There the people work at most.

**Comment by grejppi** [comment]
Ctrl+dragging sounds more like copying to me too. I still get really confused by Shift+dragging in the Piano Roll 😥

**Comment by tresf** [comment]
> Ctrl+dragging sounds more like copying to me too.

Ctrl+drag is the default for Windows and Ubuntu to make a copy of a file.  (Mac uses Shift + Alt).

**Comment by Umcaruje** [comment]
I vote for ctrl+drag as well, it's consistent with the other software I use :+1:

**Comment by BaraMGB** [comment]
I'll try my best. 😑

**Comment by BaraMGB** [comment]
I have updated this PR. [Ctrl] is now for copy. For Piano Roll Editor though I'll make a new pull request. This will be a deeper dive into the code. 

This PR should be tested.

**Comment by PhysSong** [comment]
The Qt4 builds fails, because of QAction::triggered(). I think it should be replaced with QAction::trigger() or QAction::activate(QAction::Trigger).
@BaraMGB @tresf @Umcaruje Please test this suggestion for both Qt4 and Qt5.

**Comment by BaraMGB** [comment]
@PhysSong thank you.

**Comment by zonkmachine** [comment]
Tested. :heart: 

When you delete a whole lot at once and go Ctrl+z to undo, the undo action is done in steps. I think it should all be done in one step.

**Comment by BaraMGB** [comment]
@zonkmachine  

>>When you delete a whole lot at once and go Ctrl+z to undo, the undo action is done in steps. I think it should all be done in one step.

that sounds good. Can you give me a hint how to do so?

**Comment by tresf** [comment]
Agreed.  The journaling should record everything between mouse press and mouse release when deleting.

**Comment by zonkmachine** [comment]
> that sounds good. Can you give me a hint how to do so?

Sorry, no.

**Comment by PhysSong** [comment]
Well, there are several methods to do so. An example is modifying `ProjectJournal` class to enable squashing of journaling points.
Another example, modifying `TrackContainerObjectView::remove` to `TrackContainerObjectView::remove( bool createJournalingPoint = true )` and add journaling point of whole song(I think it is simple but inefficient).

**Comment by BaraMGB** [comment]
>An example is modifying ProjectJournal class to enable squashing of journaling points.

For this one I need help. I don't get how to do this. @PhysSong

**Comment by PhysSong** [comment]
@BaraMGB I think it will take some time to do such things. I'll give it a try soon.

**Comment by PhysSong** [comment]
```cpp
const int ProjectJournal::MAX_UNDO_STATES = 100;
```
It brings another problem: If I delete more than 100 TCOs, I can't undo it completely.

**Comment by zonkmachine** [comment]
> `const int ProjectJournal::MAX_UNDO_STATES = 100;`

Just increase this? Can you count the number of objects and override this MAX when deleting many TCOs at once?

**Comment by PhysSong** [comment]
@zonkmachine Then it shouldn't be `const` anymore. For some projects, 1000 isn't enough. I tried increasing the max number more and more, but I can't completely undo delete for some project because of too much time and memory usage.

**Comment by zonkmachine** [comment]
I don't know. Maybe it's leaner and faster to copy the complete project at a certain point?
How strong is your machine?

**Comment by PhysSong** [comment]
CPU: Intel® Core™ i5-4210M
RAM: 4GB

For demo project `BuzzerBeater`, It takes memory more than 1GB.

**Comment by BaraMGB** [comment]
@zonkmachine wrote:
>>When you delete a whole lot at once and go Ctrl+z to undo, the undo action is done in steps. I think it should all be done in one step.


By investigate some PR and issues and test a little bit in lmms I came to the conclusion that the UNDO-System of lmms needs a lot of work. But I don't think, this is in the scope of this PR. (For example: if you copy a bunch of TCOs in master build, you got the same undo issue) 

I have tested this PR and (excepts the undo issue) it works like a charm. I don't wanna work without this changes in the songeditor.  **If there are no other issues with this PR I vote for merging this and file an issue for reworking the UNDO system.** Perhaps @curlymorphic can help here. He introduced the undo for the songeditor here: https://github.com/LMMS/lmms/pull/1699

**Comment by zonkmachine** [comment]
I agree on this and vote merge too.

**Comment by BaraMGB** [comment]
@zonkmachine Thank you. If there are no more objections I will merge it tomorrow. :+1:

**Comment by tresf** [comment]
The description should be updated as to not cause confusion.  Shift + drag seems to have been replaced with Ctrl + drag.

**Comment by tresf** [comment]
Sorry, was reading email and not PR. Description is good. :)

**Pull request merged**
