### PR TITLE
Use Qt's Resource System

### PR DESCRIPTION
**Pull request by Lukas-W**
LMMS has been using some custom code found in [`bin2res.cpp`](https://github.com/LMMS/lmms/blob/v1.1.0/buildtools/bin2res.cpp) to embed resources like pixmaps in binary files. This PR removes that code and introduces the use of the resource system provided by Qt instead (http://qt-project.org/doc/qt-4.8/resources.html).

That means embedded resources are now available through Qt's classes:
```c++
embed::getIconPixmap("project_save");
// becomes
QPixmap("icons:project_save.png");
```

Qt's Resource System reads a list of files to embed from a `.qrc` file that looks something like this:
```xml
<RCC>
	<qresource prefix="lb302">
		<file>artwork.png</file>
		<file>logo.png</file>
	</qresource>
</RCC>
```
I didn't want to write all those files for every single plugin, so I wrote a CMake script that generates them instead, see [`GenQrc.cmake`](https://github.com/LMMS/lmms/blob/9e0e63b9ff97b04723a2e417905ffffea276399d/cmake/modules/GenQrc.cmake). It works like this:
```cmake
ADD_GEN_QRC(RCC_OUT lmms.qrc PREFIX /icons
    lmms-icon.png happy-devs.png 
)
ADD_EXECUTABLE(lmms
    main.cpp some.cpp other.cpp sources.cpp ${RCC_OUT}
)
```

Also, a lot of plugins had the same "logo" (shown below) included that wasn't even visible in the UI. I removed those files in ec5b10b.
plugin logo

There's no direct user benefit in this, it's just some sort of cleaning up. Nevertheless, the changes are quite huge, so it'd be great if we could get a few people to test if all plugins' pixmaps/logos still load correctly, especially when using different themes.

### CODE REVIEW

**Comment by Spekular** [comment]
@Lukas-W Seems pretty great! I'll do some testing if I get the time.

**Comment by tresf** [comment]
If plugins had the ability to offer icons for each we should consider displaying them.

I understand the GUI has no such place for these currently, but the idea has value.  For examole, browsing FX plugins by name leaves a bit to be desired from a UI perspective.

**Comment by tresf** [comment]
Quite a bit of code cleanup here.  Nice work @Lukas-W.

As I understand it, this means we now specify the file extension for our pixmaps.  Does this consequently introduce the availability of SVG artwork now?

I've reviewed the changes from a code perspective and they look great. :+1: 

-Tres

**Comment by curlymorphic** [comment]
Nice work lukas :) I do like the Qt resource system.



> As I understand it, this means we now specify the file extension for our pixmaps. Does this consequently introduce the availability of SVG artwork now?

According to the Qt documentation you cant load a svg directly into a QPixmap. If I am reading it correctly The Qtmodule that handles svg is not GPL, but someone else should read that before taking my word for it.

http://qt-project.org/doc/qt-4.8/qtsvg.html.

> If plugins had the ability to offer icons for each we should consider displaying them.

I do like this idea, a picture paints a thousand words as they say. There are a few things that would need to be sorted. currently we display all plugin effects in a single list, native, Ladspa and vst and hopefully more formats to be supported in the future. Not all these formats support icons iirc. As Lukas has already pointed out most of the native plugins use the same icon (yes im guilty of this) So we would need to produce these.

**Comment by badosu** [comment]
Gonna test here! Amazing Yak-Shaving skills :-)

**Comment by badosu** [comment]
@Lukas-W It is really hard to review the changes when your editor automatically fixes code style.

**Comment by Lukas-W** [comment]
> @Lukas-W It is really hard to review the changes when your editor automatically fixes code style.

Yeah, sorry for that. It was too late when I noticed it.

**Comment by diizy** [comment]
@tresf "Does this consequently introduce the availability of SVG artwork now?"

No, because we already have that ability - it was implemented by Raine some time ago. We just haven't utilized it yet.

**Comment by tresf** [comment]
> No, because we already have that ability - it was implemented by Raine some time ago. We just haven't utilized it yet.

:+1:

**Comment by Lukas-W** [comment]
New approach: #1891

**Pull request closed without merging**
