### PR TITLE
Run `dos2unix`

### PR DESCRIPTION
**Pull request by rdrpenguin04**
Every CRLF line ending in the main repo should now be replaced with LF. I tried to only touch text files, but it's possible something slipped through the cracks.

Let me know if you have any questions!

### CODE REVIEW

**Comment by rdrpenguin04** [comment]
I just got around to testing the modified `.ds` and `.xiz` file(s); they work! If anyone else has edge cases to test, feel free; I think this should be set though.

**Comment by superpaik** [comment]
Interfase works well, instrument presets work well, midi import/export as well. Tested on W10.

**Comment by JohannesLorenz** [comment]
@rdrpenguin04 I'll merge this now. Want squash or rebase+ff?

**Comment by rdrpenguin04** [comment]
Probably squash

**Comment by tresf** [comment]
> This seems like a good opportunity to add CRLF fixing to `.gitattributes` as well, so that `dos2unix` won't have to be run again. I found a good article on the subject here: https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/. Besides that, this looks fine to me!

Late to this PR, but @TechnoPorg thanks for this insight, it's helped me on [another project](https://github.com/java-native-access/jna/pull/1273#issue-748316737) as well. 👌

**Pull request merged**
