### PR TITLE
Specify DirectConnection for a few plugins

### LINKED ISSUE #5665: LFO Controller/Automation exports poorly
### Bug Summary
Automating a property with an LFO Controller works fine in real-time playback, but it seems to be only *occasionally* sampled on export (regardless of the file format AFAIK), and sounds "stepped" as a result

#### Steps to reproduce
LMMS project file
[bugrep.zip](https://github.com/LMMS/lmms/files/5160846/bugrep.zip)

Listen to the project file first, and then export to WAV or some other format

<details>
if you want to do it manually with the default file:<br>

1. Add an LFO Controller with any settings (Sine wave and tempo-synced to Eight Beats for example)<br>
2. Connect it to a Coarse Detuning knob in the TripleOscillator<br>

3. Add a pattern with a long note and play it in the Song Editor; the TripleOsc should sound fine as expected<br>
4. Export it to some audio file format and listen to the exported file<br>
</details>

#### Expected behavior
The exported audio file sounds like the real-time playback of LMMS with no issues

#### Actual behavior
The exported audio file has very noticeable "jumps" in the LFO Controller

#### Screenshot
A little comparison of an exported file from LMMS (top track) and recorded real-time output from LMMS (bottom track) in Audacity
an Audacity screenshot of two tracks

[bugrep-aup.zip](https://github.com/LMMS/lmms/files/5160953/bugrep-aup.zip)

#### Affected LMMS versions
Branch: master. I've noticed this issue on stable 1.2.x as well.
This never occured in 1.1.3.

### PR DESCRIPTION
**Pull request by Firepal**
Fixes #5665.
Continues #4942. (somewhat, at least)

(If i understand this problem right,) some knob connections were automatically set to QueuedConnection, which made them update poorly and thus caused audible "snapping" with knob values in knobs that were automated. Manually setting those connections to DirectConnection fixes that.

The following plugins were changed:

- TripleOscillator
- BitInvader
- AudioFileProcessor
- **Monstro**
- **Nescaline** (haven't tested these last two, but for good measure...)

### CODE REVIEW

**Comment by Firepal** [comment]
Did it for Nescaline detuning knobs at the last minute. Haven't tested, but looks safe. I won't commit any more changes, you can merge if you want.

**Review by DomClark — APPROVED** [review]
Looks good to me. You could also make the volume and pan connections for TripleOscillator direct (just above the other changes in that file).

**Comment by Firepal** [comment]
Shoot. Didn't see those, good eye

**Comment by DomClark** [comment]
This can be merged now - I will do so tomorrow if there are no objections.

**Pull request merged**
