### PR TITLE
Updated Freeboy files from Game Music Emu 0.6.1

### PR DESCRIPTION
**Pull request by karmux**
Following files are from new upstream package:
```
plugins/papu/gb_apu/Blip_Buffer.cpp  
plugins/papu/gb_apu/Blip_Buffer.h
plugins/papu/gb_apu/Blip_Synth.h 
plugins/papu/gb_apu/Gb_Apu.cpp 
plugins/papu/gb_apu/Gb_Apu.h
plugins/papu/gb_apu/Gb_Oscs.cpp 
plugins/papu/gb_apu/Gb_Oscs.h
plugins/papu/gb_apu/Multi_Buffer.cpp
plugins/papu/gb_apu/Multi_Buffer.h
plugins/papu/gb_apu/blargg_common.h
plugins/papu/gb_apu/blargg_config.h
plugins/papu/gb_apu/blargg_source.h
```

These files were updated to work with latest upstream files:
```
plugins/papu/Basic_Gb_Apu.cpp
plugins/papu/Basic_Gb_Apu.h
plugins/papu/CMakeLists.txt
```

### CODE REVIEW

**Comment by zonkmachine** [comment]
stable-1.2-rc3 with (top) and without (bottom) @karmux fix.

freeboyfix

**Comment by karmux** [comment]
> The only local adaptation is one line in plugins/papu/CMakeLists.txt

`plugins/papu/Basic_Gb_Apu.h` and `plugins/papu/Basic_Gb_Apu.cpp` too.

**Comment by zonkmachine** [comment]
OK. Can you then add a description and tell us what's in this PR?

**Comment by zonkmachine** [comment]
@Umcaruje. Do you want me to backport this one?

**Comment by zonkmachine** [comment]
@Umcaruje. Do you want me to backport this one?

**Pull request merged**
