### PR TITLE
Update Chinese translations

### PR DESCRIPTION
**Pull request by liushuyu**
The translation file has been regenerated from the latest master branch of LMMS 
Overall Translation Progress: 1635 of 2627 strings (62.24%)

[Review on Reviewable](https://reviewable.io/reviews/lmms/lmms/2648)

### CODE REVIEW

**Comment by tresf** [comment]
FYI, Travis's Linux jobs seemed to fail on wine (unrelated to Chinese translation).  Restarted.

**Comment by Umcaruje** [comment]
This seems to be an internet connection issue, travis downloads packages at very low speeds (~30 Kbps), so the build just eventually times out before it even finishes the downloading.

**Comment by tresf** [comment]
@Umcaruje thanks for the information.  There's no reason not to merge this. :+1:

**Comment by Umcaruje** [comment]
:+1:

**Pull request merged**
