### PR TITLE
Fix broken FxLine tool tips (#3321)

### PR DESCRIPTION
**Pull request by xy124**
Hi, this is my first contribution, so please tell me if I do something wrong.
I hope many will follow ;)

### CODE REVIEW

**Comment by zonkmachine** [comment]
Tested, fixes https://github.com/LMMS/lmms/issues/3321, thanks!

It looks fine to me but I can't really review the code. If it's acceptable to the rest of the devs I think this should go into stable-1.2 .

Welcome to the lmms but tracker... :)

**Comment by PhysSong** [comment]
It looks fine to me, though I think we may also fix this on a different side.

**Comment by zonkmachine** [comment]
> It looks fine to me, though I think we may also fix this on a different side.

@PhysSong Can you want to be more specific? I would like to push this to stable-1.2 tomorrow if there are no bigger objections.

**Comment by zonkmachine** [comment]
Pushed to stable-1.2 directly. dd6d4a552b3e1c51fc39db7c0cfc19d3f33908ef
@xy124 thanks for the fix!

**Pull request closed without merging**
