### PR TITLE
Add a minimalist build target

### LINKED ISSUE #2580: -DWANT_MINIMAL
Git bisect is a wonderful tool but it takes time. I suggest, just a thought, that we make a
new compile option MINIMAL which lets you build lmms without most of the pluggins.
We have little use of it today but I suspect that we'll have good use of it a year from now.
Many times when I bisect I test against the previous stable release so for this to work it
should be included now for 1.2

```
ADD_SUBDIRECTORY(kicker)
ADD_SUBDIRECTORY(triple_oscillator)

IF(NOT WANT_MINIMAL)
ADD_SUBDIRECTORY(Amplifier)
ADD_SUBDIRECTORY(Bitcrush)

...


ENDIF()
```

Test builds after make clean. This doesn't mean that an actual bisect will take half the time but it will cut it significantly. Two lines of code well spent I say.

```
cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=DEBUG

real	5m50.047s
user	9m55.876s
sys	0m51.896s


cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=DEBUG -DWANT_MINIMAL=ON

real	2m44.669s
user	4m43.520s
sys	0m24.904s
```

### PR DESCRIPTION
**Pull request by Umcaruje**
Supersedes #2581, closes #2580. 

Just implemented the idea from https://github.com/LMMS/lmms/pull/2581#issuecomment-187566013

Tested it out with ninja, works like a charm, and @tresf already tested on make.

### CODE REVIEW

**Comment by zonkmachine** [comment]
Thanks, testing!

**Comment by zonkmachine** [comment]
It works, but one thing I couldn't grasp with solving it with make when I was working on #2581 is how to do a `make install` while being minimal at the same time. `make install` will build the rest of the modules and then install. I quite often end up installing when troubleshooting with `git bisect`.

**Comment by tresf** [comment]
Perhaps more `OPTIONAL` items are in store per http://stackoverflow.com/a/16499905/3196753

**Comment by tresf** [comment]
... or perhaps http://stackoverflow.com/questions/13381742/cmake-exclude-executable-during-install/17202096#17202096

**Comment by Umcaruje** [comment]
Superseded by #2968

**Pull request closed without merging**
