### PR TITLE
Merge branch `stable-1.2` into `master`

### PR DESCRIPTION
**Pull request by liushuyu**
Another merge to keep `master` branch in synchronize and up-to-date.

No sure if I have broken something.

**Directly push to this PR if you have any fix or patch.**

---
This change is [Reviewable](https://reviewable.io/reviews/lmms/lmms/4296)

### CODE REVIEW

**Comment by liushuyu** [comment]
Okay, there's problem with the submodule, investigating

**Comment by PhysSong** [comment]
Fixed submodule. Still needs some more fixes because of 87e6b48df73518b4c43db118374f2d94e034edde and e554a4c4b093ea4c319cceed98f4495484da37b0.

**Comment by PhysSong** [comment]
I've needed to manually adapt two commits to `master` and apply them. I'll test and push it if it works.

**Comment by PhysSong** [comment]
@liushuyu Not pushed to your `master` yet, but you can find that on https://github.com/PhysSong/lmms/commit/9aec1d3868628791c95702f37ad051a878b32753.
Since new commits are added into both `stable-1.2` and `master`, you may need to do a new merge. And why did you removed some trailing whitespaces in `Track.cpp` when merging?

**Comment by liushuyu** [comment]
>Since new commits are added into both stable-1.2 and master, you may need to do a new merge. 

New merge proposed, GitHub acted strangely though, it closed this PR and re-opened during the process.

>And why did you removed some trailing whitespaces in Track.cpp when merging?

Not sure if it's my text editor behavior or `git` merge whitespace suppression.

**Comment by PhysSong** [comment]
Changes in `Track.cpp` look weird. I'll fix it today.

**Comment by liushuyu** [comment]
>Changes in Track.cpp look weird. I'll fix it today.

Thanks a bunch, you have been very helpful.

**Comment by PhysSong** [comment]
@liushuyu Fixed. You may need to force-push new merge one more time because of a new commit on `master`. I hope you don't screw anything up this time if you do so.

**Comment by liushuyu** [comment]
>@liushuyu Fixed. You may need to force-push new merge one more time because of a new commit on master. I hope you don't screw anything up this time if you do so.

It's very tricky to do a correct merge

**Comment by liushuyu** [comment]
Sorry, pressed wrong button.

**Comment by lukas-w** [comment]
Is this ready to merge?

**Comment by PhysSong** [comment]
This is quite out of date, so I think it'd be better to do new and clean merge.

**Comment by liushuyu** [comment]
>This is quite out of date, so I think it'd be better to do new and clean merge.

Sorry for the inactivity. I will address this asap.

**Comment by lukas-w** [comment]
> better to do new and clean merge.

Why do a new one when the merge conflicts have already been resolved?

**Comment by PhysSong** [comment]
Because it will include new commits in `stable-1.2` and make the commit history cleaner.

**Comment by lukas-w** [comment]
> commit history cleaner

You mean the one merge commit less as opposed to doing a second merge after this one? I don't feel that's worth the trouble of re-doing all the work done here, seeing that this PR even still merges cleanly:

image

**Comment by PhysSong** [comment]
> I don't feel that's worth the trouble of re-doing all the work done here

There's an easier trick:
1. Merge updated upstream branches into this `master` branch first.
2. Checkout clean upstream `master` and merge `stable-1.2`. There will be some merge conflicts.
3. Ignore conflicts and commit merge.
4. Hard reset to the merged branch in step 1, and then soft reset to dirty `master`.
5. `git commit --amend`.

FYI, I've done a clean merge on my fork. @liushuyu If you're okay, I'm going to push that.

Again, thank you for doing this work, @liushuyu!

**Comment by PhysSong** [comment]
> it will include new commits in `stable-1.2`

There were no issues when I merge latest `master` into this branch. However, there were some conflicts with `stable-1.2`.

I also needed to fix CALF submodule. It is not easy to work with submodules and hard to notice what goes wrong.

**Comment by PhysSong** [comment]
Pushed `8a41def61629a736fefa19a2ac5c4ea8c0acd928` instead of merging this. Now all commits in `stable-1.2` are synced into `master`.

**Comment by lukas-w** [comment]
Thanks @PhysSong

**Pull request closed without merging**
