### PR TITLE
Allow Apple install step to fail CI

### PR DESCRIPTION
**Pull request by tresf**
Per https://github.com/LMMS/lmms/pull/6782#issuecomment-1663056464

It's tempting to use `COMMAND_ERROR_IS_FATAL <ANY|LAST>`, however this is only available since CMake 3.19.

Please ignore shellcheck, the commit cdeee7e is deliberate and it is temporary.

### CODE REVIEW

**Comment by tresf** [comment]
Failure message:

https://github.com/LMMS/lmms/actions/runs/5746375397/job/15575739762?pr=6796

```
CMake Error at cmake/install/cmake_install.cmake:95 (MESSAGE):
  Execution of install_apple.sh failed
Call Stack (most recent call first):
  cmake_install.cmake:48 (include)
```

**Review by DomClark — APPROVED** [review]
I don't believe you need to use `\n` to get a line break in multiline strings - my understanding is that CMake preserves the line break unless you explicitly ask to remove it by ending the line with a backslash. But it doesn't hurt, and since it's working as is, I don't see any reason to change it.

**Comment by tresf** [comment]
> I don't believe you need to use `\n` to get a line break in multiline strings - my understanding is that CMake preserves the line break unless you explicitly ask to remove it by ending the line with a backslash. But it doesn't hurt, and since it's working as is, I don't see any reason to change it.

Although this statement is true for `CMake`, it is not true for `CMake` interpreting `CMake`.

**Comment by DomClark** [comment]
Interesting. I've tried a simple test case without `\n`s and it Works On My Machine™:
```cmake
cmake_minimum_required(VERSION 3.9)

project(cmake_test)

install(CODE "
  message(\"Line 1\")
  message(\"Line 2\")
")
```
Of course, if omitting them breaks it, leave them in. I'm not sure it's worth investigating why.

**Comment by tresf** [comment]
> Interesting. I've tried a simple test case without `\n`s and it Works On My Machine™:
> 
> ```cmake
> cmake_minimum_required(VERSION 3.9)
> 
> project(cmake_test)
> 
> install(CODE "
>   message(\"Line 1\")
>   message(\"Line 2\")
> ")
> ```
> 
> Of course, if omitting them breaks it, leave them in. I'm not sure it's worth investigating why.

Interesting.   I wonder if it's an `\r\n` nuance or a typo in my testing.  The error was quite obvious, it said that newline was expected while processing `MESSAGE(...)`.

For sale of future code contributions, I'll do some more testing.

**Comment by tresf** [comment]
In hindsight, I think I [hit my own tripwire](https://github.com/LMMS/lmms/pull/6796#issuecomment-1663255278) and misinterpreted `(MESSAGE)` for `MESSAGE()`.  Reverted via 8253a93.

**Pull request merged**
