### PR TITLE
Fixes crash on exit when peak controller is present

### LINKED ISSUE #2604: Crash when closing LMMS if a peak controller is present
To reproduce: have a project open with a peak controller in it somewhere and close LMMS.

I already tried to fix this in the course of fixing #2584, but for every crash I got rid of another one surfaced. Therefore, I'm making this its own issue so it can be thoroughly fixed when someone has the time.

### PR DESCRIPTION
**Pull request by Teuthis**
Closes #2604 
Peak controller destructor was calling PresetPreviewPlayHandle::isPreviewing() after PresetPreviewPlayHandle static member s_previewTC was already destroyed. Added a null pointer test to PresetPreviewPlayHandle::isPreviewing(), returning false if s_previewTC is null.

### CODE REVIEW

**Comment by liushuyu** [comment]
This seems to target #2604

**Comment by liushuyu** [comment]
This worked for me and it seems to be have none or little side effect.

**Comment by Umcaruje** [comment]
@Fastigium could you review/test this one out?

**Comment by Fastigium** [comment]
Looks good to me, and I haven't been able to produce a shutdown crash with it applied. Yay for that! I'd like to see a commit message with lines of <80 chars, but otherwise this seems ready to merge :+1:

**Comment by liushuyu** [comment]
>I'd like to see a commit message with lines of <80 chars

Hmm, hmm :sweat:

**Comment by Fastigium** [comment]
> Hmm, hmm :sweat:

I'm actually not sure if that's LMMS policy, but it was at a different project I used to work for, and I really liked how it made the output of `git log` much more readable :blush:

**Comment by liushuyu** [comment]
Well, I suggest to change it to `Add null pointer check for Peak Controller`(47 characters)

**Comment by Teuthis** [comment]
Sorry about the long commit message. I'm still getting a handle on Github norms. I've amended the commit message on my local copy of the repository, but I haven't force pushed it to Github yet. Will I need to resubmit the pull request after doing so?

**Comment by liushuyu** [comment]
>Will I need to resubmit the pull request after doing so?

No, GitHub can handle force pushes.

**Comment by Teuthis** [comment]
Ok, new commit message is pushed.

**Comment by liushuyu** [comment]
Okay, Travis CI is re-running the tests...

**Comment by Umcaruje** [comment]
>It seems this will work fine. :+1:
aaand travis can't seem to find qt5 packages...

**Comment by Umcaruje** [comment]
@Teuthis can you please rebase this PR so that you get a green light from Travis?

**Comment by Teuthis** [comment]
I hope I did that correctly.

**Comment by jasp00** [comment]
@Teuthis, you can see in your request: Commits 8, Files changed 107. This is not correct.
I am not a Git guru, but follow these steps:

* Grab your patch: `git show 7d8f319 > my.patch`
* Add upstream remote (if not done): `git remote add upstream https://github.com/LMMS/lmms`
* Sync your master branch: `git fetch upstream && git reset --hard upstream/master`
* Apply your patch (`my.patch`), commit and push your changes.

**Comment by Teuthis** [comment]
I fear I'm just making things worse now. I'm tempted to just cancel the pull request altogether, grab a new fork, make the code change, and submit a new pull request. For any git operation more complicated than a simple commit, I feel like a dog trying to use chopsticks.

**Comment by tresf** [comment]
> I fear I'm just making things worse now. I'm tempted to just cancel the pull request altogether, grab a new fork, make the code change, and submit a new pull request. For any git operation more complicated than a simple commit, I feel like a dog trying to use chopsticks.

We've all been there.  Unfortunately, you need to fix your own `master` branch or else all future PRs will be a severe pain in the ass. :)

Reset assured, we can get you there... 

If you have a good copy of the patch lying around as a backup, do this:

```bash
# Go back in time, undo a bunch of stuff
git reset --hard HEAD~100
# Tell git to add a new remote called "upstream".  If it already exists, that's fine!
git remote add upstream https://github.com/LMMS/lmms.git
# Sync your local branch with what's upstream
git pull --rebase upstream master
# Get your own master branch back in sync
git push
```

At this point, when you browse to your fork, it should say you're even with master:

image

Next, apply your patch as you normally would (change the source, commit, push).

When that's done, this PR will look exactly as you intended.  If you need help, I'll jump on `#lmms` on IRC for a while just incase.

**Comment by liushuyu** [comment]
@Teuthis Hey, why closed?

**Comment by Teuthis** [comment]
I followed @tresf 's instructions and when I pushed it closed. I'm not sure where I screwed it up, but I didn't intend to close it.

**Comment by tresf** [comment]
Hmm.. That's fine, must be a GitHub bug/feature :smiling_imp: .  Just open a new PR and we'll happily merge.  `~100` may have been overzealous for an open PR, but at least your master branch is fixed!

**Comment by liushuyu** [comment]
@Teuthis That's right. Sorry for my rude words... But glad to see your contribution! :+1:

**Comment by zonkmachine** [comment]
> I followed @tresf 's instructions and when I pushed it closed. I'm not sure where I screwed it up, but I didn't intend to close it.

Because you pushed no commits at all. It's automatic GitHub behavior.

**Comment by tresf** [comment]
> Because you pushed no commits at all. It's automatic GitHub behavior.

Ah...  Good call @zonkmachine.  So if he had committed his patch prior to pushing, it would have remained open. :+1:

**Comment by liushuyu** [comment]
>Hmm.. That's fine, must be a GitHub bug/feature :smiling_imp: . Just open a new PR and we'll happily merge. ~100 may have been overzealous for an open PR, but at least your master branch is fixed!

@tresf GitHub has many strange "features", did I tell you they banned my account for no reason several days ago ?

**Comment by Umcaruje** [comment]
@Teuthis this is a good read: https://guides.github.com/introduction/flow/

You should generally use seperate branches for PR's and not your master branch, so we avoid these types of situations

**Comment by tresf** [comment]
> @tresf GitHub has many strange "features", did I tell you they banned my account for no reason several days ago ?

`<offtopic>`Yeah I was banned too.  I just clicked "Contact a human" and they restored it almost immediately.  There is usually a good reason.  In my case, my high activity triggered some robot-like heuristics.  For example, often I paste a picture into an empty bug report and then link it in a wiki, etc.  They told me I was incorrectly flagged as a robot.  When they see a bunch of images uploaded to non-existent bug reports, it must raise some flags.`</offtopic>`

**Comment by Teuthis** [comment]
Ok, new pull request (#2788) submitted using a fork instead of master. Travis is looking it over now. I really appreciate all of you taking the time to help me out with this and get me pointed in the right direction. I'll be sure to contribute as much as I can as repayment.

**Pull request closed without merging**
