### PR TITLE
Qt5 compatibility: QAtomicInt, QAtomicPointer casting changes

### PR DESCRIPTION
**Pull request by softrabbit**

### CODE REVIEW

**Comment by tresf** [comment]
Hmm... this probably should have stayed open a bit longer I feel.  I think we can tackle this with an inline `#ifndef` header approach like we do for some other missing or slightly displaced functions (i.e. `isnanf` comes to mind per [lmms_math.h#L38](https://github.com/LMMS/lmms/blob/master/include/lmms_math.h#L38))

**Comment by softrabbit** [comment]
Yeah, but I think it's better to concentrate all this qt5 effort into the one branch, and maybe first get the Travis job passing before fine-tuning. Besides, if Qt4 is to be dropped after 1.2 those #ifdefs might be gone pretty soon anyway.

**Comment by tresf** [comment]
> if Qt4 is to be dropped after 1.2

I don't know if this is a fair assumption to make yet.  We haven't tested the slightest on QT5 on Mac or Windows.

**Comment by Lukas-W** [comment]
> Hmm... this probably should have stayed open a bit longer I feel.

It should. I reverted it in `LMMS:travis-qt5`.

**Pull request merged**
