### PR TITLE
fix eliding issue on fx mixer fader

### PR DESCRIPTION
**Pull request by BaraMGB**
fixes https://github.com/LMMS/lmms/issues/3237

Windows builds for testing can be found here: https://github.com/BaraMGB/lmms/releases/tag/v1.2rc2.8

### CODE REVIEW

**Comment by zonkmachine** [comment]
> @miketurn @musikBear can you test this?

Bump.

@BaraMGB I don't see this on linux.

**Comment by BaraMGB** [comment]
@zonkmachine yes it depends on the used font. You can see it on Windows. In this PR the font metrics is calculated on the fader label font. Before that it's calculated on the widgets font and delivered wrong values.

**Comment by musikBear** [comment]
@BaraMGB sorry, yes i will dl and test

**Comment by BaraMGB** [comment]
Then this should be merged. Any objections here @zonkmachine?

**Comment by miketurn** [comment]
@BaraMGB
Sorry I missed your request to test this
Thank You for fixing the issue
@musikBear 
Thank You for testing this

**Pull request merged**
