### PR TITLE
Show knob value on hover.

### PR DESCRIPTION
**Pull request by DarkoiV**
My take on [issue 5778](https://github.com/LMMS/lmms/issues/5779)

### CODE REVIEW

**Comment by superpaik** [comment]
Tested on Windows 10 64bits.
It works as expected, but in the song editor volume label for an instrument is "volume" but for a sample track is "channel volume". I supose that's because of the "internal" label of the knob.

Also, it would be great to have this behaviour on the volume slider on the FX-Mixer and also on the piano roll on "note velocity" and "note panning". They are not strictly knobs but I think would be useful. Maybe on other PR, though.

**Comment by DarkoiV** [comment]
I added it to sliders in FX-Mixer too, since it seems like pretty much the same change. 
Though it now shows both name of slider and volume on separate floats, idk if this is desired behavior, but they don't overlap and are readable. 
FXMixer

**Comment by superpaik** [comment]
Yeah, it's kind of weird. Idk why the FX name is shown when hover over the channel (maybe for long FX names). But, for exemple, when you hover a track on the Song Editor you don't get the track name (even if the track name is not full visible). 
I would remove the FX name, but I know that removing existing functionality may not be a good idea.
So, let it be, unless other people says otherwise.

**Comment by wujekbrezniew** [comment]
> I added it to sliders in FX-Mixer too, since it seems like pretty much the same change.
> Though it now shows both name of slider and volume on separate floats, idk if this is desired behavior, but they don't overlap and are readable.
> FXMixer

Does it shows two separate boxes with names/values like one pic? Should not be better to show those things in one bigger box?

**Comment by DarkoiV** [comment]
It probably would be better, but I have no idea how it is exactly shown. Fader class only have one static FloatText, so it has to be something else. 
Greping "TextFloat" only returns "TrackContentObjectView" that could be responsible for it. And I am quite unsure about messing with it's logic. Especially since it has hide() method on mouse release, but from what I see "FX" float disappears on mouse click, not release so I am not certain it is even that. 

Someone who has better grasp on this codebase needs to look at this I think.

**Comment by Spekular** [comment]
I'm think this is where the tooltip is set: 
https://github.com/LMMS/lmms/blob/2f17c0da2b20ecb9b00f8dcb227d02731325796b/src/gui/widgets/FxLine.cpp#L101

If you remove it and add `m_renameLineEdit.setToolTip( name );` instead, you might get a tooltip that only shows when hovering over the name. Then the issue should be solved, as each tooltip has it's own area.

I also found this line, not sure what it does though:
https://github.com/LMMS/lmms/blob/2f17c0da2b20ecb9b00f8dcb227d02731325796b/src/gui/FxMixerView.cpp#L365

**Comment by DarkoiV** [comment]
Yeah, they both are responsible for it.  
I couldn't make it work on `m_renameLineEdit`, but it can work on m_lcd. Though I dunno if it is even worth to keep this tool tip.
Name is clearly visible on line itself anyway. 

I think proper implementation of choosing between line tool tip and fader value should be made with `eventFilter`. 

And I am no sure how to do it right now. FxLine is not parent of Fader. Nor is FxMixerView parent of them. They are both contained in inner class FxChannelView which is not Widget.

For now I just deleted it.

**Comment by Spekular** [comment]
> Though I dunno if it is even worth to keep this tool tip.
> Name is clearly visible on line itself anyway.

Except when the name is too long. It's also easier to read horizontal text than vertical.

**Comment by DarkoiV** [comment]
That's good point, I will try to implement `eventFilter` then.

**Pull request closed without merging**
