### PR TITLE
Bump veal submodule

### PR DESCRIPTION
**Pull request by tresf**
- Adds MSVC support to "Calf" plugins.
- Adds several upstream patches

See also https://github.com/LMMS/veal/pull/9, https://github.com/LMMS/veal/pull/5, https://github.com/LMMS/veal/pull/6, (etc)

### CODE REVIEW

**Comment by Rossmaxx** [comment]
Have found some issues. Old project files where i've used the calf plugins seem to crash. Maybe cause of missing upgrade mappings.

**Comment by tresf** [comment]
> old files load fine, not much issues. Haven't tested indepth though. If someone could test it better, would be appreciated.

Thanks for testing.  I realize now that quite a bit has happened on our fork, this adds more than just MSVC support.  We can merge it and cross our fingers or wait on some detailed testing.

**Comment by tresf** [comment]
This may be superseded by #6758

**Comment by Rossmaxx** [comment]
feel free to merge this before #6758. That will make it easier to debug calf related issues in the future and keep that pr for enabling support alone, bumping can be done by this pr instead.

**Comment by tresf** [comment]
If it were just a matter of MSVC changes, I'd merge this without question, but since there were several fast-forwards from upstream code changes, it increases the chance of a regression.  I can merge this, but I will not have time to jump into tracking down regressions, so this is a risk.  I just want another developer to OK this.

**Comment by Rossmaxx** [comment]
Happened to take a look at the code again and saw that the majority changes are, in fact, msvc changes. Also, most of the other changes look harmless too. The only suspect possible of causing any regression is in the `orfanidis_eq.h` file. I wanted to test deeper but college is interfering pretty hard so can't do anything other than looking at the diff on GitHub via mobile.

Inviting @zonkmachine for testing.

**Comment by JohannesLorenz** [comment]
From a code perspective, no complaints against this (but testing would not harm).

Note that in the recent days, I merged a few commits to calf's master, and there may follow some in the next week, as I am setting up a CMake base CI for it, including MSVC support. Maybe it is better to still wait? But I am OK with merging, too.

**Comment by messmerd** [comment]
The veal submodule has 3 new commits since this PR was opened, so they could be included too

**Pull request merged**
