### PR TITLE
Denormal protection refactoring

### PR DESCRIPTION
**Pull request by softrabbit**
The code should be pretty much self-explanatory.

### CODE REVIEW

**Comment by tresf** [comment]
:+1:

**Comment by curlymorphic** [comment]
I like this. It's a good tidy up.

**Comment by tresf** [comment]
Thanks for the second set of eyes, Dave.  Merging.

**Comment by curlymorphic** [comment]
@tresf If I have not commented on a pull request in 24 hours, It means I have simply not noticed it.

**Comment by tresf** [comment]
@curlymorphic :+1: 

Amadeus said yesterday that he's mostly out and Vesa hasn't been active in quite a while, so we need all the help we can get. :+1:

**Pull request merged**
