### PR TITLE
Fix time display

### LINKED ISSUE #2112: Bar:Beat:Tick / Min:Sec:Msec timer values disagree with playhead
Steps to reproduce (I recommend dialing the tempo down to ~20 bpm to make things easier to see):
1. Open LMMS and create an empty pattern on the tripleosc track.
2. Open said pattern in piano roll, hit play.
3. Hit pause in the piano roll.
4. In the song editor, move the playhead to some non-zero position.
5. Hit play in the song editor.

The Bar:Beat:Tick counter should reset and begin counting from 1:1:0 (or 0:0:000 if M:s:ms), however the playhead will _not_ reset, and they will thus be in a disagreement over what time it is. 

If notes are added to the pattern, you will hear them play according to where the playhead is, and not what the timer says.

A gif for your viewing pleasure:

lmms-timer

### PR DESCRIPTION
**Pull request by PhysSong**
It fixes #2112, ~~also fixes https://github.com/LMMS/lmms/pull/3701#issuecomment-316512622.
If https://github.com/LMMS/lmms/pull/3701#issuecomment-316512622 is fixed by @michaelgregorius(or other person), I'll drop the fix for https://github.com/LMMS/lmms/pull/3701#issuecomment-316512622 and modify my PR.~~

Edit: @michaelgregorius have done fix by bcdb5ec, so commif 8ffebbb have been dropped.

### CODE REVIEW

**Comment by michaelgregorius** [comment]
@PhysSong My commit to fix #3701 has introduced a conflict but it should hopefully be possible to resolve by dropping 8ffebbb0436b4fe8b6b9c0896970578755a0a7b9 as you have already mentioned. The difference to your fix is that I have introduced a second methods so that the version with `tick_t` can still be used.

**Comment by PhysSong** [comment]
@michaelgregorius Okay. I'll drop that commit and fix my PR.

**Comment by PhysSong** [comment]
I found that `m_elapsedTicks` and `m_elapsedTacts` are no longer used. Could I remove them?

**Comment by michaelgregorius** [comment]
If they are no longer used I'd say we should remove them.

**Comment by tresf** [comment]
Tested, works.

**Pull request merged**
