### PR TITLE
Add a testing framework

### PR DESCRIPTION
**Pull request by Lukas-W**

### CODE REVIEW

**Comment by Lukas-W** [comment]
I knew Windows wouldn't like this.

**Comment by Lukas-W** [comment]
Hm… both win32 and win64 fail at the eq plugin, other plugins build fine:
```
Linking CXX shared module eq.dll

/opt/mingw64/bin/x86_64-w64-mingw32-ar cr CMakeFiles/eq.dir/objects.a @CMakeFiles/eq.dir/objects1.rsp

/opt/mingw64/bin/x86_64-w64-mingw32-g++ -shared -o eq.dll -Wl,--major-image-version,0,--minor-image-version,0 -Wl,--whole-archive CMakeFiles/eq.dir/objects.a -Wl,--no-whole-archive -L/home/travis/build/LMMS/lmms/build -L/home/travis/build/LMMS/lmms -lfftw3f -Wl,-Bstatic -lQtGui4 -lQtXml4 -lQtCore4 -Wl,-Bdynamic ../../src/liblmms.dll.a -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32

CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj):EqEffect.cpp:(.text+0x3e62): undefined reference to `__imp__Z7absspecPA2_fPfi'
CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj):EqEffect.cpp:(.text+0x3eb9): undefined reference to `__imp__Z13compressbandsPfS_iiii'
CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj):EqEffect.cpp:(.text+0x3ec8): undefined reference to `__imp__Z7maximumPfj'
CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj):EqEffect.cpp:(.text+0x3f54): undefined reference to `__imp__Z7absspecPA2_fPfi'
CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj):EqEffect.cpp:(.text+0x3fb5): undefined reference to `__imp__Z13compressbandsPfS_iiii'
CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj):EqEffect.cpp:(.text+0x3fc4): undefined reference to `__imp__Z7maximumPfj'

/opt/mingw64/lib/gcc/x86_64-w64-mingw32/4.8.5/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj): bad reloc address 0x0 in section `.data'

collect2: error: ld returned 1 exit status
```

**Comment by Lukas-W** [comment]
So, this is the way this is supposed to work. Say you want to write a test.

1. Create a new source file, e.g. `tests/core/MyClassTest.cpp`
2. In that file, create a class inheriting `QTestSuite`. Create test functions in that class (see the Qt documentation about [writing tests](http://qt-project.org/doc/qt-4.8/qtestlib-tutorial1.html)). The class also must have a instance:
    ```c++
    #include "QTestSuite.h"
    #include "MyClass.h"
    class MyClassTest : QTestSuite 
    {
        Q_OBJECT
    private slots:
        void testClass() 
        {
            MyClass* object = new MyClass();
            Q_ASSERT(object->works());
            object->setValue(37);
            QCOMPARE(object->value(), 37);
        }
    } instance;

    #include "MyClassTest.moc"
    ```
3. Add that file to the CMake script `tests/CMakeLists.txt`
    ```cmake
    ADD_EXECUTABLE(tests
        EXCLUDE_FROM_ALL
        main.cpp
        QTestSuite

        core/MyClassTest.cpp
    )
    ```

**Comment by tresf** [comment]
Great.  Should we have this information available in wiki for future reference?

**Comment by Lukas-W** [comment]
Actually it's so simple you'll get it as soon as there's at least one written test in the source. But on the other hand it wouldn't hurt having it in the wiki. Feel free to copy it there.

**Comment by curlymorphic** [comment]
> Hm… both win32 and win64 fail at the eq plugin, other plugins build fine:

@Lukas-W im unsure if this is fixed, i can see commits that have built since this. if not i will get onto it right away, looks like the fft lib is not being linked

**Comment by badosu** [comment]
@Lukas-W Really nice! Looks very straightforward to add tests.

**Comment by Lukas-W** [comment]
> im unsure if this is fixed, i can see commits that have built since this.

Yes for some reason it's fixed now ;)

**Comment by curlymorphic** [comment]
UNIT TESTING comes to lmms

:) :) :100:  :+1:  :)


:) :) :)

comments and unit test in 24 hours very nice.

Do these tests run on travis and flag the build as failed?

**Comment by Lukas-W** [comment]
> Do these tests run on travis and flag the build as failed?

Not yet, but as of now, there are no tests anyway. ;) Someone will have to write them.

**Comment by tresf** [comment]
> Not yet, but as of now, there are no tests anyway. ;) Someone will have to write them.

I'm excited about this too... `lmms tripleoscillator-test.mmpz`, compare output.

Blame people `<-- kidding :)`

**Comment by curlymorphic** [comment]
> Someone will have to write them.

That will be no small undertaking. seeing as lmms was not written with testing in mind, and testing code often contains more lines of code than the code being tested.  Im happy to help where i can on these. 

I think  this could be one of the best things for lmms. There have been a couple of cases where i have fixed a bug, only to find out i broke something else. I am guessing im not the only one to have done this. This is the sort of thing testing will reduce, the more code that is tested the less bugs creep  in.

@tresf 

> Blame people

Not really, git does a far better job of that.  Never tested with Qt before, but normally you can set  up so the build fails if the unit tests break, long before commits are made. 

Got me excited now, lol, I think im going to have a go at writing us a few tests this evening.

**Comment by Lukas-W** [comment]
> I think im going to have a go at writing us a few tests this evening.

:)

**Comment by curlymorphic** [comment]
@Lukas-W 

> see the Qt documentation about writing tests   http://qt-project.org/doc/qt-4.8/qtestlib-tutorial1.html

There examples dont look anything like yours, theey inherit QObject. I will have a look at your way first, as that makes more sense

**Comment by Lukas-W** [comment]
> There examples dont look anything like yours, theey inherit QObject.

As does mine, but indirectly through the custom class `QTestSuite`. I probably should have named it `TestSuite` so that it's clear it's not a part of Qt itself. `QTestSuite`'s purpose is to collect all its subclasses (via its constructor) in a static list, so that the `main` function can automatically run all tests without explicitly listing them.

**Comment by curlymorphic** [comment]
> As does mine, but indirectly through the custom class QTestSuite. I probably should have named it TestSuite so that it's clear it's not a part of Qt itself. QTestSuite's purpose is to collect all its subclasses (via its constructor) in a static list, so that the main function can automatically run all tests without explicitly listing them.

just worked that out. I did get confused by QTestSuite.  

how do we run the tests?

**Comment by Lukas-W** [comment]
> how do we run the tests?

```sh
$ make tests
$ ./tests/tests
```

**Comment by curlymorphic** [comment]
I cant get the tests to link

my test class
AutomatableModelTests.cpp
```
#include "QTestSuite.h"
#include "AutomatableModel.h"
#include "AutomatableModelTests.moc"

class AutomatableModelTests : QTestSuite
{
	Q_OBJECT
private slots:
	void constructed()
	{
		FloatModel *fm = 0;
		fm = new FloatModel( 0.0, 0.0, 0.0, 0.1, this );

		Q_ASSERT( fm );
	}
};

```

and the results of building. I have already run cmake and make to build

```
dave@dave-700-230ea:~/Development/lmms/modelTest/lmms-build$ make tests
[  4%] Automoc for target tests
Generating AutomatableModelTests.moc
Generating moc_QTestSuite.cpp
[  4%] Built target tests_automoc
[  4%] Automoc for target lmms
[  4%] Built target lmms_automoc
[  4%] Built target bin2res
[100%] Built target lmms
Scanning dependencies of target tests
[100%] Building CXX object tests/CMakeFiles/tests.dir/main.cpp.o
[100%] Building CXX object tests/CMakeFiles/tests.dir/QTestSuite.cpp.o
[100%] Building CXX object tests/CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o
/home/dave/Development/lmms/modelTest/lmms/tests/src/core/AutomatableModelTests.cpp:2:24: fatal error: lmmsconfig.h: No such file or directory
 #include "lmmsconfig.h"
                        ^
compilation terminated.
tests/CMakeFiles/tests.dir/build.make:100: recipe for target 'tests/CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o' failed
make[3]: *** [tests/CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o] Error 1
CMakeFiles/Makefile2:8664: recipe for target 'tests/CMakeFiles/tests.dir/all' failed
make[2]: *** [tests/CMakeFiles/tests.dir/all] Error 2
CMakeFiles/Makefile2:8672: recipe for target 'tests/CMakeFiles/tests.dir/rule' failed
make[1]: *** [tests/CMakeFiles/tests.dir/rule] Error 2
Makefile:2910: recipe for target 'tests' failed
make: *** [tests] Error 2
dave@dave-700-230ea:~/Development/lmms/modelTest/lmms-build$ 
```

**Comment by Lukas-W** [comment]
Hm… Try adding `INCLUDE_DIRECTORIES("${CMAKE_BINARY_DIR}")` to `tests/CMakeLists.txt`

**Comment by curlymorphic** [comment]
> Hm… Try adding INCLUDE_DIRECTORIES("${CMAKE_BINARY_DIR}") to tests/CMakeLists.txt

now i get 93 errors.

I did find this on the net

${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}

but CMake didn't like the CMAKE_FILES_DIRECTORY

**Comment by curlymorphic** [comment]
Some progress. i have been trying to get this to build all night. The problem with lmmsconfig.h is sorted :)

It appears to me that the headders are included. but the actual source under test (the .cpp) is not being linked.

here is what i have so far

automatableModelTests.cpp
```
#include "QTestSuite.h"
#include "AutomatableModel.h"

class AutomatableModelTests : QTestSuite
{
	Q_OBJECT
private slots:
	void constructed()
	{
		FloatModel *fm = 0;
		fm = new FloatModel( 0.0f, 0.0f, 0.0f, 0.1f);

		Q_ASSERT( fm );
	}
} instance;

#include "AutomatableModelTests.moc"
```


CMakeLists.txt
```
INCLUDE_DIRECTORIES("${CMAKE_CURRENT_SOURCE_DIR}")
INCLUDE_DIRECTORIES("${CMAKE_CURRENT_BINARY_DIR}")
INCLUDE_DIRECTORIES("${CMAKE_SOURCE_DIR}/include")
INCLUDE_DIRECTORIES("${CMAKE_BINARY_DIR}")

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} --std=c++11")

SET(CMAKE_AUTOMOC ON)

ADD_EXECUTABLE(tests
	EXCLUDE_FROM_ALL
	main.cpp
	QTestSuite

	src/core/AutomatableModelTests.cpp
)
TARGET_LINK_LIBRARIES(tests ${QT_LIBRARIES} ${QT_QTTEST_LIBRARY})
TARGET_LINK_LIBRARIES(tests lmms)
```

the make errors

```
dave@dave-700-230ea:~/Development/lmms/modelTest/lmms-build$ make tests
[  4%] Automoc for target tests
[  4%] Built target tests_automoc
[  4%] Automoc for target lmms
[  4%] Built target lmms_automoc
[  4%] Built target bin2res
[100%] Built target lmms
Linking CXX executable tests
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o: In function `AutomatableModel::operator new(unsigned long)':
/home/dave/Development/lmms/modelTest/lmms/include/AutomatableModel.h:69: undefined reference to `MemoryManager::alloc(unsigned long)'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o: In function `AutomatableModel::operator delete(void*)':
/home/dave/Development/lmms/modelTest/lmms/include/AutomatableModel.h:69: undefined reference to `MemoryManager::free(void*)'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o: In function `FloatModel::FloatModel(float, float, float, float, Model*, QString const&, bool)':
/home/dave/Development/lmms/modelTest/lmms/include/AutomatableModel.h:407: undefined reference to `AutomatableModel::AutomatableModel(AutomatableModel::DataType, float, float, float, float, Model*, QString const&, bool)'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o:(.data.rel.ro._ZTV10FloatModel[_ZTV10FloatModel]+0x10): undefined reference to `AutomatableModel::metaObject() const'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o:(.data.rel.ro._ZTV10FloatModel[_ZTV10FloatModel]+0x18): undefined reference to `AutomatableModel::qt_metacast(char const*)'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o:(.data.rel.ro._ZTV10FloatModel[_ZTV10FloatModel]+0x20): undefined reference to `AutomatableModel::qt_metacall(QMetaObject::Call, int, void**)'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o:(.data.rel.ro._ZTV10FloatModel[_ZTV10FloatModel]+0x80): undefined reference to `Model::fullDisplayName() const'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o:(.data.rel.ro._ZTV10FloatModel[_ZTV10FloatModel]+0x88): undefined reference to `AutomatableModel::saveSettings(QDomDocument&, QDomElement&, QString const&)'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o:(.data.rel.ro._ZTV10FloatModel[_ZTV10FloatModel]+0x90): undefined reference to `AutomatableModel::loadSettings(QDomElement const&, QString const&)'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o:(.data.rel.ro._ZTV10FloatModel[_ZTV10FloatModel]+0xa0): undefined reference to `AutomatableModel::reset()'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o:(.data.rel.ro._ZTV10FloatModel[_ZTV10FloatModel]+0xa8): undefined reference to `AutomatableModel::copyValue()'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o:(.data.rel.ro._ZTV10FloatModel[_ZTV10FloatModel]+0xb0): undefined reference to `AutomatableModel::pasteValue()'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o:(.data.rel.ro._ZTV10FloatModel[_ZTV10FloatModel]+0xe8): undefined reference to `JournallingObject::saveState(QDomDocument&, QDomElement&)'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o:(.data.rel.ro._ZTV10FloatModel[_ZTV10FloatModel]+0xf0): undefined reference to `JournallingObject::restoreState(QDomElement const&)'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o: In function `FloatModel::~FloatModel()':
/home/dave/Development/lmms/modelTest/lmms/include/AutomatableModel.h:400: undefined reference to `AutomatableModel::~AutomatableModel()'
CMakeFiles/tests.dir/src/core/AutomatableModelTests.cpp.o:(.data.rel.ro._ZTI10FloatModel[_ZTI10FloatModel]+0x10): undefined reference to `typeinfo for AutomatableModel'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/tests.dir/build.make:164: recipe for target 'tests/tests' failed
make[3]: *** [tests/tests] Error 1
CMakeFiles/Makefile2:8664: recipe for target 'tests/CMakeFiles/tests.dir/all' failed
make[2]: *** [tests/CMakeFiles/tests.dir/all] Error 2
CMakeFiles/Makefile2:8672: recipe for target 'tests/CMakeFiles/tests.dir/rule' failed
make[1]: *** [tests/CMakeFiles/tests.dir/rule] Error 2
Makefile:2910: recipe for target 'tests' failed
make: *** [tests] Error 2
dave@dave-700-230ea:~/Development/lmms/modelTest/lmms-build$ 
```

**Comment by Lukas-W** [comment]
@curlymorphic 
My pull request #1626 should fix this, I'll wait for the Travis build before merging it though.

**Comment by Lukas-W** [comment]
@curlymorphic Should work now. ;

**Pull request merged**
