### PR TITLE
MIDI import: add support for track names

### PR DESCRIPTION
**Pull request by softrabbit**
Having actual track names on your tracks is better than naming all the tracks after your default SF2 file.

### CODE REVIEW

**Comment by Sti2nd** [comment]
What do you mean non functional code and actual track names? I have helped get the auto-naming worked like three times, so it certainly works.?

If you now fetch instrument name, cool!

**Comment by softrabbit** [comment]
"Actual track names" = the track names that might be in the MIDI file, they should override any autonaming logic in the SF2 player.

Any instrument name fetching is out of scope for this PR, it should IMO be left to SF2 player and Patman (yup, MIDI import uses Patman as a fallback...).

"Non functional code" = the old attempt at making this happen, which was code that would:
1. never run; track name is a MIDI file meta event without a channel number, which was caught by ```if( evt->chan == -1 )``` and never got to the ```else if( evt->is_update() )``` where it was supposed to be handled.
2. if it had run, it would've named all tracks "tracknames" (calling the wrong method on the event).

**Comment by tresf** [comment]
@Sti2nd he's talking about info embedded in the midi file, not the instrument.   The sountfont name works well, but sometimes it is more useful to auto-fill what the MIDI file had intended that track to be. :)

**Comment by Sti2nd** [comment]
Ohh, cool!

**Comment by tresf** [comment]
@softrabbit as far as I can see, this is ready to be merged.  @Sti2nd @Umcaruje @mikobuntu @badosu please take note if we have any midi import issues.

**Pull request merged**
