### PR TITLE
Resizable mixer channels/strips

### PR DESCRIPTION
**Pull request by michaelgregorius**
This pull request makes the mixer channels/strips grow with the mixer view. The mixer view now also provides the maximize button so that users can mix in almost full screen.

Screenshot:

Resizable mixer channels

### CODE REVIEW

**Comment by Gabrielxd195** [comment]
This is great, we can finally maximize the mixer. but there is a problem, I don't think it is necessary to have to remove the volume knobs because the space they occupy is fixed; However, the length of the space where the channel names are written varies depending on the number of letters it has. Don't you think it would be better to remove the space where the channel names are written? My suggestion is to leave the volume knobs as they were next to the mute and solo buttons, but make the channel name space larger. 

Google Translate

**Comment by Gabrielxd195** [comment]
> @Gabrielxd195, what do you mean with regards to the removal of the volume knobs? I did not remove any knobs with this PR.
> 
> Regarding the name labels: I tried to make them grow as well but due to their implementation I ran into problems while doing so. It is something that should later be attempted again because it would definitively make sense to have them grow as well.

First of all, sorry for my translation errors, I don't speak English, I used Google translate. 

At no point did I say to remove the volume knobs (Impossible), but rather to leave them as they were but to remove the space where the channel names are written.

**Comment by michaelgregorius** [comment]
> > @Gabrielxd195, what do you mean with regards to the removal of the volume knobs? I did not remove any knobs with this PR.
> > Regarding the name labels: I tried to make them grow as well but due to their implementation I ran into problems while doing so. It is something that should later be attempted again because it would definitively make sense to have them grow as well.
> 
> First of all, sorry for my translation errors, I don't speak English, I used Google translate.

No problem. I have already noticed the "Google Translate" at the bottom of your first message. :slightly_smiling_face:

> At no point did I say to remove the volume knobs (Impossible), but rather to leave them as they were but to remove the space where the channel names are written.

Ah, I think I understand now. So you mean to leave the size of the faders as they were but to use additional space for the channel names if the mixer is made larger?

In an ideal implementation both the faders and the names would grow when more space is available. However, as already noted, I ran into problems when trying to make the channel names use the space. Therefore the fader are currently the only thing that can make use of the additional space.

**Review by Rossmaxx — APPROVED** [review]

**Comment by Gabrielxd195** [comment]
> Ah, I think I understand now. So you mean to leave the size of the faders as they were but to use additional space for the channel names if the mixer is made larger?
> 
> In an ideal implementation both the faders and the names would grow when more space is available. However, as already noted, I ran into problems when trying to make the channel names use the space. Therefore the fader are currently the only thing that can make use of the additional space.


Come to think of it, your idea is much better because the size of the knobs and text space should be proportional to the screen resolution. I hope they can implement this later. By the way, I already tried this improvement and I loved how the mixer was maximized, now I can have it fixed. thanks for your contribution.

**Comment by michaelgregorius** [comment]
You're welcome, @Gabrielxd195! I am happy if you and other people find it useful!

**Pull request merged**
