### PR TITLE
Feature/tap enum texts

### PR DESCRIPTION
**Pull request by teknopaul**
lmms-tap-plugin-text

Some tool tip text for TAP plugins, so you can tell what Reverb you are using.

### CODE REVIEW

**Comment by qnebra** [comment]
Voxpop is completly pointless in this PR

**Comment by teknopaul** [comment]
sorry, git issues, should be just that one last commit 232dd23ced1b90679503de4dbab2be1cc26dc93b.
In theory this is PR'd from my master.

**Comment by teknopaul** [comment]
git branch feature/tap-enum-texts
  git switch feature/tap-enum-texts
  git status
  git add ../plugins/LadspaEffect/LadspaMatrixControlDialog.cpp ../plugins/LadspaEffect/LadspaMatrixControlDialog.h
  git commit -m "adding text to TAP plugin enums bar editors"
  git push

Literally no other commands run, in my CLI history, I don't see how this branch has anything but those two files I added

**Comment by teknopaul** [comment]
> > Voxpop is completly pointless in this PR
> 
> To be fair to the op, i remember him talking about messing up git. Might have been a side effect.
> 
> @teknopaul i recommend you checkout to master, create a branch and cherry pick needed commits.
> 
> You might need to close this pr and open another one.

This type of shit scares me with git.  That branch has one commit, in the old days that literally meant there was one patch file. 

I deleted everything from github remote.   in teknopaul/lmms  There is now, 1 PR with, 1 branch, 1 one commit.

I have only one other branch with my code that you don't want, if anything "leaks" from that branch I'll move it to gitlab.

**Pull request closed without merging**
