### PR TITLE
Fix ladspa plugin discovery

### LINKED ISSUE #2426: LADSPA plugins list in plugin browser only
@grejppi and @karmux have mentioned this but in master branch, LADSPA plugins list in the `LADSPA Plugin Browser`, but don't list in the `Add effect` dialog.

image

Furthermore, the default paths for these don't seem to be getting setup properly like the rest of the [`ConfigManager.cpp#L67`](https://github.com/LMMS/lmms/blob/master/src/core/ConfigManager.cpp#L67) config detection logic.  Pinging @Lukas-W as this may be related to some changes made to [data/plugins path enhancement which allows launching from the build directory (#1719)](https://github.com/LMMS/lmms/pull/1719).

To reproduce:

 * Build master branch
 * Launch LMMS from `build` directory
 * Observe all LADSPA plugins are missing from both the LADSPA Plugin Browser dialog as well as the Add effect dialog.

 * Edit LADSPA path preferences, add `build/plugins/ladspa/` to the LADSPA path
 * Launch LMMS from `build` directory
 * LADSPA plugins list in the Plugin Browser only.  The Add effect dialog is missing LADSPA plugins.

### PR DESCRIPTION
**Pull request by Lukas-W**
Reverts the three commits (PRs #2428, #2430, #2432) that fixed #2426 in a way that I think may be too complicated.

45cafd3f601b08c7cf675394f78351d65d342b4c is my approach to the problem.

### CODE REVIEW

**Comment by tresf** [comment]
:+1: Nice work, including the cleanup.  Thanks for fixing this up.

**Comment by tresf** [comment]
@Lukas-W Tests fail for me on Ubuntu 12.04.

Clean checkout and build of `ladspa-dirs` to no avail.

image

And proof that I'm on the right branch:

image

I didn't even begin trying the other platforms.

**Comment by Lukas-W** [comment]
Thanks for testing. That was just a typo I managed to throw in between building and committing, should work now… I also moved the `plugin:ladspa` search path addition out of ConfigManager back to LadspaManager so that it doesn't appear in the settings dialog, and is not removable by the user.

**Comment by tresf** [comment]
Thanks.  Here are the test results.  All pass. :+1: 


Ubuntu 12.04:
image

Windows (via Wine):
image

Mac 10.7:
image

**Comment by Lukas-W** [comment]
Thanks for testing :+1:

**Pull request merged**
