### PR TITLE
russian translation update

### PR DESCRIPTION
**Pull request by oeai**
some changes for, monstro and some new strings
it's not fully translated yet, not sure that IN, OUT, GAIN should be translated because of UI issues
maybe some feedback comes later.

### CODE REVIEW

**Comment by badosu** [comment]
Hi @oeai, would you mind squashing all these commits together into a single one? Since this affects just a single functionality this would be ideal so we don't fill our git history with redundant stuff.

In your case you would use the following command: `git rebase -i HEAD~15` (since you created the last 15 commits on our branch) then let the first commit on the editor to be `pick`, all the other cases of `pick` you replace with `squash`. See some references:

- http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
- https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

You'll have to push with `-f` later.

**Comment by oeai** [comment]
i'm not sure if i need to merge first commit from LMMS/lmms that was needed to sync version.

**Comment by badosu** [comment]
It's not really needed, you can squash it together too, I guess.

Anyway, it's already much better now, thanks!

**Comment by tresf** [comment]
@oeai I'm merging this.  If someone else familiar with Russian can test it prior to 1.2 that would be valuable.

**Pull request merged**
