### PR TITLE
Make the window border lighter

### PR DESCRIPTION
**Pull request by Umcaruje**
Should help with #2867 
screenshot from 2016-07-08 18 41 44
screenshot from 2016-07-08 18 39 33

### CODE REVIEW

**Comment by RebeccaDeField** [comment]
Can this border wrap around the whole window so that the title bars benefit from the increased contrast as well? If not, could we add a separate border that wraps around the title bar?

**Comment by BaraMGB** [comment]
@RebeccaDeField since we don't get the corners straight, a border around the title bar looks a little bit odd. I have add a thin dark line on top here https://github.com/LMMS/lmms/pull/2912

**Comment by RebeccaDeField** [comment]
Ah, I see how that wouldn't work. Basically my concern is that having the stroke end before the title bar might be a bit jarring with the lighter stroke. What if we put a border on the bottom on the title bar so that the stroke looks like it wraps around the whole lower section of the window?? Please see example bellow.

0f5cf148-4767-11e6-930b-9d959de93a9e

**Comment by Umcaruje** [comment]
@RebeccaDeField I'm not too fond of the idea, as it would disconnect the title bar from the rest of the window, which I don't see as necessary.

**Comment by RebeccaDeField** [comment]
@Umcaruje The disconnect I was concerned about has already been resolved with the lighter title bars. :)

**Comment by Umcaruje** [comment]
@RebeccaDeField so this is ok to merge then?

**Comment by RebeccaDeField** [comment]
@Umcaruje I think so :+1:

**Comment by Umcaruje** [comment]
:+1:

**Pull request merged**
