### PR TITLE
Initialize all fields of EqFilter upon construction

### PR DESCRIPTION
**Pull request by Wallacoloo**
This fixes a warning by valgrind in which "conditional jumps depend on uninitialized values" when entering the `setParameters` function. Additionally, it simplifies the code in said function.

### CODE REVIEW

**Comment by Wallacoloo** [comment]
I'll be merging this later today unless somebody says otherwise.

**Comment by tresf** [comment]
I forgot to tag @curlymorphic on this one (although he's on copy of all PRs anyway).

**Comment by curlymorphic** [comment]
Looks good to me @Wallacoloo

@tresf 
(although he's on copy of all PRs anyway).

May be I have to set that up

**Comment by tresf** [comment]
> May be I have to set that up

screen shot 2015-07-11 at 6 15 12 pm

**Comment by curlymorphic** [comment]
@tresf 

Thats is what I was set on, but seem to be acting as only when mentioned or participating. I have unwatched, re watched, to see if this can rectify the situation.

**Pull request merged**
