### PR TITLE
Upgrade Calf plugins to 0.90

### PR DESCRIPTION
**Pull request by tresf**
The calf plugins we ship are very outdated (~0.18) yet 0.90 is available.  This PR adds the latest.

**Download**

https://github.com/LMMS/lmms/pull/3987#issuecomment-377959431

Or to compile locally...

```bash
git checkout -b tresf-veal master
git pull https://github.com/tresf/lmms.git veal
git submodule deinit -f plugins/LadspaEffect/calf/veal
git submodule update --init --recursive plugins/LadspaEffect/calf/veal
```

**Background**

Calf has removed support for LADSPA, however generous work from @JohannesLorenz, now LADSPA support on 0.90 is finally possible.

The efforts are currently living in `tresf/veal` on a branch called `veal_with_0.90`.  These changes won't ever show in this PR, but will instead be in a separate PR against `lmms/veal` once ready (then we update the submodule here, then we merge), but since few people will read that, I'm posting the high-level changes here.

**What's Changed?**

Below is a list of what's removed and what's added in Calf 0.90.  Note, a removed plugin may be due to a name change.  We'll know more after a proper investigation.

* `WONTFIX` - Input gains `MIN: 0` changed to `MIN: 0.01625`

Plugin<br>(new in bold) | Sound Tested<br>(new premarked) | Notes
----------------------|------------------------------------------|----
**Calf Analyzer** |☑️
Calf Bass Enhancer |   ✅ 
**Calf Compensation Delay Line**  | ☑️
Calf Compressor |  ✅ | New "Mix" knob
**Calf Crusher** | ☑️
Calf Deesser | ✅ 
**Calf Emphasis** | ☑️
Calf Equalizer 12 Band | ✅  | [Display issues](https://user-images.githubusercontent.com/6345473/33529138-51ce4512-d83a-11e7-802d-62f8f5a5fd90.png) (fixed)
**Calf Equalizer 30 Band**  | ☑️
Calf Equalizer 5 Band | ✅ | Same display issues as 12 band (fixed)
Calf Equalizer 8 Band | ✅ | Same display issues as 12 band (fixed)
Calf Exciter | ✅ 
Calf Filter | ✅ | New "Bypass" checkbox, "Input Gain" and "Output Gain" knobs
Calf Filterclavier |  ✅ | New "Bypass" checkbox, "Input Gain" and "Output Gain" knobs
Calf Flanger | ✅ | Sound Ok.  **Defaults changed!**  New "Active", "LFO" checkboxes, "Input Gain" and "Output Gain" knobs
Calf Gate | ✅
**Calf Haas Stereo Enhancer** | ☑️
Calf Limiter | ☑️ | [Segfaults LMMS](https://gist.githubusercontent.com/tresf/4748bf29a6b849398a9d43829055a5d9/raw/c9a9d987f73e25795ce122dc52e12213cec99ec4/gistfile1.txt) (fixed)
**Calf Mono Compressor** | ☑️ 
Calf MultiChorus | ✅ | Sound Ok.  **Defaults changed!**  New "Active", "LFO" checkboxes, "Input Gain" and "Output Gain" knobs
**Calf Multi Spread** | ☑️ 
Calf Multiband Compressor | ✅ |  [S's & Q's removed (`wontfix`)](https://github.com/calf-studio-gear/calf/issues/98)
**Calf Multiband Enhancer** |☑️
Calf Multiband Gate | ✅  | [S's & Q's removed (`wontfix`)](https://github.com/calf-studio-gear/calf/issues/98), similar UI changes as Calf Multiband Compressor (fixed)
Calf Multiband Limiter | ✅ | [S's & Q's removed (`wontfix`)](https://github.com/calf-studio-gear/calf/issues/98)
Calf Phaser | ✅ | New "Active", "LFO" checkboxes, "Input Gain" and "Output Gain" knobs
Calf Pulsator | ✅   | More knobs, L&R was split, [needs remapping](https://user-images.githubusercontent.com/6345473/36069332-77ffe4fa-0eb5-11e8-8ce0-8b3e2996b813.png)
Calf Reverb | ✅  | More knobs, but they [map properly](https://user-images.githubusercontent.com/6345473/36069363-f3616088-0eb5-11e8-8eb1-51b9392ecb00.png).
**Calf Reverse Delay** | ☑️
**Calf Ring Modulator** | ☑️
 Calf Rotary Speaker | ☑️ |  Output Gain is 0 by default (fixed)
Calf Saturator |  ✅  | Two new LEDs, Active Pre, Active Post
Calf Sidechain Compressor | ⚠️   | "S/C-Route" switched from knob to LED.  New "Mix" knob.  **L/R sidechaining is no longer possible.**
Calf Sidechain Gate | ⚠️   | "S/C-Route" switched from knob to LED.   **L/R sidechaining is no longer possible.**
Calf Stereo Tools | ⚠️  | New knobs "S/C Level", "Stereo Phase".  "Widener" renamed "Stereo Base" and allows negatives now. **M-Level and S-Level knobs won't upgrade.  See https://github.com/LMMS/lmms/pull/3987#issuecomment-377956801.**
**Calf Tape Simulator** | ☑️
**Calf Transient Designer** | ☑️
Calf Vintage Delay | ✅   | More knobs, [needs remapping](https://user-images.githubusercontent.com/6345473/36069417-2a4d4fd4-0eb7-11e8-9dcb-435de4fb653d.png)
```

### CODE REVIEW

**Comment by qnebra** [comment]
I hate adding @tresf repository in Gitkraken, because this cause some errors and troubles with infinite tries of define repository version and Gitkraken had infite loop of open repository. This bug is in program itself, because when I am doing add remote repository and merge commits via git command line everything works perfect.

These changes looks very good for me, I think we should move to latest standards in lmms.

**Comment by tresf** [comment]
> I think we should move to latest standards in lmms [... because ... ]  Gitkraken

I'm not sure how this is relevant.  We will merge this once we get help porting 0.4 to 0.9.  Complaints about 3rd party tools should not be an influence nor relevant in the decision to merge.  Submodules suck, especially when dealing with non-default branches.  Master has a cmake helper script to deal with this, which is what people should be using/reporting complaints against.

**Comment by Umcaruje** [comment]
```diff
- Calf Sidechain Compressor
```

Huh, so how do we sidechain now?

**Comment by qnebra** [comment]
My previous answer has a two completly separated topics, without any joints between them.

**Comment by tresf** [comment]
@Umcaruje the codebase still [contains it by name](https://calf-studio-gear.org/doc/Sidechain%20Compressor.html) so I'm not sure if it was removed or if we just no longer have a way to load in in 0.90.  @JohannesLorenz would be the person to spearhead that investigation.  I would also recommend looking for it in the LADSPA Browser's incompatible plugins listing.

**Comment by JohannesLorenz** [comment]
@tresf You can update your list:
* MultiChorus -> Multi Chorus
* Calf Multiband Compressor -> It's still there (typo?)
* Calf Sidechain Compressor + Gate -> Are still there, but require a small change with the way ports are counted for LMMS to "allow" them. I'll have to check how to solve it.

**Comment by tresf** [comment]
> MultiChorus -> Multi Chorus

It needs to be tested though.  Can you confirm it still loads in 0.90 with a project/preset created with 0.40?

> Calf Multiband Compressor -> It's still there (typo?)

Fixed.


> Calf Sidechain Compressor + Gate -> Are still there, but require a small change with the way ports are counted for LMMS to "allow" them. I'll have to check how to solve it.

👍

**Comment by tresf** [comment]
MultiChorus seems to be used by `presets/TripleOscillator/DirtyReece`.  That should be a valid test.

**Comment by JohannesLorenz** [comment]
@tresf Here are some updates:
* MultiChorus: No Bug, No Fix (Only the displayed name changed, the internal is unchanged)
* Sidechain effects: Are now available with `d2943d34`

More TODOs:
* Rename `calf` to `veal` in the XML savefiles (I have prepared a patch for it), **or** rename `veal.so` to `calf.so`

Optional:
* Calf has a vocoder, but it has 4 non-optional input ports. We could make it a mono vocoder, if there's interest in that.
  - Contra: It would increase the merge complexity to original calf
  - Contra: We already have the swh adapted vocoder
  - Pro: It might sound good

**Comment by tresf** [comment]
> More TODOs:
> 
> Rename calf to veal in the XML savefiles (I have prepared a patch for it), or rename veal.so to calf.so

This has already been done on master via https://github.com/LMMS/lmms/pull/3940/commits/58d117ea667e0aa93190f1c0af09603ca435f727#diff-cea4bcf0045758a3134d437ede509c7c

> MultiChorus: No Bug, No Fix (Only the displayed name changed, the internal is unchanged)

👍 

> Sidechain effects: Are now available with d2943d34

Thanks, I'll pull in the latest and update the list.

> Calf vocoder

Sure, if it's not too much work and does't change too much of the code.

@JohannesLorenz this is great news, thanks.

**Comment by tresf** [comment]
@JohannesLorenz, synced in your changes as well as updated against the state of `master` branch.  You can snag it using `git reset --hard 2e9f98d`.  Make sure to back up any changes first.

**Comment by tresf** [comment]
Testing appreciated, here's an appimage for Linux users: https://github.com/tresf/lmms/releases/download/vmaster/lmms-1.2.0-rc3.319-linux-x86_64.AppImage

**Comment by qnebra** [comment]
Thanks for AppImage.

**Comment by tresf** [comment]
I'm starting the process of sound-testing each Calf plugin.  This is a basic test.  I'm using BellArp.xpf (3xOsc) and running it through with randomly positioned knobs.  This is to ensure the knob range as well as the general sound hasn't been drastically changed.

I've switched the plugin format to a table.  I'm marking each plugin with a checkbox as they're sound tested.
* I've pre-checked new plugins, there's nothing to compare to.
* This is by no means meant to be a full regression test.
   * We do not yet have true regression tests or fuzzing for deterministic effects or instruments, so we will ultimately trust feedback from real-world testing against 1.3.0 from our users.
* I've made notes for any major changes I observe.
* We may add a fourth column for project testing (port names and order, etc).  Hopefully @JohannesLorenz can quickly help with this from a code perspective.

If someone has time to help with any of this, PM me on [Discord](https://lmms.io/chat).  These tests should be pretty simple whereas the C* plugins (over in #4027) will be much, much harder to avoid regressions.

**Comment by JohannesLorenz** [comment]
My todo list for the next days:
* Fix segfault arising in all limiters (done, pushed)
* Enable vocoder (done, pushed)
* Don't only break ladspa GUI lines for toggles, but also for enums (calf eq 12 bands) (in progress)
* Multiband Compressor: Re-implement S and Q values and commit to CALF's master

**Comment by qnebra** [comment]
Rotary Speaker - input and output values set by default to 0, I don't it is error or not.
Reverb - Work nice

**Comment by JohannesLorenz** [comment]
@qnebra: Thanks for the issue report, I added it to the bug list above

**Comment by JohannesLorenz** [comment]
The parameter analysis is finished (but bugs are still open, see above).

What I checked:
* Did the minimum value increase?
* Did the maximum value decrease?
* Did the scale type (log/linear) change?
* Any other strange things?

Result:
* There should be no loss when for any effect when loading old files
* However, some effects have new parameters. These should not have any effects as soon as the above bug list is fixed.

**Comment by JohannesLorenz** [comment]
A bit of info for the last step (re-implementing S and Q values).

Affected (this was already noted above, but I wanted make sure these are all):
* Multiband Compressor
* Multiband Gate
* Multiband Limiter

What has to be done?
1. Add the parameters to the end of the parameter lists
2. The arrays of low- and highpasses were moved into the `dsp::crossover` class. Feed them with the newly added coefficients somehow...
3. Once step 1 is done, I'd give @tresf a list of mapping of the parameter's numbers. He could help patching old savefiles

Aside from this, I discovered a few effects that need to be renamed. @tresf can I please ask you to help here (if it's not already done)?

```
Sidechaincompressor -> SidechainCompressor
Sidechaingate -> SidechainGate
Multibandcompressor -> MultibandCompressor
Multibandgate -> MultibandGate
Multibandlimiter -> MultibandLimiter
```

**Comment by tresf** [comment]
Per https://github.com/calf-studio-gear/calf/issues/98, marking `S` and `Q` removals as `wontfix`.  Upstream has justified this decision and they will not be making it back in.  Thanks @JohannesLorenz for the research.

**Comment by tresf** [comment]
> Aside from this, I discovered a few effects that need to be renamed. @tresf can I please ask you to help here (if it's not already done)?

Yes, I'll tackle the upgrade scripts. 👍

**Comment by tresf** [comment]
So the next step is merging in https://github.com/LMMS/veal/pull/2 which may require some rebasing to clean up the commit history (or we could just squash it all).  Then, we can point this PR back at `lmms/veal` and then we can merge.

**Comment by tresf** [comment]
Whoops... I missed this part... 

> Affected:
> * Multiband Compressor
> * Multiband Gate
> * Multiband Limiter
> 
> Those will **not be re-added**. Please read [this CALF issue](https://github.com/calf-studio-gear/calf/issues/98). @tresf can you please patch this?
> 
> |old   |new   |
> |---|---|
> |port <= 17   |don't change port info   |
> |18 <= port <= 23	   |remove port info   |
> |port >= 24   |port-id -= 6  |

I'll tackle this in the next day or so.

**Comment by tresf** [comment]
@JohannesLorenz 

So I've written the code in ab72fe2 but something's wrong... here's a before/after.  If I made a typo in the code, let me know.

image

**Comment by tresf** [comment]
@JohannesLorenz on Discord you suggested you'd like to see the raw XML.  Here it is... 

**BEFORE**
```xml
<effect on="1" autoquit_denominator="4" gate="0" autoquit_numerator="4" autoquit_syncmode="0" name="ladspaeffect" wet="1" autoquit="1">
              <ladspacontrols ports="49">
                <port04 data="1"/>
                <port05 data="32.24"/>
                <port06 data="64"/>
                <port015>
                  <data scale_type="log" value="15484.8" id="6433884"/>
                </port015>
                <port016>
                  <data scale_type="log" value="10" id="6128560"/>
                </port016>
                <port017>
                  <data scale_type="log" value="15757.1" id="5036555"/>
                </port017>
                <port018 data="-0.4675"/>
                <port019 data="0.3525"/>
                <port020 data="-0.38"/>
                <port021 data="4"/>
                <port022 data="0.590625"/>
                <port023 data="2.85"/>
                <port024 data="1"/>
                <port025 data="1"/>
                <port026 data="20"/>
                <port027>
                  <data scale_type="log" value="694.497" id="3739249"/>
                </port027>
                <port028>
                  <data scale_type="log" value="935.245" id="8090992"/>
                </port028>
                <port029 data="64"/>
                <port030 data="8"/>
                <port031 data="1"/>
                <port034 data="0"/>
                <port035 data="1"/>
                <port036 data="0.94158"/>
                <port037 data="14.8675"/>
                <port038>
                  <data scale_type="log" value="1221.99" id="7642734"/>
                </port038>
                <port039>
                  <data scale_type="log" value="820.746" id="2038352"/>
                </port039>
                <port040 data="15.12"/>
                <port041 data="8"/>
                <port042 data="1"/>
                <port045 data="0"/>
                <port046 data="1"/>
                <port047 data="1"/>
                <port048 data="7.48125"/>
                <port049>
                  <data scale_type="log" value="762.996" id="3731330"/>
                </port049>
                <port050>
                  <data scale_type="log" value="594.247" id="140482"/>
                </port050>
                <port051 data="27.9562"/>
                <port052 data="5.10125"/>
                <port053 data="0"/>
                <port056 data="0"/>
                <port057 data="1"/>
                <port058 data="0.894126"/>
                <port059 data="13.6562"/>
                <port060>
                  <data scale_type="log" value="640.497" id="7512257"/>
                </port060>
                <port061>
                  <data scale_type="log" value="1401.99" id="7497737"/>
                </port061>
                <port062 data="38.745"/>
                <port063 data="8"/>
                <port064 data="1"/>
                <port067 data="0"/>
                <port068 data="1"/>
              </ladspacontrols>
              <key>
                <attribute name="file" value="calf"/>
                <attribute name="plugin" value="Multibandcompressor"/>
              </key>
            </effect>
```

***AFTER***
```xml
            <effect autoquit_numerator="4" on="1" wet="1" autoquit_denominator="4" autoquit_syncmode="0" gate="0" autoquit="1" name="ladspaeffect">
              <ladspacontrols ports="44">
                <port04 data="1"/>
                <port05 data="32.24"/>
                <port06 data="64"/>
                <port015>
                  <data scale_type="log" id="6433884" value="15484.8"/>
                </port015>
                <port016>
                  <data scale_type="log" id="6128560" value="10"/>
                </port016>
                <port017>
                  <data scale_type="log" id="5036555" value="15757.1"/>
                </port017>
                <port018 data="1"/>
                <port019 data="0.3525"/>
                <port020 data="1"/>
                <port021 data="4"/>
                <port022 data="0.590625"/>
                <port023 data="2.85"/>
                <port024 data="1"/>
                <port025 data="1"/>
                <port028>
                  <data scale_type="log" id="8090992" value="1"/>
                </port028>
                <port029 data="1"/>
                <port030 data="1"/>
                <port031 data="1"/>
                <port032>
                  <data scale_type="log" id="7714001" value="94.5742"/>
                </port032>
                <port033>
                  <data scale_type="log" id="6424337" value="94.5742"/>
                </port033>
                <port034 data="1"/>
                <port035 data="1"/>
                <port036 data="0.94158"/>
                <port039>
                  <data scale_type="log" id="2038352" value="1"/>
                </port039>
                <port040 data="1"/>
                <port041 data="1"/>
                <port042 data="1"/>
                <port043>
                  <data scale_type="log" id="2020688" value="94.5742"/>
                </port043>
                <port044>
                  <data scale_type="log" id="5606438" value="94.5742"/>
                </port044>
                <port045 data="1"/>
                <port046 data="1"/>
                <port047 data="1"/>
                <port050>
                  <data scale_type="log" id="140482" value="1"/>
                </port050>
                <port051 data="1"/>
                <port052 data="1"/>
                <port053 data="1"/>
                <port054>
                  <data scale_type="log" id="4113707" value="94.5742"/>
                </port054>
                <port055>
                  <data scale_type="log" id="3838422" value="94.5742"/>
                </port055>
                <port056 data="1"/>
                <port057 data="1"/>
                <port058 data="0.894126"/>
                <port061>
                  <data scale_type="log" id="7497737" value="1"/>
                </port061>
                <port062 data="1"/>
                <port063 data="3"/>
              </ladspacontrols>
              <key>
                <attribute value="veal" name="file"/>
                <attribute value="MultibandCompressor" name="plugin"/>
              </key>
            </effect>
```

**Comment by tresf** [comment]
Patched via 8077007. @JohannesLorenz the knobs are [looking much better](https://user-images.githubusercontent.com/6345473/36058655-521f58c2-0df4-11e8-9749-3f4c40b13088.png).

**Comment by tresf** [comment]
All "veal" work all merged into `lmms/veal` repo (a fork of `calf-studio-gear/calf` with LADSPA1 enabled).  So no need to work from `tresf/veal` any longer. :)

I finished testing the remaining plugins and found two that need attention:

* [Calf Pulsator](https://user-images.githubusercontent.com/6345473/36069332-77ffe4fa-0eb5-11e8-8ce0-8b3e2996b813.png)
* [Calf Vintage Delay](https://user-images.githubusercontent.com/6345473/36069417-2a4d4fd4-0eb7-11e8-9dcb-435de4fb653d.png)

Both of these plugins got some new knobs and remapping them is needed prior to merge.

Also, the Windows builds are failing in Travis.  It's complaining about C++11 features which should be easy enough to toggle back on.

**Comment by tresf** [comment]
@JohannesLorenz just a bump, I know you're working hard on some other things, but I'd be happy to merge this once we can sort out the remaining plugins.

**Comment by JohannesLorenz** [comment]
@tresf The only thing I've been working hard on in the last 2 weeks was curing the flu ;) I'll restart coding tomorrow

**Comment by JohannesLorenz** [comment]
There is still a bit work left to do. Sidechain Compressor originally had 3 modes:
1. The sidechain signal is built of the filtered input signal.
2. The filtered left channel is the sidechain, the right signal is the input signal.
3. The filtered right channel is the sidechain, the left signal is the input signal.

Now, the new CALF filter uses 4 inputs instead of 2: 2 for the input signal, 2 for the sidechain input:
1. The sidechain signal is built of the filtered input signal. (like 1. above)
2. The sidechain signal is built of the filtered sidechain signal

This raises 2 problems:
* LMMS can only handle two inputs, so currently, point 2 is of no use. (Sidechaining can still be done by connecting the "S/C Level" knob)
* We have a regression issue for points 2 and 3.

One possible solution (similar to what I did with the vocoder) would be to prepend a stereo input port, where one channel splits over the two CALF input ports, and the other channel splits over the two CALF sidechain inputs. Should we prepend this, or just leave the CALF ports like they are in CALF now?

**Comment by JohannesLorenz** [comment]
Three more commits, one being a merge from CALF's master
(no further parameter changes), another one fixing a lot of parameters.

There were a few effects where we could not keep compatibility
for all parameters (@tresf: Can you please mark this in the table?):

* All sidechain effects: L/R sidechaining is not possible anymore.
  - Reason: CALF does not provide code for this anymore.
  - Fix: In one of the next LMMS versions, we will hopefully allow
         side-inputs for effects. Until then, there is no fix. We're really sorry! :sweat:
* StereoTools: Multiple knobs, mostly S-Level and M-Level.
  - Reason: Old effect was either buggy or it did behave significantly
            different.
  - Fix: None. :neutral_face: 

Can we start testing again?

**Comment by tresf** [comment]
New binaries available for testing:

https://github.com/tresf/lmms/releases/download/vmaster/lmms-1.2.0-rc5.6602-linux-x86_64.AppImage
https://github.com/tresf/lmms/releases/download/vmaster/lmms-1.2.0-rc5.6602-mac10.12.dmg
https://github.com/tresf/lmms/releases/download/vmaster/lmms-1.2.0-rc5.6602-win32.exe
https://github.com/tresf/lmms/releases/download/vmaster/lmms-1.2.0-rc5.6602-win64.exe

**Comment by tresf** [comment]
No one seems interested in testing this further than @JohannesLorenz and myself have so it will have to be tested from `master`.  Calf is widely used so minor regressions should be expected.  Merging.  Thanks @JohannesLorenz terrific work on this one.  @JohannesLorenz brought back LADSPAv1 support and wrote some excellent upgrade calls.

**Comment by karmux** [comment]
How to do sidechaining at the moment with Veal?
Previously with Calf I connected the Peak Controller of some channel to the S/C Level knob of SC Compression but S/C Level doesn't change sound at all anymore. I tried with all SC Mode values. Tried with many combinations of other knobs as well.

**Comment by tresf** [comment]
He's not talking about L/R panning he's talking about the SC knob which should still be fully supported; If not, it needs to be fixed.

**Comment by karmux** [comment]
Yes I didn't talk about L/R chaining but basic kick and bass sidechaining which is broken at the moment.

**Comment by JohannesLorenz** [comment]
Many thanks for the info. I'll try to debug it this week.

**Comment by karmux** [comment]
Calf Sidechain Gate seems to be working.
Calf Sidechain Limiter crashes LMMS when adding it in most of my projects and if not then when pressing play or when previewing samples.

**Comment by JohannesLorenz** [comment]
@karmux Thanks. Sorry, I forgot about your previous comment. I'll take a look at everything this week.

**Comment by JohannesLorenz** [comment]
@karmux Both issues were fixed in CALF. I merged into master and pushed, and it seems to be working there.

Many thanks also to @boomshop for fixing these issues instantly!

**Comment by karmux** [comment]
@JohannesLorenz and @boomshop, many thanks to you!

**Pull request merged**
