### PR TITLE
FreeBSD build version

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by PhysSong** [comment]
Since I don't have a machine with FreeBSD, I can't test this PR.
BTW, have you searched for all `LMMS_BUILD_LINUX` and checked if it requires more changes?

**Comment by devnexen** [comment]
This is the safest changes for now, most of them are linux-ism (plugins)

**Comment by devnexen** [comment]
Thinking of it, Cirrus CI might be a way to test FreeBSD.

**Comment by PhysSong** [comment]
> Thinking of it, Cirrus CI might be a way to test FreeBSD.

Sounds good. You can add a config file if you want, then we can enable CI in this repository. If you're not going to do that, you can open an issue as a suggestion.

**Comment by devnexen** [comment]
I took a template, we shall see ...

**Comment by zonkmachine** [comment]
Should this be merged?

**Comment by zonkmachine** [comment]
@devnexen Thanks!

c9b2194fb07d058ccf7d74b843b7dd8b8dfaaacc was merged separately in 732448c3921d9ef2e4297d6670ecfcade42e8572. The Cirrus CI part was deemed better suited for downstream after a discussion on our discord/#devtalk channel.

**Pull request closed without merging**
