### PR TITLE
Song Editor and bbEditor undo.

### PR DESCRIPTION
**Pull request by curlymorphic**
Editing of song arrangement is now undoable.
Editing of bb patterns is undoable

Adding and removing tracks is not implemented yet, that is going to take some more work.
Changes in length to bb patten is also not undoable yet.

### CODE REVIEW

**Comment by tresf** [comment]
Tremendous.  Reading the code I'm curious how well this works for right click->delete, middle-click, etc.  We really need some testing on this one @mikobuntu any interest?

I remember track moving spiked memory use by magnitudes so I'm interested and eager to know how well this works.

Also, is the Journal Checkpoint self-aware of entries that didn't change anything? (I assume it is?)

**Comment by mikobuntu** [comment]
" We really need some testing "
@tres , yes I will test this out and report back with progress ;)

thanks Mikobuntu ;)





  
    
    
  
  
 		 	   		  =

**Comment by Spekular** [comment]
Undo is a pretty big feature and it seems like adding a journal entry is a
pretty easy way to allow undoing of an action. Is that all that needs to be
done? Do we/should we have multiple journals (bb journal/se journal etc.
Similar to blender where edit mode changes are separate from object mode)

**Comment by curlymorphic** [comment]
From yesterdays tests, journals in there current state are good at saving changed data, not so good when adding  or deleting. for example if an instrument track is deleted, you cant simply write it's xml data back. you would have to recreate the track, load the instrument, then restore the xml, on the other hand, if a tco is moved, it is simply just a cast of restoring it's old position.

What i have done  here is by no means a complete solution. Its the start of something that may take along time to complete.



> Do we/should we have multiple journals (bb journal/se journal etc.
> Similar to blender where edit mode changes are separate from object mode)

atm the undo is done thru a global journal. Multiple journals is a possibility, but does add another layer of complexity and if we decide to go that route, a fair bit of designing. Would it be 1 for every window, what happens to linked controllers, data concurrency across journals, etc.

**Comment by tresf** [comment]
Will merge or comment based on @mikobuntu's finding.  Thanks for the explanation Dave, greatly appreciated.

**Comment by curlymorphic** [comment]
I have done some reading on undo systems, as i have seen the idea mentioned :) 

In an ideal world using journals is not the best way forward. A Command pattern is normally used, and Qt does have a framework for this.

from the Qt manual


The Command pattern is based on the idea that all editing in an application is done by creating instances of command objects. Command objects apply changes to the document and are stored on a command stack. Furthermore, each command knows how to undo its changes to bring the document back to its previous state. As long as the application only uses command objects to change the state of the document, it is possible to undo a sequence of commands by traversing the stack downwards and calling undo on each command in turn. It is also possible to redo a sequence of commands by traversing the stack upwards and calling redo on each command.


http://qt-project.org/doc/qt-4.8/qundo.html

Lmms is currently not written using commands that know how to undo themselves. This would involve a lot of work and alot of testing, but would probably result in a better system. If we had the resources I would recommend this.

The Journal method while still needs testing, does not change the actual code base. appart for 1 liners to take a 'snapshot', so the amount of code that gets broken and needs fixing should be far less. There is also no need to code,test,debug  an undo function for every command. So the dev time should be shorter.  The downside , im sure we are going to hit limitations.

So i guess it's a decision as to what route to take?

**Comment by Spekular** [comment]
Using commands seems best to me. Perhaps yet another 2.0 project?

**Comment by tresf** [comment]
> So i guess it's a decision as to what route to take?

Great question.  If we track everything with Journaling today, we should probably enhance that to suit our needs.  If the Journaling limitations seem too much work, we should reconsider and begin the switch to qundo.

What we may be able to do is... once `stable-1.2` is released, we may decide to start the work for qundo but override its shortcut key (such as using Meta + Z) so that we don't go blowing away good journaling code without some testing.

**Comment by tresf** [comment]
@curlymorphic we should probably side-bar the undo convos into a separate thread.

**Comment by tresf** [comment]
Merging because this can easily be reverted if needed and we should get some real world testing on it.

**Comment by jackokring** [comment]
I'd suggest not deleting the track, but just muting (or placing it on a different pointer chain) (and) making it invisible. This would make redo much simpler. The save of a project would then involve appending extra information (if the undo buffer is kept).

I did suggest in another issue having a tool bar button to drop down a list of "deleted" tracks relevant to specific windows, so undo would not just be for accidents, but would work as a delete multi entry clipboard. This could be particularly useful when CPU is maxing out, and a mix down render is an option.

When memory is getting low, a need to purge the clip would occur. I suggest a memory bar similar to the CPU bar, and a "purge" clip drop down entry (listing all clip types). This would have to remove the redo entry by replacing it with a pop up dialog (on redo), indicating the track has been purged.

**Comment by tresf** [comment]
@jackokring You're commenting on an already-merged and closed PR, so the audience for your comments will be limited.  You should consider putting your points in context of a problem, i.e.  

> Lmms is currently not written using commands that know how to undo themselves. This would involve a lot of work and alot of testing, but would probably result in a better system. If we had the resources I would recommend this.

> The Journal method while still needs testing, does not change the actual code base. appart for 1 liners to take a 'snapshot', so the amount of code that gets broken and needs fixing should be far less. There is also no need to code,test,debug an undo function for every command. So the dev time should be shorter. The downside , im sure we are going to hit limitations.

> So i guess it's a decision as to what route to take?

Were they in context of this question? --^

Side note... the functionality you describe is inconsistent with how we do journaling today.  If you are serious about opening up a bug report on this topic and discussing the best approach, you should make sure to explain your reasoning for breaking our current design.

**Comment by jackokring** [comment]
The undo of track deletes does not work in the 1.1.3-g3e03e71 build I made last night.

I don't see how the inconsistency arises, if the undo worked (let's assume it did), then there would be a representation of how to re-insert the track, my assertion was to 'save' this as an extended clip for certain 'recyclables' and have a method to carry out the insertion without a full undo rewind.

I agree that this would not be possible for all undo 'anti commands', but for some it would be and would therefore be useful.

The thread I reached this one from said there was more information on the issue here. I'm not suggesting you in anyway change progress toward the current functionality prospect, but after that prospect, I think it is worth considering a sub classing override on some journal class methods.

**Comment by tresf** [comment]
Can we move this discussion please?

**Pull request merged**
