### PR TITLE
Enable plugins msvc

### PR DESCRIPTION
**Pull request by dan-giddins**

### CODE REVIEW

**Comment by Rossmaxx** [comment]
are you still working on this or did you abandon it?

**Comment by dan-giddins** [comment]
> are you still working on this or did you abandon it?

@Rossmaxx I do plan on trying to finish this at some point in the future, but I don't think I will be working on it any time soon... feel free to branch off and work on this if you would like to (if you do I'd be interested in seeing how you get on)

**Comment by dan-giddins** [comment]
Linking #6758 to this PR

**Comment by Rossmaxx** [comment]
#6758 is now complete. If you don't mind, can you close this one?

**Pull request closed without merging**
