### PR TITLE
Properly disable FadeButtons when tracks are muted

### PR DESCRIPTION
**Pull request by enp2s0**
FadeButtons on muted tracks weren't properly disabled (they wouldn't pulse when they activate, but they would still glow dimly when the note was being held). This fixes that. 

It also changes the way FadeButtons are disabled, as the old way specified colors in two unique places, meaning that changing the colors of an active Fadebutton might not affect a muted one, and vice versa. This PR adds a new method to FadeButtons that allows them to be enabled/disabled, and simply keeps them at their base color when disabled.

### CODE REVIEW

**Comment by enp2s0** [comment]
Fixes #5998

**Comment by enp2s0** [comment]
Also, ignore all the bogus PR commits, they are from me making PRs from lmms/lmms to enp2s0/lmms to update my forked master branch.

**Review by IanCaio — CHANGES_REQUESTED** [review]
Minor code style guidelines fixes.

At first glance code looks good. Did you test muting the track in the middle of the fading animation? Does it stop in the animation before it finishes?

**Comment by enp2s0** [comment]
When muting a track that's currently playing a note, the animation immediately stops (which I think is the best way to handle this, since the sound immediately stops as well).

I'm hesitant to apply those style changes -- it seems better to follow the style of the files for such a small change, it would be confusing imo to have a file with everything in one style and a few lines in a different one. When we do a project-wide formatting the styles will be corrected everywhere anyway, and having, for example, two different styles in the *same function definition* is a bad practice imo.

**Comment by softrabbit** [comment]
Looks good. The compiled LMMS, that is. I'll leave the code formatting nuances to someone else, but I know I'm firmly on the side of "make the code fit in with the surrounding code", e.g.:

> I'm hesitant to apply those style changes -- it seems better to follow the style of the files for such a small change, it would be confusing imo to have a file with everything in one style and a few lines in a different one. When we do a project-wide formatting the styles will be corrected everywhere anyway, and having, for example, two different styles in the _same function definition_ is a bad practice imo.

**Comment by IanCaio** [comment]
This argument of the automatic changes have been used before and I've even been flexible with style change requests on recent previous reviews but I'm back to being a little more strict, and here's why:

The argument against a strict code style review was that there would be an automatic code style change on the whole code base (the clang PR) and that it would fix everything anyways. The Clang PR is being worked on right now and as I have warned before it isn't that simple to automatically fix everything. The code style isn't going to magically be 100% fixed in the code base and there will probably be stuff left to be fixed manually. The more uncompliant code is added, the more work is also added to the refactoring. We have very few active devs that would actually work on this and I personally, as one of the maybe 2 devs that was more strict with style, will feel very uncomfortable if I've to fix it on a PR that I had already reviewed for style before.

If we are not being strict with code style we should remove the code style guidelines page even if temporarily, it feels tiring to have to defend something that is explicitly written in our contribution wiki. I can even notice how some contributors dislike having this kind of review on their PRs like somehow I'm nit-picking them.

### That all aside:

There's no surrounding code on `muteChanged` that uses one line `if` with no explicit code blocks, so at the very least that one I'll have to be firm about.

**Comment by IanCaio** [comment]
Oh, and I'm cool with the animation stopping midways. I was just double checking because I haven't tested the build yet and from the code it seemed that if you muted in the middle of the animation, the LED might be frozen in the animation frame it was at the moment of the muting. All good by me if we use this behavior.

**Comment by Spekular** [comment]
The LEDs blinking when muted is intentional, it's just the color gradient that needs adjustment. Even if you intend to have them not blink, you could simply make use of the existing muted property instead of introducing a new `enabled` property.

**Pull request closed without merging**
