### PR TITLE
Fix race condition in TrackContainer::removeTrack

### PR DESCRIPTION
**Pull request by Wallacoloo**
Possible execution path to trigger race condition:
1. `index` is set to the location of the track within `m_tracks`
2. Some other thread comes in and modifies `m_tracks`
3. local `index` variable is tested against `-1` and found to be valid. We lock `m_tracks` and delete the track.

The error: since m_tracks was modified by another thread *after* index had been calculated, we could be deleting the wrong track.

The solution is that `m_tracks` *must* be locked for reading by the current thread before we calculate `index`. Once it's found to be valid, then we upgrade to a write lock as we modify `m_tracks` and release it once we're done.

Unfortunately, Qt does not support any lock upgrade mechanism, as far as I can tell. It's unsafe to release the read lock and then acquire a write lock, as another thread could modify `m_tracks` during the in-between time. Therefore, we must be pessimistic and start out with a write lock, which is a valid thing to do since a write lock is stronger than a read lock.

### CODE REVIEW

**Comment by Wallacoloo** [comment]
The following code in this file also concerns me [TrackContainer.cpp:205-213](https://github.com/LMMS/lmms/blob/ca746e50f9bfe69efa36943bbeaca5301bcc492a/src/core/TrackContainer.cpp#L205:L213):

```c++
void TrackContainer::clearAllTracks()
{
    //m_tracksMutex.lockForWrite();
    while( !m_tracks.isEmpty() )
    {
        delete m_tracks.first();
    }
    //m_tracksMutex.unlock();
} 
```

Anyone care to explain why the lock statements are commented out while `m_tracks` is *clearly* being modified?

**Comment by Wallacoloo** [comment]
Indeed, there are code paths in which the body of this function is executed without `m_tracksMutex` being locked. Just start lmms and it'll reach there as the UI is being launched.

```$ gdb lmms
(gdb) b TrackContainer::clearAllTracks
Breakpoint 1 at 0x558a00: file /home/colin/proj/lmms/src/core/TrackContainer.cpp, line 208.
(gdb) r
Starting program: /home/colin/proj/lmms/build-debug-gcc/install/usr/local/bin/lmms 
[...]
Breakpoint 1, TrackContainer::clearAllTracks (this=0xaf7700) at /home/colin/proj/lmms/src/core/TrackContainer.cpp:208
208		while( !m_tracks.isEmpty() )
(gdb) p this->m_tracksMutex.tryLockForWrite()
$1 = true
(gdb) bt
#0  TrackContainer::clearAllTracks (this=0xaf7700) at /home/colin/proj/lmms/src/core/TrackContainer.cpp:208
#1  0x0000000000545f76 in Song::clearProject (this=0xae2bc0) at /home/colin/proj/lmms/src/core/Song.cpp:778
#2  0x00000000005466cf in Song::loadProject (this=0xae2bc0, fileName=...) at /home/colin/proj/lmms/src/core/Song.cpp:934
#3  0x000000000054652d in Song::createNewProjectFromTemplate (this=0xae2bc0, templ=...) at /home/colin/proj/lmms/src/core/Song.cpp:899
#4  0x00000000005461e8 in Song::createNewProject (this=0xae2bc0) at /home/colin/proj/lmms/src/core/Song.cpp:839
#5  0x00000000004d4f3c in main (argc=1, argv=0x7fffffffe1b8) at /home/colin/proj/lmms/src/core/main.cpp:497```

When `p this->m_tracksMutex.tryLockForWrite()` prints 'true', this means that the mutex wasn't previously locked.

So I believe these lines should be uncommented.

**Comment by badosu** [comment]
@Wallacoloo 
> The following code in this file also concerns me TrackContainer.cpp:205-213:

Funnily enough, this was added on this commit: https://github.com/lmms/lmms/commit/fe7d269c

**Comment by badosu** [comment]
@Wallacoloo Maybe this can help you to further investigate race conditions with `m_tracks`?

#2043

**Comment by Wallacoloo** [comment]
Good to merge?

**Comment by tresf** [comment]
It is a small enough fix although I think this is the first time our codebase has seen this write locker, so we may not get much more useful feedback prior to merging. :+1:

**Comment by Wallacoloo** [comment]
@tresf indeed, I believe it is, and we should probably try to use these locker objects in any future code, based on the comment @michaelgregorius made [here](https://github.com/LMMS/lmms/issues/2040#issuecomment-100667485).

I'm going to leave the `TrackContainer::clearAllTracks()` method as-is for now - adding a lock there would require some more extensive testing, and after 1.2 is released I'd like to obsolete much of this locking by working towards a system where the UI thread isn't competing with the rendering thread willy-nilly. i.e. establish some actual message-passing protocol, as touched upon briefly throughout [this](https://github.com/LMMS/lmms/issues/1911#issuecomment-88137166) thread.

**Pull request merged**
