### PR TITLE
Better French translations in the menu item file

### PR DESCRIPTION
**Pull request by trebmuh**
in order to stick with the original English meaning

### CODE REVIEW

**Comment by jasp00** [comment]
Transifex should be used for these translations.

**Comment by trebmuh** [comment]
Are you 100% sure @jasp00 ? If the translation of the desktop item file would be in transifex (or another sort of translator tools), then the ca/fr/de/... translation wouldn't be in the .desktop file, isn't it?

**Comment by jasp00** [comment]
You can build the `.desktop` from all `.ts`; coding exercise.

**Comment by trebmuh** [comment]
I'm not a coder, hence I didn't understand what you said.

**Comment by jasp00** [comment]
>I'm not a coder

Do you want to be? No hurries.

**Comment by DomClark** [comment]
Is the `.desktop` currently built from the `.ts` files? Certainly this would be nice to have, but if it isn't at the moment, and no-one's about to implement it, shouldn't this PR suffice for `stable-1.2`?

**Comment by trebmuh** [comment]
> Is the .desktop currently built from the .ts files?

I don't think so.


>  shouldn't this PR suffice for stable-1.2?

Yes, hence my PR here.

**Comment by jasp00** [comment]
> >I'm not a coder

>Do you want to be?

An answer would be appreciated.

**Comment by trebmuh** [comment]
>>> I'm not a coder

>> Do you want to be?

> An answer would be appreciated.

Depends what that means/involved in your sentence.

**Comment by jasp00** [comment]
>Depends what that means

Since coding is fun, let us assume you want to be a coder; you can change your mind later. There are no deadlines. First goal is to build this `.desktop` generator.

Do you want to start solving the problem right away or do you want to train some skills first?

**Comment by trebmuh** [comment]
I'll be AFK for the next 4 or 5 days.

> Do you want to start solving the problem right away or do you want to train some skills first?

You're the teacher, your call.

**Comment by zonkmachine** [comment]
> Transifex should be used for these translations.

Transifex is now pointing to master so we've accepted translation fixes against stable-1.2 here.
Not general translation work but in cases where formatting has been broken etc.

**Comment by jasp00** [comment]
@trebmuh, read [Becoming a coder](https://github.com/LMMS/lmms/wiki/Becoming-a-coder) and try to complete the activities.

**Comment by zonkmachine** [comment]
@liushuyu Is it too much work for two lines to have this merged in stable-1.2 and then updated on Transifex? We could refer this to master/Transifex directly but this is the new wording of the menu file and just looks better.

**Comment by jasp00** [comment]
>There are no deadlines.

Just my opinion: I believe this request is more useful if it is not merged yet.

**Comment by PhysSong** [comment]
For 1.2, I vote for merging this if there are no objections.

**Comment by JohannesLorenz** [comment]
I'm for keeping the number of open PRs low (to not oversee PRs) and merging this one does not harm. If anyone wants a generator, I propose they set up a separate issue.

Merging in 5 days if no one has objections (and I don't forget).

**Comment by trebmuh** [comment]
@JohannesLorenz has this been merged and we can close this PR?

**Comment by JohannesLorenz** [comment]
> has this been merged

Yes :smiley:

**Comment by trebmuh** [comment]
Thank you!

**Comment by pikachuk** [comment]
There is an issue that is still there since a long time that I reported multiple times in the french translation 
image
where "sauvegardder en tant que omdele par defaut" is written instead of "sauvegarder en tant que modele par defaut"

**Comment by JohannesLorenz** [comment]
@pikachuk The only way to fix this is by getting a Transifex account and editing it there.

**Comment by trebmuh** [comment]
Nope, that's not the only way (or it shouldn't be). @liushuyu is usually managing to keep his github repo and the transifex one in sync.
That being said, I remember to have fixed this typo a while ago. It is strange that it came back.
@liushuyu do you have any idea of what is going on here?

**Comment by liushuyu** [comment]
>That being said, I remember to have fixed this typo a while ago. It is strange that it came back.
@liushuyu do you have any idea of what is going on here?

Probably someone overrode your changes on Transifex.

>BTW it is unfortunate that a free software is kind of enforcing to use a non-free product to work on the translation. @liushuyu has been helping me on the last years so I can translate LMMS (soft + website) into French without giving information to yet another business non-free company. I would suggest to switch to Weblate here.

Well, actually Transifex was releasing the source code of their website before they made their service as a kind of SaaS.

**Comment by trebmuh** [comment]
The **was** is the point. Too bad.

It seems to me that Weblate is still releasing [its code](https://github.com/WeblateOrg/weblate) under a free licence.

**Pull request merged**
