### PR TITLE
New UI design for gig player plugin

### PR DESCRIPTION
**Pull request by Rossmaxx**
Let's be honest, the old ui for gigplayer looked incomplete. I designed this ui by taking inspiration from a tree, and also to make it match with other plugins. The backdrop and the images are taken from grimnir's maxim with his permission, which i tweaked. All the "wooden" parts are my design. 

Here's the new UI. 

image

Do note that i'm willing to change anything with the artwork as it's a wip.

tagging @RebeccaDeField for ideas/suggestions.

Also, spek mentioned about having proof for permission. Hope this screenshot might suffice.

Screenshot_20240111_185311

### CODE REVIEW

**Comment by Monospace-V** [comment]
prefer the old one.
Additionally see no point in updating.

**Comment by Spekular** [comment]
> The backdrop and the images are taken from grimnir's maxim with his permission

Design-opinions aside, any permissions (/ agreements / licenses) need to be properly documented / recorded for future reference.

**Comment by Rossmaxx** [comment]
> Design-opinions aside, any permissions (/ agreements / licenses) need to be properly documented / recorded for future reference.

I've attached a screenshot now. Hope that's enough.

**Comment by Rossmaxx** [comment]
Did an update to the artwork.
image

@Monospace-V you still feel like it's bad or is this update better acc to you?

**Comment by Monospace-V** [comment]
I still don't like it, unfortunately. This is just my opinion, of course, but I really don't like this design base.
I liked the old one, it was elegantly empty. This one feels wrong. The colours; the font; the tree (why?); the design... I really find it unpleasant.
If we feel we need an update to the artwork of the GIG Player plugin art, I'd be glad to try and contribute on that front. But I am really not willing to let this design merge. I don't like it, and I don't like how it looks.

If you think it's a sensible idea, though, I'd be glad to try my own hand at this.

**Comment by Rossmaxx** [comment]
> If you think it's a sensible idea, though, I'd be glad to try my own hand at this.

Feel free to, and send it to me on discord. I'll take a look.

**Comment by Monospace-V** [comment]
> Feel free to, and send it to me on discord. I'll take a look. 
Gotcha. There's a lot of other things I got to do rn, but I'll put this one down. I might open a separate PR for it aside though, simpler as a single job. I typically work with lines, it might look interesting.

**Comment by enp2s0** [comment]
I have to agree with @Monospace-V here -- this design looks extremely dated and doesn't fit with the LMMS style, at all.

**Comment by Rossmaxx** [comment]
Got another random thought, I'll just convert the "sign boards" to something line based. I'll keep the browns tho.

**Comment by Rossmaxx** [comment]
here's a quick mock up 
image

To proceed, I need to edit other image assets too. Need some opinions before i start with that.

Note : This design is based on the one monospace sent me on discord.

**Comment by Monospace-V** [comment]
> To proceed, I need to edit other image assets too. Need some opinions before i start with that.
> Note : This design is based on the one monospace sent me on discord.

as far as this thread goes, this is better than the initial, but I still don't see a point replacing. I personally like the current design enough, and we are achieving nothing by making our Gig player green.
I am only working on my design because I didn't like this one. But the LMMS GIG player doesn't need a redesign as I see it.
So I guess my opinion is no. It's not bad, but I don't find it good enough to be worth changing to.

For reference, my work looks something like this:
image
I may not finish this, but if we are _going_ to change the GIG Player design I will try.
I may not be proud of the lack of finesse here, especially with my shadow skillset being nil and the odd line weight at some points, but I can learn if I need to and am willing to make up for it with time.

**Comment by sakertooth** [comment]
> as far as this thread goes, this is better than the initial, but I still don't see a point replacing. I personally like the current design enough, and we are achieving nothing by making our Gig player green.

Yeah, there's no point IMO.

**Comment by Rossmaxx** [comment]
Though i did some un asked for stupidity with this PR, i have been noting another use case for a gig player redesign, mainly to remove the .ui file (should do this for sf2 player too). Will wait till Michael is done with his instrument scaling work.

**Pull request closed without merging**
