### PR TITLE
Update ko.ts

### PR DESCRIPTION
**Pull request by MarongHappy**

### CODE REVIEW

**Comment by Rossmaxx** [comment]
what is this pr about?

**Comment by Monospace-V** [comment]
> what is this pr about?

According to the "Files changed" section, ko.ts is in /data/locale. "locale" usually means localization, and by extension ts must be translation or something like that. Presumably ko.ts is the Korean translation.

**Comment by qnebra** [comment]
I guess someone wanted to update translations directly, instead through Transifex.

**Comment by perillamint** [comment]
I'd strongly suggest DO NOT MERGE this pull request. This committer is notorious translation troll who produce poor translation (most of them are machine translation anyway., see https://github.com/Ultimaker/Cura/pull/11308), does not bother to match their "translation" nuance, behave badly on GNOME l10n and KDE i18n lists.

Additionally, I'd STRONGLY recommend to BLOCK this person from the Transifex to protect the quality of translation.

**Comment by PhysSong** [comment]
I already thought that the translation contains unusual terms such as "방형파" for square wave(it's not incorrect but very uncommon in audio domain), "톱파" for sawtooth wave("톱니파" is much more widely used), or "배율기" for multiplier when it's not for electric circuits.
I was planning to just fix problematic translations when I have enough time, but according to @perillamint's report, it might be better to revert the whole contributions because the translator translated 2208 out of 3055 strings, which is very hard to review one by one.

@MarongHappy Thank you for your effort, but I'm giving you a warning: **bad translations are worse than no translations**. Consider this as the final warning. If you add more weird translations, you will be blocked.
@perillamint Again, thanks for your report!

**Comment by PhysSong** [comment]
@MarongHappy Additional note: I've removed all of your contributions for now, but I will allow you to re-add some translations **only if you're 100% sure the string is correct and natural in given context**. Otherwise, you will be banned on Transifex.

**Comment by MarongHappy** [comment]
물론 내가한 LMMS 번역이 완벽하다 자신하고 주장할 수 없습니다.
또한, 실수도 있을수 있고 전문가가 아니니 최대한 찾아보고 고민하고 용어를 선택을 했다고 생각합니다.
제가 생각하기에 기존의 번역되어 있는 번역또한 완벽하지도 정확하지도 않았다고 생각합니다.

그렇게 생각했기에 2년가까이 지켜보면서 번역작업을 해왔습니다.
저 말고도 기여해주시는 몇몇 분들도 지켜보니 구글번역의 붙여넣기 수준인 번역이 많았습니다.
그러다 보니 오역이나, 몇몇 용어들의 다른 표기등, 동사의 명사형으로 인해 아리송한 번역들이 많았다고 생각합니다.
Transifex에서 번역한 자료들을 github 올린것이 큰 문제가 된듯 하군요.

리눅스는 개방적인 시스템이고 다양한 기여자들의 참여를 원하면서도 정작 기여를 하고 참여를 하려하면,
상당히 보수적인 관리자들과 기여에 대한 배척을 논하는 글들을 몇몇 보게됩니다.
내가 원하고 행하고자 했던 것은, 많은 프로그램들이 완전한 한국어로 많은 사람들이 편하게 즐길 수 있기를 바랬던 것 뿐입니다.

기쁨 마음으로 번역을 하였고, 좋은 프로그램을 한국어로 좀 더 빨리 즐기고 싶다는 마음이 너무 앞섰나 봅니다.
LMMS를 번역에 대한 나의 행동이 문제가 됐다면, 제가 기여한 모든 번역을 지워주시고 삭제해 주십시오.

그리고 Transifex LMMS 한국어 번역팀에서 차단당하지 않도록 노력해보겠습니다.
차단당한다는 글을 보니, 착참한 마음을 금할 길이 없지만, 내 행동이 어디서 잘못됐는지 다시한번 생각해 보겠습니다.

마지막으로, Transifex의 번역과는 달리 역시 github는 피드백이 빠르고, 다양하군요.
한국분이면 한국어로 답들 달아주셨으면, 좀더 감사했을것 같습니다.

답글 감사했습니다. 송현진님.

2022년 5월 8일 (일) 오전 11:05, Hyunjin Song ***@***.***>님이 작성:

**Comment by MarongHappy** [comment]
> This commit contains lots of flaws and extremely hard to review due to complete mix up of translation pair order, as usual as translation from them.
> 
> Since GitHub refuses to start review process of this commit because the diff is too huge to handled by GitHub UI, it is impossible to point out flaw line-by-line here but I'll list my quick review (skimmed through 5minute) of the commit here.
> 
> 1. I'd strongly recommend do not touching GPL license text, unless the translator is fully experienced lawyer
> 2. Most Korean audio experts does not use translation "평균화" for the translation of "Normalize".
> 3. Translating "About text here" to "여기 텍스트 정보"... No machine translation is allowed here. Please close your translate.google.com window now and do the translation by hand.
> 
> I'd strongly suggest DO NOT MERGE this pull request. This committer is notorious translation troll who produce poor translation (most of them are machine translation anyway., see [Ultimaker/Cura#11308](https://github.com/Ultimaker/Cura/pull/11308), ), does not bother to match their "translation" nuance, behave badly on GNOME l10n and KDE-kr lists (https://mail.kde.org/pipermail/kde-kr/2021-May/000032.html, not only limited to this conversation).
> 
> Additionally, I'd STRONGLY recommend to BLOCK this person from the Transifex to protect the quality of translation.

You gossip at me, but I will respect you.
However, I will give you one piece of advice.
Don't underestimate the goodwill of the contributor.

**Comment by perillamint** [comment]
> 한국분이면 한국어로 답들 달아주셨으면, 좀더 감사했을것 같습니다.
This project is not maintained solely by Koreans. Lots of maintainers could not speak nor read Korean, so if Korean people discuss project-related stuff in Korean, it would render impossible or extremely troublesome to understand the conversation to them. So, it is strongly recommended to discuss in English (as you know, the de-facto common language in Earth) in this case.

> 내가 원하고 행하고자 했던 것은, 많은 프로그램들이 완전한 한국어로 많은 사람들이 편하게 즐길 수 있기를 바랬던 것 뿐입니다.
Again, bad translation is more harmful than no translation. Bad translation can cause trouble, and it can screw up people effectively. For example, AWS "termination" (translated in "종료") and "shut-down" (translated in "중지") translation caused many cases of data loss among Korean AWS users who used the control panel in Korean translation. Keep this in your mind when doing translation next time. Just filling *.po file using machine translation service and call it a day is definitely not good attitude for translator.

**Comment by MarongHappy** [comment]
While checking my email on Google Mail, I came across a post from a Korean,
and I didn't think my post would be posted on github.

Now I want to stop talking about my writing.

2022년 5월 8일 (일) 오후 8:45, perillamint ***@***.***>님이 작성:

**Pull request closed without merging**
