### PR TITLE
versioninfo.h: improve recognition of compiler and platforms

### PR DESCRIPTION
**Pull request by barracuda156**
@tresf Forward-porting the fix :) 

P. S. For the record, while the logic appears coherent and simple, this is untested, as my environment does not support building from the master.

**Edit: @tresf:**

This is a forward-port of #6794

### CODE REVIEW

**Comment by tresf** [comment]
@barracuda156 thanks!

This causes a compilation error, perhaps a copy/paste error?

```
In file included from /Users/owner/lmms/src/gui/modals/AboutDialog.cpp:29:
/Users/owner/lmms/include/versioninfo.h:61:23: error: redefinition of 'LMMS_BUILDCONF_PLATFORM'
constexpr const char* LMMS_BUILDCONF_PLATFORM = "unknown platform"
                      ^
/Users/owner/lmms/include/versioninfo.h:41:23: note: previous definition is here
constexpr const char* LMMS_BUILDCONF_PLATFORM = "OS X";
                      ^
/Users/owner/lmms/include/versioninfo.h:61:67: error: expected ';' after top level declarator
constexpr const char* LMMS_BUILDCONF_PLATFORM = "unknown platform"
                                                                  ^
                                                                  ;
```

**Comment by barracuda156** [comment]
@tresf Indeed, thank you for pointing out. Will fix it now. Sorry, missed it.

**Comment by barracuda156** [comment]
@tresf Added it: https://github.com/LMMS/lmms/compare/f23ccccbcdfeb5c399854f7015142da6db7e1271..6d6dc9d729cc5d211b5e8337dd4f72b3bee87e06
But GH does not restart CI.

**Comment by tresf** [comment]
@barracuda156 

New error:

```
In file included from /Users/owner/lmms/src/gui/modals/AboutDialog.cpp:29:
/Users/owner/lmms/include/versioninfo.h:61:23: error: redefinition of 'LMMS_BUILDCONF_PLATFORM'
constexpr const char* LMMS_BUILDCONF_PLATFORM = "unknown platform";
                      ^
/Users/owner/lmms/include/versioninfo.h:41:23: note: previous definition is here
constexpr const char* LMMS_BUILDCONF_PLATFORM = "OS X";
                      ^
```

**Comment by barracuda156** [comment]
@tresf Well, let’s trow away unknown platform? Perhaps folks on NetBSD will be upset, but it is hard to debug something via CI.

**Comment by barracuda156** [comment]
Ah wait I know, it is not PLATFORM now.

**Comment by tresf** [comment]
> @tresf Well, let’s throw away “unknown platform”? Perhaps folks on NetBSD will be upset, but it is hard to debug something via CI.

I think it's still a copy/paste error, `stable-1.2` used `PLATFORM`, but `master` uses `LMMS_BUILDCONF_PLATFORM`.

**Comment by barracuda156** [comment]
@tresf Still does not want to work:
```
In file included from /__w/lmms/lmms/src/gui/modals/AboutDialog.cpp:29:0:
/__w/lmms/lmms/include/versioninfo.h:61:23: error: redefinition of 'constexpr const char* const LMMS_BUILDCONF_PLATFORM'
 constexpr const char* LMMS_BUILDCONF_PLATFORM = "unknown platform";
                       ^~~~~~~~~~~~~~~~~~~~~~~
/__w/lmms/lmms/include/versioninfo.h:53:23: note: 'constexpr const char* const LMMS_BUILDCONF_PLATFORM' previously defined here
 constexpr const char* LMMS_BUILDCONF_PLATFORM = "win32";
                       ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by tresf** [comment]
FYI - I think the proper way to do it now that we're using an actual variable is to create a large `if/else` like above.

**Comment by barracuda156** [comment]
> FYI - I think the proper way to do it now that we're using an actual variable is to create a large `if/else` like above.

Let’s try this, since in principle we _should_ have an unknown platform case.

**Comment by tresf** [comment]
image

**Comment by tresf** [comment]
Once the CI's pass, we'll merge.  Thanks!

**Comment by barracuda156** [comment]
Great, thanks.

**Pull request merged**
