### PR TITLE
Replacement metronome samples

### PR DESCRIPTION
**Pull request by Mark-Agent003**
@Replacement metronome sounds

image

### CODE REVIEW

**Comment by Umcaruje** [comment]
This keeps failing travis on mac ... :confused:

**Comment by tresf** [comment]
> This keeps failing travis on mac ... 😕

@Mark-Agent003's branch is missing `[fluid-synth.rb`](https://raw.githubusercontent.com/Mark-Agent003/lmms/master/cmake/apple/fluid-synth.rb).  Probably missing a fast-forward along the way.  Confusing, but should be OK.

**Comment by Mark-Agent003** [comment]
I'm confused. Is the Travis failing a problem, or are we good to go?

**Comment by tresf** [comment]
The problem is unrelated so good from a CI perspective.

**Comment by Mark-Agent003** [comment]
Alright. What do I need to do?

**Comment by tresf** [comment]
Nothing, just waiting in some to review and approve.  We're a bit backlogged.

**Comment by tresf** [comment]
@Mark-Agent003 Just noticed this also comes with a new tiled background although the PR doesn't set it by default.  @RebeccaDeField, I'll defer this decision to you.

image

**Comment by UnityParadox** [comment]
I took a listen to the new metronome. I personally think the measure click is good but the beat click could use a bit of work. Perhaps using a slightly shorter, lower-pitch version of the measure click instead?

**Comment by Mark-Agent003** [comment]
@UnityParadox , do you like this better? I did exactly what you said, but I also made the measure click sound less like a bubble popping 😀

**Comment by UnityParadox** [comment]
@Mark-Agent003 Indeed, much nicer! =)

**Comment by RebeccaDeField** [comment]
@Mark-Agent003 Thank you for your work on this :blush:

I tested your background proposal and I think we're going to keep the bg simple and clean. Can you remove the additional background from this pull request so that it only includes your updates to the metronome?

Please feel free to upload a version of the theme that includes your background on our [Sharing Platform.](https://lmms.io/lsp/)

**Comment by Mark-Agent003** [comment]
Done.

**Comment by tresf** [comment]
Can we get a second set of ears on this?  I think the old version sound more like a metronome "click".

Here's a zip containing both:
[new_vs_old.zip](https://github.com/LMMS/lmms/files/1005968/new_vs_old.zip)

**Comment by BaraMGB** [comment]
The new click sounds more modern. The attack is enough for working with. I like it.

**Comment by Umcaruje** [comment]
I like the new one better too :+1:

**Comment by tresf** [comment]
Great!  3 thumbs up.  Merging.

**Pull request merged**
