### PR TITLE
MINIMAL command line option

### LINKED ISSUE #2580: -DWANT_MINIMAL
Git bisect is a wonderful tool but it takes time. I suggest, just a thought, that we make a
new compile option MINIMAL which lets you build lmms without most of the pluggins.
We have little use of it today but I suspect that we'll have good use of it a year from now.
Many times when I bisect I test against the previous stable release so for this to work it
should be included now for 1.2

```
ADD_SUBDIRECTORY(kicker)
ADD_SUBDIRECTORY(triple_oscillator)

IF(NOT WANT_MINIMAL)
ADD_SUBDIRECTORY(Amplifier)
ADD_SUBDIRECTORY(Bitcrush)

...


ENDIF()
```

Test builds after make clean. This doesn't mean that an actual bisect will take half the time but it will cut it significantly. Two lines of code well spent I say.

```
cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=DEBUG

real	5m50.047s
user	9m55.876s
sys	0m51.896s


cmake .. -DCMAKE_INSTALL_PREFIX=../target -DCMAKE_BUILD_TYPE=DEBUG -DWANT_MINIMAL=ON

real	2m44.669s
user	4m43.520s
sys	0m24.904s
```

### PR DESCRIPTION
**Pull request by zonkmachine**
Closes #2580

### CODE REVIEW

**Comment by Umcaruje** [comment]
:+1: from me, if it cuts the build time, it will be useful.

**Comment by Fastigium** [comment]
:+1: from me as well; tested and works fine. Good idea! And kudos for the bisecting work you did on bugs recently, too :smiley:

**Comment by tresf** [comment]
How will this new `WANT_MINIMAL` be documented?

For example, when we use `WANT_VST=false`, it's echo'd via the configure screen... 

```
* VST-instrument hoster       : 
* VST-effect hoster           : 
```

... or when it is set to true:

```
* VST-instrument hoster       : OK
* VST-effect hoster           : OK
```

But this new switch is **after** this check, so we get something like this in the log... 

```
Optional plugins
----------------
* Carla Patchbay & Rack       : not found, please install the latest carla
* SoundFont2 player           : OK
* Stk Mallets                 : OK
* VST-instrument hoster       : OK
* VST-effect hoster           : OK
* CALF LADSPA plugins         : OK
* CAPS LADSPA plugins         : OK
* CMT LADSPA plugins          : OK
* TAP LADSPA plugins          : OK
* SWH LADSPA plugins          : OK
* GIG player                  : OK
```

Thoughts?

**Comment by Fastigium** [comment]
Hm, the compiled result is not very usable for anything but debugging. Many of the presets for Triple Oscillator even give errors when previewing due to missing effects. So perhaps it would suffice to add a comment with `IF(NOT WANT_MINIMAL)` to explain what it does to people viewing the CMake files, and add a small page to the developer wiki about bisecting that shows how it's used.

**Comment by tresf** [comment]
> So perhaps it would suffice to add a comment with IF(NOT WANT_MINIMAL) to explain what it does to people viewing the CMake files, and add a small page to the developer wiki about bisecting that shows how it's used.

Or we tackle this like so...

```cmake
IF(WANT_MINIMAL) 
   OPTION(WANT_FOO "OFF")
   OPTION(STATUS_FOO "Disabled, minimal requested")
   OPTION(WANT_BAR "${WANT_FOO}")
   OPTION(STATUS_BAR "${STATUS_FOO}")
   # ...
ENDIF
```

Or.... 
```diff
ADD_SUBDIRECTORY(cmake)
ADD_SUBDIRECTORY(src)
- ADD_SUBDIRECTORY(plugins)
+ IF(NOT WANT_MINIMAL) 
+    ADD_SUBDIRECTORY(plugins)
+ ELSE
+    # Required for building
+    ADD_SUBDIRECTORY(plugins/foo)
+    ADD_SUBDIRECTORY(plugins/bar)
+ ENDIF
ADD_SUBDIRECTORY(tests)
ADD_SUBDIRECTORY(data)
ADD_SUBDIRECTORY(doc)
```

... but then you'd miss [this stuff](https://github.com/LMMS/lmms/blob/master/plugins/CMakeLists.txt#L1:L6)... 

So placing this information in a dedicated bisect tutorial may be the cleanest way.... :confused: Perhaps as a compromise, we simply move the required plugins to the top of the stack and comment (you may have already suggested this...)

**Comment by Lukas-W** [comment]
If I'm getting the purpose of this feature right, you can also just use `make lmms` instead of `make` (which is an alias to `make all`). This builds the lmms binary only, without any plugins. Any builds can be built the same way, e.g. `make lmms zynaddsubfx`.

**Comment by zonkmachine** [comment]
> If I'm getting the purpose of this feature right, you can also just use make lmms instead of make (which is an alias to make all). This builds the lmms binary only, without any plugins. Any builds can be built the same way, e.g. make lmms zynaddsubfx.

I didn't know that, haven't dived much into 'make' at all, but you would still need a couple of plug-ins in order to test stuff. The ones I choosed were the ones from the default project.

**Comment by Lukas-W** [comment]
> but you would still need a couple of plug-ins

True. Maybe something like this would be slightly better then? (Not tested)

```cmake
add_custom_target(lmms-minimal
    DEPENDS lmms audiofileprocessor kicker tripleoscillator
)
```
This creates a target called `lmms-minimal` that includes all the plugins you chose. You could then use 
```sh
$ make lmms-minimal
```
to build the minimal environment it.

This would avoid reconfiguring CMake and rebuilding the Makefile, which should reduce compilation time when switching between a minimal and a full LMMS build.

**Comment by tresf** [comment]
> True. Maybe something like this would be slightly better then? (Not tested)

Tested, works great.

```cmake
#
# adds minimalist target
#
ADD_CUSTOM_TARGET(minimal DEPENDS lmms audiofileprocessor kicker tripleoscillator)
```

Usage:

```bash
cd lmms
mkdir build
cd build
cmake ..
make minimal
```

(Please pardon the dated code :smile_cat: )
screen shot 2016-02-23 at 1 26 32 am

**Comment by zonkmachine** [comment]
Cool! Thanks for all feedback, will try this.

**Comment by tresf** [comment]
@zonkmachine after this is implemented, we'll need to find a good place to document it as well. :+1:

**Comment by tresf** [comment]
Closing since we already have support for this.  Please feel free to open a new PR with the recommended changes (https://github.com/LMMS/lmms/pull/2581#issuecomment-187566013)

**Comment by Lukas-W** [comment]
@tresf
> we already have support for this

I can't find any. Could you clarify?

**Comment by tresf** [comment]
> Could you clarify?

Per https://github.com/LMMS/lmms/pull/2581#issuecomment-186760959, https://github.com/LMMS/lmms/pull/2581#issuecomment-187566013

```bash
make lmms audiofileprocessor kicker tripleoscillator
```

**Pull request closed without merging**
