### PR TITLE
Kicker: new UI / graphics, also some additions:

### PR DESCRIPTION
**Pull request by diizy**
- Envelope length is now temposyncable and has higher maximum
- Distortion is divided to start/end knobs for a simple distortion envelope
- Everything backwards compatible

### CODE REVIEW

**Comment by musikBear** [comment]
fyi: lmms uses old kicker graphic for sidebar icon, and icon on preset-button
kickergraphics

**Comment by grejppi** [comment]
Yes, because the logo was not changed. Why is this an issue now, and not a year ago?

**Comment by tresf** [comment]
> Why is this an issue now, and not a year ago?

:+1:

**Comment by musikBear** [comment]
> Why is this an issue now, and not a year ago?
actually i only saw it because i looked at @Rebbekka's new design, it stood out :p

**Pull request merged**
