### PR TITLE
Changes to be committed:

### PR DESCRIPTION
**Pull request by Jinxuan2001**
modified:   src/gui/FileBrowser.cpp
add naturalCompare function

### CODE REVIEW

**Comment by Rossmaxx** [comment]
Can you format the title and description to be more clear? Also, what is this new change used for?

**Comment by Rossmaxx** [comment]
@sakertooth you have any ideas on what might be the purpose of this new function?

**Comment by Jinxuan2001** [comment]
add naturalCompare function ：In the current snippet, the ordering of directories and files is based on alphabetical order. Especially when dealing with directories, the code is sorted by name (fileName < d->text(0)). To implement natural sorting, we need to implement a custom comparison function. The natural sorting algorithm is a more human intuitive way of sorting, for example, putting "file1", "file2",... ", "file10", rather than alphabetically placing "file10" before "file2". We can do this by implementing a custom comparison function.

**Comment by Rossmaxx** [comment]
Alrighty. Makes sense now. But why close the issue tho. Could have edited the title and description to make the PR clear

**Pull request closed without merging**
