### PR TITLE
Removed dead code using #if 0

### PR DESCRIPTION
**Pull request by Rossmaxx**
Title says it. From git blame, the code in question is from toby, 16 years old. At this point, no one knows the origin.

### CODE REVIEW

**Comment by Rossmaxx** [comment]
Ohh so this was a wip performance upgrade, which never went through. @sakertooth any chance you might need this in the future, once your refactor gets through?

**Comment by sakertooth** [comment]
> Ohh so this was a wip performance upgrade, which never went through. @sakertooth any chance you might need this in the future, once your refactor gets through?

No.

**Review by sakertooth — APPROVED** [review]
I don't have many rejections to this. This is code no one bats an eye until this PR was made to remove it, so it's fine with me.

**Comment by Rossmaxx** [comment]
I'll let someone else take a look at this before merge as there's complaints about way too quick merges (especially by me). This is a trivial thing but i don't wanna let it slide anymore like i used to do.

**Comment by michaelgregorius** [comment]
I have merged this now. Anyone who'd be missing the code should at least know which file it was in. And in that case the Git history of that file could be searched and the code activated again. It's not like it is gone for good.

**Pull request merged**
