### PR TITLE
Remove the 6 year old TODO file

### PR DESCRIPTION
**Pull request by Wallacoloo**
The TODO file in the repository root hasn't been touched in 6 years. We have an issue tracker, so I don't see the need of keeping a to-do file in the actual repository anymore.

Edit: I'll maintain the entries of the to-do list that haven't been implemented / posted to the tracker below. Leave a comment on which ones are safe to be removed:

**Unknown** if valid or not:
```
-- resample sample-track-tcos when exporting at different samplerate        
-- select all MIDI devices by default when you bring up the "connect to controller"     
-  window and wait for first event - then uncheck all other MIDI devices that no        
-  events were detected from        
-- load asdlol.mmpz. if you render it without playing it, or if you play it     
-  the first time, you hear unwanted artifacts. (solution: apply automation     
-  before playing)      
-- speed up painting of sampleTCO       
-- when you click and drag a mixer bar, it doesn't click and drag, it sets      
-  absolutely. this is annoying     
```

**Probably** still valid issues for which no tracker exists:
```
-- message to user when importing unsupported MIDI-file (track-count = 0) 
```

### CODE REVIEW

**Comment by tresf** [comment]
Agreed, but some of these are valid.  We should probably file bug reports for those not currently represented in our tracker.  This is a very timely process.  I would recommend going line-by-line and crossing them out.  People like @musikBear @Sti2nd @Umcaruje @mikobuntu @curlymorphic @badosu could help with this effort, since they're very familiar with the state of our current tracker.

-Tres

**Comment by musikBear** [comment]
You mean this one 
https://github.com/LMMS/lmms/blob/master/TODO
??
looks messy.. almost like a 'note to self' or 'assented' notes..

**Comment by curlymorphic** [comment]
I will start by deleting the items i know are done.
If every one does the same in a chain, we can see whats still left.

		
-- resample sample-track-tcos when exporting at different samplerate		
-- message to user when importing unsupported MIDI-file (track-count = 0)		
-- when you add vestige, have it automatically pop the find VST plugin dialog		
-- select all MIDI devices by default when you bring up the "connect to controller"		
-  window and wait for first event - then uncheck all other MIDI devices that no		
-  events were detected from		
-- load asdlol.mmpz. if you render it without playing it, or if you play it		
-  the first time, you hear unwanted artifacts. (solution: apply automation		
-  before playing)		
-- speed up painting of sampleTCO		
-- copy-pasted automation patterns have to be manually linked back to		
-  their knob for some reason		
-- improve TrackLabelButton: split 80%-20% (80%=name, 20%=button showing a popup		
-  menu with track operations, make the midi input a top-level menu item)		
-- when you click and drag a mixer bar, it doesn't click and drag, it sets		
-  absolutely. this is annoying		
-

**Comment by Wallacoloo** [comment]
@curlymorphic I edited your list into the PR description so that people can leave comments here just detailing the ones they know are safe to remove.

@musikBear yes, that's the one.

I can't make sense of very many of these. In regards to this entry:
```
-- when you click and drag a mixer bar, it doesn't click and drag, it sets      
-  absolutely. this is annoying
```
I tried dragging both the vertical mixer channel bars and the FX slots in the FX chains, and neither of them support dragging. Any idea what this one is referring to? Maybe a feature of the old mixer? Is it safe to delete this entry?

**Comment by Wallacoloo** [comment]
```
-- improve TrackLabelButton: split 80%-20% (80%=name, 20%=button showing a popup        
-  menu with track operations, make the midi input a top-level menu item) 
```

This seems to be referring to [this](https://github.com/LMMS/lmms/blob/fe797cb09fb897ade99bacdb014fc6fb97af6583/src/gui/widgets/TrackLabelButton.cpp#L58) piece of the code (replicated below):

```c++
if( ConfigManager::inst()->value( "ui",
					  "compacttrackbuttons" ).toInt() )
	{
		setFixedSize( 32, 29 );
	}
	else
	{
		setFixedSize( 160, 29 );
	}

	setIconSize( QSize( 24, 24 ) );
```

So the ratio of the icon to the text is currently 85%-15% (1-24/160 : 24/160). A ratio of 80%-20% could be achieved by `setFixedSize(120, 29)` and keeping the icon size at 24. This seems like a matter of personal preference, and I haven't seen any one else complain about the current icon to text split. Therefore, I am removing this entry - comment if you think it needs more discussion.

**Comment by Wallacoloo** [comment]
```
-- copy-pasted automation patterns have to be manually linked back to       
-  their knob for some reason
```

I just tested that and it appears that this issue has since been solved; removing this item from the list.

**Comment by Wallacoloo** [comment]
```
-- when you add vestige, have it automatically pop the find VST plugin dialog
```

This hasn't been implemented & wasn't on the issue tracker, so I created #1983 for it.

**Comment by Wallacoloo** [comment]
As far as `-- message to user when importing unsupported MIDI-file (track-count = 0)`:

This condition is detected in [mfmidi.cpp:31](https://github.com/LMMS/lmms/blob/fe797cb09fb897ade99bacdb014fc6fb97af6583/plugins/MidiImport/portsmf/mfmidi.cpp#L31). Following the call chain, the message isn't logged in that class, but is relayed to a pure-virtual method, Mf_error. The only class that implements that is Alg_midifile_reader in [allegrosmfrd.cpp:172](https://github.com/LMMS/lmms/blob/fe797cb09fb897ade99bacdb014fc6fb97af6583/plugins/MidiImport/portsmf/allegrosmfrd.cpp#L172), which just logs the error to the console.

Looking further, it looks like LMMS' MidiImport class doesn't bother using that Midi reader for some reason though (so you can probably discard the above information). The only call into the allegro library is, from what I can tell, in creating an `Alg_seq` in [MidiImport.cpp:283](https://github.com/LMMS/lmms/blob/fe797cb09fb897ade99bacdb014fc6fb97af6583/plugins/MidiImport/MidiImport.cpp#283). From here, it looks like the only time the number of tracks in the midi file is queried (`seq->tracks()`) is in setting up the progress display and in the for loop that imports each track. 

So from what I can tell, no checks are made to ensure that a Midi file has > 0 tracks. Therefore this issue is probably still valid. But I don't know enough about Midi to be able to create a 0-track midi file and test it.

**Comment by tresf** [comment]
This PR isn't needed since the TODO file was removed via #2210.   @Wallacoloo if you'd like, feel free to reopen this as a bug report (or several, depending on your approach).

**Pull request closed without merging**
