### PR TITLE
Redesign Spectrum Analyzer

### PR DESCRIPTION
**Pull request by RebeccaDeField**
Updated screenshots of plugin design @Umcaruje @BaraMGB 

**Before:**
spectrum_analyzer_1 0 0

**After:**
image

**In this pull request I have:**

- Updated the fonts, colors and aesthetic to match new theme
- Recreated grid, while remaining pixel perfect with exactly the same spacing as the previous grid

### CODE REVIEW

**Comment by Umcaruje** [comment]
d7d11fd8-6034-11e6-982b-36970bc5773f

I feel the title should be moved 2 pixels down to be centered perfectly. Other than that, looking mint :ok_hand:

**Comment by tresf** [comment]
Those dimmed LEDs are difficult to see now.   Is that due to the colors chosen for this plugin, or is that something new-theme related?

**Comment by RebeccaDeField** [comment]
@Umcaruje Great observation! I aligned the text to be the same distance from the top as the other plugin I designed, but I it might make more sense to center the title within the elements of each particular plugin.

@tresf I believe that the plugin is coded in a way that dims the background, while leaving the graph/visualizer the same as the original graphic. This left my graphic a darker than I expected when I first put it in place. I brightened the colors to compensate, but I can absolutely bump the brightness up a notch if it's looking too dark on your computer.

**Comment by RebeccaDeField** [comment]
@BaraMGB I did a quick search for other Spectrum Analyzers and it does seem that most put the db readout on the right (or both sides), but there _are_ some that put it on the left. As long as we wouldn't be breaking any standards, I don't see any problem with changing the layout that way.

> And the background has a specific gradient.

The background has the same gradient here as in the other plugins. :+1:

**Comment by RebeccaDeField** [comment]
Updated spectrum analyzer design based on feedback:
image

@BaraMGB I was going to move the db readout, but ended up removing the titles so I didn't see a reason to move it anymore. Please let me know if you would still like it on the right instead :)

**Comment by RebeccaDeField** [comment]
I just noticed that the background needs to be tweaked. Will be updating soon.

**Comment by BaraMGB** [comment]
@RebeccaDeField Of course the readout is fine on the left without the title. 👍

**Comment by tresf** [comment]
> This left my graphic a darker than I expected when I first put it in place. I brightened the colors to compensate, but I can absolutely bump the brightness up a notch if it's looking too dark on your computer.

The LEDs look too dark in general.  They disappear into the background.  I don't think this is a problem with the background but rather something with the new theme itself.

BEFORE vs. AFTER

image  image

**Comment by RebeccaDeField** [comment]
@tresf Just realized that when you said LEDs I was thinking of the graph because it lights up. Are you talking about the Linear spectrum and Linear Y axis LEDs?

If so, do you find that they are too dim throughout the whole theme or just on this plugin? I have solutions for both scenarios.

**Comment by tresf** [comment]
> do you find that they are too dim throughout the whole theme or just on this plugin? I have solutions for both scenarios.

Terrific question.

Well, upon reexamination, the whole theme albeit less noticeable of an issue when [nearby LEDs are lit](https://cloud.githubusercontent.com/assets/6345473/17954911/3a9c46a8-6a4c-11e6-8df9-3a38307ae8a5.png) or when the LED is a [two-state LED](https://cloud.githubusercontent.com/assets/6345473/17954924/51f61ed2-6a4c-11e6-9d13-19835dcc2119.png).  So my LED contrast comments are off-topic to this post and should be tracked in a separate issue.

**Comment by RebeccaDeField** [comment]
@tresf I agree. It sounds like this is something separate from this plugin design.

The darker leds were one of the first elements I designed so with all of the color changes I believe they no longer have enough contrast with the rest of the theme. Lightening (probably) or darkening them (maybe) should be the solution. Because this seems pretty straightforward to me, I think I will go ahead and make a PR for it and if that doesn't fix the issue, further discussion can continue there. :)

**Comment by RebeccaDeField** [comment]
LEDs aside, I have made all of the changes that have been requested to the Spectrum Analyzer, and since I have not received any further changes since two days ago when I updated it, I think it is ready to be merged.

**Comment by Umcaruje** [comment]
Merging.

**Pull request merged**
