### PR TITLE
Rename Beat/Bassline editor to Pattern editor

### PR DESCRIPTION
**Pull request by Umcaruje**
Partial fix for #120. 
This PR solves the problem on a superficial level, affecting only the gui. I will try to make a PR that will do the name change on the code level. 

Now, I added an part in the upgrade that replaces 'Beat/Bassline' with 'Pattern'. I also made this change to necessary built in projects.

Testing welcome, please let me know If I missed something.

### CODE REVIEW

**Comment by Mark-Agent003** [comment]
Looks good 👌

**Comment by Umcaruje** [comment]
I don't feel comfortable doing this change so superficially, this takes extensive planning and I want to rename the underlying code as well, but further discussion is needed to define all the names for the elements we have in software. Closing for now.

**Comment by tresf** [comment]
Why?  This is still valid and relevant.

**Comment by tresf** [comment]
Ah, nevermind it's a PR. :)

**Pull request closed without merging**
