### PR TITLE
Add initial Debian packaging for stable-1.2

### PR DESCRIPTION
**Pull request by jasp00**
This is the first step towards Debian integration, as stated in #4695.

### CODE REVIEW

**Comment by PhysSong** [comment]
Could you consider removing `clang.patch`? We don't add `-Werror` by default anymore. Also, I can't apply the old patch into current `stable-1.2`.
Also, `CONTRIBUTORS` are outdated in your patch.

**Comment by jasp00** [comment]
I did not explain that patches under `debian/patches` are not meant to be applied, since the package format is native.

> Could you consider removing `clang.patch`?

It is only a reminder to add a clang pass on Debian sid.

> We don't add `-Werror` by default anymore.

It is good practice to enable `-Werror` on sid. Specific errors can be disabled.

> Also, `CONTRIBUTORS` are outdated in your patch.

It is just another reminder.

**Comment by trebmuh** [comment]
Suggestion to remove the debian/menu file following [this Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=741573) which have deprecated the menu file.

**Comment by jasp00** [comment]
If there is no more feedback, I will merge this and continue the integration.

**Comment by PhysSong** [comment]
I forgot to mention that `debian/lmms.xpm` should be updated according to #4519.

**Pull request merged**
