### PR TITLE
Add Transifex automation file

### PR DESCRIPTION
**Pull request by liushuyu**
Add Transifex project automation file
I am busy with configuring bot... The bot (or I, if bot wouldn't work in very near future) will push back the translations in several minutes or hours.

---
This change is [Reviewable](https://reviewable.io/reviews/lmms/lmms/2706)

### CODE REVIEW

**Comment by tresf** [comment]
@liushuyu no objections here..  Are there things we should watch our for once merged?

**Comment by liushuyu** [comment]
Emm… The bot that Transifex provided has a limitation that regeneration of
source strings is needed with new strings appear. And according to official
documentation, the owner of the bot should have the write access to the
repo,  which bot will use to push back the translations. And after merging,
I think just release the LMMS (if there will be a release) would be fine😃

BTW, after the week of work, I have witnessed the huge progress that our
translators made which is amazing!

**Comment by tresf** [comment]
> And according to official documentation, the owner of the bot should have the write access to the
repo, which bot will use to push back the translations. 

Can you add `lmmservice` as the owner?  It's a service account all admins have access to.  I can give you the credentials for it too if needed.

> after the week of work, I have witnessed the huge progress

:+1: :+1:

**Comment by liushuyu** [comment]
>Can you add lmmservice as the owner? It's a service account all admins
have access to. I can give you the credentials for it too if needed.

Ah, that's even better. So I won't need to store my credentials on the bot
😃.

**Comment by tresf** [comment]
> Ah, that's even better. So I won't need to store my credentials on the bot 😃.

Email or Hangouts me `tres.finocchiaro`&nbsp;`@`gmail.

**Comment by tresf** [comment]
Done and done.  Once your end is complete, you can merge this and close out #2676

**Comment by liushuyu** [comment]
Well, first merge this, or I can't even test the bot

**Comment by tresf** [comment]
> Well, first merge this, or I can't even test the bot

Go for it!

**Pull request merged**
