### PR TITLE
Remove 'using namespace std;' from LMMS headers

### PR DESCRIPTION
**Pull request by irrenhaus3**
Removes "using namespace std" from global scope, which is a common source of symbol clashes. Adds std:: prefix to affected symbols in the header and some sources which included it transitively.

### CODE REVIEW

**Comment by Veratil** [comment]
LGTM, double check for any other locations!

**Comment by PhysSong** [comment]
Isn't it possible to add `using std::foo;`s in place of `using namespace std;` instead of adding `std::` everywhere we need?

**Comment by rdrpenguin04** [comment]
That can lead to just as many name conflicts, with the only difference being us opting into every one individually.

The people here have many things to say about this: [StackOverflow link](https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice). While this often doesn't address `using std::*`, making use of any `using` declaration at header scope is nearly universally a bad idea for the same reasons. At implementation scope, it's fine, but it's generally clearer to specifically name when something is coming from `std` and when we have our own implementation.

**Comment by irrenhaus3** [comment]
> That can lead to just as many name conflicts, with the only difference being us opting into every one individually.
> 
> The people here have many things to say about this: [StackOverflow link](https://stackoverflow.com/questions/1452721/why-is-using-namespace-std-considered-bad-practice). While this often doesn't address `using std::*`, making use of any `using` declaration at header scope is nearly universally a bad idea for the same reasons. At implementation scope, it's fine, but it's generally clearer to specifically name when something is coming from `std` and when we have our own implementation.

Agreed. `using [namespace]::[symbol] ` is OK inside a lexical scope of some function or class, but at global scope it's more trouble than it's worth. IMO just writing `std::foo` instead of `foo` isn't too big a hassle either, so my personal usage of `using std::foo` is pretty low anyways - but that's more of a matter of personal style.

As for other locations, `using namspace std;` appears at global scope in the following header files:

3rdparty/jack2:
- common/JackNetTool.h
- macosx/coreaudio/JackCoreAudioAdapter.h
- macosx/coreaudio/JackCoreAudioDriver.h   

plugins:
- zynaddsubfx/src/Effects/Alienwah.h
- zynaddsubfx/src/Tests/[several files]
- carlabase/carla/source/native-plugins/external/zynaddsubfx/UI/TipWin.h
- LadspaEffect/calf/veal/src/calf/orfanidis_eq.h

Most of these occurences might be contained to their respective projects - at least the Zyn Test header instances definitely are.

**Comment by JohannesLorenz** [comment]
> plugins:
> 
>     * zynaddsubfx/src/Effects/Alienwah.h
>     * zynaddsubfx/src/Tests/[several files]

We could fix the Alienwah in our fork (though note that this has been fixed on zyn's upstream). The Test files are only a source for auto-generating cpp files using "cxxtest", and they will only be ever included by their autogenerated cpp files. So I'm OK with leaving those as they are.

This PR LGTM, but feel free to fix the occurences in the submodules mentioned - at least in those which we own (e.g. LMMS/zynaddsubfx).

**Comment by PhysSong** [comment]
Note: The changes should be tested against GCC 6 to make sure it doesn't break builds. See #5831 for an example.

**Comment by JohannesLorenz** [comment]
@PhysSong How do we test GCC6? Is this part of our CI, or must we ask one of our devs who has GCC6? I think @Veratil posted with GCC6 on discord?

**Comment by irrenhaus3** [comment]
Update on veal: orfanides_eq.h does in fact not contain a `using namespace std` anymore, I was mistaken because my submodule was not up to date. Fun!
So with the Zyn patch, this removes `using namespace std` from global scope in all LMMS-owned header files except the self-contained Zyn tests.
Do not merge before the PR in the Zyn repo has been merged and the temp. URL for the submodule has been reverted.

**Comment by JohannesLorenz** [comment]
@irrenhaus3 I merged the zyn submodule to its master. If you revert the remote, I think we are ready to go.

**Review by JohannesLorenz — APPROVED** [review]

**Review by JohannesLorenz — APPROVED** [review]

**Pull request merged**
