### PR TITLE
Add a sidebar tab for VST plugins

### PR DESCRIPTION
**Pull request by Delta-Psi**
Not sure why this wasn't implemented already, it's really useful (at least for me) and not particularly hard to code.

### CODE REVIEW

**Comment by BaraMGB** [comment]
Actually we should think about a tab for all effect plug ins.

**Comment by tresf** [comment]
> Actually we should think about a tab for all effect plug ins.

Effect != Instrument

**Comment by grejppi** [comment]
VST instruments are special in LMMS for now anyway, so this addition would make sense 👍 

This doesn't look like a massive new feature, though would it make sense to merge it just before the next 1.2 preview release?

**Comment by tresf** [comment]
> VST instruments are special in LMMS for now anyway

"Special" is a good word to describe it... https://github.com/LMMS/lmms/issues/2003

And of course.... https://github.com/LMMS/lmms/issues/1807#issuecomment-86239225

And a similar problem with SF2's https://github.com/LMMS/lmms/issues/1807#issuecomment-86260519
 as we already have an instrument section.

But I agree that a sidebar section is probably a good start ONLY if we can [determine the difference from an instrument and an effect plugin](https://github.com/LMMS/lmms/issues/2003).

**Comment by zonkmachine** [comment]
> play sampletracks from any song position

You have merged your branch against BaraMGB's sampletrack branch and now pushed his commits together with yours. I'm in no way an expert on git but I think the way to update your commits is to rebase against, in our case, the branch named `master`.
If I've understood this correctly the first commit https://github.com/LMMS/lmms/pull/3048/commits/56c7a058a97b1855cf76783c03eb027fc79ee5d9 is the only part you need in here.

**Comment by difarem** [comment]
Yes, thank you. It should be fixed now.

**Comment by tresf** [comment]
> Mark-Agent003 approved these changes 2 hours ago

Quoting previous comment... 

> But I agree that a sidebar section is probably a good start ONLY if we can [determine the difference from an instrument and an effect plugin](https://github.com/LMMS/lmms/issues/2003).

Has anyone tested/verified this?

**Comment by tresf** [comment]
I'd still like to see what this PR looks like when the VST directory is loaded with FX plugins.

**Comment by zonkmachine** [comment]
vstplugins

**Comment by tresf** [comment]
@zonkmachine I assume some of those are FX plugins mixed (such as NyquistEq5.dll)?  Can we [hack them out](https://github.com/LMMS/lmms/issues/2003)?  It doesn't have to be pretty, it just needs to work.

**Comment by zonkmachine** [comment]
Why not have two directories under VST plugins. VST and VSTi? Then @difarem can scan only the VSTi for the sidebar and it's up to the user to aim straight for 3 seconds...

`
The VST specification does not provide any means to distinguish between instruments and effects.
`

Seriously!?...

In any case, this is good use of ten lines of code.

**Comment by difarem** [comment]
There is currently no differentiation between VST effects and instruments on any other place (the Vestige file selection dialog and the FX effect list, IIRC), so I can't see why this should be an exception. For now, of course.

**Comment by tresf** [comment]
> There is currently no differentiation between VST effects and instruments on any other place (the Vestige file selection dialog and the FX effect list, IIRC), so I can't see why this should be an exception. For now, of course.

There appears to be a flag designating whether or not the plugin is a synth or not.  I don't believe we currently expose this and we must reverse engineer it from the API as to not violate the Steinberg license but it's there.

Another (mostly accurate) option is to assume a plugin with > 0 inputs is an effect.  For example, mda Talkbox has 2 inputs and 2 outputs whereas DPC3 Drumpad has 0 inputs and 2 outputs.  This would cover about 99% of use-cases until the official synth API is sorted.

**Comment by jasp00** [comment]
>There appears to be a flag designating whether or not the plugin is a synth or not. I don't believe we currently expose this and we must reverse engineer it from the API as to not violate the Steinberg license but it's there.

Are you talking about `effFlagsIsSynth`? It is in the header, it is just not used.

**Comment by tresf** [comment]
> Are you talking about effFlagsIsSynth? It is in the header, it is just not used.

No, I would guess it's `isSynth`.  A VST inspector program can show this information.  It may be missing from our implementation.

**Comment by jasp00** [comment]
`isSynth`? What is this VST inspector? Could you tell a plug-in that is a synth and another that is not?

**Comment by tresf** [comment]
> isSynth? What is this VST inspector? Could you tell a plug-in that is a synth and another that is not?

It's called VSTSpy for Windows and yes, it can distinguish between Synths versus Effects plugins.  I tested it on a handful and it works fine.  I would assume it's compiled against the Steinberg header so proceed with cleanroom caution.

**Comment by jasp00** [comment]
It is very likely that `isSynth` is our `effFlagsIsSynth`, because they report the same.

I see that VSTSpy generates `VSTSpy.ini`. We could have a CSV file with all known plug-ins. Instead of the file name, we could use the SHA-256 hash. This way we know whether an plug-in is a synth without running plug-in code. Entries would look like:

```
034153170ce4242447d1371b466945984a5d4887072791fa12f3a259b3ce21fc,T-Force Alpha Plus,T-Force Alpha Plus,Michael Berendes,1,TAPL,Synth,335,128,1,0,2,0,0,false,2300,true,false,false,false,false,true,true,true,false,false,maybe,no,no,maybe,yes,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe,maybe
```

**Comment by tresf** [comment]
> It is very likely that isSynth is our effFlagsIsSynth, because they report the same.

Does this mean we can already use it?

> We could have a CSV file with all known plug-ins. 

Perhaps if we crowd-sourced it, but there's too many (hundreds or thousands) to make this reliable unless we phone home on each new plugin load.

I think I understand your point but isn't there a quick way to call the function as a stub and just get the true/false?

**Comment by jasp00** [comment]
>We could have a CSV file with all known plug-ins. [...] This way we know whether an plug-in is a synth without running plug-in code.

Bad idea. I thought LADSPA did not have this problem, but LADSPA also runs plug-in code.

>isn't there a quick way to call the function as a stub and just get the true/false?

Yes, there is.

>Does this mean we can already use it?

Just use `m_plugin->flags & effFlagsIsSynth`.

**Comment by zonkmachine** [comment]
I see no reason to hold back this PR. I suggest we merge this and continue this discussion in a new issue.

**Comment by tresf** [comment]
> I see no reason to hold back this PR. I suggest we merge this and continue this discussion in a new issue.

Because it will put effects there, that's why.

**Comment by tresf** [comment]
This tab should be hidden if VST support has been disabled for a build configuration.  Furthermore, if I'm reading this correctly, it's for making the DLLs easier to find?  Wouldn't it be easier to just add common VST locations to "My Home" since we're already listing DLLs there by default?

screen shot 2017-11-15 at 2 25 17 am


If enough people wants this, we can add it in, it just seems like we could deliver the UX better.  I currently save all of my DLLs inside a dedicated folder and that works just fine when I need a VST. This doesn't seem like it offers much over the existing file navigation.

**Comment by jibin1573** [comment]
Are we talking about showing the user specified vst folder in the sidebar?
If that's the case, users mostly segregate their VSTs into VSTi and VSTs (in that folder). Like in my VST folder, I have made separate folders for piano, Synth, organs etc. So, the sidebar has to just show up this folder, right?

**Comment by RoxasKH** [comment]
As a lmms user i think this will be really needed (i was just about to ask it), also thinking to beginner that to load a vst they need to open up vestige and then load it, it's really unintuitive, this would help a lot, also if we are not able to distinguish between vsti and fx, even if perfection would be seeing only dll without folders and the .dll extension, and only instruments.

**Comment by tresf** [comment]
> As a lmms user i think this will be really needed (i was just about to ask it), also thinking to beginner that to load a vst they need to open up vestige and then load it, it's really unintuitive, this would help a lot, also if we are not able to distinguish between vsti and fx, even if perfection would be seeing only dll without folders and the .dll extension, and only instruments.

No, you can just drag the DLL from the sidebar.

**Comment by JohannesLorenz** [comment]
I'm not familiar with the whole discussion, but would like to add that @CYBERDEViLNL has already [added a new tree layout for our plugins](https://github.com/LMMS/lmms/issues/4759) which may be perfectly suited for VSTs. The code is on master. As you can see in the image, it has tree widgets for LMMS and Lv2, and adding one for VST is less than a "good first issue".

If Cyberdevil's solution is redundant to this PR maybe we might consider closing this PR now. In that case I'm really sorry for the coding/reviewing efforts of this PR, but duplicating the plugin browsers will only cause confusion.

Tree layout and search bar in action

**Comment by tresf** [comment]
> If Cyberdevil's solution is redundant to this PR maybe we might consider closing this PR now. In that case I'm really sorry for the coding/reviewing efforts of this PR, but duplicating the plugin browsers will only cause confusion.

👍

**Pull request closed without merging**
