### PR TITLE
LADSPA Multiband EQ (mbeq_1197) bugfix #1885

### PR DESCRIPTION
**Pull request by geedubess**
Corrected Hann (raised cosine) window function.

Corrected output-windowing logic and recalculated correction factor
for window type. Tested against white noise & triple_osc output.

### CODE REVIEW

**Comment by curlymorphic** [comment]
Thanks @geedubess, Have just tested this, and it sounds much better than my fix:).

**Comment by geedubess** [comment]
Win! I actually made/tested the patch against stable-1.1 because I was having build problems against master, but it looked safe. ;) Lots of newness for me - had to learn how to use github, the ladspa sdk (their makefile is broken!), wav file processing in python, not to mention trying to remember/relearn DSP... Good times - and now I'm *so* glad to hear it works well for you!

(As a side note, I'm now pretty well set up to analyze/fix LADSPA plugins if there are any other troublemakers hanging around).

**Comment by Sti2nd** [comment]
Not sure if it is a real bug, or just because of the math happening then, but Glame highpass filter (and possibly lowpass) will glitch and sometimes crash LMMS if you automate the frequency knob to 0. Also described here http://lmmsmusiccreation.blogspot.no/2013_11_01_archive.html

Didn't manage to reproduce right now, but I am sure some people can chime in and give projects that always crashes because of this @Umcaruje

**Comment by tresf** [comment]
@Sti2nd feel free to create and cross link a bug report so we can track it properly.

**Comment by tresf** [comment]
This looks good and @curlymorphic claims it fixes #1885, merging. :+1:

**Comment by tresf** [comment]
@geedubess, this need to make it to Steve Harris's upstream repo at [`swh/ladspa`](https://github.com/swh/ladspa), specifically the slighly obscurely named XML build file here: [`mbeq_1197.xml#L80`](https://github.com/swh/ladspa/blob/master/).  Would you please followup with a PR to Steve?

**Pull request merged**
