### PR TITLE
Dual Filter Plugin Redesign

### PR DESCRIPTION
**Pull request by RebeccaDeField**
In this pull request, I have recreated the Dual Filter plugin redesign proposed by @simonvanderveldt in #3093 as a part of our efforts [here.](2831)

shot-2017-04-26_17-45-24

@Umcaruje @BaraMGB

### CODE REVIEW

**Comment by BaraMGB** [comment]
That looks good to me. 👍

**Comment by RebeccaDeField** [comment]
@Umcaruje I plan on merging today if you don't have any changes :blush:

**Comment by Umcaruje** [comment]
>@Umcaruje I plan on merging today if you don't have any changes :blush:
Sorry I was busy so I didn't have time to comment.

The box size is off by 2 pixels, and the third knob's position is off by a pixel. I'll post a fixed mockup asap.

**Comment by Umcaruje** [comment]
Actually, sorry, the knob spacing is not the same on the 2 boxes, it's either 1 or 2 pixels off. It should all be on the same value and the padding of the box should be the same on both sides.

**Comment by Umcaruje** [comment]
b1d130fa-17f6-11e7-811d-d0f5cb37d9e2
Here, I made the boxes thinner by 1px, aligned the knobs in them. I also changed the boxes' position so the spacing between the edges and the mix knob is the same.

**Comment by Umcaruje** [comment]
b1d130fa-17f6-11e7-811d-d0f5cb37d9e2
 
It looks even better to me if you deliberately move the knobs 1px off horizontal center, cause of the LED

**Comment by Umcaruje** [comment]
Also do we want a line connecting the boxes like in the stereo matrix plugin? So it's clear the mix is between the two filters?

**Comment by RebeccaDeField** [comment]
@Umcaruje Wonderful feedback, thanks! A mockup works just fine for me. I'll play with the spacing and try your idea to connect the boxes.

**Comment by Umcaruje** [comment]
I'm merging this in 12 hours if there are no objections.

**Pull request merged**
