### PR TITLE
Borg Jr - FM synth based on stk::FM

### PR DESCRIPTION
**Pull request by zonkmachine**
borgjr

When I've been poking the code because of issues in Mallet #2455, I came up with this little FM synth. The mallet synths are based on three different sound engines and the one that is least buggy ( In our application n.b. ) is Tubular Bells and as it turns out it has siblings. https://ccrma.stanford.edu/software/stk/classstk_1_1FM.html

I tried them out and liked what I heard.

---

Some issues.
- Crash when using together with Mallets.
- ~~Like Mallets, changes to the settings doesn't update a note that is playing.~~ **_fixed_**
- ~~The ADSR doesn't seem to work on all of the engines. I think this is depending on the stk implication and not on Mallets/Borg Jr. ( _Confirmed. FMVoices :: noteOn writes over the same registers as the ADSR control change so it needs to be set after. Tried it but it doesn't sound very interesting. Could be something more missing there..._ )~~ **_fixed with the updated notes fix_**
- ~~FMVoices - Modulation 2 only goes to 127.9 to counter for a bug in stk.~~ **_fixed_**
- Spread isn't maybe the best on board effect for this one. Basically it's a short delay that only affects the left channel which makes it a bit unnatural sounding when you want to pan the sound to the right as the time shift in itself pans the sound to the left. I'm thinking either adding a delay to the right channel and then you can 'pan' the sound by delaying the signal or adding something else entirely in there like a chorus or phaser.
- I'm not an artist but I'm happy with the icon.

### CODE REVIEW

**Comment by tresf** [comment]
I've always wondered if we'd get more out of `stk`.  Nice.

Slightly off topic... We have a lot (a lot!) of instruments, so we're going to need to start consolidating these down at some point... i.e. all patch instruments into a single plugin visually, etc.

Keep this in mind long term for `stk` bases instruments as well, as we may eventually be able to rename mallets without adding more instruments to the listing.

**Comment by zonkmachine** [comment]
> Slightly off topic... We have a lot (a lot!) of instruments, so we're going to need to start consolidating these down at some point... i.e. all patch instruments into a single plugin visually, etc.

I think we could have the option to hide instruments either by us by default when they get a bit dated or by the user if they don't use it. `Right click - hide`

**Comment by zonkmachine** [comment]
I crachez here!
https://github.com/zonkmachine/lmms/blob/borgJr/plugins/stk/borgJr/borgjr.cpp#L356

I can run a heap of Mallets or Borg Jr but not together. As soon as I mix them I get a crash within short around the code segment linked above.

```
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f8f28896cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007f8f28896cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f8f2889a0d8 in __GI_abort () at abort.c:89
#2  0x00007f8f288d3394 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7f8f289e1b28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007f8f288df66e in malloc_printerr (ptr=<optimized out>, str=0x7f8f289e1cf0 "double free or corruption (fasttop)", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007f8f28ce3529 in std::string::assign(std::string const&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f8f113719a2 in stk::Stk::setRawwavePath(std::string) () from /usr/lib/x86_64-linux-gnu/libstk.so.0
#7  0x00007f8f115a806b in borgjrSynth::borgjrSynth (this=0x7f8ee4042a40, _pitch=130,81277465820312, _velocity=1, _preset=0, _control1=0, _control2=0, _control4=0, _control11=0, 
    _control128=0,10000000149011612, _delay=0 '\000', _sample_rate=44100) at /home/zonkmachine/builds/lmms/lmms/plugins/stk/borgJr/borgjr.cpp:356
#8  0x00007f8f115a6c15 in borgjrInstrument::playNote (this=0x7f8f1f5f5720, _n=0x7f8f1f4cee98, _working_buffer=0x7f8f1f5c80a0)
    at /home/zonkmachine/builds/lmms/lmms/plugins/stk/borgJr/borgjr.cpp:188
#9  0x000000000060519e in InstrumentTrack::playNote (this=0x7f8f1f5effa0, n=0x7f8f1f4cee98, workingBuffer=0x7f8f1f5c80a0) at /home/zonkmachine/builds/lmms/lmms/src/tracks/InstrumentTrack.cpp:469
#10 0x00000000005270ae in NotePlayHandle::play (this=0x7f8f1f4cee98, _working_buffer=0x7f8f1f5c80a0) at /home/zonkmachine/builds/lmms/lmms/src/core/NotePlayHandle.cpp:249
#11 0x000000000052ebd6 in PlayHandle::doProcessing (this=0x7f8f1f4cee98) at /home/zonkmachine/builds/lmms/lmms/src/core/PlayHandle.cpp:49
#12 0x000000000050ca25 in ThreadableJob::process (this=0x7f8f1f4cee98) at /home/zonkmachine/builds/lmms/lmms/include/ThreadableJob.h:74
#13 0x0000000000523473 in MixerWorkerThread::JobQueue::run (this=0x9330a0 <MixerWorkerThread::globalJobQueue>) at /home/zonkmachine/builds/lmms/lmms/src/core/MixerWorkerThread.cpp:75
#14 0x00000000005236cd in MixerWorkerThread::startAndWaitForJobs () at /home/zonkmachine/builds/lmms/lmms/src/core/MixerWorkerThread.cpp:148
#15 0x000000000051e4f5 in Mixer::renderNextBuffer (this=0x13629a0) at /home/zonkmachine/builds/lmms/lmms/src/core/Mixer.cpp:406
#16 0x000000000051fe2d in Mixer::fifoWriter::run (this=0x149aa70) at /home/zonkmachine/builds/lmms/lmms/src/core/Mixer.cpp:986
#17 0x00007f8f2afcb32f in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#18 0x00007f8f2c340182 in start_thread (arg=0x7f8ef23d5700) at pthread_create.c:312
#19 0x00007f8f2895a47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by zonkmachine** [comment]
Fixed the crash when running mallets and borgJr together. We're calling stk::setRawwavePath at every note on, but this is done internally in the stk-demo instruments. I don't update mallets this close to 1.2 release as this needs to be tested properly.

**Comment by zonkmachine** [comment]
Fixed updating controls while note is playing so now basically just one issue remains. The odd delay knob, spread, which is one of the last remnants of Mallets. It should really be replaced with some other effect or function. I've thought about either a randomness control like the one I tried out [here](https://github.com/LMMS/lmms/pull/2671). It's a bit more complex to implement that here though, now that the sound is updated continuously, as the randomness will have to be passed to two places. Maybe the best thing to do is to just take the spread knob/function out and the Borg is basically ready to go and other things can be added later and there will be no problems with backward compatibility.

**Comment by zonkmachine** [comment]
> I've always wondered if we'd get more out of stk. Nice.

:open_mouth:[stk/voices](
https://github.com/LMMS/lmms/tree/5d5ad19021fab8cf82542baebf2daf71ae23d4d2/plugins/stk/voices)

**Comment by zonkmachine** [comment]
> - Crash when using together with Mallets.

We need some sort of common mutex in order to run other Stk based plugins from within lmms.
As the [code says](https://github.com/LMMS/lmms/blob/master/plugins/stk/mallets/mallets.cpp#L297:L300), Stk isn't thread safe:

```
		// critical section as STK is not thread-safe
		static QMutex m;
		m.lock();
```

Create an StkInstrument subclass of Instrument with a _static QMutex_ ?

**Comment by zonkmachine** [comment]
Closing this for now.


> Create an StkInstrument subclass of Instrument with a static QMutex ?

Stk has a [Mutex class](https://ccrma.stanford.edu/software/stk/classstk_1_1Mutex.html) ... Example of use in [Stk demo.cpp](https://github.com/thestk/stk/blob/488301223ab6766a7a88d8a30bb2d63793b04865/projects/demo/demo.cpp).

**Pull request closed without merging**
