### PR TITLE
Enabled VSTs on Qt 6

### PR DESCRIPTION
**Pull request by Rossmaxx**
Enabled VST on Qt 6 ~~but for some reason, I couldn't use VSTs on linux~~(Unrelated). Also disabled X11 embedding for now.

note: this PR adds a dependency on `libxcb-cursor0` package if you want to use VSTs.

### CODE REVIEW

**Comment by Rossmaxx** [comment]
Will undraft it once i get vsts working.

**Comment by Rossmaxx** [comment]
Nvm the building of vsts issue might be due to the wine 9 issue. Will look into it seperately.

**Comment by Rossmaxx** [comment]
> Nvm the building of vsts issue might be due to the wine 9 issue. Will look into it seperately.

Fixed in #7260

**Comment by tresf** [comment]
I've squashed this PR into a commit here to make it easier to cherry-pick atop the Qt6 branch. https://github.com/tresf/lmms/commit/51c0a45e3a62ca89cc1eecaafac9ebd139498442.

@Rossmaxx if you wish, feel free to cherry-pick this.  Just a disclaimer, I don't think I got the attribution right, I think it added some people from the rebase that don't belong, but you can rewrite that portion with an amend if interested.

**Comment by Rossmaxx** [comment]
I forget stuff.

**Comment by tresf** [comment]
> I forget stuff.

This PR says it touches 21 files, but mine says 9, so make sure to double-check that the other 12 are as a result of the rebase and not something that got squashed out.

**Comment by Rossmaxx** [comment]
Nvm it would be better to close this one and start from scratch. I do have the diff here so it's just a matter of copy paste

**Comment by tresf** [comment]
> Nvm it would be better to close this one and start from scratch. I do have the diff here so it's just a matter of copy paste

Even if you start from scratch, you can still push the diff to this branch.

**Comment by Rossmaxx** [comment]
closed in favour of #7273

**Pull request closed without merging**
