### PR TITLE
Proposed fix for 1695 Cannot save templates

### PR DESCRIPTION
**Pull request by curlymorphic**
Proposed fix for #1695 Cannot save templates

### CODE REVIEW

**Comment by badosu** [comment]
Just tested and it works, thanks @curlymorphic!

**Comment by tresf** [comment]
@badosu did you test to make sure manually typed names don't put two extensions?

@curlymorphic off-topic to this PR, but I just noticed we allow translation files to override the filters which I think it a bad approach.  We should probably change this as a bad translation file could break file saving! :bomb:

**Comment by tresf** [comment]
Confirmed.  Double file extension when typed.

image

We should probably check for `QString::endsWith(".mpt")` prior to appending.  Once that's done, we'll be good to merge I think. :+1:

**Comment by curlymorphic** [comment]
Have added the check for ````QString::endsWith(".mpt")```` before appending the extension

**Comment by tresf** [comment]
Thanks (again!)

**Comment by curlymorphic** [comment]
:)

**Pull request merged**
