### PR TITLE
Triplets in Automation Editor

### PR DESCRIPTION
**Pull request by zonkmachine**
:tractor:

### CODE REVIEW

**Comment by Umcaruje** [comment]
Cool, though I think we should also allow the maximum quantisation amount of `1/192`, to be absolutely consistent with the piano roll. Also the drawing of triplets is fixed with #3062

**Comment by zonkmachine** [comment]
> I think we should also allow the maximum quantisation amount of 1/192

Tried it, pushed it. I think maybe they are a bit too hard to erase without a proper select tool.

> Also the drawing of triplets is fixed with #3062

:+1:

**Comment by zonkmachine** [comment]
> I think maybe they are a bit too hard to erase without a proper select tool.

No, it's about the same.

**Comment by zonkmachine** [comment]
Needs testing and review. I can merge this into https://github.com/LMMS/lmms/pull/3358 if that simplifies things.

**Comment by zonkmachine** [comment]
> I can merge this into #3352 if that simplifies things.

Closing this, now in https://github.com/LMMS/lmms/pull/3352

**Pull request closed without merging**
