### PR TITLE
Haiku update

### PR DESCRIPTION
**Pull request by korli**
The first commit from waddlesplash allows to run as root.
The two others commits fix the build on Haiku, though the one with unistd.h isn't specific to Haiku.

### CODE REVIEW

**Comment by tresf** [comment]
Why would you want to run as root?

Also, we have an override flag that can be used, does it not work?

**Comment by korli** [comment]
Running as root is the default on Haiku. I can remove that commit if you prefer.

**Comment by tresf** [comment]
If that is the norm, OK, then people can run it by default, it is just strange to read as a Linux/Unix user.

**Comment by korli** [comment]
@waddlesplash your opinion on the "Allow running as root on Haiku." commit?

**Comment by waddlesplash** [comment]
@tresf Haiku has POSIX multiuser, but the GUI all runs as root for BeOS compatibility. That won't change till after R1, most likely.

So keeping that change in there makes sense to me.

**Comment by tresf** [comment]
> So keeping that change in there makes sense to me.

👍

**Comment by tresf** [comment]
@korli for consistency can we switch the statement to `defined(LMMS_BUILD_HAIKU)`

https://github.com/LMMS/lmms/blob/master/include/lmms_math.h#L37

**Comment by korli** [comment]
It's now updated.

**Comment by tresf** [comment]
> It's now updated.

Thanks.  Will merge once Travis succeeds.

**Pull request merged**
