### PR TITLE
Sort effects in dialog

### LINKED ISSUE #2834: Effects plugin list is in reverse order alphabetically ( for the internal plugins )
**Running latest Master branch**
reversedorder

* The internal effects should be in alphabetical order as they used to be.

 * LADSPA Effects are listed correctly.
 * Presently not using windows VST ( via W.I.N.E ), so no way of checking them.

### PR DESCRIPTION
**Pull request by jasp00**
This fixes #2834.

### CODE REVIEW

**Comment by jasp00** [comment]
Entries are sorted by display name. Example:

    Amplifier
    LADSPA: 3 Band EQ
    Multitap Echo

**Comment by tresf** [comment]
Can we abolish LADSPA and VST prefixes while we're at it?  What worth does that have?

**Comment by DeRobyJ** [comment]
I think they are useful. It's just an opinion.
Having them lets you see what lmms sees in the vst folder, for example.

**Comment by mikobuntu** [comment]
I think the best way to approach this would be to have lists e.g Internal , LADSPA , VST . 
Why not even have these collapsible like in the browser dialogue? 
On 11 Jun 2016 09:46, Roberto Giaconia <notifications@github.com> wrote:I think they are useful. It's just an opinion.
Having them lets you see what lmms sees in the vst folder, for example.

**Comment by tresf** [comment]
If we like em, make I a sortable table.  Alphabetically, they cause a problem.

**Comment by grejppi** [comment]
> Can we abolish LADSPA and VST prefixes while we're at it? What worth does that have?

FWIW #2616 will make them redundant with only an `External` prefix, which would be even less useful.

**Comment by jasp00** [comment]
Effects are now sorted with a sortable table.

**Comment by tresf** [comment]
@jasp00 at a glance, this seems to work well.

Pardon the screenshot, the font contrast will be filed as a separate issue.

screen shot 2016-06-14 at 9 59 53 pm

**Pull request merged**
