### PR TITLE
Add Button 'Hover' effect

### LINKED ISSUE #4464: Button "hover" effect
Can we have glowing buttons, like in FL studio. Like when we press a button, it should light up with a different colour. 

Thank you!

### PR DESCRIPTION
**Pull request by luzpaz**
Closes #4464

### CODE REVIEW

**Comment by luzpaz** [comment]
This PR is simply here to get the ball rolling on adding #4464  
Please feel free to push any changes to the PR to your hearts content once consensus on colors has been reached.

**Comment by DomClark** [comment]
The CodeFactor failure is unrelated to your changes and can be ignored.

Can you provide a screenshot or even a video for both themes? It's a lot easier to discuss colours and styling if everyone can actually see what the changes look like. My eyes don't evaluate CSS.

**Comment by irrenhaus3** [comment]
I recorded this PR in action:

https://github.com/LMMS/lmms/assets/6547205/9bb7723f-8b55-4e3f-9592-c053413f9776


https://github.com/LMMS/lmms/assets/6547205/d466494e-c03e-4ab5-9e7f-39c3d1609d8a

**Comment by qnebra** [comment]
It looks fine, judging from irrenhaus videos

**Review by zonkmachine — COMMENTED** [review]
_Edit: I do see the changes now, yes, it subtle._
~~I see no change whatsoever in the default theme.~~ In the classic theme, try the buttons in the side panel ('**Instrument Plugins**' etc.). They are also affected. If you want to explore what objects are affected, then set the color to something extreme, like #ff0000 (red).

**Comment by luzpaz** [comment]
Inviting anyone to take over this PR and tweek it as needed.

**Comment by zonkmachine** [comment]
> Inviting anyone to take over this PR and tweek it as needed.

Thanks! I'm closing this in favor of https://github.com/LMMS/lmms/pull/7202

**Comment by Rossmaxx** [comment]
I haven't dropped the hover effect entirely. I just removed it from the scrollbar

**Pull request closed without merging**
