### PR TITLE
Fix hang on exit with SDL2 audio backend

### LINKED ISSUE #4668: LMMS process keeps running (master)
On master branch LMMS process keeps running after exit.
I just open and close LMMS without loading any project.
This doesn't happen in stable-1.2 branch.
I'm using Manjaro Linux.
gdb doesn't show anything useful.

### PR DESCRIPTION
**Pull request by firewall1110**
Now dangerous in capture callback locking and gui signaling functions are disabled if not recording audio.
Also capture callback is not enabled on startup, but startCapture(); stopCapture(); functions provided.
Also some information provided if capture callback is not used properly:
- capture callback called when devise is stopped (now only in rendering process);
- startCapture(); stopCapture(); are called when capture is not implemented or not implemented properly .

Fixes #4668.

### CODE REVIEW

**Comment by firewall1110** [comment]
It seems, that always  right is capture choice, **_except_** GUI lines in **_AudioSdl.cpp line ~350_**, where right is master choice (capture hold some lines removed by refactoring ). But I am not sure ...  

P.S. I will try to rebase locally on my computer, resolve as I mention before, and than ... do the same here ?

**Comment by firewall1110** [comment]
This #6070  and #5990 
_May be have hidden conflict:_
now audio call back is always active, but after #6070  must be activated before recording (and turned off after)
P.S. It seems, that  #5990 will be merged to master before this, so  conflict should be resolved here

**Comment by firewall1110** [comment]
**This PR should be deleted** (or continued with different goal):
can not fix **bug already fixed** (by LMMS initialization process correct order):
SDL2 audio backend never hung on current master.

**Comment by firewall1110** [comment]
About different goal:
sdl_settings
but should be like this:
soundio
but with:
- Input:
- Output:

**Comment by michaelgregorius** [comment]
> About different goal: sdl_settings but should be like this: soundio but with:
> 
>     * Input:
> 
>     * Output:

@firewall1110, this is how it should ideally look for all audio devices indeed. This has already been implemented for the SDL back end via the issue #5990. Unfortunately, it is mixed with something that might not be merged for a long time. Perhaps it will make sense to cherry-pick the relevant commits and to open an individual pull request.

See also these comments for more information: https://github.com/LMMS/lmms/pull/5990#issuecomment-2143526733, https://github.com/LMMS/lmms/pull/5990#issuecomment-2143552495

**Comment by michaelgregorius** [comment]
> @michaelgregorius Quote: "_Perhaps it will make sense to cherry-pick the relevant commits and to open an individual pull request._" How I understand - it is Yours commit: You should do this.

Yes, that's how I meant it.

> P.S. (1) 3 years ago I had idea how to implement audio monitoring, input changing and simple recording, but than give priority to #5990 author. I am "shocked" - why #5990 is not in master yet ... I made video to give hint to author merge my PR to his testing copy - it is difficult to develop recording without working driver with input support ... (2) My opinion is that such "brand new" feature is too big for one PR: #5990 should be "splinted" ...

Perhaps it would indeed be better to work incrementally in smaller steps towards that goal.

**Comment by michaelgregorius** [comment]
> [...] Perhaps it will make sense to cherry-pick the relevant commits and to open an individual pull request.

Done via pull request https://github.com/LMMS/lmms/pull/7421.

**Comment by firewall1110** [comment]
About another goal: **_Audio recording in alternative way_**.
Quote:"_via the issue #5990. Unfortunately, it is mixed with something that might not be merged for a long time._"[@michaelgregorius]
Strategy:
(1) **_Simple audio input monitoring and recording_** with processing format somewhere, there file can be easily found and included in sound track part (clip).  This is custom widget placed in main application window (near oscilloscope). Recording may be started/stopped by mouse click, or may be pinned to song play start/stop. (**_This PR another goal_**.)
(2) Implement some kind **_session audio pool_** context to easy **_place samples_** to sample track with **_context menu_** (now lmms don't have any context menu on empty track - only on part; sometimes  we have Paste). New recordings automatically be placed in this context menu. (_These feature is completely independent and may be developed right now, if not already done, but not merged)_
(3) Improve **_managing_** recordings and **_project audio files_**: folder and name and format for recording files, easy file renaming(, format changing, normalization,....) and moving, algorithm to find missing audio. In this stage may be implemented audio embedding in project file (easy can be done if using compressing format - compress project xml file and audio files together in one archive). (_Also can be started right now - but only without recording managing, but in recording in mind_).

After all this recording session happens in such way (assumed, that recording folder, format and name template is already prepared):
- prepare or not prepare sample tracks (assumed prepared);
- chose start place and pin recording to song start/stop;
- start song playing and play your instrument or sing;
- stop song (file now is recorded, may be in computer memory);
- with context menu place recording where you want;
- continue recording 
- mange placed files: rename, normalize, change format, save recorded (if in memory), delete not placed files. 

In this case:
- no change in clip/part look needed;
- no need for track to be armed for recording. 

**_One big problem:_** I do not know any DAW, with such audio recording style (some problems with multi-track recording can be solved by extension).

**Comment by michaelgregorius** [comment]
@firewall1110, the problem with the approach that you have described is that it assumes that users only want to records single tracks from single sources. However, most audio interfaces have more than one input and in all DAWs it is possible to record from them in parallel.

To solve this issue it must be possible to assign each track the input that it should record from. Because there are several potential inputs not it also does not make sense to have one global input monitor. Instead it must be possible to monitor for each individual track.

Regarding the audio pool. If it is not already implemented it would also be nice to be able to drag samples, e.g. from a sample track into AFP, etc.

Perhaps it would be best to improve LMMS from the bottom up instead of starting with "high level" features like audio recording. A good first step might be to implement the management of input and output audio channels in LMMS. This would for example enable a more flexible routing or at one point even potential support for surround sound and other multi-channel related features.

**Comment by firewall1110** [comment]
Quote: "_it assumes that users only want to records single tracks from single sources._ " **No ... Let's continue strategy**:
(4) Enabling placement for multiple audio files from session (as we can now paste multiple clips). Some handy pool files grouping. (_Can not start develop now:_ session audio pool must already be in master).
(5) Enable multiple input file naming policy and "round robin" input source monitor. (_Can not start develop now:_ no multi-track recording capable audio back-end, project audio file managing must already be in master).
(6) Enable input source "mixer" with possibility record plugin processed audio, adjust gain, ....   (_Can not start develop now:_  no multi-track recording capable audio back-end).

I wrote before only steps, could be started right now -  in parallel. 

P.S.
(a) I do not think my idea as #5990 replacement - it is something _in addition, that can be implemented easier_. 
(b) I have (and not one) multi-track recording capable audio device, but **_mostly_** recording single track from single source (Only in sound recording studio engineers **_mostly_** record multi-track).  
(c) SDL2 is only audio back-end supporting **_audio input_** (more than 3 years) but feature **_can not be used_**, even tested - is it really working? 
(d) **_How someone can enable audio input_** on Jack (good start for multiple source recording -  even not needed record capable sound card for implementing), pulseaudio, portaudio, ... : it is **_not possible to test_** input device.

**Comment by firewall1110** [comment]
_10 days alert to change goal to:_
(1) Simple audio input level monitoring and recording with processing format somewhere, there file can be easily found and included in sound track part (clip). This is custom widget placed in main application window (near oscilloscope). Recording may be started/stopped by mouse click, or may be pinned to song play start/stop.
P.S.
Alternative is to close this PR and delete branch.

**Comment by firewall1110** [comment]
**10 days alert to close this PR as not actual**

**Pull request closed without merging**
