### PR TITLE
Split InstrumentTrack

### PR DESCRIPTION
**Pull request by M374LX**
This PR aims to split InstrumentTrack.cpp and InstrumentTrack.h into one pair of files per class, as per #5592.

### CODE REVIEW

**Review by JohannesLorenz — APPROVED** [review]

**Comment by JohannesLorenz** [comment]
Thanks for the contribution.

**Comment by DomClark** [comment]
This PR downgrades rpmalloc from the latest `develop` to release 1.4.3. Is there a reason for this? Also, CircleCI didn't run for this PR for some reason, but fortunately all passed when merged into master.

**Comment by M374LX** [comment]
No, the rpmalloc downgrade was unintentional.

**Comment by DomClark** [comment]
Ah, okay. I don't think it's a problem - looking at the rpmalloc changes, it should only affect MSYS2, which we don't officially support any more. It's probably something to watch out for in the future though (not just authors, but reviewers too) - submodules seem to have a habit of doing things like this.

**Pull request merged**
