### PR TITLE
Adds automation flipping.

### PR DESCRIPTION
**Pull request by Spekular**
Implements #1289.

### CODE REVIEW

**Comment by Spekular** [comment]
@diizy is it safe to delete my branch for this now?

**Comment by diizy** [comment]
Sorry, where is the commit for the fixes?

**Comment by Spekular** [comment]
@diizy it should be the latest one.

**Comment by tresf** [comment]
> @diizy is it safe to delete my branch for this now?

image


Well... you called your branch "master" and your changes have already been merged.  Do you want to delete your own master branch? :)

Normally in your case a developer would fast forward his/her master branch and continue using it, although ideally these types of changes would be on a separate branch that could be easily deleted once merged.

**Comment by diizy** [comment]
On 01/05/2015 04:12 PM, Spekular wrote:
>
> @diizy <https://github.com/diizy> it should be the latest one.
>

You can't add commits to a pr after it's merged. You need to do a new pr.

**Comment by Spekular** [comment]
@tresf yeah it's a bit of a mess, which is why I wanna delete the entire fork and make a new proper one. The new commits don't seem to be showing up as merge-able or merged, so I suppose I should make a new pr?

**Comment by tresf** [comment]
> @tresf yeah it's a bit of a mess, which is why I wanna delete the entire fork and make a new proper one. The new commits don't seem to be showing up as merge-able or merged, so I suppose I should make a new pr?

Well, yes... sort of.  First, backup your code changes.  Next, fast forward per our wiki tutorial.  Last, verify your code is good and make a new PR.

If you really want to clean house, backup your code, hard reset your master branch, and do future changes via a dedicated branch as to not mess up your own master.

Lastly, you can always delete your repo on GitHub which will really clean things up... but if you're like me and use it for Windows binary releases and Wiki articles, you would want to weigh your options a bit first due to the amount of work involved.

**Comment by tresf** [comment]
Related #1554

**Pull request merged**
