### PR TITLE
Synchronize with remote plugins using local sockets

### LINKED ISSUE #2724: Interoperability between 32-bit and 64-bit code
I am having locking problems with VST on amd64. It looks like sem_t cannot be shared between 32-bit and 64-bit processes.
https://sourceware.org/bugzilla/show_bug.cgi?id=17980

Inter-process communication should use new sem32_* functions, pipes or sockets. You may consider endianness too (VST on powerpc). Do you want me to code this feature?

### PR DESCRIPTION
**Pull request by jasp00**
This fixes #2724 and possibly #1875.

### CODE REVIEW

**Comment by tresf** [comment]
Albeit off-topic, I had to kick-start this job 3 times for Travis to execute it properly.

@Lukas-W should we consider [`travis_retry`*`-ing`*](https://docs.travis-ci.com/user/common-build-problems/#Timeouts-installing-dependencies) our commands?

**Comment by jasp00** [comment]
The Apple builds are fixed.

**Comment by tresf** [comment]
@tobydox do you have time to review this?

@Narfinger, FYI, this will throw #2390 into conflict once merged.

**Comment by Umcaruje** [comment]
Hmm, I just compiled this branch, and now when I load up a VST using vestige (Synth1) I get this outputted in the terminal:
```
Unexpected poll error.
Error while writing.
QProcess: Destroyed while process is still running.
```
I'm on elementary OS Freya 64-bit. LMMS info:
```
Version 1.1.90-g5a74b7f (Linux/x86_64, Qt 4.8.6, GCC 4.8.4)
```

**Comment by jasp00** [comment]
This error is expected on 64-bit: you need the 32-bit `RemoteVstPlugin` (and 32-bit dependencies). This comes from a 32-bit build; your distro would provide an i386 package to an amd64 system, see #2735. Theoretically, `RemoteVstPlugin` can be compiled on amd64 with 32-bit Wine, but I have not tried that method.

**Comment by jasp00** [comment]
> Theoretically, `RemoteVstPlugin` can be compiled on amd64 with 32-bit Wine, but I have not tried that method.

You may be unable to try this. In Debian, 32-bit Wine tools depend on 32-bit GCC, which conflict with 64-bit GCC.

**Comment by Narfinger** [comment]
It still might be good to merge this if this fixes the archlinux bug. And after some testing the QT and sem_t code can be removed to cleanup the #ifdef mess.

Am I understanding this correctly that the current source code cannot be compiled on 64bit to get a working lmms+vestige? Does this first need to be merged with #2735?

**Comment by liushuyu** [comment]
>It still might be good to merge this if this fixes the archlinux bug.

I and many of my friends can help test this out. I (we) will test this very
soon.

**Comment by tresf** [comment]
> Does this first need to be merged with #2735?

From my understanding, #2735 is to allow linking against an already existing `RemoteVstPlugin`, such as in the event that it was provided by another package.  If this is the case, it means compilation for LMMS could go without the Wine dependencies and instead just link against the library.

To my understanding, #2735 is to help Debian packaging and is quite benign (adds a new optional `cmake` parameter).

> Am I understanding this correctly that the current source code cannot be compiled on 64bit to get a working lmms+vestige? 

Seems to be slightly correct statement, more of a 32 vs. 64 thing and I don't like reading comments like this... 

> You may be unable to [compile `RemoteVstPlugin` with 32-bit wine]. In Debian, 32-bit Wine tools depend on 32-bit GCC, which conflict with 64-bit GCC.

I think #2724, needs a better explanation in regards to what situation we've gotten into with Wine.  It appears @jasp00 has a pretty good grasp on why things have gone awry but I'm still missing the big picture (so I assume others are).  This is why I've asked @tobydox to review.  He knows the VST stuff better than anyone. 👍 

Here's a copy of the description from #2724:

> I am having locking problems with VST on amd64. It looks like sem_t cannot be shared between 32-bit and 64-bit processes.
https://sourceware.org/bugzilla/show_bug.cgi?id=17980

> Inter-process communication should use new sem32_* functions, pipes or sockets. You may consider endianness too (VST on powerpc). Do you want me to code this feature?

**Comment by jasp00** [comment]
> Am I understanding this correctly that the current source code cannot be compiled on 64bit to get a working lmms+vestige?

You can (and it works). In Debian, you need some trickery, see https://bugs.debian.org/823264 .
Developing with Wine in Debian has some issues (you have to set `PATH` and `RUNPATH`); it is not very friendly, although LMMS is the only project that links with Wine.

**Comment by Narfinger** [comment]
I don't quite understand. I am on archlinux and have multilib stuff installed but the standard compile does not work. It gives the same error as in @Umcaruje comment.

**Comment by jasp00** [comment]
Do you have `RemoteVstPlugin` in your installation folder, such as `/usr/lib/lmms`?

**Comment by jasp00** [comment]
I have added a test to detect the missing `RemoteVstPlugin`. The console output should be more helpful. @Umcaruje or @Narfinger, could you confirm this was the error?

**Comment by liushuyu** [comment]
I tested this patch and found that this could surely fix #1875 ! :+1: :smile: 

My configuration when testing:
Arch Linux (Base version 229, update 2016-05-20)
Wine 1.9.9-staging

**Comment by Umcaruje** [comment]
@jasp00 I can't build the branch using ninja on elementary OS Freya x64:
```
[480/481] Linking CXX shared module plugins/libzynaddsubfx.so
FAILED: : && /usr/bin/c++  -fPIC -fno-exceptions -Wall -Werror=unused-function -Wno-sign-compare -Wno-strict-overflow -Wno-array-bounds  -fPIC -DPIC -g -DLMMS_DEBUG   -shared -Wl,-soname,libzynaddsubfx.so -o plugins/libzynaddsubfx.so plugins/zynaddsubfx/CMakeFiles/zynaddsubfx.dir/ZynAddSubFx.cpp.o plugins/zynaddsubfx/CMakeFiles/zynaddsubfx.dir/moc_ZynAddSubFx.cxx.o  -Wl,--enable-new-dtags -L.. -lZynAddSubFxCore -Wl,-rpath,"\$ORIGIN" && :
/usr/bin/ld: cannot find -lZynAddSubFxCore
collect2: error: ld returned 1 exit status
```
This is probably not relevant to this patch, but to your cmake patches. I'll disable zyn and build without it, to test this out.

**Comment by Umcaruje** [comment]
Ok, wow, great job @jasp00! I managed to load several VST's into LMMS, and all worked like a charm, without any errors. I even loaded xfer Serum in, and it worked, but the GUI was all dark (that's a different issue though). So I tried Synth1, T-Force Alpha Plus, DVS Saxophone and some other VST's and all worked nicely.

**Comment by Umcaruje** [comment]
Ok, I found a weird issue, when I enable VST sync to host playback in my settings, I can't load any VST plugins, and I get 
```
Error while reading.
Remote plugin did not connect.
Error while writing.
QProcess: Destroyed while process is still running.
```
Outputted in my terminal. 

When I disable it, this is the output:
```
VST sync support disabled in your configuration
RemotePluginClient::shmget: No such file or directory
RemoteVstPlugin.cpp::shmget: No such file or directory
RemoteVstPlugin.cpp: Failed to initialize shared memory for VST synchronization.
 (VST-host synchronization will be disabled)
unique ID: S1Vs
RemotePlugin::DebugMessage: inputs: 0  output: 2
RemotePlugin::DebugMessage: creating editor
RemotePlugin::DebugMessage: editor successfully created
RemotePlugin::DebugMessage: failed getting shared memory
```

**Comment by jasp00** [comment]
> I can't build the branch using ninja on elementary OS Freya x64

@Umcaruje, this looks like a [bug in CMake 2.8](https://cmake.org/Bug/view.php?id=14728). Should I work around this bug?

**Comment by jasp00** [comment]
> I found a weird issue, when I enable VST sync to host playback in my settings, I can't load any VST plugins

Fixed.

**Comment by liushuyu** [comment]
I tested this again and found this worked for me (I am using Arch Linux which means this even fixed #1875 ) . Should we merge this ? @tresf  @Umcaruje

**Comment by Umcaruje** [comment]
>@Umcaruje, this looks like a bug in CMake 2.8. Should I work around this bug?

Well, I just upgraded my cmake to 3.2 and ninja to the latest version and I still get the error: 
```
[968/1012] Linking CXX shared module plugins/libzynaddsubfx.so
FAILED: plugins/libzynaddsubfx.so 
: && /usr/bin/c++  -fPIC -fno-exceptions -Wall -Werror=unused-function -Wno-sign-compare -Wno-strict-overflow -Wno-array-bounds  -fPIC -DPIC -O2 -Wno-write-strings -Wno-deprecated-declarations -fpermissive -O3 -DNDEBUG   -shared -Wl,-soname,libzynaddsubfx.so -o plugins/libzynaddsubfx.so plugins/zynaddsubfx/CMakeFiles/zynaddsubfx.dir/ZynAddSubFx.cpp.o plugins/zynaddsubfx/CMakeFiles/zynaddsubfx.dir/moc_ZynAddSubFx.cxx.o  -Wl,--enable-new-dtags -L.. -lZynAddSubFxCore -Wl,-rpath,"\$ORIGIN" && :
/usr/bin/ld: cannot find -lZynAddSubFxCore
collect2: error: ld returned 1 exit status
```

**Comment by Umcaruje** [comment]
Ok VST's load now with sync on. I got a crash but I'll try to reproduce and post a backtrace tommorow.

**Comment by liushuyu** [comment]
>I got a crash when closing the window of T-Force Alpha Plus but I'll try to find steps to reproduce and post a backtrace tommorow.

Did you get a SIGPIPE? Some of my VST plugins also crashed and gave me SIGPIPE or SIGSEGV

**Comment by jasp00** [comment]
I have fixed some concurrency issues with the last commit.

**Comment by liushuyu** [comment]
I have tested the new commit. It seemed that the issues were eliminated. But I am not sure if it will appear again later.

**Comment by liushuyu** [comment]
@Umcaruje So how is your result? Maybe we could merge it now?

**Comment by Umcaruje** [comment]
Ok, so I have a crash. Steps to reproduce: 
1. Open up a VST in vestige
2. Click the wrench icon () to access its parameters.
3. Close the window with the paramaters
bt full: 
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff711203a in QWidget::testAttribute_helper(Qt::WidgetAttribute) const () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
(gdb) bt full
#0  0x00007ffff711203a in QWidget::testAttribute_helper(Qt::WidgetAttribute) const () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#1  0x00007ffff71145f1 in QWidgetPrivate::setWindowTitle_helper(QString const&) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#2  0x00007ffff7119347 in QWidget::setWindowTitle(QString const&) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#3  0x00007fffafe8301f in VestigeInstrumentView::paintEvent(QPaintEvent*) () from /home/umcaruje/github/lmmsjasp/build/plugins/libvestige.so
No symbol table info available.
#4  0x00007ffff7123230 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#5  0x00007ffff70d3dec in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#6  0x00007ffff70da430 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#7  0x00007ffff695df2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#8  0x00007ffff711d951 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#9  0x00007ffff711e380 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#10 0x00007ffff711d50c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#11 0x00007ffff711e380 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#12 0x00007ffff711d50c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#13 0x00007ffff711e380 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#14 0x00007ffff711d50c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#15 0x00007ffff711e380 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBacki---Type <return> to continue, or q <return> to quit---
ngStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#16 0x00007ffff711e1ef in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#17 0x00007ffff711d50c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#18 0x00007ffff711e380 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#19 0x00007ffff711e1ef in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#20 0x00007ffff711e1ef in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#21 0x00007ffff711d50c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#22 0x00007ffff711e380 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#23 0x00007ffff711d50c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#24 0x00007ffff711e380 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#25 0x00007ffff711d50c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#26 0x00007ffff711e380 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#27 0x00007ffff711d50c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#28 0x00007ffff711e380 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#29 0x00007ffff711e1ef in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#30 0x00007ffff711d50c in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#31 0x00007ffff72e0666 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#32 0x00007ffff7112df0 in QWidgetPrivate::syncBackingStore() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#33 0x00007ffff7122daa in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#34 0x00007ffff74dcba3 in QMainWindow::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#35 0x00007ffff70d3dec in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#36 0x00007ffff70da430 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#37 0x00007ffff695df2d in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#38 0x00007ffff696155d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#39 0x00007ffff698b973 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#40 0x00007ffff3bfcbd4 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#41 0x00007ffff3bfce18 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#42 0x00007ffff3bfcebc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#43 0x00007ffff698b191 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#44 0x00007ffff7175a06 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
No symbol table info available.
#45 0x00007ffff695caef in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#46 0x00007ffff695cde5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#47 0x00007ffff6962599 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
No symbol table info available.
#48 0x00000000004883fb in main ()
No symbol table info available.
```

Another thing I noticed is that the parameter window also has a fixed width, which ends up having a lot of blank space when dealing with VST's with few parameters.

**Comment by jasp00** [comment]
Yes, there is a crash and a lot of blank space in the window. There is another crash when removing the track while still playing. But these are issues independent from this pull request.

**Comment by Umcaruje** [comment]
>Yes, there is a crash and a lot of blank space in the window. There is another crash when removing the track while still playing. But these are issues independent from this pull request.

Ok, I'll open up new issues for those, as they are out of scope :+1: 

I tested again, and can conclude that VST's work stable and like a charm, this is good to be merged :tada:

**Comment by tresf** [comment]
> [...] fixed width [...]

Yes.  Somewhat related/FYI https://github.com/LMMS/lmms/issues/1184#issuecomment-57627988

**Comment by jasp00** [comment]
Fixed loading on Windows.

**Comment by falkTX** [comment]
can someone do a rebase of this patch against the stable branch please?

I'm not sure how long the next version of lmms is going to take, so I'd like to backport the fix into the current stable release.

**Comment by jasp00** [comment]
This is not exactly a backport. This is the Debian [patch](https://anonscm.debian.org/cgit/debian-edu/pkg-team/lmms.git/plain/debian/patches/sync-socket.patch) against version 1.1.3; it was developed before this pull request.

**Pull request merged**
