### PR TITLE
Making preset saving oblivious to mute/solo/muteBeforeSolo states.

### PR DESCRIPTION
**Pull request by justlog**
Addresses issue #6073. 

After saving the track settings into dataFile, we should be able to just set the muted/solo/mutedBeforeSolo attributes to 0 as we don't use them for preset saving.

### CODE REVIEW

**Comment by PhysSong** [comment]
There might be some better ways to do this, but this looks fine to me, except indentations. Please use tabs instead of spaces in `src/tracks/InstrumentTrack.cpp`.

**Comment by justlog** [comment]
> There might be some better ways to do this, but this looks fine to me, except indentations. Please use tabs instead of spaces in `src/tracks/InstrumentTrack.cpp`.

Fixed.

**Comment by Spekular** [comment]
I think you should probably implement mutedBeforeSolo get/setters for consistency, leaving m_mutedBeforeSolo private. That would mean putting this in the public section
```
bool isMutedBeforeSolo() const
{
	return m_mutedBeforeSolo();
}
```
and this in the public slots:
```
void setMutedBeforeSolo(const bool muted)
{
	m_mutedBeforeSolo = muted;
}
```

These functions are generated automatically for solo and mute via the lines linkes below, but because mutedBeforeSolo isn't an AutomatableModel you can't do the same for it
https://github.com/LMMS/lmms/blob/6a716fa5fd114525b0562cd1788534820eb5d16d/include/Track.h#L60-L61
	
What you should _definitely_ do is put m_soloModel back in the private section.

That aside this looks good to me.

**Comment by justlog** [comment]
> 

Fixed.

**Review by Spekular — APPROVED** [review]
LGTM!

**Pull request merged**
