### PR TITLE
Fix lost connections when restoring automation clip

### LINKED ISSUE #6829: Undoing a deletion of an automation entry causes all automation entries on that automation line to lose their connections
### Bug Summary
Undoing a deletion of an automation entry causes all automation entries on that automation line to lose their connections.

#### Steps to reproduce
Create multiple automation with multiple connections.
Delete one of the automation entries.
Undo the automation deletion.
All other automaton entries on that line lose their connections.

#### Expected behavior
All other automaton entries should retain their connections.

#### Actual behavior
All other automaton entries on that line lose their connections.

#### Screenshot
TODO

#### Affected LMMS versions
Current Master branch (fc2f6a0b31bdd10c47cc0c6c2c18723d208eaae0) (built on Windows with MSVC).

#### Logs
TODO

### PR DESCRIPTION
**Pull request by szeli1**
this fixes #6829

Now when undeleting an automation clip, it's connections shouldn't be lost.

### CODE REVIEW

**Review by zonkmachine — APPROVED** [review]
Tested, fix confirmed!

**Comment by DomClark** [comment]
Do projects with a lot of automation still load correctly after this change? It looks like this may resolve IDs too early, so automation clips connected to objects which have not yet been loaded may never be reconnected.

**Comment by zonkmachine** [comment]
> Do projects with a lot of automation still load correctly after this change? It looks like this may resolve IDs too early, so automation clips connected to objects which have not yet been loaded may never be reconnected.

I've tested the bigger projects like Greippi - Krem Kaakkuja, and EsoXLB - CPU They seem to open correctly.

**Comment by szeli1** [comment]
> Do projects with a lot of automation still load correctly after this change? It looks like this may resolve IDs too early, so automation clips connected to objects which have not yet been loaded may never be reconnected.

resolveAllIDs gets run for every single restored clip so this shouldn't be a problem, but there is a chance it gets called unnecessarily

**Comment by szeli1** [comment]
This should make resolveAllIDs run only once for 1 automation track loading (not a perfect solution).
Song.cpp line 1192 is now unnecessarily, but I left it in.

**Comment by szeli1** [comment]
> `AutomationClip::resolveAllIDs` should run only once everything has been loaded. Perhaps consider putting it at the end of `ProjectJournal::undo` and `ProjectJournal::redo`?

I thought about that and to me It looked out of place. In `ProjectJournal` how would I check if it is necessary to run `AutomationClip::resolveAllIDs`?

**Comment by szeli1** [comment]
> `AutomationClip::resolveAllIDs` should run only once everything has been loaded. Perhaps consider putting it at the end of `ProjectJournal::undo` and `ProjectJournal::redo`?

I think I managed to move the `AutomationClip::resolveAllIDs` into `ProjectJournal::undo`. (I had issues with git, hopefully it did not cause issues here)

**Comment by DomClark** [comment]
> I thought about that and to me It looked out of place.

Automation and undo history are some of the uglier bits of LMMS, so where the two intersect, you'll unfortunately have nasty things like this. We want to improve them, but it's a lot of work, there are lots of other things to do, and there's only so much contributor time to go around.

> In `ProjectJournal` how would I check if it is necessary to run `AutomationClip::resolveAllIDs`?

I'm not sure whether it's worth checking at all, but if you do want to check, have a look at `QDomDocument::elementsByTagName`, which should provide a concise way to check for the existence of any `automationclip` tags.

**Comment by szeli1** [comment]
> have a look at `QDomDocument::elementsByTagName`, which should provide a concise way to check for the existence of any `automationclip` tags.

implemented, tested it with your example project (and others), should I re request a review?

**Comment by zonkmachine** [comment]
This PR has conflicts with master.

**Comment by szeli1** [comment]
I can not see conflicts. I will mark this as resolved (if you agree).

**Comment by zonkmachine** [comment]
I mean this here:

image

If you check the 'Resolve conflicts' button it will show no conflicts but merging into master on the command line there really is unresolved stuff in `src/core/Track.cpp`. Odd. If you're happy with it as it is, though, then I'm happy.

**Comment by zonkmachine** [comment]
> If you're happy with it as it is, though, then I'm happy.

The PR can't actually be merged as it is though. The merge button is greyed out on my side.

**Comment by szeli1** [comment]
I will resolve the 0 conflicts. I don't know why git is confused, I eventually deleted all the changes in `Track.h` in this pr.

**Comment by zonkmachine** [comment]
Git is happy now.

**Comment by Rossmaxx** [comment]
From the comments, looks like it was supposed to be merged last month.

**Comment by zonkmachine** [comment]
> From the comments, looks like it was supposed to be merged last month.

No. It's awaiting a re-review from Dom.

**Review by DomClark — APPROVED** [review]

**Pull request merged**
