### PR TITLE
Save and load the mute flag for automation patterns

### PR DESCRIPTION
**Pull request by Sti2nd**
Cherry picked from master

### CODE REVIEW

**Comment by Spekular** [comment]
@sti2nd nice!

**Comment by Sti2nd** [comment]
lol, I didn't do anything. Compliment to you, Dave

**Comment by tresf** [comment]
:+1:

**Comment by Spekular** [comment]
@sti2nd I know it was just a cherry-pick, but I haven't seen you touch code
in any way before. There's always a start :P

**Comment by Sti2nd** [comment]
:) How much Java did you know before you began coding C++? I am learning Java now at school, and C++ in my spare time, but I find C++ rather hard. What resources did you use for learning C?

**Comment by Spekular** [comment]
@sti2nd been learning java on and off for a couple of years now, just using
the official tutorials and stuff. Haven't actually "learned" any C++, I
just use what I know from java and can infer from the rest of the source
code (read: copy paste :P ).

**Comment by curlymorphic** [comment]
> Compliment to you, Dave

cheers for doing the cherry picking :)

I
just use what I know from java and can infer from the rest of the source
code (read: copy paste :P ).

I find thats the best way when starting to use a different language. most programming concepts remain the same between languages. Java was designed to be similar to c++, IMO the main difference when first moving from java to c++ is pointers and memory management (remembering to deallocate is the usual pitfall).

**Comment by curlymorphic** [comment]
back on topic, seeing as this had not gone thru bug testing, maybe it would be a good idea to make sure we test it as soon as the builds are released.

**Comment by Sti2nd** [comment]
It works by testing with https://github.com/LMMS/lmms/issues/1662#issuecomment-73834706

**Comment by tresf** [comment]
back off-topic... :)

My second job is coding Java, and I can say I have some pretty big learning curves when jumping from Java to C++.

In Java everything is a pointer.  All objects are passed by reference and a garbage collector cleans up the unused objects.  All classes are objects and objects are classes.  There are primitives (like bool and int) but for the most part objects behave like pointers to containers.

QT seem to do something similar under the covers in terms of memory/object lifecycle management,  In Java, allowing the garbage collector to clean everything up automagically I works 95% of the time without worry.  For the edge-cases, setting a variable to `null` is usually good enough.  But memory management simply isn't a worry in Java.  I don't consider this the largest learning curve though.... 

Here's what I find most confusing about C++
 * **MACROS** Looking at code and seeing [`QOBJECT` or `MM_OPERATORS`](https://github.com/LMMS/lmms/blob/master/plugins/organic/organic.h#L78) in the class constructor is a foreign concept to Java programmers.  Also, the UPPERCASE_NAMES look a lot like `const` variables in Java, so that takes a while to rewire in the brain. :)
 * **INITIALIZER LISTS** In Java, setting a variable `final` and placing instantiation in the constructor is all that is needed to initialize it with an object.  In C++, it must be part of an initialize list (similar to a Java Enum declaration).  This makes the constructors very hard for me to read IMO.
 * **INITIALIZER LISTS, AGAIN** In C++ the instantiation is done via `varable(value);` rather than `variable = value`.  Again, makes it hard to read as declaration in `function(variable)` syntax is just plain strange to read to a non-C coder.
 * **EXTENDING CLASSES** I'm still trying to wrap my head around this, but extending a class with a ` : ` colon is tremendously confusing to me still.  I need to study this more.
 * **MIXING OF CODE** The fact that C++ allows programmers to use C syntax is very noble, but it is damn hard to read.  You'll see this with you see `myObject.setValue(myValue);` and then later `myObject::setValue(myValue);` and then the pointer version (I think) `myObject->setValue(myValue);`
 * **HEADER FILES** I see a lot of computational logic code which should be in a `.cpp` file but is instead placed into a `.h` file.  LMMS has full classes which exist only in header files.  This concept is foreign to Java.
 * **HEADER FILES, AGAIN** Furthermore, the idea of putting all header files everywhere (plugins excluded) into a single `./include` directory is quite foreign.  It has similarities in the sense of Java Class paths, but it really is strange API organization from most modern languages I've dealt with.
 * **MULTIPLE CLASSES, CLASS NAMING** Having multiple classes within a single header or source file is a bit strange.  In Java the class name must always match the source file.  C++ isn't strict in this regard.
 * **IMPLICIT CONSTRUCTORS** When I see ProjectVersion p = "1.0.0" I stop and say... WTF?  These "hey, I think this is what you mean" implicit constructing of variables is foreign but only because of how strongly typed of a language C++ is.  Most scripting languages allow loose handling of objects, but this one is simply puzzling to me.
 * **OPERATOR OVERRIDES** Being able to override the return value of `>, <, =, !=, etc` is something I've never had the luxury of doing in any other language.  This is quite foreign (but quite nice too).

I'm sure I have a few more, but those are the first that come to mind... 

-Tres

**Comment by curlymorphic** [comment]
Maybe i'm looking at this from the wrong perspective. I learnt c and c++ long before i learnt any java. I only stared to learn java at the end of 2013 for use in android apps, I used java pretty much exclusively for most of last year. I do like to swap and change what language i code in.

@tresf im going to respond to your notes. most of what I will say is mainly opinion, maybe it will help out, If i confuse anyone, sorry. I am also answering these to make things clearer in my own head.




> MACROS Looking at code and seeing QOBJECT or MM_OPERATORS in the class constructor is a foreign concept to Java programmers. Also, the UPPERCASE_NAMES look a lot like const variables in Java, so that takes a while to process. :)

Agreed the only other language that i used to use where macro's were common was x86 assembler. Qt does seem to like a macro, but for 99% of the time there is no need to understand them, just remember to put a Q_OBJECT macro in classes that use signals and slot. Thats probably enough about macros to build your first few apps, and to work on the majority of lmms issues.

UPPERCASE_NAMES CamelCase and pascalCase seem to switch from language to language, but these are only guidelines (not sure about c++ macros). luckily for the most part c++ and java use the same, pascalCase for functions and members, CamelCase for class names. I find the whole concept of java's
````
public final static int FIRST_OPTION = 0;
public final static int SECOND_OPTION = 1;
````
to be very verbose, iirc enums were a late addition to java? Android apps are full of the above code.

> INITIALIZER LISTS In Java, setting a variable final and placing instantiation in the constructor is all that is needed to initialize it with an object. In C++, it must be part of an initialize list (similar to a Java Enum declaration). This makes the constructors very hard for non-C++ coders to read IMO.

This can be frustrating at first. yes life would be easier if '''' float m_myVar = 1234.0f;```` worked in the header file.

> INITIALIZER LISTS, AGAIN In C++ the instantiation is done via varable(value); rather than variable = value. Again, makes it hard to read as the declaration LOOK LIKE function(variable)/ This is just plain strange to read to a non-C coder and has taken a long time for me to realize.

yeah, this is sort of a convention as ````m_myVar = new MyClass("hello world");```` also works. It also gets more confusing when you also pass parameters to base class constructors using the same format.

> EXTENDING CLASSES I'm still trying to wrap my head around this, but extending a class with a : colon is tremendously confusing to me still. I need to study this more.

This is just c++ way of handling inheritance. in java i believe  it would be wtitten as
````public class Myclass extends SomeOtherClass````.  http://docs.oracle.com/javase/tutorial/java/IandI/subclasses.html



> MIXING OF CODE The fact that C++ allows programmers to use C syntax is very noble, but it is damn hard to read. You'll see this with you see myObject.setValue(myValue); and then later myObject::setValue(myValue); and then the pointer version (I think) myObject->setValue(myValue); This is just a code quality thing, but it suggests those that know C++ also have historically known C (which seems to be the case out of necessity). I find the intermingling of code standards to be tremendously confusing. :)

All the examples used above are c++ syntax. c does not have any concept of classes. but im going to try and explain the differences. ````myObject.setValue(myValue);```` is the same as java, it call the setValue function on the myObject INSTANCE. ````myObject::setValue(myValue);```` is calling the STATIC function setValue on the class not an instance of. this is the same principal as java, http://docs.oracle.com/javase/tutorial/java/javaOO/classvars.html. ````myObject->setValue(myValue); ```` can be read the same as  ````myObject.setValue(myValue);```` except it is using a pointer. the ide i use automatically converts between . and -> when needed. 


> HEADER FILES I see a lot of computational logic code which should be in a .cpp file but is instead placed into a .h file. LMMS has full classes which exist only in header files. This concept is foreign to Java.

The closest i can compare a header file to in java is an interface. Im not sure why we put implementations in the header file, maybe to save space.



> HEADER FILES, AGAIN Furthermore, the idea of putting all header files everywhere (plugins excluded) into a single ./include directory is quite foreign. It has similarities in the sense of Java Class paths, but it really is strange API organization from most modern languages I've dealt with.

where the header files go is developer choice, it's declared in the make files. My preference would be to keep the .h files in the same folder as the relevant .cpp file. each project/developer has his own way of doing it, no one way is better than any other, it's just what you get used to.



> MULTIPLE CLASSES, CLASS NAMING Having multiple classes within a single header or source file is a bit strange. In Java the class name must always match the source file. C++ isn't strict in this regard.

I feel the java way is cleaner, but the c++ way lets you group related classes together.

> OPERATOR OVERRIDES Being able to override the return value of >, <, =, !=, etc is something I've never had the luxury of doing in any other language. This is quite foreign (but quite nice too).

yes. It can also be abused by developers to make following there code harder, deliberately reversing the meanings of > and < for example.

Im glad I responded to this, it has made me think about my above statement, maybe moving from java to c++ is not as simple as i thought. If anyone has trouble converting some code from java to c++ i will try and help (LMMS related or not) my email is all over github, commit logs etc. Anyway enough waffle from me, github is telling me i have spent 2 hours on this reply. I might be able to code in a few languages, but i struggle to write coherently in my native tongue, and that is the 1 language i have to use daily all my life.

**Comment by tresf** [comment]
> github is telling me i have spent 2 hours on this reply. I might be able to code in a few languages, but i struggle to write coherently in my native tongue, and that is the 1 language i have to use daily all my life.

Thanks for the pointers.  Greatly appreciated...

**Pull request merged**
