### PR TITLE
Disable fluidsynth audio backends if possible

### LINKED ISSUE #649: SF2 hangs on open (Apple)
Software freezes and causes the user to "Force Quit" when opening any project with at least one soundfont .
- This crash occurs with SF2 files as relative OR absolute paths.
- This crash occurs with SDL OR PortAudio.
- This crash DOES NOT occur when using Dummy Audio.

The soundfont player works if added manually, but when reopening the project, the software hangs on a dialog that says "Opening project" usually around 70-80% with the spinning wheel which never goes away.

The screenshot below (sorry, not ver descriptive) is the screen that the user will see when the freeze occurs.  The default project is loaded in the background while the "Opening project" screen appears and then the pinwheel appears and the software has crashed.

screen shot 2014-04-26 at 12 25 10 pm

Possibly related:  http://www.juce.com/forum/topic/coreaudio-possible-deadlock-when-moving-mavericks

Backtrace:
https://gist.github.com/tresf/230b20f083403a11a3c7

### PR DESCRIPTION
**Pull request by tresf**
Closes #649
Partially reverts #3446

Wiki has already been updated to remove custom homebrew formulae.
https://github.com/LMMS/lmms/wiki/Dependencies-MacOS

### CODE REVIEW

**Comment by Birch-san** [comment]
LGTM, for what it's worth. That same runtime check [worked for me](https://github.com/Birch-san/juicysfplugin/commit/6e88039085525fbf906743e481aac440bce530c6). with that, my plugin was able to use standard fluidsynth without compile flags.

**Comment by tresf** [comment]
Tested, works.  Travis is happy.  Merging.

**Comment by derselbst** [comment]
The version check will silently evaluate to false for a 2.0 or 1.2.0 release. Consider using

```c
#if FLUIDSYNTH_VERSION_MAJOR > 1 || FLUIDSYNTH_VERSION_MICRO > 1 || (FLUIDSYNTH_VERSION_MICRO >= 1 && FLUIDSYNTH_VERSION_MICRO >= 9)
```

or

```c
#if QT_VERSION_CHECK(FLUIDSYNTH_VERSION_MAJOR, FLUIDSYNTH_VERSION_MINOR, FLUIDSYNTH_VERSION_MICRO) >= QT_VERSION_CHECK(1,1,9)
```

**Comment by tresf** [comment]
@derselbst good catch.  Done via aaee2ec.

**Pull request merged**
