### PR TITLE
Recording -> SampleBuffer -> TripleOscillator: Support loading empty files and add samples/empty.wav  

### PR DESCRIPTION
**Pull request by Reflexe**
Since a few TripleOscillator presets uses the non-existing `samples/empty.wav`, I've decided to use the simplest way and just add this file. 

However, the current implementation of SampleBuffer treated empty data as an error. So this PR should take care of that too.

### CODE REVIEW

**Comment by karmux** [comment]
This PR fixes empty.wav problem with TripleOscillator presets.

Wouldn't it have been simpler to just change `userwavefileX="samples/empty.wav"` to `userwavefileX=""` in project files? :slightly_smiling_face:

**Comment by Reflexe** [comment]
It would. But i think that this is the safest way to ensure backward
compatibility with older presets and avoid changing a big amount of presets
which could lead to more bugs.

**Comment by PhysSong** [comment]
> Wouldn't it have been simpler to just change `userwavefileX="samples/empty.wav"` to `userwavefileX=""` in preset files? 🙂

I think we can use `DataFile::upgrade`. BTW, what if a user has non-empty `samples/empty.wav?` Should we ignore that case?

**Comment by Reflexe** [comment]
@PhysSong  Could you merge it to the main recording pull request?

**Comment by PhysSong** [comment]
@Reflexe I'm not sure how to handle the `empty.wav` issue, but the rest of this PR looks good. Sorry for the late response.

**Comment by Reflexe** [comment]
@PhysSong I think that this is the best and natural way to do it. that would also make sure user's presets would not get invalidated.

**Comment by PhysSong** [comment]
@Reflexe Cherry-picked most commits to #4531. Thank you for your works! :+1:

**Pull request closed without merging**
