### PR TITLE
adds doxygen documentation to SubWindow.cpp

### PR DESCRIPTION
**Pull request by BaraMGB**
I began to write documentation for my work on lmms. Perhaps someone with more expierence on this can guide me a little bit.

### CODE REVIEW

**Comment by jasp00** [comment]
You should document public and protected interfaces in the headers. Copyright notices should not be the place for documentation. You should explain what the functions are supposed to do without giving implementation details; documentation is like a contract, try not to describe behavior you may want to change later.

**Comment by Umcaruje** [comment]
Changed the PR to address `stable-1.2`

**Comment by BaraMGB** [comment]
@jasp00 I'll try to make it better. I think I understand what you mean. 

@umcaruje thank you.

**Comment by Umcaruje** [comment]
@BaraMGB is there more work that you want to do on this or can we merge?

**Comment by BaraMGB** [comment]
@Umcaruje yes. But I'm short in time at the moment. But soon it will be better and I can develop again.

**Comment by tresf** [comment]
Bad documentation is better than no documentation.  No need to bike-shed over where it lives.  Doxygen is meant to be exported as an API, so whether this is in a single comment or a proper parsable comment is rather arbitrary until we publish an API for our developers.

Merging.  @BaraMGB can improve this down the road, no PR needed, just commit straight to master. 👍

**Pull request merged**
