### PR TITLE
Add Quantize button to Piano Roll (WIP)

### PR DESCRIPTION
**Pull request by grejppi**
# WORK IN PROGRESS

Inspired by a conversation on #lmms:

```
14:03 < klopsi-u3> is there a way to force an already recorded track to a lower 
                   quantisation?
...
14:42 < grejppi> klopsi-u3: none in the interface
14:42 < grejppi> that would be a useful feature though
14:44 < klopsi-u3> ok
14:45  * grejppi might hack that in
14:45 < klopsi-u3> :)
14:45 < grejppi> or at least try
14:46 < grejppi> I've already been sidetracked by so many things today c:
14:50 < klopsi-u3> i think there should be a seperate button for 'quantise 
                   piano roll'
14:50 < klopsi-u3> iow, not automatically shift quantisation if the 
                   quantisation dropdown is changed
14:51 < grejppi> yeah
14:51 < klopsi-u3> maybe even only quantise selected notes
```

There is now a new button in the Piano Roll editor toolbar:

toolbr

If there is a selection, it will quantize the selected area to the current quantization level (1/4 in these screenshots for clarity):

quantize_sel

Without a selection the entire pattern is quantized.

quantizeproper

## Known issues:
* ~~As you can see from the [last screenshot](https://cloud.githubusercontent.com/assets/772336/11762384/484eefb8-a0ed-11e5-9e53-b93a866bd1db.png), there are still cases where some notes are left as-is. I will investigate this.~~
* This has absolutely not been tested yet. At least it builds for now.

### CODE REVIEW

**Comment by BaraMGB** [comment]
There should be a different between length and position quantization.

**Comment by grejppi** [comment]
@BaraMGB that would be a matter of changing the behaviour of `Note::quantizeLength()`.

**Comment by zonkmachine** [comment]
Cool! Tested it and it seem to work just fine.

**Comment by zonkmachine** [comment]
Swing?

swing

**Comment by grejppi** [comment]
@zonkmachine what happens in that screenshot?

**Comment by zonkmachine** [comment]
Yes, that wasn't all too clear.
I'm trying to show that from implementing quantisation to adding swing/groove shouldn't be that much work. I haven't dug any deeper into the various versions of swing but an Issue for it with links to articles is here -> https://github.com/LMMS/lmms/issues/1091

**Comment by grejppi** [comment]
@LMMS/developers I don't generally like merging my own pull requests, but unless there are any objections I will do that in 24 hours. This does not seem to break existing functionality :+1:

**Comment by tresf** [comment]
👍

**Pull request merged**
