### PR TITLE
provides a new GUI for the peak controller plugin

### PR DESCRIPTION
**Pull request by BaraMGB**
bildschirmfoto von 2016-06-02 16-49-09

I wait for an answer from @RebeccaDeField for providing a better artwork.png for this. 

The label of the amount knob is different to the label of the LFO controller. In Peak controller it is "AMNT" named. In LFO controller "AMT". I suggest, we should decide for one version. I think, "AMNT" is the better choice, but for that, I have to make an other PR to change the LFO. If we decide for "AMT", I can do this with this PR.

Regards

### CODE REVIEW

**Comment by RebeccaDeField** [comment]
I inspected both the LFO and Peak controllers and came to the conclusion that the LFO title had too much anti-aliasing and the Peak had a bit too little (notice how the L's are flush together. Sub-pexel rending would probably be the perfect solution, but unfortunately, to my knowledge Inkscape does not currently have that capability.

I played around with the kerning, tracking, different font sizes, etc and came to something that I think is a good compromise between the two.
lfo2
peakcontroller

I also realized that the LFO and Envelope graph would need to match, but the smaller font size caused some issues. If found that choosing a lighter font weight and making a couple of tweaks in the GIMP has the best results.

lfo
envelope

Please note that these are transparent, so they won't look the same here as they will in the program.

**Comment by BaraMGB** [comment]
Thank you very much, @RebeccaDeField. I set the new artwork in, soon. For the lfo controller I make a new PR. 

@Umcaruje any suggestions?

**Comment by Umcaruje** [comment]
>Sub-pexel rending would probably be the perfect solution, but unfortunately, to my knowledge Inkscape does not currently have that capability.

By rendering with Cairo PNG, you get better font hinting in inkscape: http://libregraphicsworld.org/blog/entry/getting-crisper-text-out-of-inkscape

I'm not sure its exactly sub-pixel rendering, but it really saves you the trouble of going to gimp and manually editing the text. You also ought to know that Cairo PNG doesn't support transparency, so for that you'll need to manually convert the black color to alpha, by using the Gimp 'color to alpha' tool.

The Cairo PNG export is located in the Save As…/Save Copy As… dialog.

>@Umcaruje any suggestions?

You could easily replace the lfo controller artwork too, just make a seperate commit. 

Also @BaraMGB @RebeccaDeField this shuld also happen with the amplifier plugin and others, so it'd be nice to share the final .svg with the "winning formula"

**Comment by BaraMGB** [comment]
Okay, done so far. And changed the amount knob label in LFO.

bildschirmfoto von 2016-06-03 14-24-26

**Comment by RebeccaDeField** [comment]
> By rendering with Cairo PNG, you get better font hinting in inkscape

Cairo PNG actually is what I use for hinting :+1:  It just took some tweaks to the SVG before exporting to get it to look right. For example, if you bring the font 1px down in size it doesn't work all that well.

> I'm not sure its exactly sub-pixel rendering, but it really saves you the trouble of going to gimp and manually editing the text.

Yes, I don't think it supports sub-pixel rendering, but it still is a pretty good hinting tool. That is why I had to make a couple of edits in the GIMP on the Cairo exports that were using the light weight font (I couldn't use bold on the smaller ones without it looking muddy.)

I didn't make any edits in GIMP on the first two with the bold font after exporting in Cairo.

> It'd be nice to share the final .svg with the "winning formula"

I'll update the SVG's in my pull request later today.

**Comment by Umcaruje** [comment]
@BaraMGB are there gonna be any updates to the artworks or is this the final version, and we can merge?

**Comment by BaraMGB** [comment]
If you don't have objections about this, it can be merged.

**Comment by Umcaruje** [comment]
:+1:

**Pull request merged**
