### PR TITLE
Better handling of invalid audio/MIDI backend

### PR DESCRIPTION
**Pull request by PhysSong**
Fix crash when nonexistent/not supported audio/MIDI backend is written in `.lmmsrc.xml`.
Supersedes #4372.

### CODE REVIEW

**Comment by PhysSong** [comment]
Merging this one will stop crash in #4405. However, LMMS will show up a dialog to select audio backend(the default value will be Dummy). Before releasing RC7, we should add an upgrade logic or some alternative way to change PortAudio to SDL. Should I add that in this pull request, or open a separate one?

**Comment by zonkmachine** [comment]
> Should I add that in this pull request, or open a separate one?

Just fix it up here.

**Comment by PhysSong** [comment]
> Before releasing RC7, we should add an upgrade logic or some alternative way to change PortAudio to SDL.

I have some ideas about it:
- Fallback to default audio backend if invalid one is selected. In Windows case, it will automatically fallback to SDL.
- Write a separate upgrade logic for PortAudio -> SDL. Then the fix will be out of scope of this PR.
- In case of invalid backend selections, show default backend instead of Dummy one in setup dialog at launch.

**Comment by zonkmachine** [comment]
> * Fallback to default audio backend if invalid one is selected. In Windows case, it will automatically fallback to SDL.

If this means that you won't have to restart lmms again after doing a selection this is my choice. A separate  upgrade routine sounds like a bit of an over kill. Maybe one of those floating messages to give a hint of the changes to the user would be a good idea.

**Comment by lukas-w** [comment]
Either option 1 or 3 is fine in my eyes.

**Comment by PhysSong** [comment]
Then I'll implement option 1 here. It looks simple to me.

**Comment by PhysSong** [comment]
I found that if the audio backend is set to an empty string, LMMS will use the default one and not show the setup dialog.
In case of invalid settings, the dialog should show up. However, I don't know if this should be the same for empty strings. It depends on how I implement the fallback logic, and the converse is also true.
How should I handle the empty-string case?

**Comment by PhysSong** [comment]
Implemented the fallback logic via c5810d2b5b1a21e8af57d897079fb9ec433ac072.

**Comment by PhysSong** [comment]
I will merge this one soon if no one objects. Further refactorings and UX improvements are also possible, but I'd like to defer them to the `master` branch.

**Pull request merged**
