### PR TITLE
Apple Travis-CI enhancments

### PR DESCRIPTION
**Pull request by tresf**
Per https://github.com/LMMS/lmms/issues/2504#issuecomment-186252596

Note: I'll merge this myself.  This PR is explicitly for testing Travis + Mac, which makes the PR necessary for proper testing.  I'll squash commits once everything looks ok.

### CODE REVIEW

**Comment by tresf** [comment]
For some reason the Apple build is failing on `tests`.... It says `libogg` isn't present, not sure why... 

Squashing commits and monitoring build to see if it's a fluke with Travis...

```
Supported file formats for project export
-----------------------------------------
* WAVE                        : OK
* OGG/VORBIS                  : not found, libogg-dev and libvorbis-dev (or similar) ;is highly recommended


# ... 

[100%] Built target tests
dyld: Library not loaded: /usr/local/opt/libogg/lib/libogg.0.dylib
  Referenced from: /usr/local/opt/libsndfile/lib/libsndfile.1.dylib
  Reason: image not found
/Users/travis/build.sh: line 45: 21937 Trace/BPT trap: 5       ./tests/tests
```

**Comment by tresf** [comment]
Re-firing build still doesn't help.... @Lukas-W any insight here?  The log says it is installed, but cmake is having trouble locating it...  shall we merge anyway?  My box doesn't exhibit this problem, instead it says `OGG/VORBIS : OK`.

```
Supported file formats for project export
-----------------------------------------
* WAVE                        : OK
* OGG/VORBIS                  : not found, libogg-dev and libvorbis-dev (or similar) ;is highly recommended
```

**Comment by tresf** [comment]
Ok, changing the order of things has now caused libsndfile to break.  Interesting.... I'm going to move `libogg` before `libvorbis` and before `sndfile` because the others seem to rely on it. 56b2947.  P.S. This sucks. :+1: 

```
-- Checking for module 'sndfile>=1.0.11'
--   Package 'sndfile>=1.0.11' not found
CMake Error at /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPkgConfig.cmake:360 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.4.3/share/cmake/Modules/FindPkgConfig.cmake:522 (_pkg_check_modules_internal)
  CMakeLists.txt:176 (PKG_CHECK_MODULES)
```

**Comment by tresf** [comment]
Now it skips `libsamplerate`... this has gotta be a bug with `brew reinstall`.  When examining the logs, it says it is reinstalling, but instead skips over `libsamplerate`.

**Comment by tresf** [comment]
Ok, shuffled some more items around ( `libsamplerate` before `jack`) and it's passing.  Will wait for final green light from Travis, then merge.

**Comment by Umcaruje** [comment]
:+1:

**Comment by tresf** [comment]
Merged, updated wiki.

**Pull request merged**
