### PR TITLE
 Random crash in sf2_player #2401 

### PR DESCRIPTION
**Pull request by midi-pascal**
Remove note from m_playingNotes before deleting its pluginData in deleteNotePluginData()

### CODE REVIEW

**Comment by tresf** [comment]
@midi-pascal for starters, you can feel free to squash these commits.

Second, the extra header -- is that needed?

Last, the newlines/line deletes can probably be restored to their previous state unless they were done for readability reasons.

I'll let someone more qualified speak to the actual code changes.

Thanks for taking the time to figure git out, often I spend more time with git command than I do with actual code.

**Comment by midi-pascal** [comment]
@tresf The extra commits are the goofs I made previously trying to make my fork in sync with the master branch. They contains nothing but I do not know how to remove them from the PR. Only one file was changed.
The empty new lines or deleted empty lines are the result of many many trials and errors while tracking the issue.  I will be more vigilant in the future.
Anyway many thanks for your invaluable help with git; I still have to get familiar with it.

**Comment by tresf** [comment]
`git rebase -i HEAD~4`

When prompted, squash everything except the intended commit by replacing `merge` with `squash`.

If your intended commit isn't on top, out it there.

The second prompt, leave only one comment.  Delete or comment out the rest.

When you push, you'll have to force.  That will overwrite history and put you back to a single clean commit.

**Comment by midi-pascal** [comment]
@tresf git rebase -i HEAD~4 gives:
pick 3878fe5 Removes existing controllers from the view when a new project is created
pick d6a25f9 FileBrowser: Fix file paths
pick 8e633df Adds better versioning for non-stable builds
pick 61334e8 Remove note from m_playingNotes before deleting its pluginData in deleteNotePluginData$

# Rebase d4b2cb1..61334e8 onto d4b2cb1
#
...
So I do not see my goofs in the list and no "merge".
git makes me feel so dumb...

**Comment by tresf** [comment]
Sorry, that's what I get for typing from a phone... I meant to say replace `pick` with `squash`, but since your changes are minor, you are better off making a backup copy of `sf2_player.cpp` and doing a hard reset and then a fast-forward, and then put `sf2_player.cpp` back in place.


```bash
cp plugins/sf2_player/sf2_player.cpp ~/Desktop/sf2_player.cpp # backup work
git reset --hard 7881e0 # rewind to some old arbitrary commit
git remote add upstream https://github.com/LMMS/lmms.git # add upstream (ok if already added)
git pull --rebase upstream master # this should execute without problems
git push --force
```

Now, [visit your branch](https://github.com/midi-pascal/lmms) and make sure it says it is even with `lmms/lmms` master.

Now, leave master alone, and create a new branch.  A quick way to do this is to make it [through the GitHub web page through the dropdown that switches branches](https://cloud.githubusercontent.com/assets/6345473/10594976/e11b9042-76a0-11e5-89f5-51310ac05b74.png).

```bash
git pull # fetch list of branches, etc
git checkout branch_name_you_used_above
cp ~/Desktop/sf2_player.cpp plugins/sf2_player/sf2_player.cpp  # restore work
# now you can edit the file and fix the extra/deleted and unnecessary lines
git add plugins/sf2_player/sf2_player.cpp
git commit # add a commit message
git push
```

I think that is it.  Then close out this pull request and open a new one with your dedicated branch so that your master branch remains even with upstream.  As a rule of thumb, always use a new branch when making pull requests.  This practice will save you grief down the road.

**Comment by midi-pascal** [comment]
@tresf Thank you so much for this step-by-step how-to cope with git. I will keep this at hand for the next contributions because I am not the kind of guy who ask the same question more than once :smile: 
Let's say git is really powerful but not very intuitive or user friendly...

**Comment by tresf** [comment]
> A last silly question: should/may I delete the branch I created before the PR is accepted/rejected?

Generally speaking, no, you'll leave it around so that you can adjust items before it is merged.  Once it is merged, GitHub will remind you at the bottom of the PR that it can be deleted.

> Thank you so much for this step-by-step how-to cope with git. I will keep this at hand for the next contributions because I am not the kind of guy who ask the same question more than once

I have the feeling we'll still need to go over squashing soon.  Squashing is a good way to do the same thing we did above and it is very common on PRs since after feedback and changes, we could have 20 commits that only change one line due to trial and error.  Squashing is the `pick`/`squash` steps I had listed above and work very well to cleanup rebasing.

The reason I had you create a dedicated branch was to also fix your master branch, but generally, you can squash stuff down and achieve the same effect without manually backing up and restoring code changes.

Last, thanks for taking the time to do this.  In my experience, when I hit a Git snag, I spend about an hour trying to correct it.  This is a necessary evil, and I hadn't used version control prior to Git, so I had to learn everything the hard way too.  Your efforts are greatly appreciated.

**Pull request closed without merging**
