### PR TITLE
Add automation flip icons

### LINKED ISSUE #2075: Automation Editor: Missing pixmap files
In automation editor, the pixmaps files associated with the buttons "Flip vertically" (flip_y.png) and "Flip horizontally" (flip_x.png) are missing in the default theme directory. (Master)

### PR DESCRIPTION
**Pull request by Umcaruje**
Fixes #2075.

Here's how they look:
image
 
I'll make the appropriate pull request with source files to [`LMMS/artwork`](https://github.com/LMMS/artwork) too.

### CODE REVIEW

**Comment by Spekular** [comment]
Sweet!

**Comment by Wallacoloo** [comment]
Tried your changes - looks good on my end. Not sure what the typical procedure is with theme changes though, so I'll let you or somebody else merge this when you're ready.

**Comment by tresf** [comment]
This is technically a bug since they were missing from the codebase.  Safe to merge, IMO. :+1:

**Comment by tresf** [comment]
P.S. The procedure last year was to run all theme changes past @diizy since he authored the 1.x theme.  He's been busy and mostly absent from the code as of recent months, so we have to step in and try our best to uphold his 1.x theme style, which I think @Umcaruje has done a great job on. :+1:

**Comment by Umcaruje** [comment]
These icons were based on @diizy's svg's, so they use the same gradients as all other icons. I think this should be merged.

**Comment by Wallacoloo** [comment]
These icons are unarguably better than having no icons, so I concur.

**Pull request merged**
