### PR TITLE
Fix regression where autosave function is off by default

### PR DESCRIPTION
**Pull request by zonkmachine**
Autosave regression https://github.com/LMMS/lmms/issues/181#issuecomment-299703956

Introduced here: https://github.com/LMMS/lmms/commit/901fea51d064df9fd2665c6b737f7a70ed18b4db

### CODE REVIEW

**Comment by tresf** [comment]
@zonkmachine thanks.  Although this fixes the problem in the UI, can you help explain what's happening in the config?  Is this value being stored incorrectly as  code looks backwards now. :)

**Comment by tresf** [comment]
Ok... I think I see what happened... @jasp00 complained about double-negatives in our variable names, but we don't currently seem to have a way to default an unconfigured property to `enabled`, right?

**Comment by zonkmachine** [comment]
I'm basically just copying the logic of the other 'default on' buttons. SetupDialog.cpp and I aren't really on speaking terms...

**Comment by zonkmachine** [comment]
Merge?


> but we don't currently seem to have a way to default an unconfigured property to enabled, right?

Yes, something like that. In any case I've never had an easy time when I've touched that file.

**Comment by tresf** [comment]
> Merge?

No unfortunately now the code is backwards, so the patch is masking the problem.

@jasp00's advice was pragmatic but impractical.  We either revert the variable naming to what the project uses and keep this type of patch, or spend the time necessary to have default-on in our config file.

**Comment by zonkmachine** [comment]
> We either revert the variable naming to what the project uses and keep this type of patch,

I didn't get this. 



> or spend the time necessary to have default-on in our config file.

Sorry. I don't have much time now.

**Comment by tresf** [comment]
I'm not sure how else to phrase this properly.... 

```cpp
m_enableAutoSave( !ConfigManager::inst()->value( "ui", "enableautosave" ).toInt() ),
```

This essentially says 
```cpp
m_enableAutoSave = !enableautosave;
```

These are the same conceptual concerns [@jasp00 raised](https://github.com/LMMS/lmms/pull/3088#pullrequestreview-20149999) in #3088.

There's likely a better way to handle this all in our `ConfigManager` class to actually fix the underlying problem of default int value is zero.  Alternately, we can go back to the old `disableautosave` verbiage and just let it be zero naturally, but the logic proposed in this PR is incorrect.

**Comment by tresf** [comment]
Ok... I'd appreciate a second set of eyes on this, but if what I'm observing is true, all of our booleans can never be true, which punishes anyone that wants a "default on" value without a "default off" name.

Here's a hacked proposal... 

Note, this has some implications... namely, it potentially enables `animateafp`, `displaydbfs` and `enableautosave` by default.  It's the wrong way, but illustrates the problem.

```diff
const QString & ConfigManager::value( const QString & cls,
					const QString & attribute ) const
{
	if( m_settings.contains( cls ) )
	{
		for( stringPairVector::const_iterator it =
						m_settings[cls].begin();
					it != m_settings[cls].end(); ++it )
		{
			if( ( *it ).first == attribute )
			{
				return ( *it ).second ;
			}
		}
	}
-	static QString empty
+	// Default enable flags to true
+	static QString empty = attribute.startsWith("enable") || 
		attributes.startsWith("display")  ||
		attributes.startsWith("animate") ? "1" : "";
	return empty;
}
```

The better proposal... add new function that accepts a default value when one can't be found... (pseudocode, untested)

```cpp
const QString & ConfigManager::value( const QString & cls, const QString & attribute, const QString & defaultVal ) const
{
	QString val = value(cls, attribute);
        return val.isEmpty() ? defaultVal : val;
}

**Comment by zonkmachine** [comment]
> Alternately, we can go back to the old disableautosave verbiage and just let it be zero blank -- resolving to zero -- naturally, but the logic proposed in this PR is incorrect.

So, just reverting 901fea51d064df9fd2665c6b737f7a70ed18b4db ?
I suggest you start a separate issue with the above proposed code. I'm not going to have time to implement anything like that here and now.

**Comment by tresf** [comment]
> So, just reverting 901fea5 ?

That was my original thought, but please read the [bottom of the post](https://github.com/LMMS/lmms/pull/3541#issuecomment-300361815), I provided a better fix that's only a few lines and allows us to keep the `enabled` flag.

**Comment by zonkmachine** [comment]
> That was my original thought, but please read the bottom of the post, I provided a better fix that's only a few lines and allows us to keep the enabled flag.

Still not within my time limit. What I can do is revert 901fea5. I won't have time to look any deeper into things right now and for a possible long time coming.

**Comment by tresf** [comment]
> Still not within my time limit. 

Someone else will have to tackle it then.  This PR is as good as a bug report since it contains the valid info.  We'll either supercede this will a new PR or use this PR directly for the code.

**Comment by tresf** [comment]
Superseded by https://github.com/LMMS/lmms/pull/3551.

**Pull request closed without merging**
