### PR TITLE
Haiku build fix.

### PR DESCRIPTION
**Pull request by devnexen**
related to ringbuffer, matching cmake settings to disable mlock for this platform.
Haiku does not support tls model as well.

### CODE REVIEW

**Comment by devnexen** [comment]
Little question. If there any plan to update rpmalloc (ie its current git hash is old and sets wrongly tls model, thus the runtime_loader fails to resolve when it starts but it had been solved since) ?

**Comment by JohannesLorenz** [comment]
About rpmalloc, we still have #4752 open. We should get that done, but this is blocked as long as we still support Ubuntu 14.04.

@devnexen Do you require an rpmalloc update to get LMMS run on Haiku?

**Comment by devnexen** [comment]
Right but isn't Ubuntu 14.04 EOL ? Anyway yes in that cas the compiler toolchain might be old for newer rpmalloc. Yes indeed I changed locally to make it work :-)

**Review by JohannesLorenz — APPROVED** [review]
Looks all good. I'll merge this now. The rpmalloc fix will remain delayed until #5696 is done.

**Comment by JohannesLorenz** [comment]
@devnexen for your info, rpmalloc is updated on master now.

**Pull request merged**
