### PR TITLE
Change the link of carlabase to SHARED and explicitly link carlarack and carlapatchbay to carlabase.

### LINKED ISSUE #2572: Carla plugin compiles fine but is not loaded in the synth menu
I compiled lmms-1.1.90 on fedora 23 64 bits. I use carla from git repo.
lmms compiles fine with carla (I can see carlabase.so and others in the install lib directory) but when I open lmms, carlarack and carla-patchbay are missing.

After some investigations, this is due to the fact that carlabase.so is compiled as a module and not as a shared library (maybe a change in cmake cause this - cmake 3.4.1 is shipped under fedora).
I changed the link of carlabase to SHARED (via a change in BuildPlugin.cmake) and explicitely linked carlarack and carlapatchbay to carlabase and everything went fine. The carla-rack and carla-patchbay and loaded in the synth menu of lmms.

### PR DESCRIPTION
**Pull request by ycollet**
A tentative commit to fix #2572 .

### CODE REVIEW

**Comment by Umcaruje** [comment]
Hi, could you amend your commit (`git commit --amend` and `git push -f`) to be a bit more descriptive please. Something like `change the link of carlabase to SHARED and explicitly link carlarack and carlapatchbay to carlabase`

**Comment by ycollet** [comment]
Is it OK ?
I hope I haven't made any mistake ...

**Comment by Umcaruje** [comment]
>Is it OK?

You changed the title of your PR, and not your commit message. You need to do this from the terminal:

``` bash
# cd to your repo
git commit --amend
# This will open up a nano instance (usually). 
# Edit the commit text and press Ctrl + X and then just press Y and afterwards enter
# Then you need to force push 
git push -f
```

**Comment by ycollet** [comment]
OK, new tentative for the commit amend.

**Comment by Umcaruje** [comment]
:+1: Tagging @falkTX since he's the author of carla.

**Comment by falkTX** [comment]
Seems fine to me if it builds.

**Comment by Umcaruje** [comment]
>Seems fine to me if it builds.

Ok, I'll build @ycollet's branch and test it out.

**Comment by Umcaruje** [comment]
Ok, built the branch, carla builds fine, and did a quick test ( Put carla in the song editor, load an instrument and play a few notes), and all works fine. FalkTX gave the green light, so I'm merging this.

**Comment by tresf** [comment]
@Umcaruje thanks for following up and testing this. :+1:

**Pull request merged**
