### PR TITLE
Fix broken data file upgrade

### PR DESCRIPTION
**Pull request by M374LX**
Addresses the data file upgrade breakage introduced in #6226.

### CODE REVIEW

**Review by JohannesLorenz — CHANGES_REQUESTED** [review]
Code review finished. Issues:

* In `DataFile.cpp`, `ELEMENTS_WITH_RESOURCES` still uses `sampleclip`.

Testing is required after that.

**Review by JohannesLorenz — APPROVED** [review]
Sorry, last time I have forgotten to check the headers. But you seem to have them complete now, too. LGTM. Now, testing review required.

**Comment by JohannesLorenz** [comment]
Test review minimum:

The following should work with all kinds of clips (Automation Clip, BB Clip, MidiClip (these are the clips with MIDI notes), SampleClip):

* drag/drop a clip
* save a file with that clip type
* load a file (which you created with this PR) with that clip type
* load a file (which you did not create with this PR) with that clip type

**Comment by M374LX** [comment]
Another problem found: when dragging and dropping a sample clip from the Song Editor to the Beat+Bassline Editor, it does not work.

**Comment by JohannesLorenz** [comment]
Oh, OK. Then I'd say let's merge this? It can't get much worse :smiling_face_with_tear:

**Comment by M374LX** [comment]
For me, it is ready to be merged.

**Pull request merged**
