### PR TITLE
Translation Fixes (Continuation of #4482)

### PR DESCRIPTION
**Pull request by zonkmachine**
Fixes https://github.com/LMMS/lmms/issues/5032

Fixing some formatting issues in LMMS-1.2 caused by translations.
Continuation of https://github.com/LMMS/lmms/pull/4482

Problematic translation strings replaced with `<translation type="unfinished"/>` as mentioned [here](https://github.com/LMMS/lmms/issues/5032#issuecomment-531496557) except for the [polish translation](https://github.com/LMMS/lmms/compare/stable-1.2...zonkmachine:translationfixes2?expand=1#diff-f644f02e8f755b7cb39a896fa278355fR3005-L3005) where I removed one of the words. I don't speak polish. Not a bit.

### CODE REVIEW

**Review by liushuyu — COMMENTED** [review]
>This is leftover from #4482. I can fix it by going over the translations again and just removing the borked lines but maybe this is best handled on Transifex?

Yes, these changes will be eventually got overridden by Transifex. However, removing translations is not a decent way to do this since you will always find some languages got extra long strings somewhere.

**Comment by zonkmachine** [comment]
> However, removing translations is not a decent way to do this since you will always find some languages got extra long strings somewhere.

What is the way to go about this then? Report the problematic lines on Transifex instead?
I won't have time to dive into that site. I tried once and we didn't seem to be compatible...
Dow we merge back translations from Transifex for lmms-1.2 ?

**Comment by qnebra** [comment]
For me @liushuyu it was some kind of lazy translation. Translate without caring about avalaible space and line lenght.

**Comment by liushuyu** [comment]
>Even if they will be removed later by transifex it will fix the formatting issues in lmms-1.2.1 that is  being prepared.

You can merge this for now.

>Should these strings be reported on Transifex each one separately and then fixed by the translators?

You can open an issue on Transifex.

**Comment by zonkmachine** [comment]
> You can open an issue on Transifex.

OK. Is this one issue per string? I don't find a general issue tracker there.

**Comment by liushuyu** [comment]
>Is this one issue per string?

Yes

I don't find a general issue tracker there.

>There's a per-language tracker (discussion section). This is where Transifex does not work well.

**Comment by zonkmachine** [comment]
@liushuyu I have fixed the Swedish strings on transifex but for the rest I don't think I have access to even comment on the other languages (and I probably shouldn't have... :) )
I have found the LMMS translatin team however and will start a conversation there. Thanks for your patience!

**Comment by zonkmachine** [comment]
> I have found the LMMS translation team 'discussions page' however and will start a conversation there.

https://www.transifex.com/lmms/teams/61632/discussions/19385/
Links and Pics and editing the post doesn't seem to work though.

**Pull request merged**
