### PR TITLE
Use new carla-native-plugin library

### PR DESCRIPTION
**Pull request by falkTX**
Also fixes build with latest carla (which will be 2.0 soon)

Should be pushed to stable-1.2 branch too, but there will be conflicts to resolve for that.
@tresf can I let you handle that?

### CODE REVIEW

**Comment by PhysSong** [comment]
`stable-1.1` is no longer used, so you should open a PR against `stable-1.2`.
I think @tresf can handle conflicts. If not, I can help you resolve them.

**Comment by falkTX** [comment]
stable-1.1 is still the latest stable release of LMMS available, and it is simply not that that is no longer used - I am using it myself and everyone with kxstudio repos.
Without the patch, the build fails against latest carla.
This is a bugfix, not a new feature. Please merge.

**Comment by PhysSong** [comment]
BTW, won't it make the build fail with old version of Carla?

**Comment by falkTX** [comment]
no, as the library it uses was changed. it no longer links against the full carla standalone lib, but only against the exported plugin version (libcarla_native-plugin.so).
it makes a lot more sense to link against this new object file.

as it is now, stable-1.1 finds carla-standalone and then fails to build.
the patch fixes this, among other things.

**Comment by PhysSong** [comment]
I meant there's no fallback logic for old versions. It looks like a regression to me. Can we try `carla-standalone` if the old version of Carla is detected?
> stable-1.1 finds carla-standalone and then fails to build.

I can't reproduce it. Do you have a build log with the failure?

**Comment by falkTX** [comment]
treat it as a regression if you wish, I feel like now it is doing things proper.
the symbols it uses are all defined in a single header file, which is the one also used when exporting the library.
the old behaviour was hacky, experimenting with getting it to work.
now with carla going stable (2.0), it was time to clear up the hacks and make things work properly.

I dont have the logs with the failure, but the error only happens due to -Werror.
You need latest git of carla (from maximum 2 days ago) to get the new header file and library.

**Comment by tresf** [comment]
I have mixed feelings about this landing on the `stable-1.1` branch.  First of all, I really don't care because the branch is stale, unmaintained and doesn't provide any binaries to our website, so the impact is only downstream and I can't speak on behalf of downstream + Carla.  @falkTX perhaps you can shed some insight on this?

So the impact of merging this to `stable-1.1` is:
 * This would only impact distros that ship 1.2 (which most do) that would pull from `HEAD` of the `stable-1.2` branch.   Does this ever happen?  I can't imagine this would be common, instead they'd pull from the `1.1.3` release.  Do we need to ship a `1.1.4` version?  It would be for Carla only as the Windows and Mac builds are not impacted by this change.
 * What I don't truly understand is how the distros get Carla to begin with.  I'm familiar with the Debian/Ubuntu technique but even then I'm not exactly sure how it's provided as I don't think the major distributions have Carla support baked in.  If this is only to satisfy the KXStudio's build process, then it seems like a sane change.
* @PhysSong's concerns about regression handling seem valid but only if the distribution of these libraries happens separately and I can't speak on behalf of those distros.  The ones that come to mind are Fedora and Arch, which we get a lot of bug reports for -- including Carla bug reports (#4156, #4515, #3452, #3218, #2213, #2212, #2549, #2543, #1444, #1221, #1201, #1199).

What I think would be more responsible of a change -- albeit leaving cruft into the Carla build system -- is for @falkTX to leave the old library around and deprecate it off sanely instead of putting this decision on us at LMMS.  The justification for this is we've [worked with package maintainers that require a version bump to receive a change](https://github.com/LMMS/lmms/issues/4197#issuecomment-415896881) so I'd like to be cognizant of that.

@falkTX thoughts welcome. :)

**Comment by falkTX** [comment]
thanks for the reply.

I understand the situation, I was hoping 1.1 would still be maintained in a way.
it is the current stable branch, and the one I am still using. but it is fine that it is not supported anymore.
In such cases, then **I really recommend taking out -Werror, and that is it.**
Without that flag, carla will keep building and working just fine with the current code.

Most distros don't have Carla afaik.
I know Arch does, I know the maintainer for the packager and we meet in Berlin from time to time, so I can request updates in person :P
Some Fedora and Gentoo audio overlay/repos/external-sources contain it too, but I dont know how those work.
Debian does not have it, neither does Ubuntu.

@tresf could you please merge this patch into your lmms-carla-osx PR?
I think pushing to 1.2 branch right now is a bit pointless, if you will have conflicts with it right away, so you will have to resolve them anyway.

**Pull request closed without merging**
