### PR TITLE
Add X11EmbedContainer Qt5 port

### PR DESCRIPTION
**Pull request by lukas-w**
Alternative solution for issue #2855 (other PRs trying to solve the same issue are ~~#2856~~ #3497  and #3295). I ported most of `QX11EmbedContainer` from Qt4 to Qt5 for this. I haven't looked at the code in detail, so it's quite possible most of it is not even used in our case.

It'd be great if we could get some more test results for this. :)

### CODE REVIEW

**Comment by Lukas-W** [comment]
I pushed some more commits, which fixes Qt's [`XEMBED`](https://specifications.freedesktop.org/xembed-spec/xembed-spec-latest.html) implementation, which apparently has always been broken. See for example [QTBUG-36446](https://bugreports.qt.io/browse/QTBUG-36446) and related [Wine bug 35347](https://bugs.winehq.org/show_bug.cgi?id=35347) (Wine even included a workaround for our VSTs to work).

This also fixes a long-standing issue with VST GUIs, which is sub-elements like combobox dropdowns appearing in the wrong screen position, most of the time outside of the VST subwindow. Wine has full XEMBED support, and with the protocol being fixed on our side, screen positions seem to get mapped to the embedder's coordinates properly now:

image

This is even broken with Qt's `createWindowContainer`, which is why I closed #3295 in favor of this PR. The only issue I found with this so far is that clicking inside the VST will not bring the subwindow to the front.

Some testing would be useful to know if we should pursue this approach further.

**Comment by Umcaruje** [comment]
This PR is failing travis, and going external window is better in my opinion than porting x11embedcontainer to qt5.

So fwiw I vote we close this PR out in favour of #3497

**Comment by BaraMGB** [comment]
>This PR is failing travis, and going external window is better in my opinion than porting x11embedcontainer to qt5.

>So I vote we close this PR out in favour of #3497

I agree.

**Comment by tresf** [comment]
> external window is better in my opinion than porting x11embedcontainer to qt5.

Before we make that decision, please consider #3532 which would make both behaviors possible.  The decision to merge should pivot on the status of #3532.

**Comment by BaraMGB** [comment]
@tresf  On MS Windows VSTs aren't subwindows. #3497 would be more consistent. Also single window GUI would be easier to implement.

**Comment by Lukas-W** [comment]
> This PR is failing travis

I've been waiting with fixing Travis because I hoped to get some testing first. So Travis status depends on this PR being accepted, not vice-versa as you seem to imply.

> and going external window is better in my opinion than porting x11embedcontainer to qt5

I'm quite fond of being able to have everything inside one window, especially on a single monitor. Are you sure we want to remove that feature?

> On MS Windows VSTs aren't subwindows.

Well that's just not true. Or has it changed recently?

**Comment by BaraMGB** [comment]
>>    On MS Windows VSTs aren't subwindows.

>Well that's just not true. Or has it changed recently?

Sorry my fault.

**Comment by Lukas-W** [comment]
> Also single window GUI would be easier to implement.

@BaraMGB Could you elaborate on this one? Why would it be easier when we don't have the ability to embed plugins?

**Comment by BaraMGB** [comment]
In my understanding of the single window GUI we want to get rid of any MDI subwindows. Our native plugins would be organized into racks. External plugins would be realized in external windows.

**Comment by karmux** [comment]
This looks very stable and is working perfectly.

I also like that for effects plugins a GUI is shown already when clicking on `Controls` in the `Effects Chain`. Previously there were a small intermediate window and it required one extra click. Now this intermediate window and VST GUI are merged :+1:

**Comment by Lukas-W** [comment]
@karmux Thanks for testing.

I moved the `X11EmbedContainer` implementation to its own repository (https://github.com/Lukas-W/qt5-x11embed) and included as a git submodule. Building it using CMake's `add_subdirectory` for now, though `ExternalProject_Add` may be a better choice.

Fixed some warnings that caused the Travis build to fail.

**Comment by Umcaruje** [comment]
After your comments in the other pull request, I now see this is really the way to go. I'll see to test this in the following days, because we really need this for AppImages and the 1.2 release :+1:

**Comment by Umcaruje** [comment]
Ok, so I just built the branch and the VST windows don't seem to load at all. I'm on elementary OS Loki, and I'm using wine 1.8. 
This is the output in my terminal:
```
fixme:heap:RtlSetHeapInformation 0x240000 0 0x23fe10 4 stub
fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
fixme:advapi:RegisterEventSourceW ((null),L"Bonjour Service"): stub
fixme:advapi:ReportEventA (0xcafe4242,0x0004,0x0000,0x00000064,(nil),0x0001,0x00000000,0x54df40,(nil)): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000064,(nil),0x0001,0x00000000,0x69c90,(nil)): stub
fixme:winsock:WSAIoctl WS_SIO_UDP_CONNRESET stub
err:winsock:WSAIoctl -> _WSAIO(IOC_WS2, 23) request failed with status 0x2733
fixme:iphlpapi:CreateIpForwardEntry (pRoute 0x54e298): stub
fixme:advapi:ReportEventA (0xcafe4242,0x0004,0x0000,0x00000064,(nil),0x0001,0x00000000,0x54df40,(nil)): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000064,(nil),0x0001,0x00000000,0x69c90,(nil)): stub
fixme:service:svcctl_EnumServicesStatusW resume index not supported
fixme:service:svcctl_EnumServicesStatusW resume index not supported
fixme:advapi:ReportEventA (0xcafe4242,0x0004,0x0000,0x00000064,(nil),0x0001,0x00000000,0x54df40,(nil)): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0004,0x0000,0x00000064,(nil),0x0001,0x00000000,0x69c90,(nil)): stub
fixme:netapi32:NetGetJoinInformation Semi-stub (null) 0x54dfb8 0x54dfb0
fixme:winsock:WSAIoctl WS_SIO_UDP_CONNRESET stub
fixme:winsock:WSAIoctl WS_SIO_UDP_CONNRESET stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x33fd2c 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x29cc290 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x29cc1dc 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x29cc03c 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x29cd1d4 1 C) semi-stub
fixme:service:scmdatabase_autostart_services Auto-start service L"Tpkd" failed to start: 3
fixme:msvcrt:type_info_name_internal_method type_info_node parameter ignored
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x29c902c 1 C) semi-stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x29c8fe0 1 C) semi-stub
fixme:ntdll:NtLockFile I/O completion on lock not implemented yet
fixme:advapi:ReportEventA (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x54d450,(nil)): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x69c90,(nil)): stub
err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Received from 192.168.1.11:5353   16 umpc.local. AAAA FE80:0000:0000:0000:DD1F:78FE:CBD5:D1ED"
fixme:advapi:ReportEventA (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x54d450,(nil)): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x69c90,(nil)): stub
err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: ProbeCount 2; will deregister    4 umpc.local. Addr 192.168.1.11"
fixme:advapi:ReportEventA (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x54d360,(nil)): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x69c90,(nil)): stub
err:eventlog:ReportEventW L"Local Hostname umpc.local already in use; will try umpc-2.local instead"
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x29c787c 1 C) semi-stub
fixme:msvcp:locale_operator_not_equal (0x29c76d8 0x7e6ee118) stub
fixme:msvcp:locale_operator_not_equal (0x29c7680 0x7e6ee118) stub
fixme:msvcp:locale_operator_not_equal (0x29c76f8 0x7e6ee118) stub
fixme:msvcp:locale_operator_not_equal (0x29c7730 0x7e6ee118) stub
fixme:msvcp:locale_operator_not_equal (0x29c7730 0x7e6ee118) stub
fixme:msvcp:locale_operator_not_equal (0x29c7730 0x7e6ee118) stub
fixme:msvcp:locale_operator_not_equal (0x29c7708 0x7e6ee118) stub
fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (0x29cd204 1 C) semi-stub
unique ID: S1Vs
RemotePlugin::DebugMessage: inputs: 0  output: 2
RemotePlugin::DebugMessage: creating editor
RemotePlugin::DebugMessage: editor successfully created
RemotePlugin::DebugMessage: failed getting shared memory
fixme:advapi:ReportEventA (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x54d450,(nil)): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x69c90,(nil)): stub
err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Received from 192.168.1.11:5353   12 11.1.168.192.in-addr.arpa. PTR umpc.local."
fixme:advapi:ReportEventA (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x54d450,(nil)): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x69c90,(nil)): stub
err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Unexpected conflict discarding   14 11.1.168.192.in-addr.arpa. PTR umpc-2.local."
fixme:advapi:ReportEventA (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x54d450,(nil)): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x69c90,(nil)): stub
err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Received from 192.168.1.19:5353   12 19.1.168.192.in-addr.arpa. PTR umpc.local."
fixme:advapi:ReportEventA (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x54d450,(nil)): stub
fixme:advapi:ReportEventW (0xcafe4242,0x0001,0x0000,0x00000064,(nil),0x0001,0x00000000,0x69c90,(nil)): stub
err:eventlog:ReportEventW L"mDNSCoreReceiveResponse: Unexpected conflict discarding   14 19.1.168.192.in-addr.arpa. PTR umpc-2.local."
```

And I just get an empty plugin window like this 
image


Closing and reopening doesn't fix the problem.

**Comment by lukas-w** [comment]
@Umcaruje I installed elementary OS in a VM to test this but I can't reproduce what you experience. Tried with Synth1 1.12, Qt 5.5.1, wine 1.6 (which is the version elementary ships provides) and wine 2.0.2 from WineHQ's official repo. Where did you get wine 1.8 from?

**Comment by Umcaruje** [comment]
>Where did you get wine 1.8 from?

Oh shit, looks like I was using a deprecated old wine repo. I'll update and retest.

**Comment by karmux** [comment]
This should be included in 1.2.0-rc4 IMHO.

**Pull request closed without merging**
