### PR TITLE
Set Stk::showWarnings() via LMMS_DEBUG

### PR DESCRIPTION
**Pull request by zonkmachine**
Fixup of #3172

### CODE REVIEW

**Comment by tresf** [comment]
@zonkmachine I was going to comment on this before merge... 

We should really consider configuring this debug value into a header to avoid unnecessary pre-compiler tags all over our code.

Perhaps a nice home for it would be here: https://github.com/LMMS/lmms/blob/master/src/lmmsconfig.h.in

**Comment by tresf** [comment]
Sorry... bad example... `LMMS_VERSION` is a better example.  https://github.com/LMMS/lmms/blob/master/src/lmmsversion.h.in.  Note how the logic in the code can [use it directly](https://github.com/LMMS/lmms/blob/master/src/gui/AboutDialog.cpp#L43), rather than changing the precompile behavior.  This means we could do something like:  `Stk::showWarnings(LMMS_DEBUG)` instead. :)

**Comment by tresf** [comment]
Also, side-note... probably overkill to have both `lmmsconfig.h.in` as well as `lmmsversion.h.in`  We should consider consolidating these. `/offtopic`.

**Comment by zonkmachine** [comment]
> This means we could do something like: Stk::showWarnings(LMMS_DEBUG) instead. :)

OK, interesting so...

```
#cmakedefine LMMS_DEBUG 1
#ifndef LMMS_DEBUG
#define LMMS_DEBUG 0
#endif

...

Stk::showWarnings(LMMS_DEBUG);
```

**Comment by tresf** [comment]
@zonkmachine poorly documented as many of the `cmake` features, but I believe `#cmakedefine01 LMMS_DEBUG` will do the trick per https://github.com/adobe/webkit/blob/master/Source/cmakeconfig.h.cmake#L4

Yes, you read that right, `#cmakedefine01` :)

**Pull request merged**
