### PR TITLE
Grey out muted patterns in the BB editor

### LINKED ISSUE #939: Pattern editor does not gray out when other track is solo-ed
winxp32
Solo a track: 
Only tracks made in piano-roll, greys-out when one intrument is solo'ed. BB-track-types does not grey-out
Logical -no errors

### PR DESCRIPTION
**Pull request by Umcaruje**
Fixes #939

screenshot from 2016-03-18 23 52 39

### CODE REVIEW

**Comment by tresf** [comment]
Spelling: `rectrangle`

Well, it does the trick simple and elegantly for sure, but it's [not the same technique we use for other paint events](https://github.com/LMMS/lmms/blob/master/src/gui/AutomationPatternView.cpp#L268:L269), so if we decided to merge, I vote we do so with the intention of eventually fixing the steps draw code down the road to use techniques closer to what we're already using.

i.e. Perhaps a technique similar to the [volume drawing code](https://github.com/lmms/lmms/blob/master/src/tracks/Pattern.cpp#L1130:L1139) could tackle this.

**Comment by Umcaruje** [comment]
Well, that would require making another pixmap for muted steps, and I would probably again end up drawing a semi-transparent rectrangle over the steps.

>Well, it does the trick simple and elegantly for sure, but it's not the same technique we use for other paint events,

But you gotta admit that these patterns are nothing alike the other ones we have. While all other TCO's are static, the user interacts with these ones and they have a complex drawing code. We can't really use the methods from other TCO's on here.

**Comment by tresf** [comment]
> We can't really use the methods from other TCO's on here.

I think eventually we can use a similar technique, but there's no rush and this can be merged at any time.

The fact that we use pixmaps for the steps may not even be needed (and may help resolve https://github.com/HDDigitizerMusic/lmms-alt-theme/issues/18) but the long-term issue with drawing something over the notes is we'll end up with slightly inconsistent L&F since blending would occur.

Again, minor and not worth holding up this great addition, but a worthy discussion as we continue to cleanup theme support.

**Comment by tresf** [comment]
That said, merging. :+1:

**Comment by Umcaruje** [comment]
:+1:

**Pull request merged**
