### PR TITLE
Applied Proper Case To Misc Text Items

### PR DESCRIPTION
**Pull request by miketurn**
@liushuyu
Hopefully I am doing this correctly

### CODE REVIEW

**Comment by liushuyu** [comment]
I think we could merge these PRs together?

**Comment by tresf** [comment]
@liushuyu @miketurn is not yet familiar with full-fledged-git, so he's using the browser for each pull request.

@miketurn @liushuyu is correct. Even if you use the browser you can still put these all in one PR by editing on your own branch and then issues one single PR containing all of the changes.

If you get even more involved, we can help you do a formal commit from the PC.

https://github.com/miketurn/lmms/tree/patch-1

**Comment by miketurn** [comment]
@tresf  @liushuyu (I apologize)
Damn that is what I was afraid of, I am not sure what I am doing, and the terminology is over my head.
So you are saying that the process where I am editing the cpp files is okay, but when I create a "pull request" I can combine all the edits I make into one "pull request" under the title "patch 1"?
Is this correct?

> by editing on your own branch and then issues one single PR containing all of the changes.

Question is how do I link my patch 2 - 5 to patch 1?

Thank You, again I am sorry

**Comment by tresf** [comment]
> So I currently have about 6 patches and all of these should be linked to one "pull request"?

Yes, ideally.

> when I create a "pull request" I can combine all the edits I make into one "pull request".

Correct.  If you're using the web, each change is considered a `commit` (a change).  The commit can be one file or several but since you're using the web, each change will be a single commit (this is fine for now).

Rather than clicking the "Edit" pencil in LMMS, you can go to https://github.com/miketurn/lmms and select the branch (`patch-1` is a branch, it's just a snapshot in time.  There are a bunch of others too, most stale snapshots that our team haven't cleaned up).

So you want to edit all of the files directly on your copy.  Using the web, each edit (or save) will put another commit on your copy.  Once you're all done, you can manually request they're brought in, all in one request.  We call this a PR -- or "Pull Request".  It's a confusing term, but it's what GitHub calls it.

Anyway, these concepts all make it possible to contribute and they won't change from project to project, so they're valuable to know.

If you prefer to do everything from your PC, GitHub has a desktop client which makes it a bit easier to understand.  We really like the Pull Requests because they allow us to comment on each change and offer feedback prior to accepting it into our code.  Putting all of these minor changes in a single request will make it easier to comment on, easier to merge in. :)

**Comment by miketurn** [comment]
@tresf 
Thank you for this explanation, I think I understand but I do have a couple of questions maybe you or someone else could help me with.

1.) The method I started with created a "patch/branch' for each fix that I made so I have a 6 of them.  Is there a way that I can bring patch 2-6 into my patch 1 so I can keep them all in one patch (patch 1) and then do a pull request of my patch 1?  Or do I have to redo my fixes made to patch 2-6 in my patch 1?

2.) After I create a pull request for my patch 1 and I let liushuyu know about it, he will merge my patch 1 into the "master" and then closes my pull request letting me know that it has been completed?

As you mentioned, I will close this pull request (patch 5) once I receive your answer, I just didn't want to close it because it contained your instructions.

Thank You for your help, sorry to take up your time.

**Comment by tresf** [comment]
> Is there a way that I can bring patch 2-6 into my patch 1 so I can keep them all in one patch (patch 1) 

Yes, just navigate to your [`patch-1`](https://github.com/miketurn/lmms/tree/patch-1) branch and edit them there.  It will all be reflected in the already open pull request for that branch.

>  will close this pull request (patch 5) once I receive your answer, I just didn't want to close it because it contained your instructions.

Don't worry, the instructions won't be lost if this is closed. :)

**Comment by miketurn** [comment]
@tresf 
> Yes, just navigate to your patch-1 branch and edit them there. It will all be reflected in the already open pull request for that branch.

So in order to get my edits that I completed that saved in PATCH 2-6, I will have to REDO them in patch 1? 
Or is there a way to MOVE each of them to PATCH 1?

**Comment by tresf** [comment]
You can pull request them on your own branch back in (see the compare button).  Otherwise, you'd need command line or hand edit then again.

**Pull request closed without merging**
