### PR TITLE
Zooming with mouse wheel center

### PR DESCRIPTION
**Pull request by Premik**
Fixes the #2303

### CODE REVIEW

**Comment by Umcaruje** [comment]
Hi Premik, thanks for contributing to LMMS, I tested this out and it works well, and the code is by the guidelines, but can you implement this in the automation editor as well, so we have consistent UX over the software?

**Comment by Premik** [comment]
@Umcaruje I've noticed this too. But it is another bug or missfeature which was there before my change. Somehow the automation track doesn't expand to new bars as the control poins are being added (like the other editors do). And if you zoom in a bit more the Automation editor won't let you scroll after the Pattern end (I bet it would be the Bar no. 4 in your case). Try with shift+mouse wheel for example. You can workaround this by expanding the Pattern in the song editor.

 Maybe a picture would be better. Below the first automation track with the long Pattern is ok. But the second one is dodgy.
automationscroll


@zonkmachine Can you provide more details about that Piano Roll issue?

**Comment by PhysSong** [comment]
According to the [`QAbstractSlider` documentation](http://doc.qt.io/qt-5/qabstractslider.html#value-prop), it looks like a problem with scrolls' range.

**Comment by Premik** [comment]
@PhysSong True. The zooming would center to the cursor as far as it is possible to do so. I think that is where the confusion came from. For example when zooming to some bars at the very beginning or very end of a clip those can never be in the middle of the screen (where the mouse would be).
This works exactly the same way as selecting the zoom level from the top-left drop down first and then scrolling with the scroll-bar. And I don't think it is something that should be changed.

For the automation editor I suggest to open separate ticket and not mix it with this one. As those are not related.

**Comment by tresf** [comment]
@Umcaruje, this PR shows 2 changes requested.  Is there anything remaining before merging?

**Comment by zonkmachine** [comment]
> @Umcaruje I've noticed this too. But it is another bug or missfeature which was there before my change. Somehow the automation track doesn't expand to new bars as the control poins are being added (like the other editors do). And if you zoom in a bit more the Automation editor won't let you scroll after the Pattern end (I bet it would be the Bar no. 4 in your case). Try with shift+mouse wheel for example. You can workaround this by expanding the Pattern in the song editor.

Could have been this I saw. If the rest of you are happy with this then go ahead and merge it.

**Comment by Wallacoloo** [comment]
Just merged this locally and gave it a try - impressively it's still working fine with no merge conflicts even after 8 months. It's undeniably better than what we have in place right now - I feel we can do whatever further work is needed to improve zoom behavior in the automation editor and piano roll sometime down the road after merging.

@Umcaruje Github has this marked as not ready to merge because "Umcaruje requested changes". This is a useful Github feature that I don't want to blow off - but you didn't reply back in November when tresf asked if you were happy to merge it. I'll give you another chance to speak up, otherwise I'm going to merge this in a few days.

**Comment by Umcaruje** [comment]
Sorry about this, I completely forgot about this PR. OP’s explanation for the behavior i expirienced is good I’m merging.

**Comment by Wallacoloo** [comment]
@Umcaruje No worries. Thanks for reviewing it.

@Premik Thanks for the contribution! (And sorry we let it sit here inactive/unmerged for so long >.<)

**Pull request merged**
