### PR TITLE
Delay and Flanger, removed noise from delay when automating length

### PR DESCRIPTION
**Pull request by curlymorphic**
The original delay code, was setting it read index relative to the length
of the delay. This fixes that, now when the length is changed the read
index stays in the correct place in the buffer.

### CODE REVIEW

**Comment by tresf** [comment]
@curlymorphic does this have a bug associated with it?  Also, are there going to be any significant compat issues introduced with this patch?  I think I missed the history on this one. :)

**Comment by curlymorphic** [comment]
The code currently in place  calculates the read point, using the length, This has the undesired effect of moving the "Play head" when the length is adjusted, causing a horrid sound. This effect was amplified with the inclusion of the x-y pad on the delay effect, where the user is now encouraged to automate the delay length.

The audio will sound the same with these plugins while the length is not automated, and will remove the "Buzzy scratchy sound" during automation.

**Comment by tresf** [comment]
@curlymorphic thanks.  So if no one is intentionally using the horrid sound in their song, no impact expected.  :+1:

**Comment by curlymorphic** [comment]
:+1:

**Pull request merged**
