### PR TITLE
Wrap resource urls in double quotes

### PR DESCRIPTION
**Pull request by anytizer**
1. Wrap resource URLs in double quotes so that IDEs treat these values as string.
2. alternate-background-color: #111314; from: #6822: Failing css line fix only from this PR

### CODE REVIEW

**Comment by DomClark** [comment]
Should the classic theme be updated too?

**Comment by anytizer** [comment]
It is good to get them updated. But these changes are purely for editor/IDEs only, that will properly colorate values while editing editing them.

**Comment by DomClark** [comment]
Sorry if I was unclear - what I meant was: should the same changes be applied to the classic theme too? It also has some unquoted resource URLs.

**Comment by anytizer** [comment]
Yes, they should be changed in classic theme too.
I have sent another PR for that.

**Comment by zonkmachine** [comment]
> I have sent another PR for that.

Those changes belongs to this PR. When you add changes to a branch that has been made into a PR like this one, when you commit the changes and do another push, the changes are added here. No need for a separate PR.

**Review by zonkmachine — APPROVED** [review]
Looks good to me

**Review by DomClark — APPROVED** [review]

**Pull request merged**
