### PR TITLE
Support VST windows on Qt5

### LINKED ISSUE #2855: VSTi plugins don't show in Subwindow on Qt5 build (probably only X11)
screenshot_20160616_145731

Qt 5 bug:

the vst window will not be caught by the subwindow. With Qt4 we use QX11EmbedContainer for catching the vst window in our subwindow. QX11EmbedContainer is gone in Qt5. 

https://github.com/LMMS/lmms/blob/master/plugins/vst_base/VstPlugin.cpp#L228

```

#ifdef LMMS_BUILD_LINUX
    if( m_pluginWindowID == 0 )
    {
        return;
    }

    m_pluginWidget = new QWidget( _parent );
    m_pluginWidget->setFixedSize( m_pluginGeometry );
    m_pluginWidget->setWindowTitle( name() );
    if( _parent == NULL )
    {
        vstSubWin * sw = new vstSubWin(
                    gui->mainWindow()->workspace() );
        if( isEffect )
        {
            sw->setAttribute( Qt::WA_TranslucentBackground );
            sw->setWindowFlags( Qt::FramelessWindowHint );
            sw->setWidget( m_pluginWidget );
#if QT_VERSION < 0x050000
            QX11EmbedContainer * xe = new QX11EmbedContainer( sw );
            xe->embedClient( m_pluginWindowID );
            xe->setFixedSize( m_pluginGeometry );
            xe->show();
#endif
        } 
        else
        {
            sw->setWindowFlags( Qt::WindowCloseButtonHint );
            sw->setWidget( m_pluginWidget );

#if QT_VERSION < 0x050000
            QX11EmbedContainer * xe = new QX11EmbedContainer( sw );
            xe->embedClient( m_pluginWindowID );
            xe->setFixedSize( m_pluginGeometry );
            xe->move( 4, 24 );
            xe->show();
#endif
```

### PR DESCRIPTION
**Pull request by jasp00**
This fixes #2855, but subwindows are not used. It is a simpler alternative to #3475, uses separate windows like ZynAddSubFX, and unifies Windows and Linux behavior. Since there is no embedding, more clients are supported. The inability to embed native windows properly is likely because of Qt; the embedding implementation is left, just in case Qt is fixed.

This is the continuation of #2856, but disables FluidSynth because of #3490. You may reenable it prior to merging, but I recommend you not to do so.

### CODE REVIEW

**Comment by tresf** [comment]
I've always been fond of the separate window idea if that's what gets decided.

FYI, I've created a wiki for re-enabling SF2: https://github.com/tresf/lmms/wiki/Bollocks

**Comment by BaraMGB** [comment]
> I've always been fond of the separate window idea if that's what gets decided.

👍 I really hope this will make it!

**Comment by karmux** [comment]
I really like that I can move VST windows to another monitor. Didn't find any problems or glitches yet.

Few VSTs due to whatever reason always used to dissapear step by step when clicking on them (#2037). With this PR I don't have that issue any more. I also hope that this will get merged to master.

**Comment by Umcaruje** [comment]
I think this should be targeted at stable-1.2 so we finish the switch to Qt5 for all platforms. I also welcome the external window approach, will make workflow with VST's easier than before 👍

**Comment by karmux** [comment]
I've been running on this PR for a month now and haven't noticed any regression with variety of VSTs. This is safe to add into 1.2.

**Comment by Umcaruje** [comment]
@jasp00 is there anything left to add to this PR? would you change the base branch to stable-1.2?

**Comment by zonkmachine** [comment]
In response to: da99d75

Upstream fix for libfluidsynth license issue.
https://github.com/FluidSynth/fluidsynth/pull/177

**Comment by tresf** [comment]
@zonkmachine thanks for the link.  Probably better placed in #3490, as any @jasp00 PR should already have the sf2 enabled until this issue is settled.

In regards to VST + Qt5.... Since @jasp00 seems to be away, I'd like to defer this decision to @Lukas-W.  At a glance, it appears we can bundle a [newer Qt5 version](https://github.com/probonopd/lmms/commit/dc9fd086e344e842613ab45623ed96246ab58e77#diff-354f30a63fb0907d4ad57269548329e3R7) using `sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y`.

**Comment by BaraMGB** [comment]
The thing is, a Vst-mdi-subwindow is pointless in a single window GUI. 

If it's our goal to have the single window GUI then ‎we should work towards.

**Comment by tresf** [comment]
Here's a Qt5.8 `.AppImage` containing this patch for testing https://github.com/tresf/lmms/releases/download/v1.2.0-rc4/lmms-1.2.0-rc.vstwindow-linux-x86_64.AppImage

**Comment by karmux** [comment]
I see that VeSTige icons are missing in this AppImage. This was introduced by #1891 and fixed by #3501 and #3554.

**Comment by tresf** [comment]
@karmux this isn't a clean merge, the branch was never rebased so the AppImage likely has some regressions.

**Comment by Lukas-W** [comment]
> I'd like to defer this decision to @Lukas-W

I'm a bit biased of course because I wrote #3475 and I would not have written it if I didn't think it was the way to go. But I'll try to explain my reasoning by referring to @BaraMGB's comment:

> The thing is, a Vst-mdi-subwindow is pointless in a single window GUI.

Quite the opposite is true: #3475 implements an universal way of embedding external windows into our (or any Qt) GUI on X clients. We are currently embedding them into MDI subwindows, but the code for embedding them into any Qt Widget would be exactly the same (just like we already do for VST efffects) – we'd just embed them into a different widget. So if we're going to build a single window GUI with VST embedding support, we'll need #3475 for the Linux/X11 implementation.
I wrote #3475 with the single-window GUI in mind, and it was in fact one of the reasons I decided to take that approach.

Regardless of this PR, #3475 can be considered a bug fix to the previous Qt4 implementation. Qt never implemented the Xembed protocol correctly, which may have been the cause for some VSTs not working correctly when embedded (haven't tested with a lot of VSTs).

Ultimately, I'd love if both solutions could be merged into our codebase.  If embedding turns out to be a problem that we can't solve reliably (or if Linux distros migrate to Wayland), we can switch to this solution or always offer it as an option for troubling environments/VSTs.

**Comment by BaraMGB** [comment]
@Lukas-W I thank you very much for the clarification in this matter. Now I have no objections against https://github.com/LMMS/lmms/pull/3475, anymore. We should merge https://github.com/LMMS/lmms/pull/3475 and release 1.2 :)

**Comment by Lukas-W** [comment]
> We should merge #3475 and release 1.2 :)

:) We should test it thoroughly first though, or better just defer it to 1.3 and ship with Qt4 in 1.2 on Linux for one last time.

**Comment by tresf** [comment]
> ship with Qt4 in 1.2 on Linux for one last time.

Qt4 is still our default framework on builds, but the `linuxdeployqt` tool we use for `.AppImages` is currently [Qt5-only](https://github.com/probonopd/linuxdeployqt/issues/20), so this depends on the definition of "ship with".

**Comment by simonvanderveldt** [comment]
@lukas-w What is in the end for the user the actual difference between embedding/#3475 and this PR? 
Will this PR result in a new application per plugin and #3475 a new subwindow (i.e. to switch alt-tab vs alt-~) or is there effectively no difference at all?

**Comment by lukas-w** [comment]
> Will this PR result in a new application per plugin and #3475 a new subwindow

Exactly. This PR opens a new window per VST while #3475 opens a subwindow, maintaining the original behaviour from Qt4.

**Comment by simonvanderveldt** [comment]
> Exactly. This PR opens a new window per VST while #3475 opens a subwindow, maintaining the original behaviour from Qt4.

OK, thanks for the clarification!

**Comment by AngeloSorte** [comment]
@lukas-w Lukas, thank you! I would have time to invest in that. I am graduated in computer science engineering, but i am completely new in this. Could u say to me better what I should do to complete this job? Thanks a lot. PS: i made 6 albums with this program! :)) I tried many times to thank you all in general, but i couldn't! Now i found this. Thx!

Angelo

**Comment by lukas-w** [comment]
@AngeloSorte Glad to hear you're eager to help :) I'm not sure though what "job" to complete you're referring to though. 

If you're talking about the issue this PR is targeting (#2855), note that this PR will be superceded by #3786. #3786 is waiting for #3991 at the moment, but apart from that it's pretty much ready for testing. So unless major bugs are discovered in #3786, there's not much left to do.

If you want to contribute to the project in general, a good way to get in touch with the team is by introducing yourself on our Discord server at https://lmms.io/chat/ in `#devtalk` or `#programming`.

**Comment by AngeloSorte** [comment]
@lukas-w Thank you so much Lukas! Indeed I am new here. So I don't understand very well, but I just wanted to start a project to improve LMMS, that anyway I already used so much to make music. But I am also graduated in computer science engineering. And I wanted to invest my time in doing a project for the open source, like this. If you can help........even if u already did it. Going to register there. Then we will see......thanks!!! :)))) Really I hope to start soon...

**Pull request closed without merging**
