### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by liushuyu**
Fix Travis autodeploy

---
This change is [Reviewable](https://reviewable.io/reviews/lmms/lmms/3211)

### CODE REVIEW

**Comment by tresf** [comment]
@liushuyu can you explain this please?  Looks different than the documentation.

https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A

**Comment by liushuyu** [comment]
According to their documentation, this expression will be pasted to `if [[ <condition> ]]; then <deploy>; fi` and I just wonder if this will work, because this is a valid Bash expression.

**Comment by liushuyu** [comment]
And I suspect if this is a big of Travis CI. It says it can't execute `getcwd()` normally, this is impossible unless the current folder has been removed.

**Comment by jasp00** [comment]
The solution was to add `skip_cleanup`, you should revert to the previous condition. New one is invalid (no wildcards, case-sensitive).

**Comment by jasp00** [comment]
Use `"$TARGET_OS != linux"`.

**Comment by Umcaruje** [comment]
>Use "$TARGET_OS != linux".

This would make travis build packages for mac as well, and would end up uploading double files for windows. That's why I changed the condition

**Comment by Umcaruje** [comment]
>no wildcards, case-sensitive

so `condition: "($TARGET_OS = win32 || $TARGET_OS=win64) && $QT5 = True"`?

**Comment by jasp00** [comment]
My bad, I was thinking about `[` instead of `[[`; it is case-sensitive, though. So:
`condition: "$TARGET_OS = win* && $QT5 = True"`

**Comment by zonkmachine** [comment]
Superseded by 4db1db5ecaa183b24525296e8d344bf789b78f00, closing.

**Pull request closed without merging**
