### PR TITLE
Sort lists generated from globbing expressions

### PR DESCRIPTION
**Pull request by jasp00**
LMMS does not build reproducibly (https://reproducible.debian.net/rb-pkg/lmms.html). One identified issue is that lists from `FILE(GLOB ...)` are not deterministic. This patch sorts those lists. This issue does not affect CMake after version 3.5.2.

### CODE REVIEW

**Comment by teeberg** [comment]
According to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824263, a fix for this [has already been merged upstream in cmake](https://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=edcccde7). I feel like we shouldn't worry about it here if upgrading to a newer cmake version will take care of it for us.

**Comment by jasp00** [comment]
The reproducibility problem will be in all environments that do not upgrade CMake, such as Ubuntu 14.04LTS (Travis builds).

**Comment by teeberg** [comment]
Do travis builds need to have reproducible builds? As far as I understand, reproducibility is about the enduser being able to confirm that a shipped binary was actually built from a specific set of files. Are you pursing other objectives?

I don't care or mind though, I'm just wondering :)

**Comment by jasp00** [comment]
I am just trying to provide reproducible builds. This could be useful in backports to stable distributions, and possible deployments by Travis (Ubuntu packages of 1.2.0-RC2).

**Comment by jasp00** [comment]
If an AppImage is built by Travis (#2556), it should be reproducible.

**Pull request merged**
