### PR TITLE
Fix project export problems when using the alsa audio interface

### LINKED ISSUE #2457: Can't export audio from master
Rendering audio to files is broken in master, the progress bar sticks at 0 and the GUI freezes. Tested with ```Skiessi-Onion.mmpz``` and some others, 64-bit builds fail but on my 32-bit system I get one successful export and the second one in the same LMMS instance freezes.

Git bisect points to 8b65ae37b4c9b9b9286b180b1b1b31f5d7ba44d4 but I might've screwed something up, as that commit looks pretty unlikely to cause this.

### PR DESCRIPTION
**Pull request by Fastigium**
This pull request is an effort to fix #2457

### CODE REVIEW

**Comment by Umcaruje** [comment]
@Fastigium do you need some testing for this PR?

**Comment by Fastigium** [comment]
@Umcaruje Hm, complicated. I intended to implement a better fix as I explained in the last few posts on #2457, but it seems my LMMS coding motivation packed its bags and left without a forwarding address :neutral_face:. This PR makes things work again, but in a suboptimal way. It has already been tested by both [zonkmachine](https://github.com/LMMS/lmms/issues/2457#issuecomment-199350064) and [softrabbit](https://github.com/LMMS/lmms/issues/2457#issuecomment-200240502) with successful results.

So, unless someone else shows up who'd like to fix it good and proper using the things I explained in #2457, or unless my motivation shows up again, merging this PR should fix #2457. My inner perfectionist screams that it should be noted that this solution is *ugly™* as explained [here](https://github.com/LMMS/lmms/issues/2457#issuecomment-200250877) and a better one would be something like [this](https://github.com/LMMS/lmms/issues/2457#issuecomment-202326640). But that's just me, and the end user probably doesn't care as long as the export works.

My advice: give this PR one more test and merge it if it works. Things can always be fixed later if need be. If funky things start happening on project export later on, feel free to poke me and/or use the explanations in #2457 to fix things in a better way.

**Comment by zonkmachine** [comment]
> My advice: give this PR one more test and merge it if it works. Things can always be fixed later if need be. If funky things start happening on project export later on, feel free to poke me and/or use the explanations in #2457 to fix things in a better way.

I'm sorry I haven't been around to testing this PR.
#2457 seem to be partially fixed by #2879 , at least I can export the same file many times without LMMS freezing up, and the PR now has conflicts. It will still crash on pressing Cancel during export.
@jasp00

**Comment by Umcaruje** [comment]
#2457 has been closed as fixed, closing this PR.

**Pull request closed without merging**
