### PR TITLE
Move widget files, add folder for track and instrument

### PR DESCRIPTION
**Pull request by allejok96**
Moving files in `src/gui`, no change to their source. Updated translations accordingly.

- `gui/clips` for `*ClipView`
- `gui/editors` for editors *and* their child widgets
- `gui/instrument` for `InstrumentTrackWindow` and child widgets
- `gui/tracks` for `*TrackView` and child widgets
- `gui/widgets` for generic widgets only

### CODE REVIEW

**Comment by allejok96** [comment]
I didn't touch `LinkedModelGroupViews`, `Controls` and `ControlLayout`. I wonder if @JohannesLorenz thinks these should be moved out of `widgets` ?

**Review by Spekular — COMMENTED** [review]
A few thoughts
- PositionLine is only used in editors, right? Maybe it should live in the editors folder.
- I'm not sure how I feel about ClipViews being in the track folder. I understand the reasoning, but that's not where I would expect them to be if I were searching for them.

Looks good otherwise

**Comment by allejok96** [comment]
> I'm not sure how I feel about ClipViews being in the track folder.

I share that feeling :sweat_smile: but it would be nice if they lived together in a directory, even if it's only 5 of them.

> PositionLine is only used in editors, right? Maybe it should live in the editors folder.

I could see that. Same goes for TimeLineWidget, StepRecorderWidget and Rubberband.

**Comment by JohannesLorenz** [comment]
> I didn't touch `LinkedModelGroupViews`, `Controls` and `ControlLayout`.

I designed `Controls` and `ControlLayout` as generic-purpose widgets, so I think they can stay in `widgets`.

For `LinkedModelGroupViews`, this is only useful if you have a dynamic set of controls (e.g. TripleOscillator is static, but e.g. Lv2, LADSPA etc. are dynamic, because the controls depend on the loaded plugin). Due to their complexity and their rare use case (Lv2 currently, possibly LADSPA, VST), I'd rather say not `widgets`?

**Comment by allejok96** [comment]
Okay so LinkedModelGroupViews goes.

I'd like to move out `ControlLayout` too since it's not a QWidget even if it's general purpose (similarly to ActionGroup).

**Comment by JohannesLorenz** [comment]
> I'd like to move out `ControlLayout` too since it's not a QWidget even if it's general purpose (similarly to ActionGroup).

Sounds good!

**Comment by allejok96** [comment]
I don't know what the consensus is for more small widgets in the `editors` folder and a separate `clips` folder (like @Spekular insinuated), but I've made those changes. Now let's see what the people think.

**Comment by PhysSong** [comment]
Why is `InstrumentTrackWindow.cpp` in `gui/instrument` while `SampleTrackWindow.cpp` is in `gui` and `InstrumentTrackView.cpp` is in `gui/tracks`?
I think `InstrumentTrackWindow.cpp` should stay in `gui` unless we move `SampleTrackWindow.cpp` to `gui/tracks`.

**Comment by allejok96** [comment]
I understand how it can get confusing with many classes named "instrument". The `instrument` directory should really be called `instrumentwindow` to avoid all confusion...

> Why is `InstrumentTrackWindow.cpp` in `gui/instrument` while `SampleTrackWindow.cpp` is in `gui`?

I thought it made sense to put the window in the same directory as all its children, but I'll reverse it if I get a second opinion.

> Why is `InstrumentTrackView.cpp` is in `gui/tracks`?

`InstrumentTrackView` is a track (view)

> ... unless we move `SampleTrackWindow.cpp` to `gui/tracks`

 `SampleTrackWindow` is not a track, and not a child to a track (view)

**Comment by allejok96** [comment]
I need some opinions before I can continue (will have to fix a lot of strings)

- [ ] Is `instrument` a good name for the directory that holds the instrument window and it's stuff?
- [ ] Is it ok to put `TrackContainerView` inside `tracks`? Motivation: where else would you expect to find it?
- [ ] Is it ok to put editor specific widgets, like time line, into `editors`?

**Comment by Spekular** [comment]
Makes more sense to put `TrackContainerView` in `editors `than `tracks`, IMO, since it's the parent to both the song and pattern editors. I lean towards yes for the other two questions.

**Comment by JohannesLorenz** [comment]
My opinion would be a copy of Spekular's:

1. Yes. What other name would fit better if it has instrument specific GUI stuff?
2. In `editors`. Because if our philosophy is that everything in `tracks` is a widget used inside tracks, then `TrackContainerView` would not fit `SongEditor` (which *contains* tracks). Also, it's more like an editor to me.
3. Yes. I think we said everything inside "editors" should be a widget used inside editors.

**Comment by allejok96** [comment]
Thank goodness for the Unix toolbox. This oneliner finds all renamed files since a given commit and updates all strings to use the new path (works only for paths relative to base of repo). Maybe you might find it useful.
```sh
git ls-tree -rz --name-only HEAD | xargs -0 sed -i -f <(git diff --raw ENTER_COMMIT_ID_HERE | sed -En 's/.*R[0-9]+\t(.*)\t(.*)/s^\1^\2^g/p')
```

**Comment by allejok96** [comment]
I've squashed the commits, ready for review.

**Comment by JohannesLorenz** [comment]
@allejok96 While users are reviewing, if you rebase a local copy of this branch on #6379 (or wait until it's in master), you can check your locale updates.

**Comment by allejok96** [comment]
@JohannesLorenz Strings look alright, except for `PatternClipView` which will cause a conflict with #6379 if I rename. Either I wait for check-strings to be merged, or you resolve the conflict later.

**Comment by JohannesLorenz** [comment]
> @JohannesLorenz Strings look alright, except for `PatternClipView` which will cause a conflict with #6379 if I rename. Either I wait for check-strings to be merged, or you resolve the conflict later.

Both is OK to me. I'd say first come first serve?

**Comment by allejok96** [comment]
I wait until the renames of this PR are approved.

**Comment by JohannesLorenz** [comment]
If it's just for moving forward, I'd help you by reviewing this PR, but I'm rarely involved in GUI stuff, so I'm not a good candidate. I might try a review if no one else does it in the next days... :smiling_face_with_tear:

**Comment by allejok96** [comment]
@JohannesLorenz and @Spekular's suggestions has been added. @PhysSong had some concerns - maybe we can get a second opinion? Or else we're good to go, as long as it builds :upside_down_face:

**Review by JohannesLorenz — APPROVED** [review]
Most widgets reside where I'd expect them. A few points:

1. `MixerLineLcdSpinbox` sounds a bit non-generic. Should it be in `src/gui`?
2. I wonder if `SubWindow` is so generic that it should go down into `widgets`?
3. Should we add a folder `src/gui/base-classes`? (`AutomatableButton`, `SideBarWidget`, `ControllerDialog`...)
4. We have a lot of `...View`s. Extra folder `src/gui/views`?
5. I wonder why we have an extra directory for `editors`, but leave the non-modal dialogs (`EffectControlDialog`) in `src/gui`. After all, aren't they both some kind of windows inside the MainWindow?

Anyways, these are all just suggestions. The PR is OK.

**Comment by allejok96** [comment]
> I wonder why we have an extra directory for editors, but leave the non-modal dialogs (EffectControlDialog) in src/gui. 

I aimed to group things by concept rather than if it's a base/derived class, if it contains a specific word, or if it's located at a specific level in the GUI. I find this approach more helpful when looking for where a certain feature is implemented. So `editors` are for the main editors of LMMS and their specialized widgets. You'd never call `EffectControlDialog` an editor, so it's excluded.

> MixerLineLcdSpinbox sounds a bit non-generic. Should it be in src/gui?

Perhaps. I just put it where all of the other Lcd* siblings were, since there are a few.

> I wonder if SubWindow is so generic that it should go down into widgets?

On the other hand it's mostly used by `MainWindow`. Personally I wouldn't look for it in `widgets`.

**Comment by JohannesLorenz** [comment]
I'd say let's merge it, then?

**Comment by PhysSong** [comment]
I'm still not sure where `InstrumentTrackWindow.cpp` should be, but I'm okay with the others.

**Comment by JohannesLorenz** [comment]
Note: As I merged the `check-strings` branch prior to this PR, it might be good if you rebase on master and see if CI still passes.

**Comment by allejok96** [comment]
> PatternClipView which will cause a conflict

Lol I forgot to update my own remark. Well, now we know that CI works :smile:

**Pull request merged**
