### PR TITLE
Knob value hover

### PR DESCRIPTION
**Pull request by salilra**

### CODE REVIEW

**Comment by PhysSong** [comment]
I can see the "stuck" text float even after the mouse pointer moves out of the knob. Also, [indentations should be done with tabs](https://github.com/LMMS/lmms/wiki/Coding-Conventions#indentation), not spaces.

**Comment by superpaik** [comment]
In addition to what PhysSong said, I just notice that the text appears almost instantly. It's common UX practice to wait some time (about a second) before the text popup to avoid the text to constantly appear when the user moves the mouse.

**Comment by Spekular** [comment]
> In addition to what PhysSong said, I just notice that the text appears almost instantly. It's common UX practice to wait some time (about a second) before the text popup to avoid the text to constantly appear when the user moves the mouse.

A second is rather long. Off the top of my head I recall 300ms being "standard", but searching again I find a range of 300-500ms. Google claims the average human reaction time (for visual stimuli) is 250ms, which lines up nicely with the 300ms delay.

If we had used a QToolTip for this, there's an [existing method](https://doc.qt.io/qt-5/qtooltip.html#showText-2) to show a tooltip with delay. [TextFloat](https://github.com/LMMS/lmms/blob/89b13280de93ad2131c12dc234fa65cd10855996/include/TextFloat.h) doesn't have such a method at the moment though, so it would need to be improved if we want to use it for this. (I don't think it's wise to implement the delay logic inside Knob).

In regards to the stuck tooltip, I think you should use the [enterEvent](https://doc.qt.io/qt-5/qwidget.html#enterEvent) and [leaveEvent](https://doc.qt.io/qt-5/qwidget.html#leaveEvent) rather than mouseMoveEvent to trigger the tooltip.

**Comment by michaelgregorius** [comment]
The cleanest way would be if Qt provided some mechanism to be notified when a (custom) tool tip should be shown or hidden. That way the custom tool tip would be consistent with the other ones with regards to the time that it takes until it is triggered.

The documentation of [QToolTip](https://doc.qt.io/qt-6/qtooltip.html#details) has some details on how to intercept a `QHelpEvent` that indicates that a tool tip would be about to show. Unfortunately, this only works half the way, i.e. there does not seem to be a way to get informed that a tool tip should be hidden again.

An alternative option might be to have a fixed place in the GUI where detail information can be shown, e.g. when the mouse pointer is above certain elements/widgets. So as soon as you'd move the mouse over a knob it would show some information about the current value in that area.

**Comment by michaelgregorius** [comment]
> > An alternative option might be to have a fixed place in the GUI where detail information can be shown, e.g. when the mouse pointer is above certain elements/widgets. So as soon as you'd move the mouse over a knob it would show some information about the current value in that area.
> 
> #5571

Ah, there's always already an issue. 😅

**Comment by zonkmachine** [comment]
> Ah, there's always already an issue. 😅

And now there's a PR. I bumped you to review it. My coding is weak. https://github.com/LMMS/lmms/pull/6835

**Comment by zonkmachine** [comment]
Closing as superseded by https://github.com/LMMS/lmms/pull/6835
@salilra Thanks for your efforts!

**Comment by michaelgregorius** [comment]
> > Ah, there's always already an issue. 😅
> 
> And now there's a PR. I bumped you to review it. My coding is weak. #6835

Done, @zonkmachine!

**Pull request closed without merging**
