### PR TITLE
Color Updates

### PR DESCRIPTION
**Pull request by RebeccaDeField**
In this PR I have:

- Updated a knob to have better contrast with the lightened track titles
- Made tweaks to perfect track labels with new border on hover
- Updated name for shadows with "p" for pressed instead of clicked
- Edited the sidebar better contrast and consistency
- Lightened plugin list for better contrast
- Tweaked BG color for better contrast

While the changes may be only tweaks I feel they positively impact the overall usability and contrast.

@Umcaruje @BaraMGB @grejppi

### CODE REVIEW

**Comment by Umcaruje** [comment]
This looks very good to me :+1: 

Some screenshots:
screenshot from 2016-07-26 15 17 22
screenshot from 2016-07-26 14 30 34

**Comment by BaraMGB** [comment]
Yes, that's looking very clean now.

**Comment by RebeccaDeField** [comment]
@Umcaruje @BaraMGB Glad to hear you think so.

I am noticing that the button and track shadows are missing from your screenshots, which has me concerned that there is an error somewhere with it. Please see example of what the pressed buttons and tracks are supposed to look like:


As you can see they have a shadow around the edges giving it a pressed in effect, compared to what your screenshot is showing:
20cd5772-5344-11e6-9b2d-d88b61d4d8bc

**Comment by Umcaruje** [comment]
>I am noticing that the button and track shadows are missing from your screenshots, which has me concerned that there is an error somewhere with it

There probably is a problem somewhere, I ran `ninja clean` and compiled a fresh build, the buttons still look the same way.

**Comment by RebeccaDeField** [comment]
@Umcaruje It's also strange because I tested it on a two laptops and two desktop computers and the shadow shows up for me. Hmmm.

**Comment by Umcaruje** [comment]
@RebeccaDeField qt4 or qt5?

**Comment by jasp00** [comment]
@Umcaruje, your TripleOscillator logo looks different. Are your theme settings right?

**Comment by Umcaruje** [comment]
@jasp00 that was an old build, and the plugins don't actually change their logos when you recompile, unless you manually remove the `embedded_resources.h` file from the `build/plugins/plugin_name` folder. Now, I did a fresh build with qt5 too, no luck: 
screenshot from 2016-07-27 21 16 03

**Comment by jasp00** [comment]
I see the shadows with Qt4.

**Comment by RebeccaDeField** [comment]
@Umcaruje In your screenshot the track label isn't just missing the shadow. It's also missing some other changes. It has a slight radius (I straightened the corners) and a darker border (I lightened the border).

**Comment by Umcaruje** [comment]
I'm terribly sorry, seems I've been building the wrong branch: `theme-contrast` rather than `color-updates`.
screenshot from 2016-07-29 22 51 51

**Comment by RebeccaDeField** [comment]
Not a problem. Is this good to merge now?

**Comment by Umcaruje** [comment]
Yes :+1:

**Pull request merged**
