### PR TITLE
Feature/voxpop

### PR DESCRIPTION
**Pull request by teknopaul**
PR adds an instrument to make playing voice samples easier.  
It allows importing multiple cue points that can be created with labels in Audacity and exported as .txt.
The Instrumnet imports a .wav and the cue points as a .txt file and then setups up sampleBuffers internally for each cue point.
Currently selected cue piont's index and text is shown in the GUI.

To select the cue point during playback user can chose between 1 of 3 modes
**Sequential** - selecting the sample one after the other in order, e.g.a song chopped in to verse1, chorus, verse2, verse3
**Automation** - separate automation track selects the cue point by index, 1,2 3 4
**Piano** - note chosen selects which sample to play (naturally pitch variation is lost in this mode

voxpop-screenshot

### CODE REVIEW

**Comment by Rossmaxx** [comment]
Just curious, what's the difference between this plugin and the new slicer plugin at #6857 ?

**Comment by RoxasKH** [comment]
Yeah, i'm having kind of an hard time understanding its purpose too.

You need to load 2 separate files (which you have to go through audacity to create) to do something that at my current understanding seems could be easily pulled off just using the sample tracks in 1.3, as slice aren't that frequent with vocals, or well if you're doing chops, SlicerT has been merged as well.

So i'm most likely trying to understand the usecase where this would help comfortably improving the workflow.

**Comment by teknopaul** [comment]
Not seen that plug-in. Where do I get it? 
Potentially it's the same thing but green.

**Comment by teknopaul** [comment]
Audacity does not export cue to wave (yet) a Linux user

**Comment by Rossmaxx** [comment]
> Not seen that plug-in. Where do I get it?

The latest master. It was merged just a week ago.

**Comment by teknopaul** [comment]
OK finally managed to rebase and look at SlicerT

Kinda cool, but not the same thing.   Looks designed for chopping up loop samples like rex, an algo for finding beat start points will not work reliably for voice because of vocal sounds like 'S' and 'W'.

I loaded my e.g voice sample and this is what I see with slicer,  its split per word (without text)

image

Rather tha split by what you would want to trigger, i.e. a whole phrase / sentence.

Slicer does not seem to allow pitch shifting? or sample selection with automation? i.e. it seems it only supports one of the modes in Voxpop (piano).  The UI is like all lmms plugins 250px across.  For the whole wave that is too cramped and you don't get tools for finding 0 Z positions.   The idea of importing cues from Audacity is that you get a full screen GUI and better zoom tools and labeling, start and end points and a standard format as output.

The music I've been writing with Voxpop I could not port to slicer.

I could try to pourt some stuff from voxpop to add to slicer but I dont think the goal is the same,  slicer is a looping tool , voxpop is voice sample player for "one shots"  I dont think a feature merge would make sense.
I plan someday to add key mappings to voxpop so it can be used as multisampler with configurable pitch range per sample.  This will resolve a few use-cases logged for "multi-instrumnets"

I could try to port cue sheet import from voxpop to slicer, looks like slicer does not have end points or text tho.

**Comment by teknopaul** [comment]
ho hum:  bit silly to publish a plugin architecture and docs on how to use it and then not accept user generated plugins.

**Comment by Spekular** [comment]
> ho hum: bit silly to publish a plugin architecture and docs on how to use it and then not accept user generated plugins.

I don't want to encourage off-topic conversation on this issue, but since you're not in the Discord (AFAIK) I'll reply here to point out that friction when merging PRs isn't a devaluation of your work. There's just a lot of costs involved and few resources to go around, as you can tell from the number of open PRs and issues. It's frustrating to be held back by the project's limited bandwidth, and I think most developers who have worked on LMMS have experienced that, but to some extent it's inevitable (you can mitigate this a bit if you make your plans known ahead of time and get feedback before you put too much work in).

To briefly define what I mean by costs: Every merged PR comes with an upfront time investment to review and test, and the risk that mistakes slip past review and need to be fixed. Features have the added cost of indefinite maintenance; even if they become redundant and can "safely" be removed at some point, that requires upgrade routines and forces users to re-adjust their workflow. Plus, every feature needs to be exposed in the UI somehow, which can easily end up cluttered and inconsistent (e.g. our keyboard shortcuts).

**Comment by tresf** [comment]
@teknopaul thanks for the submission and for explaining the difference that this plugin has over others https://github.com/LMMS/lmms/pull/6994#issuecomment-1821198288.

> it silly to publish a plugin architecture and docs on how to use it and then not accept user generated plugins.

We do!  Can we keep this open?

**Comment by teknopaul** [comment]
Voxpop is not being developed on its own branch.

If it is wanted somewhere else, I would need to create a new branch and separate stuff out that is not wanted.

**Pull request closed without merging**
