### PR TITLE
Remove obsolete workaround for Qt4 since we no longer use it

### PR DESCRIPTION
**Pull request by SpomJ**

### CODE REVIEW

**Review by sakertooth — APPROVED** [review]

**Review by Rossmaxx — APPROVED** [review]
LGTM.

**Comment by Rossmaxx** [comment]
I refrain for merge because our CI is broken and I'll merge as soon as #7589 is taken care of

**Comment by SpomJ** [comment]
#7589 has been merged

**Comment by messmerd** [comment]
Should we be using `setNativeMenuBar()` from `QMenuBar`?

**Comment by SpomJ** [comment]
If you're waiting for my answer, I have no clue. The code said this was a workaround specifically for Qt4, and since we don't use it anymore, there is no reason to keep it.

If I had to guess, this was in place to explicitly state that OS shouldn't steal the menu bar, and now it's probably implicit so it's not like behavior should change, it's just that explicit statement is no longer needed.

You could test `setNativeMenubar()`, but that's probably subject to a separate commit anyways.

**Pull request merged**
