### PR TITLE
fixed broken 21pink LCD display

### LINKED ISSUE #6454: Bad selection of colors on SF2 UI
### Bug Summary
Visual impaired can see the settings for BANK & PATCH.
Dark-purple on black is not functional

#### Steps to reproduce
Just look at it

#### Expected behavior
Clear and distinctable  UI-text

#### Actual behavior
Not distinctable  UI-text

#### Screenshot
image

#### Affected LMMS versions
< 1.2. 

#### Type of Issue
Good fist Issue

### PR DESCRIPTION
**Pull request by Rossmaxx**
fixes #6454 

Apparently, the "pink" lcd on the default theme is purple and it is barely visible with the dark background. I changed it to use an actual pink color.

before : 
image

after : 
image

fix suggested by @DanielKauss

### CODE REVIEW

**Comment by Veratil** [comment]
@RebeccaDeField

**Comment by RebeccaDeField** [comment]
@Veratil I don't think having a pink color to improve the contrast is a problem. There was a time that we spent way too many thread messages and issues trying to get the purple light enough, so given that it's still blending into the background, it's probably not going to get bright enough as purple.

I haven't used LMMS in a while so what needs to be tested is making sure that every area this effects is taken into account in case the color change will also modify colors unelated to the LCD. We will also need to see how this looks on several plugins.

Lastly, I don't know if we still take into account general public opinion because small tweaks can cause some strong reactions, so it might not be a bad idea (or might be) to get a few thoughts from a few other users about a particular color and how it blends in with the rest of the program, especially if they are more familiar with the program than I am atm.

My thought is that if it gets the job done and takes away one contrast issue, then go for it 👍

**Comment by Rossmaxx** [comment]
> We will also need to see how this looks on several plugins.

Afaik, the 21pink lcd is used only in sf2 player (and SlicerT once it gets merged). Correct me if i miss out any plugin. 

> don't know if we still take into account general public opinion

That's still the case but things get merged pretty fast these days because we tend to agree on stuff more compared to the past. 

The more eyes the better.

**Comment by superpaik** [comment]
I like it better now. I think it's more in line with the "green" lcd

**Review by superpaik — APPROVED** [review]

**Comment by tresf** [comment]
When did change from green?

image

**Comment by Veratil** [comment]
> When did change from green?
> image

https://github.com/LMMS/lmms/commit/f7b160d34f84f9c0b131a2941c0f6059e03ed55d#diff-13236858ad549aea6331ae6486fdaa11dbd9d73d03be0e628abf632415d13ac7

**Comment by tresf** [comment]
> [f7b160d#diff-13236858ad549aea6331ae6486fdaa11dbd9d73d03be0e628abf632415d13ac7](https://github.com/LMMS/lmms/commit/f7b160d34f84f9c0b131a2941c0f6059e03ed55d#diff-13236858ad549aea6331ae6486fdaa11dbd9d73d03be0e628abf632415d13ac7)

No, in that commit it's pink, not purple and using the older LCD style artwork.

**Comment by Veratil** [comment]
> > [f7b160d#diff-13236858ad549aea6331ae6486fdaa11dbd9d73d03be0e628abf632415d13ac7](https://github.com/LMMS/lmms/commit/f7b160d34f84f9c0b131a2941c0f6059e03ed55d#diff-13236858ad549aea6331ae6486fdaa11dbd9d73d03be0e628abf632415d13ac7)
> 
> No, in that commit it's pink, not purple and using the older LCD style artwork.

Oops, you're right. Here it is. https://github.com/LMMS/lmms/commit/3f2e17dd04d5bad40e76928f10621dee803d28ce#diff-4d6d01e3874566c5ebc59ff14cf5c36e0a4a456eb44277d6e5a6a83ed6945c10

**Comment by tresf** [comment]
Yeah but it hasn't been working.  My screenshot is from stable.

**Comment by Veratil** [comment]
> Yeah but it hasn't been working. My screenshot is from stable.

You're right. I just checked 1.2.1 as well and it's using green there, too.

**Comment by Rossmaxx** [comment]
It's ok to change to green, but imo, the current pink suits the ui better than green.

**Comment by tresf** [comment]
My guess is that it was inadvertently fixed in https://github.com/LMMS/lmms/pull/5865.  Yeah, the pink is fine, it's just an odd one to have been broken for so long and then resurrected and then turned into a bug report.

**Comment by tresf** [comment]
> We will also need to see how this looks on several plugins.

@RebeccaDeField Only SF2 and GigPlayer uses this particular "pink" LED style.

Here's GigPlayer with this PR:

image

> My thought is that if it gets the job done and takes away one contrast issue, then go for it 👍

I sort of agree.  I feel that GigPlayer doesn't really have enough of it's own visual style to warrant NOT merging.

**Comment by sakertooth** [comment]
If we are all happy with the contrast change, I say merge?

**Comment by zonkmachine** [comment]
> If we are all happy with the contrast change, I say merge?

Sure. That's a whole lotta pink. I actually prefer the original green but if people want pink then I guess pink it is.

**Comment by RebeccaDeField** [comment]
I prefer to consolidate into one green if it's only used in two instances, but pink also works if it contracts well enough. Is it possible to consolidate even the separated definition for these LCDs and point it to just use the normal color or is that a pretty complex rabbit hole? From my perspective it's better if we have less unique colors to deal with.

I'm not strongly opinionated on this as the pink still has good contrast and is not offensive in any way.

**Comment by messmerd** [comment]
If we go with pink, I'd prefer if the pink of the LCD display and the pink of the file open icon matched. Right now they are slightly different shades of pink and it bothers me a little.

**Comment by RebeccaDeField** [comment]
@messmerd You're right on that point. So I think we have two options and this can be merged upon one direction being completed:

- Change icon to match and merge
- Change icon to be a neutral color and LCD to be green and merge

**Comment by Rossmaxx** [comment]
From this discussion, I just noticed that the pink shade in lcd box and the pink in file dialog is different. Will fix it now. 
Also, using green is ok but I don't feel like it matches the theme of sf2player. So I feel it's better to use pink here.

**Pull request merged**
