### PR TITLE
Fix issue #1848

### PR DESCRIPTION
**Pull request by M374LX**
Fix issue #1848.

### CODE REVIEW

**Comment by tresf** [comment]
@badosu,

I'm going to need some help reviewing this.  I hope you don't mind me deferring.

P.S. The code styling changes really make this tough to read through.

**Comment by badosu** [comment]
@tresf I am sorry but this one is pretty difficult.

@M374LX can you separate the actual relevant change in a separate commit to make it easier to review?

**Comment by M374LX** [comment]
The only change is 5d70e3d. Sorry for the trouble I am having with Git.

**Comment by badosu** [comment]
@M374LX No problem, you already outlined the relevant change, thanks!

**Comment by badosu** [comment]
Oh, now I got what the issue was, I totally misunderstood it at first:

> ...options for the sound driver are **now** the ones for the newly selected driver, but tho...

You mean **not** there. I am gonna review this tomorrow, thanks!

**Comment by M374LX** [comment]
> You mean not there. I am gonna review this tomorrow, thanks!

All right. That was a typo. The original comment has been updated.

**Comment by M374LX** [comment]
Something went wrong, but the new pull request is #1851.

**Pull request closed without merging**
