### PR TITLE
Remove use of QApplication::desktop in ComboBox.cpp

### PR DESCRIPTION
**Pull request by michaelgregorius**
Remove use of `QApplication::desktop` in `ComboBox.cpp`. The method was already deprecated in Qt5 and is removed in Qt6.

Generalize the check if the menu can be shown in the screen. The code now also does handles the case where the menu would go out of screen along the X axis.

Also remove the unused include `embed.h`.

### CODE REVIEW

**Comment by Snowiiii** [comment]
CI is unhappy

**Comment by michaelgregorius** [comment]
> CI is unhappy

Yes, I guess the Qt version for Linux and mingw is too old.

`QWidget::screen` has been introduced with version 5.14 ([doc](https://doc.qt.io/qt-5/qwidget.html#screen)). Ubuntu 18.04 uses 5.9.5: https://launchpad.net/ubuntu/bionic/+package/qt5-default.

**Comment by Snowiiii** [comment]
> > CI is unhappy
> 
> Yes, I guess the Qt version for Linux and mingw is too old.
> 
> `QWidget::screen` has been introduced with version 5.14 ([doc](https://doc.qt.io/qt-5/qwidget.html#screen)). Ubuntu 18.04 uses 5.9.5: https://launchpad.net/ubuntu/bionic/+package/qt5-default.

Thats just ridiculous, Having this old Ubuntu stops so much future work, Some progress needs to start on https://github.com/LMMS/lmms/pull/7015

**Comment by Rossmaxx** [comment]
You can use the `#if (QT_VERSION > QT_VERSION_CHECK(5,14,0))` macro to get it through for now, with a todo comment. That's what i did for #7133

**Comment by michaelgregorius** [comment]
> You can use the `#if (QT_VERSION > QT_VERSION_CHECK(5,14,0))` macro to get it through for now, with a todo comment. That's what i did for #7133

Thanks for the tip @Rossmaxx! I have applied it with commit c1ee2d8346b.

**Review by DomClark — APPROVED** [review]

**Comment by DomClark** [comment]
FWIW, I think the version check itself serves well enough as a TODO marker. (In fact, it's more accurate here, as it specifies the actual minimum required Qt version where the old code can be removed, which is 5.14.0 and not 6.0.0.) See also the [coding conventions entry](https://github.com/LMMS/lmms/wiki/Coding-Conventions#qt-versions).

**Pull request merged**
