### PR TITLE
Merge pull request #2 from LMMS/master

### PR DESCRIPTION
**Pull request by midi-pascal**
Sync my fork with master

### CODE REVIEW

**Comment by Umcaruje** [comment]
@midi-pascal stop this. https://github.com/LMMS/lmms/wiki/%5BGit%5D-Fast-forward-personal-branch-to-upstream Here is a guide on rebasing your fork so it stays up to date.

**Comment by midi-pascal** [comment]
@Umcaruje Sorry about that. I am not familiar with Git :-1:

**Comment by Umcaruje** [comment]
>@Umcaruje Sorry about that. I am not familiar with Git :-1: 
>And thanks for the link to the wiki :+1:

The thing is, this is not git, this is github. You can't change your files, pull or commit online. You need to install git on your PC and use the command line (or some GUI) to do what you want.

**Comment by midi-pascal** [comment]
@Umcaruje Thanks. git is already installed on my PC but I thought my fork on github was not in sync with the master branch. This why I tried the bad thing.

**Comment by tresf** [comment]
@midi-pascal it is most likely that you are doing the pull against the wrong branch.  Try to follow the fast-forward instructions that @Umcaruje linked and that should get you fast-forwarded properly.

**Comment by midi-pascal** [comment]
@tresf Done. Thanks!

**Comment by grejppi** [comment]
FYI: Your fork still has [this enormous difference](https://github.com/LMMS/lmms/compare/master...midi-pascal:master) to upstream.

**Comment by midi-pascal** [comment]
@grejppi Please never assume others have the same knowledge as yours. I am an old seasoned developper, not a github maintainer.

**Comment by tresf** [comment]
> I am an old seasoned developper, not a github maintainer.

We appreciate the help with the codebase and we're happy to help you with the git portions. :+1:

**Comment by Umcaruje** [comment]
@midi-pascal you should try to hard reset your master branch to the upstream branch and then force push.

**Comment by tresf** [comment]
Also, there are several of us on `#lmms` on IRC/freenode, if you want to open up a chat session.  There's a private message feature that allows you to ping someone like @Umcaruje or myself directly if needed. :+1: (@grejppi and several others are on there as well)

**Pull request closed without merging**
