### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### LMMS/lmms now has a Chat Room on Gitter

@liushuyu has just created a chat room. You can visit it here: [https://gitter.im/LMMS/lmms](https://gitter.im/LMMS/lmms?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/LMMS/lmms?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by Umcaruje** [comment]
@liushuyu what's the advantage of this service over IRC?

**Comment by tresf** [comment]
> @liushuyu what's the advantage of this service over IRC?

Perhaps the fact that IRC is spammed with non-dev conversation and lurkers and gives no historical content for those just joining. :smiling_imp:

**Comment by liushuyu** [comment]
>@liushuyu what's the advantage of this service over IRC?

Just take a look at their advertisement and you will know :smiley: 
(I won't tell you they have an alternative IRC tunnel at https://irc.gitter.im)

>Perhaps the fact that IRC is spammed with non-dev conversation and lurkers and gives no historical content for those just joining.

... and solutions to some common problems can be found in IRC channel history, but IRC doesn't keep any logs so it will be hard for newcomers to find the answer, and they will open an issue for a tiny question which is not needed.

**Comment by Umcaruje** [comment]
Ok, then, we should give it a shot. :+1:

**Comment by Umcaruje** [comment]
So anyways, after some discussion, we figured out it was better to use discord as our chatting service. Here's the discord server: https://discord.gg/5kSc32Z 

You can join without any accounts, it supports more roles, voice chat and seperare channels for different discussion. Discord also has a nicer mobile app, and  desktop versions for OSX and Windows.

**Pull request merged**
