### PR TITLE
Issue Template

### PR DESCRIPTION
**Pull request by Anonymouqs**
This issue template is designed to encourage clearer debug reports and more concise feature requests.

### CODE REVIEW

**Comment by tresf** [comment]
Related #2348.  The shorter, the better, and please make the formatting perfect.
1. Link your own bug tracker where we can test this out.
2. Try not to be overly wordy.  e.g., don't define stuff in your instructions.  This isn't a EULA.  Cross-link to wiki if there's potential for misunderstanding.

> In general, most conversations should take place in the IRC Channel except in rare cases. IRC: http://webchat.freenode.net/?channels=%23lmms

Nope.  Also, irony because you've been violating this rule. ;)

This file really adds a bunch of TL;DR.  Let's take a second swing at it.  Put yourself in the shoes of a person that just had a crash with LMMS.  Get the most information fastest.

Next, put yourself in the shoes of a person wanting a small feature added.  Get the most information fastest.

Speaking personally, I have a high standard for technical writing as well as seeing success and failure when too much information is thrown at a bug submitter.   Perhaps you should have followed your `conversation` proposal and asked the devs about this on Discord first. :)

Anyway, we'd be happy to add an issue template if it adds value without adding clutter. 👍

**Comment by tresf** [comment]
For reference, here's how Homebrew does it... https://github.com/Homebrew/homebrew-core/issues/new

**Comment by tresf** [comment]
Proposal below.

Demo of what it looks like here: https://gist.github.com/tresf/1fc66be7d80b975f04b9f9bc22348136

```
<!-----------------------------
|                             |
|     BUG REPORT TEMPLATE     |
|                             |
|  DELETE SECTIONS AS NEEDED  |
|                             |
------------------------------>
### Bug Summary

#### Steps to reproduce

#### Expected behavior

#### Actual behavior

#### Screenshot

**Logs**
<details>
  <summary>Click to expand</summary>
(remove this slash-->)\```
# paste here
(remove this slash-->)\```
</details>

<!-----------------------------
|                             |
|    ENHANCEMENT TEMPLATE     |
|                             |
|  DELETE SECTIONS AS NEEDED  |
|                             |
------------------------------>

### Enhancement Summary

#### Justification

#### Mockup

```

**Comment by lukas-w** [comment]
FYI, GitHub now supports multiple templates by storing them in the directory `.github/ISSUE_TEMPLATE`: https://blog.github.com/2018-05-02-issue-template-improvements/

image

**Comment by lukas-w** [comment]
Closing in favour of #4884.

**Pull request closed without merging**
