### PR TITLE
Fixes the build location of the LADSPA effect plugin

### LINKED ISSUE #2426: LADSPA plugins list in plugin browser only
@grejppi and @karmux have mentioned this but in master branch, LADSPA plugins list in the `LADSPA Plugin Browser`, but don't list in the `Add effect` dialog.

image

Furthermore, the default paths for these don't seem to be getting setup properly like the rest of the [`ConfigManager.cpp#L67`](https://github.com/LMMS/lmms/blob/master/src/core/ConfigManager.cpp#L67) config detection logic.  Pinging @Lukas-W as this may be related to some changes made to [data/plugins path enhancement which allows launching from the build directory (#1719)](https://github.com/LMMS/lmms/pull/1719).

To reproduce:

 * Build master branch
 * Launch LMMS from `build` directory
 * Observe all LADSPA plugins are missing from both the LADSPA Plugin Browser dialog as well as the Add effect dialog.

 * Edit LADSPA path preferences, add `build/plugins/ladspa/` to the LADSPA path
 * Launch LMMS from `build` directory
 * LADSPA plugins list in the Plugin Browser only.  The Add effect dialog is missing LADSPA plugins.

### PR DESCRIPTION
**Pull request by michaelgregorius**
Removes the instruction to build the LADSPA effect plugin in the
"plugins/ladspa" directory instead of the "plugins" directory where all
other plugins are built. This change enables the usage of LADSPA plugins
in development builds where the binary is started from the build
directory.

Fixes #2426.

### CODE REVIEW

**Comment by tresf** [comment]
Good catch.  @grejppi FYI, this seems to have been introduced with this commmit: https://github.com/LMMS/lmms/commit/7be47230e33e381991001f6f28b7468e877d581a#diff-fbfd80c945aeb574475a68ec8646735fR1

**Comment by tresf** [comment]
The only part I would like to mention is that @Lukas-W may have had something in mind putting these in an `ladspa` sub-folder that was intentional... If he doesn't chime in, we can always ask him for help fixing it later.

**Comment by Lukas-W** [comment]
If I recall correctly, I did that because when installing lmms, ladspa plugins are put in a `ladspa` sub-folder as well. See e.g. [plugins/LadspaEffect/caps/CMakeLists.txt#L4](https://github.com/LMMS/lmms/blob/master/plugins/LadspaEffect/caps/CMakeLists.txt#L4) or the lmms installation on your system.
So I figure there must be something wrong in the code, especially the difference between plugin browser and add effect dialog should not be there no matter how wrong the CMake files may be.

**Comment by tresf** [comment]
> especially the difference between plugin browser and add effect dialog should not be there no matter how wrong the CMake files may be.

Yes, I think we have two issues... 

 * The latest master [won't list LADSPA plugins default](https://cloud.githubusercontent.com/assets/6345473/10846490/7edd29ec-7ee6-11e5-99c4-42d1d62c6334.png) in the Plugin Browser when running from build directory.
 * Add Effect dialog unable to locate any LADSPA plugins

I looked through the code for quite a while and I can't figure out where the LADSPA Plugin Browser gets its listing from.

**Comment by michaelgregorius** [comment]
The only missing piece that will make this pull request work seems to be to initialize the LADSPA paths in LMMS' preferences to the correct directories when the `lmmsrc.xml` is created or to dynamically set a relative path to the plugins at runtime (something like `./plugins`). Here's what I did:
* Delete `~/lmmsrc.xml`.
* Build from scratch.
* Start the development build from the build directory.
* Check the "Add Effect" dialog. It only provides the LADSPA plugins which are installed system wide, i.e. not the ones built by LMMS.
* Check the "LADSPA Plugin Browser". Same situation here, only the system plugins are listed.
* Check the preferences: The following paths are preconfigured:
  * `/home/michael/lmms-dev-mg/lib/lmms/ladspa`
  * `/home/michael/lmms/plugins/ladspa/`
* Add the location where the LADSPA plugins are build to the path:
  * `/home/michael/lmms-dev-mg/lmms-build/plugins/`
* Restart LMMS and check "Add Effect" and "LADSPA Plugin Browser" again. Now they list all plugins.

To me this implies that the "Add Effect" plugin (`libladspaeffect.so`) and the Plugin Browser share the same source and that adding the correct location to the preferences will fix the problem.

So far the pull request only fixes part of the problem by putting `libladspaeffect.so` in the correct directory so that it can be found and used in the first place. The part that's missing is a configuration issue.

**Comment by tresf** [comment]
@michaelgregorius after review, I am certain that your fix is the correct one.  The ladspa's themselves need to go into `plugins/ladspa`, however, the plugin which locates them should remain in `plugins` for the reasons you've illustrated.  i.e. `libladspaeffect.so` is not an LADSPA plugin!!

Merging.

Side note... agreed on the paths part.  We can tackle that separately.

**Comment by karmux** [comment]
@michaelgregorius followed exactly your steps and had following differencies:
- When I run LMMS first time after building then "Add Effect" dialog has both installed and native effects listes, CALF plugins are missing.  "LADSPA Plugin Browser" has only installed effects, CALF plugins are missing.
- When I run LMMS after editing LADSPA paths CALF plugins become available into "Add Effect" dialog and "LADSPA Plugin Browser". "Add Effect" has all effects. "LADSPA Plugin Browser" still don't have native plugins.

Now I can open my projects made couple of months back at least :) Thanks!

**Comment by Umcaruje** [comment]
>"LADSPA Plugin Browser" still don't have native plugins.

That's because the native plugins shouldn't be there, since they are not LADSPA.

**Comment by tresf** [comment]
@karmux @michaelgregorius  #2430 should address the issue that occurs when running from build directory.

**Pull request merged**
