### PR TITLE
Use OSC messaging to notify GUI of FxMixer channel peaks

### PR DESCRIPTION
**Pull request by Wallacoloo**
This builds off of #2252, so only the commits after and including 1e98bad are unique to this PR.

Currently, the gui will spontaneously call into the core in order to determine the peak values to display for each mixer channel (I believe this is done 20 times per second). This can occasionally cause errors when both gui and mixer threads attempt to access the same resource simultaneously. This PR fixes that by instead having the mixer broadcast its peak values at the end of every buffer segment it computes, which also helps to move some gui code out of the core.

The peak values are broadcast via OSC messaging, and I discovered that the time it takes to read an argument list of size N with rtosc is proprotional to N^2. In a project that has 100 mixer channels, and therefore 200 peaks to be broadcast (left+right channel), this becomes very inefficient. For this reason, I have removed rtosc and am instead using liblo. Liblo also has the advantage of being a pretty well-tested library and is easily available through most package managers (thus it doesn't need to be distributed in the same source tree).

------
This should be ready to merge as-is, but there are also a few performance optimizations that I'll be making either before or after it's merged. Specifically (noting these here so I can reference them later as well):

* Peak values are broadcasted after *every* buffer, which is a bit excessive if the user is using something small like 64 samples. These should be grouped.
* The mixer (core) needs to compute the peak values only when at least one object is listening for them; that is, if the mixer window is closed in the gui, there's no reason to compute peak values.

### CODE REVIEW

**Comment by fundamental** [comment]
As of [today](https://github.com/fundamental/rtosc/commit/cc6e004ad2c85eff263c605130352f1b652dfca1) rtosc no longer has this O(n^2) issue, though liblo certainly does offer wider adoption and overall it is more mature.

**Comment by Wallacoloo** [comment]
Looks great @fundamental (and wow, speedy work)! Given your valid points in IRC about realtime safety, I'll go ahead and switch everything back to rtosc.

**Comment by tresf** [comment]
@Wallacoloo should we keep this guy open or close it? I know we've had other fish to fry 🐟

**Comment by tresf** [comment]
> it seems reasonable to close these PRs to declutter the tracker and reopen them later if needed. Feel free to close these if you agree.

Closing for now. 👍

**Pull request closed without merging**
