### PR TITLE
Progressive coding conventions update

### PR DESCRIPTION
**Pull request by M374LX**
The method saveSettings() had its second parameter named "_parent" in the header but "_this" in the CPP. Both have been renamed to "parent".

The method loadSetting() has a parameter named _this. Perhaps we should rename it to "parent", as done in saveSettings(). As all of you probably know, it cannot be called "this".

### CODE REVIEW

**Comment by tresf** [comment]
You could probably even get away with:

```cpp
void Note::saveSettings( QDomDocument & doc, QDomElement & element )
```

... as I don't see the contextual significance of the word "parent" in either of these files.

**Comment by M374LX** [comment]
Updates to "Track.cpp" and "Track.h" have been added.

Those files have too many classes, which make them difficult to maintain. I suggest moving the classes directly related to GUI to a new file.

**Comment by Lukas-W** [comment]
> I suggest moving the classes directly related to GUI to a new file.

Agreed. Feel free to do so :)

**Comment by M374LX** [comment]
Next update: Song.cpp and Song.h

The following files use the type "Song::playPos" (now "Song::PlayPos") and thus needed small updates: Mixer.cpp ProjectRenderer.cpp Timeline.cpp Timeline.h

An expression that often appears in Song.cpp is "60 * 1000 / 48". Is anyone able to tell what the expression means?

I also suggest to move the file dialogs from Song::importProject() and Song::exportProject() to the GUI source files.

**Comment by softrabbit** [comment]
>An expression that often appears in Song.cpp is "60 * 1000 / 48". Is anyone able to tell what the expression means?

From what I can see every 48 in Song.cpp should be `DefaultTicksPerTact/4`, as it is the number of ticks in a quarter note. 60 and 1000 come from seconds in a minute and milliseconds in a second.

**Comment by tresf** [comment]
@M374LX can you rebase this against master please to resolve merge conflicts?  Sorry for the delay as well as the inconvenience.

**Comment by M374LX** [comment]
@tresf 
The branch "coding" has been created.

**Comment by diizy** [comment]
Needs rebasing.

**Comment by tresf** [comment]
As @diizy said, this will need to be rebased on master ([fast forward](https://github.com/LMMS/lmms/wiki/%5BGit%5D-Fast-forward-personal-branch-to-upstream) and hand-edit any [conflicts](https://help.github.com/articles/resolving-merge-conflicts/)) before it is merged..

If you need help, please ask.  :)

**Comment by M374LX** [comment]
Done in #1622?

**Comment by tresf** [comment]
Thanks.  That one looks like it has conflicts as well.  Try to fast-forward it and see where the conflicts are...

**Comment by Lukas-W** [comment]
Closing as this is the exact same pull request as #1622.

**Pull request closed without merging**
