### PR TITLE
Replace information obtained from the web in aeffectx.h

### PR DESCRIPTION
**Pull request by jasp00**
I fear that information obtained from the web was copied from the Steinberg SDK. I would like to replace that information with safe data. This pull request should be handled in two commits rather than one, because changes should not be compared: the first one is the commit that erases the information, and the second one is the following squashed commits that add the discovered data.

### CODE REVIEW

**Comment by liushuyu** [comment]
The removed constants fail the Travis CI, so we should wait for the new constants?

**Comment by jasp00** [comment]
> we should wait for the new constants?

Yes. I will comment when I need help (example plug-ins) and when it is done.

**Comment by jasp00** [comment]
The class `VstParameterProperties` is only referenced in message `IdVstGetParameterProperties` (`effGetParameterProperties` in VST), but the message is not used in LMMS; I wonder why this was added. So, I will remove that message and the class.

**Comment by jasp00** [comment]
It is done. The information comes from the 32-bit library of [Helm](http://tytel.org/helm/), version 0.6.0. The function `getCurrentPosition` of file `juce_VST_Wrapper.cpp` starts at address 0x100a2870.

**Comment by SirBothersome** [comment]
> I fear that information obtained from the web was copied from the Steinberg SDK. I would like to replace that information with safe data.

@jasp00 Technically, the Steinberg license would allow you to do that, (although I'm reading the 2010 version). We can borrow stuff from the SDK, but I think we need to credit Steinberg's copyright in the documentation. I'll read it over again, but we seem to be abiding by the majority of its terms and conditions

**Pull request merged**
