### PR TITLE
Add insert/remove bar buttons in Song editor

### PR DESCRIPTION
**Pull request by allejok96**
Added two buttons for the shortcuts insert and remove bar #5602

This is my first ever pull request and piece of C++ code, so forgive any errors.

bild

### CODE REVIEW

**Comment by JohannesLorenz** [comment]
@allejok96 I get an error while starting LMMS:
```
Error loading icon pixmap "insert_bar": File not found
Error loading icon pixmap "remove_bar": File not found
```
Indeed, I see not pixmaps on the new buttons. Did you forget to add them to your commit?

**Comment by allejok96** [comment]
@JohannesLorenz Will the error fix itself or do I need to change anything?
And does classic theme need the icons too?

**Comment by JohannesLorenz** [comment]
> Will the error fix itself

Indeed! I had to do a `make clean` and a further `make install` to get it run. Seems like a bug of the build system.

Now going on with the review...

**Review by JohannesLorenz — APPROVED** [review]
LGTM

**Pull request merged**
