### PR TITLE
Updated the cmake version.

### PR DESCRIPTION
**Pull request by ranft**
Commit 2f7820a6d90bfdbd603c5c5a6617bf5fa81b9bd8 introduced a change, which
causes the build to fail with strange linker errors at least on Debian Wheezy.

### CODE REVIEW

**Comment by Lukas-W** [comment]
I don't believe this change is necessary. Can you paste the linker errors here?

**Comment by ranft** [comment]
I placed the build logs at https://qzzq.de/lmms/buildlog/. The error seems to be on line 1059 in buildlog-2.8.9-2f7820a6d90bfdbd603c5c5a6617bf5fa81b9bd8.txt and buildlog-2.8.11-2f7820a6d90bfdbd603c5c5a6617bf5fa81b9bd8.txt, where CMakeFiles/lmmsobjs.dir/lmmsobjs_automoc.cpp.o does not get included by CMake-2.8.9.

**Comment by tresf** [comment]
> I placed the build logs at https://qzzq.de/lmms/buildlog/. The error seems to be on line 1059 in buildlog-2.8.9-2f7820a6d90bfdbd603c5c5a6617bf5fa81b9bd8.txt and buildlog-2.8.11-2f7820a6d90bfdbd603c5c5a6617bf5fa81b9bd8.txt, where CMakeFiles/lmmsobjs.dir/lmmsobjs_automoc.cpp.o does not get included by CMake-2.8.9.

@Lukas-W here are the logs without invalid HTTPS certificates and untarring :)

 * [`buildlog-2.8.9-2f7820a6d90bfdbd603c5c5a6617bf5fa81b9bd8.txt`](https://gist.githubusercontent.com/tresf/84c4cb778bd0dd3a5dc4/raw/b294e9fd5662ec609bdd32f71e70c07b296f9ead/gistfile1.txt)

 * [`buildlog-2.8.11-2f7820a6d90bfdbd603c5c5a6617bf5fa81b9bd8.txt`](https://gist.githubusercontent.com/tresf/41e2afdcaa8cf59f1698/raw/302cbdf58711876893eb9b9332d03fb1f269aca8/gistfile1.txt)

**Comment by Lukas-W** [comment]
@tresf Thanks

@ranft Are you building 2f7820a? If so, you should probably update, I believe the issue you're experiencing has been fixed just one commit later, in ff882e021e1ef1430fc89fd8cdc93460051dc999. ;-)

We don't require a newer CMake version to build LMMS, so I'll close this PR. Let me know if you're still experiencing this issue with the most recent master.

**Comment by ranft** [comment]
A added the buildlog of 478bbbd4d0cde1bd6da84f24c731b206b122c6cf at  https://gist.github.com/ranft/0c74f71a67557782b9c4

**Pull request closed without merging**
