### PR TITLE
Blacklist SWH GLAME filters for Lv2

### PR DESCRIPTION
**Pull request by JohannesLorenz**
Hotfix for #5767. Implement a blacklist and add the SWH GLAME Lv2 filters to it.

This is just temporary, but I think it's important to take those filters out before more users hear that noise.

Reviewer hints:
1. The implementation may not be 100% perfect:
  a. it should be in the core, not restricted to Lv2
  b. a blacklist should be more general, as suggested in #5771 
2. ~~Wait for CI before review~~

Tester hints:
1. This PR does not require testing IMO, I tested the few bits myself. However, if you really want to test anything: Make sure you use "dummy audio output" in the LMMS settings and have restarted before. The audio produced by those effects is horrible.

### CODE REVIEW

**Comment by JohannesLorenz** [comment]
As this is a fix for a critical issue, I'll merge this without review in 3 days unless anyone has objections.

**Comment by PhysSong** [comment]
Please don't merge this now. I figured out the cause of it.

**Comment by zonkmachine** [comment]
I have a hunch the blacklist function will come in handy again later anyway. It's quite handy to have the option to temporarily remove plugins that cause trouble while we develop this.

**Comment by JohannesLorenz** [comment]
Agreed to both of you. It should not be merged like this. However, e.g. Calf Analyzer and Calf Bass Enhancer cause crashes, so I'lll remove the GLAME filters (handled by #5783) and add those Calf effects.

**Pull request merged**
