### PR TITLE
Mallets 2

### LINKED ISSUE #2455: Mallets no sound under Tubular Bells
The first time a selection is made of a setting lower than tubular bells, a sound similar to a mangled buffer is played, then nothing ... until one of the working ones is selected. Further more the mangle is heard just once, and never upon reselection of a non working variety.

**Edited @tresf**

### PR DESCRIPTION
**Pull request by zonkmachine**
Fixes  #2455
mallets2

Changes from mallets.
 * The knobs work
 * Position was mirrored to reflect actual physics but it was a bit confusing as you get the same result turning the knob left/right. We only need to model from one edge to center.
 * Added a randomness knob which randomises the position and hardness knobs. At full on and with position/hardness in center positions the randomness sweeps across the whole range.
 * Tubular bells removed. Now in Borg Jr.
 * BandedWG ( Uniform bar - Tibetan bowl ) removed.

### CODE REVIEW

**Comment by DeRobyJ** [comment]
Nice touch for randomness :like:

**Comment by tresf** [comment]
Nice, but we cannot add a second mallets instrument.  Let's find a way to fix the one we have please.

**Comment by zonkmachine** [comment]
> Let's find a way to fix the one we have please.

I came to the conclusion that the bugs that matter probably are in stk. I've already sent a fix upstream but specifically the sudden glitches in BandedWG is something I can't do anything about. The other models just works. Modal bar was obviously wired up the wrong way so the problem was on our side but for the BandedWG stuff I get completely different results.

Test:
1. Open Mallets/Tibetan Bowl
2. Without any envelopes, just left click the keyboard and move up and down over the keys. There will be spikes, I get a dozen of them per minute,  and I think they're originating from the stk model.
3. This doesn't happen on the other models. 

Also the knobs Motion and Vibrato isn't doing anything and they won't respond to the same changes I did for the modal bar. Any ideas how to get further with this?
My conclusion for now is, it's just not worth it. There is too many unknowns in that project so I just put together two replacement plugins and I think they kick some serious but. Knobs works, no glitches and apart from the randomness add on for the modal bar stuff ( I'm going to try that with the Borg too ) it's all just Mallets in there. If I have to add the BandedWG in there to something that is otherwise good it's just going to draw some serious points from the over all experience. I'm not happy with that at all.

**Comment by tresf** [comment]
@zonkmachine can we get these fixes applied to `Mallets` and not a new instrument?  I assume this was done for backwards compat, but if there's inevitable compat issues that can't be be fixed with an `upgrade(...)`, sometimes we just have to live with 'em.

**Comment by tresf** [comment]
> @zonkmachine can we get these fixes applied to Mallets?

I assume this isn't as straight forward of an answer as I had hoped for... I guess my point is, we can break Mallets a bit if we have the ability to make it better but I strongly feel we should not have two Mallet instruments.

**Comment by zonkmachine** [comment]
> can we get these fixes applied to Mallets and not a new instrument?

I didn't quite get this. Most of this is in already, https://github.com/LMMS/lmms/pull/2670 and the discussion was unfortunately spread out over more than one thread( spike issue answered here https://github.com/LMMS/lmms/issues/2455#issuecomment-199408660 ), but I still think the idea to drop the dead weight of Mallets less well working parts is motivated I just haven't had time to build a good case for it. I type slow. 

PS. I'll be away for a couple of days now.

**Comment by tresf** [comment]
Again, we aren't adding a second mallets instrument.  If we want to change the behavior of mallets to make it better, let's focus on that.

If you're concerned about the ramifications of removing a part of the instrument (e.g. Tubular bells) then don't!  Well, don't until Borg Jr is merged, then just make the Tubular Bells upgrade task part of that PR.

It's hard to comment on the impact of the code without pulling down Mallets2 and doing a local diff, so I believe a proper code review should be done on the original instrument.

**Pull request closed without merging**
