### PR TITLE
Minor icon updates

### PR DESCRIPTION
**Pull request by RebeccaDeField**
- Recreated step record icon to be less fuzzy
- Recreated ghost note icon to not include red (outside of our standard palette)
- Updated Loop Points icon to match the already improved icon created here #3069

Edit: here are some screenshots and @Umcaruje in case he wants to peak at this before it's merged.

Screenshot from 2020-07-18 18-40-03

Screenshot from 2020-07-18 18-40-43

Screenshot from 2020-07-18 18-41-11

### CODE REVIEW

**Comment by RoxasKH** [comment]
I love the ghost notes concept for those icons.

**Comment by russiankumar** [comment]
Are the .pngs saved as 16x16 or 20x20?

**Comment by RebeccaDeField** [comment]
Will be adding one last icon edit to this PR, so will be ready to merge shortly.

**Comment by RebeccaDeField** [comment]
Updated track op icon scaled down a few px as per #4255 

Before:
Screenshot from 2020-07-25 10-58-44


After:
Screenshot from 2020-07-25 10-58-38

**Comment by RoxasKH** [comment]
Way better. The once in the other pr felt someway too small imo.

**Pull request merged**
