### PR TITLE
Removed unnecessary SF2 directory setting

### LINKED ISSUE #4180: SF2 Directory Setting/Relative Paths
Spin-off from #3810... 

There are two named settings that pertain to soundfonts... 

1. There's a path called "SF2 DIRECTORY"
2. There's a path called "DEFAULT SOUNDFONT FILE"

screen shot 2018-02-19 at 9 50 51 pm

Unfortunately the software doesn't really make use of either of these when calculating relative paths, and I'm not sure we ever will, but I feel this is a bug.

Soundfonts were decided to be stored inside `samples/sf2`, discussed in https://github.com/LMMS/lmms/issues/1807 and implemented in https://github.com/LMMS/lmms/pull/1908 and then renamed to `samples/soundfonts` in https://github.com/LMMS/lmms/pull/3895.

What seems to be the missing puzzle piece here is that we added an option for a "SF2 DIRECTORY" folder, but we ignore it.  I think it simply needs to be removed.

I'm sure there will be a few people asking to have their SF2 directory outside their `samples` directory, but still relocatable, but it's simply not something we support.  If you can point me to a regression that occured between 1.1.0 and 1.2.0, I'll consider writing a patch for this, but at a glance it appears the bug was adding this location to the UI to begin with.

This is not to be confused with storing samples relative to project files, which is outlined in https://github.com/LMMS/lmms/issues/2982.

### PR DESCRIPTION
**Pull request by necrashter**
Closes #4180 

Removed every occurrence of SF2 directory in SetupDialog as well as ConfigManager. You might want to check my modification in the plugins/sf2_player/sf2_player.cpp though. I didn't understand what original code does; removed it anyway.

### CODE REVIEW

**Comment by Spekular** [comment]
I disagree with tresf on removing this directory. It adds work if someone later wishes to improve relative paths, since this will have to be reverted. It also results in user's sf2 directory configuration being lost. Finally, I believe we found the directory *does* affect where sf2 browsing opens to, which is valuable in itself.

**Comment by necrashter** [comment]
Thanks for feedback, sir.

> I believe we found the directory _does_ affect where sf2 browsing opens to, which is valuable in itself.

This seems to be the only function of this setting. But the soundfonts selected from SF2 directory are not saved relatively, i.e. it saves their absolute path. Whereas soundfonts from samples/soundfonts directory are saved relatively.

To be frank, I like the idea of configurable SF2 directory so that multiple programs can use soundfonts from the same directory; however it's poorly implemented right now.

Should we remove this setting and use samples/soundfonts directory, or should we close this pull request and make soundfont paths relative to the SF2 directory?

**Comment by Spekular** [comment]
I believe the correct solution to this is to improve our handling of
relative paths, hence why I argue for keeping the setting. The "only"
problem with that solution is that it's much more difficult than axing the
setting.

**Comment by Spekular** [comment]
Relevant: #5117

**Comment by JohannesLorenz** [comment]
Since #4180 got re-milestoned to 1.3.0, I'll change the PR base from stable-1.2 to master in 7 days. (Or you can also do it now @necrashter)

**Comment by Spekular** [comment]
I'm closing this since I'm pushing to get #5117 merged before the refactor in #5592

**Pull request closed without merging**
