### PR TITLE
Redesign Crossover Equalizer

### PR DESCRIPTION
**Pull request by Umcaruje**
Per #2978 and #2831

Screenshot:
screenshot from 2016-08-22 23 11 41

@RebeccaDeField 

Removed the redundant "M" label next to the mute LED's. The LED behaviour was also reworked to match the rest of the software (Band is muted when the LED is off, same as the mixer).

### CODE REVIEW

**Comment by Spekular** [comment]
The green on the handles is nice, but also seems to suggest "on". Do the
handles gray out when a band is muted?

**Comment by Umcaruje** [comment]
>The green on the handles is nice, but also seems to suggest "on". Do the
handles gray out when a band is muted?

No they don't. The green handles on the FX mixer don't grey out when a band is muted?

Maybe I could change the LED color to blue to avoid confusion.

**Comment by Spekular** [comment]
You're right, I didn't think about that. It's probably fine.

**Comment by Umcaruje** [comment]
screenshot from 2016-08-22 23 40 58

@Spekular is this better?

**Comment by Spekular** [comment]
@Umcaruje I think the original is better, since the LEDs are consistent that way. Since the handles are the same style as the new mixer handles it's fine, I was thinking about the old mixer handles that were gray and thought that a mismatch there might be confusing.

**Comment by Umcaruje** [comment]
@Spekular Yeah, I'm going to keep them green, to be consistent with the Mixer. Graying out the handles is probably an overkill.

**Comment by RebeccaDeField** [comment]
For some reason the box that wraps around the sliders and LEDs doesn't quite look right to me. I might be wrong, but it didn't look pixel perfect when I zoomed in and the borders and highlights seems a bit thicker than what I used elsewhere.

I went ahead and created a new version of the box that matched the plugin bg a little more. Please see the file attached and of course, if you want to modify I will send over the source file :)

artwork

**Comment by Umcaruje** [comment]
@RebeccaDeField thanks for the feedback, I just resized your graphics as a group, which was a bad idea. I rectreated the whole thing from scratch now, since it needed some tweaking. I also want to say that the faders are pixel perfect now too: 
screenshot from 2016-08-26 00 41 24

**Comment by RebeccaDeField** [comment]
@Umcaruje Looks better to me now :+1:

**Pull request merged**
