### PR TITLE
Update spanish translation

### PR DESCRIPTION
**Pull request by tresf**
This is for the `stable 1.1` branch only

Per conversations over at #2359, Performed by @GNUMariano

@DiegoAccorinti, @IvanMaldonado, FYI

### CODE REVIEW

**Comment by Umcaruje** [comment]
@tresf is this translation finished? Can this be merged?

I'm also wondering about why this is targeted at `stable 1.1`, since there aren't any more releases planned for `1.1`, since we are approaching `1.2`

**Comment by tresf** [comment]
> I'm also wondering about why this is targeted at stable 1.1, since there aren't any more releases planned for 1.1, since we are approaching 1.2

It was intended for automated package managers to pick up (pacman, etc).

**Comment by Umcaruje** [comment]
>It was intended for automated package managers to pick up (pacman, etc).

Ah, I see. 

So can this be merged?

**Comment by tresf** [comment]
@Umcaruje Sure.  I have a hard time knowing due to the large amount of deliberation over the quality of this and others at #2359.  :+1:

**Comment by Umcaruje** [comment]
:+1:

**Comment by GNUMariano** [comment]
Hi @Umcaruje, @tresf.
I've made the translations to Spanish for different versions since I was using LMMS since 0.4 and some distros are still packing old versions of LMMS. I also translate the master branch but, since I've noticed you're working really hard on making it stable and there is (?) no deadline for 1.2, I didn't want to bother you with this. When you think it's the right moment to work on that let me know I'll be glad to help (I'm keeping an eye on the development version and I know there are some changes to do on the ES.TS file to keep it fully translated).
Thanks for the hard work. I hope 1.2 will be ready soon!

**Pull request merged**
