### PR TITLE
Theme Tweaks

### PR DESCRIPTION
**Pull request by RebeccaDeField**
In this pull request I have...

- Deleted an unused file.
- Fixed the contrast for the muted led (@tresf)
- Fixed the radius of a rounded corner on the output graph
-Changed colors for sample and automation tracks

For the muted LED I decided to keep the border dark so that it would display well on light backgrounds, but the fill color is now much lighter so that it will display well on dark backgrounds.

### CODE REVIEW

**Comment by RebeccaDeField** [comment]
@Umcaruje @tresf 

**Before:**
8d13bbcc-69da-11e6-904f-8bc4d34cd3e4

51f61ed2-6a4c-11e6-9d13-19835dcc2119

**After:**

**Comment by tresf** [comment]
| Before | After |
|--------|------|
| screen shot 2016-09-17 at 7 48 49 pm | screen shot 2016-09-17 at 7 49 00 pm |

The new artwork is definitely more noticeable in the Spectrum Analyser, I'd say it closes https://github.com/LMMS/lmms/pull/2971#issuecomment-242267060.

**Comment by RebeccaDeField** [comment]
@Umcaruje Updated LED:
eaa69268-7cf5-11e6-8795-cecc109b9c58

@grejppi Updated Sample track:
image

**Comment by tresf** [comment]
That dark purple is nearly the same color as it's background color.  Is there room for improvement there?

**Comment by RebeccaDeField** [comment]
@tresf Now that you point it out, I seem to recall lightening the sample track already some time ago. I compared to an eailer screenshot and when overlayed ontop of eachother is it clear that the sample track color did somehow get darker. I only lightened in this commit so I'm not sure when it happened. I guess it doesn't mater anyway. I will update to the color it has previously been.

68135b9a-26a8-11e6-8e17-65aaf6f42734
New (on the left) and old (on the right)

**Comment by tresf** [comment]
Yes, that's better... 

image

But in fear of sounding picky... it's still quite off when compared to the piano roll contrast against the bg. 

image

**Comment by RebeccaDeField** [comment]
> But in fear of sounding picky
Not a chance! I prefer more detail in feedback and I like working with observant people :)

When the purple is the same value as the green, does it look better to you?
8713ef12-7de9-11e6-9f69-753e97d590ae
vs
8713ef12-7de9-11e6-9f69-753e97d590ae 1

**Comment by tresf** [comment]
Running certain desaturation filters put these colors close together but luminosity filter seems to be very close to what my eyes see.

I'm going to post the results of a color contrast analyser.  This is on par with what my eyes see.  I see the green as being drastically more contrasting versus the purple.

**Green**
```diff
  Foreground:#21A14F
  Background:#14151A

+ The contrast ratio is: 5.4:1

+ Text passed at Level AA
- Text failed at Level AAA
+ Large text passed at Level AA
+ Large text passed at Level AAA
```

**Purple**
```diff
  Foreground:#4B31A1
  Background:#14151A

- The contrast ratio is: 2.0:1

- Text failed at Level AA
- Text failed at Level AAA
- Large text failed at Level AA
- Large text failed at Level AAA
```

**Comment by RebeccaDeField** [comment]
@tresf A couple of thoughts...

This #3F21A1 is the purple with the same value and saturation and the green. The only difference is the hue here. It's not much different so I don't know if it will solve the problem you're having.

The background is not pure gray. It is a blue-gray. Purple is closer to blue than green. This is probably what you're seeing. This is probably what you are seeing. We can (A) make the purple bright enough to compensate for what you're seeing. #6c3fff maybe?? (B) use a different color. #C18204 is the only other color we are using right now in the theme.

**Comment by tresf** [comment]
I'm using [CCA](https://github.com/ThePacielloGroup/CCA-OSX) and I feel it's tests match my eyes (or perhaps my LCD combined with my eyes).

image


Here's the results as screenshots:
image

image

**Comment by RebeccaDeField** [comment]
@tresf How does the orange look in your program?

**Comment by tresf** [comment]
It doesn't start to pass until it hits right around the waveform brightness.

**Comment by RebeccaDeField** [comment]
@tresf And the orange?

**Comment by tresf** [comment]
> And the orange #DE9505?


image

**Comment by RebeccaDeField** [comment]
Here is a scale of colors according to what our eyes sensitivity. As you can see, green and yellow are very high on the scale and purple is quite low. This and the fact that the background color has some blue in it, is probably the cause of what you are seeing here.
669px-eyesensitivity svg

If we did switch to orange, it would look something like this:
8a8bffa2-7dd2-11e6-9558-c59947139e47

**Comment by tresf** [comment]
They both look closer to the green, which I find to be very visible. 👍

**Comment by Umcaruje** [comment]
I find the orange one nicer 👍

**Comment by RebeccaDeField** [comment]
@Umcaruje Thank you for the feedback. I'm going to code up both the orange and purple options alongside the other colors in the program so that we can see how everything looks together and make a decision. :)

**Comment by RebeccaDeField** [comment]
Okay, here are our options for a more visible sample track:

**Option 1:**
purplelight
The purple is very visible, however it is going on the verge of lavender and I'm not sure it fits within the theme.

If we were to go with purple, this is probably the lightest we could go to keep everything looking cohesive:
purplemedium

**Option 2:**
orange
Orange is personally not my favorite color, but it  would definitely tie in the new website design and the stereophonic matrix redesign.

Opinions? What option do you like best?
@Umcaruje @tresf @BaraMGB @grejppi @LocoMatt @zonkmachine

**Comment by BaraMGB** [comment]
Yes, the orange looks sweet.

**Comment by grejppi** [comment]
Orange looks a lot better than purple to me 👍

The screenshot raises two concerns however:
1. The markers within a b&b clip are dark on the top and light on the bottom. This made sense when there was a gradient but not a lot anymore. Also they are not really visible unlike those in note clips which have good contrast
2. All the other clip types represent their contents with a lighter shade now except automation clips

**Comment by BaraMGB** [comment]
> All the other clip types represent their contents with a lighter shade now except automation clips

👍

**Comment by RebeccaDeField** [comment]
Orange it is!

@grejppi You bring up some great points.
The markers within a b&b clip are dark on the top and light on the bottom.

This should definitely changed, however I believe it is hard coded. Does anyone know where or how to change this element?


> All the other clip types represent their contents with a lighter shade now except automation clips

I actually was just thinking about this this morning. I will go ahead and change it to match.

**Comment by Umcaruje** [comment]
>This should definitely changed, however I believe it is hard coded. Does anyone know where or how to change this element?

I'll do that. I'm getting home from my trip on tomorrow evening

**Comment by Umcaruje** [comment]
I don't particularly like the color red for the automation tracks, and am kinda used to how the automation tracks were purple in the previous theme. So here's an idea: Use the colors from Option 1 in your comments as the color for automation clips?

I think that would work. I like the lighter, more lavender color more personally.

**Comment by RebeccaDeField** [comment]
> So here's an idea: Use the colors from Option 1 in your comments as the color for automation clips?

I will give that a try and see how it looks. :+1:

**Comment by musikBear** [comment]
@RebeccaDeField 
> @tresf How does the orange look in your program? How light does the purple need to be to pass?

FYI: You can also get this service online
https://snook.ca/technical/colour_contrast/colour.html#fg=5256FF,bg=FBC532

**Comment by RebeccaDeField** [comment]
@musikBear Thanks for the link :+1: 

@Umcaruje tried your idea of using the purple for the automation tracks. I tweaked the purple background color to have a contrast ratio of 3.06 which meets the requirement for large text and this element is much larger than what is considered large text by those standards (14pt bolded text for example.)



I believe these updated colors are very visible and have much higher contrast when compared to the colors that were in place before:

**Comment by BaraMGB** [comment]
:thumbsup great!

**Comment by Umcaruje** [comment]
Great job @RebeccaDeField that's awesome. Though I'd have the background color just a bit darker

**Comment by RebeccaDeField** [comment]
@Umcaruje Lightened the sample foreground and made sure it didn't clash with the selected color as we talked about. I would appreciate it if someone reviewed this PR.

**Comment by BaraMGB** [comment]
I get a terminal debug output when I add a fader in mixer:
Fader(0x2ed3270)  does not have a property named  "peakYellow"

**Comment by RebeccaDeField** [comment]
@baramgb I did not remove that, but I believe these errors occurred because I created this commit at about the same time that the new fader design was merged. Thanks for testing, I think I can fix it.

**Comment by RebeccaDeField** [comment]
@BaraMGB If you would kindly test again please :)

**Comment by BaraMGB** [comment]
For me it looks okay, now. If no one else chime in here, I would merge this in few hours.

**Comment by Umcaruje** [comment]
screenshot from 2016-10-04 12 05 01
screenshot from 2016-10-04 12 06 13

This looks awesome to me. Merging.

**Pull request merged**
