### PR TITLE
Fix too small height of the carla instrument window

### LINKED ISSUE #5828: Carla instruments - Add effect button missing and related size issues
### Bug Summary

Carla Rack and Carla Patchbay miss the "Add effect" button in the FX rack. They also different in size to other plugins and the lower parts of the other tab windows are cut off.

#### Steps to reproduce

Open one of the Carla instruments and drag them above another instrument. Now go through the tabs one by one.

#### Affected LMMS versions

master probably since https://github.com/LMMS/lmms/pull/4906

carla2

### PR DESCRIPTION
**Pull request by PhysSong**
Fixes #5828.

### CODE REVIEW

**Comment by zonkmachine** [comment]
It also affects the behavior of https://github.com/LMMS/lmms/issues/5827 so they seem related after all.

**Comment by PhysSong** [comment]
> It also affects the behavior of #5827

How?

**Comment by zonkmachine** [comment]
> How?

You can now easily grab/drag the plugin, so that's a fix. The cursor behavior has changed a bit though. For instance, earlier you had the hand when you were over the canvas and now it's the arrow. That sounds about right. In the FX Mixer you used to have the hand over the "Add channel" button and now it's the arrow. In the Song Editor you now create a track content objects with the arrow and it used to be the hand cursor. Now when the tco exists it's once more the hand cursor when you move over it. Things like that.

**Comment by zonkmachine** [comment]
OK. I get it now. I saw changes in the rest of lmms but this is because once you open one of the Carla instruments, they won't give you back the arrow. It looks like this persists for the rest of the session.

Merge?

**Review by zonkmachine — APPROVED** [review]

**Pull request merged**
