### PR TITLE
Fix apple install script for zyn interface

### LINKED ISSUE #6781: ZynAddSubFX is broken on MacOS
Quoting Discord:

The file `libZynAddSubFxCore.dylib` is never getting built on `master` for MacOS.

Reverting MSVC support for Zyn (d95c897 + https://github.com/LMMS/zynaddsubfx/commit/551e816a6334fd190c74ce971378063b2757b47b) brings this file back to where it's supposed to be.

Running `make install`

BEFORE:

```
Creating App Bundle "/Users/owner/lmms/build/LMMS.app"...

Finished.
```

AFTER:
```diff
Creating App Bundle "/Users/owner/lmms/build/LMMS.app"...
- mv: Cannot find file "/Users/owner/lmms/build/LMMS.app/Contents/lib/lmms/libZynAddSubFxCore.dylib"
```

### PR DESCRIPTION
**Pull request by tresf**
Attempts to close #6781

### CODE REVIEW

**Comment by tresf** [comment]
For some reason starting `LMMS.app` simply crashes on MacOS, however when run through `lldb`, Zyn builds and starts, but the GUI won't show.  Here's the logs:

```
2023-07-30 14:46:35.794698-0400 lmms[49438:6059466] [default] CGSWindowShmemCreateWithPort failed on port 0
2023-07-30 14:46:35.880820-0400 lmms[49438:6059466] applyPortMode displayName:''
2023-07-30 14:46:36.274772-0400 lmms[49438:6059466] applyPortMode displayName:''
2023-07-30 14:46:36.689394-0400 lmms[49438:6059466] [default] CGSWindowShmemCreateWithPort failed on port 0
2023-07-30 14:46:37.337677-0400 lmms[49438:6059466] [default] CGSWindowShmemCreateWithPort failed on port 0
2023-07-30 14:46:39.789573-0400 lmms[49438:6059466] applyPortMode displayName:''
2023-07-30 14:46:39.845037-0400 lmms[49438:6060086] QtXmlWrapper::loadXMLfile(): empty data
2023-07-30 14:46:41.732596-0400 lmms[49438:6059466] Unexpected poll error.
2023-07-30 14:46:41.732655-0400 lmms[49438:6060163] Process error:  QProcess::Crashed
Error while writing.
2023-07-30 14:46:41.732683-0400 lmms[49438:6060163] Remote plugin crashed
remote plugin died! invalidating now.
```

**Comment by tresf** [comment]
It's working locally after adding code signing via 00f48fb.

**Comment by tresf** [comment]
Works from artifacts, just need to remove the quarantine flag:
```bash
sudo xattr -r -d com.apple.quarantine /Applications/LMMS.app
```

**Comment by DomClark** [comment]
Currently, we ignore the result of this script when building the install target. I think we should change it so that if this script fails, the install target fails too. I didn't catch this myself because I don't have a Mac to test on and CI passed for my changes, whereas ideally this would result in a CI failure.

**Comment by tresf** [comment]
> Currently, we ignore the result of this script when building the install target. I think we should change it so that if this script fails, the install target fails too. I didn't catch this myself because I don't have a Mac to test on and CI passed for my changes, whereas ideally this would result in a CI failure.

Done via https://github.com/LMMS/lmms/pull/6796.

**Pull request merged**
