### PR TITLE
Fix EffectRackView appearance (GUI).

### PR DESCRIPTION
**Pull request by DigArtRoks**
* Elide the name of the effect when it tends to be too big. (#5752)
* Evenly space the controls (W/D, Decay Gate). (#5750)
* Show the scrollbar in the default theme to close the gap. (#5752)
* Reduce the gap between the effect and the scrollbar. (#5757)
* Use always the same width for the EffectRackview (InstrumentTrack and SampleTrack) to avoid gaps or cutoffs of the background.
* Widen the background in the default theme.
* Widen the embossed space in the background in the classic theme to fit the controls.

afbeelding afbeelding

### CODE REVIEW

**Comment by superpaik** [comment]
It seems perfect to me. Tested on W10/64 bits (both MSVC and Mingw) and with different display resolutions.
Just one comment. You said (point 5): Use always the same width for the EffectRackview (InstrumentTrack and SampleTrack) to avoid gaps or cutoffs of the background.
I think that applies to Effects Chain in FX mixer as well. Or at least the width seems to be the same, which I find correct.

Thanks.

**Comment by DigArtRoks** [comment]
Thansk for trying it out.

Yes the width of the EffectRackView is now the same for FxMixer, InstrumentTrack and SampleTrack.

I initially thought the issue was flagged for the FxMixer alone. After fixing that one, I still saw similar issues in the InstrumentTrack and SampleTrack. Hence my comment in point 5 only referring to the latter 2.

It turned out that for the 3 locations where the EffectRackView is used different widths (and heights) are used. So I fixed the width for all 3 to the same value. The widget does not really allow horizontal resizing due to the fixed background that is used for an EffectView. Either more space between the EffectView and the scrollbar appears or the background is cropped.

The width remains as was for the FxMixer, gets 5 pixels wider for the SampleTrack (which still fits) and is reduced about 5 pixels in the InstrumentTrack.

**Comment by Spekular** [comment]
I've put together a before and after (Ignore the fact that my before image doesn't gray out disabled knobs):
image

I think the classic theme effects now end up a bit too close to the scrollbar, I reckon around halfway between the old width and the new one would look good.

Similarly, I perceive the right side padding on the default theme effects to be narrower than the left, even though they're both 4 pixels. Perhaps 5 pixels on the left would give the scrollbar a little more space to breathe (since it stands out more than the outline). Here's a mockup + comparison of how that would look:
image
(PR on the left, mockup on the right, space in the middle so you can focus on one at a time)

**Review by DomClark — APPROVED** [review]
Code looks good.

I do wonder, however, whether the knobs are a little too far apart now. Also, it looks like a dark line has appeared at the bottom right of the classic theme effect background, although it's not very noticeable.

**Comment by DigArtRoks** [comment]
Thanks for the reviews.

I did an additional commit.
* Reduce the background for the default theme by 1 pixel.
* Reduce the background for the classic theme by 2 pixels and remove the darker line at the bottom right.
* Reduce the width of long names of the plugin also by 2 pixels.
* Put the controls 2 pixels closer to each other.

This is how it looks now:
afbeelding afbeelding

**Comment by superpaik** [comment]
Yeah, much better now!

**Review by Spekular — APPROVED** [review]
LGTM both code and design wise.

**Comment by sound8** [comment]
I was freaking out because I found a whole bunch of other little things to go with my posts, I created all these graphics, I rushed here to tell you guys....  and then I found this page where you not only found them all but applied them! :)
Wow, excellent job guys, everything looks great
Thank You for all this work.

**Comment by Spekular** [comment]
> Should I close my original posts?

We usually only close issues when the fix is merged, so leave it open :)

**Comment by Spekular** [comment]
Actually though, Dom gave the changes after his latest review a thumbs up reaction, so I suppose this has two up to date + passing reviews and no CI failures. Merging!

**Pull request merged**
