### PR TITLE
makes Subwindow title label transparent for mouse events

### PR DESCRIPTION
**Pull request by BaraMGB**
closes https://github.com/LMMS/lmms/issues/2823

### CODE REVIEW

**Comment by jasp00** [comment]
It works for the title bar, but the resize action is still active when moving to the minimize, maximize and close buttons.

**Comment by BaraMGB** [comment]
Okay, I updated. Here it works proper now.

**Comment by jasp00** [comment]
Setting the cursor hides the problem. If you start to drag inside a button and get outside of it, a resize is performed, sometimes the window moves.

**Comment by BaraMGB** [comment]
I can not reproduce here on Ubuntu build qt5. Which configuration do you use? 
@jasp00

**Comment by jasp00** [comment]
Qt 4.8.7.

**Comment by liushuyu** [comment]
@BaraMGB Maybe you could try to insert 

```CPP
m_*Btn->setAttribute( Qt::WA_NoMousePropagation ); //Replace `*' with respective names
```
after setting the mouse cursor.

This worked for me (GCC 6.1.1 20160501, Qt 4.8.7; Plasma KDE 5, KWin Windows Manager, KDE Framework  5.22.0, xcb)

**Comment by BaraMGB** [comment]
Have you tried to drag around? This bug is difficult to reproduce. I hope it works with your suggestion.

**Comment by BaraMGB** [comment]
@liushuyu That seems to work! 
@jasp00 please test again.

**Comment by jasp00** [comment]
It makes sense and works.

**Comment by BaraMGB** [comment]
@jasp00 :+1: 
@liushuyu Thank you very much! :grinning:

**Pull request merged**
