### PR TITLE
Make the instrument section of the sidebar themeable

### LINKED ISSUE #2329: Instrument section base color
The Instrument section is not the same base color as the other sections, is there any reason for this?

qjiorzp     
xezj4ss

### PR DESCRIPTION
**Pull request by Umcaruje**
Fixes #2329 

Based off of @michaelgregorius's patch: https://github.com/LMMS/lmms/issues/2329#issuecomment-138976075

You can do this now: 
screenshot from 2016-02-05 01 30 44

As always, testing and comments welcome.

### CODE REVIEW

**Comment by IvanMaldonado** [comment]
Thank you very much!

**Comment by Wallacoloo** [comment]
:+1: Works as expected on my system, and the default look remains unchanged.

There's no reason *not* to move color constants & such out of the code, so I'm very in support of these changes.

**Comment by Umcaruje** [comment]
No objections in over a week, and it works for @Wallacoloo.

Merging.

**Comment by IvanMaldonado** [comment]
Is this comment still necessary?

captura de pantalla_2016-03-06_20-53-05

**Comment by tresf** [comment]
@IvanMaldonado IMO, yes, until we get double-click support like the rest of the side-bar items. :+1:

**Pull request merged**
