### PR TITLE
Envelopes are on now by default

### PR DESCRIPTION
**Pull request by mikobuntu**
~~fixes~~ Temporary workaround for #3086

I set a minimal attack just to quash any artefacts caused by a loud instrument, which i believe 0.002 secs will not be noticeable or feel like there is any delay until the audio starts. I set both Hold and Decay to 0 so that we only hear sound as long as a key is pressed. Sustain was obviously set to full i.e 1 to allow the note to hold while being pressed and most importantly release was kept at the default of 0.1 , which seemed to give the best results ( no clicks on key release ) [ smaller values might work ]. 
Setting m_amountModel to 1.0 ensures that amount of the Envelope is at maximum ( which switches it on by default ).

### CODE REVIEW

**Comment by simonvanderveldt** [comment]
imho this doesn't "fix" the issue, it introduces a workaround.
This gives an example how to actually fix it https://github.com/LMMS/lmms/issues/3086#issuecomment-255605414

**Comment by mikobuntu** [comment]
@simonvanderveldt my sentiments exactly. I should have called my pull request a workaround. As you can see from my posts in the thread I would prefer a proper fix for this issue. It will not be hard to revert my patch if/when someone codes this.

**Comment by simonvanderveldt** [comment]
> @simonvanderveldt my sentiments exactly. I should have called my pull request a workaround. As you can see from my posts in the thread I would prefer a proper fix for this issue. It will not be hard to revert my patch if/when someone codes this.

Awesome! Just making sure we don't forget to fix the issue :)

**Comment by mikobuntu** [comment]
@simonvanderveldt Yes that makes sense to comment on how I came to my settings, I will update the description to reflect this. :)

**Comment by grejppi** [comment]
So, uh, what would you say a proper fix would be like then? If something like this was applied to 0% envelope that wouldn't really be 0% anymore would it? I'm confused...

**Comment by mikobuntu** [comment]
@grejppi I seem to be good at confusing people :)
My 'proper fix' I was referring to was like @fundamental said in ZASF 

> Any rapid change in volume within zyn results in an interpolation from the current value to the destination value over the course of a processing unit (buffersize in zyn terms). Just a simple linear interpolation to zero over 32 samples should be plenty to avoid the clicking.

As for your comment about 0% envelope, now I'm confused..... can you elaborate thanks :gear:

**Comment by mikobuntu** [comment]
I have been thinking that I could possibly add to this PR, by allowing the user to choose whether or not to have envelopes off/on in the settings config. This would take a bit of research by myself. It might be also be possible to actually set the default envelope values within the configure too.

**Comment by Umcaruje** [comment]
Please don't do that, if a user does not want an envelope he can simply
turn it off. This is about having more sane defaults and I think this issue
accomplishes that as is.

**Comment by musikBear** [comment]
@Umcaruje wrote
> This is about having more sane defaults 
:+1: 

With that in mind, i hope a simple waveform combo also is chosen in 3oc, because my feel is that it is important that the very first sound the user hear when he press a note, is an *instrumental* sound, and not the sine sound from a test-tv-picture.
It is equally important that the sound is not clipping, eg it should be less loud than current default 3oc
So : 
* Nice instrumental envelope
* Instrumental wave-shapes
* Pleasant loudness
Would be my preferred default 3oc

**Comment by Spekular** [comment]
@musikbear I'd argue for keeping the sine wave. The default preset
dhouldn't sound good so much as have the most basic settings, imo. An
envelope on by default goes a bit against this, but as I'm assuming it's
there to prevent pops/clicks I'd consider it justified.

**Comment by mikobuntu** [comment]
@musikBear 

> Nice instrumental envelope

I prefer just to have the raw waveform, I mean to have only the waveform play as long as a key is held, I'm kind of using ZASF for comparison here.

> Instrumental wave-shapes

I think presets cover this for now.

> Pleasant loudness

I 100% agree with your point here. We should really think about the new user here who might be trying just a few default instruments and at the moment iirc a kicker and a triple_osc played together will be clipping/distorting. Perhaps a new issue should be opened for " _sane defaults for all instrument's loudness_ " or something to that effect?

**Comment by grejppi** [comment]
> Perhaps a new issue should be opened for " *sane defaults for all instrument's loudness* " or something to that effect?

...also known as #113 👍

**Comment by Umcaruje** [comment]
Are there any objections to this PR? I think its very important to have sane defaults, and will merge if there are no objections

**Comment by tresf** [comment]
> Are there any objections to this PR

None, we can pick up any complains in RC2 testing.

**Comment by tresf** [comment]
Actually... what about instruments that can't use envelope, would we want them excluded from this logic to avoid confusing in the mmpz or don't we even care?

**Comment by zonkmachine** [comment]
I haven't tested it and I'm away from my build machine, but that sure looks like better default settings. Pro merge.

**Comment by Spekular** [comment]
I've been meaning to ask actually, why is it that envelopes don't work on
some instruments? Amplitude modulation and filtering should work on
anything, right?

**Comment by Umcaruje** [comment]
@Spekular IIRC, and I might be wrong, MIDI based instruments don't have envelopes because we wouldn't know how to handle polyphony on them. Each note/stream is going through an envelope seperately for native instruments, while for midi based instruments all is in the same stream, so when you press 2 notes LMMS couldn't envelope those 2 notes separately.

**Comment by Spekular** [comment]
@Umcaruje oh, duh, I should have thought about that. Would it be possible
to convert user input to only play one note at a time? Like, keep only the
first or latest note when several are played at once. Then we could have a
toggleable "monophony w/ envelopes" mode.

Filters w/o envelopes should be able to work either way, too.

**Comment by Umcaruje** [comment]
>@Umcaruje oh, duh, I should have thought about that. Would it be possible
to convert user input to only play one note at a time? Like, keep only the
first or latest note when several are played at once. Then we could have a
toggleable "monophony w/ envelopes" mode.

>Filters w/o envelopes should be able to work either way, too.

This is a conversation that should happen in a seperate issue.

**Comment by tresf** [comment]
Just an FYI, I feel we may have increased complaints about this issue https://github.com/LMMS/lmms/issues/1592 for very long notes.  AFAIK, they are bugged if they're longer than a certain length, which a default envelope will expose more.

**Comment by Umcaruje** [comment]
>Just an FYI, I feel we may have increased complaints about this issue #1592 for very long notes (AFP specifically). AFAIK, they are bugged if they're longer than a certain length, exposed by the envelope's limited cut-off time.

Is there an clear open issue about that bug?

**Comment by tresf** [comment]
> Is there an clear open issue about that bug?

Couldn't find one.  I believe it was incorrectly consolidated midst the Reaper10 issue spamming.

**Comment by musikBear** [comment]
> Is there an clear open issue about that bug?

Not sure they are 'clear' but candidates could be:
directly: 2092
indirectly 113
dont want to associate in excess, so i omit '#'
You decide

**Pull request merged**
