### PR TITLE
Full spanish translation  (Argentina)

### PR DESCRIPTION
**Pull request by DiegoAccorinti**
From Huayra gnu/Linux team we have full translate LMMS to spanish (Argentina) beacuse he current Spanish translation was very incomplete, less than 50%

### CODE REVIEW

**Comment by tresf** [comment]
@DiegoAccorinti how close is Argentina to native Spanish?

If they are different, I believe we may want to add this as `es_AR.ts` or something similar.  @Umcaruje @Lukas-W do you have any experience with locale variants?  Currently we only have two-letter files.

If we decide to keep a single Spanish translation, we'll have to merge this with that which was submitted on our mailing list this week.  The submitter translated all of our branches including our current stable and our master branch so that all versions could benefit from this language change.

Here's the master copy if you'd like to do a comparison against your own:

https://gist.github.com/tresf/23ae38700cf67b5d79a6

**Before**

untitled

**After**

capture

**Comment by IvanMaldonado** [comment]
We could use two Spanish translations for this, Latin American and European. 

This is how many things are translated into Spanish, from movies, videogames, etc... 

I am also working on the Spanish and Portuguese translations, the last Spanish translations lmms had, had some mistakes like "desintonización" (which means detuning as if you were using a radio) instead of "desafinación" (for piano detuning) what makes me think they used literal translations for everything and this is not how translations work, we have to know what we are talking about. 

I would like to check this translation, this could be merged as the Latin American version.

**Comment by DiegoAccorinti** [comment]
I have not used literal translations, but I'm not a translator then you may have some errors, such as "detune".
 Sounds like a good idea to have a branch "es-LA" bone-Latin American Spanish, but the differences are small so we must not resign ourselves to use Spanish from Spain.

Here in Argentina we use "es-AR" as locale. Good would include a "es-AR".
greetings

**Comment by tresf** [comment]
@DiegoAccorinti @IvanMaldonado do you want me to wait for you to review the [`es.ts`](https://gist.githubusercontent.com/tresf/23ae38700cf67b5d79a6/raw/c6a5e3a5f00a7e130e83c3c3ca3d29cd30edd13d/es.ts%2520-%2520master%2520Branch) that was submitted via email prior to making a decision on merging?

If this is better for `es-ES`, then shall we adjust the pull request to reflect `es-AR` (I'm not sure that `es-LA` is a valid locale name).

**Comment by IvanMaldonado** [comment]
I'm on it.

@DiegoAccorinti You and your team did an awesome job I have to admit, there is an inconsistency though. Sometimes indications are given formally and sometimes informally e. g.

<b>Formal indication:</b>
Arrastre un control manteniendo Ctrl presionado

<b>Informal indication:</b>
Haz click aquí para mostrar u ocultar la ventana de notas del proyecto. En esta ventana puedes escribir notas, comentarios y recordatorios de tu proyecto.

I could fix this if you want, I don't know by far which form is more used, but I think we should use the formal one, most programs I remember use the formal way.

I'm also changing some words I will put here so we can debate if the changes are good.

Greetings.

**Comment by GNUMariano** [comment]
Hi!
I made the translation to es (AR), because the pre-packaged version for Linux and windows was actually less than 10% correctly translated (I'm not saying my translation is perfect. It needs to be revisited. But it's correct, I know that). Even the pop-up file menu is half translated. I'been waiting for LMMS to be translated in Spanish for a long time, that's why I decided to help.
I'm an actual musician, and a music teacher, and a user [of LMMS] of course.
The main challenge here it's that we (native Spanish-speakers) always adopt English words when we don't know exactly what they mean or find'em hard to translate (guitarists here always use words like 'sustain', 'slide', etc, )
I've noticed the [minor] formal/informal inconsistency (in fact they appeared more often before I revisited for the first time) and I'll gladly correct this if it makes a better translation. [BTW even pro-commercial software often have this same inconsistency. It's a hard choice every time because 'Do this' can be translated equally --> 'Haz esto / Haga esto / Hacé esto'....) I've noticed the original translation to ES was not made by a musician (here the difference between 'desintonización' and 'desafinación' for the Englisn 'detune', for example). I've tried to correct this.
All suggestions are welcome. I just hope it helped.

Thanks!

**Comment by tresf** [comment]
To put @GNUMariano's message into context, it's Mariano Macri from the mailing list regarding these translations:

https://gist.github.com/tresf/23ae38700cf67b5d79a6

**Comment by IvanMaldonado** [comment]
@GNUMariano Greetings, first of all, you did an awesome work with the translation, there are some things I was struggling with and you made them far more clear than I ever could. Congratulations. 

Here are some observations I made of your work:

http://pastebin.com/54ceZpfU

Keep up the good work and thanks for helping lmms!

**Comment by GNUMariano** [comment]
Thank you for taking your time checking out my translations.
I would like to improve it, making it all more consistent (in the way to
address the user).
Besides, there are some technical terms that are very difficult to
translate because:
A wrong translation is already widespread among musicians (in other DAWs,
in the studio, etc)
Or sometimes we've learn wrong terms [yet accepted] instead of the right
ones in our native language-
For example, when we think of 'sensitivity', we often think of how 'hard'
or 'soft' we hit a key/string/drum. And really it's how 'fast/slow' we do
that what really affects volume, etc. That's why we aren't used to the term
'velocity'.

In response to your observations, they are correct. Let's take it one by
one:


Se requiere el plugin LADSPA desconocido %1. -> Se requiere un plugin
LADSPA desconocido %1.

Yes, the use of the indefinite article i'ts possible more appropriate.
Still, the definite article is not wrong here because the required plugin
in not *any *plugin, but *the* plugin %1.  Even if it's not wrong, I agree
that 'un' applies here better than 'el'.

Principal -> Maestro

I totally agree with that! I also commented it in the **.ts that 'Maestro'
it's a better translation that 'Principal'. I only heard 'principal' in a
few studios. 'Maestro' is not only correct, but cooler!!!

"Por lo tando"....Eh... my mistake, this one is a typo!

Elige imágenes para el fondo -> Elige una imagen para el fondo

I had trouble with this [...*choose background artwork...*] because in
Spanish we don't use any word that can correctly be translated as 'artwork'
(I mean, as it is used here. It can refer to a singe image or a vast group
of images as well). But I agree again that 'Elige una imagen de fondo [or
'para el fondo']' is way better.

Elige un directorio de instalación de FL-Studio -> Elige el directorio de
instalación de FL-Studio

You're right. Here the definite article is the right choice.

Base Velocity -> Velocidad de base

Well, this is a tough one. Here 'base-velocity' is really the 'velocity
normalization base' for MIDI based instruments. Musicians who are used to
play MIDI instruments are familiar with the term 'velocity'. while
traditional musicians think in terms of dynamic (you know, piano - forte -
etc). But here, this doesn't refer to the velocity itself. but the base
used for the *normalization* of the velocity (could it be more
complicated?)
This works like this: the higher you set this parameter, the more
normalization you get, making the performance smoother, but you'll loose
the 'fortissimo' and the 'pianissimo' (so you loose expressiveness). So, if
you are a really expressive artist who has a first-class MIDI input device,
set a low value for this setting. Other way, if you're looking for a
smooth, even sound (even in terms of *volume*), use a higher value.
I think this shouldn't be translated as 'base-velocity'. Instead we
(Spanish-speakers) should think of this as the 'normalization-base'.
I came up with 'Base de normalización' for this one. But I just didn't dare
to make such a change without asking first.

I think that, since it goes below the input field for the user to specify
the velocity normalization base, it could be either

velocidad
normalización
velocidad básica
velocidad de base
media de normalización

But it also has to be in concordance with the title and the explanation
within that box, and we have some limited space here, that's why I used
'velocidad básica' although I prefered 'Normalización' (''velocidad base
para la normalización' is too long and unnecessary because an explanation
[that really doesn't explain too much, really] is right there.
(I've also noticed I made a typo in the text inside the box: I put 'bse'
instead of 'base' ! )

In my opinion, to have a really comprehensive translation, we should change
it drastically, like this:

CUSTOM BASE VELOCITY -----> NORMALIZACIÓN (PERSONALIZADA*)
BASE VELOCITY-------------------> NORMALIZACIÓN

Specify the velocity normalization base for MIDI-based instruments at note
volume 100%


'Especifique la normalización de velocidad para los instrumentos MIDI a
volumen de nota del 100%.'


in Spanish, we don't say MIDI-based nor MIDI-controlled instrument. We
simply say MIDI instrument (which I know is wrong, but it's hard to change
old habits).

Also 'PERSONALIZADA (CUSTOM)' isn't needed here. It's obvious that the user
will set this value to his / her preference.


Well, that's (almost) all.

I still want to take another look at the translation. I think that terms
like 'slope' and all the envelope related words and explanations could be
even better translated. Here we are too used to the English words for that
area, and it's difficult to decide if it's better to translate or to keep
the English original. That's not a decision one person can [or must] take
by its own.


I hope mine is one more opinion that helps the general consensus.


PS: I'll keep an eye on the next release. I've sent a translation for the
master branch but I'm sure there still will be some changes to do and there
are a few sentences I couldn't translate since I couldn't compile it
successfully yet!


PS: I couldn't come up with something appropriate for 'In place broken'
(it's on the LADSPA plugins browser window)


Again, thank you all for your time and for developing and sharing this
great DAW.

I'll try to help as much as I can.

And thank you, Ivan, for the feedback. I'm glad I could help.


Next in my agenda: Update the [*translation of the*] Wiki and *[I'll try to*]
upload some video-tutorials and share some projects.


Long Live LMMS!

**Comment by GNUMariano** [comment]
I almost forget it! Thanks, Tres, for the help and putting my message into context. I've just joined to Github today and this is all new for me. This are my first steps helping the free-software community.
I've got a great free-as-in-freedom OS, a great collection of free software, and an awesome community that helped me when I needed it. I just want to give something back.

**Comment by IvanMaldonado** [comment]
@GNUMariano It was a pleassure to help you, I know it's hard to translate some stuff we are so used to (I personally am an enemy of naming english concepts in spanish) but we can always find a way.

If you need any help or if you're not sure about how to translate something, you can post it right here, I'll be checking this thread.

@tresf I don't think LMMS 1.2 will be released anytime soon, so can we wait to merge this? until we're sure this is translated the best way possible (as I can see, the translaton is almost done though).

**Comment by tresf** [comment]
> @tresf I don't think LMMS 1.2 will be released anytime soon, so can we wait to merge this?

:+1:

**Comment by GNUMariano** [comment]
Great! I'll keep working on it. It's good to know that, if I'm not very sure of something, I can ask you here. 
Let's make a great and useful translation so musicians and students can enjoy LMMS as we do!

**Comment by GNUMariano** [comment]
HI!

I'm reviewing the translation to make it clearer and more consistent. As you know, an English sentence like:
"You can drag this element" can be translated in several ways.
1).- "Puede arrastrar este elemento" (formal: subject = Ud. [tácito])
2).- "Puedes arrastar este elemento" (informal, casual: subject = tu [tácito])
3).- "Podés arrastrar este elemento" (informal, casual, [Argentina] subject = vos [tácito])
(there are also even more familiar ways but, they are not appropriate for addressing the user)

1 and 2 are used both in Spain and Latin America. 3 is very restrictive because it's only used in Argentina and Uruguay (Although it would be awesome having the chance to choose a more specific localization: es.ES, es.LA and es.AR).
Because the English form it's the same for both cases, and is the context (and inflection and...) what makes it formal or casual, my question is: What should be the preferred form for translation? Would people at LMMS like to address the user in a friendly way?
PS: I personally think #2 is the best choice right now (neither too formal nor too casual), but I like to make later an es.AR (#3) for us in Argentina.

**Comment by tresf** [comment]
I can't speak to the Spanish portions, but casual is the direction of most software and it is just fine when used in a consistent format.

For example:

"Error loading page."

    vs.

"Whoops!  Something went wrong."

The latter is generally preferred in modern software as it is mote friendly, although the project doesn't have any official preference or policy on formality currently, so whatever you decide is what we will use. :)

**Comment by IvanMaldonado** [comment]
The thing here is about how we should refer to the User "Du vs Sie" in German "Tu vs Vous" in French. 

For practical reasons, both are correct and I don't think anyone would feel offended if they are being refered informally. On top of this, consistency is what matters. 

Many Software is moving to informal ways anyway (like the woops example).

For an Argentinian version, how much will change? Just the conjugation? If you think this will make the Argentinian User more confortable, it's fine I guess.

**Comment by GNUMariano** [comment]
Thank you. Both comments were very helpful. I've noticed that in the next release, the source text has changed a little and it's even more casual and concise. 
Spanish has too many variants, and English too. But the neutral form is intelligible for almost everyone.
I'll keep it that way (casual and neutral) but I'll correct those lines I translated in a formal way.
I'll post here the ones I can't translate.
Thanks for the help.

**Comment by GNUMariano** [comment]
Once this neutral translation is done and merged I'll make the es.AR.

**Comment by GNUMariano** [comment]
Hi again!

I've just downloaded the "es.ts" that send @DiegoAccorinti and check it out in QT 4 Linguist...
Don't get me wrong, I want to be polite. But that translation contains too many errors. I don't want to point to a specific error because there are too many. Really. Besides it has fewer lines that the original es.ts file from LMMS 1.0.3..., I don't know what version do they translate, it sure isn't the 1.1.3.
That file has only 1,556 lines.
The es.ts from 1.0.3 has 1,646 lines.
The es.ts from 1.1.3 has 1,978 lines.
The one for the master branch has 2,302 lines.

Many lines aren't even translated, just copy-paste the English source (if you want to keep the English source, just leave the blank space. When you copy & paste the source and mark it as translated you only make it seem as it's fully translated, but it's not. )

There's no way that file can be used in LMMS. I guess the people at Huayra Linux just wanted to help. But this is far from helpful. This kind of translations will only confuse the user. Besides this will promote the language misuse among students. I can't believe that "that" came from the team in charge of a distro supposedly aimed at local students. It's a shame.

Even if you Google-translate it you'll get a better one.
Sorry. I didn't want to be rude, but I just can't believe what I've seen on that... file.

**Comment by DiegoAccorinti** [comment]
@GNUMariano I think you're being disrespectful. If you do not like the translation makes better, because you have not belittle my work. Spanish language file was translated into 50%. You provided no you anything until I got the full translation, so now you're judge translations, please! .. If you want to make do with work, no disrespect.

@GNUMariano  me parece que estás faltando el respeto.   Si no te gusta la traducción hacé una mejor, no tenés porque menospreciar mi trabajo.  EL archivo de idioma español estaba traducido al 50%.   Vos no aportaste nada hasta que yo subí la traducción completa, entonces ahora sos juez de traducciones, por favor!..    si querés aportar hacelo con trabajo, no faltando el respeto. 

@GNUMariano  -> Public contributions 0

**Comment by tresf** [comment]
> I guess the people at Huayra Linux just wanted to help. But this is far from helpful. This kind of translations will only confuse the user. Besides this will promote the language misuse among students. I can't believe that "that" came from the team in charge of a distro supposedly aimed at local students. It's a shame.

> Even if you Google-translate it you'll get a better one.

I'm in agreement with @DiegoAccorinti, @GNUMariano, this is a poor choice of words directed at people simply trying to help.  Let's please focus on the translation and be more sensitive in how we express our disagreements.

**Comment by GNUMariano** [comment]
Hi @DiegoAccorinti .
If it seems disrespectful I apologize. That was NOT my intention.

**Comment by DiegoAccorinti** [comment]
@tresf  tnks!
@GNUMariano  I accept your apology, we do together the best translation for LMMS continue to grow and more and more people disfute this great application.
I am available for whatever you need.

hacepto tus disculpas,  hagamos entre todos la mejor traducción para que LMMS siga creciendo y cada vez más gente disfute esta gran aplicación.
Estoy a disposición para lo que necesiten.

Diego.

**Comment by GNUMariano** [comment]
Thank you @DiegoAccorinti , I also want us to work together to get the best possible result. 

I also want to apologize to @tresf , @IvanMaldonado and everyone here and the people at Huayra Linux, I know I shouldn't express myself that way.

Please lead me in the way I should (or shouldn't) point some corrections, or if should I write the observations I may have directly to @DiegoAccorinti or if that's not up to me. I just want the translation to be accurate and comprehensive. 

I'm here to help. Any doubt you may have you can ask me if you want.

I'll wait for your answer to continue with this project.

Thanks!

Gracias @DiegoAccorinti , también quiero que trabajemos juntos para logar el mejor resultado posible.

Por favor, decime cual es la manera apropiada de hacer llegar algunas observaciones sobre la traduccion (o si no corresponde que yo lo haga.). No quiero poner nada aquí porque no es mi intención hacerlos quedar mal ni nada. Y si no me corresponde decímelo. La idea es ayudar a hacer una traducción precisa y comprensible.

Cualquier duda pueden consultarme si lo desean.

Espero su respuesta para continuar con este proyecto.

¡Gracias!

**Comment by DiegoAccorinti** [comment]
IGNUMariano Think the best way is to do all the editing changes you think the correct es.ts I proposed. and commit here so we see together. I estimate that with your knowledge and musical program you will be able to polish pretty and correct errors you find. The important thing is to get the most complete and accurate translation in Spanish is possible.

@GNUMariano  creo que la mejor forma es que hagas todos los cambios que creas correctos editando el es.ts  que propuse.  y lo publiqueas acá mismo haciendo un nuevo commit así lo vemos entre todos. calculo que con tu conocimiento del programa y musical vas a poder pulir bastante y corregir los errores que encuentres.  Lo importante es lograr que esté la traducción lo más completa y correcta posible en español.

**Comment by GNUMariano** [comment]
Thanks @DiegoAccorinti I'll do that. I guess you know I already submitted the full translations for the versions 1.0.3 , 1.1.3 and the masterbranch (this last still needs work because there are lots of new suff coming up in LMMS 1.2 !! ). This translations are correct but not perfect, so I am checking out some lines of it. I will also check out yours and submit here the file with what I think should be corrected so you can check it out. I can't be the final judge here, I'm human too so I'm also make some mistakes!
I guess it will take me four days / a week to do the job. Then I'll post it here. 
Hope we can enjoy LMMS  in Spanish soon!

A technical question: What version are you packing within your distro? I used the sources from 1.0.3, 1.1.3 and the MB to make the translations, and neither those match your es.ts. It will be very helpful to know that. For the sake of translation I like to compile the exact version I'm working on so I can translate while using LMMS to make sure everything is in the right context and fits the GUI as well (that's the way I made the mentioned translations. That help me to know LMMS more deeply.)

Thanks in advance! 

Gracias @DiegoAccorinti así lo haré. Creo que ya sabes que yo envié las traducciones completas para las 3 versiones de LMMS (1.0.3 y 1.1.3 están completas, necesitan ajustes menores, la traducción para la rama en desarrollo aún no está completa pues se vienen unas cuantas cosas nuevas en LMMS 1.2 !! ). Estas traducciones son correctas, pero no perfectas, estoy volviendo a revisar algunas líneas. También revisaré la suya y postearé aqui el archivo con las correcciones que yo considero necesarias para que las revisen. No puedo tener yo la última palabra, ¡yo también me puedo equivocar!
Me va a llevar de cuatro días a una semana hacer el trabajo. Cuando estésn listas las subo.
¡Ojalá podamos disfrutar un LMMS en Español muy pronto!

Una pregunta técnica: ¿Qué versión de LMMS viene con su distro? Yo he usado las fuentes de las versiones 1.0.3, 1.1.3 y la de la rama en desarrollo para hacer las traducciones. y he notado que tu archivo es.ts no concuerda con ninguna de estas tres. Sería muy útil para mi saberlo. Cuando traduzco un programa siempre compilo primero la version que voy a traducir. De esa manera puedo hacer la traduccion trabajando con el programa abierto al mismo tiempo y así me aseguro de que todo esté en el contexto adecuado y que además encaje bien en la GUI. (así es como he hecho las traducciones que envié. ¡Esto además me ha brindado un conocimiento más profundo de LMMS!)

¡Gracias anticipadas!

**Comment by GNUMariano** [comment]
BTW I've removed the previous comment. That doesn't belong here, we're all trying to do our best. 
Thanks!

Por cierto he retirado el comentario anterior. Se que no corresponde aqui donde todos están tratando de dar lo mejor.
¡Gracias!

**Comment by DiegoAccorinti** [comment]
La versión incluida en nuestra distro es la estable,  la 1.0.3 .  Sobre esa trabajé para completar la traducción,  pero seguramente hubiera sido mejor utilizar la versión en desarrollo :/ 
pero olvidémonos del caso puntual de Huayra, ya que nosotros empaquetamos nuestra versión de lmms incluyendo la mejor traducción disponible, actualmente es la mía pero si hay una mejorada claramente la utilizaremos.  Con que apuntemos a tener la mejor traducción en el proyecto general, más allá de una disto puntual.
Esperamos entonces el commit Mariano! cualquier cosa avisá.
--
The version included in your distribution is stable, 1.0.3. On that I worked to complete the translation, but probably would have been better to use the development version: /
but forget about the specific case of Huayra, as we packed our version of lmms including the best translation available, here is mine but if there is a clearly improved use. With to aim to have the best overall translation project, beyond a point disto.

**Comment by GNUMariano** [comment]
It's a deal!

Trato hecho!

**Comment by IvanMaldonado** [comment]
How is this going?

**Comment by GNUMariano** [comment]
HI @IvanMaldonado !

Sorry I'm late. I'm having too much work (non-related to this!) I've been very busy. (BTW I'm making a series of video tutorials for LMMS in Spanish!) but it's almost done. 

Just give me a few days.

PS: I'm still working on three versions of LMMS. My questions is: Is there a possibility of including this translations on versions 1.0... and 1.1... or it only will be included in the next, 1.2.. version of LMMS? I don't know how it works, but I hope uses of DEBIAN, KXTUDIO, AVLINUX, and other distros as well can benefit from it too.

There's still one line I can't translate:
From the lapsda plugin browser --> "In place broken"...
If somebody can explain it to me (in English is fine) so I don't have to leave it blank!

(wait for the commit soon!) 

Thanks!

**Comment by tresf** [comment]
> From the lapsda plugin browser --> "In place broken"...

The source code comments say the following:

> Indicates that the plugin may cease to work correctly if the host elects to use the same data location for both input and output (see connectPort).

The word "inplace" means: 

> in the correct or usual position or order:

And of course you know what the word "broken" means.  Does that help?

In regards to the translations making it to the older, stable releases, we can commit them but whether or not they make it downstream to the Linux distributions would be a question better suited for the package maintainers for those distributions.

-Tres

**Comment by GNUMariano** [comment]
Thanks, @tresf . that's exactly what I needed to know!

**Comment by GNUMariano** [comment]
Hi @tresf , I've got a question about the Triple Osc.
In the source it says:
"Use phase modulation for modulating oscillator 2 with oscillator 1"..etc,
but what it actually does is to modulate osc 1 with osc 2.
This is the same for FM, and AM (it obviously doesn't affect MIX), and again:
"Use phase modulation for modulating oscillator 3 with oscillator 2"
when actually osc 3 is the modulator.
Am I wrong? When I use the TripleOsc, osc 2 modulates osc 1, and osc 3 modulates osc 2.

My question is: If I'm right about this, should I correct it on the translation?

BTW, @IvanMaldonado :
in the instrument FUNC tab, I've translated STACKING  as "SUPERPOSICIÓN", yet I think a more musical term would be "VOCES" or even "ARMONÍA". What do you think?

Thank you for your time.

**Comment by tresf** [comment]
> If I'm right about this, should I correct it on the translation?

Absolutely (the source should also be fixed), but I would want someone more familiar to confirm the accuracy of this statement (or alternately, provide an adequate reference)

**Comment by GNUMariano** [comment]
Yes, of course. 
You can find it in this great book about LMMS:
"LMMS: A Complete Guide to Dance Music Production" by David Earl (yes, I know. You reviewed this book!) The chapter "The Language of Synthesis" (p.347) mention this. Hope it helps.

I've finished the translation and now it's very concise, clear and elegant. I think I've removed all typos (I hope so!) but I still got a few questions before sending the resulting es.ts. First I'll wait your answer on the triple oscillator modulator - carrier issue.

Second: What about the Papu Instrument? I can't find it anywhere. Windows only? or?

**Comment by grejppi** [comment]
@GNUMariano Freeboy is internally known as `papu`.

**Comment by tresf** [comment]
> You reviewed this book!) The chapter "The Language of Synthesis" (p.347) mention this. Hope it helps.

Your [page number is off](https://cloud.githubusercontent.com/assets/6345473/10870331/1617e148-8096-11e5-9d83-4592feb5bddd.jpg)... :) Staying on topic... I think you're right, but I simply don't know enough about the synth logic to be able to say for sure.   The answer is likely in [this portion of the code](https://github.com/LMMS/lmms/blob/master/plugins/triple_oscillator/TripleOscillator.cpp#L297:L369).  The loop appears to run in reverse order if that matters (starts at MAX counts back to MIN).  The author is @tobydox who would be able to answer this question for sure.

**Comment by GNUMariano** [comment]
Thanks @grejppi I couldn't find anything about "papu" on the forum and I would never imagine that _that_ was FreeBoy!

@tresf , sorry! I got the e-book! (_I'd love to have the paperback, but it isn't available around here_) a I guess that's why the pages don't match. I'll try to contact @tobydox about it. In the meantime, I'll keep it as it is now. But I mention this topic because it's something that puzzles synth newbies (_users with experience in synthesizer programming [and/or FL users] notice it right away. It took me a while to figure it out the first time I used the triple osc_) and LMMS new users in general. 
If we can fix this, that would be great. Yet I know that's not a priority right now, and there are some good tutorials on **3xO** on Youtube so I guess that would do it by now.

I guess we are not in a hurry since 1.2 is not happening very soon, so I'll wait a little to see if we can get this fixed (I'll send an e-mail to @tobydox and wait for his reply). That's all I can do right now.

Thanks for the support!

**Comment by tresf** [comment]
@GNUMariano if the proposed TripleOscillator correction needs to be made, then it needs to be corrected in the source as well as in all language translations.

That said, please proceed as normal and open a new bug report for the 3xOsc question so that it does not hold up or interfere with your very good translation progress.  :+1:

**Comment by GNUMariano** [comment]
Thanks, I'll do that!

**Comment by tresf** [comment]
Per @GNUMariano I've issued a pull request for the `stable-1.1` translation which was emailed to me here: #2436

If it's not too much, I'd like a sanity check over at #2436 before merging.

**Comment by GNUMariano** [comment]
HI @tresf, 
About the correction on **3xOsc**, @midi-pascal volunteers to fix the source here #2435

**Comment by IvanMaldonado** [comment]
@GNUMariano Sorry, I missed your post.

For the "stacking" thing superposition may be the best option from what you said since VOCES is actually the translation for "voices" (Which is often used) and "armonía" isn't necessarily something you "stack" as in stacking here. In my opinion it should be "Acordes" because that's what they actually are, I don't think we have a direct "stacking" translation in this context.

**Comment by GNUMariano** [comment]
Hi @IvanMaldonado ! 
I agree with you, that's why I choose the word **superposición** for stacking (the literal translation would be *pila* or *apilamiento*... it doesn't work fine in this case). I didn't mention **acordes** (chords) because it lets you stack chords *and scales* as well... 
--- I'll keep **superposición**. If I think of a better one, I'll let you know! 
Thanks for the answer!

**Comment by tresf** [comment]
Closed, superseded by #2676.

**Pull request closed without merging**
