### PR TITLE
Fix behavior of shift+dragging note ends

### LINKED ISSUE #1905: Proportionally changed notes bug
win32 1.1.3
Reproduce
Insert two chords of 2 bar note-length
Mark all
use combo sh+LMB in order to change note-lenght and note-position simultaneous. (proportional) 
Change length to 1 bar
At that moment the 2. chord get into its correct length, and position, the notes abruptly snaps into the first chord.
Obs!
This bug *only* occur when the first chord is in first bar! 
The first chord will in addition to this, *sometimes* be muted (looks like the note-start-pos could be outside first bars left limit?)

### PR DESCRIPTION
**Pull request by Wallacoloo**
This fixes #1905 by altering the behavior of shift+dragging a note end. When a group of notes is resized this way, each note's start-point and endpoint relative to the start-point of the left-most selected note gets scaled by some constant. This constant is chosen such that the endpoint of the note whose tail is being dragged is always keep directly under the mouse.

This change subtly affects the behavior of `shift+ctrl+drag` as well (which scales the selection and shifts posterior notes to maintain alignment). Previously, if you had a selection of notes and there were some unselected notes *between* the leftmost selection and the rightmost selection, these unselected notes would also be affected by the bug. Now, only the notes to the *right* of the right-most selected note's endpoint are shifted, and they're shifted to maintain a constant distance from that endpoint.

Some other edge cases, like dragging notes while toggling ctrl, might also behave differently, so anybody testing this should probably do so fairly thoroughly & make sure they don't have any objections to this.

### CODE REVIEW

**Comment by tresf** [comment]
IIRC, @badosu was the last to tweak this code.  @badosu, so you have time to review? ;)

**Comment by badosu** [comment]
I only added some keybindings once, I don't feel I can really review what's going on here.

**Comment by curlymorphic** [comment]
I have just tested this, It appears to be working as intended.

**Comment by tresf** [comment]
Thanks for testing dave.  The code seemed larger than what I would have expected, but Colin's work has been pretty solid and I don't see any problems.  Merging.

**Comment by badosu** [comment]
@tresf For some reasons I feel like I lost the momentum I had to develop LMMS, mainly I guess because some important issues I'd like to have solved where too ambitious for my own sake (LV2, mainly).

There are other reasons related to the social/organizational structure of the project as well.

So I just want to let you know that I'll probably be less dependable on the future, but if something really important comes up that I feel I can help I'll try :-).

**Comment by tresf** [comment]
> For some reasons I feel like I lost the momentum I had to develop LMMS, mainly I guess because some important issues I'd like to have solved where too ambitious for my own sake (LV2, mainly).

:(

> There are other reasons related to the social/organizational structure of the project as well.

:_(

> So I just want to let you know that I'll probably be less dependable on the future, but if something really important comes up that I feel I can help I'll try :-).

Fair enough.  Thanks for the heads-up.  If you'd like to discuss via PM or email, you know how to get a hold.

**Pull request merged**
