### PR TITLE
MixerView: skip confirmation when using clear

### LINKED ISSUE #7153: Confirmation for channel removal requested when loading another project
### System Information

Linux build (should affect every version)

### LMMS Version(s)

3e19d1335f478504c22ed68af9c96fccd6a6774b

### Bug Summary

A confirmation dialog for channel removal is shown when loading a new project with another project being already loaded.

### Expected Behaviour

No confirmation dialog is shown.

### Steps To Reproduce

1. Load "Greippi - Krem Kaakkuja (Second Flight Remix).mmpz" from the demos.
2. Click "File > New".

The following confirmation dialog is now shown several times:

LMMSConfirmationBug

### PR DESCRIPTION
**Pull request by Veratil**
Fixes #7153

### CODE REVIEW

**Comment by Veratil** [comment]
@michaelgregorius can you please test that this works as intended now? If we need to add any other places to skip confirmation we can do that, too.

**Comment by michaelgregorius** [comment]
Hi @Veratil! This fixes the problem for me.

**Comment by sakertooth** [comment]
I find this to be breaking SRP a bit. `MixerView::deleteChannel` should only worry about deleting the actual channel, while any outside code that wants to do a confirmation before deletion should do it there. This also would have fixed the problem, since we wouldn't be doing the confirmation in `MixerView::deleteChannel`, while `MixerView::clear` can just clear the mixer if it wants to without confirmation.

I would prefer we do the confirmation in `MixerChannelView::contextMenuEvent` where the action is created to remove a channel.

**Comment by Veratil** [comment]
> I would prefer we do the confirmation in `MixerChannelView::contextMenuEvent` where the action is created to remove a channel.

Good point, I'll adjust the PR for this.

**Comment by Veratil** [comment]
@sakertooth moved to `MixerChannelView`
@michaelgregorius I tested the same method you used and it didn't prompt, so I assume this still fixes the issue :)

**Review by sakertooth — APPROVED** [review]

**Review by michaelgregorius — APPROVED** [review]

**Pull request merged**
