### PR TITLE
Delete Zakarra songs, missing sounds

### LINKED ISSUE #2101: Demo projects that are missing samples.
Some projects miss drum samples:
https://github.com/LMMS/lmms/tree/master/data/projects/demos/Zakarra

Downstream bug:
https://bugs.launchpad.net/ubuntu/+source/lmms/+bug/1386542

Demo projects last changed in commit ce0a56a482819f728fdcfba01f6ba3ceb32e2ff7
miss some (or all) samples. 
@cubician  Do you have the original files so you can complement the projects?

_Edit: Fix links_

### PR DESCRIPTION
**Pull request by zonkmachine**
Fixes #2101

It's a bit on the brutal side but the samples are from a project not automatically installed with LMMS so I think just removing these projects altogether is the best thing to do. Unless Zakarra can drop by and fix them up ... ( _Edit: @cubician submitted the files and hasn't responded in_ #2101 ) 

Related to  #2813

### CODE REVIEW

**Comment by SirBothersome** [comment]
I think our demo repo as a whole needs to be blowtorched to a more manageable size, and with new sample libraries on the way, songs may need to be retrofitted anyhow. I think we only need about five for so demo projects to demonstrate the basics of LMMS to a new user.

**Comment by Umcaruje** [comment]
I agree with this, there's no point in shipping broken projects. You should also remove them from https://github.com/LMMS/lmms/blob/master/data/projects/demos/LICENSES.TXT

**Comment by zonkmachine** [comment]
> and with new sample libraries on the way, songs may need to be retrofitted anyhow.

Waiting eagerly!

OK, merging...

**Comment by Umcaruje** [comment]
:+1:

**Comment by SirBothersome** [comment]
> Waiting eagerly!

OK, merging...

@zonkmachine, I can't tell if you're being sarcastic or not... bare-bones acoustic library will hopefully be up Monday

**Comment by zonkmachine** [comment]
> I can't tell if you're being sarcastic or not...

:smile_cat: Not sarcastic, needz samplez!

**Comment by SirBothersome** [comment]
> :smile_cat: Not sarcastic, needz samplez!

Cool. Well, if you've got the time, you can be one of my beta testers, my current focus group isn't exactly what you'd call 100% dynamic

**Pull request merged**
