### PR TITLE
Feature/outputprefs

### PR DESCRIPTION
**Pull request by teknopaul**
Adds settings in .lmmsrc.xml so users can set their preferences for Exporting tracks.

This enables, for example, to setup the default as mp3 at 256 bit rate. 
Aslo added  Ctrl + Alt + E  Exports with no questions asked since defaults will always be correct.
Has settings for ogg , flac and wav so users that prefer one of those formats can configure their instance of lmms to have their correct settings by default.
Also added a default export directory if some people usually render to a different place than the .mmpz directory.

Settings UI is a bit basic I'll make it look nicer if this is being considered.

### CODE REVIEW

**Comment by teknopaul** [comment]
I tried to split two changes across two feature branches but it has not worked, somehow meta data features leaked into this branch and have code complexity issues.  Should get fixed if bother were merged

**Comment by teknopaul** [comment]
screenshot of UI as it stands

lmms-output-settings-screenshot

Hopefully self explanatory,  ignore "bouncing clips" this is something I have working on a  different branch

**Comment by teknopaul** [comment]
File menu has export options which dont require popups to set output format each time since preferences are defined

Ctrl+Al+E and it exports with your defauilts

lmms-output-settings-filemenu

**Comment by DomClark** [comment]
I appreciate the effort to streamline the export process somewhat, but I think this could be a little clearer to the user as to what is going on. Two similarly names "export" menu items is likely to cause confusion, especially to those who are unfamiliar with the convention of using ellipsis to indicate further interaction. The automatic export will overwrite the corresponding file without confirmation, which is risky enough for users who know what it does, let alone those who don't. If the project doesn't have a file name, the automatic export fails silently, which is confusing and can give the impression that it is broken.

Would it not be sufficient to simply fill the existing export dialog with the preferred options? I realise this isn't quite as efficient as a one-click export, but it only requires a few presses of the enter key, and is free of any additional footguns. This also avoids the need to add options to the config dialog, as the export dialog itself can be used to perform the configuration (perhaps with the addition of a "set default configuration" button).

Also, your metadata changes seem to be mixed in with these.

**Comment by teknopaul** [comment]
Filling the dialogs is explicitly what I want to avoid.
I use this for every render now. Ctrl + Alt + É. 

To render clips Ctrl +B. 

I get MP3s with text & images, mastered and compressed. 
Zero post processing, just one key press. Everything in the right place. 

I have always used a fork of Lmms with this change, only difference here is I made it optional in case some users actually want pop-ups everytime.  No workflow is changed for anyone it's one new option to never see save pop-ups. 


The elipsis thing seems standard across operating systems. 
If it's just Export without elipsis that you think people will not understand we could change the text?   Export as...  &  Export

I can't find an app on my desktop that does not have Save and Save as...  meaning pop-ups or just overwrite. 

If you think that is not generally useful, no worries. 

Bounce outputprefs and song meta data are all part of the same workflow so I'll close them all because it's quite painful maintaining stuff in branches

**Pull request closed without merging**
