### PR TITLE
Remove FLP import, revert to GPLv2+ only

### LINKED ISSUE #2752: License of the project as a whole is GPL-3+
The following files are licensed under GPL-3+:

    plugins/flp_import/unrtf/*

Files are included in `plugins/flp_import/unrtf.cpp`. This commit changed the license: 98371cb1481e2e11d284223deed0d349ee953010

    plugins/LadspaEffect/swh/vocoder_1337.c

This one is being handled in #2366.

    plugins/zynaddsubfx/zynaddsubfx/src/Nio/AlsaEngine.cpp
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/AlsaEngine.h
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/JackEngine.cpp
    plugins/zynaddsubfx/zynaddsubfx/src/Nio/JackEngine.h

These files are not enabled.

### PR DESCRIPTION
**Pull request by grejppi**
The fact that searching for `flp` [gives only three results](https://github.com/LMMS/lmms/issues?utf8=%E2%9C%93&q=is%3Aissue%20flp) somehow tells me it won't be missed. @LMMS/developers, Y/n?

This should also close #2752 and resolve the GPLv3 issues once and for all.

May still contain traces in the translation files. @liushuyu, should they be edited on Transifex, your `lmms-translations` repository, or here?

### CODE REVIEW

**Comment by Umcaruje** [comment]
Yes from me, it didn't import properly anyways, and if it clashes with our license that's another reason to remove it.

**Comment by liushuyu** [comment]
>May still contain traces in the translation files.@liushuyu, should they be edited on Transifex, your `lmms-translations` repository, or here?

My `lmms-translations` repository is just a mirror of Transifex stash. 
And if you don't want to refresh the translation file yourself, I will do the job. Just simply run `lupdate -Iinclude/ src/ plugins/ -ts data/locale/en.ts` on working copy of LMMS source directory. 

And for the "traces" you have mentioned, Qt will mark these translations as deprecated by default instead of wiping them out, so do you want to just make them hidden or totally delete them?

**Comment by DeRobyJ** [comment]
I agree on this too: it's better to export the FLStudio project (or any other daw) to MIDI and import that in LMMS, so we should concentrate on MIDI rather than FLP files.

**Comment by grejppi** [comment]
Alright, this has got quite a few :+1:s already, so I guess I'll merge this in 24 hours ~~unless someone else does it first~~ unless there are no objections.

**Comment by Tubenyan-Official-YT** [comment]
I want flp import add again. because many FNF songs has midi/FLP, but many FNF songs doesn't have LMMS file, so It is uncomfortable.

**Comment by headquarter8302** [comment]
FLP import was never supported properly. I recommend using tools like https://github.com/DawVert/DawVert or opening the project in FL Studio and then exporting it as MIDI to reimport into LMMS

**Pull request merged**
