### PR TITLE
Show/Focus BBEditor on TrackLabelButton click #4946

### PR DESCRIPTION
**Pull request by CYBERDEViLNL**
Will close https://github.com/LMMS/lmms/issues/4946 and it's ready for review.

### CODE REVIEW

**Comment by Spekular** [comment]
What pattern does this actually open?

- If I click a track with no patterns in it, what does it open? If it opens
an empty editor, what's the point?
- If I click a track with more than one pattern on it, which one opens? The
latest edited pattern might be on an entirely different track.

In addition, doesn't this clash with clicking and dragging to move a track,
clicking to edit a track name, or clicking to open the track instrument?

**Comment by CYBERDEViLNL** [comment]
@Spekular, yes you are right it is rather pointless for the Automation Editor and would only cause confusion. I will remove the code for the Automation Editor. (don’t know what I was thinking on that one, thanks for pointing it out :confused: )

Also found that when the BBEditor it’s parent widget is hidden it won’t show on click of it’s TrackLabelButton, will make a adjustment to that too.

**Comment by JohannesLorenz** [comment]
@CYBERDEViLNL Is this ready for review, or is it in progress? I'm asking so we can apply the right labels to it :smiley:

**Comment by CYBERDEViLNL** [comment]
@JohannesLorenz it is ready :-)

**Comment by JohannesLorenz** [comment]
Confirming that it's style conforming :+1: . I'll leave the functional review for whoever is interested.

**Comment by JohannesLorenz** [comment]
I'll do the functional review.

**Comment by JohannesLorenz** [comment]
`QWidget::show` already shows all child widgets, so the line `gui->getBBEditor()->show();` can be safely removed (I tested it). SampleTrack and InstrumentTrack also just call `show` for the parent. This is just a suggestion though.

**Comment by JohannesLorenz** [comment]
Code is functional OK and fixes what it claims :+1: . Let me know when you want to merge or when rework needs to be checked.

**Comment by CYBERDEViLNL** [comment]
Great thank you! I removed the now unnecessary `show()`, should I squash the commits or will that be done if merged by the merger?

**Comment by JohannesLorenz** [comment]
@CYBERDEViLNL That's done when merging.

Thanks for the PR. I'll merge as soon as CI will have passed.

**Pull request merged**
