### PR TITLE
FindWine improvements

### PR DESCRIPTION
**Pull request by tresf**
> Wine 5.0 Release notes:
> * Binaries built for a Windows target no longer depend on the `libwine` library, to enable them to run on Windows without any extra dependencies. The `libwine` library is no longer built for Windows at all.

> Wine 9.0 Release notes
> * The `libwine.so` library is removed. It was no longer used, and deprecated since Wine 6.0. Winelib ELF applications that were built with Wine 5.0 or older will need a rebuild to run on Wine 9.0.

Fix `RemoteVstPlugin.exe.so` compilation for WineHQ builds.

```
-- Found Wine: /opt/wine-staging/bin/wineg++
--   WINE_INCLUDE_DIR:     /opt/wine-staging/include
--   WINE_CXX:             /opt/wine-staging/bin/wineg++
--   WINE_GCC:             /opt/wine-staging/bin/winegcc
--   WINE_32_FLAGS:        -L/opt/wine-staging/bin/../lib/wine/i386-unix/
--   WINE_64_FLAGS:        -L/opt/wine-staging/bin/../lib64/wine/x86_64-unix/
```

Supersedes  #7260

Wine search order: (TBD)
* `wine-staging[-dev]`, `wine-devel[-dev]`, `wine-stable[-dev]`, `<whatever your distro offers>`
* If your build fails after this PR please ensure the **appropriate** `-dev` package is installed! 

Summary:
* Uses `NO_DEFAULT_PATH` when locating files to avoid prefix mixing
* Removes polluting `CMAKE_PREFIX_PATH`
* Moves `winegcc` references to a new variable `WINE_GCC`
   *  `WINE_CXX` is solely for `wineg++`.
* Echo's found `bin|include|libs` to the CMake summary

Note, Ubuntu 20.04 ships with Wine 5.0, but WineHQ is 9.0 and these produce Windows VST interfaces that are incompatible with each other.

TODO:

* [x] RemoteVstPlugin32.exe.so will build with `wine-staging`, but crashes.   `ldd` output is [missing `libwine.so.1`](https://github.com/LMMS/lmms/assets/6345473/2eb687f5-0123-41e1-9a13-de3004c0dd40).
   * I can't find this information anywhere, but `libwine.so.1` is no longer linked to executables created with Wine 9's `wineg++`.  Furthemore, those executables seem to be incompatible with older Wine versions.  Replacing package `wine` with package `winehq-staging|devel|stable` is fine as well, versions don't need to be identical.
* [x] 64-bit VSTs effects are reported as not working, quoting:
   > -1 — Today at 3:08 AM
   > No 64bits effect plugins are working. 64bits instrument plugins seem to run properly
   * Cannot reproduce with [this plugin](http://www.tokyodawn.net/labs/TDR%20Feedback%20Compressor%20II.zip?x26827).  -1 claims a reboot fixed it.  Marking as resolved.

### CODE REVIEW

**Comment by Rossmaxx** [comment]
> This fix doesn't work for me. Without a fix it works fine with WineHQ devel.

I guess you use ubuntu/debian or any other "stable" distro. This is a known issue and is currently under investigation by me and tres. The consensus now is to block older releases to a degree, because somewhere down the line, `libwine.so.1` has been removed and that change gets reflected in WineHQ but not in distro wine. I advise you to use wine hq.

**Comment by Z3R0C** [comment]
That's right. I use Ubuntu 24.04 and these wine packages are installed:

Bildschirmfoto vom 2024-05-19 17-08-07

**Comment by tresf** [comment]
> `* 32-bit Windows host : not found, please install (lib)wine-dev (or similar) - 64 bit systems additionally need gcc-multilib and g++-multilib
> 
> * 64-bit Windows host       : not found, please install (lib)wine-dev (or similar) - 64 bit systems additionally need gcc-multilib and g++-multilib
>   `
> 
> This fix doesn't work for me. Without a fix it works fine with WineHQ devel.

You're probably missing the winehq `-dev` packages.  This is deliberate, it shouldn't have worked before but got mangled due to search paths combining wine versions.  Can you install the appropriate `-dev` packages from WineHQ and try again please?

**Comment by tresf** [comment]
> I tested vst-fix2 and wine is no longer found. I chose winehq-devel for reasons.

Yeah, but you also have staging, but not staging-dev.  It finds staging then can't find the header.  Please remove wine-staging or install staging-dev.  If people don't like this search order, I can reverse it.  I'll edit the original PR description to mention this.

**Comment by tresf** [comment]
Feedback from Discord:

image

**Comment by Z3R0C** [comment]
wine-devel-dev is the winehq-dev package. 

I have now installed wine-staging-dev as a test and the fix works. But I don't want to be forced into wine-staging-dev when I have wine-devel-dev installed. :)

**Comment by tresf** [comment]
> But I don't want to be forced into wine-staging-dev when I have wine-devel-dev installed. :)

You're not.  You installed that package, not me, no one forced you into anything.  Two options were provided, uninstall staging completely or install the dev portion.

**Comment by Z3R0C** [comment]
Bildschirmfoto vom 2024-05-19 22-42-34

But I would like to use the development branch. The equivalent to wine-staging-dev (from the staging branch) is wine-devel-dev (from the development branch). Why is this so difficult to understand? You're saying again I should use staging. That does not make sense.

**Comment by tresf** [comment]
Use it.  Remove staging.  This is the third time I've said this.

**Comment by tresf** [comment]
> By the way, the staging:i386 files are requirements from the carla-bridge package. I don't know if I want to do without Carla.

Then install them.  If you have staging installed, you'll also need staging-dev installed.  Compiling LMMS against staging DOES NOT mean it runs with staging.  That's configured by which primary wine package you have installed.

**Comment by tresf** [comment]
Quoting winehq.  Please note the difference between `wine-stable` and `winehq-stable`.

> By splitting a Wine over different packages, it is possible to install different branches side by side.
>*  For example: Use Wine stable as the default Wine version and install Wine staging to test other programs.
> ### Install Wine stable:
> ```bash
> sudo apt install --install-recommends winehq-stable
> ```
> ### Install Wine staging:
> ```bash
> sudo apt install --install-recommends wine-staging # (Note the missing hq after wine)
> ```
> ### Run a program with Wine stable:
> ```bash
> wine program.exe
> ```

I'll reiterate one more time before marking this as off-topic... 

* If you have `wine-staging` installed, it exposes `winegcc` to the system, so it **NEEDS** a matching `wine-staging-dev` package.

We did not make the decision to ship `winegcc|g++|cpp` WITHOUT matching `dev` headers, that's a decision by WineHQ.  We simply search and use the version installed, newest to oldest.

**Comment by tresf** [comment]
This came in through Discord... will attempt to confirm:
image

**Comment by tresf** [comment]
> This came in through Discord... will attempt to confirm: image

I tested in my Linux VM [this plugin](http://www.tokyodawn.net/labs/TDR%20Feedback%20Compressor%20II.zip?x26827) and could not reproduce, so this crash may be unrelated to LMMS' implementation.

**Review by messmerd — APPROVED** [review]

**Pull request merged**
