### PR TITLE
Make Pause hotkey Shift+Space

### PR DESCRIPTION
**Pull request by russiankumar**
This PR targets issue #5301 (and similar issues). This fix is similar to that of #5332, however that PR is stagnant and I want to commit changes to all editors so pausing can be done in all editors.

I've had some issues with git commiting recently, so you may see a whole load of random commits, but the final result works so far on `SongEditor.cpp`. Will commit soon to implement the same in Piano Roll, B+B Editor, etc.

It works as expected:
- While playing, Shift+Space stops the song in its place (like the `>>` option would for playback start position)
- While paused, Shift+Space (or Space) continues from the place it is stopped at.

### CODE REVIEW

**Comment by russiankumar** [comment]
Ok, I underestimated how messed up my git has become.
image
Though the final file has the expected code, so not an issue?

**Comment by russiankumar** [comment]
Discovered a very useful `togglePause()` function. Changed to use that function as it emits `playbackStateChanged()` as well.

**Comment by russiankumar** [comment]
Moved the shortcut to `Editor.cpp`. Every `Editor` will now pause on Shift+Space.

---
#### Noted bug
When having the song editor in pause state, a pattern is played, the song editor is stopped. This may be intended behaviour, so please let me know if I should make changes to that as well.

**Comment by russiankumar** [comment]
Uhh... could someone review this...? @PhysSong? @SecondFlight? @DomClark? Tagging because you reviewed my previous PR too.

**Comment by musikBear** [comment]
👍 * 💯 Good stuff! 🥇

**Pull request merged**
