### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by anytizer**

### CODE REVIEW

**Review by sakertooth — APPROVED** [review]

**Review by zonkmachine — APPROVED** [review]

**Comment by zonkmachine** [comment]
There was an attempt way back to make this automated by a cron job. This line and the `CONTRIBUTORS` file was supposed to be updated by a script.

**Comment by DomClark** [comment]
I wonder if we could pull it from the latest Git commit. The contributors list in the about dialog is already generated from Git:
https://github.com/LMMS/lmms/blob/f664698c80f8bf55992071a409cff4b24da84739/CMakeLists.txt#L658-L672

**Comment by anytizer** [comment]
This gist is [returning the current date, using macro](https://gist.github.com/alorence/59d18896aaad5188b7b4) - hope, we can implement something similar.

**Comment by messmerd** [comment]
As it mentions in the gist, it looks like we can use the [`string(TIMESTAMP)` command](https://cmake.org/cmake/help/latest/command/string.html#timestamp) as of CMake 3.0.

I believe it would be something like this:
```cmake
string(TIMESTAMP PROJECT_YEAR "%Y" UTC)
```

**Comment by DomClark** [comment]
Surely the copyright year of a program should be when it was written, not when it was built? It wouldn't make sense to check out a commit from years ago, build it, and claim the copyright to be from the current year. I'd rather play it safe when it comes to legal stuff.

**Comment by Veratil** [comment]
> Surely the copyright year of a program should be when it was written, not when it was built? It wouldn't make sense to check out a commit from years ago, build it, and claim the copyright to be from the current year. I'd rather play it safe when it comes to legal stuff.

Copyright is from the initial creation to today, most will write it as `(C) FIRST-TODAY`.
An example of not doing it that way would be GitHub itself using `(C) CURRENT_YEAR`.

Both work and are valid from what I understand.

**Pull request merged**
