### PR TITLE
Try to find libraries in a non-standard directory

### PR DESCRIPTION
**Pull request by jasp00**
This workaround may fix the issue @midi-pascal is having in #2748.

### CODE REVIEW

**Comment by midi-pascal** [comment]
@jasp00 Just to be sure, I did a fresh git clone from master branch and applied this patch.
That's a lot better: zynaddsubfx seems to link successfully now but I get this error at the end:
``make[2]: *** No rule to make target `../target-debug/lib', needed by `plugins/RemoteZynAddSubFx'.  Stop.``
``make[1]: *** [plugins/zynaddsubfx/CMakeFiles/RemoteZynAddSubFx.dir/all] Error 2``
which I think is an other problem.
The directory ``buid/../target-debug`` does exist

**Comment by jasp00** [comment]
@midi-pascal, could you try the current patch?

**Comment by jasp00** [comment]
@midi-pascal, do not bother, it will not work.

This should not be worked around. The patch in #2755 does not fix the issue and must be reverted.

**Comment by midi-pascal** [comment]
@jasp00 Tried this patch with no success. Same link error.
I even added a CMake "MESSAGE" in the patch to be sure it is really executed.
It is...

**Pull request closed without merging**
