### PR TITLE
Replace corrupted default samples with fixed ones.

### PR DESCRIPTION
**Pull request by Rossmaxx**
Apparently, a few built in samples are corrupted. I replaced them by using audacity.

But these samples play fine in lmms as of now because of some clunky workaround in sample buffer but once #6610 gets merged, all these samples will break. Even VLC couldn't play these samples. 

https://github.com/LMMS/lmms/assets/74815851/9e9e2d7d-25a9-4662-9ceb-76e784f36f2c

### CODE REVIEW

**Review by sakertooth — COMMENTED** [review]
Why the changes to the ``exptrk`` submodule? Try and see if you can undo them.

**Comment by Rossmaxx** [comment]
> Why the changes to the exptrk submodule? Try and see if you can undo them.

i messed up on git. don't know how it happened

**Review by sakertooth — APPROVED** [review]

**Comment by messmerd** [comment]
It looks like all samples except for kick04.ogg are slightly shorter in duration now. It seems to just be silence that was cut off the ends, but we should probably add the silence back in to prevent any potential issues with projects that used the longer samples. I also confirmed that the silence is present in LMMS, so it isn't just Audacity.
Screenshot from 2023-06-28 16-58-58

**Comment by messmerd** [comment]
Here are the samples with the silence added back onto the end
[FixedSamples.zip](https://github.com/LMMS/lmms/files/11900022/FixedSamples.zip)

**Comment by Rossmaxx** [comment]
> It looks like all samples except for kick04.ogg are slightly shorter in duration now

Thanks for finding it out. I've replaced those samples with the ones in your folder.

Btw, messed up with exprtk submodule again. Don't know what's happening.

**Review by messmerd — APPROVED** [review]

**Comment by messmerd** [comment]
> What's happening with mingw builds failing? I haven't touched any code.

Looks like it failed to download a dependency from the Ubuntu package archive. Might be a temporary outage or something - not anything you did.

**Comment by Rossmaxx** [comment]
> Looks like it failed to download a dependency from the Ubuntu package archive. Might be a temporary outage or something - not anything you did.

Thanks for the clarification. I noticed it too but after posting the comment.

**Comment by messmerd** [comment]
If there are no objections, I'll merge this tomorrow.

**Pull request merged**
