### PR TITLE
Remove the file extensions from the translations in the saveAsDialog

### PR DESCRIPTION
**Pull request by curlymorphic**
Moved the file extensions outside the translations, as per a discussion in #1709.

### CODE REVIEW

**Comment by tresf** [comment]
Thanks but won't this cause issues if we don't fix the old translation files too?

**Comment by curlymorphic** [comment]
Yeah. any translations will be lost. I can go thru the xml and edit them.

**Comment by tresf** [comment]
@curlymorphic, once we clean up the translation files, this can be merged.

-Tres

**Comment by curlymorphic** [comment]
Cleaned up the translation files

**Comment by curlymorphic** [comment]
:)

**Pull request merged**
