### PR TITLE
fixes sample muting bug for sampletrack

### PR DESCRIPTION
**Pull request by BaraMGB**
fixes : https://github.com/LMMS/lmms/issues/3590

### CODE REVIEW

**Comment by PhysSong** [comment]
Good.
Maybe #3133 have caused #3590.
Could we change SampleTrack::updateTcos() into more simple form?

**Comment by BaraMGB** [comment]
>Could we change SampleTrack::updateTcos() into simpler form?

Yes, thinking about that brings me to another problem. If we have more than one sample track this would not work. 

I'm on it.

**Comment by BaraMGB** [comment]
>~~Yes, thinking about that brings me to another problem. If we have more than one sample track this would not work.~~

That's not true. I updated the PR.

**Comment by BaraMGB** [comment]
If no one has objections about this I'll merge in few hours.

**Comment by tresf** [comment]
FYI, cherry-picked to `liushuyu/merge` via 8c17b39.

**Pull request merged**
