### PR TITLE
Add Ukrainian translation

### PR DESCRIPTION
**Pull request by NeiroNext**
Hello!
I would like to add the Ukrainian translation, for a stable branch "```stable-1.1```".

P.S. Firstly send the changes to mail (as it is written in the wiki), but never received a reply.

### CODE REVIEW

**Comment by tresf** [comment]
@NeiroNext Thanks kindly for this contribution.

@midi-pascal since you've helped with translations in the past, I'll ask you... How hard is it to sync this to master if we accept it against stable?  My instinct is to request this is re-done on the future branch since we don't currently have plans to release another `stable-1.1` release.

**Comment by midi-pascal** [comment]
Basically the only things to do is to add the file data/locale/uk.ts to the master tree and run lupdate so the file uk.ts will be updated. The next build will generate the file uk.qm.
- The installation process copies data/locale/*.qm to share/lmms/locale/ of the installation directory so nothing to change there.
- The Lmms code does need modification since it detects the languages available dynamically at runtime.

<i>However:</i>
- The code of Lmms changed a lot between stable-1.1 and master so, the translation files will be incomplete and the translation would need to be updated by someone to be in sync with the master.

**Comment by Wallacoloo** [comment]
@tresf I don't know how familiar you are with git, but you should be able to merge this into stable-1.1, fetch stable and master on your computer, and then `git checkout master` and `git cherry-pick 6e9b1824` to apply it to master.

**Comment by tresf** [comment]
@Wallacoloo we sync our branch commits in, so that is something we'd do naturally, I'm not concerned about this from a VCS perspective but rather from a 1.1 vs. 1.2 perspective which is more of a question around what's changed.  @midi-pascal hit the nail on the head I think with this line:

> @tresf Since there are many many literals still valid from stable-1.1 I would suggest the update instead of a complete re-do (I know what I am speaking about :smile: )

In that case, we'll merge, sync (eventually) and then update at our leisure. :+1:

**Comment by NeiroNext** [comment]
@tresf I so understood the translation needed to do for the master branch, I've translated to version 1.1 because in the wiki was wrote to do the translation for the `stable` release.
I'll can translate it for `master` branch if need =) but I need some time for it and new `pull request` as I understood.
@midi-pascal Which files need to change for the correct definition of a new translation? (The interface is normally translate into my language)

**Comment by midi-pascal** [comment]
@NeiroNext When the file uk.ts will be available in the master branch and lupdate run on it, it will be updated to reflect the new or deleted literals added or removed since stable-1.1.
If you do not know, lupdate is the Qt utility which extracts the literals from the C++ code which updates the "*.ts" files.
Then you will have to pick "uk.ts" up from the master branch.
If you use QtLinguist, you will see the new literals appearing as "not translated".
Not to discourage you but be prepared to see many many new literals! :smile:
There were some places in the code (mainly macros) that prevented literals to be extracted correctly by lupdate since recently so, there is now a lot more to translate.
Should you need help, ask for it!

**Comment by NeiroNext** [comment]
@midi-pascal Thank you! I know what are `lupdate` and `QtLinguist` :smile: because only this software I can comfortably translate program, in this case, instead of using `lupdate make .. && make my_language.ts` to update the translation.
529 new literals were find.
Initially, I did the translation for version 1.0.3-5, and to upgrade to the `stable-1.1` branch I had to translate the 600 literals of what I spent for 3 ~, so the upgrade to the `master` branch, I also spend ~ 3 days.
As I understand the new changes must be placed in a new pull request?
Thanks for your quick answer and sorry for my late answer!

**Comment by midi-pascal** [comment]
@NeiroNext Yes you will have to make a new pull request on the master branch because it applies to an other Lmms branch.
Do not feel sorry for the delay, we are spread all over the world in various time zones so delays are part of the contributions contingencies.
@tresf All contributions are welcome even with delays, uh? :+1:

**Comment by tresf** [comment]
> @tresf All contributions are welcome

:+1:

**Comment by NeiroNext** [comment]
OK! So as I understand this pull request can be closed ?

**Comment by midi-pascal** [comment]
@tresf You're the boss!

**Comment by NeiroNext** [comment]
@midi-pascal I asked because not absolutely understood whether it is used for `stable-1.1` or not used :-/

**Comment by midi-pascal** [comment]
@NeiroNext I do not know for sure. I think @tresf has the answer since he knows - or decides - what goes where so, I cannot answer your question.

**Comment by tresf** [comment]
I'll merge, but keep in mind @midi-pascal's notes about the incompleteness on master.

**Comment by NeiroNext** [comment]
@tresf Yes, I have already doing the translation for `master` branch.

Thanks to all :smiley:

**Pull request merged**
