### PR TITLE
editor couple of build warning

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by JohannesLorenz** [comment]
I just wonder if we should not make the vector contain floats instead of casting?

@Veratil what do you think? It's your code area :smiley:

**Comment by Veratil** [comment]
> I just wonder if we should not make the vector contain floats instead of casting?
> 
> @Veratil what do you think? It's your code area 😃

I don't think we need the precision of doubles, as none of our zoom levels use greater than 7 digits of precision, so making them floats would be easier (should only be two lines in the header).

**Comment by JohannesLorenz** [comment]
LGTM. Are the compiler warnings all gone now?

**Comment by devnexen** [comment]
the remaining are mostly QT deprecations better not touching them I think.

**Comment by Veratil** [comment]
Why does the compare have changes to rpmalloc and weakjack?

**Comment by devnexen** [comment]
was unintended .

**Review by Veratil — APPROVED** [review]

**Review by JohannesLorenz — APPROVED** [review]

**Pull request merged**
