### PR TITLE
linkage issue fixes due to inlined functions

### PR DESCRIPTION
**Pull request by devnexen**
Spotted on OS X.

### CODE REVIEW

**Comment by tresf** [comment]
@devnexen thanks!  This has been breaking on my machine as well.  Can you please also submit a PR to https://github.com/swh/ladspa?

**Comment by devnexen** [comment]
@tresf Seems done https://github.com/swh/ladspa/pull/50

**Comment by tresf** [comment]
@devnexen Thanks again.

I'm sorry for the inconvenience, but since this is needed for our next stable release, we will need to be merged into `stable-1.2` and then we'll sync it back to master.  This may seem counter-intuitive, but that's how we're handling the branch drifting.  I've attempted to rebase using the GitHub GUI, but it threw the PR out of whack.  I think the branch needs to be rewound to the state of `stable-1.2` and then the commit can be cherry-picked.

**Comment by tresf** [comment]
Force rebased against `stable-1.2`.  Merging.

**Pull request merged**
