### PR TITLE
Bloody 'ell

### PR DESCRIPTION
**Pull request by grejppi**
Withdrawing my song from this project because of #1687.

If you want artists to disown their work for the glory of LMMS,
go right ahead.

This idea sickens me, really.

There's no way anyone in their right mind would tell an artist to give up
their music under CC0 just in order to get it in LMMS distribution.

### CODE REVIEW

**Comment by Spekular** [comment]
Sorry guys (as the rest of you all seem to agree on this CC0 thing) but I
gotta agree with grejppi. I've stayed out of discussions on this because I
don't want to 1vEveryone, but credit is a perfectly reasonable thing to ask
for.

**Comment by grejppi** [comment]
@tresf your turn.

**Comment by Umcaruje** [comment]
I too think that making songs anonymous and CC0 is a  bad idea. It really does not make any sense to me. Artists should not be left creditless.

**Comment by Sti2nd** [comment]
Firstly, your song will never be forced to use CC0, grejppi, so you didn't have to remove it...

> Artists should not be left creditless.

That is fair and square IMO. The idea of demo songs is to showcase LMMS, and if some artists have made something brilliant they want to give out to the masses, they could, and they should be credited. I am against any self promotional links, cause that enforces the wrong idea of demo songs.

PS: Not sure how much the discussion benefits of splitting it up in several different threads https://github.com/LMMS/lmms/pull/1687#issuecomment-71389485

**Comment by diizy** [comment]
On 01/25/2015 11:03 PM, grejppi wrote:
>
> Withdrawing my song from this project because of #1687
> <https://github.com/LMMS/lmms/pull/1687>.
>
> If you want artists to disown their work for the glory of LMMS,
> go right ahead.
>
> This idea sickens me, really.
>
> There's no way anyone in their mind would tell an artist to give up
> their music under CC0 just in order to get it in LMMS distribution.
>

CC0 doesn't imply that you have to "disown" your work. CC0 works about
the same as public domain: you give up the copyright, but not the right
of attribution, meaning that people are free to share and do what they
want with derivatives, but the original work is still attributed to you.
Someone taking your original work (not a derivative work) and
representing it as their own is still illegal, even under CC0 or public
domain.

LMMS demo songs should first and foremost be material for the user to
use freely, because think of the alternative - we give the user editable
projects, but not the right to use them in any way they choose? That's a
bad idea on many levels - firstly, it's something of a newbie trap
because people assume that resources that come with a software such as
LMMS are available to be used freely, secondly because think of the
fallback and controversy caused if some of the demo song authors decided
to pursue legal action against some LMMS user for violating their
copyright...

I'm not saying you have to be OK with distributing your material as
CC0... but if doing so seems unpleasant to you, then it sort of raises
the question, is LMMS demo songs really the right place for you to
distribute your work? Soundcloud etc. already exist for distributing
your art under more artist-friendly terms...

**Comment by SecondFlight** [comment]
So what does this mean then?

Here is one of the rights I would be waiving if I were to apply CC0 to my work:
> moral rights retained by the original author(s) and/or performer(s);

Moral rights as defined on Wikipedia:
>Moral rights are rights of creators of copyrighted works generally recognized in civil law jurisdictions and, to a lesser extent, in some common law jurisdictions. They include the **right of attribution,** the right to have a work published anonymously or pseudonymously, and the right to the integrity of the work.

**Comment by interstar** [comment]
"Someone taking your original work (not a derivative work) and representing it as their own is still illegal, even under CC0 or public domain."

Are you sure about that. Surely "public domain" means exactly that you have no rights to something. Not even attribution or recognition.

**Comment by tresf** [comment]
CC0 is a recommendation and thus a goal.  We should spend more time discussing and being proactive about our intents.  Before we discuss what "sickens" us, perhaps we should step back and see what contribs to our project couldn't have be possible without carefully choosing the right licensing.

**Comment by tresf** [comment]
> @tresf your turn.

@grejppi I think this conversation escalated a bit out of context.  Our long term goal is to allow our users to use our default projects and presets without the worry of accreditation.  I think we can achieve that without conflict, I hope you feel the same.

Yes, that does mean we will ultimately have to remove most of our current bundled projects in the future, but  I really hope this isn't perceived as anything but good planning for our users and our contributors.  We aren't trying to coerce artists into releasing music without accreditation.

**Comment by SecondFlight** [comment]
I suppose I should probably say that @diizy's description of CC0 would be fine with me. My issue is that his description of CC0 isn't correct as far as I can tell. I don't really care if someone is messing around with my song, makes something cool, and then uploads it somewhere. That kind of thing can be expected in this situation. What i don't want to do, however, is loose my rights to the original work.

**Comment by Umcaruje** [comment]
>I suppose I should probably say that @diizy's description of CC0 would be fine with me. My issue is that his description of CC0 isn't correct as far as I can tell. 

What @diizy described is actually CC BY, not CC0. Public domain works don't requre any attribution simply because nobody can own them. That's the main issue here. 

With CC BY you can edit, modify and sell the works, as long as you clearly state the author.

With CC0 you can edit, modify and sell the works, but you don't need to attribute the author. This can easily escalate to someone misrepresenting slightly modified songs as their own. I'm not saying that this won't happen with any other licence, but CC0 is making that easier. To me, as an artist, this is a pretty big deal.

**Comment by SecondFlight** [comment]
Actually what @diizy described was a sort of restricted CC-BY in which you can edit the work without attributing the original author, but you can't flat-out steal it. This really doesn't work in practice though, because I change one note of someone's song then technically I've edited it.

**Comment by diizy** [comment]
On 01/26/2015 11:17 PM, Umcaruje wrote:
>
>     I suppose I should probably say that @diizy
>     <https://github.com/diizy>'s description of CC0 would be fine with
>     me. My issue is that his description of CC0 isn't correct as far
>     as I can tell.
>
> What @diizy <https://github.com/diizy> described is actually CC BY,
> not CC0. Public domain works don't requre any attribution simply
> because nobody can own them. That's the main issue here.
>

You're confusing attribution as defined by CC licenses with the moral
right of attribution. The latter is something that can't be taken away
by any license and is entirely separate from the right to control
distribution/copying. The artist always retains this right, it cannot be
transfered or revoked. For instance, Bethoven's 5th is in the public
domain, however no one can suddenly claim authorship of Bethoven's 5th
because the moral rights of the author are non-reversible. We know the
author of Bethoven's 5th, which is Bethoven.

**Comment by diizy** [comment]
On 01/26/2015 11:24 PM, SecondFlight wrote:
>
> Actually what @diizy <https://github.com/diizy> described was a sort
> of restricted CC-BY in which you can edit the work without attributing
> the original author, but you can't flat-out steal it. This really
> doesn't work in practice though, because I change one note of
> someone's song then technically I've edited it.
>

Actually that's also wrong. Depends on jurisdiction, but most courts
would very likely rule one note as an insufficient change to consider
the work a derivative.

In any case that doesn't really matter. As long as the original song is
available and distributed via LMMS, the original work will always be
attributed to the original author.

Of course, someone can take your song and try to represent it as their
own. But technically, that's also possible no matter what license the
song is licensed under. If you license your song as CC BY, and someone
uses it without attribution, say, someone living in China, what are you
going to do? You're technically entitled to sue them, but are you going
to? Will you really go through a whole legal battle, spending who knows
how much money, just because some idiot is claiming a song you made as
their own - and especially since people can easily find the original
song with your attribution and check it for themselves?

Unless it's a corporation who's using your song for commercial purposes,
there's very little to be gained in pursuing legal action...

**Comment by SecondFlight** [comment]
Assuming this is 100% accurate, then I suppose this could make a lot of sense. The issue I have with this is that this licensing affects anything else I want to do with the song - what if I want to retain the sole right to sell the song?

For me, this isn't really about what legal action I would take if someone stole my music. I doubt I have the funds to sue anyone, and it probably wouldn't be worth my time even if I did. People are more likely to follow rules you set in place, and I still want to be able to retain some boundaries.

**Comment by Spekular** [comment]
Forgot to mention this earlier, but If we're going with CC0 tracks I have a few old songs I'd love to disown. "Who me? No I never made that, yuck!" (Jokes aside, I do have some songs that might be decent enough to add that I wouldn't mind giving away)

**Comment by Sti2nd** [comment]
@SecondFlight You are definitively not talking about a demo song then, but a full scale project that you want to keep the rights to. You can sell it, but not with the sole rights of course.

Full scale projects from good artists would perhaps be cool to have in LMMS, and those probably must have a licence, but weren't this discussion about demo projects? Or am I confusing the two other threads now -_-

**Comment by Spekular** [comment]
@Sti2nd you my have. I definitely did, oops.

**Comment by SecondFlight** [comment]
I think it's reasonable to ask people to put CC0 on a small loop they make. I was talking about a full project.

**Comment by tresf** [comment]
@SecondFlight you can still use your version of the song.  That's the beauty of CC0.  You can still own your version, but there is a strange catch-22 that you can get into... 

 * Your separately licensed work needs to be unique and different enough from the CC0 version to ever be able to defend a copyright claim.  If its the same song, the defendant can claim they copied the CC0 version, not your version.
 
So yes you are voiding all rights to your own track, but you and others can reserve whatever rights you'd like on derivative works.

For example, last year I made a track which eventually made it onto the Best of LMMS album.  It was a collaborative work and I don't have permission (nor do I want to seek permission) from all of the vocalist to release it under CC0.   It just doesn't make any sense to do this.

However,  I was able to isolate a very early version of the track melody and beat which I think would be a good CC0 candidate.

If I submit this for "CoolSongs", it will be under a CC0 license.  Someone can do whatever they want.  I've protected the Best of LMMS track by [making it different enough](https://lmms.io/lsp/?action=show&file=6003) that we can still claim ownership and reserve rights to our published version.

**Comment by SecondFlight** [comment]
Well yes, in theory that works great. My song is a remix, so regardless of what I want I need to respect Greippi's views, which he has made plain.

Also, I've already uploaded a version to soundcloud. It has 3 sound effects added to it in 3 different places, and that is the only difference.

**Comment by tresf** [comment]
> Well yes, in theory that works great. My song is a remix, so regardless of what I want I need to respect Greippi's views, which he has made plain.

Right, this was hypothetically speaking about an original work, sorry for the confusion.

**Comment by Spekular** [comment]
@grejppi do you still want your song removed, or have you changed your mind? This pull request ought to be merged or closed, and discussion should really happen on #1693

**Comment by grejppi** [comment]
@Spekular depends on the outcome of this discussion. Removed if future contributions are only allowed under CC0, retained if other licenses will still be an option.

**Comment by tresf** [comment]
> @Spekular depends on the outcome of this discussion. Removed if future contributions are only allowed under CC0, retained if other licenses will still be an option.

:+1: 

And to @Spekular's point, this PR can probably be closed if that is the case because any `CC0` cleanup will occur as a single PR... individual ones probably aren't needed.

**Comment by diizy** [comment]
On 01/27/2015 05:40 PM, SecondFlight wrote:
>
> Assuming this is 100% accurate, then I suppose this could make a lot
> of sense. The issue I have with this is that this licensing affects
> anything else I want to do with the song - what if I want to retain
> the sole right to sell the song?
>
> For me, this isn't really about what legal action I would take if
> someone stole my music. I doubt I have the funds to sue anyone, and it
> probably wouldn't be worth my time even if I did. People are more
> likely to follow rules you set in place, and I still want to be able
> to retain some boundaries.
>

Well, you're certainly entitled to your own boundaries.

For example... if you want to contribute code to LMMS, you have to do it
under the GPLv2 license, you can't add any terms on top of that license
for the usage of your code... if you're not comfortable with releasing
your code under GPLv2, then you shouldn't contribute code to LMMS.

It's the same thing with demo songs... if we decide the songs should be
licensed in a certain way in order to be convenient and useful for our
users, then that license will be the terms under which demo songs need
to be contributed, if you're not comfortable with that, then there are
tons of other avenues for you to promote and share your music.

IMO we should think about the users as a priority here. I could be
writing proprietary code for some music software company (well, in
theory) but I choose to not do that, and instead give my code away under
a license that makes it useful to the community. Generosity is
meaningless unless it requires some sacrifice. The same, again, applies
to demo songs... it is a sacrifice the artist is making in order to help
our users... just the same way as contributing code is a sacrifice made
in order to help our users.

You might also point out that the GPLv2 is a reciprocal "share-alike"
license, while CC0 is not. But that's a bit like comparing apples to
oranges. The code is under GPL because that ensures it stays free. The
users however don't need to access the source code in order to produce
music. They don't need to care about the software license, so any
restrictions in the GPL do not concern them. The GPL doesn't require the
user to label every song they make with LMMS as "made with LMMS", they
don't need to attribute the LMMS developers in their work. However, if
the demo songs are licensed under a CC-BY license, then the users are
required to attribute the original material, and this reduces the
usefulness of the demo songs to the users.

We should maybe not think of the demo songs as pieces of art that we're
publishing under our own names as artists. Maybe they should be seen
more as educational material, given away by their creators in order to
help others learn and create new things. It may not earn you money but
you'll get that warm fuzzy feeling of helping others :)

**Comment by Sti2nd** [comment]
> We should maybe not think of the demo songs as pieces of art that we're
publishing under our own names as artists. Maybe they should be seen
more as educational material, given away by their creators in order to
help others learn and create new things.

Indeed, we should make a difference between demo projects and other projects IMO. 
What do you think about putting for example unfa's Spoken into it's own folder called Licenced Songs? If some people have created an amazing full length song with native LMMS and don't want to give up credit that could also qualify for the folder.

**Comment by diizy** [comment]
On 01/27/2015 11:51 PM, Stian Jørgensrud wrote:
>
>     We should maybe not think of the demo songs as pieces of art that
>     we're
>     publishing under our own names as artists. Maybe they should be seen
>     more as educational material, given away by their creators in order to
>     help others learn and create new things.
>
> Indeed, we should make a difference between demo projects and other
> projects IMO.
> What do you think about putting for example unfa's Spoken into it's
> own folder called Licenced Songs?
>

Why do they need to be bundled with LMMS? Why not just host them on the
LSP? If you want to share the original project file but limit its use,
that seems like a better fit for your song.

They can also post that song on Soundcloud/Youtube/etc and advertise to
people it's made with LMMS. Why does it need to be bundled with LMMS, if
the users won't be able to use it freely?

**Comment by Sti2nd** [comment]
> Why do they need to be bundled with LMMS?

unfa's song can be good as benchmarking and testing, and since demo projects are probably going to be projects to learn and have fun with, the songs in the licenced folder could push LMMS to the limits, the very best, show that a specific genre can be done in LMMS for example? Some full scale songs would be nice at least, but I agree on that demo songs will be the most important projects and we will focus mostly on demo projects.

**Comment by tresf** [comment]
>  the songs in the licenced folder could push LMMS to the limits, the very best, show that a specific genre can be done in LMMS for example

Yes, but our LSP and album does that and does it better IMO.  I'm not sure shipping with these tracks offers a whole lot of quality to the software.  They're good tracks, but we really need users to step up and speak on behalf of what they've learned from them to warrant their inclusion against a CC0 future.  I understand there's a bit of pride that goes into having a track listed in the CoolSongs, but pride aside, we should have some users expressing how valuable these are to the composition process.  I think YouTube, Bandcamp and soundcloud can do the promo part for us.

**Comment by tresf** [comment]
@Sti2nd why are we still discussing this in the wrong thread?  Sorry @grejppi for the above comments as they were intended for the sister thread.

**Comment by SecondFlight** [comment]
It does it better, in theory anyways, but it's not reliable. There aren't enough people to rate songs on LSP - whether a good song gets to the top of the list is more a matter of who happens to click on it than anything else. Anybody can boost downloads just by ctrl-clicking the link multiple times, so that doesn't work. I still think it's a good idea to have some songs in LMMS.

Yes, bandcamp can do a great job, but when over half of the songs are made with external plugins, it's not a very good benchmark of what LMMS is capable of by itself. I think there is a benefit to being able to rip apart a project and see how it works.

**Comment by diizy** [comment]
On 01/28/2015 01:08 AM, Stian Jørgensrud wrote:
>
>     Why do they need to be bundled with LMMS?
>
> unfa's song can be good as benchmarking and testing,
>

Well up to 1.2 at least, if we break compat in 2.0 then the point
becomes moot...

**Comment by Sti2nd** [comment]
@tresf cause Vesa seems to only read this thread, no other reason really, lol

**Comment by SecondFlight** [comment]
> if we break compat in 2.0 then the point
becomes moot...

And we're basically planning to, no?

So why is this even an issue?

**Comment by diizy** [comment]
On 01/28/2015 02:39 PM, Stian Jørgensrud wrote:
>
> @tresf <https://github.com/tresf> cause Vesa seems to only read this
> thread, no other reason really, lol
>

I'm currently unimaginably busy, I only have like 5 minutes a day to
check emails and such... If there's something you absolutely want my
comment on, you can always email me directly, outside the mailing list.

**Comment by Sti2nd** [comment]
> And we're basically planning to

To break compat, yes, already planned and done :p

**Comment by tresf** [comment]
Closing for several reasons:
 * SecondFlights track puts a merge conflict on this
 * The author's decision is dependent on a larger decision
   * which we can't make on a whim
    * which already has a bug report dedicated to it
 * If this is removed it will be part of a separate PR anyway

@grejppi if you disagree with this decision to close the PR, let us know and we'll be happy to accommodate.

**Pull request closed without merging**
