### PR TITLE
Fix Carla compile error

### PR DESCRIPTION
**Pull request by rola22**
Fixed Carla compile errors in Linux Mint.

### CODE REVIEW

**Comment by rola22** [comment]
Don't know why but both CARLA_API_EXPORT and CARLABASE_EXPORT allows me to compile LMMS on Linux Mint.
However CARLABASE_EXPORT makes LMMS crash.

**Comment by PhysSong** [comment]
@rola22 Could you check if #6403 works?

**Comment by rola22** [comment]
@PhysSong I'm still learning git, and i don't know if i did it ok.
I went to my lmms main folder, and in console i typed:
`git fetch origin 9c49a7747c38ac0a3dd1c21d30019a830155d500` which as i understand downloaded your changes.
I've checked files, and your changes were here so i tried to compile, but i still got compilation errors.

I have also cloned lmms from your repo, switched to fix-carla-compilation branch, and after compiling it everything worked for me.

Sorry for bad english :)

**Comment by PhysSong** [comment]
> I have also cloned lmms from your repo, switched to fix-carla-compilation branch, and after compiling it everything worked for me.

That's a great news! Thank you for your contribution, but I'm closing this in favor of #6403 which is more correct.

**Pull request closed without merging**
