### PR TITLE
Use weak loading of libjack

### PR DESCRIPTION
**Pull request by tresf**
WeakJack is a third party tool that abstracts the JACK Application Binary Interface for use with various jack versions.  It helps make LMMS a portable application on Linux.

* This used to be part of #3688.  It was separated to make tracking (blaming, cherry-picking, submoduling) easier.
* This is 100% 3rd-party code and should eventually be submoduled.

### CODE REVIEW

**Comment by tresf** [comment]
Travis-CI passes for Linux and Windows.  I'm not waiting for Apple, this has been tested several times in the other PR.  Merging.

**Comment by lukas-w** [comment]
Can we move the third-party code to a dedicated directory, such as `src/3rdparty`, similar to what I've done in #3873 or #3475? This will make it clear to everyone that it's not part of LMMS, and we can easily exclude it from tools like automatic code formatting.

Also, maybe we should add a file or a comment somewhere that documents the upstream source of the code.

**Comment by tresf** [comment]
@lukas-w I agree fundamentally, although I see little benefit in doing refactoring in `stable-1.2` branch.  We could triage these refactoring items into a new milestone so that we don't forget them?  `ArashPartow/exprtk` is another candidate.

**Comment by lukas-w** [comment]
Sure 👍

**Pull request merged**
