### PR TITLE
Add Ukrainian translation

### PR DESCRIPTION
**Pull request by NeiroNext**
Add Ukrainian translation for `master` branch

### CODE REVIEW

**Comment by Wallacoloo** [comment]
That was really quick!

**Comment by NeiroNext** [comment]
@Wallacoloo Thanks ! :smiley:

**Comment by tresf** [comment]
@NeiroNext why did you close this?  Are you going to issue a new pull request?

**Comment by NeiroNext** [comment]
@tresf Very very sorry, I have some problem with git when want to rebase old commit, merge is not fine because it make two commits
I would be happy if you tell me what to do in this case is to save one commit, and send it to the global repository.

Sorry!

**Comment by tresf** [comment]
If this happens again, you can Fast Forward per https://github.com/LMMS/lmms/wiki/%5BGit%5D-Fast-forward-personal-branch-to-upstream

Then force push.

Then last you can squash your commits back down per http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

Of course for a single translation, what you've done by closing out the PR is probably much less work for the short term, so whatever works. :+1:

**Comment by NeiroNext** [comment]
@tresf Thanks!

**Comment by NeiroNext** [comment]
@tresf `git push --force` =) It's simple way in my situation (I used only `git push` and so have error with `rebase`)
Your links very interesting, especially second link very very interesting!
Thanks again!

**Pull request closed without merging**
