### PR TITLE
fix crash on export per command line with sample track

### PR DESCRIPTION
**Pull request by BaraMGB**
this should fix https://github.com/LMMS/lmms/issues/3338

@zonkmachine can you look at this?

### CODE REVIEW

**Comment by zonkmachine** [comment]
Now the file loads and exports fine but never hands back to main() . The Render Manger is stuck reporting 100% .

**Comment by zonkmachine** [comment]
Sometimes it renders just fine. I think I've seen this before. Just once in a while a render will fail to complete. It may be that you've poked another bug a bit. I'll continue testing this to see if I can find a pattern in it.

**Comment by BaraMGB** [comment]
Does it depends on the project?

**Comment by zonkmachine** [comment]
> Does it depends on the project?

It seem to depend on the length of the samples. I'm testing this with noise samples of various length and with a 15 second sample in the project there is about 50% chance of the renderer getting stuck after export.

**Comment by zonkmachine** [comment]
Sorry. I went back 50 commits and this bug is there also. It's hard to see a real pattern in it though other than the sample track being involved. This commit fixes the issue reported and should be merged. I can probe into the hanging renderer a bit more and write a new issue for it.

**Comment by zonkmachine** [comment]
The hanging render on longer Sample Tracks is an SDL thing.
I'm not done bisecting this but it may have happened around these commits 8497d39eec78f3f23f0581898e18868025d5070e e55ec80c3d956dea8674afc0755bc87831c64ce6

**Comment by zonkmachine** [comment]
New issue opened for the SDL issues here: https://github.com/LMMS/lmms/issues/3344
I suggest you merge this.

**Comment by BaraMGB** [comment]
Okay. Thanks for the investigation

**Pull request merged**
