### PR TITLE
See  #2046

### PR DESCRIPTION
**Pull request by friedemann-**
See issue  #2046

### CODE REVIEW

**Comment by tresf** [comment]
This is nice, thank you!

A few things.... 

 * You've packed a lot of patches in this commit, which makes it a bit harder to review and to test the individual items.  This isn't bad, but can delay the merge a bit as the review time will take longer.

 * You should get rid of the "Merge remote-tracking branch" commit if possible.  It will be in our merge history and offers no value.  To do this on your branch, you usually:
  
  ```bash
  git rebase -i HEAD~2
  ```
  * Change the `11c7718` to `squash`, save.
  * When prompted, comment out the `Merge remote-tracking` message, save.

  ```bash
  git push --force
  ```
 
 * Last item is to restart Travis since the build fail was unrelated to your code change, but rather Travis ran out of space.  You shouldn't have to do this once your new squashed commits make it in, it should re-run the Travis build job and get green lights, but FYI.

**Comment by tresf** [comment]
Oh.. one more item....  although seemingly redundant, please rename the PR to something more relevant. It will only make things easier when we're looking for this change while troubleshooting a month or a year from now..

**Comment by tresf** [comment]
> there was no possibility to change the volume of an multiple notes.

Is this comment in regards to using the keyboard exclusively (i.e. shortcut keys?)  AFAIK, we have recently added the volume functionality with mouse cursor.

**Comment by tresf** [comment]
@friedemann-  We could really benefit your patches, but can we get some feedback on the questions above?  There are some cleanup that must occur prior to us merging.  If we don't hear back from you in a week, we'll close this out and wait for a new pull request.

**Comment by Spekular** [comment]
@tresf Two weeks and two days have passed!

**Comment by tresf** [comment]
> @tresf Two weeks and two days have passed!

Thanks.  @friedemann-  There is some cleanup that must occur prior to us merging. Closing as we will need to wait for a new pull request.

**Pull request closed without merging**
