### PR TITLE
Add an Empty template

### LINKED ISSUE #2202: Empty Template
Hello. i think it is a little boring to remove and clean up the default track, automation, triple osc and baseline at start, it is better to have a "Clean" or "Empty" template like FL Studio. can it be included in the default templates that coming with project?

### PR DESCRIPTION
**Pull request by Umcaruje**
Resolves #2202.
Adds an Template with no tracks whatsoever.

screenshot_2015-08-29_00-59-01

Here's how it looks when you open it up:

screenshot_2015-08-29_00-59-22

### CODE REVIEW

**Comment by Wallacoloo** [comment]
Nice. For a stripped down template like this, should we even have the Controller Rack be opened by default?

**Comment by Wallacoloo** [comment]
No response? I'll merge as-is then.

**Comment by Umcaruje** [comment]
Sorry, I meant to respond, but just forgot :) For me, the controller rack was always there when opening the default project, so I figured that the empty project should look like that as well. If you want, I could issue another PR (or push directly to master) to make the controller rack hidden in this template.

**Comment by Wallacoloo** [comment]
Nah, I think the lack of input by anyone on github shows that there's not much overall preference one way or the other. May as well leave as-is, and with @michaelgregorius's recent work, it's pretty easy for a user to change the controller rack visibility if they have a strong preference.

**Comment by mamins1376** [comment]
thanks for this work.

**Pull request merged**
