### PR TITLE
Better default working directory

### LINKED ISSUE #1135: ~/lmms in our build tutorials
Does anyone else have a problem with the fact that our build tutorials all but encourage building in the same directory that the software defaults to?

i.e. `git clone` in the home directory (which is default Terminal landing location for most flavors of Linux/Unix) puts the source code in the same folder that the software uses as its working directory.

I thought of this when @eagles051387 had to do a fresh pull of the github source.  Telling him to blow away `~/lmms` could have unintended consequences. :)

There's not an easy way to prevent this other than changing our default working directory, or making our build instructions specifically move the person from that directory prior to issuing the `git clone` command.

I never use `~/lmms` as the default working directory as I store my samples on a cloud service so I've never blown away any projects or samples, but it seems like it has the potential to mess stuff up.

Thoughts?

-Tres

### PR DESCRIPTION
**Pull request by tresf**
Better behavior of default working directory:

* Fresh installs of LMMS (e.g. no `~/.lmmsrc.xml`) will default to the more browsable, more sane and less conflicting `~/Documents/lmms`.
~~* No longer prompt to create the home directory.~~

**Note:** The Qt4 logic is currently untested.

Closes #1135

### CODE REVIEW

**Comment by PhysSong** [comment]
> Fresh installs of LMMS (e.g. no `~/.lmmsrc.xml`) will default to the more browsable, more sane and less conflicting `~/Documents/lmms`.

:+1:
> No longer prompt to create the home directory.

Could you explain why did you change that?

**Comment by zonkmachine** [comment]
> Note: The Qt4 logic is currently untested.

Tested, works fine.

**Comment by tresf** [comment]
> No longer prompt to create the home directory.

Because asking newcomers a confusing question on first install is a bad first impression.

**Comment by PhysSong** [comment]
> > No longer prompt to create the home directory.

> Because asking newcomers a confusing question on first install is a bad first impression.

I agree, but I found some situations where that behavior is undesirable. When the working directory is set by user and moved/deleted/temporarily unable, prompt is still valid.
I suggest checking `ConfigManager::inst()->value( "app", "configured" ).toInt()` if you want to detect fresh install.

**Comment by tresf** [comment]
> When the working directory is set by user and moved

A warning is valid and a blocking dialog is the wrong way.

> /deleted/

I'm not sure how this is helpful to anyone in this case.  They can delete the bread crumbs.  It's of zero consequence.

> temporarily un[avail]able

This dialog offers no contextual evidence that it's temporarily unavailable and the mkdir will silently fail.  I'm not sure the use-case here.

> I suggest checking ConfigManager::inst()->value( "app", "configured" ).toInt() if you want to detect fresh install.

That would be create unpredictable behavior.  It's better to just create the directory in 99.9% of use-cases.  We shouldn't be coding to the 1%.

I assume the atypical use-case you're describing is a user-space mountpoint where a driver is mounted in `~` instead of `/media/`, etc?  Apps should create working directories.  Arguably, the `.lmmsrc.xml` should live directly inside the working directory too, it has no place in `~/.lmmsrc.xml`, but I plan to address that as part of DataFile moving from XML to JSON, related: https://github.com/LMMS/lmms/issues/3981.

**Comment by PhysSong** [comment]
I use a NTFS partition as the working directory. If LMMS creates the working directory without prompt when the partition is not mounted, it will create a directory which was the path for the partition. That can break several things(bookmarks, other programs' data directories).

I think it's unusual, but I think it'd be better to cover such cases.

**Comment by musikBear** [comment]
> Arguably, the .lmmsrc.xml should live directly inside the working directory too, it has no place in ~/.lmmsrc.xml

Imo in **Data**, its wrong to force-install things in C: when a user has chosen a different partition as install-point.

**Comment by tresf** [comment]
> Imo in Data

I'm not sure what you're talking about.  There's no such thing as `data`.  Perhaps you're referring to `%APPDATA%`, but that's still explicit.

>  its wrong to force-install things in C:

Nothing's being force-installed anywhere, please don't make blanket statements.

**Comment by tresf** [comment]
Tested this for a day, accidentally clicked the wrong folder and created a bunch of breadcrumbs.  I don't like the dialog and the experience should be better but I'll have to agree with @PhysSong and leave it out of scope for now.

Reverted and ready for review/merge.

**Comment by musikBear** [comment]
> There's no such thing as data

Now you confuse me:

**Comment by tresf** [comment]
@musikBear, that's unrelated to the working directory.  Install LMMS wherever you want. :)

**Comment by tresf** [comment]
```
:..LMMS \data
```

The problem @musikBear is that you are making up terms.  Yes the skeleton directory is created automatically.  That's done as a convenience so that when you save something such as a preset or a sample you don't have to create the directory -- or worse -- you create it in a non-relative path and projects won't load.

> who made the descission to place files here.
> @tresf

The dev team did.  Otherwise the folder structure is unobvious and relative paths break.  This is a stop-gap courtesy until we introduce portable project files.

**Comment by zonkmachine** [comment]
Shouldn't we probe for `~/lmms` or `~/Documents/lmms` when starting with no `.lmmsrc.xml` ? You'd probably want to default to an existing working directory.

**Comment by tresf** [comment]
> Shouldn't we probe for ~/lmms or ~/Documents/lmms when starting with no .lmmsrc.xml ? You'd probably want to default to an existing working directory.

Sure.  `~/Documents/lmms` doesn't need a probe because that's the new default.  #1135 is what inspired this change so we'd need to know what to match on so we don't accidentally select the code repository.

**Comment by zonkmachine** [comment]
Look for`QDir::home().absolutePath() + "/lmms/projects/"` ?

**Comment by tresf** [comment]
> Look `forQDir::home().absolutePath() + "/lmms/projects/"` ?

Done via 052eedc.  Ready for testing/review.

**Comment by zonkmachine** [comment]
Works as intended.

**Comment by lukas-w** [comment]
@tresf Why did you close this?

**Comment by tresf** [comment]
> @tresf Why did you close this?

Branch cleanup, it was a mistake.

**Pull request merged**
