### PR TITLE
Minor refactoring

### PR DESCRIPTION
**Pull request by teeberg**
I've just started to work on the source and cleaned up as I saw fit on the way. Checking in to make sure my code refactor/cleanup meets other developers' expectations!

### CODE REVIEW

**Comment by Lukas-W** [comment]
Looks good, thanks.

If you find yourself refactoring iterator for loops again in the future, I suggest using C++11's range-based for loop:
```c++
// This (although there's some ugly const-ness in here)
for (Note* const& note : notes) {
    note->setSelected(false);
}

// Instead of this
NoteVector::ConstIterator it;
for( it = notes.begin(); it != notes.end(); ++it ) {
    Note *note = *it;
    note->setSelected( false );
}
```

**Comment by tresf** [comment]
> If you find yourself refactoring iterator for loops again in the future, I suggest using C++11's range-based for loop

I prefer these too, so as long as index information can ve disgarded, which seems to be about half of the time in my experience.

**Comment by teeberg** [comment]
I didn't realise you were compiling c++11! How about using `auto` then for that loop?
```cpp
for( auto& note : notes )
```
It is hardly ever used in the code base, I wonder why!

**Comment by diizy** [comment]
On 01/12/2015 07:33 AM, Jonas Trappenberg wrote:
>
> I didn't realise you were compiling c++11! How about using |auto| then
> for that loop?
>
> for( auto& note : notes )
>
> It is hardly ever used in the code base, I wonder why!
>

Maybe because it makes code less readable. I'd prefer we kept not using
it, it's much better to declare explicitly. Readability is pretty
important in a project this size.

**Comment by Lukas-W** [comment]
I tend to agree with Vesa. `auto` may be super easy to write, but when reading code it's harder to understand what's happening.

**Comment by curlymorphic** [comment]
Im probably too stuck in my ways to be objective on this. 

The only time i ever use auto in a typecast language is when the returned type is dynamically created, thus unknown at compile time (C# and linq is my experience in this).

Auto can be easier and the type can to total obvious to coders the know the code base well, but Lmms probably only has 3 - 4 developers in this category, and only 2 of them are active (from what i can see when looking at the commit history). There are a few newcomers here (Im in this bracket) that still need things spelt out. With the nature of open source hopefully time will bring more newcomers, so there will always be developers learning the code base.

When I started out with lmms, I was shocked at the lack of documentation and comments. But the style it is written in makes things very clear. So clear in fact the i feel the current level of comments is correct, and I delete mine before any pull request. If Auto were to be used I feel this would no longer be the case, and better documentation would be required.

**Comment by tresf** [comment]
> When I started out with lmms, I was shocked at the lack of documentation and comments. But the style it is written in makes things very clear. So clear in fact the i feel the current level of comments is correct, and I delete mine before any pull request. If Auto were to be used I feel this would no longer be the case, and better documentation would be required.

Agreed.  The comments are so sparse that it is quite intimidating at first, but once you crawl around for a while it becomes increasingly obvious that the style makes these things fall into place.

However, I do feel we need some better explanations at least on the high-level libraries.  Just a sentence over each class would go a long way to understand what it is used for.

**Comment by Lukas-W** [comment]
> I delete mine before any pull request.

:scream: 

Please, please don't!

**Comment by curlymorphic** [comment]
> Please, please don't!

Oh :(

I wish i knew that.

I think i have had some sort of comment block at the start of nearly every class and function i have ever written since I learnt to code pascal. Not doing them, to try and keep in the current code style has been hard for me.

@Lukas-W 

do you want 1 line comments on future bug fixes?

example

//760 Improve search field

**Comment by Lukas-W** [comment]
Well I don't think we need comments that do nothing but provide history about the GitHub issue that introduced the change, but short explanations about what a block of code does would be great. Especially high-level, I agree with Tres there.

So if you come across some code/function/class, understand it, and feel that there's documentation missing (which is actually everywhere in our code), just drop a line or two and make the world (aka our code) a better place. :)

**Pull request merged**
