### PR TITLE
Fixed a race condition that caused clicks and pops (partial fix for #1662)

### PR DESCRIPTION
**Pull request by Fastigium**

### CODE REVIEW

**Comment by curlymorphic** [comment]
Im so happy to see this.

**Comment by diizy** [comment]
No.

**Comment by diizy** [comment]
Adding more locks is not the solution. The whole point of using atomics is to ensure lockless operation to preserve RT-safety. Locking is bad for RT-safety. This needs to be dealt with in another way.

**Comment by curlymorphic** [comment]
> No.

your people skills are improving I see!!!



> Adding more locks is not the solution. The whole point of using atomics is to ensure lockless operation to preserve RT-safety. Locking is bad for RT-safety. This needs to be dealt with in another way.

would you mind giving us your advise on how you would like to see this fixed please?

**Comment by Umcaruje** [comment]
>No.

Could you keep in mind that this issue has made numerous people not upgrade to LMMS 1.1 and also it has made them very unhappy. AFAIK RT-safety will largely be addressed in LMMS2 effort. 

Can a small change like this, that fixes a major bug, slip thru the mighty RT-safety firewall? This would be a great temporary fix for a bug that has affected a lot of people.

**Comment by tresf** [comment]
@diizy do you have objections to pushing this to `stable-1.1` as an interim solution to the bug and leaving master untouched?

-Tres

**Comment by Sti2nd** [comment]
He better not have...

**Comment by Fastigium** [comment]
Hang on, I may just have thought of a way to fix this without using a lock.
Only it's 1am here now :P. I'll give it a shot tomorrow!

**Comment by unfa** [comment]
6 lut 2015 19:40 "Dave" <notifications@github.com> napisał(a):
>>
>> No.
>
> your people skills are improving I see!!!
I LOLed harder than a brickwall limiter.
Sorry. Let's all improve our people skills. No?

>>
>> Adding more locks is not the solution. The whole point of using atomics
is to ensure lockless operation to preserve RT-safety. Locking is bad for
RT-safety. This needs to be dealt with in another way.
>
> would you mind giving us your advise on how you would like to see this
fixed please?

**Comment by Fastigium** [comment]
Just to be sure everyone sees it: I propose a lockless fix in #1745

**Comment by diizy** [comment]
Ok so I'm all for fixing bugs but when the fix is arguably worse than the actual bug, and actually undermines the efforts of others (ie. getting rid of locks) then I have to argue against it. People, please remember, we're not under a deadline here. It's better to get things done right - if we keep on piling up "fast and easy" fixes, we'll be left with a huge mess of spaghetti code and kludges that are impossible to maintain.

This part of the mixer code is very speed-critical, it is code that is called n times every period, where n = number of mixer channels. So you can see why adding locks into it is a very, very bad idea. We need this code working locklessly. It's not only a matter of RT-safety, but also of performance, this is likely to cause "traffic jams" or "bottlenecks" in the mixer multithreading operation.

Since the OP says this is would only work as a partial fix anyway, I'm thinking the problem may actually be elsewhere in the program flow. What we need to do now is to figure out the exact parameters of this bug. Is the clicks/pops thing happening on all platforms? Does period size have any effect on it? Or CPU usage? If we can figure out why this is happening, how the race condition is triggered, then we should be able to come up with a solution that doesn't require locking.

**Comment by Sti2nd** [comment]
For master and future versions of LMMS we all agree with you diizy, but having a program out in the wild right now which can be experienced as useless, could be devastating.

**Comment by diizy** [comment]
There will always be bugs, even ones considered "devastating" to some. If we go into panic mode and instantly patch them up with quick-and-dirty fixes, that's going to add up and cause even more problems in the long run. 

@Sti2nd, I appreciate your input, I really do, but you don't have to maintain the codebase, so you maybe could take my word for it if I say, as a maintainer, that some code is not a good solution for a problem.

In any case it's a moot point, the OP has come up with a better fix that doesn't require locks. See now, sometimes people just need a little push to come up with better solutions. I don't mind administering some "tough love" from time to time if it makes our codebase cleaner and better functioning. 

And as for people skills... go take a look at how Linus handles kernel development. I'm from the same country as him, so maybe you guys are getting off **easy** ;)

**Comment by Sti2nd** [comment]
> that's going to add up and cause even more problems in the long run.

If you take it into master which none of us were suggesting :)

**Comment by tresf** [comment]
> If you take it into master which none of us were suggesting :)

@Sti2nd Since we tend to merge our stable fixes downstream eventually we have to weigh the pros and cons in times like these.

In the case of this bug, it worked out in favor of the ideal scenario.  Kudos to those involved, including Vesa for the tough love.  I'm excited to see the teamwork as well as a some great investigation by @Fastigium and some others.

There will be scenarios where the ideal scenario won't be available for weeks or months or years and the "right" decision will be shelved in favor of the non-ideal fixes.  We need to keep these non-ideal fixes to a minimum.  As far as "not being under a deadline", I feel that depends on the severity, impact and the branch.  In this case, it was a moderately affecting bug (we weren't inundated with requests, really). :+1:

**Comment by Spekular** [comment]
@diizy I had that comparison in mind after your single word response, but I
thought it was a bit harsh. Since you took it there yourself though, you
need to start calling things " 'sloth dropped on it's head as a baby' level
idiotic" if you wanna match him.

**Comment by Sti2nd** [comment]
> we weren't inundated with requests, really

Slightly disagree :p To back up with some actual facts: I have personally answered maybe 30 persons with this problem and suggested changing sound drivers etc, in some cases it worked, in other cases not. I actually gave up responding to all of them, couldn't figure out a fix. Perhaps I should have told that in an e-mail on the mailing list?

How many problem affects isn't necessarily visible on github since we have a "if it is an existing issue don't create a new" rule.
image

**Comment by tresf** [comment]
Well I'm not sure that screenshot is illustrative (it has many topics that are unrelated in its listing), but duly noted.

The fact that our own dev team had difficulties reproducing lends to the severity (or lack thereof).  But you have a good point.  We should probably encourage the forum admins to help tally these things in our tracker.

**Comment by Fastigium** [comment]
@diizy I don't mind the "tough love", though I think I would have if I had been younger. But I just came in on all this, not knowing a thing about LMMS's codebase except what I found out in the course of a single bug hunt. So I needed someone to tell me how to fix this properly. You did, I changed my fix, all is better :).

About the exact parameters of the bug: there is a lot of data in #1662, though it is spread over many posts. A few points AFAIK them:
 1. the clicks/pops have been confirmed on Linux and Windows,
 2. the period size influences their length in samples,
 3. higher CPU usage results in slightly more pops,
 4. enabling power saving on Windows laptops results in many more pops,
 5. more FX channels mean more pops,
 6. versions up to 1.0.96 have almost no pops whereas 1.0.98 and later have them noticeably,
 7. the exact commit that makes that difference seems to be https://github.com/LMMS/lmms/commit/ca06a10a4292f95c8922f4b089dbf7756078078c.

You can read all about how I went from this data to my initial fix starting [here](https://github.com/LMMS/lmms/issues/1662#issuecomment-72637763). I'm not sure if my new fix solves the problem entirely; time will have to tell. I can still reproduce an occasional click while mashing the "add FX channel" button, but none during regular playback.

@tresf Yeah, reproducing this issue was a key problem. I failed at it initially or I might have chimed in earlier. It was sheer luck that I found the method that I shared in my [first comment in #1662](https://github.com/LMMS/lmms/issues/1662#issuecomment-72370457) :P. And I only tried again because @Sti2nd asked me on Soundcloud.

**Pull request closed without merging**
