### PR TITLE
Enter key play pause

### PR DESCRIPTION
**Pull request by zonkmachine**
I added play/pause function to the Enter key (in all the editors) . It's not as useful though on LMMS if your music is depending heavily on samples/loops since sound files and arpeggios won't start in the middle but it's still a practical/common key assignment and it behaves like the GUI play button.

### CODE REVIEW

**Comment by musikBear** [comment]
Neither NUM[0] or sh+space has been implemented.
I request this issue reopened.

**Comment by SecondFlight** [comment]
This is not an issue, and the relevant code is 5 years old. If you're interested in that as a suggestion, the best thing to do would be to create an issue (assuming there isn't already one) and link it to this PR.

**Comment by tresf** [comment]
> the best thing to do would be to create an issue (assuming there isn't already one) and link it to this PR.

Preferably, just a PR. 😄

**Comment by musikBear** [comment]
@SecondFlight -you are correct its not an issue, it just has content as an issue, but it is marked 'closed', even though the discussed functionality never was implemented
The discussion here, around the functionality is really relevant, perhaps this post could simply be *changed* into an 'issue' ?

@tresf im unsure about what you mean with 'PR'

**Comment by SecondFlight** [comment]
> perhaps this post could simply be changed into an 'issue' ?
Unfortunately not possible on Github.

**Comment by tresf** [comment]
> @tresf im unsure about what you mean with 'PR'

PR = Pull Request.  Some changes are best done as a PR.  Tons of small issues clutter the tracker as can be observed by the > 600 bug reports open.

**Comment by musikBear** [comment]
@SecondFlight - Oh thats unfortunate 
@tresf - Ok understood!

**Comment by zonkmachine** [comment]
Forgot about this one. I'll look into again.

**Comment by zonkmachine** [comment]
Also, @teknopaul left us some song transport oriented code in one of the commits in the [groove PR](https://github.com/LMMS/lmms/pull/3296/commits/8e2f06baabdf024f3acfcd69ff11a4e72552ca9c).

**Pull request closed without merging**
