### PR TITLE
CMake: Try something different for making tests work

### PR DESCRIPTION
**Pull request by Lukas-W**

### CODE REVIEW

**Comment by Lukas-W** [comment]
So we get the same error on Windows as in #1612. @curlymorphic, any ideas?
```
Linking CXX shared module eq.dll

/opt/mingw64/bin/x86_64-w64-mingw32-ar cr CMakeFiles/eq.dir/objects.a @CMakeFiles/eq.dir/objects1.rsp

/opt/mingw64/bin/x86_64-w64-mingw32-g++ -shared -o eq.dll -Wl,--major-image-version,0,--minor-image-version,0 -Wl,--whole-archive CMakeFiles/eq.dir/objects.a -Wl,--no-whole-archive -L/home/travis/build/LMMS/lmms/build -L/home/travis/build/LMMS/lmms -lfftw3f -Wl,-Bstatic -lQtGui4 -lQtXml4 -lQtCore4 -Wl,-Bdynamic ../../src/liblmms.dll.a -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32

CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj):EqEffect.cpp:(.text+0x3e62): undefined reference to `__imp__Z7absspecPA2_fPfi'
CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj):EqEffect.cpp:(.text+0x3eb9): undefined reference to `__imp__Z13compressbandsPfS_iiii'
CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj):EqEffect.cpp:(.text+0x3ec8): undefined reference to `__imp__Z7maximumPfj'
CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj):EqEffect.cpp:(.text+0x3f54): undefined reference to `__imp__Z7absspecPA2_fPfi'
CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj):EqEffect.cpp:(.text+0x3fb5): undefined reference to `__imp__Z13compressbandsPfS_iiii'
CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj):EqEffect.cpp:(.text+0x3fc4): undefined reference to `__imp__Z7maximumPfj'

/opt/mingw64/lib/gcc/x86_64-w64-mingw32/4.8.5/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/eq.dir/objects.a(EqEffect.cpp.obj): bad reloc address 0x0 in section `.data'

collect2: error: ld returned 1 exit status
```

**Comment by tresf** [comment]
That `-j4` is messing with my brain. :)  Took me a while to find it on the Travis site... 

Is this line correct:

**Comment by tresf** [comment]
That `-j4` is messing with my brain. :)  Took me a while to find it on the Travis site... 

Is this line correct?

```
/opt/mingw64/lib/gcc/x86_64-w64-mingw32/4.8.5/../../../../x86_64-w64-mingw32/bin/ld
```

Looks wrong.  Seems like too many `../`'s

**Comment by tresf** [comment]
> Looks wrong. Seems like too many ../'s

I'm wrong it's correct.

**Comment by tresf** [comment]
The internet says this:

> You have to link the lib file using g++ ... -llibraryName.

... but I don't know what it means... 

And then this one:

> When searching how to compile with static libs, I found one mailer who added
> QMAKE_LFLAGS= -static
> which I did, and which gave problems as described.
> Another page on the web gave a more precise detailing of what to do, which
> is essentially set
> CONFIG += static

But I simply don't know enough about CMake to point out if that information is useful or not :coffee: 

https://github.com/LMMS/lmms/blob/master/plugins/Eq/CMakeLists.txt

**Comment by curlymorphic** [comment]
Looks to me like it's not linking the fft lib, but it is the same fft lib as the "spectrum analyser" uses. Im going to have a look now.

@Lukas-W have you deleted your branch.?
I was going to fork it to try and work out why the eq breaks your work.

**Comment by Lukas-W** [comment]
I deleted the old branch from #1612, if that's what you're trying to do.

**Comment by curlymorphic** [comment]
Sorry my bad. Was looking on your fork, didn't realize it was a branch :(.

Will have to look at this tomorrow now. but It must be something i have done, because the fft libs link ok elsewhere.

**Comment by tresf** [comment]
@curlymorphic shot in the dark but is it perhaps the newline character in your last line of CMakeLists.txt?

**Comment by tresf** [comment]
... also, you have a lot more imports... Namely `MainWindow.cpp` is specified in [`EqEffect.cpp`](https://github.com/LMMS/lmms/blob/master/plugins/Eq/EqEffect.cpp)  Is that needed?

**Comment by Lukas-W** [comment]
I don't think it's the fft libs… `absspec`, `compressbands` and `maximum` are functions in `src/core/fft_helpers.h`.

**Comment by Lukas-W** [comment]
#1626 is working now, closing this one.

**Comment by curlymorphic** [comment]
@Lukas-W was it my code at fault?

**Comment by Lukas-W** [comment]
@curlymorphic I don't think so, at least could I not find anything wrong with your code.

**Pull request closed without merging**
