### PR TITLE
lv2 support

### PR DESCRIPTION
**Pull request by alex-tee**
opening PR here for review/comments
temporarily setting target to stable-1.2 so that file diff can easily be viewed, once done will set target to master
work in progress

### CODE REVIEW

**Comment by tresf** [comment]
> Is it our intent to bake LV2 support in as part of the core or as a plugin?

We discussed this on Discord and the initial reaction is "yes", so I'm leaving the conditional build logic out for now.

I found a few plugins missing `Plugin::Embed`.  There may be more, but now my build is failing at the following:

```
/home/ubuntu/Desktop/lmms/src/core/Lv2Manager.cpp: In constructor ‘Lv2Manager::Lv2Manager()’:
/home/ubuntu/Desktop/lmms/src/core/Lv2Manager.cpp:80:21: error: ‘SUIL_ARG_NONE’ was not declared in this scope
  suil_init(0, NULL, SUIL_ARG_NONE);
                     ^
/home/ubuntu/Desktop/lmms/src/core/Lv2Manager.cpp:80:34: error: ‘suil_init’ was not declared in this scope
  suil_init(0, NULL, SUIL_ARG_NONE);
                                  ^
make[2]: *** [src/CMakeFiles/lmmsobjs.dir/core/Lv2Manager.cpp.o] Error 1
```

**Comment by tresf** [comment]
Ok, turns out that neither Ubuntu 14.04 nor 16.04 provide a suitable version of `suil-0`.  `suil_init` was introduced with 0.8.7.  Ubuntu 16.04 ships with 0.8.2.

**Comment by PhysSong** [comment]
@JohannesLorenz Should we keep this open? I think this one is not needed once #4899 is merged, but some changes in this PR may still be useful.

**Comment by JohannesLorenz** [comment]
@PhysSong Agreed, this branch won't be merged to master, but can be useful. I'm fine with either keeping open or closing.

**Comment by alex-tee** [comment]
fwiw here's my lv2 implementation for zrythm for additional info/reference:
https://github.com/zrythm/zrythm/blob/master/src/plugins/lv2_plugin.c

**Comment by JohannesLorenz** [comment]
Closed as it's currently in the "open PRs for stable-1.2" list, which must be cleaned up. I added this to the "Add Lv2 support" project so it's "bookmarked".

**Pull request closed without merging**
