### PR TITLE
Fix regression in handling RPATH for RemoteZynAddSubFx

### PR DESCRIPTION
**Pull request by jasp00**
This fixes the issue @midi-pascal has in #2748.

### CODE REVIEW

**Comment by midi-pascal** [comment]
@jasp00 :+1: :beers: :cake: :heart:  I **_knew_** there was a proper way to handle this. The _make_ step works _**but**_...
now it is ``make install`` that triggers the issue. :cry:

**Comment by jasp00** [comment]
@midi-pascal, I cannot reproduce it with `make install`. Is it the same error?
`/usr/bin/ld: warning: libicui18n.so.53, needed by /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5.4.2, not found (try using -rpath or -rpath-link)`

**Comment by jasp00** [comment]
Your installed version of lmms (the main application) is compiled with Qt 5.4, but at runtime it uses Qt 5.2.

**Comment by midi-pascal** [comment]
@jasp00 Yes, same message when doing ``make install``:
``/usr/bin/ld: warning: libicui18n.so.53, needed by /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5.4.2, not found (try using -rpath or -rpath-link)``
``/usr/bin/ld: warning: libicuuc.so.53, needed by /opt/Qt/5.4/gcc_64/lib/libQt5Core.so.5.4.2, not found (try using -rpath or -rpath-link)``

**Comment by jasp00** [comment]
@midi-pascal, could you configure with `-DCMAKE_VERBOSE_MAKEFILE=ON`? You will see the linking command with a `-Wl,-rpath,` argument at the end. What is this argument?

**Comment by midi-pascal** [comment]
@jasp00 Here is the faulty link command (only when doing ``make install``).
Strange enough there is no reference to zyn* ...
``CMakeFiles/lmmsobjs.dir/lmmsobjs_automoc.cpp.o  -o CMakeFiles/CMakeRelink.dir/lmms -rdynamic -lpthread /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Core.so.5.4.2 /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Gui.so.5.4.2 /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Widgets.so.5.4.2 /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Xml.so.5.4.2 -lasound -lSDL -lpthread -lportaudio -lasound -lm -lpthread -lpulse -ljack -logg -lvorbis -lvorbisfile -lvorbisenc -lsamplerate -lsndfile -lasound -lSDL -lportaudio -lasound -lm -lpthread -lpulse -ljack -logg -lvorbis -lvorbisfile -lvorbisenc -lsamplerate -lsndfile /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Gui.so.5.4.2 /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Core.so.5.4.2`` 
``/usr/bin/ld: warning: libicui18n.so.53, needed by /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Core.so.5.4.2, not found (try using -rpath or -rpath-link)``
``/usr/bin/ld: warning: libicuuc.so.53, needed by /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Core.so.5.4.2, not found (try using -rpath or -rpath-link)``

**Comment by jasp00** [comment]
@midi-pascal, the errors are because of RPATH handling. RemoteZynAddSubFx was ready, but the main application was not. With this new patch, `make install` should work.

**Comment by midi-pascal** [comment]
@jasp00 :tada: I can build and install Lmms/Qt5 again! This is **THE** fix. :heart: 
Being at it, I have also Qt 5.5.1 installed. Should I give it a try? :smiling_imp:

**Comment by jasp00** [comment]
@midi-pascal
> Should I give it a try?

Go ahead.

**Comment by midi-pascal** [comment]
@jasp00 Lmms builds, installs _AND_ works properly with Q5.5.1. :+1:

**Comment by midi-pascal** [comment]
@jasp00 Could you merge this _wonderful_ fix?

**Comment by jasp00** [comment]
@midi-pascal, there are some problems with the automated Qt5 build (#2780). As soon as those are fixed and the build for this pull request is done, I will merge.

**Comment by midi-pascal** [comment]
@jasp00 Yes! :100:

**Pull request merged**
