### PR TITLE
makes Tracks themable / adds 1 px Space between tracks

### PR DESCRIPTION
**Pull request by BaraMGB**
Something went wrong in https://github.com/LMMS/lmms/pull/2885 , I think.
Next try. 
@Umcaruje I updated the colors in the style.css. Looks now like this:

trackcolorflat

### CODE REVIEW

**Comment by Umcaruje** [comment]
Looks a lot better :+1:

**Comment by BaraMGB** [comment]
I have to prove the classic theme with this changes in code right now.

**Comment by BaraMGB** [comment]
@Umcaruje Okay, had to think a lot about this. But now it works like a charm also with the classic theme. 

----------------

@RebeccaDeField wrote here : https://github.com/LMMS/lmms/issues/2867#issuecomment-230111970
> Make some color tweaks and took out the borders in GIMP. What do you think about something like this? >The active and hover colors might also need some work if we change up the colors.
> 5d9a9400-403c-11e6-9ff0-512c70040824

@RebeccaDeField lets talk about the colors here in the pull request. In my opinion with this lighter colors and same color on track label button it looks much cleaner and contrasted. 
trackcolorflat

**Comment by Umcaruje** [comment]
I agree with @BaraMGB. The seamless tracks look great to me.

**Comment by RebeccaDeField** [comment]
Somehow missed this PR. The seamless idea with border on hover looks great to me as well!

Can we change the bg to #3B424A and the track border (on hover) to something like #515B66??

The pressed color isn't looking quite right, but I the issue is happening with the buttons too so I might open another issue for it so that I don't mix up the conversation here.

**Comment by BaraMGB** [comment]
Update:

flatgrey

**Comment by WinLin97** [comment]
Hi all,

This skin is very, very cool, but...

The idea is to allow setting the default size of tracks and that did not have to diminish and zoom all. Default size of tracks is for me too big.
przechwycenie obrazu ekranu_2016-07-07_15-38-09

Best regards :)

**Comment by Umcaruje** [comment]
@BaraMGB can we merge this?

**Comment by BaraMGB** [comment]
I reduced it to few lines in the style.css. Now it can be merged.

**Comment by Umcaruje** [comment]
@BaraMGB you removed the code changes? Why?

**Comment by BaraMGB** [comment]
Because it works without, too. We can't add a border but we won't a border and that was my intention with the code changes. At next I noticed a different behavior on resize the track with shift + click. It looks not bad but different.

**Comment by Umcaruje** [comment]
Ok then, merging.

**Pull request merged**
