### PR TITLE
Fix some problems with knob labels

### PR DESCRIPTION
**Pull request by dj-pixus**
This PR addresses some of the stuff in #5817, making tooltips a bit more consistent. Also made the Crossover Eq controls translatable.
It's just a quick aesthetic change which shouldn't conflict with the reorganization.

### CODE REVIEW

**Comment by qnebra** [comment]
For me its fine. Only some text changes, few typos fixed. Nothing technical was touched from what I see.

**Review by IanCaio — APPROVED** [review]
Code style ignored on review. Changes LGTM!

**Comment by superpaik** [comment]
EQ: A question: why IN and OUT gain faders in EQ are labeled **dBv** and gain faders in filters are **dB**? Is there a reason for that?
Flanger: Delay has the label "Delay time" without space before "s" (0.XXs) but Rate has space (0.XX s)

Suggestion: since you are checking knobs labels in general, the instrument's envelop knobs (in volume, cutoff, resonance) doesn't have a unit. I don't know if its always the same unit for every instrument and can be added to the label? Maybe you can check that out.
imatge

**Comment by dj-pixus** [comment]
> EQ: A question: why IN and OUT gain faders in EQ are labeled **dBv** and gain faders in filters are **dB**? Is there a reason for that?

Don't know what the original concept was, but **dBv** is certainly not the right unit here. It is used on analog gear to specify the voltage of a signal, which is uninterpretable in a digital environment.
Apparently these faders use normal **dB** values, so I'm going to change them to **dB** like it is everywhere else in the program.

Some weird thing about spaces: `setHintText( tr( "Delay time:" ) + " ", " s" )`
Looks like the leading space in `" s"` gets trimmed here, but in other places there is no space written in the quotes, but the final displayed string still contains one. So I guess the space is somehow part of the value itself(?) But it's not consistent.

The envelope parameters:
This is where my brain gave up. It appears to be some really weird exponential-like scale. `0.5` is 1.25 second, `1.0 is` 5 seconds, `2.0` is 20 seconds. It doesn't look like any regular function. Also, they seem to be adjusting the slope rather than the time, because the sustain knob also affects the decay time with the slope remaining the same.

**Comment by superpaik** [comment]
I agree with you on de dB dBv matter.
As for the delay, maybe the correct code should be delayKnob->setHintText( tr( "Delay time:" ) + , " s" ) with the space next to the s, as it is in the rest of the code.
And about the envelope parameters, now I see why it was so difficult to use ¿? Let's see if someone else can shed some light on the matter, if not let it be as it is.

**Comment by Veratil** [comment]
Hey @dj-pixus if you could rebase and update to the current style conventions we can work on getting this merged. :)

**Comment by dj-pixus** [comment]
Rebased in #6651, closing this one.

**Pull request closed without merging**
