### PR TITLE
Switch to libsamplerate's callback API in `Sample`

### PR DESCRIPTION
**Pull request by sakertooth**
This PR switches the use of libsamplerate in `Sample` to the callback API instead of the full API. This PR is great for many reasons:

1. Massive simplification of the audio processing in `Sample`. The `Sample::advance` function was removed as well as the heap allocation in `Sample::play`.
2. Since the heap allocation in `Sample::play` was removed, `Sample::play` should be more safe to call in real-time.
3. Don't know if anybody can notice this, but in current master, it sounds like some high frequency content in the playback was not being added compared to this PR. Using a `marginSize` of `64` fixed this in current master, but I wanted to try and improve this code further.

Other changes:
* I also added some fixes here and there (e.g., libsamplerate takes in the resampling ratio as a `double`, but it was originally being passed in as a `float`).
* I removed `AudioResampler` since it was no longer being used by anything, and it does not seem like a good idea for libsamplerate's usage in the codebase to be limited by the API of `AudioResampler`. The code should be allowed to choose which API from libsamplerate it wants to use. 
* `s_interpolationMargins` is only used by `GigInstrument` currently, so I moved the array in there.

### CODE REVIEW

**Comment by sakertooth** [comment]
Forgot to apply amplification, fixing that now.

**Comment by Rossmaxx** [comment]
> Since the heap allocation in Sample::play was removed, Sample::play is now safe to call in a real-time.

Does this got anything to do with the crashes I experience on #5990? Looks like it.

**Comment by sakertooth** [comment]
> Does this got anything to do with the crashes I experience on https://github.com/LMMS/lmms/pull/5990? Looks like it.

I don't think so. 5990 uses `SampleRecordHandle`'s, which do not involve calling `Sample::play`. This is for processing samples and is used in the AFP, Patman, sample tracks, etc.

**Review by messmerd — APPROVED** [review]
I tested it and it seems to work pretty well

**Pull request merged**
