### PR TITLE
ModernNoir Theme For The New Default

### PR DESCRIPTION
**Pull request by RebeccaDeField**
In this pull request, I am proposing that we use the ModernNoir theme as the new `default`, and the previous theme as a `classic` option as many people have suggested.

**Modern Noir As Default**
shot-2016-05-30_00-36-20

**Previous Design As Classic**
shot-2016-05-29_21-27-40

Please note: this is my version of the Modern Noir theme. This version will be added to the LSP. If this were to be the new default, I am not at all opposed to anyone making changes that do not match the style of my original preview, as there will always be a version available on the LSP. I am also doing this so that I can upload a version for the older release.

**A little history**
This theme started [here](https://github.com/LMMS/lmms/issues/880#issuecomment-192983120), where many people stated that they were interested in having this as an alternate theme option. Development for the theme continued on my fork [here](https://github.com/HDDigitizerMusic/lmms-alt-theme/issues). @tresf posted [this](https://github.com/LMMS/lmms/issues/2587), opening up the discussion for this theme to become the default. We came to the consensus that many people wanted me to move the theme into a pull request, hence the PR that I am posting here.

I would like to thank everyone for their support, feedback and contributions! :smile:

### CODE REVIEW

**Comment by liushuyu** [comment]
@RebeccaDeField Looks like your first PR (~~in your life~~) is pretty professional :+1: 
If there is no objections, we will merge this ASAP.

Thx

**Comment by liushuyu** [comment]
@RebeccaDeField Thanks for you valiant contributions!

**Comment by RebeccaDeField** [comment]
You are very welcome! I am honored to have my work as the default. I would also like to give special thanks to @HDDigitizerMusic for bringing me into this in the first place and working along side me, @Umcaruje for all of his contributions (especially with the hard coding), @IvanMaldonado for his contribution on the piano, @tresf, @BaraMGB, @michaelgregorius and all of the others that have made contributions, given feedback and helped to make this a reality!

**Comment by BaraMGB** [comment]
@RebeccaDeField that's a very clean and good looking theme! Thanks for the hard work on it. Can you tell me which font you use for the LFO label?
bildschirmfoto von 2016-05-31 11-58-46

**Comment by Umcaruje** [comment]
@liushuyu I'm sorry, but this Pull Request was merged way too soon. 
>No immediate objections, will merge shortly.

You merged it in around an hour, I live in a different timezone and I was unable to object. I don't get the need to merge stuff quickly. The general rule is to always wait at least 24 hours so a PR can properly get tested. 

There are many issues that need to be adressed here.

The theme has left some things very inconsistent in the overall look of the software.

For example, the LB302 instrument looks really bad now, because of lack of proper background on the waveform selectors:
screenshot from 2016-05-31 12 07 12

Same with Vibed: 
screenshot from 2016-05-31 12 13 01

Since the scrollbars now have a different height/width, there are uninitalised areas in the plugins (I'll fix this in a PR probably):
screenshot from 2016-05-31 12 08 13 
and the Piano roll/Automation editor scrollbars look weird, because they are too wide: 
screenshot from 2016-05-31 12 13 39

The LFO controller is the only plugin that was redesigned, and that left the peak controller looking very inconsistent: 
screenshot from 2016-05-31 12 11 26

There may be some other issues I overlooked, but the point is this PR should've had proper testing before merging. I know we are all excited about the new theme, as we all worked hard on it, but rushing at the end was not the way to go.

**Comment by BaraMGB** [comment]
@Umcaruje if @RebeccaDeField has no time for, I would like adjust the peak controller design. In my opinion it should look similar to the LFO controller in appearance and (!) size. Actually I work on this, yet. I have to know the font. I think it is Spaceport2006. there could be a license issue. That we have to prove. If I'm right, fonts have to be under a free license for lmms, isn't it? 

Regards

**Comment by Umcaruje** [comment]
@BaraMGB I think it might be [Orbitron](https://www.fontsquirrel.com/fonts/Orbitron)
screenshot from 2016-05-31 12 58 02

**Comment by BaraMGB** [comment]
👍 @Umcaruje

**Comment by tresf** [comment]
Well, that happened quickly.  I agree with @Umcaruje when a merge has so many affected files (in this case, 488), we need to be a bit more careful when we merge.  That's OK though, we'll make due.

My biggest concern is that I thought we had agreed to **not** keep around the classic theme.

Well anyway, @Umcaruje approves all theme merges from here on out please.

**Comment by RebeccaDeField** [comment]
I was also surprised by how quickly this was merged, but I think we can still collaborate to test and update the theme where needed.

@tresf perhaps we should leave the classic option for now, so that we can make up for the fast merge? I think that usually people test PRs so leaving the other theme for now could give a bit of a buffer.

@BaraMGB Yes, Orbitron was the font I used. It is under the Open Font License.

I noticed that all of the plugins had a unique look and so I assumed that it was important to you guys that it stayed that way. With that in mind, I tried to design the knobs in a way that they would look transparent but still be visible in the other parts of the program. Now I see that people would like it to look more consistent, which I prefer myself.

@Umcaruje You mentioned [here](https://github.com/LMMS/lmms/issues/2770#issuecomment-220005870) that there was a simpler way to re-theme all of the plugins. Maybe we could implement that on all of the plugins for more consistency?

On the subject of the scroll bars, I think we have two options. We can either restore them to the same size as the previous ones and update the radius to match, or we can update the size in the Automation editor and just create matching graphics for the plugins with the new size in mind. Either way works for me.

I can also give the waveform selectors a dark background to add more contrast.

Right now might be a good time to add my source files to the repository so that other people can use them if they want contribute to this. I tried to layout my files in a way that would be easy to use for that reason.

**Comment by Umcaruje** [comment]
>@Umcaruje You mentioned here that there was a simpler way to re-theme all of the plugins. Maybe we could implement that on all of the plugins for more consistency?

No, that is just if you want to change up the plugins on a seperate theme. For the default we edit the artwork files directly, since that is easier. The method I mentioned may be used by a theme designer such as yourself to quickly test out the new look of the plugin you're working on, without recompiling.

>On the subject of the scroll bars, I think we have two options. We can either restore them to the same size as the previous ones and update the radius to match, or we can update the size in the Automation editor and just create matching graphics for the plugins with the new size in mind. Either way works for me.

I'm already working on reducing the size, but I really think the handlebar would benefit from a 1px margin, since when applied to the plugin window it just looks too near the piano:
screenshot from 2016-05-31 20 26 06
I'll try to finish up the PR soon.

>Right now might be a good time to add my source files to the repository so that other people can use them if they want contribute to this. I tried to layout my files in a way that would be easy to use for that reason.

You need to fork https://github.com/LMMS/artwork and just add files to the `src` dir, and make a PR just like you did here :)

>I noticed that all of the plugins had a unique look and so I assumed that it was important to you guys that it stayed that way. With that in mind, I tried to design the knobs in a way that they would look transparent but still be visible in the other parts of the program. Now I see that people would like it to look more consistent, which I prefer myself.

Well I'd like for the instrument plugins to stay the same, but for the effect plugins I think we should have a consistent redesign.

***
P.S. @RebeccaDeField you might wanna consider joining our gitter chat (https://gitter.im/LMMS/lmms) to have another way of communication and to discuss the theme stuff.

**Comment by RebeccaDeField** [comment]
> No, that is just if you want to change up the plugins on a separate theme.
Ah, looks like I didn't understand the comment perfectly, thanks for clearing that up.

> Well I'd like for the instrument plugins to stay the same, but for the effect plugins I think we should have a consistent redesign.

> You need to fork https://github.com/LMMS/artwork and just add files to the src dir, and make a PR just like you did here :)

Will do.

> Well I'd like for the instrument plugins to stay the same, but for the effect plugins I think we should have a consistent redesign.

Okay, sounds good. I'll make a pull request with the updated waveform selectors. It looks like @BaraMGB is taking on the Peak Controller. Can someone make a list of the plugins that we want to redesign to match?

> P.S. @RebeccaDeField you might wanna consider joining our gitter chat.
Thanks for the invite! I'll try to join in if I can, but I'm pretty busy right now so chat might not work for me as I'm commenting here when I can find time to spare here or there.

**Comment by IvanMaldonado** [comment]
> Can someone make a list of the plugins that we want to redesign to match?

Basically, all of these.

plugins

And I personally think these should be redesigned as well, to match the modern look of Rebecca's work.

synths

**Comment by BaraMGB** [comment]
That are a lot of plugins for redesign. Perhaps we should specify something like a design convention.

**Comment by BaraMGB** [comment]
@RebeccaDeField Can I please you to create a background image for the peak controller? The size is 240x100 and it should look like this:

peak_controller_artwork

I don't get the label looking like yours.

**Comment by mikobuntu** [comment]
I agree and especially as I am the author of the Carla plug-in artwork, I did this in a hurry, but would be willing to update this to keep in tune with the new default theme.

On 1 Jun 2016 08:10, BaraMGB <notifications@github.com> wrote:That are a lot of plugins for redesign. Perhaps we should specify something like a design convention.

**Comment by RebeccaDeField** [comment]
> Can I please you to create a background image for the peak controller?

Of course :) I think have an idea of what went wrong. Will reply with more details and graphics later today.

**Comment by RebeccaDeField** [comment]
Looking at how many effects plugins that people want redesigned, I think that it would be a good idea to create a separate issue for the plugins where I can outline some good standard that people can follow to create plugins that match the rest of the theme and we can collaborate to get it done. What do you guys think?

**Comment by Umcaruje** [comment]
>Looking at how many effects plugins that people want redesigned, I think that it would be a good idea to create a separate issue for the plugins where I can outline some good standard that people can follow to create plugins that match the rest of the theme and we can collaborate to get it done. What do you guys think?

Yes, please that'd be really nice and helpful

**Pull request merged**
