### PR TITLE
MIDI import/export: map note volume and MIDI velocity with their full range

### LINKED ISSUE #4761: Export MIDI - Note velocity
Our note velocity go from 0 - 200 but midi note velocity is 0 - 127. In our export code we set anything over 127 to 127 so a track using the full range in lmms will export wrong.

https://github.com/LMMS/lmms/blob/7f0593c601a7f48fda193139f2d6bb3d76f10384/plugins/MidiExport/MidiExport.cpp#L277

Example issue reported in the forum: https://lmms.io/forum/viewtopic.php?f=7&t=29497

Can we just divide note velocity in two when exporting?
Example, crude but working:
```cpp
mnote.volume = qMin(qRound(base_volume * 0.635 * LocaleHelper::toDouble(note.attribute("vol", "100"))), 127);
```
@PhysSong

### PR DESCRIPTION
**Pull request by PhysSong**
Fixes #4761.

### CODE REVIEW

**Comment by zonkmachine** [comment]
I'm going to just go ahead and merge.

**Comment by jasp00** [comment]
According to MIDI 1.0 specification, which might be this [one](https://people.carleton.edu/~jellinge/m108f13/pages/00Reference/MIDIspecification.pdf), velocity is not strictly defined, but it should follow a logarithmic scale. I guess velocity = 64 should mean 100% in LMMS.

**Comment by zonkmachine** [comment]
> velocity is not strictly defined

Correct. It's basically just info about how fast a key is struck.



> I guess velocity = 64 should mean 100% in LMMS.

And it is. (had to double check...)

**Comment by jasp00** [comment]
Sure, 100% is 64. I was suggesting to consider a logarithmic scale instead of a linear one.

**Comment by jasp00** [comment]
Should we use the algorithm from our favorite free MIDI player?

**Pull request merged**
