### PR TITLE
slope2 parameter

### PR DESCRIPTION
**Pull request by dnl-music**
calcSlope2 is not called anywhere.

### CODE REVIEW

**Comment by dnl-music** [comment]
Monstro ENV2 slope parameter

**Comment by diizy** [comment]
Mmmyeah no, not so sure about this... I have a feeling function pointers will prevent the compiler from inlining the functions. 

Probably a better way is to consolidate the functions to one and add a parameter.

Also, we don't use this->, which is redundant in C++... please read our coding style guidelines... https://github.com/LMMS/lmms/wiki

**Comment by dnl-music** [comment]
13.01.2015 22:21, Vesa V пишет:
> Also, we don't use this->, which is redundant in C++... please read 
> our coding style guidelines... https://github.com/LMMS/lmms/wiki
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/LMMS/lmms/pull/1619#issuecomment-69771274>.
>
Hmm... I know only one way to call a method of class through a pointer 
in other method of class. And (*calcSlopes[]()) without this-> is 
compile error.And, unless the function call function no more expensive 
than just a function call?

**Comment by diizy** [comment]
On 01/13/2015 07:34 PM, dnl-music wrote:
> 13.01.2015 22:21, Vesa V пишет:
> > Also, we don't use this->, which is redundant in C++... please read
> > our coding style guidelines... https://github.com/LMMS/lmms/wiki
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/LMMS/lmms/pull/1619#issuecomment-69771274>.
> >
> Hmm... I know only one way to call a method of class through a pointer
> in other method of class. And (*calcSlopes[]()) without this-> is
> compile error.And, unless the function call function no more expensive
> than just a function call?

Yeah, I'm saying don't use function pointers. Instead, add a parameter
to the inline function, like this:

inline sample_t calcSlope( int slope, sample_t s );

Then you can call it like:

s = calcSlope( 1, s );
s = calcSlope( 2, s );

**Comment by dnl-music** [comment]
14.01.2015 02:13, Vesa V пишет:
> On 01/13/2015 07:34 PM, dnl-music wrote:
> > 13.01.2015 22:21, Vesa V пишет:
> > > Also, we don't use this->, which is redundant in C++... please read
> > > our coding style guidelines... https://github.com/LMMS/lmms/wiki
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/LMMS/lmms/pull/1619#issuecomment-69771274>.
> > >
> > Hmm... I know only one way to call a method of class through a pointer
> > in other method of class. And (*calcSlopes[]()) without this-> is
> > compile error.And, unless the function call function no more expensive
> > than just a function call?
>
> Yeah, I'm saying don't use function pointers. Instead, add a parameter
> to the inline function, like this:
>
> inline sample_t calcSlope( int slope, sample_t s );
>
> Then you can call it like:
>
> s = calcSlope( 1, s );
> s = calcSlope( 2, s );
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/LMMS/lmms/pull/1619#issuecomment-69811300>.
>
Oh yes, it is much easier:-)

**Comment by diizy** [comment]
this was merged in another pr

**Pull request closed without merging**
