### PR TITLE
Use the Trusty beta build environment

### PR DESCRIPTION
**Pull request by jasp00**
The builds for Linux/Qt5 are failing with:
`E: Unable to locate package qtbase5-dev`
I propose to use Trusty in this environment.

### CODE REVIEW

**Comment by jasp00** [comment]
The `libsoundio-dev` dependency is dropped because it comes from @andrewrk's PPA, but it is only in Precise, not in Trusty.

**Comment by jasp00** [comment]
The builds are fixed.

**Comment by tresf** [comment]
My opinion.... we go all the way and bite the bullet.

From what I'm observing, the Ubuntu dev team silently pulled Precise from the PPA we previously used for Qt5.

The readme still mentions 12.04:

```
== Earlier Ubuntu versions ==

Ubuntu 12.04 LTS has older versions of packages offered in this PPA, but the SDK support has moved to the newer releases. It's however usable for example for general Qt 5 usage.
```

However, it's not available for selection in the drop down, suggesting they finally dropped support for it.

If this is the case, we should move away from 14.04 completely.  There's little benefit in staying with a 4-year old release and if there are packages that aren't available, we make them available.

For example, you've disabled `libsoundio-dev` for Trusty, but it may be wiser to ping @andrewrk and see if he'll help with a 14.04 release.

**Comment by jasp00** [comment]
With this new patch, all remaining builds use Trusty. The `libsoundio-dev` dependency is restored.

**Comment by Umcaruje** [comment]
LGTM :+1:

**Comment by tresf** [comment]
@jasp00 much appreciated.  Next, I think we can remove the double `cmake mingw` invocations as AFAIK it was a bug with the older cmake versions.

**Pull request merged**
