### PR TITLE
Restore metalish_dong01.ogg's quality (closes #2733)

### LINKED ISSUE #2733: Restore metalish_dong01.ogg's quality
The file pulled in #2392 has less quality; the original is stereo. I will send a version where the data is copied rather than re-encoded. It was created with:
`ffmpeg -i old/metalish_dong01.ogg -acodec copy new/metalish_dong01.ogg`

### PR DESCRIPTION
**Pull request by jasp00**
This is the version mentioned at #2733.

### CODE REVIEW

**Comment by tresf** [comment]
@M374LX can you test this please?  You sent us the last one which is clearly quieter, but this one almost sounds a bit distorted at the beginning (perhaps intentional).

**Comment by zonkmachine** [comment]
The proposed sample has a similar glitch as snare04.ogg in #2594

**Comment by tresf** [comment]
@zonkmachine thanks, thought so.  Didn't have a wave editor at the time of posting.  Let's fix this once and for all.  We need'n garbage in our samples.  A quieter sample is better than a distorted one.

**Comment by jasp00** [comment]
I see some distortion at the beginning of the right channel.

> A quieter sample is better than a distorted one.

Then the current mono sample is OK?

**Comment by tresf** [comment]
> Then the current mono sample is OK?

Use #2594 as a reference point and please fix the sample. @zonkmachine feel free to just do this for @jasp00.  I'd rather not spend any more time on this bug report.

**Comment by jasp00** [comment]
I have replaced the distorted part with the left channel and re-encoded with quality 6.

**Comment by zonkmachine** [comment]
Looks and tests fine. I restarted one of the Travis tests that failed (Travis bad probably) and will merge when it's done.

**Pull request merged**
