### PR TITLE
Updated Freeboy files from Game Music Emu 0.6.1. (#3618)

### LINKED ISSUE #326: Glitchy Sound in FreeBoy
Something is wrong with FreeBoy's sound when played under Linux version of LMMS.  It makes a glitchy/static like sound when played.

I played the same notes with the same FreeBoy settings on both the Linux and Windows version of LMMS.

Linux: http://streams19.tunescoop.com/266702_IncorrectFreeboySound_stream.m4a
Windows: http://streams19.tunescoop.com/266703_CorrectFreeboySound_stream.m4a
- This issue also occurs in  Linux version of LMMS 0.4.15

### PR DESCRIPTION
**Pull request by zonkmachine**
Uses upstream files to fix #326

[oskar.wallgren13@gmail.com: backported from master]

### CODE REVIEW

**Comment by tresf** [comment]
@zonkmachine did you try a `git cherry-pick` first?  If there are no conflicts, this should be able to be directly applied to `stable-1.2` without a PR at all.

**Comment by PhysSong** [comment]
@zonkmachine I think this PR is not needed. Many devs agreed that this backporting is needed.
I also think `git cherry-pick` would be better.

**Comment by zonkmachine** [comment]
This is a `cherry-pick` to a branch off stable-1.2. You mean I should cherry-pick directly onto stable-1.2 and just push?

**Comment by PhysSong** [comment]
@zonkmachine Yes. I think that will be better.

**Comment by zonkmachine** [comment]
I pushed to stable-1.2 directly ... which caused this PR to be merged.

**Pull request merged**
