### PR TITLE
Making clearer the hierarchy.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by JohannesLorenz** [comment]
Stylistic and functional OK, but the destructor should also be marked override. If this is not done, I get clang warnings in QtCreator.

**Comment by JohannesLorenz** [comment]
Review passed again. :smile:  Do you want to merge or add more commits?

**Comment by Reflexe** [comment]
@JohannesLorenz I think we can merge it?

**Comment by JohannesLorenz** [comment]
I wasn't sure if more commits were going to be added (there are a lot more classes missing `override`). Now after 3 weeks... Time to merge.

**Pull request merged**
