### PR TITLE
Fix MIDI export

### LINKED ISSUE #2384: MIDI export doesn't handle B&B tracks correctly
Every B&B pattern in the project is placed in the resulting MIDI file in sequence, with a new pattern starting on each bar.

This may be better explained in pictures. A song like this:

kuvakaappaus 2015-09-27 21 05 39

gets exported as if it was like this:

kuvakaappaus 2015-09-27 21 07 26

(cc @mohamed--abdel-maksoud)

### PR DESCRIPTION
**Pull request by PhysSong**
Fixes #2384.
Zero-length note support needs some work, per #2074. See https://github.com/LMMS/lmms/issues/2074#issuecomment-315944761.
Also `MidiFile.hpp` needs correct copyright information. See https://github.com/LMMS/lmms/issues/2384#issuecomment-313872420.

### CODE REVIEW

**Comment by zonkmachine** [comment]
Wonderful!

Issues:
An exported track opens in MusE transposed down 2 octaves. The demo project c3.mmp has one note, c3. It will export as midi note 36 (c3.mid) which, by the most adopted standard, translates to c1. c3 should probably export as note 60. The c3 in c3.mmp seem to be the correct pitch ~130Hz.

[c3.mmp.zip](https://github.com/LMMS/lmms/files/1185016/c3.mmp.zip) [c3.mid.zip](https://github.com/LMMS/lmms/files/1185017/c3.mid.zip)

http://computermusicresource.com/midikeys.html
Related: https://github.com/LMMS/lmms/issues/1857

**Comment by PhysSong** [comment]
https://github.com/LMMS/lmms/issues/1857#issuecomment-318872278

Another issue of this PR: actually master pitch is ignored now. I'll put master pitch support if needed.

**Comment by zonkmachine** [comment]
> Possible (temporary) fix: add 12 to every note pitch.

:+1: 

> Another issue of this PR: actually master pitch is ignored now. I'll put master pitch support if needed.

Yes. I think master pitch needs to go in there.

**Comment by zonkmachine** [comment]
I tried automation of master pitch. Maybe this isn't intended to work yet but here goes...

Automation of master pitch: [midimasterpitch.mmp.zip](https://github.com/LMMS/lmms/files/1187363/midimasterpitch.mmp.zip)
Note pitch comes out with the same pitch modulation as is presently when you press export MIDI.
To reproduce. Play and pause at random positions. Right click on master pitch fader and read off the value `copy value(..)`. Export MIDI...
Expected: modulated from original C4 over a larger range, same result every time and not depending of start position.

**Comment by PhysSong** [comment]
Yes. Processing automation is difficult, so current method(based on previous one) only exports notes.
I'll try to include these automations or merge it without master pitch support.

**Comment by zonkmachine** [comment]
> or merge it without master pitch support.

Maybe that's a good idea actually. The basic functions are there and midi export works.

**Comment by PhysSong** [comment]
I need to change some things: 
* Instrument pitch should be exported as a MIDI CC.
* It is not clear whether MIDI export should transpose notes according to base notes, or not.
* MidiFile.hpp doesn't support MIDI CC. In order to export automation patterns, I should modify this file a lot, or add some more functions.
* Moreover, exporting automation patterns is complicated and difficult. For complete MIDI export, such things must be implemented.

So there's two choices about automation:
1. Merge this PR without automation support and implement it later.
2. Postpone merging until full automation support is implemented.

**Comment by zonkmachine** [comment]
> 1. Merge this PR without automation support and implement it later.

I vote this. With later here meaning in `master`.

**Comment by Umcaruje** [comment]
>Merge this PR without automation support and implement it later.

I vote on this too, midi automation can happen when we expose the midi CC messages in the instruments #1159 (part of #1472)

>It is not clear whether MIDI export should transpose notes according to base notes, or not.

That's a tricky one, I usually use the base note to tune the actual instrument, but I also sometimes use it to actually shift an instrument a couple of octaves up or down, so I don't really know about this, we could do it as an option, but midi export doesn't have any dialog so far.

**Comment by PhysSong** [comment]
I'm trying to implement automation export. If it is finished before rc4 is released, I'll merge this PR with automation support.
If not, this PR should be merged without automation support.
>I vote this. With 'later' here meaning in `master`.
It should be. However, MIDI export without automation support will be buggy for some projects.
When it have been tested enough and works well, we can(and should, in my opinion) backport it later.

**Comment by PhysSong** [comment]
>>It is not clear whether MIDI export should transpose notes according to base notes, or not.

>That's a tricky one

`InstrumentTrack::processOutEvent()` applies both base note and master pitch. According to this, I think the answer should be "yes".

I want to remove MidiFile.hpp from this project and write a new class for this purpose. That file doesn't support MIDI CC and have some bugs. I want to implement a better exporting plug-in :)
If the schedule matters, I'll instrument pitch support and merge it.

**Comment by zonkmachine** [comment]
> I want to remove MidiFile.hpp from this project and write a new class for this purpose. That file doesn't support MIDI CC and have some bugs. I want to implement a better exporting plug-in :)
> If the schedule matters, I'll instrument pitch support and merge it.

I think you should solve this the simplest possible way and leave rewrites to a later release.

**Comment by PhysSong** [comment]
Do I need to update README.md in this PR?

**Comment by tresf** [comment]
> Do I need to update README.md in this PR?

Good catch.  Sure.

**Comment by PhysSong** [comment]
Is there anything to do?

**Comment by difarem** [comment]
Besides automation, a way to choose the exported instrument for each track would be really useful. It could be selected below the master pitch toggle.

**Comment by PhysSong** [comment]
It will be a good feature, but won't be in this PR because it is a fix for broken MIDI export, not a enhancement. Furthermore, it will be merged into `stable-1.2`, which is on a feature freeze now.

However it can be done in `master` later.

**Comment by zonkmachine** [comment]
> Is there anything to do?

I think it's good enough to merge.

Just one observation when exporting shorties/Crunk(Demo).
You may want to take a look at the note length of the last beat note in a pattern. It gets a length of one whole measure. It would probably make more sense to have them cut off at the end of the measure.

Tracks `Kick 01` and `Clap 04` (Imported intor MusE) extends to measure 9.

crunklmms

**Comment by PhysSong** [comment]
Yes. I will take a look at it and fix it soon.

**Comment by PhysSong** [comment]
Yes. I will take a look at it and fix it soon.

**Comment by PhysSong** [comment]
This is the only thing left for rc4 now. I will fix the issue above and merge it tomorrow. No objection?

**Comment by zonkmachine** [comment]
> This is the only thing left for rc4 now. I will fix the issue above and merge it tomorrow. No objection?

No objection.

There was also the issue with [recording single stream instruments](https://github.com/LMMS/lmms/pull/3774#issuecomment-325090531).

**Comment by PhysSong** [comment]
As a simple workaround, I'm considering cutting notes at the end of last BBTCO, or something similar.

**Comment by zonkmachine** [comment]
> As a simple workaround, I'm considering cutting notes at the end of last BBTCO, or something similar.

I'm not that bothered by it. I think we can ship RC4 without a fix for this. MIDI export is a complex function and there will be a bunch of things that needs to be fixed anyway.

**Comment by zonkmachine** [comment]
> I'm considering cutting notes at the end of last BBTCO

... Sounds like a good idea.  :+1:

**Comment by PhysSong** [comment]
>there will be a bunch of things that needs to be fixed anyway.

Yes, maybe. Anyway, cutting notes at the end of last BBTCO or whole song will be much better. More things should be done in `master` and can be backported whenever needed.

**Comment by PhysSong** [comment]
May I merge it tomorrow?

**Comment by zonkmachine** [comment]
If you are happy with the last commit I think you should just go ahead and merge it now.

**Comment by regulus79** [comment]
Was exporting/importing MIDI to multiple tracks working when this PR was merged? Currently, if you have multiple midi clips on different tracks, when you export and import it, they are collapsed down to a single track.

**Pull request merged**
