### PR TITLE
Add mixer dB markers

### PR DESCRIPTION
**Pull request by sakertooth**
This PR adds dB markers for mixer channels. This is especially useful when leveling mixes, and is generally useful when you want to simply estimate at what dB a fader is peaking at.

**Screenshot**
image

### CODE REVIEW

**Comment by sakertooth** [comment]
Just seeing the meta issue for this: It seems like there's a lot more work to be done here.

For one, the mixer needs to move in logarithms, not linearly. The faders should also point to the top, as 0 dbFS is the ceiling for the audio signal.

**Comment by superpaik** [comment]
I totally agree that the scale should by logarithmic, it would be more useful. As for the top, it depens as how the internal signal is managed, but I in other DAWs it goes up to +6dB too.

**Comment by actuallyexeon** [comment]
I think it would be better if it was slimmer on the sides

**Comment by sakertooth** [comment]
Closing due to #7295.

**Pull request closed without merging**
