### PR TITLE
MDI Subwindow Decoration for VeSTige instruments closes #2824

### LINKED ISSUE #2824: VST plugin MDI subwindow uses default qt styling
Version `1.1.90-gdaedb92 (Linux/x86_64, Qt 4.8.6, GCC 4.8.4)`, Elementary os Freya x64
screenshot from 2016-06-05 22 42 13
VST instrument windows seem to ignore the custom MDI Subwindow styling. 

Tagging @BaraMGB

### PR DESCRIPTION
**Pull request by BaraMGB**
Can't test this. I fight with the `RemotePluginClient::shmget:` bug. 
Can someone test this please?

Regards

### CODE REVIEW

**Comment by Umcaruje** [comment]
Nope, still is there: 
screenshot from 2016-06-06 16 57 19

**Comment by liushuyu** [comment]
@BaraRGB Small hint: You forgot to change something in vestige.cpp

**Comment by tresf** [comment]
> @BaraMGB Small hint: You forgot to change something in vestige.cpp

Right, using the `SubWindow` class isn't the same as inheriting it.  See https://github.com/LMMS/lmms/issues/2824#issuecomment-223851314.

**Comment by liushuyu** [comment]
@BaraMGB Take a look at here: https://github.com/LMMS/lmms/blob/master/plugins/vst_base/VstPlugin.cpp#L57

**Comment by BaraMGB** [comment]
Yes, I have a working branch, yet. There are some graphic glitches. But no time to fix it.

**Comment by BaraMGB** [comment]
Okay, updated for now. But I have graphic glitches, yet. It seems, the title bar label background isn't repaint when the window changed active state. @liushuyu any guesses? 
vstsubwindowglitches

**Comment by tresf** [comment]
@lukas-w @PhysSong is this PR superseded by newer efforts?

**Comment by lukas-w** [comment]
@tresf No, but I wouldn't merge it into `stable-1.2`. Using our own `MdiSubWindow` subclass could change the way Qt handles those widgets internally and may break embedding, so it should be tested on its own in `master`.

**Comment by JohannesLorenz** [comment]
Can we add the "in progress" label here?

**Comment by BaraMGB** [comment]
No. I close this PR. It's not the right approach to fix the issue, obviously.

**Comment by lukas-w** [comment]
> It's not the right approach to fix the issue

Why? I'd say this can be merged as-is.

**Comment by BaraMGB** [comment]
@lukas-w can you give me a tip how to merge this? I wanted to merge it local for testing, but the file VstPlugin.cpp has changed a lot in the last 3 Years. What is the trick?

**Comment by lukas-w** [comment]
@BaraMGB The `vstSubWin` class was moved to `vestige.cpp` in a2cb7e96ea057de604003ecdc70745a80e4b40e0. Since the changes of this PR are so small, the easiest would be to just manually apply them again on current `master`.

**Comment by BaraMGB** [comment]
@lukas-w Thank you for helping here. :+1:

**Pull request merged**
