### PR TITLE
Update Swedish Translation

### PR DESCRIPTION
**Pull request by Spekular**
This file is huge and I prefer English to Swedish, so there may be some issues, but I translated a whole lot of strings that had no translations before. There are still tons remaining. If anyone else speaks Swedish feel free to correct me/discuss better translations/add more translations. 
Some info:
Some Swedish words are just English words that we use anyways (input/output for example).
Some words I didn't bother to translate ("loopback", "backend"). They're not quite like the first point but should still be acceptable.
In Swedish, some words are literally just two words put together. Writing them as two words is a "särskrivning" (splitwriting/separatewriting?). So yes, those two words did become one and I did not miss a space.
Gain was translated to volume
Contributors was translated to developers
Sample was translated to soundfile
Knob was translated to "vred", which I'm not sure about. Apparently "ratt" can also be used.
Beat/Bassline got changed to Drums/Bass

### CODE REVIEW

**Comment by Sti2nd** [comment]
> Gain was translated to volume

Isn't there a difference there? Gain just means increase in something, and volume means gain related to sound somehow. http://www.offbeatband.com/2009/08/the-difference-between-gain-volume-level-and-loudness/

**Comment by tresf** [comment]
Thanks!  This should be safe to merge, but I'll allow some conversation first.

**Comment by Spekular** [comment]
@sti2nd Yes there is a difference. I think förstärkning is better actually, whoops. It's a bit hard to translate specific terms because I never learned them in Swedish. It's like talking about physics in spanish :P

**Comment by Spekular** [comment]
@sti2nd fixed. @tresf build failed on mac...

**Comment by Sti2nd** [comment]
Same here, I have tried translating VLC to Norwegian, there a lot of advanced words I know Norwegian don't even got... Norway has this Norwegian FTW policy, so in the Norwegian version of VLC you will find Norwegian words I and others just has invented... I don't know if the same is desired for Swedish :) It seems not, you are more like the Danish with all the English influences?

**Comment by Spekular** [comment]
@sti2nd I'm pretty sure there are some words that don't exist in Swedish too. I actually translated "automation editor" to "edit automations" to avoid making up new words. Some of the two-in-one words had probably never been combined before though. I don't feel too bad, since even professional programs' translations make me cringe. "Multi-level-list" is one single word in the the Swedish version of MS Word, thanks to our horrendous combination rules. I have no clue who thought combining words like that was a good idea.

Have you tried translating LMMS? I don't see a NO translation, so anything would help I guess.

**Comment by Sti2nd** [comment]
Nope, don't intend to translate it really... I guess I got tired with VLC, and another project, have translated a lot, but I don't feel I know enough audio terms to really translate a program in a good way. I have never used a real mixer table or talked with Norwegian musicians about that stuff so my translations are based off the internet mostly. Maaybe I will translate it, but I also think most people prefer English, so it would only be for children under 8 or something, and then they would still probably not understand the advanced musical terms even though they are in Norwegian, and then I feel they might as well learn those terms in English, lol.

**Comment by musikBear** [comment]
you are SO right
In danish we talk about 'läne-ord' Whitch loosly can be translated to 'borrowed-words' -and we use å for ä :)
Mostly we in the northern language area, has been 'borrowing' from english, but also french and a few german words has ..imigrated :p
Now heres a few 'perhaps'
in swedish
Contributors is medverkende
sample should not be translated, thats a låneord, but ljudfil *would* be better
A dial is a knap
editor is redigerings-verktüg, but **editor** is much better!
hence 'automation editor' becomes ... automatiserings-redigerings-verktüg
... and it is actually quite ok to write that as automatiseringsredigeringsverktüg
infact
A danish job-description could be
jernbanevognsskinneskidtskraberassistent
That is 100% **correct** danish ..believe it or not
Dont you just love us? :ice_cream: 

I have to say, that translation to tiny languages, -imo - Is somewhat of a mixed blessing. It can be more difficult to get help, in for instance a forum, if the software is in native language

**Comment by Spekular** [comment]
@musikBear oh, thanks! I'll definitely change "contributors" to
"medverkande".

**Comment by musikBear** [comment]
also change 'vred' to 'knap' - 'vred' is the kind of handle you have on a water-taps :P

**Comment by Spekular** [comment]
@musikBear vred is also what you use to set the heat on an oven, which I'd
say is similar enough to an audio hardware knob. Besides, knap is button.

**Comment by tresf** [comment]
@Spekular is this ready to merge?

**Comment by Spekular** [comment]
@tresf think so. I might give it one last look.

**Comment by tresf** [comment]
Might or will?  Please let us know when it is ready to be merged.

**Comment by Spekular** [comment]
@tres sorry, I meant I will. Forgot to do so today, will do it on Friday.

**Comment by Spekular** [comment]
@tresf I've looked through it, seems good. Should I remove the "untranslated" tags? What do I put instead?

**Comment by tresf** [comment]
> @tresf I've looked through it, seems good. Should I remove the "untranslated" tags? What do I put instead?

I don't know. Please use another translation file as a reference point.

**Comment by Spekular** [comment]
@tresf unless the build fails we're good to merge here.

**Comment by tresf** [comment]
Merged and added to 1.2-RC1 future release notes.  Thanks!!!

**Comment by badosu** [comment]
@tresf Where are these release note? Also, do we have a plan for rc1?

There are a *lot* of things that need to be addressed beforea a RC1 in my opinion.

**Comment by tresf** [comment]
> @tresf Where are these release notes? Also, do we have a plan for rc1?

They are hidden to administrators unfortunately so I can't share them public until the release is published (or use up a bug or wiki entry for them, which seems gross... )

Here's a copy of them as of today:

> **Features and fixes:**
  * FX Mixer
    * Added "Remove unused channels" feature
    * Added Mixer "solo" mode
  * New Instruments:
    * Gig Player -  Plays Giga Sample Banks (similar in usage to SoundFont files) ([screenshot](https://cloud.githubusercontent.com/assets/6345473/5733347/b13b671a-9b6f-11e4-8fa8-a1cedd6c35ee.png))
  * New FX Plugins
    * Equalizer plugin - A new native parametric graphic EQ effects plugin ([screenshot](https://cloud.githubusercontent.com/assets/6345473/5733272/a78012d0-9b6e-11e4-9989-e631cc64848d.png)
)
    * New Bitcrush effects plugin ([screenshot](https://cloud.githubusercontent.com/assets/6345473/5733291/102a59c6-9b6f-11e4-936c-4f95c645f1db.png))
    * New Crossover EQ plugin (can be used as a tonestack) ([screenshot](https://cloud.githubusercontent.com/assets/6345473/5733367/e3a59892-9b6f-11e4-8d2b-a008622fcd68.png))
  * Sample exact models/controllers
   * Supported by FX mixer, Instrument VOL knob, Amplifier FX plugin
   * Allows smooth sidechaining with peak controller
   * Allows AM modulation with LFO controller
  * Track Enhancements:
    * Add ability for instruments to ignore "master" pitch slider
    * Quick FX Mixer assignment from track context menu
    * Added Automation Track pattern "flip" (horizontal/vertical)
    * Better thumbnails/previews of Piano Roll patterns
  * UI Improvements
    * Range Select in Song Editor
    * Group copy/move in song editor
    * Better collection and displaying of startup errors (both GUI and CLI)
    * Better name handling for copied patterns
    * Allow the disabling of ".bak" files
    * Piano Roll `Alt+Left`/`Alt+Right` switches between Piano Roll patterns
    * Better incompatible theme detection (forces minor version check)
    * Recursive sample/preset/project searching in File Browser
  * Bug Fixes
    * "Code profiling" driven performance and bug fixes
    * Fix AudioFileProcessor redraw issues
    * Fix maximize/restore window behavior in Song Editor when opening track
    * Fix noise at end of some sample previews
    * Fixed position of "Factory Presets" file divider in file browser
    * Disable VST instrument previews (prevents crashes)
    * Fix several color/display/cursor/sizing issues
    * Moving play cursor changes beat/bar/ticks display
    * Fix Nescaline high-note crash
    * Fix exporting crash on some locales/languages
  * Languages/Locale
    * Improved Chinese translation
    * Added Swedish translation

---

> **Known issues with this release:**
 * Windows
  * Software fails to load on some systems (Please see bug #1173)
  * No sound/distorted sound on some systems (Forum topics [#604](https://lmms.io/forum/viewtopic.php?f=3&t=604) [#283](https://lmms.io/forum/viewtopic.php?f=3&t=283))
 * Apple
  * Runs on OS X 10.7 "Lion" and higher only (Please see bug #1270)
  * MIDI controllers do not work on Apple (Please see bug #1153)
  * VST plugins (`.dll`) do not work on Apple (Please see bug #698)
  * SoundFonts (`.sf2`) do not work on Apple (Please see bug #649)
  * Projects open to a blank project every time when opened from Finder or Desktop (Please see bug #665)
  * ZynAddSubFX "Show GUI" button does not work on Apple (Please see bug #703)

**Comment by tresf** [comment]
> Also, do we have a plan for rc1? There are a lot of things that need to be addressed beforea a RC1 in my opinion.

Well, we're falling short I feel on stable-1.1 in my opinion.  We have documented performance issues with the new mixer and we haven't been able to offer much in terms of that.

From a feature perspective, we could easily freeze 1.2 but the tremendous amount of GUI fixes you are Dave are taking on seems to warrant leaving it open for a bit longer.

In terms of how many things should be addressed prior to an RC1, that's really a classic Quality Control dilemma because having an RC out for longer can really help expose bugs but it can also introduce a bunch of false bug reports if we're testing a moving target.

My plan was to release RC1 when we're at a good lull point and the lingering FXMixer stuff I feel is a sign that we aren't ready yet.

**Comment by badosu** [comment]
I am not even talking about enhancements, but some bug fixes that I've not even filed yet (maybe I should :-).

**Pull request merged**
