### PR TITLE
Use Qt's Resource System (2nd approach)

### PR DESCRIPTION
**Pull request by Lukas-W**
This PR does pretty much the same as #1742, but takes a less invasive approach, touching much less code. In contrast to my first approach, `embed::getIconPixmap` stays (I removed it and replaced all calls in #1742), but uses Qt's resource system and `QDir`'s search paths internally.

~~Even though I didn't test it, it should now be~~ It's now possible to drop in SVGs instead of PNGs in themes without changing any code.

It's already been possible to replace any plugin's artwork by adding a file called something like e.g. `monstro_logo.png` to the theme folder. LMMS will then use that one instead of the plugin's built-in file. This PR changes this to `monstro/logo.png` instead (subdirectory vs underscore), just for the sake of easy implementation. I could not find any theme that replaces a plugin's artwork, so I hope this will have no impact on existing themes. Please let me know if I'm wrong and if there are such themes out there (on the LSP).

### CODE REVIEW

**Comment by Umcaruje** [comment]
>It's already been possible to replace any plugin's artwork by adding a file called something like e.g. monstro_logo.png to the theme folder. LMMS will then use that one instead of the plugin's built-in file. This PR changes this to monstro/logo.png instead (subdirectory vs underscore), just for the sake of easy implementation. I could not find any theme that replaces a plugin's artwork, so I hope this will have no impact on existing themes. Please let me know if I'm wrong and if there are such themes out there (on the LSP).

I think this won't be a problem, since theme compatibility is broken anyways (you can't use 1.1 themes on 1.2). This is a very useful feature and should be documented though. 

So if I want to change the logo and/or the artwork of a plugin, I just add an png of the thing I want replaced? e.g. `lb302/artwork.png` and `tripleoscillator/logo.png` ?

**Comment by softrabbit** [comment]
> Even though I didn't test it, it should _still_ be possible to drop in SVGs instead of PNGs in themes without changing any code.

FTFY.

**Comment by Lukas-W** [comment]
> So if I want to change the logo and/or the artwork of a plugin, I just add an png of the thing I want replaced? e.g. lb302/artwork.png and tripleoscillator/logo.png ?

Exactly. Note that I didn't test that one either.

> > Even though I didn't test it, it should still be possible to drop in SVGs instead of PNGs in themes without changing any code.
> 
> FTFY.

Nope, that didn't work before. We didn't have any code capable of loading SVGs. It's now possible by using `QImageReader` which supports SVGs (see 9175928232cb79bc2df72039179ed37d110c814b).

**Comment by Lukas-W** [comment]
@softrabbit Nevertheless, I'd be interested to know what you're referring to. Maybe I'm just missing something.

**Comment by softrabbit** [comment]
This: https://github.com/LMMS/lmms/pull/887 (OK, the explicit looping through possible file names was horrible, but I've loaded SVGs in LMMS for ages with that code...)

I'm guessing ```new QPixmap(filename)``` actually uses ```QImageReader``` behind the scenes. The documentation for QPixmap does hint at that in saying: 
>The complete list of supported file formats are available through the QImageReader::supportedImageFormats() and QImageWriter::supportedImageFormats() functions.

**Comment by Lukas-W** [comment]
Ah thanks for the clarification. :) I didn't know `QPixmap` can read SVGs (maybe only on some systems?), it didn't work for me and isn't listed in the docs.

**Comment by tresf** [comment]
@Lukas-W shall we shelve this for after the 1.2 release, or work to integrate it prior?

**Comment by Lukas-W** [comment]
Seeing that 1.2 already has a lot of changes, it'd probably be wiser to merge this PR after 1.2.

**Comment by jasp00** [comment]
Why not to remove the embedding altogether? Advantages:

* Runtime will be simpler.
* No recompilation because of artwork.
* Architecture-dependent size will be smaller, which is good for distros.

**Comment by Lukas-W** [comment]
Yeah, why not. When this PR is merged it's just a matter of removing the QRC logic and installing the resources via CMake instead. No need to touch any code IIRC.

**Comment by tresf** [comment]
> Why not to remove the embedding altogether? Advantages:

For lmms.exe? Sure.  For plugins?  I'd argue this could break portability and strongly advocate against it.

**Comment by jasp00** [comment]
>For plugins? I'd argue this could break portability

What do you mean? An external image can be loaded portably.

**Comment by tresf** [comment]
> An external image can be loaded portably.

It can, but it shouldn't.  If a developer were to make a new LMMS plugin and distribute the binary, he should no need to write special instructions for users to extract images e.g. `theme/foo/bar`.

**Comment by jasp00** [comment]
>If a developer were to make a new LMMS plugin and distribute the binary, he should not need to write special instructions for users to extract images

Are users not used to run installers or install packages? Anyway, if both methods are kept, official plug-ins still benefit from:

* No recompilation because of artwork.
* Architecture-dependent size will be smaller, which is good for distros.

**Comment by tresf** [comment]
> Are users not used to run installers or install packages?

Generally, no.  Commercial plugins do this, but it is not common for community plugins and just adds unnecessary burden to the distributor.  Good installers are a lot of work to get right cross-platform.

> official plug-ins still benefit from:  No recompilation because of artwork.

Sure, but if unofficial plugins eventually use our code for building, we should have embedding be the default behavior.  #3204.

https://github.com/PaulBatchelor/lmms-reverbsc is a good use-case for our discussion.

> Architecture-dependent size will be smaller, which is good for distros.

👍

**Comment by jasp00** [comment]
> it is not common for community plugins and just adds unnecessary burden to the distributor. Good installers are a lot of work to get right cross-platform.

Then let us use ZIP files for distribution, like the JAR, XPI, and OpenDocument cases. We can package Perl and Python plug-ins for LMMS, even multiple plug-ins sharing the artwork; just do not make the artwork to be part of the compilation. LMMS would be able to handle these ZIP files. The plug-in developer would run `make plugin-package`.

> if unofficial plugins eventually use our code for building, we should have embedding be the default behavior.

Why that default? Third-party developers would also benefit from avoiding recompilation and providing separated packages, acting as a minidistro. Of course, if we give both options, it does not matter what the default is.

**Comment by tresf** [comment]
>  We can package Perl and Python plug-ins for LMMS, even multiple plug-ins sharing the artwork; just do not make the artwork to be part of the compilation. 

When LMMS starts supporting non-compiled, scripted plugins, we can revisit this topic (assuming then the scripted plugins will adopt some common GUI framework).  A gigantic part of our user base (> 1M downloads / year) is Windows and Windows doesn't yet ship with Perl or Python (Windows 10 may [eventually change this](http://www.zdnet.com/article/ubuntu-and-bash-arrive-on-windows-10/)).

> Then let us use ZIP files for distribution, like the JAR, XPI, and OpenDocument cases.

Sure, but how about we start with project files first. :)

**Comment by tresf** [comment]
> Why that default? Third-party developers would also benefit from avoiding recompilation and providing separated packages, acting as a minidistro.

Because project shouldn't prioritize ease of building over ease of distribution.  Without distribution, there's no point in building.  If recompilation is really such a problem, have the plugin look for artwork in a folder and override what's embedded.  Isn't that what we do now anyway?

**Comment by Lukas-W** [comment]
> Isn't that what we do now anyway?

It is.

**Comment by jasp00** [comment]
>Because a project shouldn't prioritize ease of building over ease of distribution.

Is distributing a ZIP file harder than distributing a DLL?

> have the plugin look for artwork in a folder and override what's embedded. Isn't that what we do now anyway?

For official stuff, yes; for external plug-ins, not as easily as I am suggesting. We look at specific folders for resources (by the way, `getIconPixmap()` definition should not be part of a plug-in). This means a binary without embedding currently needs an installation instead of simply moving the distributed file, the latter being the case of a binary with embedding.

**Comment by tresf** [comment]
> Is distributing a ZIP file harder than distributing a DLL?

It depends on how much hand-holding we do, really.  We currently have this problem with our theme files.  LMMS has no easy way to import them, so they need to be carefully created by the distributor and carefully installed by the end user.

Project files are really the worst offenders though.  We use zlib compression, but don't actually compress anything that looks like a bundled project file structure.

The only other disadvantage is going to be load times.  If we compress every single plugin we bundle into a LMMS-specific type, it will increase the time to load LMMS (which may be a fair trade-off).  I just don't want to warn strongly against developer-designed software decisions.  There must be a middle ground between what keep end-users using a product and what keeps developers and distributions contributing.

**Comment by jasp00** [comment]
Third-party resources (plug-ins, themes, samples in projects) share the same problem, we can use ZIP archives to bundle them.

>If we compress every single plugin we bundle into a LMMS-specific type

Just to be sure, official plug-ins would not be compressed; third-party plug-ins would be distributed compressed, but would be automatically uncompressed and cached.

As an alternative, would it be fine if the user double-clicks the bundle to install it? That would be equivalent to `lmms --import-addon myplugin.mmadd`.

**Comment by tresf** [comment]
> As an alternative, would it be fine if the user double-clicks the bundle to install it? That would be equivalent to lmms --import-addon myplugin.mmadd.

File association is great although again we need to prioritize the basics first (see #665) and we also need to be careful how we deploy as that assumes we either 1. Have write-access to system space -- OR - 2. Can safely write to user-defined space.

We'd also want to have an easy way to let the plugins get moved around.  Currently, one can backup the user's LMMS home directory and place it on another computer and most all works (observing natural architecture limitations of course).

**Comment by jasp00** [comment]
>We'd also want to have an easy way to let the plugins get moved around.

Then it is uncompress and cache.

**Comment by tresf** [comment]
> Then it is uncompress and cache.

In that case, I would call this uncompressed and **installed**.

**Comment by tresf** [comment]
My point in all of this is:  Don't [throw the baby out with the bath water](https://en.wikipedia.org/wiki/Don't_throw_the_baby_out_with_the_bathwater).  Switching resource systems now can help cleanup #3203.

On the contrary...  Making a drastic change such as remove all embedded resources from all of our executables assumes there's no good in doing so and `.so` and `.dll` portability is a near zero-effort benefit of having it the way it is.  The bundled plugin designs mentioned above is possible after substantial amounts of work.

**Comment by jasp00** [comment]
We would not remove the embedding method until a better alternative is developed.

>Making a drastic change such as remove all embedded resources from all of our executables assumes there's no good in keeping it the way it is today.

What are the good points for embedding in official binaries? My suggestion is to keep both options, to embed or not to embed, which could be overridden per plug-in. If embedding is done, it should happen on install rather than on build.

**Comment by tresf** [comment]
> What are the good points for embedding in official binaries? 

None.

**Comment by Umcaruje** [comment]
@Lukas-W now that we have diverged `stable-1.2` from `master`, do you want to resolve the merge conflicts so we test and merge this?

**Comment by Lukas-W** [comment]
> do you want to resolve the merge conflicts so we test and merge this?

Already at it right now 😉

**Comment by Lukas-W** [comment]
Done.

**Comment by Umcaruje** [comment]
So I tested this out, LMMS functions as expected, no visual artifacts of any sort.

I did find a bug with the plugin artwork replacement feature though. If the plugin has an underscore in its folder name, the artwork won't get replaced.
I had 4 folders for 4 plugins with a replacement `artwork.png` (or in monstro's case `artwork_op.png` and `artwork_mat.png`):
screenshot from 2017-03-26 19 24 31
Only plugins without an underscore get their artwork replaced:
screenshot from 2017-03-26 19 24 16

**Comment by Lukas-W** [comment]
Thanks for testing. 

> If the plugin has an underscore in its folder name, the artwork won't get replaced.

That's just a mismatch between the directory names in `plugins` and the actual plugin name. You have to match the plugin name, so it's `tripleoscillator` instead of `triple_oscillator`.
You can find the correct name in lines similar to `BUILD_PLUGIN(tripleoscillator …)` in the respective `CMakeLists.txt` or in the resulting library file (`libtripleoscillator.so` or `tripleoscillator.dll`).

So I guess this is good to merge?

**Comment by Umcaruje** [comment]
>That's just a mismatch between the directory names in plugins and the actual plugin name. You have to match the plugin name, so it's tripleoscillator instead of triple_oscillator.

Thanks, that's good to know.

>So I guess this is good to merge?

LGTM :+1: I can't comment on the code though, not quite versed in cmake.

**Comment by Lukas-W** [comment]
> I can't comment on the code though

It's been two years and no one's complained about the code :) Merging

**Pull request merged**
