### PR TITLE
Updated splash screen

### PR DESCRIPTION
**Pull request by RebeccaDeField**
Updated the splash screen to match the current logo/branding/website that @Umcaruje worked on.

**Old**
splash

**New**
splash

It's been a while since I've used git or github so if I've done this incorrectly just let me know. I removed the alpha layer but the splash still needs to be reviewed to make sure we don't encounter the same issue here #4062.

### CODE REVIEW

**Comment by PhysSong** [comment]
I confirmed that the image doesn't have an alpha channel. :+1:

**Comment by RebeccaDeField** [comment]
@PhysSong So is this good to merge, then?

**Comment by PhysSong** [comment]
I can't comment on the design itself, so I think it's fine to merge if you think it's okay.

**Comment by zonkmachine** [comment]
With this splash.png I get `libpng warning: iCCP: CRC error` on startup.
I'm on LinuxMint/libpng12.

**Comment by PhysSong** [comment]
Same here with Ubuntu 18.04/`libpng16`.

**Comment by zonkmachine** [comment]
$ pngcheck ../data/themes/default/splash.png 
../data/themes/default/splash.png  CRC error in chunk iCCP (computed a0032057, expected a4b05ab4)

**Comment by PhysSong** [comment]
Possibly related: https://gitlab.gnome.org/GNOME/gimp/issues/2111
If I manually change the checksum in the image file using hex editor, the bug is gone.
Here's the image file with the checksum fixed:
splash
I can commit the change now.

**Comment by PhysSong** [comment]
@RebeccaDeField If you used GIMP to export this image, could you try unchecking `Save Color Profile` on export?

**Comment by RebeccaDeField** [comment]
@PhysSong Yes. Is there a way for you to test this against the file you produced to make sure this is solving the problem? 

splash

**Comment by PhysSong** [comment]
> @PhysSong Yes. Is there a way for you to test this against the file you produced to make sure this is solving the problem?

I checked this file with both `pngcheck` and GIMP, and it looks fine. The error message is also gone. :tada:

**Pull request merged**
