### PR TITLE
CMake: Change the way tests links lmms

### PR DESCRIPTION
**Pull request by Lukas-W**
Trying this out, hoping it doesn't break the Windows build

### CODE REVIEW

**Comment by Lukas-W** [comment]
Oh crap, that feature is CMake 2.8.8+ only, Travis has 2.8.7…

**Comment by badosu** [comment]
@Lukas-W Looks like this will not happen [very soon](https://github.com/travis-ci/travis-ci/issues/2030)

**Comment by Lukas-W** [comment]
So either I find a different way for solving this (most probably Linux only then), or we install a newer CMake version in Travis from some PPA (see https://gist.github.com/winterz/10cc2741d466cbd8ff21). This means breaking compatibility with Ubuntu 12.04's standard repositories though.

**Comment by badosu** [comment]
@Lukas-W It looks fine to me to use the PPA.

**Comment by Lukas-W** [comment]
Yeah to me too. Nevertheless I'll try a different solution first, in the meanwhile I'd like @tresf to share his opinion about this.

**Comment by Lukas-W** [comment]
New try is #1628

**Comment by tresf** [comment]
>  This means breaking compatibility with Ubuntu 12.04's standard repositories though.

Well, that PPA should be in addition to the standard repositories, much like Toby's.  If the backport gives us testing ability with no other harm done, it is a win/win IMO.

We'll have to make mental note (or file a bug for the future) to take the custom PPA back out when we switch to 14.04 in the future.

**Comment by tresf** [comment]
OK... I finally figured out why you were asking... This breaks Windows builds on all 12.04 machines moving forward unless the custom PPA is installed.  That's OK with me so as long as our documentation reflects that.

**Comment by Lukas-W** [comment]
Not quite, this breaks *all* builds on 12.04 unless the custom PPA is used.

**Comment by badosu** [comment]
Well, since this is a problem with the `cmake` version I don't see any problem on simply changing the `INSTALL` file.

**Comment by tresf** [comment]
> Not quite, this breaks all builds on 12.04 unless the custom PPA is used.

Hmm... yeah that's a tough sell.  We need to move forward, but at what expense... 

Probably a better question is what other distros have stable OSs that are equally as far behind and do they offer an equivalent to the back-port ppa method. This would have to include MacPorts too (although they tend to be pretty up to date on packages).

For example, if the majority of other distros in our Linux list won't break with this custom PPA it may be a non-issue and 12.04 becomes our edge case.

-Tres

**Comment by badosu** [comment]
> For example, if the majority of other distros in our Linux list won't break with this custom PPA it may be a non-issue and 12.04 becomes our edge case.

### Arch

```
~ ❯❯❯ pacman -Ss cmake
extra/cmake 3.1.0-2 [installed]
    A cross-platform open-source make system
```

**Comment by tresf** [comment]
image

**Comment by eagles051387** [comment]
You dont need to take out the ppa. The upgrade mechanism automatically
disables ppa's and any 3rd party repositories.

On Wed, Jan 14, 2015 at 8:39 PM, Tres Finocchiaro <notifications@github.com>
wrote:

> This means breaking compatibility with Ubuntu 12.04's standard
> repositories though.
>
> Well, that PPA should be in addition to the standard repositories, much
> like Toby's. If the backport gives us testing ability with no other harm
> done, it is a win/win IMO.
>
> We'll have to make mental note (or file a bug for the future) to take the
> custom PPA back out when we switch to 14.04 in the future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/pull/1626#issuecomment-69977505>.
>



-- 
Jonathan Aquilina

**Comment by tresf** [comment]
> You dont need to take out the ppa. The upgrade mechanism automatically disables ppa's and any 3rd party repositories. 

What does that have to do with our conversation?

**Comment by badosu** [comment]
@tresf I guess it's with our own comment:

> We'll have to make mental note (or file a bug for the future) to take the custom PPA back out when we travis switches to 14.04.

**Comment by tresf** [comment]
> We'll have to make mental note (or file a bug for the future) to take the custom PPA back out when we travis switches to 14.04.

Yes, but our Travis script has nothing to do with an Ubuntu desktop upgrade.  @eagles051387 is just trolling.

**Comment by badosu** [comment]
> Yes, but our Travis script has nothing to do with an Ubuntu desktop upgrade. @eagles051387 is just trolling.

@tresf I don't know, maybe we just got confused and forgot that Travis provides a new VM everytime.

**Comment by Lukas-W** [comment]
I forgot I could just check for the CMake version and disable tests for <2.8.8. Trying that out now.

**Comment by eagles051387** [comment]
No im not I have upgraded a few ubuntu servers myself and even ubuntu
server does it as well.

On Thu, Jan 15, 2015 at 3:45 PM, Tres Finocchiaro <notifications@github.com>
wrote:

> We'll have to make mental note (or file a bug for the future) to take the
> custom PPA back out when we travis switches to 14.04.
>
> Yes, but our Travis script has nothing to do with an Ubuntu desktop
> upgrade. @eagles051387 <https://github.com/eagles051387> is just trolling.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/pull/1626#issuecomment-70095060>.
>



-- 
Jonathan Aquilina

**Comment by badosu** [comment]
@eagles051387 I guess what @tresf meant is that Travis *never* upgrades distros in the same way as we are discussing. The reason is that boxes are provided with the OS preinstalled.

So when Travis upgrades the OS version it means just that the default box has changed and that we should remove the PPA usage as it is reinstalled everytime a build occurs.

**Comment by Lukas-W** [comment]
Looks like it worked :)

**Comment by badosu** [comment]
@Lukas-W Amazing, thanks!

Gonna take a look at on how to add tests on the new features I develop now.

**Comment by tresf** [comment]
> So when Travis upgrades the OS version it means just that the default box has changed and that we should remove the PPA usage as it is reinstalled everytime a build occurs.

Right.  Johnathon read PPA and he thought he could add something.  Instead he should be fixing Mac bugs.  :deciduous_tree:

**Comment by badosu** [comment]
@tresf Chill out a bit, dude. That was just a confusion.

**Comment by Lukas-W** [comment]
> That was just a confusion.

I wish it was.

**Comment by badosu** [comment]
Ok, so let me just stop posting here, I really don't understand what's going on. My only concern is about discussions related to this PR.

**Comment by tresf** [comment]
> Ok, so let me just stop posting here, I really don't understand what's going on. My only concern is about discussions related to this PR.

Yeah, this is the wrong place for these conversations and I'd apologize for the lack of professionalism, but I also have children, and sometimes you have to let them know they are doing something wrong immediately after the action, despite the interruption in dialog it creates.

In the case of @eagles051387, he has continuously chimed in with out of context help and he really needs to work on what he has committed to years ago rather than chiming in on topics he knows nothing about.

Analogy:

He said he'd mow the lawn.  He was thinking about mowing the lawn but took interest in watering the flowers because he saw us watering the plants and it looked like something he was interested in.  Oh... but the plants have already been watered.  Ok, now the plants are dead and the lawn looks like a forest.

There's no doubt in my mind that Jonathan has value to add to this project, I'm just not sure where or when that will happen.  Apple file associations would be a tremendous start. :heart: 

-Tres

**Pull request merged**
