### PR TITLE
Backport dual filter exactness

### LINKED ISSUE #1919: Dual Filter frequency automation does not work
When I try to connect frequency knob to either MIDI or user controller to get wobble effect, it results constant frequency. But I can hear the wobble when moving knob with mouse. Connecting to controller doesn't work with any of the effects in dual filter.

### PR DESCRIPTION
**Pull request by badosu**
@curlymorphic @tresf Better done than said :-)

See the [commits list](https://github.com/LMMS/lmms/pull/1923/commits) to verify that everything's ok.

@curlymorphic let me know if I missed anything or if the backport is not a good idea.

Fixes #1919 on 1.1.x

### CODE REVIEW

**Comment by badosu** [comment]
It's not clear to me why the build is failing. :`-(

**Comment by tresf** [comment]
Since Lukas enabled CPU optimizations, the Travis build errors are often much further up the log... https://travis-ci.org/LMMS/lmms/jobs/57210514#L5672

```
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp: In member function ‘virtual bool DualFilterEffect::processAudioBuffer(sample_t (*)[2], fpp_t)’:
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:106:2: error: ‘ValueBuffer’ was not declared in this scope
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:106:15: error: ‘cut1Buffer’ was not declared in this scope
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:106:53: error: ‘class FloatModel’ has no member named ‘valueBuffer’
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:107:15: error: ‘res1Buffer’ was not declared in this scope
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:107:53: error: ‘class FloatModel’ has no member named ‘valueBuffer’
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:108:15: error: ‘gain1Buffer’ was not declared in this scope
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:108:55: error: ‘class FloatModel’ has no member named ‘valueBuffer’
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:109:15: error: ‘cut2Buffer’ was not declared in this scope
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:109:53: error: ‘class FloatModel’ has no member named ‘valueBuffer’
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:110:15: error: ‘res2Buffer’ was not declared in this scope
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:110:53: error: ‘class FloatModel’ has no member named ‘valueBuffer’
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:111:15: error: ‘gain2Buffer’ was not declared in this scope
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:111:55: error: ‘class FloatModel’ has no member named ‘valueBuffer’
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:112:15: error: ‘mixBuffer’ was not declared in this scope
/home/travis/build/LMMS/lmms/plugins/DualFilter/DualFilter.cpp:112:51: error: ‘class FloatModel’ has no member named ‘valueBuffer’
```

**Comment by badosu** [comment]
No, it's my fault. I forgot to pull an additional commit as I thought the changes were isolated on the DualFilter file.

Gonna fix this.

If this is too complicated it may not be worth it.

**Comment by tresf** [comment]
You'd know better then me, but ValueBuffer is from MemoryManager, which isn't in stable-1.1, so it will likely be a separate commit altogether to fix this.  Cherry-picking may not be a good idea here.

**Comment by badosu** [comment]
@tresf Investigating, it seems that df9d495571902cb739cecc8f37f5b8cd35366bda refactored it. Gonna see if it's a trivial patch or not.

**Pull request closed without merging**
