### PR TITLE
Save track height under a separate name, 'trackheight'

### PR DESCRIPTION
**Pull request by zonkmachine**
Temporary fix for https://github.com/LMMS/lmms/issues/3721.

### CODE REVIEW

**Comment by zonkmachine** [comment]
@PhysSong Merge?

**Comment by PhysSong** [comment]
It should work without compatibility problem, but I want to know how @michaelgregorius thinks.

**Comment by michaelgregorius** [comment]
So if I understand correctly then files stored with this patch will differentiate between `trackheight` which stores the height of the track as shown in the Song Editor and `height` which stores the height of the instrument window. Therefore loading and saving of such new files will work without the two classes interfering with each other. If an old file is loaded the new attribute `trackheight` will not be found and in these cases the tracks will be restored to their default height. Is this correct? If that's the case then the patch looks good to me.

@zonkmachine, @PhysSong: Thanks for working on this issue!

**Comment by zonkmachine** [comment]
>Is this correct?

Correct. I've tested this and it fixes the issue. Merge?

**Comment by michaelgregorius** [comment]
@zonkmachine I'd say let's merge this.

**Comment by zonkmachine** [comment]
:tractor:

**Pull request merged**
