### PR TITLE
Proposed fix 1643 Allow drag-and-drop of project files

### LINKED ISSUE #1643: PianoRoll Shift+Insert/Shift+Delete Shortcut
would be intuitive if sh+ins / del, worked exactly as in song-editor, eg simply moved all notes right of playhead.
Distance should be current note-lenght
The functionality should be independent of selections

### PR DESCRIPTION
**Pull request by curlymorphic**
Proposed fix #1643 Allow drag-and-drop of project files

### CODE REVIEW

**Comment by tresf** [comment]
Looks good.  Thanks for implementing this!

I assume this inherently checks that the project hasn't been modified same as the double-click behavior.  Merging.

**Comment by Lukas-W** [comment]
> I assume this inherently checks that the project hasn't been modified

It looks like it doesn't.

**Comment by tresf** [comment]
@curlymorphic can you shim in a project modification check?  This way the drag-and-drop doesn't bypass the "Do you want to save settings" dialog. :+1:

**Comment by tresf** [comment]
P.S. @Lukas-W thanks for checking.

**Comment by curlymorphic** [comment]
> @curlymorphic can you shim in a project modification check? This way the drag-and-drop doesn't bypass the "Do you want to save settings" dialog.

yes. I am taking a look now.

**Comment by Lukas-W** [comment]
@curlymorphic You'll probably want to use [`bool MainWindow::mayChangeProject();`](https://github.com/LMMS/lmms/blob/master/include/MainWindow.h#L75)

**Comment by curlymorphic** [comment]
> You'll probably want to use bool MainWindow::mayChangeProject();

:) has taken a few for me to work out its not static so needs an instance, but seems to be working now. Just testing it now.

**Pull request merged**
