### PR TITLE
added the function randsv to Xpressive

### PR DESCRIPTION
**Pull request by gnudles**
that function let you choose the random seed thus allowing persistent vector upon note plays and upon waveforms transit in the gui.

### CODE REVIEW

**Comment by tresf** [comment]
Before merging this, @ArashPartow can you help us decide which commit to use for our submodule?  We can no longer find https://github.com/ArashPartow/exprtk/commit/aad301a6ebbab769620b0bb0e77713c4659117a6.

**Comment by ArashPartow** [comment]
@tresf  Would it be possible to instead of using a particular revision of exprtk module to always use the tip of the master?

**Comment by tresf** [comment]
@ArashPartow thanks kindly for chiming in with a reply.  This is probably a better place than #4077 for this discussion so I'll paste my reply here again.

In our build system, we could coerce this, but no, git submodules do not directly permit this.  Is there a particular reason why the history was erased?  This is generally uncommon for a master branch and it also leaves a bit of ambiguity as to what occurred for a particular update.

Worse, it takes reliable builds completely out of our hands as we wouldn't know if a breaking change existed until after our build system broke.  It's not something I would encourage or want.

For now, our code pulls from [my fork](https://github.com/LMMS/lmms/commit/9547575c502b46857272018d768eae6234a6edd2) which has the history restored .  This fork is only around until we understand if there's a viable and reliable way to use a submodule against upstream.  👍

**Comment by tresf** [comment]
@gnudles now that Travis is fixed there seem to be some code fixes in store, here's one of the errors from Travis-CI:

```
In file included from /home/travis/build/LMMS/lmms/plugins/Xpressive/Xpressive.h:38:0,
                 from /home/travis/build/LMMS/lmms/plugins/Xpressive/Xpressive.cpp:25:
/home/travis/build/LMMS/lmms/plugins/Xpressive/ExprSynth.h:56:45: error: ‘numeric_limits’ was not declared in this scope
```

**Comment by ArashPartow** [comment]
@tresf  with regards to the above numeric_limits issue, look like all that is required is to add `#include <limits>` in the ExprSynth.h header.

**Comment by tresf** [comment]
@ArashPartow done and done.  @gnudles sorry, had to fast-forward your branch, you'll have to wind it back a few commits `git reset --hard HEAD~3` and then `git pull`.

**Comment by tresf** [comment]
Build still failing due to `numeric_limits`.  I'll defer to @gnudles I'd rather leave the coding to him, I'm better off sticking to the build environment. :)

```
/home/travis/build/LMMS/lmms/plugins/Xpressive/ExprSynth.h:57:45: note: suggested alternative:
In file included from /home/travis/build/LMMS/lmms/plugins/Xpressive/ExprSynth.h:30:0,
                 from /home/travis/build/LMMS/lmms/plugins/Xpressive/ExprSynth.cpp:26:
/opt/mingw32/i686-w64-mingw32/include/c++/4.9.4/limits:304:12: note:   'std::numeric_limits'
     struct numeric_limits : public __numeric_limits_base
            ^
In file included from /home/travis/build/LMMS/lmms/plugins/Xpressive/ExprSynth.cpp:26:0:
/home/travis/build/LMMS/lmms/plugins/Xpressive/ExprSynth.h:57:60: error: expected primary-expression before 'float'
  static const int max_float_integer_mod=(1<<numeric_limits<float>::digi
```

**Comment by ArashPartow** [comment]
@tresf fair enough. Perhaps to help @gnudles along, from what the diagnostic is saying it looks like:

- If the build is not in C++11 or after, the **digits** type from numeric_limits will not be available
- If  there's no `using namespace std` then it should be `std::numeric_limits`
- Or it might simply require brackets like so: `(std::numeric_limits<float>::digits)`

**Comment by gnudles** [comment]
@tresf , I hope I didn't messed things up too much, I recreated the fixed commit on the top of lmms:master. I added "std::" before numeric_limits.

**Comment by gnudles** [comment]
BTW, did you know you can use this plugin to play non-western music?
you can set the difference between the keys to be quarter tone like this:
sinew(integrate(440*cent(50*(key-bnote))))

**Comment by tresf** [comment]
@gnudles is this ready to merge?

**Comment by gnudles** [comment]
It looks OK to me, but I didn't tested it yet cause I somewhat can't compile lmms anymore after upgrading ubuntu. it keeps complain on missing XCB in cmake...

**Comment by PhysSong** [comment]
> it keeps complain on missing XCB in cmake...

Can you try `git submodule update --init --recursive? Alternatively, you may install `extra-cmake-modules` instead.

**Comment by tresf** [comment]
@gnudles I think you need:

```bash
sudo apt-get install qtbase5-private-dev libxcb-util0-dev libxcb-keysyms1-dev
```

**Comment by gnudles** [comment]
thanks, now it works. BTW I also get that message:
`Fetched in submodule path 'plugins/LadspaEffect/calf/veal', but it did not contain 816b4d2b7cc20429faf96863d7e8ba1cda48ace8. Direct fetching of that commit failed.
`
so it looks like that commit has been deleted

**Comment by tresf** [comment]
> Direct fetching of that commit failed.

Interesting.  If it compiles, ignore it.  It probably got confused when we renamed the branch from `veal/ladspa` to `veal/ladspa-0.18` in preparation for #3987.

**Pull request merged**
