### PR TITLE
Only filter out <>:"/\|?* while exporting tracks.

### PR DESCRIPTION
**Pull request by Cyp**
This now preserves most characters in exported track names.

### CODE REVIEW

**Comment by Spekular** [comment]
This looks good to me. Technically it misses [a few illegal names on Windows](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file), but they weren't covered before either, aside from ending a filename with a period.

Out of scope for this PR, but it feels like a bad idea to handle this in these classes. Really, all file writing should delegate to a single method that cleans the filename. That would ensure consistent behavior and make sure every fix (like this) applies to every file we save. Plus, it could be a bit larger (to handle Windows's reserved names and OS differences better) without taking up space in the classes that use it.

**Comment by Spekular** [comment]
Oh, but I don't feel like the INSTALL.txt changes  belong in this. I've seen a lot of activity around fixing CI recently so this fix may already be applied or made redundant in some other PR?

**Comment by Cyp** [comment]
I see INSTALL.txt in master does mention submodules. It doesn't mention that cmake can mysteriously fail to generate a Makefile without them, though. Anyway, dropping the INSTALL.txt commit would be fine.

**Comment by Cyp** [comment]
Rebased on latest stable-1.2, and dropped the INSTALL.txt commit…

**Comment by PhysSong** [comment]
Is it safe to be merged?

**Comment by PhysSong** [comment]
It seems like there are some file systems which support limited sets of characters. Should we take care of them?
See https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations for details.

**Comment by Cyp** [comment]
Now also filters 0x00-0x1F and 0x7F. I hope that covers any semi-serious filesystems there that aren't EBCDIC or with a 16-or-less character limit.

**Comment by JohannesLorenz** [comment]
@Cyp what do you think about a global common function for that, that also filters out periods at the end, like @Spekular suggested? I ask because, imagine the next time someone will change the filter in `RenderManager`, they'll surely forget to change it in `InstrumentTrack`.

**Comment by PhysSong** [comment]
> a global common function for that, that also filters out periods at the end

In most cases, we append the file extension at the end. A trailing period is equivalent to the empty file extension(NOT a file without extensions).

**Comment by Cyp** [comment]
It's a global common string (in the last version of the commit), so there shouldn't be anyone changing it in one place but not the other. I don't think there should be any files written without an extension added, so I don't think checking for trailing dots is needed (although it could be added if needed).

**Comment by JohannesLorenz** [comment]
If we save directories, it may be valuable, but it still seems like a seldom case.

**Comment by JohannesLorenz** [comment]
What were your reasons to choose that filter? E.g.:

1. Why allow `!` but filter `?`?
2. Why allow `;` but filter `:`?

**Comment by PhysSong** [comment]
@JohannesLorenz The filter reflects restricted characters in major OSes/file systems.

**Comment by JohannesLorenz** [comment]
OK, then I consider functional and style reviews done. Testing remains.

**Comment by JohannesLorenz** [comment]
I just tested to save a file `aaa<>:"\|?*bbb` from the instrument window's save button. It saved as `\|?*bbb.xpf`, so it

* did not remove the claimed chars `\|?*`
* removed the `aaa` postfix

Can you please check what happens in your local copy?

**Comment by Cyp** [comment]
Same here, but I think it's unrelated to the commit. The `"` seems to have special meaning to the save dialogue box. If trying to save to `/te"st"` in some other program (kwrite), it tries saving to `/st` (with just one `"`, it refuses to even try to save).

If naming the track `aaa<>:"\|?*bbb` and trying to save in the instrument window, it suggests `aaabbb` as the default filename.

**Comment by PhysSong** [comment]
I checked the regular expression, but I couldn't find any issues with it. I could also confirm the issue with the file dialog, using Qt creator.
I think it's ready to merge.

**Review by JohannesLorenz — APPROVED** [review]

**Comment by JohannesLorenz** [comment]
Right, if you don't use `"` in the dialog, it works.

I'll merge, thanks for the contribution!

**Pull request merged**
