### PR TITLE
Update effect plugin icons

### LINKED ISSUE #2388: Logos for effect plugins
Our native effect plug ins can have their own logo. This logo is shown in the plugin browser:

effektbrowser

The file name is "logo.png" and is stored in the plug in source file folder. Almost all of our plug ins got's this little penguin as logo. IMO we need new logos for every plug in.

### PR DESCRIPTION
**Pull request by Umcaruje**
Fixes #2388 
screenshot from 2016-07-26 02 17 17

The icon is based on @RebeccaDeField's cogwheel design for the settings icon.

I think icon would fit a lot better with the new theme.

### CODE REVIEW

**Comment by zonkmachine** [comment]
Good. Maybe fix the apply/cancel icons too?

**Comment by Umcaruje** [comment]
Maybe after #2908 is merged, since that adds the new icons.

**Comment by tresf** [comment]
I'm not sure I agree with the gear although I do prefer it to the penguin.  I doubt this PR is intended for ideas, but some food for thought, also @RebeccaDeField

 * We have a logo for vestige we can use.
 * We could potentially use a dinosaur for LADSPA.
 * We could potentially make a plugin icon (one that is shaped to fit inside our logo) for native effects.

**Comment by Umcaruje** [comment]
>Edit: Just noticed this PR is only for the built-in (native) effects.

Nope, I also replaced the icon for VST and LADSPA's. I like your ideas, gonna design something up.

**Comment by Umcaruje** [comment]
@tresf:
screenshot from 2016-07-27 18 35 13
screenshot from 2016-07-27 18 26 16
screenshot from 2016-07-27 18 36 46

Does this look better?

**Comment by tresf** [comment]
> Does this look better?

I like those a lot.

**Comment by BaraMGB** [comment]
That's really great, @Umcaruje!

**Comment by Umcaruje** [comment]
Glad you like em :smile:

**Comment by BaraMGB** [comment]
But we have to check this with the classic theme, too.

**Comment by Umcaruje** [comment]
>But we have to check this with the classic theme, too.

@BaraMGB:
screenshot from 2016-07-27 19 35 29
screenshot from 2016-07-27 19 35 17
screenshot from 2016-07-27 19 35 05

**Comment by RebeccaDeField** [comment]
I really like this :+1:

**Comment by Umcaruje** [comment]
Merging :+1:

**Pull request merged**
