### PR TITLE
Added a song to data/projects/CoolSongs

### PR DESCRIPTION
**Pull request by SecondFlight**
The song that will (hopefully) be added:
https://soundcloud.com/second_flight/krem-kaakkuja-remix

I also removed a couple spaces that didn't seem like they were needed.

### CODE REVIEW

**Comment by Sti2nd** [comment]
approved by me, lol.

**Comment by Sti2nd** [comment]
Approved by me, lol

**Comment by Spekular** [comment]
Hmm. Are those *annoying fairy* samples legal tho?

**Comment by SecondFlight** [comment]
I removed the external sound effects for this version, but it doesn't really matter since there is no way to include external samples in project files. If I had left them in there, the project file would be broken for everybody else. :3

**Comment by tresf** [comment]
The only reservation I have is that this has double attribution in the title and we're trying to move away from attribution (it's suggestive of non-CC0, and we'd like to keep CC0).

Can @SecondFlight and @grejppi agree to give this track a CC0 title (no attribution?) which reflects the content a little bit (Perhaps Krem Kaakkuja already represents the content, "Cream Cake"?).  Either way, we should switch it to english and possibly remove the artist name, or decide on a single artist name to remain consistent with other "cool songs". :+1:

**Comment by SecondFlight** [comment]
Well it doesn't really make sense to have no attribution, since literally every other song in that folder has an artist name tagged onto it. I don't really mind renaming it to Krem Kaakkuja though, since I have attribution in the project notes.

**Comment by SecondFlight** [comment]
Also, CapDan has a couple remixes in there. Changing it to one artist name wouldn't make too much sense imo. I didn't use the original project file, so putting Greippi's name wouldn't make sense. I didn't make the song with that title, though, so putting my name is misleading as well.

**Comment by SecondFlight** [comment]
As for making it CC0, I just looked up what that is. I'm not too excited about making it CC0, but if it's an absolute requirement then I can manage. :3

I wouldn't mind removing the ND tag. That was simply because it was a remix. I haven't talked to Greippi about licensing, so I guess we could wait to see what he has to say about it.

**Comment by grejppi** [comment]
I'd prefer either by-nd or by-sa. by at most, but CC0... no.

What is with the CC0 obsession here?

**Comment by Sti2nd** [comment]
> What is with the CC0 obsession here?

Well, the idea is that the program LMMS shouldn't promote artists, only credit people that have contributed.

What we should do is settle on a final decision, cause we never did in https://github.com/LMMS/lmms/issues/1273 or on the mailing lists.
- Allow artist name in LMMS or not?
 - If yes, what procedure do you have to go through to get your song in?
 - What licence is allowed?
- No to artist name
 - What procedure do a song have to go through?
 - Implies CC0 (?)

Or alternatively let everyone do as they want now, as before, and delete all demo songs for LMMS2 and then start fresh with rules.

**Comment by Sti2nd** [comment]
Personally I think everything in LMMS from samples to projects should be CC0, you shouldn't have to think about credit when borrowing some instruments, samples or melodies for your own song.

**Comment by SecondFlight** [comment]
That makes sense. Still, there's a couple problems:
1) So we haven't settled on a standard for what licenses are allowed. Since literally nothing in the cool songs folder is CC0, mine would be the exception. Also, I don't mind someone lifting the presets off my song, as long as they don't flat-out steal the entire song and call it theirs. Someone could do it either way, but CC0 gives permission for that.
2)
>LMMS shouldn't promote artists, only credit people that have contributed.
This counts as a contribution.. Right? :3

**Comment by Sti2nd** [comment]
> This counts as a contribution.. Right? :3

One way to view it, yes. It differs, though. When you are credited in the program you get your full name and your email address, while with a song you are getting your artist name and perhaps a link to SoundCloud and other social media?

Tres has the final call here, if he thinks it must be CC0, I would say that too. 
If we can agree on starting fresh with CC0 as requirement for LMMS2 that would be progress in itself.

**Comment by Sti2nd** [comment]
> while with a song you are getting your artist name and perhaps a link to SoundCloud and other social media?

Personally I am not against having an artist name in the title or project notes, as long as it is CC0. People die and change artist names, so one name isn't ruining that much. No links in the project notes!

**Comment by grejppi** [comment]
By this logic this very software itself should be released under CC0 so no one should be worried about crediting when borrowing some code for your own software.

**Comment by Sti2nd** [comment]
> By this logic this very software itself should be released under CC0 so no one should be worried about crediting

You know what, that is kind of how it is... lol. Crediting don't seem to be such a big deal for contributors to LMMS, or have I got the wrong impression?

**Comment by SecondFlight** [comment]
I think it's safe to say that the people who make LMMS don't want someone taking their code and selling it or attempting to take ownership of it. This is why we have licenses (such as GPL) in the first place.

**Comment by SecondFlight** [comment]
Actually Greippi makes a good point.

>Withdrawing my song from this project because of #1687.

>If you want artists to disown their work for the glory of LMMS,
go right ahead.

>This idea sickens me, really.

>There's no way anyone in their mind would tell an artist to give up
their music under CC0 just in order to get it in LMMS distribution.

CC0 would actually require me to disown my work, which is something I'm not going to do.

**Comment by Sti2nd** [comment]
Yes, good point. Just to make it clear, the songs in LMMS aren't CC0 now, and we haven't decided on the future, what we do now is that people using git has an advantage.

**Comment by SecondFlight** [comment]
I would also like to point out that there are already songs that use the song info to display their artist name and links.

>people using git has an advantage.

I asked about submitting a song on IRC and was directed here. It's not big secret or anything :3

**Comment by tresf** [comment]
We can allow it as is, but do understand that we have a long term goal to prevent restrictions on the items we ship with the software.  I won't go over the benefits of this as others have done plenty to explain why.

As far as the name part, I think `John Joe - Track ABC (Remixed by Jane Doe).mmpz` is too long and too advertising, but since we have other current bundled project examples of this, it would be no worse than what we've already done. :)

**Comment by SecondFlight** [comment]
Well, as I said earlier, I can rename it to simply "Krem Kaakkuja" if you would prefer that. If not, then I guess the pull request is ready to be merged :3

**Comment by tresf** [comment]
I want to make very clear that we NEVER want artists such as @grejppi to believe
 1.  We don't appreciate his contributions (not true, we do!!!)<br>
    *-- or --*
 2.  We want to strip artists of rights to his/her own work (not true, we don't!!!)

We aren't trying to steal or anonymize or misappropriate good hard work.  We NEVER want to remove accreditation.  However.... 

What we ship with our software and moving forward what our users can do with it is tremendously important.  We need to embrace our DAW for what it is, and when accreditation and licencing is part of that, we cripple our users and thus our software. Here's a valuable snippet from an email from lmms-devel user "Phil":

> **On Jan 15th 2015, Phil wrote:**  *"Content like sample libraries and finished works are nice, but not on my list of priorities as a new user**.  Finished works are good marketing collateral in terms of being able to point to some examples from the project page (i.e. 'here are just some examples of what LMMS can do' etc... speaking of which: why isn't there a link to the 'Best Of' collection on the LMMS homepage?) but being able to access someone else's work as an LMMS project is of limited value to me and probably not something that most artists would want to do for their better works. A small-ish default sample library (ideally used by the default sample projects) is fine to demonstrate the concept but hardly unique to LMMS. Better to point people to good sources of samples and let them find what suits their needs.  Perhaps a plugin for soundcloud or some other source of samples?"*

... 

>  **On Jan 26 2015 SecondFlight wrote**  I can rename it to simply "Krem Kaakkuja" if you would prefer that. If not, then I guess the pull request is ready to be merged :3

I'm not sure you can.... Since the author of the original work requires accreditation, we don't have much of a choice in this matter... we either reject it outright, or accept it under the combination of yours and his guidelines.  That's how licensing works, the included parties need to grant permission (or wave their rights).

Since @Sti2nd has no issues with the track, I'm inclined to merge this as-is, but I still find the conversation to be valuable, pragmatic, relevant and warranted.  If we don't have a clear vision of the intentions of our software (i.e. components such as bundled projects) then we will ultimately have conflict when trying to determine what and how to include.

Moving forward, I vote we move to a purely CC0 projects with zero mandated attribution (about dialog is ok, but not in LICENSE.TXT or in file name) starting with build 2.0.  This would ultimately start a blank slate in regards to bundled projects, and it would also require someone to gather and organize them.

That means this track can ship with 1.2, but most all of the default tracks will go away in our subsequent releases unless they are revised to accommodate our new guidelines.

**Comment by Sti2nd** [comment]
> I vote we move to a purely CC0 projects with zero mandated attribution (...) starting with build 2.0

Me too. CC0 for samples, projects and presets.

**Comment by badosu** [comment]
@grejppi @tresf @Sti2nd What about removing *all* full songs we have on LMMS right now and re-add them with more conscience and care?

**Comment by tresf** [comment]
> @grejppi @tresf @Sti2nd What about removing all full songs we have on LMMS right now and re-add them with more conscience and care?

Yes, that is the goal I think.  If we have someone that can do it for 1.2, I vote we do it and close out these two pull requests.  If not, we'll have to postpone it for a future release and keep what we have for now.

-Tres

**Comment by Spekular** [comment]
@tresf Should we create a new issue to discuss the licenses of the demo songs? I wrote around ~500 words that try to sum up my stance on this license issue. Perhaps it’ll keep the discussion organized as I won’t need to try to explain it in fragments, or it’ll drown out others with a wall of text about one single opinion that doesn't really matter more than the rest. Do I post it an if so where?

**Comment by Sti2nd** [comment]
@Spekular https://github.com/LMMS/lmms/issues/1693

^^ That one! NOT ANOTHER ONE PLEASE!!! lol

**Comment by SecondFlight** [comment]
>I'm not sure you can.... Since the author of the original work requires accreditation, we don't have much of a choice in this matter...

I don't know if you've opened up the project file, but there is attribution in the project notes, which should be open by default.

**Comment by tresf** [comment]
> I don't know if you've opened up the project file, but there is attribution in the project notes, which should be open by default.

No, I haven't -- only via soundcloud.  It looks like this conversation has grown into a topic of its own.

I'll spend time to discuss this a bit in the adjacent threads and come back here once a decision has been formed.  Feel free to share your thoughts, they are appreciated. :+1:

**Comment by SecondFlight** [comment]
>What about removing all full songs we have on LMMS right now and re-add them with more conscience and care?

I think you will be hard pressed to find good songs whose artists are willing to completely give up their rights to the music. As I said in the other thread:

>I don't really care if someone is messing around with my song, makes something cool, and then uploads it somewhere. That kind of thing can be expected in this situation. What i don't want to do, however, is loose my rights to the original work.

**Comment by Sti2nd** [comment]
> I think you will be hard pressed to find good songs whose artists are willing to completely give up their rights to the music. As I said in the other thread:

i agree, but I think it is not impossible. In my experience many artists tend to have at least one song, that no matter how bad their style and other songs are, that song is extremely interesting. And quite a few artists don't consider themselves good, so I think many would be surprised and happy rather than restricting. You are one of the exceptions to the rule SecondFlight, your songs are always amazing :heart_eyes:

**Comment by SecondFlight** [comment]
Well yes, but I don't really have any other songs that can be included with LMMS since my other songs almost invariably include external samples and/or other external things like soundfonts. I made this one specifically to be 100% LMMS.

**Comment by Sti2nd** [comment]
Perhaps not right now, but I know you have a lot of small demos of sounds and stuff. If you play with one of those it could turn into something longer, though who says demo projects must be full songs?

**Comment by SecondFlight** [comment]
Most of my demos either become full songs, are going to become full songs, or are tests that use melodies that aren't mine, or occasionally ones that I don't particularly like. That, or they're from my FL projects.

**Comment by tresf** [comment]
> who says demo projects must be full songs?

They don't and IMO most shouldn't.  We need a few good tracks for performance and quality testing, but demos are often more useful as small samples, however this conversation is mostly unrelated to this bug report and should be targeted at #1693.

**Comment by tresf** [comment]
> I made this one specifically to be 100% LMMS.

And if no one steps up to tackle the `CC0` discussion, we'll happily merge this.  It's not really fair for this to happen on your track... this convo could have happened when `unfa-Spoken` was added.

I get your point... this track is 100% LMMS and very few are, so take it or leave it.  That is something we have to weigh when we make our decision and thanks for patience while we make up our minds. :)

**Comment by SecondFlight** [comment]
It's alright. I'm in no rush :)

**Comment by SecondFlight** [comment]
Wow, it all showed up here. -_-

Well, sorry :3

**Comment by SecondFlight** [comment]
I've changed the license to CC (BY). It's a sort of a compromise I guess, and it's what I would have put it on anyways if it hadn't been a remix.

**Comment by tresf** [comment]
Thanks @SecondFlight.  I've put some thought into this and decided that there's no reason to holdup your PR for a potentially unsolved long term decision which would affect most of our CoolSongs anyway.

This is going into CoolSongs now but if we have someone ambitious enough to lay down the hammer on `CC0` it may be removed down the road.  Thanks for the tremendous understanding. :+1:

**Comment by badosu** [comment]
Yeah, this is a great track. I am using it exclusively as my new benchmark for testing.

**Comment by SecondFlight** [comment]
:)

**Pull request merged**
