### PR TITLE
Only use libc++ on when using clang *on apple*

### PR DESCRIPTION
**Pull request by Wallacoloo**
When building LMMS with `CC=clang CXX=clang++` on a stock Arch Linux distribution with all LMMS prerequisites plus`clang` and `llvm` installed, the build errors early on when trying to `#include <algorithm>`.

[Some research leads me to believe](http://stackoverflow.com/questions/14972425/should-i-use-libc-or-libstdc) that `libc++` is only needed on Apple, due to some licensing issues around GPLv3. Other than that, the system default should be preferred, by omitting the `-stdlib=xxx` flag.

This change achieves the behavior described in the previous paragraph (thus allowing LMMS to build without errors using clang on Linux systems regardless of which stdlibs the system ships with). Tagging @tresf because it seems that he was the one who added the `-stdlib=libc++` flag.

### CODE REVIEW

**Comment by tresf** [comment]
>  libc++ is only needed on Apple, due to some licensing issues around GPLv3. Other than that, the system default should be preferred, by omitting the -stdlib=xxx flag.

Thanks for clarification.  This shouldn't be a problem.  If you look at 2035ff3 it actually adds the `LMMS_BUILD_CLANG` flag just for this item.  I don't think its bad to keep around, but as I weed through compiler issues I find it difficult to know which behaviors are apple induced and which are clang induced. :+1:

**Comment by Wallacoloo** [comment]
@tresf I haven't done much development on macs, but I do believe it's possible to install gcc using macports (see https://trac.macports.org/wiki/UsingTheRightCompiler ), so I think both `LMMS_BUILD_CLANG` AND `LMMS_BUILD_APPLE` are necessary.

But maybe using `-stdlib=libc++` even on gcc (does it support that?) avoids some runtime pitfalls on OSX?

**Comment by tresf** [comment]
> @tresf I haven't done much development on macs, but I do believe it's possible to install gcc using macports (see https://trac.macports.org/wiki/UsingTheRightCompiler ), so I think both `LMMS_BUILD_CLANG` AND `LMMS_BUILD_APPLE` are necessary.

Possible?  Perhaps.  Ever going to happen?  Not for `c++`.  Here's why https://trac.macports.org/wiki/FAQ#libcpp

This also caused some [grief in regards to `winegcc`](https://github.com/LMMS/lmms/issues/698#issuecomment-42564676) and we still haven't figured that one out.

**Comment by Wallacoloo** [comment]
@tresf Ok. Thanks for clarifying. I went ahead and changed all the conditionals to only use `if (LMMS_BUILD_APPLE)`, as you suggested. I also removed the code that defines `LMMS_BUILD_CLANG`, as nothing makes use of it anymore.

If you're good with that, then we can merge this after the Travis builds finish.

**Comment by tresf** [comment]
:+1:

**Pull request merged**
