### PR TITLE
Deselect FX channels' name text when losing focus

### PR DESCRIPTION
**Pull request by PhysSong**
Fixes https://github.com/LMMS/lmms/issues/3861#issuecomment-334941292.
To reproduce on any platforms:
1. Double-click any FX channel
2. Press Alt + Tab while text is selected
3. Back to LMMS

### CODE REVIEW

**Comment by Sawuare** [comment]
This actually fixes all the bugs in #3861.

**Comment by PhysSong** [comment]
@Sawuare Which version of Qt did you use when testing this? Here's a build with Qt 5.4.2, which is currently used for official releases.
https://github.com/PhysSong/lmms/releases/download/vdummy/lmms-1.2.0-rc5.49-win64.exe

**Comment by Sawuare** [comment]
@PhysSong I used Qt 5.10.1. The other bugs aren't fixed with Qt 5.4.2.

**Comment by Sawuare** [comment]
This doesn't fix https://github.com/LMMS/lmms/issues/3861#issuecomment-334941292 on Windows. The master mixer channel remains selected.

**Comment by PhysSong** [comment]
I'll merge this one and leave #3861 open.

**Pull request merged**
