### PR TITLE
fixes crash on click on compact track label button

### PR DESCRIPTION
**Pull request by BaraMGB**
fixes https://github.com/LMMS/lmms/issues/3454

### CODE REVIEW

**Comment by jasp00** [comment]
It would be better if you unconditionally create and hide `m_renameLineEdit` in the constructor.

**Comment by BaraMGB** [comment]
Thank you for the help, @jasp00

**Comment by jasp00** [comment]
I do not get this workflow. `master` needs this patch too, but a direct commit overrides Travis guard.

**Comment by tresf** [comment]
> I do not get this workflow. master needs this patch too, but a direct commit overrides Travis guard.

In regards to `stable-x.x --> master`, here's some examples of how we've done this in the past... https://github.com/LMMS/lmms/commit/23f720f81be8f670604d862143ffec1476a55870 https://github.com/LMMS/lmms/commit/815a70a68246f5f842d5ba5232e7134e0a8cd91c https://github.com/LMMS/lmms/commit/00cb2b1b67cb0d21e0533f96fde60a64b82f68ff

**Comment by jasp00** [comment]
>here's some examples of how we've done this in the past...

But these still override Travis checks.

**Comment by tresf** [comment]
> But these still override Travis checks.

Are you trying to bypass the CI testing since it's already been merged?  We don't do that and I'm not sure we want to.

**Comment by jasp00** [comment]
Oh, you do sync PRs, such as #1115, #1129, and #1148. How do you exclude patches specific to the stable branch?

**Comment by tresf** [comment]
>  How do you exclude patches specific to the stable branch?

Vesa used to hit these occasionally.  If they don't apply to `master` chances are something has changed and they won't merge due to conflict.

The only way I'm aware is through the manual process of `>>>>>>>>>` conflict-resolution... e.g. https://github.com/LMMS/lmms/commit/8b9868e0e560119945fb3758adb5a78f607a7a9d

e.g. 
```
# Conflicts:
#	src/gui/FileBrowser.cpp
```

**Pull request merged**
