### PR TITLE
Load file names with utf chars

### LINKED ISSUE #1995: [Linux] Double click fails to open project if path contains non-ASCII characters
I'm nurring KX Studio, the file manager is Dolphin (KDE).

When I doubleclick on a project file, LMMS opens but shows this dialog:

lmms-doubleclick-project-load-fail

And creates new session.

Opening the same file via File>Open dialog works fine.

### PR DESCRIPTION
**Pull request by tresf**
File names with non-Latin1 characters won't open on Linux.  This attempts to fix this per http://doc.qt.io/qt-5/qcoreapplication.html#arguments

Fixes #1995

### CODE REVIEW

**Comment by softrabbit** [comment]
Maybe these lines, too?
https://github.com/tresf/lmms/blob/00aaa658c2b11bfa360f2cb7f8c7eeecffaaee8d/src/core/main.cpp#L220
https://github.com/tresf/lmms/blob/00aaa658c2b11bfa360f2cb7f8c7eeecffaaee8d/src/core/main.cpp#L224
https://github.com/tresf/lmms/blob/00aaa658c2b11bfa360f2cb7f8c7eeecffaaee8d/src/core/main.cpp#L249

**Comment by Wallacoloo** [comment]
:+1: Good catch @softrabbit.

**Comment by tresf** [comment]
Thanks guys.  Attempt `#2`.  Feedback welcome. :)

**Comment by eagles051387** [comment]
This is attempting to solve loading file names with utf8 characters. are we
sure they are being saved with utf8 characters?

On Tue, Apr 21, 2015 at 10:42 PM, Tres Finocchiaro <notifications@github.com
> wrote:

> Thanks guys. Attempt #2. Feedback welcome. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LMMS/lmms/pull/1998#issuecomment-94934232>.
>



-- 
Jonathan Aquilina

**Comment by tresf** [comment]
Please test and report back.

**Comment by curlymorphic** [comment]
The code looks good. I do not know enough about filesystems to know if utf8 is universal. I have found the flowing table, Half way down the page..
http://en.wikipedia.org/wiki/Filename

**Comment by softrabbit** [comment]
@curlymorphic, ```fromLocal8Bit()``` will do the conversion according to the system locale, so it should work with any 8-bit character set, not just UTF-8, if the system is set up correctly. And if it's good enough for Qts own command line argument logic, it can't be too bad.

**Comment by curlymorphic** [comment]
> fromLocal8Bit() will do the conversion according to the system locale.

Its all good then.

**Comment by tresf** [comment]
Merging. We can revert  this commit if it causes issues.

**Pull request merged**
