### PR TITLE
Carla build support for Travis

### PR DESCRIPTION
**Pull request by Umcaruje**
Per https://github.com/LMMS/lmms/issues/2549#issuecomment-192942922

### CODE REVIEW

**Comment by tresf** [comment]
@Umcaruje hmm... looks like `carla-git` isn't found for some reason.  I tried on my `Trusty` machine and got the same results.

**Comment by Umcaruje** [comment]
Hmm yeah, I'll talk with falktx over on IRC about this, I wanted to avoid adding the whole kxstudio repos installation process, since I thought it'll slow down the builds

**Comment by Umcaruje** [comment]
@tresf FalkTX says we need Trusty for this.

**Comment by tresf** [comment]
@Umcaruje that makes sense.

I tried forcing it, but I get all sorts of bad news...

Can you ask him if he's has any community members leveraging Travis?  I believe Travis has Trusty available, I'll see what it takes to turn it on.

```
The following packages have unmet dependencies:
 carla-git : Depends: libfontconfig1 (>= 2.9.0) but 2.8.0-3ubuntu9.1 is to be installed
             Depends: libmagic1 (>= 5.12) but 5.09-2ubuntu0.6 is to be installed
             Depends: libqt5core5a (>= 5.0.2) but it is not installable
             Depends: libqt5gui5 (>= 5.0.2) but it is not installable or
                      libqt5gui5-gles (>= 5.0.2) but it is not installable
             Depends: libqt5widgets5 (>= 5.0.2) but it is not installable
             Depends: libstdc++6 (>= 4.8.1) but 4.6.3-1ubuntu5 is to be installed
             Depends: carla-data but it is not going to be installed
             Depends: python3-pyqt4 but it is not going to be installed
             Depends: python3-liblo but it is not going to be installed
             Recommends: python3-pyqt4.qtopengl but it is not installable
             Recommends: python3-rdflib but it is not going to be installed
             Recommends: carla-lv2 but it is not going to be installed
             Recommends: carla-vst but it is not going to be installed
             Recommends: mod-ui but it is not going to be installed
 kxstudio-repos : PreDepends: libc6 (>= 2.19~) but 2.15-0ubuntu10.13 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

**Comment by tresf** [comment]
@Umcaruje can you try this out:

https://docs.travis-ci.com/user/trusty-ci-environment/

Note, we may have to slightly tweak our win32 builds, but it should all be relatively trivial.

**Comment by tresf** [comment]
Also, we may be able to pull this line from `before.install` once we're on Trusty as well: 

```bash
sudo add-apt-repository ppa:kalakris/cmake -y;
```

**Comment by Umcaruje** [comment]
@tresf now libsoundio can't be found...

**Comment by tresf** [comment]
It should be available through that groove URL.

I have a 14.04 box handy, I'll try it out... https://launchpad.net/~andrewrk/+archive/ubuntu/libgroove

**Comment by tresf** [comment]
Ok... @andrewrk doesn't yet offer one... 

https://launchpad.net/~andrewrk/+archive/ubuntu/libgroove?field.series_filter=trusty

So we have to pick either, Carla or libsoundio in our Linux + Travis builds. :+1:

**Comment by Umcaruje** [comment]
Here's an idea how to fix this by @tresf : https://gist.github.com/tresf/f6a6ac7fec369b9a285b

I don't want to work on this PR anymore, adding the whole KXStudio repos to travis will probably slow down the builds, and I think its not worth it, given that the carla code rarely gets changed.

So I'm closing this.

**Pull request closed without merging**
