### PR TITLE
Revert "Proposed fix for 1352  Ifreeze when adding instruments or moving...

### PR DESCRIPTION
**Pull request by diizy**
Reverts LMMS/lmms#1519

Have to revert this because this breaks all instruments that use signals, for some reasn. We need to fix the issue in another way.

### CODE REVIEW

**Comment by diizy** [comment]
@curlymorphic 
had to revert your commit because it was breaking functionality. We need another way to solve the original issue.

**Comment by curlymorphic** [comment]
Will look at this in a bit, i have an idea, been playing with Qt and threads the last couple of days,

**Comment by diizy** [comment]
On 01/04/2015 07:07 PM, Dave wrote:
>
> Will look at this in a bit, i have an idea, been playing with Qt and
> threads the last couple of days,
>

It's probable that there's just some kind of weird race condition
happening, because the hangup is only triggered when the song is playing.

Anyway, creating a new thread seems to be not the right solution for
this... possibly we just need to add the new instrument in some kind of
intermediate container, so the correct thread can then add it to the
TrackContainer at an appropriate time.

**Comment by curlymorphic** [comment]
I could well be wrong, but i think its a case of moving the loaded instrument back to the correct thread, The thread that i am spawning would be the "intermediate container" , handles the loading so there is no blocking on the main thread.

But this is just an idea in me head... i'm probably wrong

**Comment by curlymorphic** [comment]
@diizy 
How do i reproduce the bug? I have tried with all the build in instruments

**Comment by diizy** [comment]
On 01/04/2015 09:32 PM, Dave wrote:
>
> @diizy <https://github.com/diizy>
> How do i reproduce the bug? I have tried with all the build in instruments
>

Easiest on Watsyn: none of the osc volume knobs work.

**Pull request merged**
