### PR TITLE
Update UI 60 times per second.

### LINKED ISSUE #4562: Optimize LMMS To 60FPS
Hello, so LMMS currently runs at a cap of 30FPS for work flow but it would be nice if it was Optimize at 60FPS, that way we could experience a buttery smooth feel and look in LMMS.

### PR DESCRIPTION
**Pull request by karmux**
Fixes #4562.

### CODE REVIEW

**Comment by PhysSong** [comment]
Merge?

**Comment by SecondFlight** [comment]
I remember doing this on my own fork, and I noticed that the EQ visualizer seemed to behave somewhat differently. Has anybody else noticed this? I didn't see it as a problem, but I might have missed something.

**Comment by PhysSong** [comment]
> the EQ visualizer seemed to behave somewhat differently.

I think the falloff in `EqFader::updateVuMeters` should be adjusted to reflect the refresh rate change.

**Comment by PhysSong** [comment]
Also in `EqSpectrumView::paintEvent`. The exact value should be about `1.06266`, but I suggest slightly larger value around to bring some visual effects.

**Comment by karmux** [comment]
I will look into it in the weekend.

**Comment by karmux** [comment]
Adjusted also falloff of mixer faders (`FxMixerView::updateFaders`). Used value `1.07`.

**Comment by SecondFlight** [comment]
I can't think of any other possible issues with this. The fact that it's not actually 60 fps still feels wrong to me (62.5 fps, assuming the timer is accurate), but I doubt this will cause any actual issues.

Merge?

**Comment by PhysSong** [comment]
I'm not sure if this one is okay for `stable-1.2`, but the change itself looks good to me.

**Comment by SecondFlight** [comment]
I would hate to defer something so simple and beneficial to 1.3, but we are on feature freeze. It's your call, @PhysSong, I won't complain if we have to defer.

**Comment by karmux** [comment]
It's more like a fine-tuning than feature.

**Comment by PhysSong** [comment]
Merging into `stable-1.2` because we can safely revert it if it causes any issues. :tractor:

**Comment by musikBear** [comment]
Any win Test binaries?

**Comment by PhysSong** [comment]
@musikBear This will be part of RC7. So please wait a few days. :)

**Comment by musikBear** [comment]
@PhysSong Just want to let you know, that RC7 runs fine on my old Tube-monitor 👍

**Comment by DomClark** [comment]
Should `TimeLineWidget` be updated too? This looks like a 20 fps timer to me: https://github.com/LMMS/lmms/blob/d8fb07ff52ee87a290ad7e69d0851cfb1c20d261/src/gui/TimeLineWidget.cpp#L96

**Comment by PhysSong** [comment]
@DomClark Nice catch!

**Pull request merged**
