### PR TITLE
Fix job queue crash

### LINKED ISSUE #777: Segfault when job queue is full
Just documenting the backtrace here for future reference

```
#0  operator= (this=0xb32ca1a0, value=0xaac05e90) at /usr/include/qt4/QtCore/qbasicatomic.h:182
No locals.
#1  operator= (value=0xaac05e90, this=0xb32ca1a0) at /usr/include/qt4/QtCore/qatomic.h:145
No locals.
#2  MixerWorkerThread::JobQueue::addJob (this=0x82ad700, _job=0xaac05e90)
    at /home/vesa/tmp/lmms-ui/src/core/MixerWorkerThread.cpp:53
No locals.
#3  0x08173e57 in addJob (_job=<optimized out>) at /home/vesa/tmp/lmms-ui/include/MixerWorkerThread.h:86
No locals.
#4  fillJobQueue<QList<PlayHandle*> > (_opMode=MixerWorkerThread::JobQueue::Static, _vec=...)
    at /home/vesa/tmp/lmms-ui/include/MixerWorkerThread.h:98
        it = <optimized out>
#5  Mixer::renderNextBuffer (this=0x89d1ed8) at /home/vesa/tmp/lmms-ui/src/core/Mixer.cpp:380
        timer = {begin = {tv_sec = 1401133078, tv_usec = 755525}}
        it_rem = {i = 0xaac03298}
        last_metro_pos = {<MidiTime> = {m_ticks = -1, static s_ticksPerTact = 192}, m_timeLine = 0x0, 
          m_timeLineUpdate = true, m_currentFrame = 0}
        p = {<MidiTime> = {m_ticks = <optimized out>, static s_ticksPerTact = 192}, m_timeLine = <optimized out>, 
          m_timeLineUpdate = 152, m_currentFrame = 0}
#6  0x08174437 in Mixer::fifoWriter::run (this=0x8e9ed80) at /home/vesa/tmp/lmms-ui/src/core/Mixer.cpp:952
        buffer = 0xaac020e8
        b = <optimized out>
#7  0xb696eeb0 in ?? () from /usr/lib/i386-linux-gnu/libQtCore.so.4
No symbol table info available.
#8  0xb7701d4c in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
No symbol table info available.
#9  0xb6186bae in clone () from /lib/i386-linux-gnu/libc.so.6
No symbol table info available.
```

### PR DESCRIPTION
**Pull request by lukas-w**
* Don't add jobs when job queue is full
* Icrease job queue size from 1024 to 8192

Closes #777.

### CODE REVIEW

**Comment by Wallacoloo** [comment]
It seems weird to let `m_queueSize` grow beyond `JOB_QUEUE_SIZE` (i.e. sizeof(m_items)). But the only other way I see to avoid that is to use `testAndSetOrdered` in a loop, which is arguably less intuitive (and more costly).

**Comment by lukas-w** [comment]
@Wallacoloo How about renaming `m_queueSize` to something like `m_queueIndex` or `m_writeIndex`, would that make it less contradictory?

**Comment by Wallacoloo** [comment]
`m_numJobsQueued` or either of the ones you suggested would be a little better than `m_queueSize`. Not worth spending much time nitpicking over a variable name though.

**Comment by lukas-w** [comment]
Renamed to `m_writeIndex`.

**Pull request merged**
