### PR TITLE
Refactor MidiTime implementation

### PR DESCRIPTION
**Pull request by Wallacoloo**
I broke this down into some smaller commits so that it might be easier to follow.

Behaviorally, nothing has really changed. Structurally, I tried to move most of the logic that dealt with manipulating midi time values out of the Song class and into the MidiTime class. Then I separated MidiTime.h into a header and source file, rather than having its implementation in the header as before.

### CODE REVIEW

**Comment by tresf** [comment]
This is a nice addition.

The only constructive criticism I can offer (non-technical) are that the 4 newlines between functions isn't honored and that the variable `_tpt` should be renamed without the underscore but those are minor and were simply carried over from the previous version.

**Comment by Wallacoloo** [comment]
@tresf both of those things should now be fixed.

Although I'd hesitate to call the newline changes a fix, personally - yuck! :P

**Comment by tresf** [comment]
> Although I'd hesitate to call the newline changes a fix, personally - yuck! :P

Yeah, I've intentionally ignored that convention on several occasions myself. Oh well... :beers:

**Comment by Lukas-W** [comment]
That makes three of us. Let's drop that rule.

**Comment by Spekular** [comment]
Late, and I rarely contribute, but yes please! Four newlines is ridiculous
:P

**Comment by Wallacoloo** [comment]
Well given the amount of input here... I switched the spacing back to how it was before (primarily 2 blank lines between functions, but related functions like constructors that differ only by signature are only separated by 1 blank line).

**Comment by Wallacoloo** [comment]
Should we merge, or hold off on this?

**Comment by midi-pascal** [comment]
@Wallacoloo :+1:

**Comment by tresf** [comment]
Please do. :)

**Pull request merged**
