### PR TITLE
Mixer update

### PR DESCRIPTION
**Pull request by M374LX**
Separate the metronome from the mixer
Make the mixer fully independent from the GUI
Clean up mixer's constructor

### CODE REVIEW

**Comment by M374LX** [comment]
Another possibility is to create a class for the metronome.

**Comment by diizy** [comment]
Why are you removing spaces from existing parentheses?

It was decided to drop the requirement for spaces, so you no longer have to add them if you don't want to in your own code, but that doesn't meant they need to be removed from existing code.

**Comment by M374LX** [comment]
The spaces removal was actually because some topics in the coding conventions are not clear, as in issue #1826.

Do you prefer to undo the spaces removal?

**Comment by M374LX** [comment]
An even better idea is to move the code deciding when to play a metronome sample to `Song`. Does anyone here disagree?

**Comment by tresf** [comment]
@M374LX the spaces in the parenthesis isn't a big deal here but it makes it harder to see the actual change.  We'll need a rebase and some testing prior to merge.  Could you simplify the PR a bit and squash the commits back into one?  If it's easier, feel free to open a new PR.  Thanks for the help on this. :+1:

**Comment by M374LX** [comment]
@tresf 
After a better analysis, I found that better changes can be done. Perhaps the mixer samples can be handled by the `Song` class.

I have plans to check this when possible.

**Comment by tresf** [comment]
Thanks kindly for the quick response.  I hope you don't mind I'll close this out until the new work is complete.  Please open a new PR when you feel it is ready.

The `coupling between core and UI` bug is a good placeholder for now and since the conversation above is mostly in regards to coding conventions, we should be safe to start a new PR when its ready. :)

**Pull request closed without merging**
